/* Grade 1, second set: the equal sign, word problems, properties, two-digit
   comparison, adding within 100, graphs, coins, shapes, halves and fourths,
   plus enrichment (odd/even, first factors, machines, growing patterns, logic
   puzzles and simple combinatorics). Sentences stay short and concrete;
   numbers stay within 100. */
export const G1_MORE_BANKS = {
"g1-equals": [
{sec:"L",type:"in",q:"5 + 3 = __ + 6. What number goes in the blank?",ans:2,hint:"Work out the left side first.",
 expl:"5 + 3 = 8. The right side must also be 8, and 2 + 6 = 8. The blank is 2."},
{sec:"L",type:"mc",q:"Which number sentence is TRUE?",mono:true,opts:["4 + 2 = 6","4 + 2 = 8","4 + 2 = 5"],a:0,
 expl:"4 + 2 makes 6, so 4 + 2 = 6 is the true one."},
{sec:"L",type:"mc",q:"What does the = sign mean?",
 opts:["Both sides are the same amount","The answer comes next","Add the numbers"],a:0,
 expl:"The equal sign says the two sides are worth the same. It is like a balanced scale."},
{sec:"L",type:"in",q:"7 = 3 + __. What number goes in the blank?",ans:4,
 expl:"3 and 4 make 7, so the blank is 4. The equal sign can come first."},
{lvl:2,sec:"L",type:"in",q:"__ + 4 = 10 − 2. What number goes in the blank?",ans:4,hint:"Find what 10 − 2 makes first.",
 expl:"10 − 2 = 8. Then 4 + 4 = 8, so the blank is 4."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY number sentence that is true.",mono:true,
 opts:["6 = 6","3 + 4 = 4 + 3","5 + 1 = 7","9 − 2 = 6"],aMulti:[0,1],
 expl:"6 = 6 is true. 3 + 4 and 4 + 3 both make 7, so that is true. 5 + 1 is 6 and 9 − 2 is 7, so those are false."},
{lvl:3,sec:"L",type:"in",q:"A scale is balanced. One side has 6 and 5. The other side has 8 and a box. What is in the box?",
 ans:3,hint:"Both sides must weigh the same.",expl:"6 + 5 = 11. The other side needs 11 too. 8 + 3 = 11, so the box holds 3."},
{lvl:3,sec:"L",type:"mc",q:"Which number makes this true?  9 − __ = 2 + 3",mono:true,opts:["4","5","6"],a:0,
 hint:"Work out 2 + 3 first.",expl:"2 + 3 = 5. Then 9 − 4 = 5, so the missing number is 4."}
],

"g1-wordprob": [
{sec:"L",type:"in",q:"Amara has 8 apples. She gives 3 to a friend. How many apples does she have now?",ans:5,
 expl:"Giving away means take away. 8 − 3 = 5 apples."},
{sec:"L",type:"in",q:"Kenji has 6 cars. He gets 5 more. How many cars does he have now?",ans:11,
 expl:"Getting more means add. 6 + 5 = 11 cars."},
{sec:"L",type:"in",q:"There are 9 birds. Some fly away. 4 are left. How many flew away?",ans:5,hint:"What do you take from 9 to leave 4?",
 expl:"9 − 4 = 5, so 5 birds flew away."},
{sec:"L",type:"mc",q:"12 ducks swim. 5 leave. Which number sentence finds how many are left?",mono:true,
 opts:["12 − 5 = ?","12 + 5 = ?","5 − 12 = ?"],a:0,
 expl:"Ducks leaving means take away. Start with 12 and take away 5: 12 − 5 = 7."},
{lvl:2,sec:"L",type:"in",q:"Some cats sit on a wall. 6 more come. Now there are 14 cats. How many were there at first?",ans:8,
 hint:"Take the 6 back off.",expl:"14 − 6 = 8. There were 8 cats at first."},
{lvl:2,sec:"L",type:"in",q:"Zainab has some coins. She finds 4 more. Now she has 11. How many did she start with?",ans:7,
 expl:"11 − 4 = 7. She started with 7 coins."},
{lvl:3,sec:"L",type:"in",q:"Lior has 5 more marbles than Tomas. Lior has 13. How many marbles does Tomas have?",ans:8,
 hint:"Tomas has fewer.",expl:"Tomas has 5 fewer than 13. 13 − 5 = 8 marbles."},
{lvl:3,sec:"L",type:"in",q:"15 children play. 6 are on the slide. The rest are on swings. How many more are on swings than the slide?",
 ans:3,hint:"First find how many are on the swings.",expl:"15 − 6 = 9 on the swings. 9 − 6 = 3 more on the swings."},
{lvl:2,sec:"L",type:"multi",q:"Sofia has 9 pears. She eats some. 4 are left. Select EVERY sentence that helps find how many she ate.",mono:true,
 opts:["9 − ? = 4","4 + ? = 9","9 + 4 = ?"],aMulti:[0,1],
 expl:"She ate the difference between 9 and 4. Both 9 − ? = 4 and 4 + ? = 9 give 5. Adding 9 and 4 does not."},
],

"g1-props": [
{sec:"L",type:"in",q:"4 + 7 = 11. What is 7 + 4?",ans:11,hint:"Same two numbers, other order.",
 expl:"You can add in any order and get the same total. 7 + 4 = 11."},
{sec:"L",type:"mc",q:"Which has the same answer as 3 + 9?",mono:true,opts:["9 + 3","9 − 3","3 + 3"],a:0,
 expl:"Swapping the order does not change a sum. 3 + 9 and 9 + 3 both make 12."},
{sec:"L",type:"in",q:"2 + 8 + 5 = ?",ans:15,hint:"Make a ten first.",
 expl:"2 + 8 = 10, then 10 + 5 = 15."},
{sec:"L",type:"mc",q:"Which is the easiest way to add 6 + 4 + 7?",
 opts:["Make 10 with 6 + 4 first","Add 4 + 7 first","Add 7 + 6 first"],a:0,
 expl:"6 + 4 = 10, and 10 + 7 = 17 is easy. You can add in any order, so pick the pair that makes ten."},
{lvl:2,sec:"L",type:"in",q:"9 + 3 + 1 = ?",ans:13,hint:"Which two numbers make ten?",
 expl:"9 + 1 = 10, then 10 + 3 = 13."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY sum that equals 5 + 8.",mono:true,
 opts:["8 + 5","5 + 8 + 0","8 − 5","5 + 5"],aMulti:[0,1],
 expl:"5 + 8 = 13. 8 + 5 is 13 too, and adding 0 changes nothing. 8 − 5 is 3 and 5 + 5 is 10."},
{lvl:3,sec:"L",type:"in",q:"8 + 6 + 2 + 4 = ?",ans:20,hint:"Find pairs that make 10.",
 expl:"8 + 2 = 10 and 6 + 4 = 10. Together that is 20."},
{lvl:3,sec:"L",type:"mc",q:"Wei says 5 + 9 is not the same as 9 + 5. Is Wei right?",
 opts:["No, both make 14","Yes, 5 + 9 is bigger","Yes, 9 + 5 is bigger"],a:0,
 expl:"Order does not matter when you add. 5 + 9 = 14 and 9 + 5 = 14, so Wei is not right."}
],

"g1-compare2": [
{sec:"N",type:"mc",q:"Which is bigger, 47 or 52?",opts:["52","47","They are equal"],a:0,hint:"Look at the tens first.",
 expl:"52 has 5 tens and 47 has only 4 tens. So 52 is bigger."},
{sec:"N",type:"mc",q:"Which sign makes this true?  36 __ 63",mono:true,opts:["<",">","="],a:0,
 expl:"36 is less than 63, so the sign is <. The small end points to the smaller number."},
{sec:"N",type:"in",q:"Type the biggest of these numbers: 71, 17, 77.",ans:77,
 expl:"71 and 77 both have 7 tens, but 77 has more ones. 77 is the biggest."},
{sec:"N",type:"mc",q:"Which sign makes this true?  85 __ 58",mono:true,opts:[">","<","="],a:0,
 expl:"85 has 8 tens and 58 has 5 tens. 85 is greater, so the sign is >."},
{lvl:2,sec:"N",type:"order",q:"Put these numbers in order from smallest to largest.",
 items:["43","34","40","54"],ansOrder:["34","40","43","54"],
 expl:"34 has the fewest tens. Then 40 and 43 both have 4 tens, and 40 has fewer ones. 54 is last."},
{lvl:2,sec:"N",type:"mc",q:"68 and 62 both have 6 tens. Which is bigger, and why?",
 opts:["68, it has more ones","62, it has fewer ones","They are the same"],a:0,
 expl:"When the tens match, look at the ones. 8 ones is more than 2 ones, so 68 is bigger."},
{lvl:3,sec:"N",type:"in",q:"I am a 2-digit number. My tens digit is 5. I am bigger than 57 and smaller than 59. What am I?",ans:58,
 hint:"Count on from 57.",expl:"The only number between 57 and 59 is 58. It has 5 tens, so it fits."},
{lvl:3,sec:"N",type:"multi",q:"Select EVERY number that is bigger than 46.",opts:["64","49","46","39"],aMulti:[0,1],
 expl:"64 has more tens than 46. 49 has the same tens but more ones. 46 is equal, not bigger, and 39 is smaller."}
],

"g1-add100": [
{sec:"N",type:"in",q:"23 + 5 = ?",ans:28,hint:"Only the ones change.",expl:"3 ones + 5 ones = 8 ones. 23 + 5 = 28."},
{sec:"N",type:"in",q:"40 + 30 = ?",ans:70,expl:"4 tens + 3 tens = 7 tens. 40 + 30 = 70."},
{sec:"N",type:"in",q:"58 − 6 = ?",ans:52,expl:"8 ones − 6 ones = 2 ones. 58 − 6 = 52."},
{sec:"N",type:"mc",q:"What is 34 + 10?",opts:["44","35","24"],a:0,
 expl:"Adding 10 adds one more ten. 3 tens become 4 tens: 44."},
{lvl:2,sec:"N",type:"in",q:"36 + 7 = ?",ans:43,hint:"Make the next ten first.",
 expl:"36 + 4 = 40, then 40 + 3 = 43."},
{lvl:2,sec:"N",type:"in",q:"70 − 20 = ?",ans:50,expl:"7 tens take away 2 tens leaves 5 tens. 70 − 20 = 50."},
{lvl:2,sec:"N",type:"in",q:"Aisha has 25 shells. She finds 20 more. How many shells does she have now?",ans:45,
 expl:"25 + 20 = 45. Only the tens change: 2 tens and 2 more tens make 4 tens."},
{lvl:3,sec:"N",type:"in",q:"Nadia has 32 stickers. She gets 40 more, then gives away 5. How many does she have now?",ans:67,
 hint:"Add first, then take away.",expl:"32 + 40 = 72. Then 72 − 5 = 67 stickers."},
{lvl:3,sec:"N",type:"in",q:"A jar has 45 beads. Oluwaseun adds 30. How many more beads are needed to make 100?",ans:25,
 hint:"Find how many are in the jar now.",expl:"45 + 30 = 75 beads. 75 + 25 = 100, so 25 more are needed."},
{lvl:2,sec:"N",type:"order",q:"Put these sums in order from smallest to largest.",mono:true,
 items:["20 + 30","41 + 5","60 − 20","15 + 7"],ansOrder:["15 + 7","60 − 20","41 + 5","20 + 30"],
 expl:"They make 50, 46, 40 and 22. From smallest: 22, 40, 46, 50."},
],

"g1-tenmore": [
{sec:"N",type:"in",q:"What is 10 more than 34?",ans:44,hint:"Only the tens digit changes.",
 expl:"10 more adds one ten. 34 becomes 44."},
{sec:"N",type:"in",q:"What is 10 less than 67?",ans:57,expl:"10 less takes away one ten. 67 becomes 57."},
{sec:"N",type:"mc",q:"Which digit changes when you add 10 to 52?",opts:["The tens digit","The ones digit","Both digits"],a:0,
 expl:"Adding 10 adds one more ten. 52 becomes 62. The ones digit stays 2."},
{sec:"N",type:"in",q:"What is 10 more than 80?",ans:90,expl:"8 tens plus 1 more ten is 9 tens. That is 90."},
{lvl:2,sec:"N",type:"in",q:"Start at 46. Count up by ten two times. What number do you land on?",ans:66,hint:"Add ten, then add ten again.",
 expl:"46 + 10 = 56, and 56 + 10 = 66."},
{lvl:2,sec:"N",type:"mc",q:"Which number is 10 less than 90?",opts:["80","89","91","100"],a:0,
 expl:"Taking one ten from 9 tens leaves 8 tens. 10 less than 90 is 80."},
{lvl:3,sec:"N",type:"in",q:"Ingrid says 10 more than her number is 73. What is 10 less than her number?",ans:53,
 hint:"Find her number first.",expl:"Her number is 73 − 10 = 63. Then 10 less than 63 is 53."},
{lvl:3,sec:"N",type:"order",q:"Put these in order from smallest to largest.",
 items:["10 more than 25","10 less than 25","25","10 more than 35"],
 ansOrder:["10 less than 25","25","10 more than 25","10 more than 35"],
 expl:"They are 35, 15, 25 and 45. In order: 15, 25, 35, 45."}
],

"g1-graphs": [
{sec:"S",type:"mc",q:"A picture graph shows pets. Dogs: 4 pictures. Cats: 6 pictures. Fish: 2 pictures. Which pet has the most?",
 opts:["Cats","Dogs","Fish"],a:0,expl:"More pictures means more pets. Cats have 6, the most."},
{sec:"S",type:"in",q:"A bar graph shows fruit. Apples: 5. Bananas: 3. How many more apples than bananas?",ans:2,
 expl:"5 − 3 = 2. The apple bar is 2 taller."},
{sec:"S",type:"in",q:"Each picture stands for 1 child. Red: 3 pictures. Blue: 5. Green: 4. How many children in all?",ans:12,
 hint:"Add all three groups.",expl:"3 + 5 + 4 = 12 children."},
{sec:"S",type:"mc",q:"A bar graph shows how children get to school. What does the tallest bar show?",
 opts:["The way most children use","The way fewest children use","The total of all the bars"],a:0,
 expl:"A taller bar means a bigger count. The tallest bar is the way most children use."},
{lvl:2,sec:"S",type:"in",q:"A weather graph shows sunny 7 days, rainy 2 days, cloudy 4 days. How many days were NOT sunny?",ans:6,
 hint:"Add the rainy and cloudy days.",expl:"Rainy and cloudy days: 2 + 4 = 6 days were not sunny."},
{lvl:2,sec:"S",type:"mc",q:"On a bar graph, 6 children chose pizza and 6 chose pasta. Which is true?",
 opts:["The bars are the same height","Pizza has a taller bar","Pasta has a taller bar"],a:0,
 expl:"Both counts are 6, so both bars are the same height."},
{lvl:3,sec:"S",type:"in",q:"A graph shows 12 votes in all. Red got 5 and blue got 4. How many votes did green get?",ans:3,
 hint:"Add red and blue first.",expl:"5 + 4 = 9 votes for red and blue. 12 − 9 = 3 votes for green."},
{lvl:3,sec:"S",type:"in",q:"A graph shows books read. Femi: 9. Mei: 3. Leila: 5. How many more did Femi read than Mei and Leila together?",
 ans:1,hint:"Add Mei and Leila first.",expl:"Mei and Leila read 3 + 5 = 8. Femi read 9, and 9 − 8 = 1 more."},
{lvl:2,sec:"S",type:"multi",q:"A picture graph: dogs 5, cats 3, birds 5, fish 1. Select EVERY pet with the most pictures.",
 opts:["Dogs","Birds","Cats","Fish"],aMulti:[0,1],
 expl:"Dogs and birds both have 5 pictures. That is the most, so they tie."},
],

"g1-coins": [
{sec:"M",type:"in",q:"How many cents is a dime worth?",ans:10,expl:"A dime is worth 10 cents."},
{sec:"M",type:"in",q:"How many cents is a nickel worth?",ans:5,expl:"A nickel is worth 5 cents."},
{sec:"M",type:"mc",q:"Which coin is worth the most?",opts:["Quarter","Dime","Nickel","Penny"],a:0,
 expl:"A quarter is 25 cents. A dime is 10, a nickel is 5 and a penny is 1."},
{sec:"M",type:"in",q:"How many cents are 2 dimes and 1 penny worth?",ans:21,hint:"Count the dimes first.",
 expl:"2 dimes are 20 cents. Add 1 cent for the penny: 21 cents."},
{lvl:2,sec:"M",type:"in",q:"Arjun has 1 quarter and 1 nickel. How many cents does he have?",ans:30,
 expl:"25 + 5 = 30 cents."},
{lvl:2,sec:"M",type:"mc",q:"Which set of coins is worth 20 cents?",opts:["2 dimes","2 nickels","1 dime and 1 penny"],a:0,
 expl:"2 dimes are 10 + 10 = 20 cents. 2 nickels are only 10, and a dime and penny are 11."},
{lvl:3,sec:"M",type:"in",q:"Noor has 3 nickels and 2 dimes. How many cents in all?",ans:35,hint:"Count each kind of coin, then add.",
 expl:"3 nickels are 15 cents. 2 dimes are 20 cents. 15 + 20 = 35 cents."},
{lvl:3,sec:"M",type:"in",q:"Elias wants 50 cents. He has 1 quarter and 1 dime. How many more cents does he need?",ans:15,
 expl:"25 + 10 = 35 cents. 50 − 35 = 15 more cents."},
{lvl:3,sec:"M",type:"mc",q:"Which is worth more, 3 dimes or 5 nickels?",opts:["3 dimes","5 nickels","They are equal"],a:0,
 expl:"3 dimes are 30 cents. 5 nickels are 25 cents. 3 dimes are worth more."},
{lvl:2,sec:"M",type:"order",q:"Put these coins in order from least value to most value.",
 items:["Dime","Penny","Quarter","Nickel"],ansOrder:["Penny","Nickel","Dime","Quarter"],
 expl:"A penny is 1 cent, a nickel 5, a dime 10 and a quarter 25."},
],

"g1-attrib": [
{sec:"G",type:"in",q:"How many sides does a triangle have?",ans:3,expl:"Every triangle has 3 straight sides and 3 corners."},
{sec:"G",type:"mc",q:"Which is something that ALL squares must have?",opts:["4 equal sides","A red colour","A big size"],a:0,
 expl:"A square must have 4 equal sides and square corners. Colour and size can be anything."},
{sec:"G",type:"mc",q:"A shape has 4 sides and 4 corners. Which could it be?",opts:["A rectangle","A triangle","A circle"],a:0,
 expl:"A rectangle has 4 sides and 4 corners. A triangle has 3 and a circle has none."},
{sec:"G",type:"in",q:"How many corners does a hexagon have?",ans:6,expl:"A hexagon has 6 sides, so it has 6 corners."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY thing that makes a shape a triangle.",
 opts:["3 straight sides","3 corners","Being blue","Being small"],aMulti:[0,1],
 expl:"A triangle needs 3 straight sides and 3 corners. Its colour and size do not matter."},
{lvl:2,sec:"G",type:"mc",q:"Which shape has NO corners?",opts:["Circle","Square","Triangle"],a:0,
 expl:"A circle is round all the way. It has no straight sides and no corners."},
{lvl:3,sec:"G",type:"mc",q:"Chioma draws a big red rectangle. Ravi draws a small blue one. Are both shapes rectangles?",
 opts:["Yes, colour and size do not matter","No, one is too small","No, they are different colours"],a:0,
 expl:"A rectangle is about sides and corners, not colour or size. Both are rectangles."},
{lvl:3,sec:"G",type:"mc",q:"A shape has 3 straight sides. One side is much longer than the others. What is it?",
 opts:["A triangle","A rectangle","A hexagon"],a:0,
 expl:"Any shape with 3 straight sides is a triangle. The sides do not need to match."}
],

"g1-compose": [
{sec:"G",type:"mc",q:"Two squares of the same size are joined side by side. What shape do they make?",
 opts:["A rectangle","A triangle","A circle"],a:0,
 expl:"Two squares in a row make a long shape with 4 sides and square corners: a rectangle."},
{sec:"G",type:"in",q:"A square is cut from one corner to the other corner. How many triangles do you get?",ans:2,
 expl:"The cut splits the square into 2 triangles."},
{sec:"G",type:"mc",q:"Which two shapes can be put together to make a square?",
 opts:["Two triangles","Two circles","A circle and a triangle"],a:0,
 expl:"Two matching triangles fit along their long sides to make a square. Circles have no flat sides."},
{sec:"G",type:"in",q:"Mei uses 6 squares to make a rectangle 2 rows tall. How many squares are in each row?",ans:3,
 hint:"Share 6 into 2 equal rows.",expl:"6 squares in 2 rows is 3 in each row: 3 + 3 = 6."},
{lvl:2,sec:"G",type:"in",q:"It takes 6 small triangles to make a hexagon. How many triangles for 2 hexagons?",ans:12,
 expl:"6 for one hexagon and 6 for another. 6 + 6 = 12 triangles."},
{lvl:2,sec:"G",type:"mc",q:"Two trapezoids are joined along their long sides. What shape can they make?",
 opts:["A hexagon","A circle","A triangle"],a:0,
 expl:"Each trapezoid is half of a hexagon. Two of them together make a hexagon."},
{lvl:3,sec:"G",type:"in",q:"Sofia builds a big square from small squares. It has 3 rows with 3 in each row. How many small squares?",ans:9,
 hint:"Count row by row.",expl:"3 + 3 + 3 = 9 small squares."},
{lvl:3,sec:"G",type:"in",q:"A big rectangle is made from 2 rows of 5 squares. Leila takes away 3 squares. How many are left?",ans:7,
 hint:"Find the whole first.",expl:"2 rows of 5 is 10 squares. 10 − 3 = 7 squares are left."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY shape you can make from two matching triangles.",
 opts:["A square","A bigger triangle","A circle"],aMulti:[0,1],
 expl:"Two matching triangles can join to make a square, or line up to make a bigger triangle. They cannot make a round circle."},
],

"g1-shares": [
{sec:"G",type:"mc",q:"A pizza is cut into 2 equal parts. What is each part called?",opts:["A half","A fourth","A whole"],a:0,
 expl:"Two equal parts are halves. Each part is one half."},
{sec:"G",type:"in",q:"A cake is cut into fourths. How many pieces are there?",ans:4,expl:"Fourths means 4 equal pieces."},
{sec:"G",type:"mc",q:"Which shows halves?",
 opts:["A circle cut into 2 equal parts","A circle cut into a big part and a small part","A circle cut into 4 equal parts"],a:0,
 expl:"Halves must be 2 parts of the same size. Four parts are fourths, and unequal parts are not halves."},
{sec:"G",type:"mc",q:"Which is bigger: a half of a sandwich or a fourth of the same sandwich?",opts:["A half","A fourth","The same"],a:0,
 expl:"Cutting into more pieces makes each piece smaller. A half is bigger than a fourth."},
{lvl:2,sec:"G",type:"in",q:"Hana eats 1 fourth of a pie. How many fourths are left?",ans:3,hint:"A whole pie is 4 fourths.",
 expl:"4 fourths make the whole pie. 4 − 1 = 3 fourths are left."},
{lvl:2,sec:"G",type:"mc",q:"A square is cut into 4 equal parts. What is each part?",opts:["A quarter","A half","A third"],a:0,
 expl:"Four equal parts are quarters, also called fourths."},
{lvl:3,sec:"G",type:"in",q:"Elias cuts a sandwich into halves. Then he cuts each half in half again. How many equal pieces?",ans:4,
 hint:"Each half becomes 2 pieces.",expl:"2 halves, and each becomes 2 pieces. 2 + 2 = 4 equal pieces, which are fourths."},
{lvl:3,sec:"G",type:"mc",q:"Zainab and 3 friends share a pie equally. What part does each person get?",opts:["A fourth","A half","A third"],a:0,
 hint:"Count how many people share.",expl:"Zainab plus 3 friends is 4 people. 4 equal shares are fourths."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY name for one of 2 equal parts of a pizza.",
 opts:["A half","One of two equal shares","A fourth","A quarter"],aMulti:[0,1],
 expl:"Two equal parts are halves, so each is a half, or one of two equal shares. Fourths and quarters are 1 of 4 parts."},
],

"g1-evenodd": [
{sec:"T",type:"mc",q:"Is 14 even or odd?",opts:["Even","Odd"],a:0,
 expl:"14 can be split into two equal groups of 7. So 14 is even."},
{sec:"T",type:"mc",q:"Is 37 even or odd?",opts:["Odd","Even"],a:0,
 expl:"37 ends in 7. Numbers ending in 1, 3, 5, 7 or 9 are odd."},
{sec:"T",type:"mc",q:"Which digit tells you if a number is even?",opts:["The ones digit","The tens digit","Both digits"],a:0,
 expl:"Only the ones digit matters. If it is 0, 2, 4, 6 or 8 the number is even."},
{sec:"T",type:"in",q:"What is the biggest even number less than 100?",ans:98,hint:"Count back from 100.",
 expl:"99 is odd. 98 ends in 8, so it is even and the biggest under 100."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY odd number.",opts:["23","58","71","90"],aMulti:[0,2],
 expl:"23 ends in 3 and 71 ends in 1, so they are odd. 58 and 90 end in 8 and 0, so they are even."},
{lvl:2,sec:"T",type:"in",q:"Odd numbers in a row: 3, 5, 7, 9. What odd number comes next?",ans:11,
 expl:"Odd numbers go up by 2. 9 + 2 = 11."},
{lvl:3,sec:"T",type:"in",q:"Bao has an even number of shells. It is between 60 and 65 and has a 4 in the ones place. How many shells?",ans:64,
 hint:"Which number from 61 to 64 ends in 4?",expl:"The number between 60 and 65 with 4 ones is 64. It is even."},
{lvl:3,sec:"T",type:"mc",q:"You add an even number and an odd number. Is the sum even or odd?",opts:["Odd","Even","It could be either"],a:0,
 hint:"Try 2 + 3 and 4 + 5.",expl:"Pairs from the even number all match up, and the odd number leaves one out. The sum is always odd."}
],

"g1-factors": [
{sec:"T",type:"in",q:"12 cookies are put into groups of 3. How many groups?",ans:4,hint:"Count by 3s to 12.",
 expl:"3, 6, 9, 12. That is 4 groups of 3."},
{sec:"T",type:"mc",q:"Can 10 be split into 2 equal groups?",opts:["Yes, 5 and 5","No, there is one left over","Only into 3 groups"],a:0,
 expl:"5 + 5 = 10, so 10 splits into 2 equal groups of 5."},
{sec:"T",type:"in",q:"2 groups of 3 make 6. How many groups of 2 make 6?",ans:3,
 expl:"2 + 2 + 2 = 6, so 3 groups of 2 make 6."},
{sec:"T",type:"mc",q:"Which number can be shared into 3 equal groups?",opts:["9","10","11"],a:0,
 expl:"9 is 3 + 3 + 3. 10 and 11 leave some over when split into 3 groups."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number that splits into 4 equal groups with none left over.",opts:["8","12","10","6"],aMulti:[0,1],
 expl:"8 is 4 groups of 2 and 12 is 4 groups of 3. 10 and 6 leave 2 left over."},
{lvl:2,sec:"T",type:"in",q:"Amara has 15 beads. She makes equal groups of 5. How many groups?",ans:3,
 expl:"5 + 5 + 5 = 15. That is 3 groups."},
{lvl:3,sec:"T",type:"in",q:"Some chairs can be put in rows of 2, rows of 3, or rows of 6 with none left. What is the smallest number of chairs?",
 ans:6,hint:"Try rows of 6 first.",expl:"6 is 3 rows of 2, 2 rows of 3, or 1 row of 6. No smaller number works for all three."},
{lvl:3,sec:"T",type:"mc",q:"Which number can only be made as 1 row of itself, with no other equal rows?",opts:["7","8","9"],a:0,
 hint:"Try splitting each into equal rows.",expl:"8 makes 2 rows of 4. 9 makes 3 rows of 3. 7 only works as 1 row of 7."}
],

"g1-div25": [
{sec:"T",type:"mc",q:"Count by 2s: 2, 4, 6, 8... Which number will you say?",opts:["18","15","21"],a:0,
 expl:"Counting by 2s gives even numbers. 18 is even, so you will say it."},
{sec:"T",type:"in",q:"Count by 5s: 5, 10, 15, __. What comes next?",ans:20,expl:"Each number is 5 more. 15 + 5 = 20."},
{sec:"T",type:"mc",q:"Which digits can a number end in if you say it counting by 5s?",opts:["0 or 5","2 or 4","1 or 9"],a:0,
 expl:"5, 10, 15, 20, 25... They always end in 5 or 0."},
{sec:"T",type:"mc",q:"Which number can be shared by 2 with none left over?",opts:["36","35","33"],a:0,
 expl:"36 ends in 6, so it is even and shares by 2. 35 and 33 are odd."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number you say when counting by 5s.",opts:["25","40","32","54"],aMulti:[0,1],
 expl:"25 ends in 5 and 40 ends in 0, so you say them. 32 and 54 end in 2 and 4, so you skip them."},
{lvl:2,sec:"T",type:"in",q:"What is the biggest number under 50 that you say when counting by 5s AND by 2s?",ans:40,
 hint:"It must end in 0.",expl:"A number in both counts must end in 0. The biggest under 50 is 40."},
{lvl:3,sec:"T",type:"in",q:"Priya has 45 stickers. She shares them between 2 friends as equally as she can. How many are left over?",ans:1,
 hint:"Is 45 even or odd?",expl:"45 is odd, so 2 equal groups of 22 use 44 stickers. 1 is left over."},
{lvl:3,sec:"T",type:"mc",q:"A number ends in 0. Which is true?",
 opts:["It is in the 2s count and the 5s count","It is only in the 2s count","It is only in the 5s count"],a:0,
 expl:"A number ending in 0 is even, so it is in the 2s count. It also ends in 0, so it is in the 5s count."}
],

"g1-machines": [
{sec:"L",type:"in",q:"A machine adds 3. You put in 5. What comes out?",ans:8,expl:"5 + 3 = 8 comes out."},
{sec:"L",type:"in",q:"A machine takes away 2. You put in 9. What comes out?",ans:7,expl:"9 − 2 = 7 comes out."},
{sec:"L",type:"mc",q:"In: 2, out: 6. In: 4, out: 8. What does the machine do?",opts:["Adds 4","Adds 2","Takes away 4"],a:0,
 expl:"2 + 4 = 6 and 4 + 4 = 8. The machine adds 4."},
{sec:"L",type:"in",q:"A machine adds 10. You put in 27. What comes out?",ans:37,expl:"27 + 10 = 37 comes out."},
{lvl:2,sec:"L",type:"in",q:"A machine adds 5. Out comes 12. What number did you put in?",ans:7,hint:"Work backwards.",
 expl:"Something plus 5 is 12. 12 − 5 = 7, so you put in 7."},
{lvl:2,sec:"L",type:"mc",q:"In: 10, out: 7. In: 6, out: 3. What is the rule?",opts:["Take away 3","Add 3","Take away 4"],a:0,
 expl:"10 − 3 = 7 and 6 − 3 = 3. The rule is take away 3."},
{lvl:3,sec:"L",type:"in",q:"Two machines are in a row. The first adds 4. The second takes away 1. You put in 6. What comes out?",ans:9,
 hint:"Do the first machine, then the second.",expl:"6 + 4 = 10 after the first machine. 10 − 1 = 9 after the second."},
{lvl:3,sec:"L",type:"in",q:"A machine doubles the number. Wei puts in a number and 8 comes out. What did Wei put in?",ans:4,
 hint:"What number doubled makes 8?",expl:"4 + 4 = 8, so the number put in was 4."},
{lvl:2,sec:"L",type:"multi",q:"A machine takes away 5. Select EVERY correct in and out pair.",mono:true,
 opts:["in 9, out 4","in 12, out 7","in 8, out 13","in 5, out 5"],aMulti:[0,1],
 expl:"9 − 5 = 4 and 12 − 5 = 7 are correct. 8 − 5 is 3, not 13, and 5 − 5 is 0."},
],

"g1-growing": [
{sec:"L",type:"in",q:"1, 3, 5, 7, __. What comes next?",ans:9,hint:"How much does it grow each time?",
 expl:"Each number is 2 more than the last. 7 + 2 = 9."},
{sec:"L",type:"in",q:"Towers grow: 2 blocks, 4 blocks, 6 blocks. How many blocks in the next tower?",ans:8,
 expl:"Each tower has 2 more blocks. 6 + 2 = 8 blocks."},
{sec:"L",type:"mc",q:"Which pattern is growing?",opts:["1, 2, 3, 4","1, 2, 1, 2","5, 5, 5, 5"],a:0,
 expl:"1, 2, 3, 4 gets bigger each time. The others repeat or stay the same."},
{sec:"L",type:"in",q:"10, 20, 30, __. What comes next?",ans:40,expl:"It grows by 10 each time. 30 + 10 = 40."},
{lvl:2,sec:"L",type:"in",q:"4, 7, 10, 13, __. What comes next?",ans:16,hint:"Find the jump between numbers.",
 expl:"Each number is 3 more. 13 + 3 = 16."},
{lvl:2,sec:"L",type:"mc",q:"1, 2, 4, 8. How does this pattern grow?",opts:["Each number doubles","Add 2 each time","Add 3 each time"],a:0,
 expl:"1 + 1 = 2, 2 + 2 = 4, 4 + 4 = 8. Each number is double the one before."},
{lvl:3,sec:"L",type:"in",q:"Day 1: 1 flower. Day 2: 3 flowers. Day 3: 5 flowers. How many flowers on day 6?",ans:11,
 hint:"Keep adding the same amount for each day.",expl:"It grows by 2 each day: 1, 3, 5, 7, 9, 11. Day 6 has 11 flowers."},
{lvl:3,sec:"L",type:"in",q:"Steps use 1 block, then 3, then 6, then 10. How many blocks in the next step?",ans:15,
 hint:"The jump gets bigger by 1 each time.",expl:"The jumps are 2, 3, 4, so the next jump is 5. 10 + 5 = 15 blocks."},
{lvl:2,sec:"L",type:"order",q:"These are the first towers of a growing pattern. Put them in order from smallest to largest.",
 items:["7 blocks","1 block","4 blocks","10 blocks"],ansOrder:["1 block","4 blocks","7 blocks","10 blocks"],
 expl:"The pattern grows by 3 each time: 1, 4, 7, 10."},
],

"g1-grid": [
{sec:"P",type:"mc",q:"Ravi, Mei and Noor each have one pet: a cat, a dog or a fish. Ravi has the dog. Mei does not have the fish. Who has the fish?",
 opts:["Noor","Mei","Ravi"],a:0,expl:"Ravi has the dog. Mei does not have the fish, so Mei has the cat. That leaves the fish for Noor."},
{sec:"P",type:"mc",q:"There are two hats, red and blue. Aisha does not wear the red one. What colour is her hat?",opts:["Blue","Red","Green"],a:0,
 expl:"Only red and blue hats exist. Not red means blue."},
{sec:"P",type:"mc",q:"Three cups: A, B and C. The ball is not under A or C. Where is it?",opts:["Under B","Under A","Under C"],a:0,
 expl:"Cross out A and C. The only cup left is B."},
{sec:"P",type:"mc",q:"Femi and Lior each like one fruit, apples or pears. Femi likes apples. They like different fruits. What does Lior like?",
 opts:["Pears","Apples","Both"],a:0,expl:"Femi has apples. Lior likes something different, so Lior likes pears."},
{lvl:2,sec:"P",type:"mc",q:"Three children sit in seats 1, 2 and 3. Hana is not in seat 1 or 3. Yusuf is in seat 3. Where is Arjun?",
 opts:["Seat 1","Seat 2","Seat 3"],a:0,hint:"Place Hana first.",
 expl:"Hana must be in seat 2. Yusuf is in seat 3. Arjun gets the last seat, seat 1."},
{lvl:2,sec:"P",type:"mc",q:"Sofia, Diego and Chioma have a red, a blue and a green bag. Diego's bag is blue. Chioma's is not red. What colour is Sofia's bag?",
 opts:["Red","Blue","Green"],a:0,hint:"Work out Chioma's bag first.",
 expl:"Diego has blue. Chioma's is not red or blue, so it is green. Sofia's bag is red."},
{lvl:3,sec:"P",type:"in",q:"Ingrid, Mateo and Nadia are 5, 6 and 7 years old. Ingrid is not the oldest. Mateo is younger than Ingrid. How old is Nadia?",
 ans:7,hint:"Who must be the oldest?",expl:"Ingrid is not the oldest, and Mateo is younger than Ingrid. So Nadia is the oldest: 7."},
{lvl:3,sec:"P",type:"mc",q:"Three pets: a rabbit, a bird and a fish. Kofi's pet cannot fly or swim. Rosa's pet can fly. What is Omar's pet?",
 opts:["The fish","The rabbit","The bird"],a:0,hint:"Which pet cannot fly or swim?",
 expl:"Kofi's pet is the rabbit. Rosa's pet is the bird. The fish is left for Omar."},
{lvl:2,sec:"P",type:"multi",q:"Bao, Jonas and Kavya have a red, a blue or a green cup. Bao has the red cup. Select EVERY cup Jonas could have.",
 opts:["Blue","Green","Red"],aMulti:[0,1],
 expl:"Bao has the red cup, so Jonas cannot. Jonas could have blue or green."},
],

"g1-deduce": [
{sec:"P",type:"mc",q:"All cats have whiskers. Milo is a cat. What must be true?",opts:["Milo has whiskers","Milo is black","Milo is small"],a:0,
 expl:"Every cat has whiskers, and Milo is a cat. So Milo has whiskers. We know nothing about colour or size."},
{sec:"P",type:"mc",q:"If it rains, the grass gets wet. It is raining now. What do we know?",opts:["The grass is wet","The grass is dry","The sun is out"],a:0,
 expl:"Rain makes the grass wet. It is raining, so the grass is wet."},
{sec:"P",type:"mc",q:"Oluwaseun is older than Wei. Wei is older than Leila. Who is the youngest?",opts:["Leila","Wei","Oluwaseun"],a:0,
 expl:"Oluwaseun is oldest, then Wei, then Leila. Leila is the youngest."},
{sec:"P",type:"mc",q:"Every box on the shelf is empty. Tomas picks a box from the shelf. What is inside?",opts:["Nothing","A toy","A book"],a:0,
 expl:"All the boxes are empty, and his box came from the shelf. So there is nothing inside."},
{lvl:2,sec:"P",type:"in",q:"I am a number less than 10. I am even. I am more than 6. What am I?",ans:8,hint:"List the even numbers.",
 expl:"Even numbers more than 6 and less than 10: only 8."},
{lvl:2,sec:"P",type:"mc",q:"Anika has either a cat or a dog. Her pet barks. What is her pet?",opts:["A dog","A cat","A bird"],a:0,
 expl:"Cats do not bark. Her pet barks, so it must be the dog."},
{lvl:3,sec:"P",type:"mc",q:"Every red block is big. Hugo's block is small. What do we know about Hugo's block?",
 opts:["It is not red","It is red","It is big"],a:0,hint:"Could a small block be red?",
 expl:"If it were red, it would be big. It is small, so it cannot be red."},
{lvl:3,sec:"P",type:"in",q:"Two numbers add to 10. One is 4 more than the other. What is the smaller number?",ans:3,
 hint:"Try pairs that make 10.",expl:"3 + 7 = 10 and 7 is 4 more than 3. The smaller number is 3."},
{lvl:2,sec:"P",type:"multi",q:"All birds have feathers. Select EVERY thing we can be sure of about a robin, which is a bird.",
 opts:["It has feathers","It is a bird","It is blue","It is big"],aMulti:[0,1],
 expl:"A robin is a bird, and all birds have feathers. We know nothing about its colour or size."},
],

"g1-twostep": [
{sec:"P",type:"in",q:"Mateo has 4 red cars and 5 blue cars. He gives away 2. How many cars are left?",ans:7,hint:"Find the total first.",
 expl:"4 + 5 = 9 cars. 9 − 2 = 7 cars are left."},
{sec:"P",type:"in",q:"Noor picks 6 flowers, then 3 more. 2 of them wilt. How many good flowers are left?",ans:7,
 expl:"6 + 3 = 9 flowers. 9 − 2 = 7 good flowers."},
{sec:"P",type:"mc",q:"Ravi has 10 grapes. He eats 3, then eats 4 more. Which shows how to find what is left?",mono:true,
 opts:["10 − 3 − 4","10 + 3 + 4","10 − 3 + 4"],a:0,
 expl:"Eating takes grapes away twice. 10 − 3 − 4 = 3 grapes are left."},
{sec:"P",type:"in",q:"A box has 8 pens. Hana adds 6, then takes 5 out. How many pens are in the box?",ans:9,
 expl:"8 + 6 = 14 pens. 14 − 5 = 9 pens."},
{lvl:2,sec:"P",type:"in",q:"Aisha buys a toy for 7 dollars and a book for 5 dollars. She pays 20 dollars. How much change, in dollars?",ans:8,
 hint:"Add the two prices first.",expl:"7 + 5 = 12 dollars spent. 20 − 12 = 8 dollars change."},
{lvl:2,sec:"P",type:"in",q:"There are 3 red, 4 blue and 5 green balls. How many balls are NOT green?",ans:7,
 expl:"Red and blue balls: 3 + 4 = 7. Those are the ones that are not green."},
{lvl:3,sec:"P",type:"in",q:"Chioma has 12 stickers. She gives 4 to Femi and 3 to Lior. Then she finds 6 more. How many now?",ans:11,
 hint:"Take away both gifts, then add.",expl:"12 − 4 − 3 = 5 stickers. 5 + 6 = 11 stickers."},
{lvl:3,sec:"P",type:"in",q:"Two shelves hold 15 books. The top shelf has 9. Diego moves 2 books from the top to the bottom. How many are on the bottom now?",
 ans:8,hint:"Find how many were on the bottom first.",expl:"The bottom shelf had 15 − 9 = 6 books. After 2 more, it has 6 + 2 = 8."},
{lvl:2,sec:"P",type:"order",q:"Kavya has 6 marbles, wins 5, then loses 3. Put the steps in order from first to last.",
 items:["Take away 3","Start with 6","Add 5"],ansOrder:["Start with 6","Add 5","Take away 3"],
 expl:"Start with 6. Winning adds 5 to make 11. Losing takes away 3 to leave 8."},
],

"g1-choose": [
{sec:"K",type:"in",q:"You may pick 2 of these 3 fruits: apple, pear, grape. How many different pairs can you pick?",ans:3,
 hint:"List the pairs.",expl:"Apple and pear, apple and grape, pear and grape. That is 3 pairs."},
{sec:"K",type:"mc",q:"You pick a red ball and a blue ball. Is that the same pick as a blue ball and a red ball?",
 opts:["Yes, the order does not matter","No, they are different picks","Only if the balls are big"],a:0,
 expl:"You end up holding the same two balls. When you choose a group, the order does not matter."},
{sec:"K",type:"in",q:"Lucia picks 1 toy from 4 toys. How many choices does she have?",ans:4,
 expl:"Any of the 4 toys could be the one. There are 4 choices."},
{sec:"K",type:"in",q:"Four children: Isla, Yusuf, Arjun and Maya. How many different pairs can go on the slide together?",ans:6,
 hint:"Write every pair. Isla with Yusuf is the same pair as Yusuf with Isla.",
 expl:"Isla can pair with 3 others. Yusuf then has 2 new partners, and Arjun has 1 new partner: Maya. 3 + 2 + 1 = 6 pairs."},
{lvl:2,sec:"K",type:"in",q:"There are 4 ice cream flavours. You choose 3 of them. How many different ways can you choose?",ans:4,
 hint:"Think about which one you leave out.",expl:"Choosing 3 of 4 is the same as leaving 1 out. There are 4 flavours to leave out, so 4 ways."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY pair you can make from 3 balls: red, blue and green.",
 opts:["red and blue","blue and green","red and red","green and red"],aMulti:[0,1,3],
 expl:"Each pair uses two different balls. Red and red is not a pair of two balls."},
{lvl:3,sec:"K",type:"in",q:"5 friends meet. Each pair shakes hands one time. How many handshakes are there?",ans:10,
 hint:"Start with 2 friends, then 3, then 4. Look for the pattern.",
 expl:"The first friend shakes 4 hands, the next 3 new ones, then 2, then 1. 4 + 3 + 2 + 1 = 10 handshakes."},
{lvl:3,sec:"K",type:"in",q:"Tariq has 2 shirts and 3 hats. He picks 1 shirt and 1 hat. How many different outfits can he make?",ans:6,
 hint:"Try each shirt with every hat.",expl:"Each shirt goes with 3 hats. 2 shirts make 3 + 3 = 6 outfits."}
]
};
