/* Grades 1 and 2. */
export const G12_BANKS = {
"g1-add20": [
{sec:"N",type:"in",q:"8 + 5 = ?",ans:13,hint:"Make ten first: 8 + 2 = 10.",
 expl:"Split the 5 into 2 and 3. 8 + 2 = 10, then 10 + 3 = 13."},
{sec:"N",type:"in",q:"9 + 6 = ?",ans:15,hint:"Make ten first.",
 expl:"9 + 1 = 10, and 5 remains, so 10 + 5 = 15."},
{sec:"N",type:"in",q:"7 + 7 = ?",ans:14,expl:"A double: 7 + 7 = 14."},
{sec:"N",type:"in",q:"12 + 4 = ?",ans:16,expl:"Count on 4 from 12: 13, 14, 15, 16."},
{sec:"N",type:"mc",q:"Which one makes 20?",mono:true,opts:["13 + 7","13 + 6","12 + 7","14 + 5"],a:0,
 expl:"13 + 7 = 20. The others give 19, 19 and 19."},
{lvl:2,sec:"N",type:"in",q:"6 + 7 + 4 = ?",ans:17,hint:"Look for a pair that makes ten.",
 expl:"6 + 4 = 10 first, then 10 + 7 = 17. Reordering makes it easier."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY sum that equals 15.",
 opts:["8 + 7","9 + 6","7 + 9","10 + 4"],aMulti:[0,1],
 expl:"8 + 7 = 15 and 9 + 6 = 15. But 7 + 9 = 16 and 10 + 4 = 14."},
{lvl:3,sec:"N",type:"in",q:"Ana has 9 stickers. Ben has 4 more than Ana. How many do they have altogether?",
 ans:22,hint:"Work out Ben's first.",
 expl:"Ben has 9 + 4 = 13. Together: 9 + 13 = 22 stickers."}
],

"g1-tensones": [
{sec:"N",type:"in",q:"How many tens are in 47?",ans:4,hint:"Look at the first digit.",
 expl:"47 is 4 tens and 7 ones, so there are 4 tens."},
{sec:"N",type:"in",q:"How many ones are in 63?",ans:3,expl:"63 is 6 tens and 3 ones."},
{sec:"N",type:"in",q:"What number is 5 tens and 2 ones?",ans:52,
 expl:"5 tens is 50, plus 2 ones makes 52."},
{sec:"N",type:"mc",q:"Which number has 8 tens?",mono:true,opts:["83","38","8","18"],a:0,
 expl:"83 is 8 tens and 3 ones. In 38 the 8 is the ones digit."},
{lvl:2,sec:"N",type:"in",q:"What number is 3 tens and 14 ones?",ans:44,
 hint:"14 ones is more than a ten.",
 expl:"14 ones is 1 ten and 4 ones, so altogether 4 tens and 4 ones — that is 44."},
{lvl:3,sec:"N",type:"in",q:"I am a two-digit number. My tens digit is 2 more than my ones digit, and my digits add to 10. What number am I?",
 ans:64,hint:"Which two digits add to 10 and differ by 2?",
 expl:"6 and 4 add to 10 and differ by 2. The tens digit is the bigger one, so the number is 64."}
],

"g2-arrays": [
{sec:"N",type:"in",q:"An array has 3 rows of 4. How many altogether?",ans:12,
 hint:"Add 4 three times, or count the rows.",expl:"3 rows of 4 is 4 + 4 + 4 = 12."},
{sec:"N",type:"in",q:"An array has 5 rows of 2. How many altogether?",ans:10,
 expl:"5 rows of 2 is 2 + 2 + 2 + 2 + 2 = 10."},
{sec:"N",type:"mc",q:"Which addition matches an array of 4 rows of 5?",mono:true,
 opts:["5 + 5 + 5 + 5","4 + 4 + 4 + 4 + 4","4 + 5","5 + 4 + 5"],a:0,
 expl:"4 rows of 5 means adding 5 four times: 5 + 5 + 5 + 5 = 20."},
{lvl:2,sec:"N",type:"in",q:"An array of counters has 4 rows and 6 in each row. How many counters?",ans:24,
 expl:"4 rows of 6 is 6 + 6 + 6 + 6 = 24."},
{lvl:2,sec:"N",type:"mc",q:"An array has 12 counters in 3 equal rows. How many are in each row?",
 mono:true,opts:["4","3","6","12"],a:0,expl:"12 shared into 3 equal rows gives 4 in each row."},
{lvl:3,sec:"N",type:"in",q:"A box holds 5 rows of 4 chocolates. Two chocolates are eaten. How many are left?",
 ans:18,hint:"Work out the whole box first.",
 expl:"5 rows of 4 is 20 chocolates. After eating 2, there are 18 left."}
],

"g2-place1000": [
{sec:"N",type:"in",q:"How many hundreds are in 372?",ans:3,expl:"372 is 3 hundreds, 7 tens and 2 ones."},
{sec:"N",type:"in",q:"What number is 4 hundreds, 0 tens and 6 ones?",ans:406,
 hint:"The zero holds the tens place.",
 expl:"400 + 0 + 6 = 406. The 0 is important — without it you would write 46."},
{sec:"N",type:"mc",q:"Which number is the largest?",mono:true,opts:["519","591","195","159"],a:1,
 expl:"Compare hundreds first: 519 and 591 both have 5 hundreds. Then tens: 9 beats 1, so 591 is largest."},
{lvl:2,sec:"N",type:"order",q:"Put these in order, smallest first.",
 items:["408","480","84","840"],ansOrder:["84","408","480","840"],
 expl:"84 has no hundreds. Then 408, 480 and 840 compare by hundreds, then tens."},
{lvl:2,sec:"N",type:"in",q:"What is 10 more than 295?",ans:305,hint:"Watch the tens roll over.",
 expl:"295 + 10 = 305. The 9 tens become 10 tens, which makes a new hundred."},
{lvl:3,sec:"N",type:"in",q:"Using the digits 7, 2 and 5 once each, what is the largest three-digit number you can make?",
 ans:752,hint:"Put the biggest digit where it counts most.",
 expl:"The hundreds place matters most, so put 7 there, then 5, then 2: 752."}
],

"g1-sub20": [
{sec:"N",type:"in",q:"15 − 6 = ?",ans:9,hint:"Count back, or find the ten first.",
 expl:"15 − 5 = 10, then one more back: 10 − 1 = 9."},
{sec:"N",type:"in",q:"12 − 5 = ?",ans:7,expl:"12 − 2 = 10, then 10 − 3 = 7."},
{sec:"N",type:"in",q:"18 − 9 = ?",ans:9,expl:"18 − 9 = 9 — taking away 9 from 18 leaves 9."},
{sec:"N",type:"in",q:"14 − 8 = ?",ans:6,hint:"Make ten first.",expl:"14 − 4 = 10, then 10 − 4 = 6."},
{sec:"N",type:"mc",q:"Which is the same as 16 − 7?",mono:true,opts:["9","8","10","7"],a:0,
 expl:"16 − 7 = 9. The others come from different subtractions."},
{lvl:2,sec:"N",type:"in",q:"9 + 7 − 3 = ?",ans:13,hint:"Add first, then subtract.",
 expl:"9 + 7 = 16, then 16 − 3 = 13."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY problem that equals 8.",
 opts:["15 − 7","12 − 4","11 − 4","16 − 8"],aMulti:[0,1,3],
 expl:"15 − 7 = 8, 12 − 4 = 8 and 16 − 8 = 8. But 11 − 4 = 7."},
{lvl:3,sec:"W",type:"in",q:"Maya had 17 candies. She gave away 9. Then she got 4 more. How many does she have now?",
 ans:12,hint:"Subtract first, then add.",
 expl:"17 − 9 = 8, then 8 + 4 = 12."}
],

"g1-equals": [
{sec:"P",type:"mc",q:"What number makes this true?  5 + 3 = 4 + __",
 opts:["4","3","8","5"],a:0,
 expl:"5 + 3 = 8, so the other side needs to make 8 too: 4 + 4 = 8."},
{sec:"P",type:"in",q:"6 + 2 = __ + 5",ans:3,hint:"Work out the left side first.",
 expl:"6 + 2 = 8, and 8 = __ + 5 means __ = 3."},
{sec:"P",type:"mc",q:"Which of these is a TRUE equation?",mono:true,
 opts:["7 = 3 + 4","7 = 3 + 5","7 = 2 + 6","7 = 1 + 7"],a:0,
 expl:"3 + 4 = 7, so that one is true. The others make 8."},
{sec:"P",type:"in",q:"9 = __ + 4",ans:5,expl:"9 = 5 + 4, so the missing number is 5."},
{sec:"P",type:"mc",q:"The equal sign (=) means ___.",
 opts:["both sides have the same value","the answer comes next","add the numbers","the bigger number wins"],a:0,
 expl:"An equal sign says the amount on the left is the same as the amount on the right — it is a balance, not just 'here comes the answer'."},
{lvl:2,sec:"P",type:"in",q:"8 + 6 = 10 + __",ans:4,hint:"Work out the left side first.",
 expl:"8 + 6 = 14, and 10 + 4 = 14, so the missing number is 4."},
{lvl:2,sec:"P",type:"mc",q:"Which equation is FALSE?",mono:true,
 opts:["9 = 5 + 4","9 = 6 + 3","9 = 7 + 1","9 = 2 + 7"],a:2,
 expl:"7 + 1 = 8, not 9 — that one is false. The rest all make 9."},
{lvl:3,sec:"P",type:"in",q:"A balance shows 12 + 5 on one side. What number balances it on 9 + __?",
 ans:8,hint:"Work out 12 + 5 first.",
 expl:"12 + 5 = 17, and 9 + 8 = 17, so the missing number is 8."}
],

"g1-wordprob": [
{sec:"W",type:"in",q:"Sam has 8 apples. He gets some more and now has 13. How many did he get?",
 ans:5,hint:"Think about what was added.",expl:"13 − 8 = 5 more apples."},
{sec:"W",type:"in",q:"There are 15 birds in a tree. 6 fly away. How many are left?",
 ans:9,expl:"15 − 6 = 9 birds left."},
{sec:"W",type:"mc",q:"Which number sentence matches: 'Lily had some stickers, gave away 4, and has 9 left'?",
 mono:true,opts:["__ − 4 = 9","__ + 4 = 9","9 − 4 = __","4 − __ = 9"],a:0,
 expl:"She started with an unknown amount, 4 were taken away, and 9 remained: __ − 4 = 9."},
{sec:"W",type:"in",q:"A box had some pencils. 7 were added, making 16. How many were in the box at the start?",
 ans:9,hint:"Work backwards.",expl:"16 − 7 = 9 pencils to start."},
{sec:"W",type:"mc",q:"Which shows the unknown correctly for: 'I have 6 red marbles and some blue marbles, 14 in total. How many blue?'",
 opts:["6 + __ = 14","__ + 14 = 6","14 + 6 = __","6 − __ = 14"],a:0,
 expl:"The two amounts must add to the total: 6 + __ = 14."},
{lvl:2,sec:"W",type:"in",q:"There were 20 fish in a tank. Some swam into a net, leaving 12. How many swam into the net?",
 ans:8,expl:"20 − 12 = 8 fish."},
{lvl:2,sec:"W",type:"in",q:"Emma had 9 crayons. She got 6 more, then gave 4 away. How many does she have now?",
 ans:11,hint:"Do it in order: add, then subtract.",
 expl:"9 + 6 = 15, then 15 − 4 = 11."},
{lvl:3,sec:"W",type:"in",q:"A farmer had some chickens. 8 hatched, then 3 were sold, leaving 19. How many did the farmer start with?",
 ans:14,hint:"Work backwards from 19.",
 expl:"Undo the sale first: 19 + 3 = 22. Then undo the hatching: 22 − 8 = 14."}
],

"g1-compare2": [
{sec:"N",type:"mc",q:"Which symbol makes this true?  47 ◯ 52",mono:true,opts:["<",">","="],a:0,
 expl:"47 has fewer tens than 52, so 47 < 52."},
{sec:"N",type:"mc",q:"Which symbol makes this true?  63 ◯ 36",mono:true,opts:["<",">","="],a:1,
 expl:"63 has 6 tens and 36 has 3 tens, so 63 > 36."},
{sec:"N",type:"mc",q:"Which number is greater than 45 but less than 50?",mono:true,
 opts:["47","44","51","40"],a:0,expl:"47 sits between 45 and 50. The others are outside that range."},
{sec:"N",type:"order",q:"Put these numbers in order, smallest first.",
 items:["28","82","19","91"],ansOrder:["19","28","82","91"],
 expl:"Compare the tens digit first: 1, 2, 8, 9 tens gives this order."},
{sec:"N",type:"mc",q:"Which symbol makes this true?  70 ◯ 69 + 1",mono:true,opts:["<",">","="],a:2,
 expl:"69 + 1 = 70, and 70 equals 70, so the symbol is =."},
{lvl:2,sec:"N",type:"order",q:"These numbers all have 5 tens. Put them in order, smallest first.",
 items:["53","58","51","55"],ansOrder:["51","53","55","58"],
 expl:"All have 5 tens, so compare the ones digit: 1, 3, 5, 8."},
{lvl:3,sec:"N",type:"mc",q:"Which number is between 34 and 41, and greater than 38?",mono:true,
 opts:["39","34","41","33"],a:0,
 expl:"39 is bigger than 34 and smaller than 41, and it is also bigger than 38."}
],

"g1-length": [
{sec:"M",type:"mc",q:"Which is the BEST tool to measure the length of your pencil?",
 opts:["a ruler","a scale","a clock","a thermometer"],a:0,
 expl:"A ruler measures length. A scale measures weight, a clock measures time."},
{sec:"M",type:"in",q:"A crayon is 6 cubes long. Another is 4 cubes long. How many MORE cubes long is the first crayon?",
 ans:2,expl:"6 − 4 = 2 cubes longer."},
{sec:"M",type:"mc",q:"Which object is LONGER?",mono:true,
 opts:["a school bus","a shoe","they are the same","you cannot tell"],a:0,
 expl:"A school bus is far longer than a shoe."},
{sec:"M",type:"in",q:"You measure a book using paperclips laid end to end. It takes 8 paperclips. How many paperclips long is the book?",
 ans:8,expl:"The book is 8 paperclips long — that is what 'measuring with paperclips' means."},
{sec:"M",type:"order",q:"Order these pencils from SHORTEST to longest, by their length in cubes.",
 items:["9 cubes","3 cubes","6 cubes","1 cube"],ansOrder:["1 cube","3 cubes","6 cubes","9 cubes"],
 expl:"Compare the numbers: 1, 3, 6, 9 cubes, smallest first."},
{lvl:2,sec:"M",type:"in",q:"Table A is 12 spans long. Table B is 15 spans long. How many spans LONGER is Table B?",
 ans:3,expl:"15 − 12 = 3 spans longer."},
{lvl:2,sec:"M",type:"mc",q:"Why might two people measure the same desk and get a different number of spans?",
 opts:["Their hands are different sizes","The desk changed size","One of them cannot count","Desks cannot be measured"],a:0,
 expl:"A hand-span is not a fixed unit — bigger hands mean fewer spans are needed, so the count changes person to person."},
{lvl:3,sec:"M",type:"in",q:"A ribbon is 14 paperclips long. A longer clip is twice as long as a paperclip. How many long clips measure the same ribbon?",
 ans:7,hint:"A bigger unit means a smaller count.",
 expl:"Each long clip covers 2 paperclip-lengths, so 14 ÷ 2 = 7 long clips."}
],

"g2-fluency": [
{sec:"N",type:"in",q:"13 − 6 = ?",ans:7,expl:"13 − 6 = 7."},
{sec:"N",type:"in",q:"9 + 8 = ?",ans:17,expl:"9 + 8 = 17."},
{sec:"N",type:"mc",q:"Which pair makes 16?",mono:true,opts:["9 + 7","8 + 9","7 + 7","6 + 9"],a:0,
 expl:"9 + 7 = 16. 8 + 9 = 17, 7 + 7 = 14, 6 + 9 = 15."},
{sec:"N",type:"in",q:"17 − 9 = ?",ans:8,expl:"17 − 9 = 8."},
{sec:"N",type:"in",q:"6 + 6 + 3 = ?",ans:15,hint:"Add the double first.",expl:"6 + 6 = 12, then 12 + 3 = 15."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY problem that equals 9.",
 opts:["15 − 6","14 − 4","18 − 9","12 − 3"],aMulti:[0,2,3],
 expl:"15 − 6 = 9, 18 − 9 = 9 and 12 − 3 = 9. But 14 − 4 = 10."},
{lvl:2,sec:"N",type:"in",q:"14 − 8 + 5 = ?",ans:11,hint:"Work left to right.",expl:"14 − 8 = 6, then 6 + 5 = 11."},
{lvl:3,sec:"W",type:"in",q:"A jar had 20 marbles. 8 were taken out, then 6 were put back. How many are in the jar now?",
 ans:18,expl:"20 − 8 = 12, then 12 + 6 = 18."}
],

"g2-add1000": [
{sec:"N",type:"in",q:"236 + 145 = ?",ans:381,expl:"236 + 145 = 381."},
{sec:"N",type:"in",q:"580 − 235 = ?",ans:345,expl:"580 − 235 = 345."},
{sec:"N",type:"mc",q:"What is 407 + 198?",opts:["605","505","615","595"],a:0,
 expl:"407 + 198 = 605. (198 is close to 200: 407 + 200 = 607, minus 2 = 605.)"},
{sec:"N",type:"in",q:"912 − 358 = ?",ans:554,expl:"912 − 358 = 554."},
{sec:"N",type:"in",q:"265 + 340 = ?",ans:605,expl:"265 + 340 = 605."},
{lvl:2,sec:"W",type:"in",q:"A school has 384 students. 129 more enroll. How many students are there now?",
 ans:513,expl:"384 + 129 = 513."},
{lvl:2,sec:"W",type:"in",q:"A shop had 700 apples. It sold 268. How many are left?",
 ans:432,expl:"700 − 268 = 432."},
{lvl:3,sec:"N",type:"in",q:"Two numbers add to 963. One of the numbers is 428. What is the other number?",
 ans:535,hint:"Subtract the known number from the total.",expl:"963 − 428 = 535."}
],

"g2-money": [
{sec:"MNY",type:"in",q:"You have $3.25. You spend $1.10. How much is left, in dollars? Type just the number, like 2.15.",
 ans:2.15,expl:"$3.25 − $1.10 = $2.15."},
{sec:"MNY",type:"in",q:"A pencil costs $0.45 and an eraser costs $0.30. What is the total cost, in dollars?",
 ans:0.75,expl:"$0.45 + $0.30 = $0.75."},
{sec:"MNY",type:"mc",q:"You have $5.00 and buy a toy for $3.40. How much change do you get?",
 opts:["$1.60","$1.40","$2.60","$8.40"],a:0,expl:"$5.00 − $3.40 = $1.60."},
{sec:"MNY",type:"in",q:"You have 2 one-dollar bills and 3 quarters. How much money in dollars? Type just the number.",
 ans:2.75,expl:"2 dollars is $2.00, and 3 quarters is $0.75. Together: $2.75."},
{sec:"MNY",type:"in",q:"A book costs $4.50 and a bookmark costs $0.75. What is the total, in dollars?",
 ans:5.25,expl:"$4.50 + $0.75 = $5.25."},
{lvl:2,sec:"MNY",type:"in",q:"You buy 3 pencils at $0.50 each. How much do you spend in total, in dollars?",
 ans:1.5,expl:"3 × $0.50 = $1.50."},
{lvl:2,sec:"MNY",type:"in",q:"You have $10. You spend $3.75 and $2.50. How much is left, in dollars?",
 ans:3.75,hint:"Subtract both amounts.",expl:"$10.00 − $3.75 − $2.50 = $3.75."},
{lvl:3,sec:"MNY",type:"in",q:"You buy a shirt for $12.99 and pay with a $20 bill. How much change do you get, in dollars?",
 ans:7.01,expl:"$20.00 − $12.99 = $7.01."}
],

"g2-equalgrp": [
{sec:"N",type:"in",q:"There are 4 groups of 5 apples. How many apples in total?",ans:20,
 expl:"4 groups of 5 is 5 + 5 + 5 + 5 = 20."},
{sec:"N",type:"in",q:"3 groups of 6 stars. How many stars?",ans:18,expl:"6 + 6 + 6 = 18."},
{sec:"N",type:"mc",q:"Which shows 5 groups of 3?",mono:true,
 opts:["3 + 3 + 3 + 3 + 3","5 + 5 + 5","3 + 5","5 × 3 + 3"],a:0,
 expl:"5 groups of 3 means adding 3 five times: 3 + 3 + 3 + 3 + 3 = 15."},
{sec:"N",type:"in",q:"24 cookies are shared into 4 equal groups. How many cookies in each group?",ans:6,
 expl:"24 ÷ 4 = 6 cookies per group."},
{sec:"N",type:"mc",q:"Which set of groups is NOT equal?",mono:true,
 opts:["3, 3, 5","4, 4, 4","6, 6","2, 2, 2, 2"],a:0,
 expl:"3, 3, 5 has a group of a different size. The rest are all equal groups."},
{lvl:2,sec:"N",type:"in",q:"6 groups of 7 crayons. How many crayons altogether?",ans:42,
 expl:"6 groups of 7 is 7 × 6 = 42."},
{lvl:2,sec:"N",type:"in",q:"35 marbles are put into equal groups of 5. How many groups are there?",ans:7,
 expl:"35 ÷ 5 = 7 groups."},
{lvl:3,sec:"N",type:"in",q:"There are 8 equal groups. Together they have 56 counters. How many counters are in each group?",
 ans:7,expl:"56 ÷ 8 = 7 counters per group."}
],

"g2-rulers": [
{sec:"M",type:"mc",q:"When measuring with a ruler, where do you line up the start of the object?",
 opts:["At the 0 mark","At the 1 mark","At the end of the ruler","Anywhere is fine"],a:0,
 expl:"Measuring always starts at 0, or you have to subtract to correct for it."},
{sec:"M",type:"in",q:"A crayon measures 4 inches on a ruler. A marker measures 6 inches. How many inches LONGER is the marker?",
 ans:2,expl:"6 − 4 = 2 inches longer."},
{sec:"M",type:"mc",q:"Which is the better tool to measure the length of a classroom door?",
 opts:["a yardstick","a ruler","a paperclip","a scale"],a:0,
 expl:"A door is much longer than a 12-inch ruler, so a yardstick (3 feet) is the better fit."},
{sec:"M",type:"in",q:"Two ribbons measure 7 inches and 3 inches. What is their combined length, in inches?",
 ans:10,expl:"7 + 3 = 10 inches."},
{sec:"M",type:"mc",q:"A book measures 8 inches with one ruler. Measuring the SAME book with a different (accurate) ruler should give ___.",
 opts:["8 inches","a different length","no answer","only centimeters"],a:0,
 expl:"Length does not change with the tool — any accurate ruler gives the same measurement."},
{lvl:2,sec:"M",type:"in",q:"A ribbon is 24 inches long. How many feet is that? (12 inches = 1 foot)",
 ans:2,expl:"24 ÷ 12 = 2 feet."},
{lvl:2,sec:"M",type:"in",q:"A table is 36 inches long. How many feet is that?",ans:3,
 expl:"36 ÷ 12 = 3 feet."},
{lvl:3,sec:"M",type:"in",q:"A rope measures 5 feet. How many inches is that?",ans:60,
 expl:"5 × 12 = 60 inches."}
],

"g2-time5": [
{sec:"M",type:"mc",q:"The clock's minute hand points to the 3. How many minutes past the hour is it?",
 opts:["15","3","30","45"],a:0,expl:"Each number on a clock face counts for 5 minutes: 3 × 5 = 15."},
{sec:"M",type:"mc",q:"The minute hand points to the 6. How many minutes past the hour is it?",
 opts:["30","6","15","45"],a:0,expl:"6 × 5 = 30 minutes."},
{sec:"M",type:"in",q:"A clock's minute hand points to the 9. How many minutes past the hour is that?",
 ans:45,expl:"9 × 5 = 45 minutes."},
{sec:"M",type:"mc",q:"Which time is the SAME as 'half past 4'?",mono:true,
 opts:["4:30","4:15","4:45","4:06"],a:0,expl:"'Half past' means 30 minutes after the hour."},
{sec:"M",type:"in",q:"A show starts at 3:00 and the minute hand moves to the 2. How many minutes past 3:00 is it now?",
 ans:10,expl:"2 × 5 = 10 minutes."},
{lvl:2,sec:"M",type:"in",q:"A movie starts at 2:15 and ends at 2:45. How many minutes long is it?",
 ans:30,expl:"From 2:15 to 2:45 is 30 minutes."},
{lvl:2,sec:"M",type:"mc",q:"It is 6:50. In ten minutes, what time will it be?",mono:true,
 opts:["7:00","6:60","6:40","7:10"],a:0,expl:"50 + 10 = 60 minutes, which rolls over to the next hour: 7:00."},
{lvl:3,sec:"M",type:"in",q:"A clock reads 5:40. How many minutes until it is 6:00?",ans:20,
 expl:"From 40 to 60 minutes is 20 minutes."}
],

"g2-add100": [
{sec:"N",type:"in",q:"34 + 25 = ?",ans:59,expl:"34 + 25 = 59."},
{sec:"N",type:"in",q:"68 − 23 = ?",ans:45,expl:"68 − 23 = 45."},
{sec:"N",type:"mc",q:"What is 47 + 36?",opts:["83","73","93","82"],a:0,expl:"47 + 36 = 83."},
{sec:"N",type:"in",q:"90 − 47 = ?",ans:43,expl:"90 − 47 = 43."},
{sec:"N",type:"in",q:"56 + 38 = ?",ans:94,expl:"56 + 38 = 94."},
{lvl:2,sec:"N",type:"in",q:"A class has 27 boys and 34 girls. How many students total?",
 ans:61,expl:"27 + 34 = 61 students."},
{lvl:2,sec:"N",type:"in",q:"There were 82 apples. 39 were eaten. How many are left?",
 ans:43,expl:"82 − 39 = 43 apples."},
{lvl:3,sec:"N",type:"in",q:"Two numbers add to 100. One of them is 37. What is the other?",
 ans:63,expl:"100 − 37 = 63."}
],

"g2-compare3": [
{sec:"N",type:"mc",q:"Which symbol makes this true?  452 ◯ 425",mono:true,opts:[">","<","="],a:0,
 expl:"Both have 4 hundreds, but 452 has 5 tens against 425's 2 tens, so 452 > 425."},
{sec:"N",type:"mc",q:"Which number is SMALLEST?",mono:true,opts:["308","380","803","830"],a:0,
 expl:"Compare hundreds first: 308 and 380 both have 3, but 380 has more tens. 308 is the smallest."},
{sec:"N",type:"order",q:"Put these numbers in order, smallest first.",
 items:["612","621","162","261"],ansOrder:["162","261","612","621"],
 expl:"Compare hundreds digits first: 1, 2, 6, 6 — then tens for the tie."},
{sec:"N",type:"mc",q:"Which symbol makes this true?  700 ◯ 699",mono:true,opts:[">","<","="],a:0,
 expl:"700 has 7 hundreds; 699 has only 6. So 700 > 699."},
{sec:"N",type:"in",q:"Both 356 and 358 have the same hundreds digit. What is it?",ans:3,
 expl:"Both numbers start with 3 hundreds."},
{lvl:2,sec:"N",type:"mc",q:"Which symbol makes this true?  245 ◯ 254",mono:true,opts:["<",">","="],a:0,
 expl:"Both have 2 hundreds, but 245 has 4 tens against 254's 5 tens, so 245 < 254."},
{lvl:2,sec:"N",type:"order",q:"Put these numbers in order, LARGEST first.",
 items:["540","450","504","405"],ansOrder:["540","504","450","405"],
 expl:"Compare hundreds first: 5, 5, 4, 4 — then tens breaks each tie."},
{lvl:3,sec:"N",type:"in",q:"A 3-digit number is greater than 450 and less than 460. What is its tens digit?",
 ans:5,expl:"Every number from 450 to 459 has a 5 in the tens place."}
],

"g2-mental": [
{sec:"N",type:"in",q:"47 + 10 = ?",ans:57,expl:"Adding 10 raises the tens digit by one: 47 + 10 = 57."},
{sec:"N",type:"in",q:"83 − 10 = ?",ans:73,expl:"Subtracting 10 lowers the tens digit by one: 83 − 10 = 73."},
{sec:"N",type:"in",q:"236 + 100 = ?",ans:336,expl:"Adding 100 raises the hundreds digit by one: 236 + 100 = 336."},
{sec:"N",type:"mc",q:"What is 590 − 100?",opts:["490","590","690","480"],a:0,
 expl:"Subtracting 100 lowers the hundreds digit by one: 590 − 100 = 490."},
{sec:"N",type:"in",q:"45 + 20 = ? (think: 2 tens)",ans:65,expl:"Adding 2 tens: 45 + 20 = 65."},
{lvl:2,sec:"N",type:"in",q:"368 + 100 = ?",ans:468,expl:"368 + 100 = 468."},
{lvl:2,sec:"N",type:"in",q:"A number plus 10 equals 82. What is the number?",ans:72,
 expl:"82 − 10 = 72."},
{lvl:3,sec:"N",type:"in",q:"A number, after adding 100 and then subtracting 10, equals 295. What was the original number?",
 ans:205,hint:"Undo the steps in reverse.",
 expl:"Undo subtracting 10: 295 + 10 = 305. Undo adding 100: 305 − 100 = 205."}
],

"g2-estimate": [
{sec:"M",type:"mc",q:"About how long is a new pencil?",opts:["7 inches","7 feet","7 miles","7 yards"],a:0,
 expl:"A pencil is small — inches are the right size unit."},
{sec:"M",type:"mc",q:"About how long is a car?",opts:["12 feet","12 inches","12 miles","12 pounds"],a:0,
 expl:"A car is much longer than 12 inches and far shorter than 12 miles — feet fits."},
{sec:"M",type:"mc",q:"Which is the BEST estimate for the height of a door?",
 opts:["7 feet","7 inches","7 miles","7 pounds"],a:0,expl:"A door is about as tall as a very tall person — feet is the right unit."},
{sec:"M",type:"mc",q:"A book is closest to how long?",opts:["9 inches","9 feet","9 miles","9 yards"],a:0,
 expl:"A book fits in your hands — inches are the right size."},
{sec:"M",type:"mc",q:"Which unit would you use to estimate the length of a football field?",
 opts:["yards","inches","pounds","hours"],a:0,expl:"A football field is measured in yards, a much bigger unit than inches."},
{lvl:2,sec:"M",type:"mc",q:"You estimate a hallway at about 20 feet before measuring. You measure it and get 19 feet. Was your estimate reasonable?",
 opts:["Yes, it's close","No, way off","Estimates must be exact","Cannot tell"],a:0,
 expl:"A good estimate does not have to be exact — it just has to be close, and 19 is close to 20."},
{lvl:2,sec:"M",type:"mc",q:"Which is a REASONABLE estimate for the length of a school bus?",
 opts:["35 feet","35 inches","35 miles","3500 feet"],a:0,
 expl:"35 inches is smaller than a person, and 35 miles or 3500 feet is far too long. 35 feet fits a bus."},
{lvl:3,sec:"M",type:"mc",q:"You estimate your classroom is about 30 feet long. Which measured length would make your estimate UNREASONABLE?",
 opts:["3 feet","28 feet","31 feet","29 feet"],a:0,
 expl:"3 feet is wildly different from an estimate of 30 — a real classroom cannot shrink that much. The others are all close to 30."}
],

"g2-lineplot": [
{sec:"M",type:"in",q:"A line plot shows: 2 X's above 3, 1 X above 4, 3 X's above 5. How many data points are there in total?",
 ans:6,expl:"2 + 1 + 3 = 6 data points."},
{sec:"M",type:"in",q:"Using that same line plot (2 X's above 3, 1 X above 4, 3 X's above 5), how many values are LESS than 5?",
 ans:3,expl:"The values below 5 are the 2 above 3 and the 1 above 4: 2 + 1 = 3."},
{sec:"M",type:"mc",q:"In a line plot, each X represents ___.",
 opts:["one data point","the total","the average","the biggest value"],a:0,
 expl:"Every single X stands for one measurement or observation."},
{sec:"M",type:"in",q:"A line plot has 4 X's above 2 and 2 X's above 6. What is the total of ALL the data values added together?",
 ans:20,expl:"4 × 2 = 8, and 2 × 6 = 12. Together: 8 + 12 = 20."},
{sec:"M",type:"mc",q:"On a line plot, which number appears MOST OFTEN?",
 opts:["The one with the tallest stack of X's","The largest number on the plot","The smallest number on the plot","It cannot be determined"],a:0,
 expl:"The tallest stack of X's shows which value was recorded the most times."},
{lvl:2,sec:"M",type:"in",q:"A line plot: 1 X above 1, 3 X's above 2, 2 X's above 3. How many data points total?",
 ans:6,expl:"1 + 3 + 2 = 6 data points."},
{lvl:2,sec:"M",type:"in",q:"Using that same plot (1 X above 1, 3 X's above 2, 2 X's above 3), how many values are GREATER than 1?",
 ans:5,expl:"The values above 1 are the 3 above 2 and the 2 above 3: 3 + 2 = 5."},
{lvl:3,sec:"M",type:"in",q:"A line plot has 5 data points total. 2 are above 4 and the rest are above 7. How many are above 7?",
 ans:3,expl:"5 − 2 = 3 data points are above 7."}
],

"g2-polygons": [
{sec:"G",type:"mc",q:"A shape with 3 sides is called a ___.",
 opts:["triangle","quadrilateral","pentagon","hexagon"],a:0,expl:"'Tri' means three — a triangle has 3 sides."},
{sec:"G",type:"mc",q:"A shape with 5 sides is called a ___.",
 opts:["pentagon","triangle","hexagon","quadrilateral"],a:0,expl:"'Penta' means five — a pentagon has 5 sides."},
{sec:"G",type:"mc",q:"A shape with 6 sides is called a ___.",
 opts:["hexagon","pentagon","triangle","quadrilateral"],a:0,expl:"'Hexa' means six — a hexagon has 6 sides."},
{sec:"G",type:"in",q:"How many sides does a quadrilateral have?",ans:4,
 expl:"'Quad' means four — a quadrilateral always has 4 sides."},
{sec:"G",type:"mc",q:"Which fact is true about a shape no matter where you draw it?",
 opts:["Number of sides","Its color","Where it is drawn","Its size on the page"],a:0,
 expl:"The number of sides stays fixed no matter where or how you draw a shape — color and placement can change without changing what shape it is."},
{lvl:2,sec:"G",type:"in",q:"How many corners (vertices) does a pentagon have?",ans:5,
 expl:"A polygon always has the same number of corners as sides: 5."},
{lvl:2,sec:"G",type:"mc",q:"A shape has 4 sides and 4 corners. What is it called, in general?",
 opts:["A quadrilateral","A pentagon","A hexagon","A triangle"],a:0,
 expl:"Any 4-sided shape is a quadrilateral, whatever its specific type."},
{lvl:3,sec:"G",type:"mc",q:"A shape has one more side than a pentagon. What is it called?",
 opts:["Hexagon","Heptagon","Quadrilateral","Triangle"],a:0,
 expl:"A pentagon has 5 sides, so one more side makes 6 — a hexagon."}
],

"g2-rowcol": [
{sec:"G",type:"in",q:"A grid has 3 rows and 4 columns of squares. How many squares in total?",
 ans:12,expl:"3 × 4 = 12 squares."},
{sec:"G",type:"in",q:"A grid has 5 rows and 5 columns. How many squares?",ans:25,
 expl:"5 × 5 = 25 squares."},
{sec:"G",type:"mc",q:"Which describes an array with 2 rows and 6 columns?",
 opts:["12 squares in 2 rows of 6","8 squares","2 squares","6 rows of 2"],a:0,
 expl:"2 rows of 6 columns gives 2 × 6 = 12 squares."},
{sec:"G",type:"in",q:"A grid has 6 rows and 3 columns. How many squares?",ans:18,
 expl:"6 × 3 = 18 squares."},
{sec:"G",type:"mc",q:"If you add one more ROW to a 4-row, 5-column grid, how many rows are there now?",
 opts:["5","4","9","20"],a:0,expl:"4 rows plus 1 more row makes 5 rows."},
{lvl:2,sec:"G",type:"in",q:"A rectangle grid has 7 rows and 4 columns. How many squares total?",
 ans:28,expl:"7 × 4 = 28 squares."},
{lvl:2,sec:"G",type:"in",q:"A grid has 36 squares arranged in 6 equal rows. How many columns?",
 ans:6,expl:"36 ÷ 6 = 6 columns."},
{lvl:3,sec:"G",type:"in",q:"A grid has an equal number of rows and columns and has 49 squares total. How many rows does it have?",
 ans:7,hint:"What number times itself makes 49?",expl:"7 × 7 = 49, so there are 7 rows."}
],

"g2-thirds": [
{sec:"F",type:"mc",q:"A shape is split into 2 equal parts. Each part is called a ___.",
 opts:["half","third","fourth","whole"],a:0,expl:"Two equal parts are called halves."},
{sec:"F",type:"mc",q:"A shape is split into 3 equal parts. Each part is called a ___.",
 opts:["third","half","fourth","whole"],a:0,expl:"Three equal parts are called thirds."},
{sec:"F",type:"mc",q:"A shape is split into 4 equal parts. Each part is called a ___.",
 opts:["fourth","half","third","whole"],a:0,expl:"Four equal parts are called fourths (or quarters)."},
{sec:"F",type:"in",q:"How many thirds make one whole?",ans:3,expl:"1/3 + 1/3 + 1/3 = 1 whole, so 3 thirds."},
{sec:"F",type:"mc",q:"Which correctly shows a shape divided into EQUAL fourths?",
 opts:["4 same-size pieces","4 pieces of different sizes","2 pieces","3 pieces"],a:0,
 expl:"Fourths must be 4 pieces that are all the SAME size."},
{lvl:2,sec:"F",type:"in",q:"How many fourths make one whole?",ans:4,
 expl:"1/4 four times makes 4/4, which is 1 whole."},
{lvl:2,sec:"F",type:"mc",q:"A pizza is cut into 3 equal slices. What is each slice called?",
 opts:["a third","a half","a fourth","a whole"],a:0,expl:"Each of the 3 equal slices is a third of the pizza."},
{lvl:3,sec:"F",type:"mc",q:"Two same-size shapes are cut differently: one into halves, one into fourths. Which single piece is BIGGER?",
 opts:["A half","A fourth","They are the same","Cannot tell"],a:0,
 expl:"Cutting the same whole into fewer, bigger pieces (2 instead of 4) makes each piece larger."}
],

"g1-props": [
{sec:"P",type:"mc",q:"Which shows that ADDITION can be done in any order?",mono:true,
 opts:["3 + 5 = 5 + 3","3 + 5 = 8","3 − 5","3 × 5"],a:0,
 expl:"Swapping the order of the numbers being added never changes the sum."},
{sec:"P",type:"in",q:"If 4 + 6 = 10, what is 6 + 4?",ans:10,
 expl:"Addition works the same in either order, so 6 + 4 is also 10."},
{sec:"P",type:"mc",q:"Which shows grouping numbers differently without changing the sum?",mono:true,
 opts:["(2+3)+4 = 2+(3+4)","2+3 = 3+2","2+0 = 2","2+2 = 4"],a:0,
 expl:"Changing how the numbers are grouped with parentheses does not change the total."},
{sec:"P",type:"in",q:"3 + 7 = 10. What is 7 + 3?",ans:10,expl:"Swapping the order keeps the sum the same: 10."},
{sec:"P",type:"mc",q:"Adding zero to any number gives ___.",
 opts:["the same number","zero","a number twice as big","one more"],a:0,
 expl:"Adding 0 never changes the value of a number."},
{lvl:2,sec:"P",type:"in",q:"If (2 + 3) + 5 = 10, what is 2 + (3 + 5)?",ans:10,
 expl:"Regrouping the addends does not change the total."},
{lvl:2,sec:"P",type:"mc",q:"Which pair of additions always gives the SAME answer, whatever the numbers?",mono:true,
 opts:["a + b and b + a","a + b and a − b","a + 1 and a","a + 0 and a + 1"],a:0,
 expl:"a + b and b + a always match — that is what the commutative property means."},
{lvl:3,sec:"P",type:"in",q:"Using properties, if 8 + 6 + 2 = 16, what is 2 + 6 + 8?",ans:16,
 expl:"Reordering the same three addends never changes their sum."}
],

"g1-add100": [
{sec:"N",type:"in",q:"34 + 5 = ?",ans:39,expl:"34 + 5 = 39."},
{sec:"N",type:"in",q:"48 − 6 = ?",ans:42,expl:"48 − 6 = 42."},
{sec:"N",type:"in",q:"50 + 20 = ?",ans:70,expl:"50 + 20 = 70."},
{sec:"N",type:"mc",q:"What is 62 + 7?",opts:["69","70","68","72"],a:0,expl:"62 + 7 = 69."},
{sec:"N",type:"in",q:"90 − 30 = ?",ans:60,expl:"90 − 30 = 60."},
{lvl:2,sec:"N",type:"in",q:"37 + 25 = ?",ans:62,expl:"37 + 25 = 62."},
{lvl:2,sec:"N",type:"in",q:"76 − 19 = ?",ans:57,expl:"76 − 19 = 57."},
{lvl:3,sec:"N",type:"in",q:"A number plus 15 equals 82. What is the number?",ans:67,
 expl:"82 − 15 = 67."}
],

"g1-tenmore": [
{sec:"N",type:"in",q:"What is 10 more than 34?",ans:44,expl:"34 + 10 = 44."},
{sec:"N",type:"in",q:"What is 10 less than 67?",ans:57,expl:"67 − 10 = 57."},
{sec:"N",type:"in",q:"What is 10 more than 89?",ans:99,expl:"89 + 10 = 99."},
{sec:"N",type:"mc",q:"What is 10 less than 40?",opts:["30","50","41","39"],a:0,expl:"40 − 10 = 30."},
{sec:"N",type:"in",q:"What is 10 more than 95?",ans:105,expl:"95 + 10 = 105."},
{lvl:2,sec:"N",type:"in",q:"What is 20 more than 47? (think: 10 more, twice)",ans:67,
 expl:"47 + 10 = 57, then 57 + 10 = 67."},
{lvl:2,sec:"N",type:"in",q:"A number is 10 less than 82. What is it?",ans:72,expl:"82 − 10 = 72."},
{lvl:3,sec:"N",type:"in",q:"Start at 56. Add 10, then subtract 10, then add 10. What is the result?",
 ans:66,expl:"56 + 10 = 66, 66 − 10 = 56, 56 + 10 = 66."}
],

"g1-time": [
{sec:"M",type:"mc",q:"The short hand on a clock shows the ___.",
 opts:["hour","minute","second","day"],a:0,expl:"The short hand points to the current hour."},
{sec:"M",type:"mc",q:"The long hand on a clock shows the ___.",
 opts:["minutes","hour","day","month"],a:0,expl:"The long hand sweeps around to show the minutes."},
{sec:"M",type:"mc",q:"The minute hand points straight up, at 12. What do you read to find the hour?",
 opts:["The short hand's position","The color of the clock","The date","The day of the week"],a:0,
 expl:"Minute hand on 12 means exactly on the hour — read the short hand for which hour."},
{sec:"M",type:"mc",q:"Which time shows 'half past 3'?",mono:true,opts:["3:30","3:15","3:45","3:00"],a:0,
 expl:"'Half past' means 30 minutes after the hour."},
{sec:"M",type:"mc",q:"The short hand is between 7 and 8, and the long hand is on 12. What time is it?",mono:true,
 opts:["7:00","8:00","7:30","12:07"],a:0,
 expl:"The short hand between 7 and 8 with the minute hand at 12 means it is exactly 7:00 — the hour just started."},
{lvl:2,sec:"M",type:"mc",q:"Which is EARLIER: 2:00 or 2:30?",mono:true,
 opts:["2:00","2:30","They are the same","Cannot tell"],a:0,expl:"2:00 comes before 2:30 in the same hour."},
{lvl:2,sec:"M",type:"mc",q:"The long hand points to 6. What does that mean?",
 opts:["Half past the hour","The exact hour","Quarter past","Quarter to"],a:0,
 expl:"The 6 is halfway around the clock face, marking 30 minutes past the hour."},
{lvl:3,sec:"M",type:"mc",q:"It is half past 5. In one hour, what time will it be?",mono:true,
 opts:["Half past 6","6:00","5:30","Half past 4"],a:0,expl:"Adding one hour to 5:30 gives 6:30 — half past 6."}
],

"g1-graphs": [
{sec:"M",type:"in",q:"A bar graph shows 5 apples and 3 bananas. How many more apples than bananas?",
 ans:2,expl:"5 − 3 = 2 more apples."},
{sec:"M",type:"in",q:"A picture graph shows 4 pictures of cats, and each picture stands for 1 cat. How many cats?",
 ans:4,expl:"4 pictures, 1 cat each, means 4 cats."},
{sec:"M",type:"mc",q:"In a bar graph, a TALLER bar means ___.",
 opts:["a bigger amount","a smaller amount","the same amount always","nothing important"],a:0,
 expl:"Bar height shows the amount being counted — taller means more."},
{sec:"M",type:"in",q:"A graph shows: red = 6, blue = 4, green = 2. How many in total?",ans:12,
 expl:"6 + 4 + 2 = 12."},
{sec:"M",type:"mc",q:"Which question can a bar graph answer?",
 opts:["Which category has the most?","What color is the sky?","How old are you?","What is your name?"],a:0,
 expl:"A bar graph compares categories, so it can show which one has the most."},
{lvl:2,sec:"M",type:"in",q:"A graph shows dogs = 7, cats = 5. How many MORE dogs than cats?",ans:2,
 expl:"7 − 5 = 2 more dogs."},
{lvl:2,sec:"M",type:"in",q:"A graph shows 3 categories with 4, 6, and 2. What is the total?",ans:12,
 expl:"4 + 6 + 2 = 12."},
{lvl:3,sec:"M",type:"mc",q:"A graph shows 4 fruits: apples = 5, pears = 3, grapes = 8, plums = 2. Which two fruits add up to exactly 10?",
 opts:["Grapes and plums","Apples and pears","Apples and plums","Pears and plums"],a:0,
 expl:"Grapes (8) + plums (2) = 10. The other pairs add to 8, 7 and 5."}
],

"g1-attrib": [
{sec:"G",type:"mc",q:"Which is a defining fact about a triangle?",
 opts:["It has 3 sides","It is red","It is big","It is drawn on paper"],a:0,
 expl:"Having 3 sides is what makes a shape a triangle — color and size do not matter."},
{sec:"G",type:"mc",q:"Which of these can change WITHOUT a square stopping being a square?",
 opts:["Its color","Having 4 equal sides","Having 4 right angles","Being a quadrilateral"],a:0,
 expl:"Color has nothing to do with what shape something is — the sides and angles do."},
{sec:"G",type:"mc",q:"Which shape ALWAYS has exactly 4 sides?",
 opts:["A quadrilateral","A triangle","A pentagon","A circle"],a:0,
 expl:"'Quad' means four — every quadrilateral has exactly 4 sides."},
{sec:"G",type:"mc",q:"Two shapes both have 3 sides and 3 corners. What must be true?",
 opts:["Both are triangles","Both are the same size","Both are the same color","Both are squares"],a:0,
 expl:"3 sides and 3 corners is the definition of a triangle, no matter the size or color."},
{sec:"G",type:"mc",q:"Which of these tells you something about the shape itself, not just how it looks on the page?",
 opts:["Number of corners","How it is rotated","Its color","Where it sits on the page"],a:0,
 expl:"The number of corners stays the same no matter how the shape is turned, colored or placed."},
{lvl:2,sec:"G",type:"mc",q:"A shape has 4 sides but they are not all equal. Could it still be a quadrilateral?",
 opts:["Yes, any 4-sided shape is a quadrilateral","No, sides must be equal","No, it needs right angles","Only if it's a square"],a:0,
 expl:"A quadrilateral only needs 4 sides — nothing requires them to be equal."},
{lvl:2,sec:"G",type:"mc",q:"Which pair of shapes share a defining fact?",
 opts:["A square and a rectangle both have 4 right angles","A triangle and a circle both have 3 sides","A pentagon and a square have the same number of sides","A hexagon and a triangle have the same number of corners"],a:0,
 expl:"Both a square and a rectangle always have 4 right angles."},
{lvl:3,sec:"G",type:"mc",q:"A shape has exactly 3 sides and 3 angles that are ALL different sizes. What could it be?",
 opts:["A scalene triangle","A square","An equilateral triangle","A quadrilateral"],a:0,
 expl:"A scalene triangle has 3 sides and 3 angles that are all different from each other."}
],

"g1-compose": [
{sec:"G",type:"mc",q:"Two matching triangles put side by side can make a ___.",
 opts:["square or rectangle","circle","single triangle only","pentagon always"],a:0,
 expl:"Two matching triangles joined along one side can form a rectangle."},
{sec:"G",type:"mc",q:"Putting shapes together to build one new shape is called ___.",
 opts:["building with shapes","cutting a shape","coloring a shape","naming a shape"],a:0,
 expl:"Joining small shapes together to build a new, bigger one is how shapes get composed."},
{sec:"G",type:"mc",q:"Which two shapes can join to make a rectangle?",
 opts:["Two matching triangles","Two circles","A circle and a triangle","Two pentagons"],a:0,
 expl:"Two matching triangles, joined along their longest side, fit together into a rectangle."},
{sec:"G",type:"mc",q:"You put a triangle on top of a square, side to side. What new shape do you get?",
 opts:["A house shape with 5 sides","A circle","A single square","Nothing new"],a:0,
 expl:"A triangle roof on a square base makes a 5-sided house shape."},
{sec:"G",type:"mc",q:"Building a new shape out of smaller shapes is called ___.",
 opts:["putting shapes together","taking a shape apart","coloring a shape","measuring a shape"],a:0,
 expl:"Putting pieces together to build something new is what it means to compose shapes."},
{lvl:2,sec:"G",type:"mc",q:"A big triangle is split evenly into 4 small ones. How many small triangles are there?",
 opts:["4","2","3","6"],a:0,
 expl:"Splitting one triangle evenly into 4 parts gives 4 small triangles."},
{lvl:2,sec:"G",type:"mc",q:"6 matching triangles are placed point to point around one center dot. What shape do they make?",
 opts:["A hexagon","A single triangle","A square","A line"],a:0,
 expl:"6 matching triangles placed around one center point form a hexagon."},
{lvl:3,sec:"G",type:"mc",q:"You build one big square from 4 small matching squares, 2 rows of 2. Each small square's side is 2 units. What is the big square's side?",
 opts:["4","2","8","6"],a:0,
 expl:"Two small squares side by side span 2 + 2 = 4 units — the big square's side."}
],

"g1-shares": [
{sec:"F",type:"mc",q:"Cutting a shape into 2 EQUAL parts gives ___.",
 opts:["halves","thirds","fourths","wholes"],a:0,expl:"Two equal parts are called halves."},
{sec:"F",type:"mc",q:"Cutting a shape into 4 EQUAL parts gives ___.",
 opts:["fourths","halves","thirds","wholes"],a:0,expl:"Four equal parts are called fourths."},
{sec:"F",type:"in",q:"How many halves make one whole?",ans:2,expl:"1/2 + 1/2 = 1 whole, so 2 halves."},
{sec:"F",type:"mc",q:"Which shows a shape split into EQUAL halves?",
 opts:["Two same-size pieces","Two different-size pieces","Three pieces","Four pieces"],a:0,
 expl:"Halves must be the same size — that is what makes them equal shares."},
{sec:"F",type:"in",q:"How many fourths make one whole?",ans:4,expl:"1/4 four times makes 4/4, or 1 whole."},
{lvl:2,sec:"F",type:"mc",q:"A sandwich is cut into 2 pieces, but one is bigger than the other. Are these halves?",
 opts:["No, halves must be equal","Yes, any 2 pieces are halves","Yes, if there are 2 pieces","Cannot tell"],a:0,
 expl:"'Halves' specifically means equal parts — unequal pieces are not halves, even if there are 2 of them."},
{lvl:2,sec:"F",type:"mc",q:"Which shows a fair, equal share of one pizza among 4 friends?",
 opts:["Each friend gets 1/4 of the pizza","One friend gets the whole pizza","Each friend gets a different-sized piece","Only 2 friends get pizza"],a:0,
 expl:"A fair share among 4 means everyone gets an equal fourth."},
{lvl:3,sec:"F",type:"mc",q:"Two same-size shapes are shared differently: one cut into fourths, one into halves. Which single piece is BIGGER?",
 opts:["A half","A fourth","They are the same","Cannot tell"],a:0,
 expl:"Fewer, bigger pieces (2 instead of 4) means each piece is larger — a half beats a fourth."}
]
};
