/* Grades 1 and 2. */
export const G12_BANKS = {
"g1-add20": [
{sec:"N",type:"in",q:"8 + 5 = ?",ans:13,hint:"Make ten first: 8 + 2 = 10.",
 expl:"Split the 5 into 2 and 3. 8 + 2 = 10, then 10 + 3 = 13."},
{sec:"N",type:"in",q:"9 + 6 = ?",ans:15,hint:"Make ten first.",
 expl:"9 + 1 = 10, and 5 remains, so 10 + 5 = 15."},
{sec:"N",type:"in",q:"7 + 7 = ?",ans:14,expl:"A double: 7 + 7 = 14."},
{sec:"N",type:"in",q:"12 + 4 = ?",ans:16,expl:"Count on 4 from 12: 13, 14, 15, 16."},
{sec:"N",type:"mc",q:"Which one makes 20?",mono:true,opts:["13 + 7","13 + 6","12 + 7","14 + 5"],a:0,
 expl:"13 + 7 = 20. The others give 19, 19 and 19."},
{lvl:2,sec:"N",type:"in",q:"6 + 7 + 4 = ?",ans:17,hint:"Look for a pair that makes ten.",
 expl:"6 + 4 = 10 first, then 10 + 7 = 17. Reordering makes it easier."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY sum that equals 15.",
 opts:["8 + 7","9 + 6","7 + 9","10 + 4"],aMulti:[0,1],
 expl:"8 + 7 = 15 and 9 + 6 = 15. But 7 + 9 = 16 and 10 + 4 = 14."},
{lvl:3,sec:"N",type:"in",q:"Ana has 9 stickers. Ben has 4 more than Ana. How many do they have altogether?",
 ans:22,hint:"Work out Ben's first.",
 expl:"Ben has 9 + 4 = 13. Together: 9 + 13 = 22 stickers."}
],

"g1-tensones": [
{sec:"N",type:"in",q:"How many tens are in 47?",ans:4,hint:"Look at the first digit.",
 expl:"47 is 4 tens and 7 ones, so there are 4 tens."},
{sec:"N",type:"in",q:"How many ones are in 63?",ans:3,expl:"63 is 6 tens and 3 ones."},
{sec:"N",type:"in",q:"What number is 5 tens and 2 ones?",ans:52,
 expl:"5 tens is 50, plus 2 ones makes 52."},
{sec:"N",type:"mc",q:"Which number has 8 tens?",mono:true,opts:["83","38","8","18"],a:0,
 expl:"83 is 8 tens and 3 ones. In 38 the 8 is the ones digit."},
{lvl:2,sec:"N",type:"in",q:"What number is 3 tens and 14 ones?",ans:44,
 hint:"14 ones is more than a ten.",
 expl:"14 ones is 1 ten and 4 ones, so altogether 4 tens and 4 ones — that is 44."},
{lvl:3,sec:"N",type:"in",q:"I am a two-digit number. My tens digit is 2 more than my ones digit, and my digits add to 10. What number am I?",
 ans:64,hint:"Which two digits add to 10 and differ by 2?",
 expl:"6 and 4 add to 10 and differ by 2. The tens digit is the bigger one, so the number is 64."}
],

"g2-arrays": [
{sec:"N",type:"in",q:"An array has 3 rows of 4. How many altogether?",ans:12,
 hint:"Add 4 three times, or count the rows.",expl:"3 rows of 4 is 4 + 4 + 4 = 12."},
{sec:"N",type:"in",q:"An array has 5 rows of 2. How many altogether?",ans:10,
 expl:"5 rows of 2 is 2 + 2 + 2 + 2 + 2 = 10."},
{sec:"N",type:"mc",q:"Which addition matches an array of 4 rows of 5?",mono:true,
 opts:["5 + 5 + 5 + 5","4 + 4 + 4 + 4 + 4","4 + 5","5 + 4 + 5"],a:0,
 expl:"4 rows of 5 means adding 5 four times: 5 + 5 + 5 + 5 = 20."},
{lvl:2,sec:"N",type:"in",q:"An array of counters has 4 rows and 6 in each row. How many counters?",ans:24,
 expl:"4 rows of 6 is 6 + 6 + 6 + 6 = 24."},
{lvl:2,sec:"N",type:"mc",q:"An array has 12 counters in 3 equal rows. How many are in each row?",
 mono:true,opts:["4","3","6","12"],a:0,expl:"12 shared into 3 equal rows gives 4 in each row."},
{lvl:3,sec:"N",type:"in",q:"A box holds 5 rows of 4 chocolates. Two chocolates are eaten. How many are left?",
 ans:18,hint:"Work out the whole box first.",
 expl:"5 rows of 4 is 20 chocolates. After eating 2, there are 18 left."}
],

"g2-place1000": [
{sec:"N",type:"in",q:"How many hundreds are in 372?",ans:3,expl:"372 is 3 hundreds, 7 tens and 2 ones."},
{sec:"N",type:"in",q:"What number is 4 hundreds, 0 tens and 6 ones?",ans:406,
 hint:"The zero holds the tens place.",
 expl:"400 + 0 + 6 = 406. The 0 is important — without it you would write 46."},
{sec:"N",type:"mc",q:"Which number is the largest?",mono:true,opts:["519","591","195","159"],a:1,
 expl:"Compare hundreds first: 519 and 591 both have 5 hundreds. Then tens: 9 beats 1, so 591 is largest."},
{lvl:2,sec:"N",type:"order",q:"Put these in order, smallest first.",
 items:["408","480","84","840"],ansOrder:["84","408","480","840"],
 expl:"84 has no hundreds. Then 408, 480 and 840 compare by hundreds, then tens."},
{lvl:2,sec:"N",type:"in",q:"What is 10 more than 295?",ans:305,hint:"Watch the tens roll over.",
 expl:"295 + 10 = 305. The 9 tens become 10 tens, which makes a new hundred."},
{lvl:3,sec:"N",type:"in",q:"Using the digits 7, 2 and 5 once each, what is the largest three-digit number you can make?",
 ans:752,hint:"Put the biggest digit where it counts most.",
 expl:"The hundreds place matters most, so put 7 there, then 5, then 2: 752."}
],

"g1-sub20": [
{sec:"N",type:"in",q:"15 − 6 = ?",ans:9,hint:"Count back, or find the ten first.",
 expl:"15 − 5 = 10, then one more back: 10 − 1 = 9."},
{sec:"N",type:"in",q:"12 − 5 = ?",ans:7,expl:"12 − 2 = 10, then 10 − 3 = 7."},
{sec:"N",type:"in",q:"18 − 9 = ?",ans:9,expl:"18 − 9 = 9 — taking away 9 from 18 leaves 9."},
{sec:"N",type:"in",q:"14 − 8 = ?",ans:6,hint:"Make ten first.",expl:"14 − 4 = 10, then 10 − 4 = 6."},
{sec:"N",type:"mc",q:"Which is the same as 16 − 7?",mono:true,opts:["9","8","10","7"],a:0,
 expl:"16 − 7 = 9. The others come from different subtractions."},
{lvl:2,sec:"N",type:"in",q:"9 + 7 − 3 = ?",ans:13,hint:"Add first, then subtract.",
 expl:"9 + 7 = 16, then 16 − 3 = 13."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY problem that equals 8.",
 opts:["15 − 7","12 − 4","11 − 4","16 − 8"],aMulti:[0,1,3],
 expl:"15 − 7 = 8, 12 − 4 = 8 and 16 − 8 = 8. But 11 − 4 = 7."},
{lvl:3,sec:"W",type:"in",q:"Maya had 17 candies. She gave away 9. Then she got 4 more. How many does she have now?",
 ans:12,hint:"Subtract first, then add.",
 expl:"17 − 9 = 8, then 8 + 4 = 12."}
],

"g1-equals": [
{sec:"P",type:"mc",q:"What number makes this true?  5 + 3 = 4 + __",
 opts:["4","3","8","5"],a:0,
 expl:"5 + 3 = 8, so the other side needs to make 8 too: 4 + 4 = 8."},
{sec:"P",type:"in",q:"6 + 2 = __ + 5",ans:3,hint:"Work out the left side first.",
 expl:"6 + 2 = 8, and 8 = __ + 5 means __ = 3."},
{sec:"P",type:"mc",q:"Which of these is a TRUE equation?",mono:true,
 opts:["7 = 3 + 4","7 = 3 + 5","7 = 2 + 6","7 = 1 + 7"],a:0,
 expl:"3 + 4 = 7, so that one is true. The others make 8."},
{sec:"P",type:"in",q:"9 = __ + 4",ans:5,expl:"9 = 5 + 4, so the missing number is 5."},
{sec:"P",type:"mc",q:"The equal sign (=) means ___.",
 opts:["both sides have the same value","the answer comes next","add the numbers","the bigger number wins"],a:0,
 expl:"An equal sign says the amount on the left is the same as the amount on the right — it is a balance, not just 'here comes the answer'."},
{lvl:2,sec:"P",type:"in",q:"8 + 6 = 10 + __",ans:4,hint:"Work out the left side first.",
 expl:"8 + 6 = 14, and 10 + 4 = 14, so the missing number is 4."},
{lvl:2,sec:"P",type:"mc",q:"Which equation is FALSE?",mono:true,
 opts:["9 = 5 + 4","9 = 6 + 3","9 = 7 + 1","9 = 2 + 7"],a:2,
 expl:"7 + 1 = 8, not 9 — that one is false. The rest all make 9."},
{lvl:3,sec:"P",type:"in",q:"A balance shows 12 + 5 on one side. What number balances it on 9 + __?",
 ans:8,hint:"Work out 12 + 5 first.",
 expl:"12 + 5 = 17, and 9 + 8 = 17, so the missing number is 8."}
],

"g1-wordprob": [
{sec:"W",type:"in",q:"Sam has 8 apples. He gets some more and now has 13. How many did he get?",
 ans:5,hint:"Think about what was added.",expl:"13 − 8 = 5 more apples."},
{sec:"W",type:"in",q:"There are 15 birds in a tree. 6 fly away. How many are left?",
 ans:9,expl:"15 − 6 = 9 birds left."},
{sec:"W",type:"mc",q:"Which number sentence matches: 'Lily had some stickers, gave away 4, and has 9 left'?",
 mono:true,opts:["__ − 4 = 9","__ + 4 = 9","9 − 4 = __","4 − __ = 9"],a:0,
 expl:"She started with an unknown amount, 4 were taken away, and 9 remained: __ − 4 = 9."},
{sec:"W",type:"in",q:"A box had some pencils. 7 were added, making 16. How many were in the box at the start?",
 ans:9,hint:"Work backwards.",expl:"16 − 7 = 9 pencils to start."},
{sec:"W",type:"mc",q:"Which shows the unknown correctly for: 'I have 6 red marbles and some blue marbles, 14 in total. How many blue?'",
 opts:["6 + __ = 14","__ + 14 = 6","14 + 6 = __","6 − __ = 14"],a:0,
 expl:"The two amounts must add to the total: 6 + __ = 14."},
{lvl:2,sec:"W",type:"in",q:"There were 20 fish in a tank. Some swam into a net, leaving 12. How many swam into the net?",
 ans:8,expl:"20 − 12 = 8 fish."},
{lvl:2,sec:"W",type:"in",q:"Emma had 9 crayons. She got 6 more, then gave 4 away. How many does she have now?",
 ans:11,hint:"Do it in order: add, then subtract.",
 expl:"9 + 6 = 15, then 15 − 4 = 11."},
{lvl:3,sec:"W",type:"in",q:"A farmer had some chickens. 8 hatched, then 3 were sold, leaving 19. How many did the farmer start with?",
 ans:14,hint:"Work backwards from 19.",
 expl:"Undo the sale first: 19 + 3 = 22. Then undo the hatching: 22 − 8 = 14."}
],

"g1-compare2": [
{sec:"N",type:"mc",q:"Which symbol makes this true?  47 ◯ 52",mono:true,opts:["<",">","="],a:0,
 expl:"47 has fewer tens than 52, so 47 < 52."},
{sec:"N",type:"mc",q:"Which symbol makes this true?  63 ◯ 36",mono:true,opts:["<",">","="],a:1,
 expl:"63 has 6 tens and 36 has 3 tens, so 63 > 36."},
{sec:"N",type:"mc",q:"Which number is greater than 45 but less than 50?",mono:true,
 opts:["47","44","51","40"],a:0,expl:"47 sits between 45 and 50. The others are outside that range."},
{sec:"N",type:"order",q:"Put these numbers in order, smallest first.",
 items:["28","82","19","91"],ansOrder:["19","28","82","91"],
 expl:"Compare the tens digit first: 1, 2, 8, 9 tens gives this order."},
{sec:"N",type:"mc",q:"Which symbol makes this true?  70 ◯ 69 + 1",mono:true,opts:["<",">","="],a:2,
 expl:"69 + 1 = 70, and 70 equals 70, so the symbol is =."},
{lvl:2,sec:"N",type:"order",q:"These numbers all have 5 tens. Put them in order, smallest first.",
 items:["53","58","51","55"],ansOrder:["51","53","55","58"],
 expl:"All have 5 tens, so compare the ones digit: 1, 3, 5, 8."},
{lvl:3,sec:"N",type:"mc",q:"Which number is between 34 and 41, and greater than 38?",mono:true,
 opts:["39","34","41","33"],a:0,
 expl:"39 is bigger than 34 and smaller than 41, and it is also bigger than 38."}
],

"g1-length": [
{sec:"M",type:"mc",q:"Which is the BEST tool to measure the length of your pencil?",
 opts:["a ruler","a scale","a clock","a thermometer"],a:0,
 expl:"A ruler measures length. A scale measures weight, a clock measures time."},
{sec:"M",type:"in",q:"A crayon is 6 cubes long. Another is 4 cubes long. How many MORE cubes long is the first crayon?",
 ans:2,expl:"6 − 4 = 2 cubes longer."},
{sec:"M",type:"mc",q:"Which object is LONGER?",mono:true,
 opts:["a school bus","a shoe","they are the same","you cannot tell"],a:0,
 expl:"A school bus is far longer than a shoe."},
{sec:"M",type:"in",q:"You measure a book using paperclips laid end to end. It takes 8 paperclips. How many paperclips long is the book?",
 ans:8,expl:"The book is 8 paperclips long — that is what 'measuring with paperclips' means."},
{sec:"M",type:"order",q:"Order these pencils from SHORTEST to longest, by their length in cubes.",
 items:["9 cubes","3 cubes","6 cubes","1 cube"],ansOrder:["1 cube","3 cubes","6 cubes","9 cubes"],
 expl:"Compare the numbers: 1, 3, 6, 9 cubes, smallest first."},
{lvl:2,sec:"M",type:"in",q:"Table A is 12 spans long. Table B is 15 spans long. How many spans LONGER is Table B?",
 ans:3,expl:"15 − 12 = 3 spans longer."},
{lvl:2,sec:"M",type:"mc",q:"Why might two people measure the same desk and get a different number of spans?",
 opts:["Their hands are different sizes","The desk changed size","One of them cannot count","Desks cannot be measured"],a:0,
 expl:"A hand-span is not a fixed unit — bigger hands mean fewer spans are needed, so the count changes person to person."},
{lvl:3,sec:"M",type:"in",q:"A ribbon is 14 paperclips long. A longer clip is twice as long as a paperclip. How many long clips measure the same ribbon?",
 ans:7,hint:"A bigger unit means a smaller count.",
 expl:"Each long clip covers 2 paperclip-lengths, so 14 ÷ 2 = 7 long clips."}
],

"g2-fluency": [
{sec:"N",type:"in",q:"13 − 6 = ?",ans:7,expl:"13 − 6 = 7."},
{sec:"N",type:"in",q:"9 + 8 = ?",ans:17,expl:"9 + 8 = 17."},
{sec:"N",type:"mc",q:"Which pair makes 16?",mono:true,opts:["9 + 7","8 + 9","7 + 7","6 + 9"],a:0,
 expl:"9 + 7 = 16. 8 + 9 = 17, 7 + 7 = 14, 6 + 9 = 15."},
{sec:"N",type:"in",q:"17 − 9 = ?",ans:8,expl:"17 − 9 = 8."},
{sec:"N",type:"in",q:"6 + 6 + 3 = ?",ans:15,hint:"Add the double first.",expl:"6 + 6 = 12, then 12 + 3 = 15."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY problem that equals 9.",
 opts:["15 − 6","14 − 4","18 − 9","12 − 3"],aMulti:[0,2,3],
 expl:"15 − 6 = 9, 18 − 9 = 9 and 12 − 3 = 9. But 14 − 4 = 10."},
{lvl:2,sec:"N",type:"in",q:"14 − 8 + 5 = ?",ans:11,hint:"Work left to right.",expl:"14 − 8 = 6, then 6 + 5 = 11."},
{lvl:3,sec:"W",type:"in",q:"A jar had 20 marbles. 8 were taken out, then 6 were put back. How many are in the jar now?",
 ans:18,expl:"20 − 8 = 12, then 12 + 6 = 18."}
],

"g2-add1000": [
{sec:"N",type:"in",q:"236 + 145 = ?",ans:381,expl:"236 + 145 = 381."},
{sec:"N",type:"in",q:"580 − 235 = ?",ans:345,expl:"580 − 235 = 345."},
{sec:"N",type:"mc",q:"What is 407 + 198?",opts:["605","505","615","595"],a:0,
 expl:"407 + 198 = 605. (198 is close to 200: 407 + 200 = 607, minus 2 = 605.)"},
{sec:"N",type:"in",q:"912 − 358 = ?",ans:554,expl:"912 − 358 = 554."},
{sec:"N",type:"in",q:"265 + 340 = ?",ans:605,expl:"265 + 340 = 605."},
{lvl:2,sec:"W",type:"in",q:"A school has 384 students. 129 more enroll. How many students are there now?",
 ans:513,expl:"384 + 129 = 513."},
{lvl:2,sec:"W",type:"in",q:"A shop had 700 apples. It sold 268. How many are left?",
 ans:432,expl:"700 − 268 = 432."},
{lvl:3,sec:"N",type:"in",q:"Two numbers add to 963. One of the numbers is 428. What is the other number?",
 ans:535,hint:"Subtract the known number from the total.",expl:"963 − 428 = 535."}
],

"g2-money": [
{sec:"MNY",type:"in",q:"You have $3.25. You spend $1.10. How much is left, in dollars? Type just the number, like 2.15.",
 ans:2.15,expl:"$3.25 − $1.10 = $2.15."},
{sec:"MNY",type:"in",q:"A pencil costs $0.45 and an eraser costs $0.30. What is the total cost, in dollars?",
 ans:0.75,expl:"$0.45 + $0.30 = $0.75."},
{sec:"MNY",type:"mc",q:"You have $5.00 and buy a toy for $3.40. How much change do you get?",
 opts:["$1.60","$1.40","$2.60","$8.40"],a:0,expl:"$5.00 − $3.40 = $1.60."},
{sec:"MNY",type:"in",q:"You have 2 one-dollar bills and 3 quarters. How much money in dollars? Type just the number.",
 ans:2.75,expl:"2 dollars is $2.00, and 3 quarters is $0.75. Together: $2.75."},
{sec:"MNY",type:"in",q:"A book costs $4.50 and a bookmark costs $0.75. What is the total, in dollars?",
 ans:5.25,expl:"$4.50 + $0.75 = $5.25."},
{lvl:2,sec:"MNY",type:"in",q:"You buy 3 pencils at $0.50 each. How much do you spend in total, in dollars?",
 ans:1.5,expl:"3 × $0.50 = $1.50."},
{lvl:2,sec:"MNY",type:"in",q:"You have $10. You spend $3.75 and $2.50. How much is left, in dollars?",
 ans:3.75,hint:"Subtract both amounts.",expl:"$10.00 − $3.75 − $2.50 = $3.75."},
{lvl:3,sec:"MNY",type:"in",q:"You buy a shirt for $12.99 and pay with a $20 bill. How much change do you get, in dollars?",
 ans:7.01,expl:"$20.00 − $12.99 = $7.01."}
]
};
