/* Grade 2, second bank: fluency, place value to 1000, measurement, time,
   money, line plots, shapes and fractions, plus enrichment in number theory,
   early multiplication, algebraic thinking, combinatorics and symmetry.
   Sentences stay short and concrete; numbers stay within 1000. */
export const G2_MORE_BANKS = {
"g2-fluency": [
{sec:"N",type:"in",q:"13 − 7 = ?",ans:6,expl:"Think 7 + 6 = 13, so 13 − 7 = 6."},
{sec:"N",type:"in",q:"8 + 9 = ?",ans:17,hint:"Make a ten first.",expl:"8 + 2 = 10, then 10 + 7 = 17."},
{sec:"N",type:"mc",q:"Which fact helps you solve 15 − 8?",mono:true,opts:["8 + 7 = 15","8 + 8 = 16","15 + 8 = 23"],a:0,
 expl:"15 − 8 asks what plus 8 makes 15. Since 8 + 7 = 15, the answer is 7."},
{sec:"N",type:"in",q:"Mei has 9 stickers. Kofi gives her 6 more. How many stickers does Mei have now?",ans:15,
 expl:"9 + 6 = 15 stickers."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY fact that makes 14.",mono:true,opts:["6 + 8","9 + 5","7 + 6","5 + 9"],aMulti:[0,1,3],
 expl:"6 + 8 = 14, 9 + 5 = 14 and 5 + 9 = 14. 7 + 6 is only 13."},
{lvl:2,sec:"N",type:"in",q:"17 − 9 = ?",ans:8,hint:"Take away 7 to reach 10, then take the rest.",
 expl:"17 − 7 = 10, then 10 − 2 = 8."},
{lvl:2,sec:"N",type:"mc",q:"Which has the same answer as 6 + 7?",mono:true,opts:["5 + 8","6 + 6","7 + 7","8 + 4"],a:0,
 expl:"6 + 7 = 13 and 5 + 8 = 13. The others make 12, 14 and 12."},
{lvl:3,sec:"N",type:"in",q:"Ravi had some marbles. He lost 8 and has 7 left. How many marbles did he start with?",ans:15,
 hint:"Put the lost ones back.",expl:"7 left plus the 8 lost: 7 + 8 = 15 marbles."},
{lvl:3,sec:"N",type:"in",q:"Zainab has 5 red, 6 blue and 4 green beads. How many beads in all?",ans:15,
 hint:"Add the three numbers one at a time.",expl:"5 + 6 = 11, then 11 + 4 = 15 beads."}
],

"g2-equalgrp": [
{sec:"N",type:"in",q:"There are 3 bags with 4 apples in each. How many apples in all?",ans:12,
 expl:"4 + 4 + 4 = 12 apples."},
{sec:"N",type:"mc",q:"Which shows 5 groups of 2?",mono:true,opts:["2 + 2 + 2 + 2 + 2","5 + 2","2 + 5 + 2","5 + 5"],a:0,
 expl:"5 groups of 2 means 2 added five times: 2 + 2 + 2 + 2 + 2 = 10."},
{sec:"N",type:"in",q:"4 plates each hold 5 cookies. How many cookies are there?",ans:20,
 expl:"5 + 5 + 5 + 5 = 20 cookies."},
{sec:"N",type:"mc",q:"Which shows equal groups?",
 opts:["3 boxes with 6 pens each","Boxes with 2, 5 and 6 pens","One box with 8 pens, one empty"],a:0,
 expl:"Equal groups have the same number in every group. Three boxes of 6 pens are equal groups."},
{lvl:2,sec:"N",type:"in",q:"Tomas puts 18 toy cars into 3 equal groups. How many cars in each group?",ans:6,
 hint:"Share them out one at a time.",expl:"6 + 6 + 6 = 18, so each group has 6 cars."},
{lvl:2,sec:"N",type:"in",q:"How many groups of 5 make 25?",ans:5,
 expl:"Count in fives: 5, 10, 15, 20, 25. That is 5 groups."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY total you can make with equal groups of 3.",opts:["9","12","10","15"],aMulti:[0,1,3],
 expl:"3, 6, 9, 12, 15 come from groups of 3. 10 does not."},
{lvl:3,sec:"N",type:"in",q:"Aisha has 2 bags of 6 shells and 3 bags of 4 shells. How many shells altogether?",ans:24,
 hint:"Find each kind of bag first.",expl:"2 bags of 6 make 12. 3 bags of 4 make 12. 12 + 12 = 24 shells."},
{lvl:3,sec:"N",type:"in",q:"Elias has 20 stickers. He makes groups of 4. How many groups does he make?",ans:5,
 hint:"Count up in fours until you reach 20.",expl:"4, 8, 12, 16, 20 — that is 5 groups of 4."}
],

"g2-compare3": [
{sec:"N",type:"mc",q:"Which number is greater: 342 or 324?",opts:["342","324","They are equal"],a:0,
 expl:"Both have 3 hundreds. 342 has 4 tens and 324 has 2 tens, so 342 is greater."},
{sec:"N",type:"mc",q:"Which sign makes this true?  517 __ 571",mono:true,opts:["<",">","="],a:0,
 expl:"Both have 5 hundreds. 1 ten is less than 7 tens, so 517 < 571."},
{sec:"N",type:"in",q:"Which is the smallest: 608, 680 or 806? Type the number.",ans:608,
 expl:"Compare hundreds first: 6, 6, 8. Then tens: 0 is less than 8. So 608 is smallest."},
{sec:"N",type:"order",q:"Put these numbers in order from smallest to largest.",
 items:["451","415","514","145"],ansOrder:["145","415","451","514"],
 expl:"145 has only 1 hundred. 415 and 451 both have 4 hundreds, and 1 ten is less than 5 tens. 514 is largest."},
{lvl:2,sec:"N",type:"mc",q:"Which number is between 299 and 301?",opts:["300","299","310","290"],a:0,
 expl:"300 is 1 more than 299 and 1 less than 301."},
{lvl:2,sec:"N",type:"mc",q:"Which sign makes this true?  700 + 30 __ 703",mono:true,opts:[">","<","="],a:0,
 expl:"700 + 30 = 730. 730 has 3 tens and 703 has 0 tens, so 730 > 703."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY number that is greater than 465.",opts:["470","456","500","465"],aMulti:[0,2],
 expl:"470 and 500 are greater than 465. 456 is less, and 465 is equal."},
{lvl:3,sec:"N",type:"in",q:"Ingrid writes the largest number she can with the digits 3, 8 and 5. What number is it?",ans:853,
 hint:"Put the biggest digit in the hundreds place.",expl:"Largest digit first: 8 hundreds, then 5 tens, then 3 ones. That is 853."},
{lvl:3,sec:"N",type:"mc",q:"Nadia's number has 6 hundreds and 2 ones. Which number could it be?",opts:["642","462","264","620"],a:0,
 hint:"Check the hundreds digit and the ones digit.",expl:"642 has 6 hundreds, 4 tens and 2 ones. The tens digit can be anything."}
],

"g2-add1000": [
{sec:"N",type:"in",q:"245 + 132 = ?",ans:377,expl:"Add hundreds, tens and ones: 300 + 70 + 7 = 377."},
{sec:"N",type:"in",q:"568 − 243 = ?",ans:325,expl:"500 − 200 = 300, 60 − 40 = 20, 8 − 3 = 5. Total 325."},
{sec:"N",type:"in",q:"376 + 258 = ?",ans:634,hint:"6 + 8 is more than 10, so regroup.",
 expl:"Ones: 6 + 8 = 14, write 4, carry 1. Tens: 7 + 5 + 1 = 13, write 3, carry 1. Hundreds: 3 + 2 + 1 = 6. Answer 634."},
{sec:"N",type:"mc",q:"Which is the best way to find 400 − 1?",
 opts:["Count back 1 from 400","Add 1 to 400","Take away 100"],a:0,
 expl:"Taking 1 away means counting back one: 400 − 1 = 399."},
{lvl:2,sec:"N",type:"in",q:"A shop had 436 hats. It sold 219. How many hats are left?",ans:217,
 expl:"436 − 219 = 217 hats."},
{lvl:2,sec:"N",type:"in",q:"Lior read 145 pages last week and 178 pages this week. How many pages in all?",ans:323,
 expl:"145 + 178 = 323 pages."},
{lvl:2,sec:"N",type:"mc",q:"Which is equal to 500 − 250?",mono:true,opts:["250","350","300","150"],a:0,
 expl:"250 + 250 = 500, so 500 − 250 = 250."},
{lvl:3,sec:"N",type:"in",q:"Amara had 320 stickers. She gave away 85, then got 140 more. How many does she have now?",ans:375,
 hint:"Do one step at a time.",expl:"320 − 85 = 235. Then 235 + 140 = 375 stickers."},
{lvl:3,sec:"N",type:"in",q:"What number added to 375 makes 1000?",ans:625,hint:"Count up to the next hundred first.",
 expl:"375 + 25 = 400, then 400 + 600 = 1000. 25 + 600 = 625."}
],

"g2-mental": [
{sec:"N",type:"in",q:"What is 10 more than 347?",ans:357,expl:"10 more changes the tens digit: 347 + 10 = 357."},
{sec:"N",type:"in",q:"What is 100 less than 620?",ans:520,expl:"100 less changes the hundreds digit: 620 − 100 = 520."},
{sec:"N",type:"in",q:"What is 10 less than 405?",ans:395,hint:"There are 0 tens, so think about the hundreds.",
 expl:"405 − 10 = 395. The 4 hundreds become 3 hundreds and 9 tens."},
{sec:"N",type:"mc",q:"Which digit changes when you add 100 to 253?",
 opts:["The hundreds digit","The tens digit","The ones digit"],a:0,
 expl:"Adding 100 adds one more hundred: 253 + 100 = 353. Only the hundreds digit changes."},
{lvl:2,sec:"N",type:"in",q:"Start at 590. Add 10. What number do you get?",ans:600,
 expl:"590 + 10 = 600. Ten tens make a new hundred."},
{lvl:2,sec:"N",type:"mc",q:"Which number is 100 more than 899?",opts:["999","900","989","1000"],a:0,
 expl:"899 + 100 = 999."},
{lvl:2,sec:"N",type:"order",q:"Put these in order from smallest to largest.",
 items:["10 more than 500","100 less than 500","10 less than 500"],
 ansOrder:["100 less than 500","10 less than 500","10 more than 500"],
 expl:"100 less than 500 is 400. 10 less is 490. 10 more is 510. So the order is 400, 490, 510."},
{lvl:3,sec:"N",type:"in",q:"Yusuf counts up by 100 from 350. What is the fourth number he says?",ans:750,
 hint:"The first number said is 450.",expl:"He says 450, 550, 650, 750. The fourth is 750."},
{lvl:3,sec:"N",type:"in",q:"Sofia thinks of a number. She adds 100, then takes away 10, and gets 490. What was her number?",ans:400,
 hint:"Work backwards from 490.",expl:"Undo the steps: 490 + 10 = 500, then 500 − 100 = 400."}
],

"g2-rulers": [
{sec:"M",type:"in",q:"A crayon starts at 0 on a ruler and ends at 9. How long is it in cm?",ans:9,
 expl:"From 0 to 9 on the ruler is 9 cm."},
{sec:"M",type:"in",q:"A pencil starts at the 2 cm mark and ends at the 14 cm mark. How long is it in cm?",ans:12,
 hint:"Count from 2, not from 0.",expl:"14 − 2 = 12, so the pencil is 12 cm long."},
{sec:"M",type:"mc",q:"Where should you line up the end of a stick to measure it?",
 opts:["At the 0 mark","At the 1 mark","Anywhere","At the end of the ruler"],a:0,
 expl:"Start at the 0 mark so the number you read is the true length."},
{sec:"M",type:"mc",q:"Which unit would you use to measure a book with a ruler?",
 opts:["Centimetres","Kilometres","Litres","Hours"],a:0,
 expl:"A ruler measures short lengths in centimetres. Kilometres are for long distances."},
{lvl:2,sec:"M",type:"in",q:"A ribbon is 25 cm long. Femi cuts off 8 cm. How long is the rest in cm?",ans:17,
 expl:"25 − 8 = 17 cm."},
{lvl:2,sec:"M",type:"mc",q:"Chioma measured a book as 20 cm with a short ruler. What would a longer ruler show?",
 opts:["20 cm","More than 20 cm","Less than 20 cm"],a:0,
 expl:"The book does not change size. Any ruler shows the same length, 20 cm."},
{lvl:2,sec:"M",type:"in",q:"Diego measured a leaf. It went from the 6 cm mark to the 11 cm mark. How long is it in cm?",ans:5,
 expl:"11 − 6 = 5 cm."},
{lvl:3,sec:"M",type:"in",q:"Two sticks lie end to end on a ruler, starting at 0. One is 7 cm and one is 9 cm. Where does the second stick end, in cm?",
 ans:16,hint:"Add the two lengths.",expl:"7 + 9 = 16, so the second stick ends at the 16 cm mark."},
{lvl:3,sec:"M",type:"in",q:"A rope is 40 cm long. It is cut into 4 equal pieces. How long is each piece in cm?",ans:10,
 hint:"4 equal pieces share the 40 cm.",expl:"10 + 10 + 10 + 10 = 40, so each piece is 10 cm."}
],


"g2-estimate": [
{sec:"M",type:"mc",q:"About how long is a new crayon?",opts:["About 9 cm","About 90 cm","About 9 m"],a:0,
 expl:"A crayon is a bit shorter than your hand. That is about 9 cm, not 90 cm or 9 m."},
{sec:"M",type:"mc",q:"Which is about 1 metre long?",opts:["A baseball bat","A paper clip","A car","A crayon"],a:0,
 expl:"A baseball bat is close to 1 metre. A paper clip is about 3 cm and a car is about 4 m."},
{sec:"M",type:"in",q:"Priya's hand is about 10 cm wide. A book is about 2 hands wide. About how many cm wide is the book?",ans:20,
 expl:"2 hands of 10 cm: 10 + 10 = 20 cm."},
{sec:"M",type:"mc",q:"Which unit is best to estimate the length of a playground?",opts:["Metres","Centimetres","Litres"],a:0,
 expl:"A playground is long, so metres fit best. Centimetres would give a huge number."},
{lvl:2,sec:"M",type:"in",q:"Mateo's step is about 50 cm. He takes 4 steps across a rug. About how many cm long is the rug?",ans:200,
 hint:"Add 50 four times.",expl:"4 steps of 50 cm: 50 + 50 + 50 + 50 = 200 cm."},
{lvl:2,sec:"M",type:"mc",q:"A pencil is about 15 cm. About how long is a table that is 6 pencils long?",
 opts:["About 90 cm","About 9 cm","About 900 cm"],a:0,
 expl:"15 + 15 = 30, and 30 + 30 + 30 = 90. The table is about 90 cm."},
{lvl:2,sec:"M",type:"multi",q:"Select EVERY object that is shorter than 10 cm.",opts:["A paper clip","A key","A bike","A bed"],aMulti:[0,1],
 expl:"A paper clip and a key are both a few cm long. A bike and a bed are longer than 1 m."},
{lvl:3,sec:"M",type:"in",q:"Hana estimates a rope is 60 cm. She measures and it is 8 cm longer. How long is the rope in cm?",ans:68,
 hint:"Add the extra length to her estimate.",expl:"60 + 8 = 68 cm."},
{lvl:3,sec:"M",type:"mc",q:"Wei guessed a shelf was 80 cm. It measured 1 m. How far off was the guess?",opts:["20 cm","80 cm","1 cm","120 cm"],a:0,
 hint:"Change 1 m into cm first.",expl:"1 m = 100 cm. 100 − 80 = 20, so the guess was 20 cm too short."}
],

"g2-time5": [
{sec:"M",type:"mc",q:"The hour hand is just past 3. The minute hand points to the 4. What time is it?",opts:["3:20","3:04","4:15","3:40"],a:0,
 expl:"Each number on the clock is 5 minutes. 4 numbers is 4 × 5 = 20 minutes, so it is 3:20."},
{sec:"M",type:"in",q:"The minute hand points to the 6. How many minutes past the hour is it?",ans:30,
 expl:"Count by fives to the 6: 5, 10, 15, 20, 25, 30. It is 30 minutes past."},
{sec:"M",type:"mc",q:"It is 7:45. Which number does the minute hand point to?",opts:["9","7","45","3"],a:0,
 expl:"45 minutes is 9 fives, so the minute hand points to the 9."},
{sec:"M",type:"mc",q:"Which is another way to say 2:30?",opts:["Half past 2","Quarter past 2","Half past 3"],a:0,
 expl:"30 minutes is half an hour. 2:30 is half past 2."},
{lvl:2,sec:"M",type:"in",q:"The minute hand points to the 11. How many minutes past the hour is it?",ans:55,
 hint:"Count by fives all the way round to the 11.",expl:"11 fives: 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55. It is 55 minutes past."},
{lvl:2,sec:"M",type:"mc",q:"Leila wakes at 6:50. Which time is 10 minutes later?",opts:["7:00","6:60","7:10","6:40"],a:0,
 expl:"50 + 10 = 60 minutes, which is a whole hour. So 6:50 plus 10 minutes is 7:00."},
{lvl:2,sec:"M",type:"mc",q:"Which time is quarter to 5?",opts:["4:45","5:15","4:15","5:45"],a:0,
 expl:"Quarter to 5 is 15 minutes before 5:00. That is 4:45."},
{lvl:2,sec:"M",type:"multi",q:"Select EVERY time that is between 4:00 and 5:00.",opts:["4:35","4:05","5:10","3:55"],aMulti:[0,1],
 expl:"4:35 and 4:05 are after 4:00 and before 5:00. 5:10 is after 5:00 and 3:55 is before 4:00."},
{lvl:3,sec:"M",type:"in",q:"Arjun's bus leaves at 8:05. He gets to the stop at 7:50. How many minutes does he wait?",ans:15,
 hint:"Count up to 8:00 first, then keep going.",expl:"7:50 to 8:00 is 10 minutes. 8:00 to 8:05 is 5 more. 10 + 5 = 15 minutes."},
{lvl:3,sec:"M",type:"mc",q:"A film starts at 3:25 and lasts 30 minutes. What time does it end?",opts:["3:55","3:35","4:25","3:50"],a:0,
 hint:"Add the minutes to 25.",expl:"25 + 30 = 55 minutes. The film ends at 3:55."},
{lvl:3,sec:"M",type:"in",q:"The minute hand moves from the 2 to the 7. How many minutes passed?",ans:25,
 hint:"Each number it passes is 5 minutes.",expl:"From the 2 to the 7 is 5 numbers. 5 × 5 = 25 minutes."}
],

"g2-money": [
{sec:"M",type:"in",q:"A dime is 10 cents and a nickel is 5 cents. How many cents is 1 dime and 1 nickel?",ans:15,
 expl:"10 + 5 = 15 cents."},
{sec:"M",type:"in",q:"Oluwaseun has 3 quarters. A quarter is 25 cents. How many cents does she have?",ans:75,
 expl:"25 + 25 + 25 = 75 cents."},
{sec:"M",type:"mc",q:"Which coins make 30 cents?",opts:["3 dimes","3 nickels","2 dimes and 1 penny","1 quarter and 1 penny"],a:0,
 expl:"3 dimes are 10 + 10 + 10 = 30 cents. The others make 15, 21 and 26 cents."},
{sec:"M",type:"in",q:"A toy costs $4. Sofia pays with a $5 bill. How many dollars does she get back?",ans:1,
 expl:"5 − 4 = 1 dollar back."},
{lvl:2,sec:"M",type:"in",q:"Zainab buys a pen for 35 cents and a card for 45 cents. How many cents does she spend?",ans:80,
 expl:"35 + 45 = 80 cents."},
{lvl:2,sec:"M",type:"in",q:"Diego has 2 quarters, 1 dime and 3 pennies. How many cents in all?",ans:63,
 hint:"Start with the quarters, then add the rest.",expl:"25 + 25 = 50, 50 + 10 = 60, 60 + 3 = 63 cents."},
{lvl:2,sec:"M",type:"mc",q:"Which is worth the most?",opts:["5 dimes","6 nickels","1 quarter and 2 dimes","45 pennies"],a:0,
 expl:"5 dimes = 50 cents. 6 nickels = 30, a quarter and 2 dimes = 45, and 45 pennies = 45. So 5 dimes is most."},
{lvl:2,sec:"M",type:"order",q:"Put these amounts in order from least to most.",items:["1 quarter","3 dimes","4 nickels"],ansOrder:["4 nickels","1 quarter","3 dimes"],
 expl:"4 nickels = 20 cents, 1 quarter = 25 cents, 3 dimes = 30 cents. Least to most: 4 nickels, 1 quarter, 3 dimes."},
{lvl:3,sec:"M",type:"in",q:"A ball costs 65 cents. Tomas pays with 3 quarters. How many cents change does he get?",ans:10,
 hint:"Find how much 3 quarters are worth first.",expl:"3 quarters = 75 cents. 75 − 65 = 10 cents change."},
{lvl:3,sec:"M",type:"in",q:"Nadia has $3 and 4 dimes. A book costs $2 and 90 cents. How many cents does she have left?",ans:50,
 hint:"Change both amounts into cents.",expl:"$3 and 4 dimes = 340 cents. $2 and 90 cents = 290 cents. 340 − 290 = 50 cents."},
{lvl:3,sec:"M",type:"in",q:"Kofi wants to make 40 cents with the fewest coins. How many coins does he need?",ans:3,
 hint:"Start with the biggest coin that fits.",expl:"1 quarter (25) + 1 dime (10) + 1 nickel (5) = 40 cents. That is 3 coins."}
],

"g2-lineplot": [
{sec:"M",type:"in",q:"A line plot shows pencil lengths. 10 cm has 3 Xs, 11 cm has 4 Xs, 12 cm has 2 Xs. How many pencils are 11 cm?",ans:4,
 expl:"Each X is one pencil. There are 4 Xs above 11 cm, so 4 pencils."},
{sec:"M",type:"in",q:"On a line plot, 6 cm has 2 Xs, 7 cm has 5 Xs and 8 cm has 1 X. How many leaves were measured?",ans:8,
 hint:"Count all the Xs.",expl:"2 + 5 + 1 = 8 leaves."},
{sec:"M",type:"mc",q:"What does each X on a line plot stand for?",opts:["One thing that was measured","One centimetre","The longest thing","The ruler"],a:0,
 expl:"Each X stands for one thing that was measured. More Xs means more things of that length."},
{sec:"M",type:"mc",q:"On a line plot, the numbers along the bottom line show what?",
 opts:["The lengths that were measured","How many Xs there are","The names of the children"],a:0,
 expl:"The numbers along the bottom are the lengths. The Xs above each number show how many had that length."},
{lvl:2,sec:"M",type:"in",q:"A line plot of shoe lengths: 15 cm has 1 X, 16 cm has 6 Xs, 17 cm has 3 Xs. How many shoes are longer than 15 cm?",ans:9,
 hint:"Add the Xs at 16 cm and 17 cm.",expl:"6 + 3 = 9 shoes are longer than 15 cm."},
{lvl:2,sec:"M",type:"mc",q:"A line plot of shoe lengths: 15 cm has 1 X, 16 cm has 6 Xs, 17 cm has 3 Xs. Which length is most common?",
 opts:["16 cm","15 cm","17 cm"],a:0,
 expl:"16 cm has the most Xs (6), so it is the most common length."},
{lvl:2,sec:"M",type:"order",q:"Ribbons measure 4 cm, 6 cm, 4 cm, 5 cm, 4 cm, 5 cm. Order the lengths by how many Xs, from fewest to most.",
 items:["6 cm","5 cm","4 cm"],ansOrder:["6 cm","5 cm","4 cm"],
 expl:"6 cm gets 1 X, 5 cm gets 2 Xs and 4 cm gets 3 Xs. Fewest to most: 6 cm, 5 cm, 4 cm."},
{lvl:3,sec:"M",type:"in",q:"Mei measured 10 sticks. On her line plot, 8 cm has 4 Xs and 9 cm has 3 Xs. The rest are 10 cm. How many Xs at 10 cm?",ans:3,
 hint:"All 10 sticks must be on the plot.",expl:"4 + 3 = 7 sticks are shown. 10 − 7 = 3, so there are 3 Xs at 10 cm."},
{lvl:3,sec:"M",type:"in",q:"A line plot: 2 cm has 1 X, 3 cm has 4 Xs, 4 cm has 2 Xs. How many more things are 3 cm than 4 cm?",ans:2,
 hint:"Compare the Xs at 3 cm and 4 cm.",expl:"4 − 2 = 2 more things are 3 cm long."}
],

"g2-polygons": [
{sec:"G",type:"mc",q:"Which shape has 3 sides and 3 corners?",opts:["Triangle","Square","Hexagon","Circle"],a:0,
 expl:"A triangle has 3 straight sides and 3 corners."},
{sec:"G",type:"mc",q:"Elias draws a shape with 4 equal sides and 4 square corners. What is it?",opts:["A square","A triangle","A hexagon","A circle"],a:0,
 expl:"4 equal sides and 4 square corners make a square."},
{sec:"G",type:"in",q:"How many sides does a hexagon have?",ans:6,expl:"A hexagon has 6 sides and 6 corners."},
{sec:"G",type:"mc",q:"Which shape has 5 sides?",opts:["Pentagon","Hexagon","Square","Triangle"],a:0,
 expl:"A pentagon has 5 sides. A hexagon has 6, a square has 4 and a triangle has 3."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY shape that has 4 sides.",opts:["Square","Rectangle","Rhombus","Triangle","Pentagon"],aMulti:[0,1,2],
 expl:"A square, a rectangle and a rhombus all have 4 sides. A triangle has 3 and a pentagon has 5."},
{lvl:2,sec:"G",type:"mc",q:"A shape has 4 sides. Two sides are long and two are short. All corners are square. What is it?",
 opts:["A rectangle","A square","A rhombus","A triangle"],a:0,
 expl:"Square corners with two long sides and two short sides make a rectangle. A square has all sides equal."},
{lvl:2,sec:"G",type:"in",q:"Ingrid draws a cube. How many faces does it have?",ans:6,
 hint:"Think of a dice.",expl:"A cube has 6 square faces, like the 6 sides of a dice."},
{lvl:3,sec:"G",type:"in",q:"Yusuf draws 2 triangles and 3 pentagons. How many sides does he draw in all?",ans:21,
 hint:"Find the sides of each kind first.",expl:"2 triangles have 3 + 3 = 6 sides. 3 pentagons have 5 + 5 + 5 = 15. 6 + 15 = 21 sides."},
{lvl:3,sec:"G",type:"mc",q:"A shape has more sides than a square but fewer than a hexagon. What is it?",opts:["A pentagon","A triangle","An octagon","A circle"],a:0,
 expl:"A square has 4 sides and a hexagon has 6. The shape with 5 sides is a pentagon."},
{lvl:3,sec:"G",type:"in",q:"Kenji draws a shape with 2 more sides than a triangle. How many corners does his shape have?",ans:5,
 hint:"A shape has the same number of corners as sides.",expl:"3 + 2 = 5 sides, so it is a pentagon with 5 corners."}
],

"g2-rowcol": [
{sec:"G",type:"in",q:"A rectangle is cut into 3 rows of 4 squares. How many squares are there?",ans:12,
 expl:"3 rows of 4: 4 + 4 + 4 = 12 squares."},
{sec:"G",type:"mc",q:"In an array, what is a row?",opts:["A line going across","A line going down","A corner","A square"],a:0,
 expl:"Rows go across from left to right. Columns go up and down."},
{sec:"G",type:"in",q:"Wei tiles a rectangle with 2 rows of 5 squares. How many squares are in each column?",ans:2,
 hint:"A column goes up and down.",expl:"There are 2 rows, so each column has one square from each row: 2 squares."},
{sec:"G",type:"in",q:"A rectangle has 4 rows and 4 columns of squares. How many squares in all?",ans:16,
 expl:"4 rows of 4: 4 + 4 + 4 + 4 = 16 squares."},
{lvl:2,sec:"G",type:"in",q:"Aisha's array has 20 squares in 4 equal rows. How many squares are in each row?",ans:5,
 hint:"Share 20 into 4 equal rows.",expl:"5 + 5 + 5 + 5 = 20, so each row has 5 squares."},
{lvl:2,sec:"G",type:"mc",q:"Which adds up the squares in 3 rows of 6?",mono:true,opts:["6 + 6 + 6","3 + 6","3 + 3 + 3","6 + 3 + 3"],a:0,
 expl:"Each row has 6 squares and there are 3 rows: 6 + 6 + 6 = 18."},
{lvl:2,sec:"G",type:"mc",q:"A rectangle is 5 squares across and 2 squares down. How many rows are there?",opts:["2","5","10","7"],a:0,
 expl:"Rows go across. Going down there are 2 rows, each with 5 squares."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY way to make an array of 12 squares.",opts:["3 rows of 4","2 rows of 6","5 rows of 2","4 rows of 4"],aMulti:[0,1],
 expl:"3 rows of 4 is 12 and 2 rows of 6 is 12. 5 rows of 2 is only 10, and 4 rows of 4 is 16."},
{lvl:3,sec:"G",type:"in",q:"Chioma's rectangle has 3 rows of 5 squares. She adds one more row. How many squares now?",ans:20,
 hint:"How many squares does one new row add?",expl:"3 rows of 5 is 15. One more row adds 5: 15 + 5 = 20 squares."},
{lvl:3,sec:"G",type:"in",q:"A rectangle is cut into 24 equal squares in 4 rows. How many columns are there?",ans:6,
 hint:"Each row has the same number of squares.",expl:"4 rows share 24 squares: 6 + 6 + 6 + 6 = 24. Each row has 6 squares, so there are 6 columns."},
{lvl:3,sec:"G",type:"mc",q:"Which of these has the most small squares?",opts:["3 rows of 5","2 rows of 7","4 rows of 3","6 rows of 2"],a:0,
 hint:"Count the squares in each one.",expl:"3 rows of 5 is 15. The others are 14, 12 and 12. So 3 rows of 5 has the most."}
],

"g2-thirds": [
{sec:"F",type:"mc",q:"A pizza is cut into 3 equal pieces. What is each piece called?",opts:["A third","A half","A fourth","A whole"],a:0,
 expl:"3 equal pieces are thirds. Each piece is one third of the pizza."},
{sec:"F",type:"in",q:"How many fourths make one whole?",ans:4,expl:"Fourths are 4 equal parts. All 4 together make one whole."},
{sec:"F",type:"mc",q:"Which shape is cut into halves?",
 opts:["A circle cut into 2 equal parts","A circle cut into 2 parts, one big and one small","A circle cut into 4 equal parts"],a:0,
 expl:"Halves must be 2 equal parts. Two unequal parts are not halves, and 4 equal parts are fourths."},
{sec:"F",type:"mc",q:"Which is bigger, one third of a cake or one fourth of the same cake?",opts:["One third","One fourth","They are the same"],a:0,
 expl:"Cutting into 3 pieces gives bigger pieces than cutting into 4. So one third is bigger."},
{lvl:2,sec:"F",type:"in",q:"A sandwich is cut into fourths. Priya eats 1 piece. How many fourths are left?",ans:3,
 expl:"There are 4 fourths. 4 − 1 = 3 fourths are left."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY way to cut a square into 2 equal halves.",
 opts:["A line from top to bottom through the middle","A line from corner to corner","A line near one edge"],aMulti:[0,1],
 expl:"A line through the middle, or from corner to corner, makes 2 equal parts. A line near one edge makes one big and one small part."},
{lvl:2,sec:"F",type:"mc",q:"Two halves of a paper strip are put back together. What do they make?",opts:["One whole","One half","Two wholes","One third"],a:0,
 expl:"Two halves make one whole strip."},
{lvl:3,sec:"F",type:"mc",q:"Lior cuts a cake into thirds. Mateo cuts a same-size cake into halves. Whose pieces are bigger?",opts:["Mateo's","Lior's","They are the same"],a:0,
 hint:"Fewer pieces means each piece is bigger.",expl:"Halves are 2 pieces and thirds are 3 pieces of the same cake. Mateo's halves are bigger."},
{lvl:3,sec:"F",type:"in",q:"A pie is cut into 4 equal pieces. Amara eats 2 pieces. How many halves of the pie is that?",ans:1,
 hint:"Two fourths fit together to make a bigger part.",expl:"2 fourths is the same as 1 half. She ate 1 half of the pie."},
{lvl:3,sec:"F",type:"in",q:"A ribbon is cut into thirds. Each third is 5 cm long. How long was the whole ribbon in cm?",ans:15,
 hint:"Thirds are 3 equal parts.",expl:"3 thirds of 5 cm: 5 + 5 + 5 = 15 cm."}
],

"g2-prime20": [
{sec:"T",type:"mc",q:"A prime number has exactly 2 factors: 1 and itself. Which number is prime?",opts:["7","8","9","10"],a:0,
 expl:"7 can only be made as 1 × 7. 8, 9 and 10 have more factors, like 2 × 4, 3 × 3 and 2 × 5."},
{sec:"T",type:"mc",q:"Which number is composite (it has more than 2 factors)?",opts:["9","2","3","5"],a:0,
 expl:"9 = 1 × 9 and 9 = 3 × 3, so its factors are 1, 3 and 9. That is more than 2. The others are prime."},
{sec:"T",type:"in",q:"List all the factors of 6. How many are there?",ans:4,
 hint:"Find every number that divides 6 with nothing left over.",expl:"The factors of 6 are 1, 2, 3 and 6. That is 4 factors."},
{sec:"T",type:"mc",q:"Is the number 1 prime, composite, or neither one?",opts:["Neither","Prime","Composite"],a:0,
 expl:"1 has only one factor, itself. Prime numbers need exactly 2 factors, so 1 is neither prime nor composite."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY prime number.",opts:["11","13","15","9"],aMulti:[0,1],
 expl:"11 and 13 have only the factors 1 and themselves. 15 = 3 × 5 and 9 = 3 × 3, so they are composite."},
{lvl:2,sec:"T",type:"in",q:"What is the only even prime number?",ans:2,
 hint:"Check the smallest even numbers first.",expl:"2 has only the factors 1 and 2. Every other even number also has 2 as a factor, so 2 is the only even prime."},
{lvl:2,sec:"T",type:"in",q:"How many prime numbers are there from 1 to 10?",ans:4,
 hint:"Check each number from 2 to 10.",expl:"The primes are 2, 3, 5 and 7. That is 4 primes."},
{lvl:3,sec:"T",type:"in",q:"How many prime numbers are there from 11 to 20?",ans:4,
 hint:"Even numbers and 15 are not prime.",expl:"The primes are 11, 13, 17 and 19. That is 4 primes."},
{lvl:3,sec:"T",type:"mc",q:"Which number is prime?",opts:["17","15","18","20"],a:0,
 expl:"17 has only the factors 1 and 17. 15 = 3 × 5, 18 = 2 × 9 and 20 = 4 × 5."},
{lvl:3,sec:"T",type:"in",q:"Femi picks two prime numbers that add to 20. One is 3. What is the other?",ans:17,
 hint:"Take 3 away from 20 and check if what is left is prime.",expl:"20 − 3 = 17, and 17 is prime. So the other number is 17."}
],

"g2-divrules": [
{sec:"T",type:"mc",q:"A number is divisible by 2 if it is even. Which number is divisible by 2?",opts:["48","35","91","17"],a:0,
 expl:"48 ends in 8, an even digit, so it is even. 35, 91 and 17 end in odd digits."},
{sec:"T",type:"mc",q:"A number is divisible by 5 if it ends in 0 or 5. Which one is?",opts:["65","52","43","81"],a:0,
 expl:"65 ends in 5, so it can be shared into fives: 13 fives make 65."},
{sec:"T",type:"mc",q:"A number is divisible by 10 if it ends in 0. Which number is?",opts:["90","95","19","101"],a:0,
 expl:"90 ends in 0, so 90 is 9 tens. The others do not end in 0."},
{sec:"T",type:"in",q:"What digit must a number end in to be divisible by 10?",ans:0,
 expl:"Multiples of 10 are 10, 20, 30 and so on. They all end in 0."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number you can divide by 5 with none left over.",opts:["25","40","32","54"],aMulti:[0,1],
 expl:"25 ends in 5 and 40 ends in 0, so both divide by 5. 32 and 54 do not end in 0 or 5."},
{lvl:2,sec:"T",type:"mc",q:"Which number can be divided by both 2 and 5?",opts:["30","25","32","15"],a:0,
 hint:"It must be even and end in 0 or 5.",expl:"30 is even and ends in 0, so 2 and 5 both divide it. 25 and 15 are odd, and 32 does not end in 0 or 5."},
{lvl:2,sec:"T",type:"mc",q:"A number divides by 3 if its digits add to 3, 6 or 9. Which number divides by 3?",opts:["24","25","26","28"],a:0,
 expl:"2 + 4 = 6, so 24 divides by 3 (3 × 8 = 24). The digit sums 7, 8 and 10 do not work."},
{lvl:3,sec:"T",type:"in",q:"What is the smallest 2-digit number that divides by both 2 and 5?",ans:10,
 hint:"A number that both 2 and 5 divide must end in 0.",expl:"It must end in 0. The smallest 2-digit number ending in 0 is 10."},
{lvl:3,sec:"T",type:"mc",q:"Which number divides by 2, by 5 and by 10?",opts:["70","75","72","57"],a:0,
 expl:"70 ends in 0, so 2, 5 and 10 all divide it. 75 is odd, 72 does not end in 0 or 5, and 57 is odd."},
{lvl:3,sec:"T",type:"in",q:"Noor writes the even numbers from 1 to 20 that also end in 5 or 0. How many are there?",ans:2,
 hint:"An even number cannot end in 5.",expl:"Even numbers ending in 0 or 5 must end in 0. From 1 to 20 that is 10 and 20, so 2 numbers."}
],

"g2-gcf": [
{sec:"T",type:"in",q:"Factors of 6: 1, 2, 3, 6. Factors of 9: 1, 3, 9. What is the greatest factor they share?",ans:3,
 expl:"The two lists share 1 and 3. The greatest shared factor is 3."},
{sec:"T",type:"in",q:"What is the greatest common factor of 8 and 12?",ans:4,
 hint:"List the factors of each number.",expl:"8: 1, 2, 4, 8. 12: 1, 2, 3, 4, 6, 12. The biggest number in both lists is 4."},
{sec:"T",type:"mc",q:"A common factor of two numbers is what?",opts:["A number that divides both of them","A number bigger than both","The sum of both numbers"],a:0,
 expl:"A factor divides a number with nothing left over. A common factor divides both numbers."},
{sec:"T",type:"in",q:"What is the greatest common factor of 5 and 10?",ans:5,
 expl:"5: 1, 5. 10: 1, 2, 5, 10. The greatest number in both lists is 5."},
{lvl:2,sec:"T",type:"in",q:"What is the greatest common factor of 12 and 18?",ans:6,
 hint:"Write out all the factors of 12, then of 18.",expl:"12: 1, 2, 3, 4, 6, 12. 18: 1, 2, 3, 6, 9, 18. The greatest shared factor is 6."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number that is a factor of both 12 and 20.",opts:["2","4","6","5"],aMulti:[0,1],
 expl:"2 and 4 divide both 12 and 20. 6 does not divide 20, and 5 does not divide 12."},
{lvl:2,sec:"T",type:"mc",q:"What is the greatest common factor of 7 and 9?",opts:["1","7","3","9"],a:0,
 expl:"7 has factors 1 and 7. 9 has factors 1, 3 and 9. The only shared factor is 1."},
{lvl:3,sec:"T",type:"in",q:"Hana has 12 apples and 16 pears. She makes equal bags, each bag the same. What is the most bags she can make?",ans:4,
 hint:"The number of bags must divide both 12 and 16.",
 expl:"12 and 16 both divide by 4, and no bigger number divides both. So she makes 4 bags, each with 3 apples and 4 pears."},
{lvl:3,sec:"T",type:"in",q:"What is the greatest common factor of 15 and 20?",ans:5,
 hint:"Both numbers end in 0 or 5.",expl:"15: 1, 3, 5, 15. 20: 1, 2, 4, 5, 10, 20. The greatest shared factor is 5."},
{lvl:3,sec:"T",type:"in",q:"Two numbers have a greatest common factor of 6. One number is 12 and the other is between 13 and 20. What is it?",ans:18,
 hint:"The other number must be a multiple of 6.",expl:"Multiples of 6 between 13 and 20: only 18. The factors of 12 and 18 share 6 as the greatest, so it is 18."}
],

"g2-repeated": [
{sec:"N",type:"mc",q:"Which is the same as 4 × 3?",mono:true,opts:["3 + 3 + 3 + 3","4 + 3","3 + 4 + 4","4 + 4"],a:0,
 expl:"4 × 3 means 4 groups of 3: 3 + 3 + 3 + 3 = 12."},
{sec:"N",type:"in",q:"2 + 2 + 2 + 2 + 2 = 5 × 2. What is 5 × 2?",ans:10,
 expl:"Add 2 five times: 2, 4, 6, 8, 10. So 5 × 2 = 10."},
{sec:"N",type:"in",q:"What is 3 × 6? Think 6 + 6 + 6.",ans:18,expl:"6 + 6 = 12, and 12 + 6 = 18. So 3 × 6 = 18."},
{sec:"N",type:"mc",q:"Which multiplication fact matches 5 + 5 + 5 + 5?",mono:true,opts:["4 × 5","5 × 5","4 + 5","2 × 5"],a:0,
 expl:"5 is added 4 times, so that is 4 groups of 5: 4 × 5 = 20."},
{lvl:2,sec:"N",type:"in",q:"Arjun buys 4 packs of 6 pencils. How many pencils is that?",ans:24,
 hint:"Add 6 four times.",expl:"4 × 6 = 6 + 6 + 6 + 6 = 24 pencils."},
{lvl:2,sec:"N",type:"in",q:"What is 3 × 7?",ans:21,hint:"Add 7 three times.",expl:"7 + 7 = 14, and 14 + 7 = 21. So 3 × 7 = 21."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY way to show 2 × 6.",mono:true,opts:["6 + 6","2 + 2 + 2 + 2 + 2 + 2","2 + 6","6 + 6 + 6"],aMulti:[0,1],
 expl:"2 × 6 is 2 groups of 6, or 6 groups of 2. Both make 12. 2 + 6 = 8 and 6 + 6 + 6 = 18 are wrong."},
{lvl:3,sec:"N",type:"in",q:"Zara knows 4 × 5 = 20. What is 5 × 5? Add one more group.",ans:25,
 hint:"One more group of 5.",expl:"5 × 5 is one more group of 5 than 4 × 5. 20 + 5 = 25."},
{lvl:3,sec:"N",type:"in",q:"There are 5 tables with 4 chairs each, and 2 extra chairs. How many chairs in all?",ans:22,
 hint:"Find the chairs at the tables first.",expl:"5 × 4 = 4 + 4 + 4 + 4 + 4 = 20. Then 20 + 2 = 22 chairs."},
{lvl:3,sec:"N",type:"mc",q:"Which is greater: 3 × 8 or 4 × 6?",opts:["They are equal","3 × 8","4 × 6"],a:0,
 hint:"Work out both by adding.",expl:"3 × 8 = 8 + 8 + 8 = 24. 4 × 6 = 6 + 6 + 6 + 6 = 24. They are equal."}
],

"g2-sharing": [
{sec:"N",type:"in",q:"12 cookies are shared equally by 3 children. How many cookies does each child get?",ans:4,
 expl:"Give one to each child until they are gone. 4 + 4 + 4 = 12, so each child gets 4."},
{sec:"N",type:"in",q:"Share 10 pencils equally between 2 friends. How many does each get?",ans:5,
 expl:"5 + 5 = 10, so each friend gets 5 pencils."},
{sec:"N",type:"mc",q:"What does 'share equally' mean?",opts:["Everyone gets the same amount","The oldest gets more","One person gets all"],a:0,
 expl:"Sharing equally means every share is the same size."},
{sec:"N",type:"in",q:"15 stickers are shared by 5 children equally. How many stickers does each get?",ans:3,
 expl:"3 + 3 + 3 + 3 + 3 = 15, so each child gets 3 stickers."},
{lvl:2,sec:"N",type:"in",q:"Leila shares 18 grapes among 6 friends. How many grapes does each friend get?",ans:3,
 hint:"Deal them out one at a time to 6 people.",expl:"6 groups of 3 make 18, so each friend gets 3 grapes."},
{lvl:2,sec:"N",type:"in",q:"20 marbles are shared equally into 4 jars. How many marbles in each jar?",ans:5,
 expl:"5 + 5 + 5 + 5 = 20, so each jar gets 5 marbles."},
{lvl:2,sec:"N",type:"mc",q:"Which has more in each share: 12 shared by 2, or 12 shared by 4?",opts:["12 shared by 2","12 shared by 4","They are the same"],a:0,
 expl:"12 shared by 2 gives 6 each. 12 shared by 4 gives 3 each. Fewer people means bigger shares."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY number of cookies that 3 children can share equally.",opts:["9","12","10","14"],aMulti:[0,1],
 expl:"9 is 3 each and 12 is 4 each. 10 and 14 leave cookies over when shared by 3."},
{lvl:3,sec:"N",type:"in",q:"Ravi has 17 pens. He shares them equally among 4 friends. How many pens are left over?",ans:1,
 hint:"Give out as many as you can in fours.",expl:"4 friends can each get 4 pens, which uses 16. 17 − 16 = 1 pen is left over."},
{lvl:3,sec:"N",type:"in",q:"Sven and Omar share 16 cards equally. Then Omar gives 3 of his to Sven. How many does Sven have?",ans:11,
 hint:"Share first, then move the 3 cards.",expl:"They each get 8. Then Sven gets 3 more: 8 + 3 = 11 cards."},
{lvl:3,sec:"N",type:"mc",q:"24 apples are packed into 6 equal boxes. Which fact tells how many are in each box?",mono:true,
 opts:["6 × 4 = 24","6 + 4 = 10","24 − 6 = 18","6 × 6 = 36"],a:0,
 expl:"6 boxes of 4 make 24, so each box holds 4 apples."}
],

"g2-multprob": [
{sec:"N",type:"in",q:"Each bike has 2 wheels. How many wheels do 7 bikes have?",ans:14,
 expl:"7 groups of 2: count 2, 4, 6, 8, 10, 12, 14. That is 14 wheels."},
{sec:"N",type:"in",q:"A box holds 5 eggs. How many eggs are in 3 boxes?",ans:15,
 expl:"3 × 5 = 5 + 5 + 5 = 15 eggs."},
{sec:"N",type:"mc",q:"There are 4 dogs. Each dog has 4 legs. Which fact finds the total legs?",mono:true,opts:["4 × 4","4 + 4","4 − 4","4 × 2"],a:0,
 expl:"4 dogs with 4 legs each is 4 groups of 4: 4 × 4 = 16 legs."},
{sec:"N",type:"in",q:"Fatima reads 3 books each week. How many books does she read in 4 weeks?",ans:12,
 expl:"4 weeks of 3 books: 3 + 3 + 3 + 3 = 12 books."},
{lvl:2,sec:"N",type:"in",q:"A spider has 8 legs. How many legs do 3 spiders have?",ans:24,
 hint:"Add 8 three times.",expl:"8 + 8 = 16, and 16 + 8 = 24 legs."},
{lvl:2,sec:"N",type:"in",q:"Kwame buys 6 packs of 3 balloons. How many balloons does he get?",ans:18,
 hint:"Count in threes six times.",expl:"3, 6, 9, 12, 15, 18. He gets 18 balloons."},
{lvl:2,sec:"N",type:"mc",q:"A shelf holds 9 books. There are 2 shelves. How many books fit?",opts:["18","11","7","20"],a:0,
 expl:"2 shelves of 9: 9 + 9 = 18 books."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY problem you can solve with 3 × 5.",opts:["3 boxes of 5 pens","5 bags of 3 apples","3 pens and 5 more","5 boxes of 5 pens"],aMulti:[0,1],
 expl:"3 boxes of 5 and 5 bags of 3 are both 3 × 5 = 15. 3 pens and 5 more is 3 + 5, and 5 boxes of 5 is 5 × 5."},
{lvl:3,sec:"N",type:"in",q:"Lucia has 3 bags with 5 shells each. She finds 4 more shells. How many shells does she have?",ans:19,
 hint:"Find the shells in the bags first.",expl:"3 × 5 = 15 shells in the bags. 15 + 4 = 19 shells."},
{lvl:3,sec:"N",type:"in",q:"There are 4 rows of 6 chairs. 5 chairs are broken. How many good chairs are there?",ans:19,
 hint:"Count all the chairs, then take away the broken ones.",expl:"4 × 6 = 24 chairs. 24 − 5 = 19 good chairs."},
{lvl:3,sec:"N",type:"in",q:"Malik buys 2 pens for $3 each and 1 book for $4. How many dollars does he spend?",ans:10,
 hint:"Find the cost of the pens first.",expl:"2 pens cost 3 + 3 = 6 dollars. 6 + 4 = 10 dollars."}
],

"g2-symbols": [
{sec:"L",type:"in",q:"□ + 4 = 9. What number goes in the box?",ans:5,
 expl:"Think 4 + ? = 9. Since 4 + 5 = 9, the box is 5."},
{sec:"L",type:"in",q:"12 − ▲ = 7. What number is ▲?",ans:5,
 hint:"What do you take from 12 to leave 7?",expl:"12 − 5 = 7, so ▲ is 5."},
{sec:"L",type:"mc",q:"In 3 + ★ = 10, what does ★ stand for?",opts:["An unknown number","A shape","The number 3","The number 10"],a:0,
 expl:"The star holds the place of a number we do not know yet. Here it is 7, because 3 + 7 = 10."},
{sec:"L",type:"in",q:"5 + 5 = □. What is □?",ans:10,expl:"5 + 5 = 10, so the box is 10."},
{lvl:2,sec:"L",type:"in",q:"□ + □ = 14. Both boxes are the same number. What is it?",ans:7,
 hint:"Which number doubled makes 14?",expl:"7 + 7 = 14, so each box is 7."},
{lvl:2,sec:"L",type:"in",q:"20 − ♥ = 12. What number is ♥?",ans:8,
 hint:"Count up from 12 to 20.",expl:"12 + 8 = 20, so 20 − 8 = 12. ♥ is 8."},
{lvl:2,sec:"L",type:"mc",q:"Which number makes 6 + ○ = 4 + 8 true?",opts:["6","2","4","8"],a:0,
 hint:"Work out the right side first.",expl:"4 + 8 = 12. Then 6 + 6 = 12, so ○ is 6."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY number sentence where □ is 6.",mono:true,opts:["□ + 2 = 8","10 − □ = 4","□ + □ = 10","□ − 1 = 4"],aMulti:[0,1],
 expl:"6 + 2 = 8 and 10 − 6 = 4 work. In □ + □ = 10 the box is 5, and in □ − 1 = 4 the box is 5."},
{lvl:3,sec:"L",type:"in",q:"▲ + ▲ + ▲ = 15. What is ▲?",ans:5,
 hint:"Three of the same number make 15.",expl:"5 + 5 + 5 = 15, so ▲ is 5."},
{lvl:3,sec:"L",type:"in",q:"□ + 3 = 10 and □ + ▲ = 12. What is ▲?",ans:5,
 hint:"Find the box first, then use it.",expl:"□ + 3 = 10, so □ = 7. Then 7 + ▲ = 12, so ▲ = 5."},
{lvl:3,sec:"L",type:"mc",q:"Noor writes 8 + ★ = ★ + 8. Which is true?",opts:["Any number works for ★","Only 0 works","Only 8 works","No number works"],a:0,
 expl:"Adding in either order gives the same total. So any number works for ★."}
],

"g2-rule": [
{sec:"L",type:"mc",q:"In: 2, 5, 8. Out: 5, 8, 11. What is the rule?",opts:["Add 3","Add 2","Take away 3","Double"],a:0,
 expl:"2 + 3 = 5, 5 + 3 = 8 and 8 + 3 = 11. The rule is add 3."},
{sec:"L",type:"in",q:"The rule is add 10. If 34 goes in, what comes out?",ans:44,expl:"34 + 10 = 44."},
{sec:"L",type:"mc",q:"In: 10, 7, 4. Out: 6, 3, 0. What is the rule?",opts:["Take away 4","Add 4","Take away 3","Add 6"],a:0,
 expl:"10 − 4 = 6, 7 − 4 = 3 and 4 − 4 = 0. The rule is take away 4."},
{sec:"L",type:"in",q:"The rule is take away 5. If 12 goes in, what comes out?",ans:7,expl:"12 − 5 = 7."},
{sec:"L",type:"multi",q:"The rule is double. Select EVERY pair that fits the rule.",opts:["In 3, out 6","In 5, out 10","In 4, out 6","In 2, out 5"],aMulti:[0,1],
 expl:"3 doubled is 6 and 5 doubled is 10. 4 doubled is 8, not 6, and 2 doubled is 4, not 5."},
{lvl:2,sec:"L",type:"in",q:"In: 3, 6, 9. Out: 6, 12, 18. If 5 goes in, what comes out?",ans:10,
 hint:"Each out number is twice the in number.",expl:"The rule is double. 5 doubled is 10."},
{lvl:2,sec:"L",type:"in",q:"The rule is add 7. What went in if 15 came out?",ans:8,
 hint:"Undo the rule by taking away.",expl:"15 − 7 = 8. Check: 8 + 7 = 15."},
{lvl:2,sec:"L",type:"mc",q:"In: 15, 20, 25. Out: 5, 10, 15. What is the rule?",opts:["Take away 10","Add 10","Take away 5","Halve"],a:0,
 expl:"15 − 10 = 5, 20 − 10 = 10 and 25 − 10 = 15. The rule is take away 10."},
{lvl:3,sec:"L",type:"in",q:"A machine adds 6, then takes away 2. If 9 goes in, what comes out?",ans:13,
 hint:"Do the two steps one after the other.",expl:"9 + 6 = 15, then 15 − 2 = 13."},
{lvl:3,sec:"L",type:"in",q:"Ola's rule turns 4 into 12 and 6 into 18. What does it turn 7 into?",ans:21,
 hint:"Compare each out number with its in number.",expl:"12 = 4 + 4 + 4 and 18 = 6 + 6 + 6, so the rule is times 3. 7 × 3 = 21."},
{lvl:3,sec:"L",type:"mc",q:"In: 1, 2, 3, 4. Out: 4, 7, 10, 13. What is the rule?",opts:["Triple, then add 1","Add 3","Double, then add 2","Add 4"],a:0,
 hint:"Test each rule on 1 and on 2.",expl:"1 × 3 + 1 = 4, 2 × 3 + 1 = 7, 3 × 3 + 1 = 10, 4 × 3 + 1 = 13. Add 3 fails on 1, and double plus 2 fails on 2."}
],

"g2-perm4": [
{sec:"K",type:"in",q:"Kai lines up 2 toys: a bear and a duck. How many different orders can he make?",ans:2,
 expl:"Bear then duck, or duck then bear. That is 2 orders."},
{sec:"K",type:"in",q:"How many ways can you order 3 books on a shelf?",ans:6,
 hint:"Pick the first book, then see what is left.",expl:"3 choices for the first book, then 2 for the next, then 1. 3 × 2 × 1 = 6 ways."},
{sec:"K",type:"mc",q:"Imani puts a red, a blue and a green cup in a row, with red first. How many ways?",opts:["2","3","6","1"],a:0,
 expl:"The red cup stays first. Blue then green, or green then blue: 2 ways."},
{sec:"K",type:"in",q:"Rosa has 4 flags. She picks one to fly first. How many choices does she have?",ans:4,
 expl:"Any of the 4 flags can go first, so she has 4 choices."},
{lvl:2,sec:"K",type:"in",q:"3 children can line up in 6 ways. One more child joins. How many ways can 4 children line up?",ans:24,
 hint:"The new child can stand in 4 places in each old line.",expl:"For each of the 6 old lines, the new child can go in 4 spots. 6 × 4 = 24 ways."},
{lvl:2,sec:"K",type:"in",q:"Ruben has 4 cards: 1, 2, 3, 4. How many 2-digit numbers can he make using 2 different cards?",ans:12,
 hint:"Choose the tens card, then the ones card.",expl:"4 choices for the first card, then 3 for the second. 4 × 3 = 12 numbers."},
{lvl:2,sec:"K",type:"order",q:"Put these in order from fewest ways to most ways.",
 items:["Lining up 3 toys","Lining up 4 toys","Lining up 2 toys"],ansOrder:["Lining up 2 toys","Lining up 3 toys","Lining up 4 toys"],
 expl:"2 toys give 2 ways, 3 toys give 6 ways and 4 toys give 24 ways. More toys means more ways."},
{lvl:3,sec:"K",type:"in",q:"Four books sit on a shelf. The red book must be first. How many ways can the other 3 be placed?",ans:6,
 hint:"Only the 3 other books move.",expl:"The red book stays put. The other 3 can be ordered 3 × 2 × 1 = 6 ways."},
{lvl:3,sec:"K",type:"in",q:"Four runners finish a race. In how many ways can the first two places be filled?",ans:12,
 hint:"Who can be first? Then who can be second?",expl:"4 runners could be first, then 3 could be second. 4 × 3 = 12 ways."},
{lvl:3,sec:"K",type:"in",q:"Ana, Bo, Cy and Di line up. Ana must be first and Di must be last. How many ways?",ans:2,
 hint:"Only two children are free to move.",expl:"Ana and Di are fixed. Bo and Cy fill the middle in 2 orders: Bo, Cy or Cy, Bo."}
],

"g2-permcomb": [
{sec:"K",type:"mc",q:"Sana picks 2 fruits from apple, pear and plum to put in a bag. Does the order matter?",
 opts:["No, a bag is the same either way","Yes, always","Yes, if the fruit is red"],a:0,
 expl:"An apple and a pear in a bag is the same as a pear and an apple. Order does not matter."},
{sec:"K",type:"mc",q:"Two runners get gold and silver medals. Does the order they finish matter?",
 opts:["Yes, the medals are different","No, it does not matter","Only on Mondays"],a:0,
 expl:"Finishing first gets gold and second gets silver. Swapping them changes who gets which, so order matters."},
{sec:"K",type:"in",q:"From 3 colours, how many ways can you pick 2 to mix in a pot? Order does not matter.",ans:3,
 hint:"Call the colours A, B and C and list the pairs.",expl:"The pairs are A and B, A and C, B and C. That is 3 ways."},
{sec:"K",type:"in",q:"From 3 colours, how many ways can you paint a top stripe and a bottom stripe, using 2 different colours?",ans:6,
 hint:"Top and bottom swapped is a different flag.",expl:"3 choices for the top, then 2 for the bottom. 3 × 2 = 6 ways."},
{lvl:2,sec:"K",type:"in",q:"Idris chooses 2 of 4 toys to take to the park. How many different pairs can he choose?",ans:6,
 hint:"Name the toys A, B, C, D and list every pair.",expl:"AB, AC, AD, BC, BD, CD. That is 6 pairs."},
{lvl:2,sec:"K",type:"in",q:"Theo picks a first toy and a second toy from 4 toys. How many ways can they do this?",ans:12,
 hint:"Here first and second are different jobs.",expl:"4 choices for the first toy, then 3 for the second. 4 × 3 = 12 ways."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY case where order matters.",
 opts:["Choosing 1st and 2nd place","Making a 2-digit code","Picking 2 friends for a team","Choosing 2 toppings for a pizza"],aMulti:[0,1],
 expl:"1st and 2nd place are different, and 12 is not the same code as 21. A team or a set of toppings is the same in any order."},
{lvl:3,sec:"K",type:"mc",q:"Picking 2 of 4 children in order gives 12 ways. Picking a team of 2 gives how many?",opts:["6","12","24","4"],a:0,
 hint:"Each team gets counted twice when order matters.",expl:"Each team is counted twice among the 12 ordered picks. 12 ÷ 2 = 6 teams."},
{lvl:3,sec:"K",type:"in",q:"Mira has 5 stickers. She gives 2 to a friend. How many different pairs could she give?",ans:10,
 hint:"List the pairs with sticker 1, then with 2, and so on.",expl:"Pairs with 1: 4. New pairs with 2: 3. With 3: 2. With 4: 1. 4 + 3 + 2 + 1 = 10 pairs."},
{lvl:3,sec:"K",type:"in",q:"How many 2-letter codes can be made from A, B, C, D if letters cannot repeat?",ans:12,
 hint:"AB and BA are different codes.",expl:"4 choices for the first letter, then 3 for the second. 4 × 3 = 12 codes."}
],

"g2-symmetry": [
{sec:"G",type:"in",q:"How many lines of symmetry does a square have?",ans:4,
 expl:"Two lines through the middles of the sides and two through the corners. That is 4 lines."},
{sec:"G",type:"mc",q:"A shape is folded along a line and both halves match exactly. What is the line called?",opts:["A line of symmetry","A corner","A side","A curve"],a:0,
 expl:"A fold line where both halves match is a line of symmetry."},
{sec:"G",type:"mc",q:"Which letter has a line of symmetry?",opts:["A","F","G","J"],a:0,
 expl:"The letter A folds in half down the middle and matches. F, G and J do not."},
{sec:"G",type:"in",q:"How many lines of symmetry does a rectangle that is not a square have?",ans:2,
 hint:"Try folding along the middle in two ways. Corner to corner does not work.",expl:"One line across the middle and one down the middle. That is 2 lines."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY letter that has a line of symmetry.",opts:["H","M","O","P","R"],aMulti:[0,1,2],
 expl:"H and O each have 2 lines and M has 1 down the middle. P and R have none."},
{lvl:2,sec:"G",type:"in",q:"How many lines of symmetry does a triangle with 3 equal sides have?",ans:3,
 hint:"One line from each corner.",expl:"A line from each corner to the middle of the opposite side. That is 3 lines."},
{lvl:2,sec:"G",type:"mc",q:"Which shape has NO line of symmetry?",opts:["The letter Z","The letter T","A square","The letter V"],a:0,
 expl:"Z cannot be folded to match. T and V fold down the middle, and a square has 4 lines."},
{lvl:3,sec:"G",type:"in",q:"A shape has 1 line of symmetry. One side of the line has 6 dots. How many dots does the whole shape have?",ans:12,
 hint:"The other side is a mirror copy.",expl:"The other side matches with 6 dots too. 6 + 6 = 12 dots."},
{lvl:3,sec:"G",type:"mc",q:"Which shape has more lines of symmetry: a square or a rectangle that is not a square?",opts:["The square","The rectangle","They have the same"],a:0,
 hint:"Try the corner-to-corner folds on each.",expl:"A square has 4 lines. A rectangle has only 2, because corner-to-corner folds do not match."},
{lvl:3,sec:"G",type:"in",q:"Aiko folds a paper square in half, then in half again. She cuts a hole in the middle. How many holes when she unfolds?",ans:4,
 hint:"How many layers of paper did the cut go through?",expl:"Two folds make 4 layers. The cut goes through all 4, so there are 4 holes."}
],

"g2-tangram": [
{sec:"G",type:"in",q:"A tangram has 7 pieces. How many of them are triangles?",ans:5,
 expl:"There are 2 large, 1 medium and 2 small triangles: 2 + 1 + 2 = 5. The other pieces are a square and a parallelogram."},
{sec:"G",type:"mc",q:"Which two tangram pieces can make the square piece?",opts:["The 2 small triangles","The 2 large triangles","The square and the medium triangle"],a:0,
 expl:"The 2 small triangles fit together along their long sides to make the small square."},
{sec:"G",type:"mc",q:"Which shapes are in a tangram?",opts:["Triangles, a square and a parallelogram","Circles and squares","Hexagons and triangles"],a:0,
 expl:"A tangram has 5 triangles, 1 square and 1 parallelogram. There are no circles or hexagons."},
{sec:"G",type:"in",q:"Two small triangles make one medium triangle in a tangram. How many small ones make 2 medium ones?",ans:4,
 expl:"2 small for each medium: 2 + 2 = 4 small triangles."},
{lvl:2,sec:"G",type:"in",q:"A large tangram triangle is made of 4 small ones. How many small ones make both large triangles?",ans:8,
 expl:"4 + 4 = 8 small triangles."},
{lvl:2,sec:"G",type:"mc",q:"Cut a large tangram triangle from its top corner down to the middle of the bottom. What two shapes do you get?",
 opts:["Two medium triangles","Two squares","Two small triangles"],a:0,
 expl:"The cut makes 2 equal triangles, each half of the large one. Half of a large triangle is a medium triangle."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY tangram piece you can make with the 2 small triangles.",
 opts:["The square","The medium triangle","The parallelogram","A large triangle"],aMulti:[0,1,2],
 expl:"Two small triangles make the square, the medium triangle or the parallelogram. A large triangle needs 4 small ones."},
{lvl:3,sec:"G",type:"in",q:"All 7 tangram pieces equal 16 small triangles. The 2 large ones use 8. The square uses 2. How many small triangles are left?",ans:6,
 hint:"Take away what the large pieces and the square use.",expl:"16 − 8 = 8, then 8 − 2 = 6 small triangles are left for the other pieces."},
{lvl:3,sec:"G",type:"mc",q:"Esme makes a square using only the 2 large tangram triangles. How does she place them?",
 opts:["Long sides together","Short sides together","Corners touching only"],a:0,
 hint:"Try it: which sides must touch so no gap is left?",expl:"Putting the two long sides together makes a square. Short sides together make a bigger triangle."},
{lvl:3,sec:"G",type:"in",q:"Jonas uses all 5 tangram triangles for a bird. How many small triangles is that worth? (Large = 4 small, medium = 2 small.)",ans:12,
 hint:"Add up 2 large, 1 medium and 2 small.",expl:"2 large = 4 + 4 = 8. 1 medium = 2. 2 small = 2. 8 + 2 + 2 = 12 small triangles."}
]
};
