/* Grade 3, second bank: the remaining core Operations, Base Ten, Fractions,
   Measurement and Geometry topics, plus the advanced enrichment strands
   (number theory, fraction operations, algebraic reasoning, combinatorics and
   extended geometry). Advanced topics lean toward Math Kangaroo / MATHCOUNTS
   style reasoning while keeping the wording at a Grade 3 reading level. */
export const G3_MORE_BANKS = {
"g3-div": [
{sec:"N",type:"in",q:"24 ÷ 6 = ?",ans:4,hint:"How many sixes make 24?",expl:"6 × 4 = 24, so 24 ÷ 6 = 4."},
{sec:"N",type:"in",q:"35 ÷ 5 = ?",ans:7,expl:"5 × 7 = 35, so 35 ÷ 5 = 7."},
{sec:"N",type:"mc",q:"Which multiplication fact helps you solve 42 ÷ 7?",mono:true,
 opts:["7 + 6 = 13","7 × 6 = 42","42 − 7 = 35","6 × 6 = 36"],a:1,
 expl:"Division undoes multiplication. Since 7 × 6 = 42, we know 42 ÷ 7 = 6."},
{sec:"N",type:"in",q:"Amara shares 18 stickers equally among 3 friends. How many stickers does each friend get?",ans:6,
 hint:"Split 18 into 3 equal groups.",expl:"18 ÷ 3 = 6, so each friend gets 6 stickers."},
{lvl:2,sec:"N",type:"in",q:"56 ÷ 8 = ?",ans:7,hint:"Think: 8 times what is 56?",expl:"8 × 7 = 56, so 56 ÷ 8 = 7."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY division that equals 9.",mono:true,
 opts:["36 ÷ 4","45 ÷ 5","54 ÷ 6","27 ÷ 9"],aMulti:[0,1,2],
 expl:"36 ÷ 4 = 9, 45 ÷ 5 = 9 and 54 ÷ 6 = 9. But 27 ÷ 9 = 3."},
{lvl:3,sec:"N",type:"in",q:"Kenji has 48 marbles. He keeps 8 and shares the rest equally among 5 friends. How many marbles does each friend get?",
 ans:8,hint:"First work out how many marbles are shared.",
 expl:"48 − 8 = 40 marbles are shared. 40 ÷ 5 = 8, so each friend gets 8."},
{lvl:3,sec:"N",type:"in",q:"A baker puts 6 muffins in each box. She has 50 muffins. How many boxes can she fill completely?",
 ans:8,hint:"Some muffins may be left over.",
 expl:"8 × 6 = 48 and 9 × 6 = 54, which is too many. So she fills 8 boxes with 2 muffins left over."}
],

"g3-multprops": [
{sec:"N",type:"mc",q:"Which equation shows the commutative property of multiplication?",mono:true,
 opts:["4 × 7 = 7 × 4","4 × 0 = 0","4 × 1 = 4","(2 × 3) × 5 = 2 × (3 × 5)"],a:0,
 expl:"The commutative property says the order of the factors does not change the product: 4 × 7 = 7 × 4 = 28."},
{sec:"N",type:"in",q:"Any number times 1 equals itself. What is 87 × 1?",ans:87,
 expl:"Multiplying by 1 leaves a number unchanged, so 87 × 1 = 87."},
{sec:"N",type:"in",q:"What is 9 × 0?",ans:0,hint:"Nine groups of nothing.",
 expl:"Any number times 0 is 0, so 9 × 0 = 0."},
{sec:"N",type:"mc",q:"Which is the same as (2 × 5) × 3?",mono:true,
 opts:["2 × 5 + 3","2 × (5 × 3)","(2 + 5) × 3","2 × 5 × 5"],a:1,
 expl:"The associative property lets you regroup the factors: (2 × 5) × 3 = 2 × (5 × 3). Both equal 30."},
{lvl:2,sec:"N",type:"in",q:"Use the distributive property: 6 × 7 = 6 × 5 + 6 × 2. What is 6 × 7?",ans:42,
 hint:"Work out each part, then add.",expl:"6 × 5 = 30 and 6 × 2 = 12. 30 + 12 = 42."},
{lvl:2,sec:"N",type:"mc",q:"Which expression is equal to 8 × 12?",mono:true,
 opts:["8 × 10 + 2","8 + 10 + 2","8 × 10 + 8 × 2","80 + 12"],a:2,
 expl:"Split 12 into 10 + 2: 8 × 12 = 8 × 10 + 8 × 2 = 80 + 16 = 96."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY expression equal to 4 × 9.",mono:true,
 opts:["9 × 4","4 × 5 + 4 × 4","2 × 2 × 9","4 × 10 − 1"],aMulti:[0,1,2],
 expl:"4 × 9 = 36. 9 × 4 = 36, 4 × 5 + 4 × 4 = 20 + 16 = 36, and 2 × 2 × 9 = 36. But 4 × 10 − 1 = 39."},
{lvl:3,sec:"N",type:"in",q:"Priya knows that 7 × 8 = 56. Use that fact to find 14 × 8.",ans:112,
 hint:"14 is double 7.",expl:"14 = 2 × 7, so 14 × 8 = 2 × (7 × 8) = 2 × 56 = 112."},
{lvl:3,sec:"N",type:"in",q:"What is 25 × 7 × 4? Group the easy pair of factors first.",ans:700,
 hint:"Which two factors make 100?",expl:"25 × 4 = 100, so 25 × 7 × 4 = 100 × 7 = 700."}
],

"g3-twostep": [
{sec:"N",type:"in",q:"Mateo buys 3 packs of 6 pencils and gives away 5 pencils. How many pencils does he have left?",ans:13,
 hint:"Find the total number of pencils first.",expl:"3 × 6 = 18 pencils. 18 − 5 = 13 pencils left."},
{sec:"N",type:"in",q:"Zainab has 20 stickers. She gets 4 more, then shares all of them equally among 4 people. How many does each person get?",ans:6,
 hint:"Add first, then divide.",expl:"20 + 4 = 24 stickers. 24 ÷ 4 = 6 each."},
{sec:"N",type:"mc",q:"A pack of 8 crayons costs $3. Which expression gives the cost of 4 packs in dollars?",mono:true,
 opts:["8 × 3","4 × 3","4 × 8","8 + 3"],a:1,
 expl:"Each pack costs $3 and there are 4 packs, so the cost is 4 × 3 = $12. The number of crayons does not matter."},
{lvl:2,sec:"N",type:"in",q:"A hall has 5 rows of 7 chairs. 12 chairs are already taken. How many chairs are empty?",ans:23,
 hint:"Multiply to find all the chairs, then subtract.",expl:"5 × 7 = 35 chairs. 35 − 12 = 23 empty chairs."},
{lvl:2,sec:"N",type:"in",q:"Lior earns $4 for each car he washes. He washes 6 cars and then spends $9. How much money does he have left, in dollars?",ans:15,
 hint:"Earnings first, then the spending.",expl:"6 × 4 = $24 earned. 24 − 9 = $15 left."},
{lvl:2,sec:"N",type:"mc",q:"Aisha bought 3 boxes of 4 cupcakes and ate 2 of them. Which two steps find how many are left?",
 opts:["multiply, then subtract","add, then subtract","multiply, then add","subtract, then divide"],a:0,
 expl:"First multiply 3 × 4 = 12 to find the total, then subtract the 2 eaten: 12 − 2 = 10 cupcakes."},
{lvl:3,sec:"N",type:"in",q:"Tomas has 45 marbles. He gives away 13, then puts the rest into 4 equal bags. How many marbles are in each bag?",ans:8,
 hint:"Subtract before you divide.",expl:"45 − 13 = 32 marbles. 32 ÷ 4 = 8 marbles in each bag."},
{lvl:3,sec:"N",type:"in",q:"Tickets cost $6 for an adult and $4 for a child. A family of 2 adults and 3 children pays with a $50 note. How much change do they get, in dollars?",ans:26,
 hint:"Work out the adult cost and the child cost separately.",
 expl:"Adults: 2 × 6 = $12. Children: 3 × 4 = $12. Total $24, so the change is 50 − 24 = $26."}
],

"g3-patterns": [
{sec:"N",type:"in",q:"What is the next number: 4, 8, 12, 16, __?",ans:20,hint:"How much does it go up each time?",
 expl:"Each number is 4 more than the last. 16 + 4 = 20."},
{sec:"N",type:"mc",q:"What is the rule for the pattern 50, 45, 40, 35?",
 opts:["Subtract 5","Add 5","Subtract 10","Multiply by 5"],a:0,
 expl:"Each number is 5 less than the one before, so the rule is subtract 5."},
{sec:"N",type:"in",q:"The pattern is 3, 6, 9, 12, ... What is the 10th number?",ans:30,
 hint:"These are the multiples of 3.",expl:"The nth number is 3 × n, so the 10th number is 3 × 10 = 30."},
{sec:"N",type:"mc",q:"Every number in the pattern 6, 12, 18, 24 is ...",
 opts:["odd","a multiple of 4","even","less than 20"],a:2,
 expl:"They are all multiples of 6, and every multiple of 6 is even. 6 and 18 are not multiples of 4, and 24 is not less than 20."},
{lvl:2,sec:"N",type:"in",q:"In a multiplication table the row for 7 goes 7, 14, 21, ... What is the 6th number in that row?",ans:42,
 expl:"The 6th number in the row for 7 is 7 × 6 = 42."},
{lvl:2,sec:"N",type:"mc",q:"Which pattern follows the rule 'add 4'?",
 opts:["4, 8, 16, 32","3, 7, 11, 15","3, 6, 9, 12","4, 9, 14, 20"],a:1,
 expl:"3, 7, 11, 15 goes up by 4 each time. The others double, add 3, or change by different amounts."},
{lvl:2,sec:"N",type:"order",q:"Put these numbers in the order they appear in the pattern 'start at 2, then double', smallest first.",
 items:["16","2","8","4"],ansOrder:["2","4","8","16"],
 expl:"Start at 2 and double: 2, 4, 8, 16."},
{lvl:3,sec:"N",type:"in",q:"Wei writes the pattern 5, 9, 13, 17, ... What is the first number in the pattern that is greater than 40?",ans:41,
 hint:"Keep adding 4 until you pass 40.",expl:"Continue adding 4: 21, 25, 29, 33, 37, 41. The first number greater than 40 is 41."},
{lvl:3,sec:"N",type:"in",q:"A pattern starts at 100 and subtracts 6 each time: 100, 94, 88, ... How many numbers in the pattern are greater than 70?",ans:5,
 hint:"List the numbers until you reach 70 or below.",
 expl:"100, 94, 88, 82, 76 are greater than 70; the next number is 70, which is not. That is 5 numbers."}
],

"g3-round": [
{sec:"N",type:"in",q:"Round 47 to the nearest ten.",ans:50,hint:"Is 47 closer to 40 or 50?",
 expl:"47 is 3 away from 50 and 7 away from 40, so it rounds to 50."},
{sec:"N",type:"in",q:"Round 362 to the nearest hundred.",ans:400,hint:"Look at the tens digit.",
 expl:"The tens digit is 6, which is 5 or more, so 362 rounds up to 400."},
{sec:"N",type:"mc",q:"Which number rounds to 80 when rounded to the nearest ten?",opts:["86","74","84","89"],a:2,
 expl:"84 is only 4 away from 80. 86 and 89 round to 90, and 74 rounds to 70."},
{sec:"N",type:"in",q:"Round 845 to the nearest ten.",ans:850,hint:"A 5 in the ones place rounds up.",
 expl:"845 is exactly halfway between 840 and 850, and halfway rounds up, so the answer is 850."},
{lvl:2,sec:"N",type:"in",q:"Round 650 to the nearest hundred.",ans:700,hint:"Halfway numbers round up.",
 expl:"650 is halfway between 600 and 700. Halfway rounds up, so 650 rounds to 700."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY number that rounds to 300 when rounded to the nearest hundred.",
 opts:["249","250","349","350"],aMulti:[1,2],
 expl:"Numbers from 250 up to 349 round to 300. 249 rounds to 200 and 350 rounds up to 400."},
{lvl:3,sec:"N",type:"in",q:"What is the smallest whole number that rounds to 500 when rounded to the nearest hundred?",ans:450,
 hint:"Think about the halfway point below 500.",
 expl:"450 is halfway between 400 and 500, and halfway rounds up. Anything smaller, like 449, rounds to 400. So the answer is 450."},
{lvl:3,sec:"N",type:"mc",q:"Nadia says her number rounds to 70 to the nearest ten and to 100 to the nearest hundred. Which could be her number?",
 opts:["64","66","75","56"],a:1,
 expl:"66 rounds to 70 (nearest ten) and to 100 (nearest hundred). 64 rounds to 60, 75 rounds to 80, and 56 rounds to 60."}
],

"g3-add1000": [
{sec:"N",type:"in",q:"358 + 241 = ?",ans:599,expl:"Add the hundreds, tens and ones: 500 + 90 + 9 = 599."},
{sec:"N",type:"in",q:"624 − 312 = ?",ans:312,expl:"600 − 300 = 300, 20 − 10 = 10, 4 − 2 = 2. Total 312."},
{sec:"N",type:"in",q:"487 + 356 = ?",ans:843,hint:"Watch for regrouping in the ones and tens.",
 expl:"7 + 6 = 13 (write 3, carry 1). 8 + 5 + 1 = 14 (write 4, carry 1). 4 + 3 + 1 = 8. Answer 843."},
{sec:"N",type:"mc",q:"Which is the best way to estimate 298 + 403?",mono:true,
 opts:["200 + 400","300 + 500","300 + 400","290 + 400"],a:2,
 expl:"298 is close to 300 and 403 is close to 400, so 300 + 400 = 700 is a good estimate."},
{lvl:2,sec:"N",type:"in",q:"703 − 458 = ?",ans:245,hint:"Check by adding your answer to 458.",
 expl:"703 − 458 = 245. Check: 458 + 245 = 703."},
{lvl:2,sec:"N",type:"in",q:"Oluwaseun has 526 stamps. Ingrid has 187 fewer stamps than Oluwaseun. How many stamps does Ingrid have?",ans:339,
 hint:"'Fewer' means subtract.",expl:"526 − 187 = 339 stamps."},
{lvl:2,sec:"N",type:"mc",q:"Which subtraction has the same answer as 500 − 264?",mono:true,
 opts:["499 − 263","500 − 246","501 − 264","500 − 254"],a:0,
 expl:"Taking 1 from both numbers keeps the difference the same: 499 − 263 = 236, just like 500 − 264 = 236."},
{lvl:3,sec:"N",type:"in",q:"A shop had 900 apples. It sold 347 in the morning and 285 in the afternoon. How many apples were left?",ans:268,
 hint:"Find the total sold first.",expl:"347 + 285 = 632 apples sold. 900 − 632 = 268 apples left."},
{lvl:3,sec:"N",type:"in",q:"The sum of two numbers is 1000. One of the numbers is 438. What is the other number?",ans:562,
 hint:"Subtract from 1000.",expl:"1000 − 438 = 562. Check: 438 + 562 = 1000."}
],

"g3-mult10": [
{sec:"N",type:"in",q:"4 × 30 = ?",ans:120,hint:"4 × 3 tens.",expl:"4 × 3 = 12, so 4 × 30 = 12 tens = 120."},
{sec:"N",type:"in",q:"7 × 60 = ?",ans:420,expl:"7 × 6 = 42, so 7 × 60 = 420."},
{sec:"N",type:"mc",q:"Which shows a good way to work out 5 × 80?",mono:true,
 opts:["5 × 8 = 40","5 × 8 tens = 40 tens","5 + 80 = 85","50 + 8 = 58"],a:1,
 expl:"80 is 8 tens, so 5 × 80 = 5 × 8 tens = 40 tens = 400."},
{sec:"N",type:"in",q:"9 × 50 = ?",ans:450,expl:"9 × 5 = 45, so 9 × 50 = 450."},
{lvl:2,sec:"N",type:"in",q:"A box holds 40 oranges. How many oranges are in 8 boxes?",ans:320,
 expl:"8 × 40 = 320 oranges, because 8 × 4 = 32 and then add a zero for the tens."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY product that equals 240.",mono:true,
 opts:["6 × 40","8 × 30","4 × 60","3 × 70"],aMulti:[0,1,2],
 expl:"6 × 40 = 240, 8 × 30 = 240 and 4 × 60 = 240. But 3 × 70 = 210."},
{lvl:3,sec:"N",type:"in",q:"Ravi packs 6 boxes of 30 books and 3 boxes of 20 books. How many books does he pack altogether?",ans:240,
 hint:"Work out each kind of box separately.",expl:"6 × 30 = 180 and 3 × 20 = 60. 180 + 60 = 240 books."},
{lvl:3,sec:"N",type:"in",q:"What number times 70 equals 560?",ans:8,hint:"What times 7 equals 56?",
 expl:"8 × 7 = 56, so 8 × 70 = 560. The number is 8."},
{lvl:3,sec:"N",type:"mc",q:"Which is greater, 6 × 90 or 7 × 80, and by how much?",
 opts:["6 × 90, by 20","7 × 80, by 20","They are equal","7 × 80, by 10"],a:1,
 expl:"6 × 90 = 540 and 7 × 80 = 560. 560 − 540 = 20, so 7 × 80 is greater by 20."}
],

"g3-fraccomp": [
{sec:"F",type:"mc",q:"Which is larger: 3/8 or 5/8?",mono:true,opts:["5/8","3/8","They are equal"],a:0,
 expl:"Both fractions are in eighths, so compare the numerators. 5 eighths is more than 3 eighths."},
{sec:"F",type:"mc",q:"Which is larger: 1/3 or 1/5?",mono:true,opts:["1/5","1/3","They are equal"],a:1,
 expl:"Both have numerator 1. Cutting into 3 pieces gives bigger pieces than cutting into 5, so 1/3 is larger."},
{sec:"F",type:"mc",q:"Which symbol makes this true: 2/6 __ 2/4?",mono:true,opts:["<",">","="],a:0,
 expl:"Same number of pieces, but sixths are smaller than quarters. So 2/6 < 2/4."},
{sec:"F",type:"order",q:"Put these fractions in order from smallest to largest.",
 items:["3/4","1/4","2/4"],ansOrder:["1/4","2/4","3/4"],
 expl:"All are quarters, so order by the numerator: 1/4, 2/4, 3/4."},
{lvl:2,sec:"F",type:"order",q:"Order these unit fractions from smallest to largest.",
 items:["1/2","1/6","1/3","1/8"],ansOrder:["1/8","1/6","1/3","1/2"],
 expl:"With numerator 1, a bigger denominator means a smaller piece: 1/8 < 1/6 < 1/3 < 1/2."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY fraction that is greater than 1/2.",mono:true,
 opts:["3/4","2/6","5/8","3/8"],aMulti:[0,2],
 expl:"3/4 and 5/8 are more than half. 2/6 equals 1/3 and 3/8 is less than 4/8, so both are less than 1/2."},
{lvl:2,sec:"F",type:"mc",q:"Sofia ate 2/3 of her sandwich and Yusuf ate 2/5 of his. The sandwiches were the same size. Who ate more?",
 opts:["Sofia","Yusuf","Same amount"],a:0,
 expl:"Both ate 2 pieces, but thirds are bigger than fifths. 2/3 > 2/5, so Sofia ate more."},
{lvl:3,sec:"F",type:"mc",q:"Which fraction is between 1/4 and 1/2?",mono:true,opts:["1/8","3/8","5/8","2/8"],a:1,
 expl:"1/4 = 2/8 and 1/2 = 4/8. The fraction between them is 3/8."},
{lvl:3,sec:"F",type:"in",q:"How many eighths are the same as 3/4? Type the number of eighths.",ans:6,
 hint:"Each quarter is two eighths.",expl:"1/4 = 2/8, so 3/4 = 3 × 2 eighths = 6/8. The answer is 6."}
],

"g3-fraceq": [
{sec:"F",type:"mc",q:"Which fraction is equivalent to 1/2?",mono:true,opts:["2/3","3/6","1/4","3/4"],a:1,
 expl:"3 out of 6 equal pieces is half of the whole, so 3/6 = 1/2."},
{sec:"F",type:"in",q:"1/3 = ?/6. Type the missing numerator.",ans:2,hint:"6 is double 3.",
 expl:"Multiply the top and bottom by 2: 1/3 = 2/6. The missing numerator is 2."},
{sec:"F",type:"in",q:"2/4 = 1/?. Type the missing denominator.",ans:2,
 expl:"Divide the top and bottom by 2: 2/4 = 1/2. The missing denominator is 2."},
{sec:"F",type:"mc",q:"Which fraction is NOT equivalent to 2/3?",mono:true,opts:["4/6","6/9","3/4","8/12"],a:2,
 expl:"4/6, 6/9 and 8/12 all come from multiplying 2/3 by the same number top and bottom. 3/4 is a different amount."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY fraction equivalent to 3/4.",mono:true,
 opts:["6/8","9/12","4/5","12/16"],aMulti:[0,1,3],
 expl:"3/4 × 2/2 = 6/8, × 3/3 = 9/12, × 4/4 = 12/16. 4/5 is not equivalent."},
{lvl:2,sec:"F",type:"in",q:"A pizza is cut into 8 slices. Hana eats 4 slices. Written with a denominator of 2, what fraction did she eat? Type the numerator.",ans:1,
 hint:"Simplify 4/8.",expl:"4/8 = 1/2, so the numerator is 1."},
{lvl:2,sec:"F",type:"in",q:"Fill in the missing number: 3/5 = ?/10.",ans:6,hint:"10 is double 5.",
 expl:"Multiply top and bottom by 2: 3/5 = 6/10. The missing number is 6."},
{lvl:3,sec:"F",type:"in",q:"Diego says 4/6 equals 2/3. Femi says 4/6 equals 8/12. How many of them are correct? Type 0, 1 or 2.",ans:2,
 hint:"Try dividing and multiplying the top and bottom of 4/6.",
 expl:"4/6 ÷ 2/2 = 2/3 and 4/6 × 2/2 = 8/12, so both are correct. The answer is 2."},
{lvl:3,sec:"F",type:"in",q:"Two fractions are equivalent. One is 2/5 and the other has a denominator of 20. What is its numerator?",ans:8,
 hint:"How many times does 5 go into 20?",expl:"20 = 5 × 4, so multiply the numerator by 4 as well: 2 × 4 = 8. The fraction is 8/20."}
],

"g3-wholefrac": [
{sec:"F",type:"mc",q:"Which fraction equals 1 whole?",mono:true,opts:["4/4","1/4","4/1","4/8"],a:0,
 expl:"When the numerator and denominator are the same, the fraction is one whole: 4/4 = 1."},
{sec:"F",type:"in",q:"3 = ?/1. Type the missing numerator.",ans:3,
 expl:"Any whole number can be written over 1: 3 = 3/1. The numerator is 3."},
{sec:"F",type:"in",q:"How many thirds are in 2 wholes?",ans:6,hint:"Each whole has 3 thirds.",
 expl:"Each whole is 3/3, so 2 wholes are 6/3. There are 6 thirds."},
{sec:"F",type:"mc",q:"Which fraction equals 5?",mono:true,opts:["1/5","5/5","5/1","5/10"],a:2,
 expl:"5/1 means 5 wholes. 5/5 is 1, and 1/5 and 5/10 are less than 1."},
{lvl:2,sec:"F",type:"in",q:"8/4 equals what whole number?",ans:2,hint:"How many quarters make one whole?",
 expl:"4 quarters make 1 whole, so 8 quarters make 2 wholes. 8/4 = 2."},
{lvl:2,sec:"F",type:"mc",q:"Which fraction shows 3 wholes each cut into halves?",mono:true,opts:["3/2","6/2","2/3","3/6"],a:1,
 expl:"Each whole gives 2 halves, so 3 wholes give 6 halves: 6/2 = 3."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY fraction that equals a whole number.",mono:true,
 opts:["6/3","4/4","5/2","10/5"],aMulti:[0,1,3],
 expl:"6/3 = 2, 4/4 = 1 and 10/5 = 2. But 5/2 is two and a half."},
{lvl:3,sec:"F",type:"in",q:"Mei has 3 whole pizzas, each cut into 6 equal slices. She gives away 4 slices. How many sixths does she have left?",ans:14,
 hint:"Count all the slices first.",expl:"3 pizzas × 6 slices = 18 sixths. 18 − 4 = 14 sixths left."},
{lvl:3,sec:"F",type:"in",q:"What whole number is equal to 24/8?",ans:3,hint:"How many eighths make a whole?",
 expl:"8 eighths make 1 whole, and 24 ÷ 8 = 3. So 24/8 = 3."}
],

"g3-timemin": [
{sec:"M",type:"mc",q:"The hour hand is just past the 3 and the minute hand points at the 7. What time is it?",
 opts:["3:07","3:35","7:15","3:30"],a:1,
 expl:"Each number on the clock is 5 minutes, so the 7 means 7 × 5 = 35 minutes past 3. The time is 3:35."},
{sec:"M",type:"in",q:"The minute hand points at the 4. How many minutes past the hour is it?",ans:20,
 hint:"Count in fives from the 12.",expl:"4 × 5 = 20, so it is 20 minutes past the hour."},
{sec:"M",type:"in",q:"A clock shows 2:48. How many minutes until 3:00?",ans:12,hint:"Count on from 48 to 60.",
 expl:"60 − 48 = 12 minutes until 3:00."},
{sec:"M",type:"mc",q:"It is between 10 and 11 o'clock. The minute hand is one small mark past the 9. What time is it?",
 opts:["10:45","10:09","10:46","10:50"],a:2,
 expl:"The 9 means 45 minutes, and one small mark more is one minute. The time is 10:46."},
{lvl:2,sec:"M",type:"in",q:"Leila starts reading at 4:15 and reads for 37 minutes. At what time does she finish? Type just the minutes past the hour.",ans:52,
 hint:"Add the minutes.",expl:"15 + 37 = 52, so she finishes at 4:52. The minutes are 52."},
{lvl:2,sec:"M",type:"in",q:"How many minutes are there from 6:50 to 7:25?",ans:35,hint:"Count to 7:00 first, then on to 7:25.",
 expl:"6:50 to 7:00 is 10 minutes, then 7:00 to 7:25 is 25 minutes. 10 + 25 = 35 minutes."},
{lvl:2,sec:"M",type:"mc",q:"Which time is 25 minutes before 11:10?",opts:["10:35","10:45","11:35","10:50"],a:1,
 expl:"Go back 10 minutes to 11:00, then 15 more minutes to 10:45."},
{lvl:3,sec:"M",type:"in",q:"Arjun's bus leaves at 8:05. He needs 20 minutes to eat breakfast and 14 minutes to walk to the stop. What is the latest time he can start eating? Type it as a number like 645 for 6:45.",ans:731,
 hint:"Add the two times together, then count back from 8:05.",
 expl:"20 + 14 = 34 minutes. 34 minutes before 8:05 is 7:31, so type 731."},
{lvl:3,sec:"M",type:"in",q:"A film starts at 3:40 and lasts 1 hour 35 minutes. When does it end? Type it as a number like 430 for 4:30.",ans:515,
 hint:"Add the hour first, then the minutes.",
 expl:"3:40 + 1 hour = 4:40. 4:40 + 20 minutes = 5:00, and 15 more minutes makes 5:15. Type 515."}
],

"g3-volmass": [
{sec:"M",type:"mc",q:"Which unit would you use to measure the mass of an apple?",opts:["grams","litres","metres","kilometres"],a:0,
 expl:"Mass is measured in grams or kilograms. An apple is light, so grams fit best."},
{sec:"M",type:"mc",q:"About how much water does a full bathtub hold?",
 opts:["150 millilitres","150 litres","1 litre","15 millilitres"],a:1,
 expl:"A bathtub holds a lot of water, far more than a bottle. 150 litres is a sensible estimate."},
{sec:"M",type:"in",q:"How many grams are in 1 kilogram?",ans:1000,expl:"1 kilogram = 1000 grams."},
{sec:"M",type:"mc",q:"Which is the best estimate for the mass of a bicycle?",
 opts:["12 grams","120 kilograms","12 kilograms","1 gram"],a:2,
 expl:"A bicycle is heavier than a bag of sugar (1 kg) but much lighter than a car. About 12 kilograms is reasonable."},
{lvl:2,sec:"M",type:"in",q:"A jug holds 2 litres. Noor pours out 750 millilitres. How many millilitres are left?",ans:1250,
 hint:"Change the litres to millilitres first.",expl:"2 litres = 2000 mL. 2000 − 750 = 1250 mL left."},
{lvl:2,sec:"M",type:"in",q:"Three bags of flour have masses of 450 g, 380 g and 270 g. What is the total mass in grams?",ans:1100,
 expl:"450 + 380 = 830, and 830 + 270 = 1100 grams."},
{lvl:2,sec:"M",type:"multi",q:"Select EVERY amount that is more than 1 litre.",
 opts:["1500 millilitres","2 litres","900 millilitres","1000 millilitres"],aMulti:[0,1],
 expl:"1 litre = 1000 mL. 1500 mL and 2 litres are more; 900 mL is less and 1000 mL is exactly 1 litre."},
{lvl:3,sec:"M",type:"in",q:"A box of 6 identical cans has a total mass of 2400 grams. What is the mass of one can in grams?",ans:400,
 hint:"Share the mass equally.",expl:"2400 ÷ 6 = 400 grams for each can."},
{lvl:3,sec:"M",type:"in",q:"Elias fills a 5-litre bucket using a 250-millilitre cup. How many full cups does he need?",ans:20,
 hint:"How many 250s make 1000?",expl:"5 litres = 5000 mL. Four cups make 1000 mL, so 5 × 4 = 20 cups."}
],

"g3-scaled": [
{sec:"S",type:"in",q:"On a pictograph, each star stands for 5 books. The row for Class A shows 4 stars. How many books did Class A read?",ans:20,
 hint:"Multiply the stars by the key.",expl:"4 stars × 5 books = 20 books."},
{sec:"S",type:"mc",q:"A bar graph has a scale that goes up in tens. A bar reaches halfway between 30 and 40. What value does it show?",
 opts:["35","32","45","30"],a:0,
 expl:"Halfway between 30 and 40 is 35."},
{sec:"S",type:"in",q:"Each picture on a graph stands for 2 apples. Chioma's row has 7 pictures. How many apples is that?",ans:14,
 expl:"7 pictures × 2 apples = 14 apples."},
{sec:"S",type:"in",q:"In a pictograph each symbol stands for 4 votes. How many symbols are needed to show 24 votes?",ans:6,
 hint:"How many fours make 24?",expl:"24 ÷ 4 = 6 symbols."},
{lvl:2,sec:"S",type:"in",q:"A pictograph key says each apple picture means 4 apples. Amara's row shows 4 whole pictures and one half picture. How many apples is that?",ans:18,
 hint:"A half picture is half of the key.",expl:"4 × 4 = 16, and half a picture is 2 more. 16 + 2 = 18 apples."},
{lvl:2,sec:"S",type:"mc",q:"A bar graph shows Monday 15, Tuesday 25 and Wednesday 10. Which statement is true?",
 opts:["Monday had the most","Wednesday had 10 fewer than Monday","Tuesday had 10 more than Monday","Tuesday had 15 more than Monday"],a:2,
 expl:"25 − 15 = 10, so Tuesday had 10 more than Monday. Wednesday had only 5 fewer than Monday, and Tuesday had the most."},
{lvl:2,sec:"S",type:"in",q:"A pictograph uses one symbol for every 10 children. The three rows show 3, 5 and 2 symbols. How many children in total?",ans:100,
 expl:"3 + 5 + 2 = 10 symbols. 10 × 10 = 100 children."},
{lvl:3,sec:"S",type:"in",q:"On a bar graph with a scale of 5, the bar for cats is 6 lines tall and the bar for dogs is 9 lines tall. How many more dogs than cats are there?",ans:15,
 hint:"Turn each bar into a number first.",expl:"Cats: 6 × 5 = 30. Dogs: 9 × 5 = 45. 45 − 30 = 15 more dogs."},
{lvl:3,sec:"S",type:"in",q:"Kenji drew a pictograph where each symbol stands for 6 votes. Pizza got 30 votes and pasta got 18 votes. How many symbols did he draw altogether?",ans:8,
 hint:"Divide each total by the key.",expl:"Pizza: 30 ÷ 6 = 5 symbols. Pasta: 18 ÷ 6 = 3 symbols. 5 + 3 = 8 symbols."}
],

"g3-perimeter": [
{sec:"G",type:"in",q:"A rectangle is 6 cm long and 4 cm wide. What is its perimeter in cm?",ans:20,
 hint:"Add all four sides.",expl:"6 + 4 + 6 + 4 = 20 cm."},
{sec:"G",type:"in",q:"A square has sides of 7 cm. What is its perimeter in cm?",ans:28,
 expl:"A square has 4 equal sides: 4 × 7 = 28 cm."},
{sec:"G",type:"mc",q:"What is perimeter?",
 opts:["The distance around a shape","The space inside a shape","The number of sides","The longest side"],a:0,
 expl:"Perimeter is the total distance around the outside of a shape."},
{sec:"G",type:"in",q:"A triangle has sides of 5 cm, 7 cm and 9 cm. What is its perimeter in cm?",ans:21,
 expl:"5 + 7 + 9 = 21 cm."},
{lvl:2,sec:"G",type:"in",q:"A rectangle has a perimeter of 30 cm and a length of 10 cm. What is its width in cm?",ans:5,
 hint:"Two lengths use up part of the perimeter.",expl:"Two lengths make 20 cm, leaving 30 − 20 = 10 cm for two widths. Each width is 5 cm."},
{lvl:2,sec:"G",type:"in",q:"A regular hexagon has 6 equal sides of 8 cm. What is its perimeter in cm?",ans:48,
 expl:"6 × 8 = 48 cm."},
{lvl:2,sec:"G",type:"mc",q:"Which rectangle has the greatest perimeter?",
 opts:["5 cm by 5 cm","7 cm by 3 cm","9 cm by 2 cm","6 cm by 4 cm"],a:2,
 expl:"9 by 2 gives 2 × (9 + 2) = 22 cm. The other three all give 20 cm."},
{lvl:3,sec:"G",type:"in",q:"Priya puts a fence around a square garden with sides of 9 m. Fencing costs $3 per metre. How much does the fence cost, in dollars?",ans:108,
 hint:"Find the perimeter first.",expl:"Perimeter = 4 × 9 = 36 m. Cost = 36 × 3 = $108."},
{lvl:3,sec:"G",type:"in",q:"A 6 cm by 6 cm square has a 2 cm by 2 cm square cut out of one corner. What is the perimeter of the shape that is left, in cm?",ans:24,
 hint:"Trace the edge. The two new edges replace the two that were removed.",
 expl:"Cutting a corner removes 2 cm + 2 cm of edge but adds 2 cm + 2 cm of new edge, so the perimeter stays 4 × 6 = 24 cm."}
],

"g3-quads": [
{sec:"G",type:"mc",q:"How many sides does a quadrilateral have?",opts:["3","4","5","6"],a:1,
 expl:"'Quad' means four. A quadrilateral has 4 sides."},
{sec:"G",type:"mc",q:"Which shape has 4 equal sides and 4 right angles?",opts:["rectangle","rhombus","square","trapezium"],a:2,
 expl:"A square has both: four equal sides and four right angles. A rectangle only needs the right angles and a rhombus only the equal sides."},
{sec:"G",type:"mc",q:"Which is NOT a quadrilateral?",opts:["triangle","square","rhombus","trapezium"],a:0,
 expl:"A triangle has 3 sides. The others all have 4 sides, so they are quadrilaterals."},
{sec:"G",type:"multi",q:"Select EVERY shape that is always a parallelogram.",opts:["square","rectangle","rhombus","kite"],aMulti:[0,1,2],
 expl:"Squares, rectangles and rhombuses all have two pairs of parallel sides. A kite does not have to."},
{lvl:2,sec:"G",type:"mc",q:"A quadrilateral has 4 equal sides but no right angles. What is it?",opts:["square","rhombus","rectangle","trapezium"],a:1,
 expl:"Four equal sides make a rhombus. If it also had right angles it would be a square."},
{lvl:2,sec:"G",type:"mc",q:"Which statement is true?",
 opts:["Every square is a rectangle","Every rectangle is a square","Every rhombus is a square","Every quadrilateral is a square"],a:0,
 expl:"A rectangle needs 4 right angles, and every square has them. So every square is a rectangle, but not the other way round."},
{lvl:2,sec:"G",type:"in",q:"A rhombus has a perimeter of 36 cm. How long is each side in cm?",ans:9,
 hint:"All four sides of a rhombus are equal.",expl:"36 ÷ 4 = 9 cm."},
{lvl:3,sec:"G",type:"mc",q:"Mateo draws a quadrilateral with exactly one pair of parallel sides. Which shape is it?",
 opts:["parallelogram","trapezium","rectangle","rhombus"],a:1,
 expl:"A trapezium has exactly one pair of parallel sides. The other three shapes have two pairs."},
{lvl:3,sec:"G",type:"multi",q:"Select EVERY shape that ALWAYS has 4 right angles.",opts:["square","rectangle","rhombus","parallelogram"],aMulti:[0,1],
 expl:"Squares and rectangles always have 4 right angles. A rhombus or parallelogram can be slanted."}
],

"g3-equalarea": [
{sec:"G",type:"mc",q:"A rectangle is cut into 4 equal parts. What fraction of the area is each part?",mono:true,opts:["1/4","1/2","1/3","4/1"],a:0,
 expl:"Four equal parts means each part is one quarter of the whole area: 1/4."},
{sec:"G",type:"in",q:"A square is split into 8 equal pieces and Zainab shades 3 of them. What fraction of the area is shaded? Type the numerator.",ans:3,
 expl:"3 of the 8 equal pieces are shaded, so 3/8 of the area is shaded. The numerator is 3."},
{sec:"G",type:"mc",q:"A shape is divided into 6 equal parts and 2 are shaded. What fraction of the area is shaded?",mono:true,
 opts:["2/4","2/6","6/2","1/2"],a:1,
 expl:"2 parts out of 6 equal parts is 2/6 of the area."},
{sec:"G",type:"mc",q:"A rectangle is cut into 2 pieces of exactly the same area. What fraction is each piece?",
 opts:["one half","one quarter","one third","one whole"],a:0,
 expl:"Two equal pieces are halves. Each piece is one half of the area."},
{lvl:2,sec:"G",type:"in",q:"A rectangle has an area of 24 square units and is cut into 6 equal parts. What is the area of each part in square units?",ans:4,
 expl:"24 ÷ 6 = 4 square units each."},
{lvl:2,sec:"G",type:"mc",q:"A square is cut along both diagonals into 4 triangles. What fraction of the square is each triangle?",mono:true,
 opts:["1/4","1/3","1/2","1/8"],a:0,
 expl:"The two diagonals make 4 identical triangles, so each one is 1/4 of the square."},
{lvl:2,sec:"G",type:"multi",q:"A rectangle is divided into 8 equal squares. Select EVERY fraction that shows the area of 4 of them.",mono:true,
 opts:["4/8","1/2","2/4","1/4"],aMulti:[0,1,2],
 expl:"4 out of 8 is 4/8, which equals 1/2 and 2/4. It is not 1/4."},
{lvl:3,sec:"G",type:"in",q:"A garden with an area of 36 square metres is divided into 4 equal beds. Lior plants flowers in 3 of the beds. What area is planted, in square metres?",ans:27,
 hint:"Find the area of one bed first.",expl:"36 ÷ 4 = 9 square metres per bed. 3 × 9 = 27 square metres planted."},
{lvl:3,sec:"G",type:"in",q:"A rectangle is 6 units by 4 units. It is cut into 3 equal strips. What is the area of one strip in square units?",ans:8,
 hint:"Find the whole area, then share it.",expl:"Area = 6 × 4 = 24 square units. 24 ÷ 3 = 8 square units per strip."}
],

"g3-areaperim": [
{sec:"G",type:"mc",q:"Which one measures the space INSIDE a shape?",opts:["area","perimeter","length","width"],a:0,
 expl:"Area measures the space inside. Perimeter measures the distance around."},
{sec:"G",type:"in",q:"A rectangle is 5 cm by 3 cm. What is its area in square cm?",ans:15,expl:"Area = 5 × 3 = 15 square cm."},
{sec:"G",type:"in",q:"A rectangle is 5 cm by 3 cm. What is its perimeter in cm?",ans:16,expl:"Perimeter = 5 + 3 + 5 + 3 = 16 cm."},
{sec:"G",type:"mc",q:"Which unit is used for area?",opts:["metres","square metres","litres","kilograms"],a:1,
 expl:"Area is measured in square units, such as square metres or square centimetres."},
{lvl:2,sec:"G",type:"mc",q:"Two rectangles both have a perimeter of 16 cm. One is 7 cm by 1 cm and the other is 4 cm by 4 cm. Which has the greater area?",
 opts:["4 cm by 4 cm","7 cm by 1 cm","Same area"],a:0,
 expl:"7 × 1 = 7 square cm but 4 × 4 = 16 square cm. Same perimeter, very different areas."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY rectangle with an area of 12 square units.",opts:["6 by 2","3 by 4","12 by 1","5 by 2"],aMulti:[0,1,2],
 expl:"6 × 2, 3 × 4 and 12 × 1 all equal 12. 5 × 2 = 10."},
{lvl:2,sec:"G",type:"in",q:"A rectangle is 8 units by 2 units. Another is 4 units by 4 units. Both have the same area. How much greater is the perimeter of the 8 by 2 rectangle, in units?",ans:4,
 hint:"Work out both perimeters.",expl:"8 by 2 has perimeter 20. 4 by 4 has perimeter 16. 20 − 16 = 4 units."},
{lvl:3,sec:"G",type:"in",q:"A rectangle has an area of 20 square cm and a width of 4 cm. What is its perimeter in cm?",ans:18,
 hint:"Find the length first.",expl:"Length = 20 ÷ 4 = 5 cm. Perimeter = 2 × (5 + 4) = 18 cm."},
{lvl:3,sec:"G",type:"in",q:"Tomas wants a rectangular pen with a perimeter of 20 m and the largest possible area, using whole-number side lengths. What is that area in square metres?",ans:25,
 hint:"Length + width must be 10. Try different pairs.",
 expl:"Length + width = 10. Try 9 × 1 = 9, 8 × 2 = 16, 7 × 3 = 21, 6 × 4 = 24, 5 × 5 = 25. The square gives the largest area: 25 square metres."}
],

"g3-primefact": [
{sec:"T",type:"mc",q:"Which number is prime?",opts:["9","7","15","21"],a:1,
 expl:"7 can only be divided by 1 and itself. 9 = 3 × 3, 15 = 3 × 5 and 21 = 3 × 7."},
{sec:"T",type:"in",q:"12 = 2 × 2 × ?. Type the missing prime factor.",ans:3,hint:"2 × 2 = 4. What times 4 is 12?",
 expl:"2 × 2 = 4 and 4 × 3 = 12, so the missing prime factor is 3."},
{sec:"T",type:"mc",q:"What is the prime factorisation of 18?",mono:true,opts:["2 × 3 × 3","2 × 9","3 × 6","2 × 3"],a:0,
 expl:"18 = 2 × 9 and 9 = 3 × 3, so 18 = 2 × 3 × 3. Every factor must be prime, so 9 and 6 are not allowed."},
{sec:"T",type:"in",q:"How many times does the prime 2 appear in the prime factorisation of 16?",ans:4,hint:"Keep halving.",
 expl:"16 = 2 × 8 = 2 × 2 × 4 = 2 × 2 × 2 × 2. The 2 appears 4 times."},
{lvl:2,sec:"T",type:"mc",q:"Which is the prime factorisation of 30?",mono:true,opts:["5 × 6","2 × 15","2 × 3 × 5","3 × 10"],a:2,
 expl:"30 = 2 × 15 and 15 = 3 × 5, so 30 = 2 × 3 × 5. The other options still contain non-prime factors."},
{lvl:2,sec:"T",type:"in",q:"The prime factorisation of a number is 2 × 2 × 5. What is the number?",ans:20,
 expl:"2 × 2 = 4 and 4 × 5 = 20."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number that has 3 as a prime factor.",opts:["15","21","16","24"],aMulti:[0,1,3],
 expl:"15 = 3 × 5, 21 = 3 × 7 and 24 = 2 × 2 × 2 × 3. 16 = 2 × 2 × 2 × 2 has no factor 3."},
{lvl:3,sec:"T",type:"in",q:"What is the largest prime factor of 42?",ans:7,hint:"Start by dividing by the smallest primes.",
 expl:"42 = 2 × 21 = 2 × 3 × 7. The largest prime factor is 7."},
{lvl:3,sec:"T",type:"in",q:"A number's prime factorisation is 3 × 3 × 5. The number is doubled. How many prime factors, counting repeats, does the new number have?",ans:4,
 hint:"Doubling adds one factor of 2.",expl:"The number is 45. Doubling gives 90 = 2 × 3 × 3 × 5, which has 4 prime factors counting repeats."}
],


"g3-divrules": [
{sec:"T",type:"mc",q:"Which rule tells you whether a number is divisible by 3?",
 opts:["Its last digit is an even number","The sum of its digits is divisible by 3","Its last digit is either 0 or 5","It ends in two zeros, like 100"],a:1,
 expl:"A number is divisible by 3 exactly when the sum of its digits is divisible by 3. For example 1 + 2 + 3 = 6, so 123 is divisible by 3."},
{sec:"T",type:"in",q:"Add the digits of 243. What is the digit sum?",ans:9,hint:"Add 2, 4 and 3.",
 expl:"2 + 4 + 3 = 9. Because 9 is divisible by 3 (and by 9), 243 is divisible by 3 and by 9."},
{sec:"T",type:"mc",q:"Is 126 divisible by 3?",
 opts:["Yes, because 1 + 2 + 6 = 9","No, because it ends in 6","Yes, because it ends in 6","No, because 1 + 2 + 6 = 9"],a:0,
 expl:"The digit sum is 1 + 2 + 6 = 9, which is divisible by 3, so 126 is divisible by 3. The last digit does not matter for the rule of 3."},
{sec:"T",type:"mc",q:"Which number is divisible by 4?",opts:["314","322","316","318"],a:2,hint:"Look only at the last two digits.",
 expl:"A number is divisible by 4 when its last two digits are. 16 = 4 × 4, so 316 is divisible by 4. 14, 22 and 18 are not multiples of 4."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number that is divisible by 9.",opts:["108","234","145","405"],aMulti:[0,1,3],
 hint:"Add the digits of each number.",
 expl:"1 + 0 + 8 = 9, 2 + 3 + 4 = 9 and 4 + 0 + 5 = 9, so 108, 234 and 405 are divisible by 9. 1 + 4 + 5 = 10 is not, so 145 is not."},
{lvl:2,sec:"T",type:"mc",q:"Which number is divisible by 6?",opts:["123","134","138","141"],a:2,
 hint:"A multiple of 6 must be even AND divisible by 3.",
 expl:"138 is even and 1 + 3 + 8 = 12 is divisible by 3, so 138 is divisible by 6. 123 and 141 are odd; 134 has digit sum 8."},
{lvl:2,sec:"T",type:"in",q:"The three-digit number 4_2 is divisible by 9. What digit goes in the blank?",ans:3,
 hint:"The digit sum must be a multiple of 9.",expl:"4 + 2 = 6, and 6 + 3 = 9. So the missing digit is 3, giving 432 = 9 × 48."},
{lvl:3,sec:"T",type:"in",q:"The three-digit number 8_4 is divisible by both 4 and 9. What digit goes in the blank?",ans:6,
 hint:"Use the rule of 9 first, then check the rule of 4.",
 expl:"For 9, the digit sum 8 + _ + 4 = 12 + _ must be a multiple of 9, so the digit is 6. Check 4: the last two digits 64 = 4 × 16. The number is 864."},
{lvl:3,sec:"T",type:"in",q:"What is the smallest three-digit number that is divisible by both 4 and 6?",ans:108,
 hint:"A number divisible by 4 and 6 is divisible by 12.",
 expl:"Divisible by both 4 and 6 means divisible by 12. 12 × 8 = 96 is too small, and 12 × 9 = 108. Check: 08 is a multiple of 4, and 108 is even with digit sum 9."}
],

"g3-lcm": [
{sec:"T",type:"in",q:"What is the least common multiple of 2 and 3?",ans:6,hint:"List multiples of each and find the first one they share.",
 expl:"Multiples of 2: 2, 4, 6, ... Multiples of 3: 3, 6, ... The first shared multiple is 6."},
{sec:"T",type:"mc",q:"Which list shows the first four multiples of 4?",mono:true,
 opts:["4, 8, 12, 16","1, 2, 4, 8","4, 6, 8, 10","4, 8, 10, 12"],a:0,
 expl:"Multiples of 4 are 4 × 1, 4 × 2, 4 × 3, 4 × 4, which are 4, 8, 12, 16."},
{sec:"T",type:"in",q:"What is the LCM of 4 and 6?",ans:12,hint:"Count in fours and in sixes.",
 expl:"Multiples of 4: 4, 8, 12. Multiples of 6: 6, 12. The least common multiple is 12."},
{sec:"T",type:"mc",q:"Which is a common multiple of 3 and 5?",opts:["10","12","15","25"],a:2,
 expl:"15 = 3 × 5 = 5 × 3, so it is in both lists. 10 and 25 are not multiples of 3; 12 is not a multiple of 5."},
{lvl:2,sec:"T",type:"in",q:"What is the least common multiple of 6 and 8?",ans:24,hint:"Multiples of 8 are 8, 16, 24, ... Which is also a multiple of 6?",
 expl:"Multiples of 6: 6, 12, 18, 24. Multiples of 8: 8, 16, 24. The LCM is 24."},
{lvl:2,sec:"T",type:"in",q:"What is the least common multiple of 3, 4 and 6?",ans:12,
 expl:"12 is a multiple of 3 (3 × 4), of 4 (4 × 3) and of 6 (6 × 2). No smaller number works, so the LCM is 12."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number that is a common multiple of 4 and 6.",opts:["12","18","24","36"],aMulti:[0,2,3],
 expl:"12, 24 and 36 are all multiples of both 4 and 6. 18 is a multiple of 6 but not of 4."},
{lvl:3,sec:"T",type:"in",q:"One light flashes every 6 seconds and another every 9 seconds. They flash together now. In how many seconds will they next flash together?",
 ans:18,hint:"Find the least common multiple of 6 and 9.",
 expl:"The first light flashes at 6, 12, 18 seconds; the second at 9, 18 seconds. They next flash together after 18 seconds."},
{lvl:3,sec:"T",type:"in",q:"Kofi buys cups in packs of 8 and plates in packs of 6. What is the smallest number of guests he can set up so that no cups or plates are left over?",
 ans:24,hint:"He needs the same number of cups and plates.",
 expl:"The number of guests must be a multiple of 8 and of 6. The least common multiple is 24, so he buys 3 packs of cups and 4 packs of plates."}
],

"g3-gcdlcm": [
{sec:"T",type:"mc",q:"12 = 2 × 2 × 3 and 18 = 2 × 3 × 3. Which prime factors do they share?",mono:true,
 opts:["2 and 3","2 and 2","3 and 3","only 2"],a:0,
 expl:"Both factorisations contain one 2 and one 3. The shared primes are 2 and 3, so the GCD is 2 × 3 = 6."},
{sec:"T",type:"in",q:"12 = 2 × 2 × 3 and 18 = 2 × 3 × 3. What is the greatest common divisor of 12 and 18?",ans:6,
 hint:"Multiply the prime factors that appear in both lists.",expl:"The shared factors are one 2 and one 3. 2 × 3 = 6, so the GCD is 6."},
{sec:"T",type:"in",q:"8 = 2 × 2 × 2 and 12 = 2 × 2 × 3. What is the GCD of 8 and 12?",ans:4,
 expl:"Both numbers share two factors of 2. 2 × 2 = 4, so the GCD is 4."},
{sec:"T",type:"mc",q:"8 = 2 × 2 × 2 and 12 = 2 × 2 × 3. What is the LCM of 8 and 12?",mono:true,opts:["4","24","48","96"],a:1,
 hint:"Use each prime the greatest number of times it appears in either number.",
 expl:"The LCM needs three 2s (from 8) and one 3 (from 12): 2 × 2 × 2 × 3 = 24."},
{lvl:2,sec:"T",type:"in",q:"20 = 2 × 2 × 5 and 30 = 2 × 3 × 5. What is the GCD of 20 and 30?",ans:10,
 expl:"The shared primes are one 2 and one 5. 2 × 5 = 10."},
{lvl:2,sec:"T",type:"in",q:"Using 20 = 2 × 2 × 5 and 30 = 2 × 3 × 5, what is the LCM of 20 and 30?",ans:60,
 hint:"Take two 2s, one 3 and one 5.",expl:"2 × 2 × 3 × 5 = 60. Check: 60 = 20 × 3 = 30 × 2."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number that is a common divisor of 24 and 36.",opts:["4","6","8","12"],aMulti:[0,1,3],
 expl:"24 = 2 × 2 × 2 × 3 and 36 = 2 × 2 × 3 × 3. 4, 6 and 12 divide both. 8 = 2 × 2 × 2 does not divide 36."},
{lvl:2,sec:"T",type:"mc",q:"Two numbers have a GCD of 1. What does that tell you?",
 opts:["They share no prime factors","They are both prime numbers","One divides the other","They are both odd numbers"],a:0,
 expl:"A GCD of 1 means the factorisations have no prime in common. For example 8 and 9 have GCD 1 even though neither is prime."},
{lvl:3,sec:"T",type:"in",q:"The GCD of two numbers is 6 and their LCM is 36. One of the numbers is 12. What is the other number?",ans:18,
 hint:"GCD × LCM equals the product of the two numbers.",
 expl:"GCD × LCM = 6 × 36 = 216, which equals the product of the two numbers. 216 ÷ 12 = 18. Check: GCD(12, 18) = 6 and LCM(12, 18) = 36."},
{lvl:3,sec:"T",type:"in",q:"Ravi has 24 red beads and 36 blue beads. He makes identical bracelets using every bead. What is the greatest number of bracelets he can make?",
 ans:12,hint:"The number of bracelets must divide both 24 and 36.",
 expl:"The greatest number that divides both 24 and 36 is the GCD, 12. Each bracelet gets 2 red and 3 blue beads."}
],

"g3-fracadd": [
{sec:"F",type:"mc",q:"What is 1/5 + 2/5?",mono:true,opts:["3/5","3/10","2/5","1/5"],a:0,
 expl:"The pieces are the same size, so add the numerators: 1 + 2 = 3 fifths. The answer is 3/5."},
{sec:"F",type:"mc",q:"What is 3/8 + 2/8?",mono:true,opts:["5/8","5/16","6/8","1/8"],a:0,
 expl:"3 eighths + 2 eighths = 5 eighths. The denominator stays 8, so the answer is 5/8."},
{sec:"F",type:"in",q:"When you add 2/7 + 3/7, what is the numerator (top number) of the answer?",ans:5,
 hint:"Add the top numbers only.",expl:"2 + 3 = 5, so 2/7 + 3/7 = 5/7 and the numerator is 5."},
{sec:"F",type:"mc",q:"Why does the denominator stay the same when adding 1/4 + 2/4?",
 opts:["The pieces are the same size","You always add the bottom numbers","Quarters are very small pieces","You multiply the top numbers"],a:0,
 expl:"Quarters plus quarters are still quarters. Only the number of pieces changes: 1 + 2 = 3 quarters, so 1/4 + 2/4 = 3/4."},
{lvl:2,sec:"F",type:"mc",q:"What is 3/8 + 3/8 + 1/8?",mono:true,opts:["7/8","7/24","6/8","1"],a:0,
 expl:"Add the numerators: 3 + 3 + 1 = 7. The answer is 7/8."},
{lvl:2,sec:"F",type:"mc",q:"Jun ate 2/6 of a pizza and Amir ate 3/6 of the same pizza. What fraction of the pizza did they eat altogether?",mono:true,
 opts:["5/6","5/12","1/6","6/5"],a:0,
 expl:"2 sixths + 3 sixths = 5 sixths. Together they ate 5/6 of the pizza."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY sum that equals 1 whole.",mono:true,
 opts:["1/3 + 2/3","2/5 + 3/5","1/4 + 2/4","3/8 + 5/8"],aMulti:[0,1,3],
 expl:"1/3 + 2/3 = 3/3, 2/5 + 3/5 = 5/5 and 3/8 + 5/8 = 8/8, which all equal 1. But 1/4 + 2/4 = 3/4."},
{lvl:3,sec:"F",type:"mc",q:"Leila adds 3/10 and 4/10 and gets 7/20. What mistake did she make?",
 opts:["She added the denominators","She added the numerators","She multiplied the numerators","She forgot to add"],a:0,
 expl:"Tenths plus tenths are still tenths, so the denominator should stay 10. She wrongly added 10 + 10. The correct sum is 7/10."},
{lvl:3,sec:"F",type:"in",q:"A cake is cut into 8 equal slices. Maya eats 3/8 of the cake and Theo eats 2/8. How many slices are left?",ans:3,
 hint:"First find the fraction eaten, then think in slices.",
 expl:"3/8 + 2/8 = 5/8 of the cake is eaten, which is 5 slices. 8 − 5 = 3 slices are left."},
{lvl:3,sec:"F",type:"order",q:"Put these sums in order from smallest to largest.",mono:true,
 items:["1/8 + 2/8","2/8 + 4/8","3/8 + 1/8"],ansOrder:["1/8 + 2/8","3/8 + 1/8","2/8 + 4/8"],
 expl:"1/8 + 2/8 = 3/8, 3/8 + 1/8 = 4/8 and 2/8 + 4/8 = 6/8. In order: 3/8, 4/8, 6/8."}
],

"g3-fracmultw": [
{sec:"F",type:"mc",q:"What is 3 × 1/4?",mono:true,opts:["3/4","1/12","3/12","4/3"],a:0,
 expl:"3 × 1/4 means 1/4 + 1/4 + 1/4 = 3/4."},
{sec:"F",type:"in",q:"4 × 2/5 means adding 2/5 how many times?",ans:4,
 expl:"Multiplying by 4 is the same as adding the fraction 4 times: 2/5 + 2/5 + 2/5 + 2/5."},
{sec:"F",type:"mc",q:"What is 4 × 2/5?",mono:true,opts:["8/5","8/20","6/5","2/20"],a:0,
 hint:"Multiply only the numerator.",expl:"4 × 2 = 8, so 4 × 2/5 = 8/5. The denominator stays 5."},
{sec:"F",type:"in",q:"What is 2 × 1/2? Type a whole number.",ans:1,
 expl:"Two halves make one whole: 2 × 1/2 = 2/2 = 1."},
{lvl:2,sec:"F",type:"in",q:"What is 6 × 1/3? Type a whole number.",ans:2,hint:"Six thirds is how many wholes?",
 expl:"6 × 1/3 = 6/3, and 6 ÷ 3 = 2. So the answer is 2."},
{lvl:2,sec:"F",type:"mc",q:"What is 5 × 3/10?",mono:true,opts:["15/10","15/50","8/10","3/50"],a:0,
 expl:"5 × 3 = 15, so 5 × 3/10 = 15/10, which is 1 and 5/10."},
{lvl:2,sec:"F",type:"in",q:"Farah pours 1/4 of a litre of juice into each of 8 glasses. How many litres of juice does she use in total?",ans:2,
 hint:"Four quarters make one litre.",expl:"8 × 1/4 = 8/4 = 2 litres."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY product that equals 6/8.",mono:true,
 opts:["6 × 1/8","3 × 2/8","2 × 3/8","4 × 2/8"],aMulti:[0,1,2],
 expl:"6 × 1/8 = 6/8, 3 × 2/8 = 6/8 and 2 × 3/8 = 6/8. But 4 × 2/8 = 8/8, which is 1."},
{lvl:3,sec:"F",type:"in",q:"A recipe uses 2/3 of a cup of flour. Idris makes the recipe 6 times. How many cups of flour does he use?",ans:4,
 hint:"Work out 6 × 2/3, then change it to a whole number.",
 expl:"6 × 2/3 = 12/3, and 12 ÷ 3 = 4. He uses 4 cups of flour."},
{lvl:3,sec:"F",type:"in",q:"Hugo runs 3/4 of a km each day. How many km does he run in 8 days?",ans:6,
 hint:"Multiply the numerator by 8, then divide by 4.",
 expl:"8 × 3/4 = 24/4, and 24 ÷ 4 = 6. He runs 6 km."}
],

"g3-benchmark": [
{sec:"F",type:"mc",q:"Is 3/8 less than, equal to, or greater than 1/2?",
 opts:["less than 1/2","equal to 1/2","greater than 1/2"],a:0,hint:"How many eighths make one half?",
 expl:"1/2 = 4/8. Since 3/8 is less than 4/8, 3/8 is less than 1/2."},
{sec:"F",type:"mc",q:"Which fraction is closest to 0?",mono:true,opts:["1/10","1/2","9/10","5/6"],a:0,
 expl:"1/10 is one small piece out of ten, so it is very close to 0. The others are half or more of a whole."},
{sec:"F",type:"mc",q:"Which fraction is closest to 1?",mono:true,opts:["7/8","1/8","1/2","3/8"],a:0,
 expl:"7/8 is only 1/8 away from a whole. The others are much further from 1."},
{sec:"F",type:"in",q:"What numerator makes ?/12 equal to exactly 1/2?",ans:6,hint:"Half of 12 pieces.",
 expl:"Half of 12 is 6, so 6/12 = 1/2."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY fraction that is greater than 1/2.",mono:true,
 opts:["5/8","2/6","7/10","4/9"],aMulti:[0,2],hint:"Compare each numerator with half of its denominator.",
 expl:"5/8 is more than 4/8 and 7/10 is more than 5/10, so both are greater than 1/2. 2/6 is less than 3/6 and 4/9 is less than 4 and a half ninths."},
{lvl:2,sec:"F",type:"mc",q:"Which is greater: 5/9 or 3/7? Use 1/2 as a benchmark.",
 opts:["5/9, because it is more than 1/2","3/7, because it is more than 1/2","They are equal","5/9, because 9 is bigger"],a:0,
 expl:"Half of 9 is 4 and a half, so 5/9 is more than 1/2. Half of 7 is 3 and a half, so 3/7 is less than 1/2. So 5/9 is greater."},
{lvl:2,sec:"F",type:"order",q:"Order these fractions from smallest to largest.",mono:true,
 items:["4/7","1/9","8/9","1/2"],ansOrder:["1/9","1/2","4/7","8/9"],
 expl:"1/9 is close to 0. 4/7 is just over 1/2 (half of 7 is 3 and a half). 8/9 is close to 1. So the order is 1/9, 1/2, 4/7, 8/9."},
{lvl:3,sec:"F",type:"mc",q:"Which fraction is closer to 1: 5/6 or 7/8?",
 opts:["7/8, because it is 1/8 away from 1","5/6, because it is 1/6 away from 1","They are the same distance","5/6, because 5 is smaller"],a:0,
 hint:"How far is each fraction from a whole?",
 expl:"5/6 is 1/6 away from 1 and 7/8 is 1/8 away. Eighths are smaller than sixths, so 7/8 is closer to 1."},
{lvl:3,sec:"F",type:"mc",q:"Kira ate 3/7 of her sandwich and Malik ate 4/9 of his sandwich of the same size. Who ate less than half?",
 opts:["Both of them","Only Kira","Only Malik","Neither of them"],a:0,
 expl:"Half of 7 is 3 and a half, so 3/7 is less than half. Half of 9 is 4 and a half, so 4/9 is also less than half. Both ate less than half."},
{lvl:3,sec:"F",type:"in",q:"Think of fractions ?/12 where ? is a whole number. How many of them are greater than 1/2 but less than 1?",ans:5,
 hint:"Write 1/2 and 1 as twelfths first.",
 expl:"1/2 = 6/12 and 1 = 12/12. The numerators 7, 8, 9, 10 and 11 fit between them, so there are 5 such fractions."}
],

"g3-simpleeq": [
{sec:"L",type:"in",q:"n + 7 = 15. What is n?",ans:8,hint:"What do you add to 7 to get 15?",
 expl:"15 − 7 = 8, so n = 8. Check: 8 + 7 = 15."},
{sec:"L",type:"in",q:"4 × m = 28. What is m?",ans:7,hint:"Four times what is 28?",
 expl:"28 ÷ 4 = 7, so m = 7."},
{sec:"L",type:"mc",q:"Which value of x makes x − 5 = 9 true?",mono:true,opts:["14","4","45","9"],a:0,
 expl:"Add 5 to both sides: x = 9 + 5 = 14. Check: 14 − 5 = 9."},
{sec:"L",type:"in",q:"20 − y = 12. What is y?",ans:8,expl:"20 − 12 = 8, so y = 8. Check: 20 − 8 = 12."},
{lvl:2,sec:"L",type:"in",q:"36 ÷ k = 9. What is k?",ans:4,hint:"36 divided by what gives 9?",
 expl:"9 × 4 = 36, so k = 4."},
{lvl:2,sec:"L",type:"mc",q:"Which equation has the solution t = 6?",mono:true,
 opts:["3 × t = 18","t + 6 = 6","t − 6 = 6","t ÷ 3 = 18"],a:0,
 expl:"3 × 6 = 18, so t = 6 works in the first equation. The others give t = 0, t = 12 and t = 54."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY equation that is true when p = 5.",mono:true,
 opts:["p + p = 10","3 × p = 15","p − 1 = 3","20 ÷ p = 4"],aMulti:[0,1,3],
 expl:"5 + 5 = 10, 3 × 5 = 15 and 20 ÷ 5 = 4 are all true. But 5 − 1 = 4, not 3."},
{lvl:3,sec:"L",type:"in",q:"2 × n + 3 = 17. What is n?",ans:7,hint:"First take away 3, then divide.",
 expl:"17 − 3 = 14, so 2 × n = 14 and n = 7. Check: 2 × 7 + 3 = 17."},
{lvl:3,sec:"L",type:"in",q:"Anya thinks of a number, doubles it, then adds 5 to get 21. What was her number?",ans:8,
 hint:"Undo the steps in reverse order.",expl:"21 − 5 = 16, and half of 16 is 8. Check: 8 × 2 + 5 = 21."},
{lvl:3,sec:"L",type:"in",q:"In the equation 4 × b = 60 − 12, what is b?",ans:12,hint:"Work out the right-hand side first.",
 expl:"60 − 12 = 48, so 4 × b = 48 and b = 48 ÷ 4 = 12."}
],

"g3-varpat": [
{sec:"L",type:"in",q:"The pattern 3, 6, 9, 12, ... has the rule 3 × n, where n is the position. What is the 5th term?",ans:15,
 hint:"Put n = 5 into the rule.",expl:"3 × 5 = 15, so the 5th term is 15."},
{sec:"L",type:"in",q:"A pattern has the rule 2 × n + 1, where n is the position. What is the 4th term?",ans:9,
 expl:"2 × 4 + 1 = 8 + 1 = 9."},
{sec:"L",type:"mc",q:"Which rule gives the pattern 5, 10, 15, 20, ...?",mono:true,opts:["5 × n","n + 5","5 + n + n","n × n"],a:0,
 expl:"Position 1 gives 5, position 2 gives 10, position 3 gives 15. Each term is 5 times its position, so the rule is 5 × n."},
{sec:"L",type:"mc",q:"In the rule 4 × n, what does the letter n stand for?",
 opts:["The position in the pattern","The number 4","The last term","The total of all terms"],a:0,
 expl:"n is a variable that stands for the position: n = 1 gives the first term, n = 2 the second, and so on."},
{lvl:2,sec:"L",type:"in",q:"A pattern has the rule 10 − n. What is the 3rd term?",ans:7,
 expl:"10 − 3 = 7, so the 3rd term is 7. The pattern goes 9, 8, 7, ..."},
{lvl:2,sec:"L",type:"mc",q:"Which rule gives the pattern 4, 7, 10, 13, ...?",mono:true,
 opts:["3 × n + 1","4 × n","n + 3","3 × n − 1"],a:0,hint:"Test each rule with n = 1 and n = 2.",
 expl:"3 × 1 + 1 = 4 and 3 × 2 + 1 = 7, so 3 × n + 1 works. The others give 4, 8, ... or 4, 5, ... or 2, 5, ..."},
{lvl:2,sec:"L",type:"in",q:"Rosa builds towers. Tower number n uses 2 × n + 3 blocks. How many blocks does tower 10 use?",ans:23,
 expl:"2 × 10 + 3 = 20 + 3 = 23 blocks."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY rule that gives 8 as its 2nd term.",mono:true,
 opts:["4 × n","n + 6","10 − n","2 × n + 3"],aMulti:[0,1,2],
 expl:"With n = 2: 4 × 2 = 8, 2 + 6 = 8 and 10 − 2 = 8. But 2 × 2 + 3 = 7."},
{lvl:3,sec:"L",type:"in",q:"A pattern has the rule 3 × n + 2. Which position n gives the term 29?",ans:9,
 hint:"Take away 2, then divide by 3.",expl:"29 − 2 = 27 and 27 ÷ 3 = 9, so n = 9. Check: 3 × 9 + 2 = 29."},
{lvl:3,sec:"L",type:"in",q:"Nico's pattern is 6, 11, 16, 21, ... and the rule is 5 × n + 1. What is the 20th term?",ans:101,
 expl:"5 × 20 + 1 = 100 + 1 = 101."},
{lvl:3,sec:"L",type:"in",q:"The rule 4 × n − 1 gives 3, 7, 11, ... What is the position n of the first term greater than 30?",ans:8,
 hint:"Keep going until you pass 30.",expl:"4 × 7 − 1 = 27 is too small. 4 × 8 − 1 = 31 is the first term greater than 30, so n = 8."}
],

"g3-evaluate": [
{sec:"L",type:"in",q:"If a = 4, what is a + 9?",ans:13,expl:"Replace a with 4: 4 + 9 = 13."},
{sec:"L",type:"in",q:"If b = 6, what is 3 × b?",ans:18,expl:"Replace b with 6: 3 × 6 = 18."},
{sec:"L",type:"in",q:"If x = 7, what is 2 × x + 1?",ans:15,hint:"Multiply first, then add.",
 expl:"2 × 7 = 14, then 14 + 1 = 15."},
{sec:"L",type:"mc",q:"If m = 5, which expression equals 20?",mono:true,opts:["4 × m","m + 5","m × m","20 − m"],a:0,
 expl:"4 × 5 = 20. The others give 10, 25 and 15."},
{lvl:2,sec:"L",type:"in",q:"If p = 3 and q = 4, what is p × q + 2?",ans:14,
 expl:"3 × 4 = 12, then 12 + 2 = 14."},
{lvl:2,sec:"L",type:"in",q:"If n = 8, what is 50 − 3 × n?",ans:26,hint:"Do the multiplication before the subtraction.",
 expl:"3 × 8 = 24, then 50 − 24 = 26."},
{lvl:2,sec:"L",type:"mc",q:"If y = 6, what is (y + 4) ÷ 2?",mono:true,opts:["5","7","8","10"],a:0,
 hint:"Brackets first.",expl:"6 + 4 = 10, then 10 ÷ 2 = 5."},
{lvl:2,sec:"L",type:"multi",q:"If k = 3, select EVERY expression that equals 12.",mono:true,
 opts:["4 × k","k + 9","k × k + 3","10 − k"],aMulti:[0,1,2],
 expl:"4 × 3 = 12, 3 + 9 = 12 and 3 × 3 + 3 = 12. But 10 − 3 = 7."},
{lvl:3,sec:"L",type:"in",q:"The cost in dollars of n tickets is 5 × n + 2. What is the cost, in dollars, of 7 tickets?",ans:37,
 expl:"5 × 7 = 35, then 35 + 2 = 37 dollars."},
{lvl:3,sec:"L",type:"in",q:"If a = 9 and b = 4, what is (a − b) × (a + b)?",ans:65,hint:"Work out each bracket first.",
 expl:"a − b = 5 and a + b = 13. 5 × 13 = 65."},
{lvl:3,sec:"L",type:"in",q:"Sami's expression is 2 × x + 3 × y. When x = 5 and y = 4, what is its value?",ans:22,
 expl:"2 × 5 = 10 and 3 × 4 = 12. 10 + 12 = 22."}
],

"g3-syslist": [
{sec:"K",type:"in",q:"Bao has a red shirt and a blue shirt, and black shorts and white shorts. Listing every outfit, how many outfits are there?",ans:4,
 hint:"Pair each shirt with each pair of shorts.",
 expl:"red-black, red-white, blue-black, blue-white. That is 4 outfits."},
{sec:"K",type:"mc",q:"Which list shows every way to arrange the letters A and B?",opts:["AB, BA","AB","AB, BA, AA","A, B"],a:0,
 expl:"Either A comes first or B comes first: AB and BA. AA repeats a letter, so it is not an arrangement of A and B."},
{sec:"K",type:"in",q:"Using coins worth 1 cent and 2 cents, list every way to make 4 cents. How many ways are there?",ans:3,
 hint:"Start with all 1-cent coins, then swap two of them for a 2-cent coin.",
 expl:"1 + 1 + 1 + 1, 1 + 1 + 2, and 2 + 2. That is 3 ways."},
{sec:"K",type:"mc",q:"Why is it helpful to make a systematic list?",
 opts:["So nothing is missed or repeated","So the answer is always bigger","So you can skip the counting","So you only need one example"],a:0,
 expl:"Listing in a fixed order makes sure every possibility is counted exactly once."},
{lvl:2,sec:"K",type:"in",q:"How many two-letter arrangements can you make from the letters X, Y and Z, using each letter at most once? (XY and YX count as different.)",ans:6,
 hint:"List them starting with X, then Y, then Z.",
 expl:"XY, XZ, YX, YZ, ZX, ZY. That is 6 arrangements."},
{lvl:2,sec:"K",type:"in",q:"In how many ways can you write 7 as a sum of two whole numbers, if 3 + 4 and 4 + 3 count as the same? Include 0 + 7.",ans:4,
 hint:"Start with 0 + 7 and let the first number grow.",
 expl:"0 + 7, 1 + 6, 2 + 5, 3 + 4. After that the pairs repeat, so there are 4 ways."},
{lvl:2,sec:"K",type:"mc",q:"Farah lists all two-digit numbers made from the digits 2, 5 and 8 with no repeated digit. Which number should NOT be on her list?",
 opts:["55","25","82","58"],a:0,
 expl:"55 uses the digit 5 twice. The full list is 25, 28, 52, 58, 82, 85."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY way to make 10 cents using only 5-cent and 2-cent coins.",
 opts:["two 5-cent coins","five 2-cent coins","one 5-cent and two 2-cent coins","one 5-cent and three 2-cent coins"],aMulti:[0,1],
 expl:"5 + 5 = 10 and 2 + 2 + 2 + 2 + 2 = 10. One 5-cent coin with 2-cent coins gives 7, 9, 11, ... and never 10."},
{lvl:3,sec:"K",type:"in",q:"How many different three-digit numbers can be made using only the digits 1 and 2? Digits may repeat.",ans:8,
 hint:"List them in order: 111, 112, ...",
 expl:"111, 112, 121, 122, 211, 212, 221, 222. That is 8 numbers."},
{lvl:3,sec:"K",type:"in",q:"Omar has 1-cent, 2-cent and 5-cent coins. In how many different ways can he make 7 cents?",ans:6,
 hint:"Split into ways that use a 5-cent coin and ways that do not.",
 expl:"With a 5-cent coin: 5 + 2 and 5 + 1 + 1. Without: 2 + 2 + 2 + 1, 2 + 2 + 1 + 1 + 1, 2 + 1 + 1 + 1 + 1 + 1, and seven 1-cent coins. That is 2 + 4 = 6 ways."},
{lvl:3,sec:"K",type:"in",q:"How many different rectangles with whole-number sides have an area of 12 square units? (A 3 by 4 rectangle counts the same as a 4 by 3 one.)",ans:3,
 hint:"List pairs of numbers that multiply to 12.",
 expl:"1 × 12, 2 × 6 and 3 × 4. That is 3 rectangles."}
],

"g3-multprin": [
{sec:"K",type:"in",q:"A cafe offers 3 kinds of sandwich and 4 kinds of drink. How many different sandwich-and-drink combinations are there?",ans:12,
 hint:"Each sandwich can go with each drink.",expl:"3 × 4 = 12 combinations."},
{sec:"K",type:"in",q:"Tara has 5 shirts and 2 pairs of trousers. How many different outfits can she make?",ans:10,
 expl:"Each of the 5 shirts can go with either pair of trousers: 5 × 2 = 10 outfits."},
{sec:"K",type:"mc",q:"Which calculation gives the number of ways to choose one of 6 hats and one of 3 scarves?",mono:true,
 opts:["6 × 3","6 + 3","6 − 3","6 ÷ 3"],a:0,
 expl:"For each of the 6 hats there are 3 scarf choices, so multiply: 6 × 3 = 18 ways."},
{sec:"K",type:"in",q:"There are 2 paths from home to the park and 3 paths from the park to school. How many different routes go from home to school through the park?",ans:6,
 hint:"Each first path can be followed by any second path.",expl:"2 × 3 = 6 routes."},
{lvl:2,sec:"K",type:"in",q:"An ice-cream shop has 4 flavours, 2 kinds of cone and 3 toppings. How many flavour, cone and topping combinations are there?",ans:24,
 hint:"Multiply all three numbers.",expl:"4 × 2 × 3 = 24 combinations."},
{lvl:2,sec:"K",type:"in",q:"How many two-digit numbers have an odd tens digit (1, 3, 5, 7 or 9) and an even ones digit (0, 2, 4, 6 or 8)?",ans:25,
 hint:"Count the choices for each digit.",expl:"5 choices for the tens digit and 5 for the ones digit: 5 × 5 = 25 numbers."},
{lvl:2,sec:"K",type:"mc",q:"A locker code is one letter from A to Z followed by one digit from 0 to 9. How many codes are possible?",mono:true,
 opts:["260","36","2600","26"],a:0,
 expl:"There are 26 letters and 10 digits: 26 × 10 = 260 codes."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY situation with exactly 12 possible outcomes.",
 opts:["Choose 1 of 3 shirts and 1 of 4 hats","Roll a six-sided die and flip a coin","Choose 1 of 6 pens and 1 of 6 pencils","Choose 1 of 2 bags and 1 of 6 books"],aMulti:[0,1,3],
 expl:"3 × 4 = 12, 6 × 2 = 12 and 2 × 6 = 12. But 6 × 6 = 36."},
{lvl:3,sec:"K",type:"in",q:"A menu has 3 starters, 5 mains and 2 desserts. Jamal orders one main and one dessert but no starter. How many different meals can he order?",ans:10,
 hint:"Only two of the courses matter.",expl:"He ignores the starters: 5 × 2 = 10 meals."},
{lvl:3,sec:"K",type:"in",q:"Kai designs a flag with 2 stripes. Each stripe can be red, blue, green or yellow, and the two stripes must be different colours. How many flags are possible?",ans:12,
 hint:"After the first stripe is chosen, how many colours are left?",
 expl:"4 choices for the top stripe, then only 3 for the bottom stripe: 4 × 3 = 12 flags."},
{lvl:3,sec:"K",type:"in",q:"How many three-digit numbers have every digit odd?",ans:125,
 hint:"There are 5 odd digits.",expl:"Each of the three digits can be 1, 3, 5, 7 or 9: 5 × 5 × 5 = 125 numbers."}
],

"g3-composite": [
{sec:"G",type:"in",q:"An L-shape is made from a 4 by 3 rectangle and a 2 by 2 square joined together. What is its total area in square units?",ans:16,
 hint:"Find each area, then add.",expl:"4 × 3 = 12 and 2 × 2 = 4. 12 + 4 = 16 square units."},
{sec:"G",type:"mc",q:"To find the area of a shape made from two rectangles joined side by side, you should...",
 opts:["add the two areas","multiply the two areas","add all the side lengths","subtract the two areas"],a:0,
 expl:"Area is the space covered, so the two parts together cover the sum of their areas."},
{sec:"G",type:"in",q:"A shape is made from a 6 by 2 rectangle and a 3 by 3 square. What is its area in square units?",ans:21,
 expl:"6 × 2 = 12 and 3 × 3 = 9. 12 + 9 = 21 square units."},
{sec:"G",type:"mc",q:"A T-shape is split into a 6 by 1 rectangle on top and a 1 by 4 rectangle hanging below it. What is its area?",mono:true,
 opts:["10 square units","24 square units","11 square units","12 square units"],a:0,
 expl:"6 × 1 = 6 and 1 × 4 = 4. 6 + 4 = 10 square units."},
{lvl:2,sec:"G",type:"in",q:"An L-shaped room is 8 m long and 6 m wide with a 3 m by 2 m corner cut out. What is the floor area in square metres?",ans:42,
 hint:"Start with the full rectangle and take away the missing corner.",
 expl:"8 × 6 = 48 and the cut-out is 3 × 2 = 6. 48 − 6 = 42 square metres."},
{lvl:2,sec:"G",type:"in",q:"Iris draws a 7 by 5 rectangle and cuts a 2 by 2 square out of one corner. What is the area of the shape that is left, in square units?",ans:31,
 expl:"7 × 5 = 35 and 2 × 2 = 4. 35 − 4 = 31 square units."},
{lvl:2,sec:"G",type:"mc",q:"A staircase shape is made of unit squares: 1 square in the top row, 2 in the next, 3 in the next and 4 in the bottom row. What is its total area?",mono:true,
 opts:["10","4","16","9"],a:0,
 expl:"Add the rows: 1 + 2 + 3 + 4 = 10 square units."},
{lvl:2,sec:"G",type:"multi",q:"A shape is a 4 by 4 square with a 2 by 3 rectangle attached to one side. Select EVERY expression that gives its area.",mono:true,
 opts:["4 × 4 + 2 × 3","16 + 6","4 × 4 × 2 × 3","(4 + 2) × (4 + 3)"],aMulti:[0,1],
 expl:"The area is 4 × 4 + 2 × 3 = 16 + 6 = 22. Multiplying everything or adding the sides first gives the wrong shape."},
{lvl:3,sec:"G",type:"in",q:"A square garden has sides of 10 m. A straight path 10 m long and 2 m wide runs across it from one side to the other. What area of the garden is NOT path, in square metres?",ans:80,
 hint:"Subtract the path from the whole square.",expl:"10 × 10 = 100 and the path is 10 × 2 = 20. 100 − 20 = 80 square metres."},
{lvl:3,sec:"G",type:"in",q:"A cross is made from a 3 by 9 rectangle standing upright and a 9 by 3 rectangle lying across its middle. They overlap in a 3 by 3 square. What is the area of the cross in square units?",ans:45,
 hint:"Do not count the overlap twice.",
 expl:"Each rectangle has area 27. Adding gives 54, but the 3 × 3 = 9 overlap was counted twice. 54 − 9 = 45 square units."},
{lvl:3,sec:"G",type:"in",q:"A picture frame is a 12 by 10 rectangle with an 8 by 6 rectangular hole in the middle. What is the area of the frame itself in square units?",ans:72,
 expl:"12 × 10 = 120 and the hole is 8 × 6 = 48. 120 − 48 = 72 square units."}
],

"g3-volpack": [
{sec:"G",type:"in",q:"A box is filled with one layer of unit cubes, 4 cubes long and 3 cubes wide. How many cubes are in the layer?",ans:12,
 expl:"4 × 3 = 12 cubes in the layer."},
{sec:"G",type:"in",q:"A box holds 3 layers of cubes with 6 cubes in each layer. How many cubes fill the box?",ans:18,
 hint:"Multiply the cubes per layer by the number of layers.",expl:"3 × 6 = 18 cubes."},
{sec:"G",type:"mc",q:"Finding volume by packing means...",
 opts:["counting cubes that fill a shape","measuring around the outside edge","counting the corners of a shape","adding up all the side lengths"],a:0,
 expl:"Volume is the space inside a solid. Packing it with unit cubes and counting them measures that space."},
{sec:"G",type:"in",q:"Wei packs cubes into a box that is 5 cubes long, 2 cubes wide and 2 cubes tall. How many cubes fit?",ans:20,
 hint:"Find one layer first.",expl:"One layer is 5 × 2 = 10 cubes. Two layers make 10 × 2 = 20 cubes."},
{lvl:2,sec:"G",type:"in",q:"A box is 4 cubes long, 4 cubes wide and 3 cubes tall. What is its volume in cubic units?",ans:48,
 expl:"Each layer has 4 × 4 = 16 cubes, and 3 layers make 16 × 3 = 48 cubic units."},
{lvl:2,sec:"G",type:"mc",q:"A box has a bottom layer of 3 by 5 cubes and holds 45 cubes in total. How many layers are there?",mono:true,
 opts:["3","15","5","9"],a:0,hint:"How many cubes are in one layer?",
 expl:"One layer is 3 × 5 = 15 cubes. 45 ÷ 15 = 3 layers."},
{lvl:2,sec:"G",type:"in",q:"One box is 2 by 3 by 4 cubes and another is 3 by 3 by 3 cubes. How many more cubes does the larger box hold?",ans:3,
 hint:"Find both volumes.",expl:"2 × 3 × 4 = 24 and 3 × 3 × 3 = 27. 27 − 24 = 3 more cubes."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY box that holds exactly 24 unit cubes.",mono:true,
 opts:["2 by 3 by 4","1 by 4 by 6","2 by 2 by 8","3 by 3 by 3"],aMulti:[0,1],
 expl:"2 × 3 × 4 = 24 and 1 × 4 × 6 = 24. But 2 × 2 × 8 = 32 and 3 × 3 × 3 = 27."},
{lvl:3,sec:"G",type:"in",q:"Mei has 36 cubes. She packs all of them into a box that is 3 cubes long and 4 cubes wide. How tall is the box, in cubes?",ans:3,
 hint:"How many cubes are in each layer?",expl:"Each layer holds 3 × 4 = 12 cubes. 36 ÷ 12 = 3 layers, so the box is 3 cubes tall."},
{lvl:3,sec:"G",type:"in",q:"A box is 5 cubes long, 4 cubes wide and 3 cubes tall. It contains 2 full layers of cubes. How many more cubes are needed to fill it?",ans:20,
 hint:"One more layer is missing.",expl:"Each layer is 5 × 4 = 20 cubes. The box needs 3 layers, so one more layer of 20 cubes is needed."},
{lvl:3,sec:"G",type:"in",q:"A large cube is built from small cubes, with 3 small cubes along each edge. How many small cubes are used?",ans:27,
 expl:"3 × 3 × 3 = 27 small cubes."}
],

"g3-angles": [
{sec:"G",type:"mc",q:"An angle that looks like the corner of a square is called...",
 opts:["a right angle","an acute angle","an obtuse angle","a straight angle"],a:0,
 expl:"The corner of a square is a right angle, which measures 90°."},
{sec:"G",type:"mc",q:"An angle that is smaller than a right angle is...",opts:["acute","obtuse","right","straight"],a:0,
 expl:"Acute angles are less than 90°, like the sharp point of a slice of pizza."},
{sec:"G",type:"mc",q:"An angle that is bigger than a right angle but smaller than a straight line is...",opts:["obtuse","acute","right","straight"],a:0,
 expl:"Obtuse angles are between 90° and 180°, so they look wider than a square corner."},
{sec:"G",type:"in",q:"How many degrees are in a right angle?",ans:90,expl:"A right angle measures 90°. Four of them make a full turn of 360°."},
{sec:"G",type:"in",q:"How many right angles does a rectangle have?",ans:4,expl:"Every corner of a rectangle is a right angle, and a rectangle has 4 corners."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY angle that is acute.",mono:true,opts:["30°","89°","90°","120°"],aMulti:[0,1],
 expl:"Acute means less than 90°. 30° and 89° are acute. 90° is a right angle and 120° is obtuse."},
{lvl:2,sec:"G",type:"mc",q:"An angle measures 135°. What kind of angle is it?",opts:["obtuse","acute","right","straight"],a:0,
 expl:"135° is more than 90° but less than 180°, so it is obtuse."},
{lvl:2,sec:"G",type:"order",q:"Put these angles in order from smallest to largest.",
 items:["a right angle","an obtuse angle","an acute angle"],ansOrder:["an acute angle","a right angle","an obtuse angle"],
 expl:"Acute angles are less than 90°, a right angle is exactly 90°, and obtuse angles are more than 90°."},
{lvl:2,sec:"G",type:"in",q:"Two right angles placed side by side make a straight angle. How many degrees is a straight angle?",ans:180,
 expl:"90° + 90° = 180°."},
{lvl:3,sec:"G",type:"in",q:"At 3 o'clock the hands of a clock make a right angle. How many degrees is the angle between the hands at 1 o'clock?",ans:30,
 hint:"A right angle at 3 o'clock covers 3 hours.",
 expl:"3 hours make 90°, so each hour is 90 ÷ 3 = 30°. At 1 o'clock the hands are 1 hour apart: 30°."},
{lvl:3,sec:"G",type:"mc",q:"Noor draws a triangle. Which is impossible?",
 opts:["two obtuse angles","two acute angles","one right angle","three acute angles"],a:0,
 hint:"The three angles of a triangle add up to 180°.",
 expl:"Two obtuse angles would already add to more than 180°, which is all a triangle has. The other options are possible."},
{lvl:3,sec:"G",type:"in",q:"A right angle is split into two smaller angles. One of them is 35°. How many degrees is the other?",ans:55,
 expl:"90 − 35 = 55°."}
],

"g3-lines": [
{sec:"G",type:"mc",q:"Two straight lines that never meet, no matter how far they go, are...",
 opts:["parallel","perpendicular","curved","equal"],a:0,
 expl:"Parallel lines stay the same distance apart forever, so they never meet."},
{sec:"G",type:"mc",q:"Two lines that cross at a right angle are...",opts:["perpendicular","parallel","acute","obtuse"],a:0,
 expl:"Perpendicular lines meet at 90°, like the corner of a page."},
{sec:"G",type:"mc",q:"Which capital letter has two parallel line segments?",opts:["H","V","T","X"],a:0,
 expl:"The two upright strokes of H never meet, so they are parallel. T has perpendicular strokes, and V and X have crossing or slanted ones."},
{sec:"G",type:"mc",q:"Which capital letter has two perpendicular line segments?",opts:["L","V","N","O"],a:0,
 expl:"The two strokes of L meet at a right angle, so they are perpendicular."},
{sec:"G",type:"in",q:"How many pairs of parallel sides does a rectangle have?",ans:2,
 expl:"The top and bottom are parallel, and the left and right sides are parallel: 2 pairs."},
{lvl:2,sec:"G",type:"in",q:"How many pairs of perpendicular sides (sides meeting at a corner) does a square have?",ans:4,
 hint:"Look at each corner.",expl:"Each of the 4 corners is where two sides meet at a right angle, so there are 4 perpendicular pairs."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY shape that has at least one pair of parallel sides.",
 opts:["square","parallelogram","triangle","circle"],aMulti:[0,1],
 expl:"A square has two pairs of parallel sides and a parallelogram has two pairs. A triangle has no parallel sides, and a circle has no straight sides at all."},
{lvl:2,sec:"G",type:"mc",q:"Line A is perpendicular to line B. Line C is also perpendicular to line B. What can you say about lines A and C?",
 opts:["They are parallel","They are perpendicular","They must cross","They are the same line"],a:0,
 expl:"Both A and C make right angles with B, so they point the same way and are parallel to each other."},
{lvl:2,sec:"G",type:"mc",q:"The two rails of a railway track are an example of...",
 opts:["parallel lines","perpendicular lines","crossing lines","curved lines"],a:0,
 expl:"The rails stay the same distance apart and never meet, so they are parallel."},
{lvl:3,sec:"G",type:"in",q:"Elias draws 3 horizontal parallel lines, then 2 vertical lines across them. At how many points do his lines cross?",ans:6,
 hint:"Each vertical line crosses every horizontal line.",expl:"Each vertical line crosses all 3 horizontal lines: 2 × 3 = 6 crossing points."},
{lvl:3,sec:"G",type:"mc",q:"Line P is parallel to line Q, and line R is perpendicular to line Q. Which is true?",
 opts:["R is perpendicular to P","R is parallel to P","R never meets P","P and Q cross"],a:0,
 expl:"P points the same way as Q, and R makes a right angle with Q, so R also makes a right angle with P."},
{lvl:3,sec:"G",type:"in",q:"Chioma draws 4 parallel lines, then one more line perpendicular to all of them. Counting all 4 angles at each crossing, how many right angles does she make?",ans:16,
 hint:"How many crossings are there, and how many angles at each?",
 expl:"The new line crosses each of the 4 lines once, making 4 crossings. Each crossing has 4 right angles: 4 × 4 = 16."}
]
};
