/* Grade 3. */
export const G3_BANKS = {
"g3-mult": [
{sec:"N",type:"in",q:"6 × 4 = ?",ans:24,hint:"Six groups of four.",expl:"6 × 4 = 24."},
{sec:"N",type:"in",q:"7 × 8 = ?",ans:56,expl:"7 × 8 = 56."},
{sec:"N",type:"in",q:"9 × 3 = ?",ans:27,expl:"9 × 3 = 27."},
{sec:"N",type:"mc",q:"Which is the same as 5 × 6?",mono:true,opts:["6 × 5","5 + 6","6 + 6","5 × 5"],a:0,
 expl:"Multiplication can be done in either order, so 5 × 6 = 6 × 5 = 30."},
{sec:"N",type:"in",q:"A spider has 8 legs. How many legs do 4 spiders have?",ans:32,
 expl:"4 × 8 = 32 legs."},
{lvl:2,sec:"N",type:"in",q:"8 × 7 = ?",ans:56,hint:"It is the same as 7 × 8.",
 expl:"8 × 7 = 56 — the same product as 7 × 8, just the other way round."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY expression equal to 24.",
 opts:["6 × 4","3 × 8","12 × 2","5 × 5"],aMulti:[0,1,2],
 expl:"6 × 4, 3 × 8 and 12 × 2 all make 24. 5 × 5 is 25."},
{lvl:2,sec:"N",type:"in",q:"What is 4 × 25?",ans:100,hint:"Think of quarters of a hundred.",
 expl:"25 four times is 100 — like four 25p coins making £1."},
{lvl:3,sec:"N",type:"in",q:"A room has 6 rows of 7 chairs. If 5 chairs are removed, how many remain?",
 ans:37,hint:"Find the total first.",expl:"6 × 7 = 42 chairs, minus 5 removed leaves 37."},
{lvl:3,sec:"N",type:"in",q:"What is the 8th number in the pattern 3, 6, 9, 12, ...?",ans:24,
 hint:"It counts up in threes.",expl:"The pattern is multiples of 3, so the 8th is 8 × 3 = 24."}
],

"g3-fracnum": [
{sec:"F",type:"mc",q:"A pizza is cut into 4 equal slices and you eat 1. What fraction did you eat?",
 mono:true,opts:["1/4","1/3","4/1","3/4"],a:0,
 expl:"One slice out of four equal slices is 1/4."},
{sec:"F",type:"mc",q:"Which fraction is the largest?",mono:true,opts:["1/2","1/3","1/4","1/8"],a:0,
 expl:"The more pieces you cut something into, the smaller each piece. Halves are the biggest here."},
{sec:"F",type:"in",q:"How many quarters make one whole?",ans:4,
 expl:"Four quarters make a whole: 1/4 + 1/4 + 1/4 + 1/4 = 1."},
{sec:"F",type:"mc",q:"Which is the same as 2/4?",mono:true,opts:["1/2","1/4","3/4","2/2"],a:0,
 expl:"Two quarters is the same amount as one half."},
{lvl:2,sec:"F",type:"order",q:"Put these fractions in order, smallest first.",
 items:["1/2","1/8","1/3","1/4"],ansOrder:["1/8","1/4","1/3","1/2"],
 expl:"With a numerator of 1, the bigger the bottom number the smaller the fraction."},
{lvl:2,sec:"F",type:"mc",q:"Which fraction is closest to 1 whole?",mono:true,
 opts:["7/8","1/2","3/4","2/3"],a:0,
 expl:"7/8 is only 1/8 short of a whole, closer than the others."},
{lvl:3,sec:"F",type:"in",q:"Three friends share 2 pizzas equally. What fraction of a pizza does each get? Type the bottom number of the fraction.",
 ans:3,hint:"Each pizza is split three ways.",
 expl:"Each pizza splits into thirds, so each friend gets 2/3 of a pizza. The bottom number is 3."}
],

"g3-area": [
{sec:"G",type:"in",q:"A rectangle is 5 squares long and 3 squares wide. What is its area in square units?",ans:15,
 hint:"Count the squares, or multiply.",expl:"Area = 5 × 3 = 15 square units."},
{sec:"G",type:"in",q:"A square has sides of 4 units. What is its area in square units?",ans:16,
 expl:"A square's sides are equal, so area = 4 × 4 = 16 square units."},
{sec:"G",type:"mc",q:"What does area measure?",
 opts:["The space inside a shape","The distance around a shape","The number of corners","The longest side"],a:0,
 expl:"Area is the space inside. The distance around the outside is the perimeter."},
{lvl:2,sec:"G",type:"in",q:"A rectangle has an area of 24 square units and is 6 units long. How wide is it?",
 ans:4,hint:"What times 6 makes 24?",expl:"6 × 4 = 24, so the width is 4 units."},
{lvl:2,sec:"G",type:"in",q:"An L-shape is made from a 3 by 2 rectangle joined to a 2 by 2 square. What is the total area in square units?",
 ans:10,hint:"Work out each piece, then add.",
 expl:"The rectangle is 3 × 2 = 6 and the square is 2 × 2 = 4. Together 6 + 4 = 10 square units."},
{lvl:3,sec:"G",type:"in",q:"A rectangle has an area of 36 square units and a perimeter of 26 units. What is its longer side?",
 ans:9,hint:"Which pair multiplies to 36 and adds to 13?",
 expl:"Half the perimeter is 13, so the sides add to 13 and multiply to 36. That is 9 and 4, so the longer side is 9."}
],

"g3-div": [
{sec:"N",type:"in",q:"24 ÷ 6 = ?",ans:4,expl:"24 ÷ 6 = 4."},
{sec:"N",type:"in",q:"35 ÷ 5 = ?",ans:7,expl:"35 ÷ 5 = 7."},
{sec:"N",type:"mc",q:"Which division matches: 'sharing 18 stickers equally among 3 friends'?",mono:true,
 opts:["18 ÷ 3","3 ÷ 18","18 × 3","18 − 3"],a:0,
 expl:"Sharing equally among 3 means dividing by 3: 18 ÷ 3 = 6 stickers each."},
{sec:"N",type:"in",q:"42 ÷ 7 = ?",ans:6,expl:"42 ÷ 7 = 6."},
{sec:"N",type:"in",q:"A box has 48 pencils split evenly into 6 packs. How many pencils per pack?",ans:8,
 expl:"48 ÷ 6 = 8 pencils per pack."},
{lvl:2,sec:"N",type:"in",q:"56 ÷ 8 = ?",ans:7,expl:"56 ÷ 8 = 7."},
{lvl:2,sec:"N",type:"mc",q:"Which multiplication fact matches 45 ÷ 9 = 5?",mono:true,
 opts:["9 × 5 = 45","45 × 9 = 405","9 − 5 = 4","45 + 9 = 54"],a:0,
 expl:"Division undoes multiplication: 45 ÷ 9 = 5 because 9 × 5 = 45."},
{lvl:3,sec:"N",type:"in",q:"A number divided by 6 gives 9 with none left over. What is the number?",ans:54,
 hint:"Multiply to undo the division.",expl:"9 × 6 = 54."}
],

"g3-round": [
{sec:"N",type:"in",q:"Round 47 to the nearest ten.",ans:50,expl:"47 is closer to 50 than to 40."},
{sec:"N",type:"in",q:"Round 82 to the nearest ten.",ans:80,expl:"82 is closer to 80 than to 90."},
{sec:"N",type:"in",q:"Round 350 to the nearest hundred.",ans:400,
 hint:"350 is exactly halfway — round up.",expl:"Halfway points round up, so 350 rounds to 400."},
{sec:"N",type:"mc",q:"Round 125 to the nearest ten.",opts:["130","120","100","200"],a:0,
 expl:"125 is halfway between 120 and 130, and halfway points round up: 130."},
{sec:"N",type:"in",q:"Round 999 to the nearest hundred.",ans:1000,
 expl:"999 is only 1 away from 1000, so it rounds up to 1000."},
{lvl:2,sec:"N",type:"in",q:"A number rounds to 400 when rounded to the nearest hundred. What is the SMALLEST whole number it could be?",
 ans:350,hint:"Halfway points round up.",expl:"350 is the smallest number that rounds up to 400."},
{lvl:2,sec:"N",type:"in",q:"Round 3,462 to the nearest hundred.",ans:3500,
 expl:"The tens digit is 6, which rounds up: 3,462 rounds to 3,500."},
{lvl:3,sec:"N",type:"mc",q:"Which number rounds to 60 (nearest ten) AND to 100 (nearest hundred)?",mono:true,
 opts:["64","52","65","46"],a:0,
 expl:"64 rounds to 60 (nearest ten) and to 100 (nearest hundred, since it is closer to 100 than to 0). The others fail one test or the other."}
],

"g3-fraccomp": [
{sec:"F",type:"mc",q:"Which is greater: 3/4 or 1/4?",mono:true,
 opts:["3/4","1/4","They are equal","Cannot compare"],a:0,
 expl:"With the same denominator, more pieces means a greater fraction: 3/4 > 1/4."},
{sec:"F",type:"mc",q:"Which symbol makes this true?  2/3 ◯ 2/5",mono:true,opts:[">","<","="],a:0,
 expl:"Same numerator, so fewer pieces (thirds) means each piece is bigger: 2/3 > 2/5."},
{sec:"F",type:"mc",q:"Which is smaller: 1/6 or 1/3?",mono:true,
 opts:["1/6","1/3","They are equal","Cannot compare"],a:0,
 expl:"Cutting something into 6 pieces makes each piece smaller than cutting it into 3."},
{sec:"F",type:"order",q:"Order from smallest to largest.",
 items:["1/2","1/8","1/4"],ansOrder:["1/8","1/4","1/2"],
 expl:"With numerator 1, the bigger the bottom number, the smaller the fraction."},
{sec:"F",type:"mc",q:"Which symbol makes this true?  5/6 ◯ 5/8",mono:true,opts:[">","<","="],a:0,
 expl:"Same numerator, and sixths are bigger pieces than eighths: 5/6 > 5/8."},
{lvl:2,sec:"F",type:"mc",q:"Which is greater: 3/8 or 1/2?",mono:true,
 opts:["1/2","3/8","They are equal","Cannot compare"],a:0,
 expl:"1/2 = 4/8, and 4/8 > 3/8."},
{lvl:2,sec:"F",type:"mc",q:"Which symbol makes this true?  2/3 ◯ 3/4",mono:true,opts:["<",">","="],a:0,
 expl:"Using twelfths: 2/3 = 8/12 and 3/4 = 9/12, so 2/3 < 3/4."},
{lvl:3,sec:"F",type:"mc",q:"Order from LARGEST to smallest:  5/6,  2/3,  3/4",mono:true,
 opts:["5/6, 3/4, 2/3","2/3, 3/4, 5/6","3/4, 5/6, 2/3","5/6, 2/3, 3/4"],a:0,
 expl:"As decimals: 5/6 ≈ 0.83, 3/4 = 0.75, 2/3 ≈ 0.67 — so 5/6, 3/4, 2/3."}
],

"g3-timemin": [
{sec:"M",type:"in",q:"A clock shows 4:37. How many minutes until 4:45?",ans:8,expl:"45 − 37 = 8 minutes."},
{sec:"M",type:"in",q:"A movie starts at 2:50 and ends at 3:15. How many minutes long is it?",ans:25,
 hint:"Count to the hour first, then the rest.",
 expl:"2:50 to 3:00 is 10 minutes, then 3:00 to 3:15 is 15 more: 10 + 15 = 25."},
{sec:"M",type:"mc",q:"Which time is 20 minutes after 5:45?",mono:true,
 opts:["6:05","5:65","6:25","5:20"],a:0,expl:"45 + 20 = 65 minutes, which is 1 hour 5 minutes past 5:00: 6:05."},
{sec:"M",type:"in",q:"A train leaves at 9:05 and arrives at 9:48. How many minutes is the trip?",ans:43,
 expl:"48 − 5 = 43 minutes."},
{sec:"M",type:"mc",q:"It is 11:52. What time will it be in 10 minutes?",mono:true,
 opts:["12:02","11:62","12:00","11:42"],a:0,expl:"52 + 10 = 62 minutes, which rolls over to 12:02."},
{lvl:2,sec:"M",type:"in",q:"A recipe takes 55 minutes and starts at 3:20. How many minutes PAST 4:00 does it finish?",
 ans:15,hint:"Work out the finishing time first.",
 expl:"3:20 + 55 minutes = 4:15, which is 15 minutes past 4:00."},
{lvl:2,sec:"M",type:"in",q:"Two classes are 42 minutes and 38 minutes long, back to back with no break. What is the total time, in minutes?",
 ans:80,expl:"42 + 38 = 80 minutes."},
{lvl:3,sec:"M",type:"in",q:"A bus is scheduled for 8:15 but leaves 12 minutes late, then takes 53 minutes to arrive. How many minutes after 8:15 does it arrive?",
 ans:65,expl:"The delay and the trip both add up: 12 + 53 = 65 minutes after 8:15."}
],

"g3-quads": [
{sec:"G",type:"mc",q:"Which shape has exactly 4 sides?",
 opts:["Quadrilateral","Triangle","Pentagon","Hexagon"],a:0,
 expl:"'Quad' means four — a quadrilateral always has 4 sides."},
{sec:"G",type:"mc",q:"A rectangle is ALSO a ___.",
 opts:["quadrilateral","triangle","pentagon","circle"],a:0,
 expl:"Any 4-sided shape, including a rectangle, is a quadrilateral."},
{sec:"G",type:"mc",q:"Which is true of ALL squares?",
 opts:["4 equal sides and 4 right angles","Only 2 equal sides","3 sides","No right angles"],a:0,
 expl:"A square is defined by having 4 equal sides AND 4 right angles."},
{sec:"G",type:"mc",q:"A shape has 4 sides, opposite sides parallel, but no right angles. What could it be?",
 opts:["A rhombus","A square","A triangle","A circle"],a:0,
 expl:"A rhombus has parallel opposite sides and equal sides, but its angles need not be right angles."},
{sec:"G",type:"mc",q:"Which quadrilateral has exactly one pair of parallel sides?",
 opts:["A trapezoid","A square","A rhombus","A rectangle"],a:0,
 expl:"A trapezoid is defined by having just one pair of parallel sides — the others all have two pairs."},
{lvl:2,sec:"G",type:"mc",q:"Every square is a rectangle, but not every rectangle is a square. Why?",
 opts:["A rectangle does not need all 4 sides equal","A rectangle has no right angles","A square has more sides","They are actually the same shape always"],a:0,
 expl:"A rectangle only requires 4 right angles. A square adds the extra requirement that all 4 sides are equal."},
{lvl:2,sec:"G",type:"mc",q:"Which shape can be BOTH a rhombus and a square?",
 opts:["One with 4 equal sides and 4 right angles","One with only 2 equal sides","One with exactly 3 sides","One with 5 sides and no right angles"],a:0,
 expl:"A shape with 4 equal sides is a rhombus; adding 4 right angles makes it a square too."},
{lvl:3,sec:"G",type:"mc",q:"A shape has 4 right angles. Which additional fact would make it a SQUARE rather than just a rectangle?",
 opts:["It also has all 4 sides equal","It also has parallel sides","It also has exactly 4 sides","It is also a quadrilateral"],a:0,
 expl:"Every rectangle already has parallel sides, 4 sides and is a quadrilateral. Equal sides is the extra fact that makes it a square."}
]
};
