/* Grade 3. */
export const G3_BANKS = {
"g3-mult": [
{sec:"N",type:"in",q:"6 × 4 = ?",ans:24,hint:"Six groups of four.",expl:"6 × 4 = 24."},
{sec:"N",type:"in",q:"7 × 8 = ?",ans:56,expl:"7 × 8 = 56."},
{sec:"N",type:"in",q:"9 × 3 = ?",ans:27,expl:"9 × 3 = 27."},
{sec:"N",type:"mc",q:"Which is the same as 5 × 6?",mono:true,opts:["6 × 5","5 + 6","6 + 6","5 × 5"],a:0,
 expl:"Multiplication can be done in either order, so 5 × 6 = 6 × 5 = 30."},
{sec:"N",type:"in",q:"A spider has 8 legs. How many legs do 4 spiders have?",ans:32,
 expl:"4 × 8 = 32 legs."},
{lvl:2,sec:"N",type:"in",q:"8 × 7 = ?",ans:56,hint:"It is the same as 7 × 8.",
 expl:"8 × 7 = 56 — the same product as 7 × 8, just the other way round."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY expression equal to 24.",
 opts:["6 × 4","3 × 8","12 × 2","5 × 5"],aMulti:[0,1,2],
 expl:"6 × 4, 3 × 8 and 12 × 2 all make 24. 5 × 5 is 25."},
{lvl:2,sec:"N",type:"in",q:"What is 4 × 25?",ans:100,hint:"Think of quarters of a hundred.",
 expl:"25 four times is 100 — like four 25p coins making £1."},
{lvl:3,sec:"N",type:"in",q:"A room has 6 rows of 7 chairs. If 5 chairs are removed, how many remain?",
 ans:37,hint:"Find the total first.",expl:"6 × 7 = 42 chairs, minus 5 removed leaves 37."},
{lvl:3,sec:"N",type:"in",q:"What is the 8th number in the pattern 3, 6, 9, 12, ...?",ans:24,
 hint:"It counts up in threes.",expl:"The pattern is multiples of 3, so the 8th is 8 × 3 = 24."}
],

"g3-fracnum": [
{sec:"F",type:"mc",q:"A pizza is cut into 4 equal slices and you eat 1. What fraction did you eat?",
 mono:true,opts:["1/4","1/3","4/1","3/4"],a:0,
 expl:"One slice out of four equal slices is 1/4."},
{sec:"F",type:"mc",q:"Which fraction is the largest?",mono:true,opts:["1/2","1/3","1/4","1/8"],a:0,
 expl:"The more pieces you cut something into, the smaller each piece. Halves are the biggest here."},
{sec:"F",type:"in",q:"How many quarters make one whole?",ans:4,
 expl:"Four quarters make a whole: 1/4 + 1/4 + 1/4 + 1/4 = 1."},
{sec:"F",type:"mc",q:"Which is the same as 2/4?",mono:true,opts:["1/2","1/4","3/4","2/2"],a:0,
 expl:"Two quarters is the same amount as one half."},
{lvl:2,sec:"F",type:"order",q:"Put these fractions in order, smallest first.",
 items:["1/2","1/8","1/3","1/4"],ansOrder:["1/8","1/4","1/3","1/2"],
 expl:"With a numerator of 1, the bigger the bottom number the smaller the fraction."},
{lvl:2,sec:"F",type:"mc",q:"Which fraction is closest to 1 whole?",mono:true,
 opts:["7/8","1/2","3/4","2/3"],a:0,
 expl:"7/8 is only 1/8 short of a whole, closer than the others."},
{lvl:3,sec:"F",type:"in",q:"Three friends share 2 pizzas equally. What fraction of a pizza does each get? Type the bottom number of the fraction.",
 ans:3,hint:"Each pizza is split three ways.",
 expl:"Each pizza splits into thirds, so each friend gets 2/3 of a pizza. The bottom number is 3."}
],

"g3-area": [
{sec:"G",type:"in",q:"A rectangle is 5 squares long and 3 squares wide. What is its area in square units?",ans:15,
 hint:"Count the squares, or multiply.",expl:"Area = 5 × 3 = 15 square units."},
{sec:"G",type:"in",q:"A square has sides of 4 units. What is its area in square units?",ans:16,
 expl:"A square's sides are equal, so area = 4 × 4 = 16 square units."},
{sec:"G",type:"mc",q:"What does area measure?",
 opts:["The space inside a shape","The distance around a shape","The number of corners","The longest side"],a:0,
 expl:"Area is the space inside. The distance around the outside is the perimeter."},
{lvl:2,sec:"G",type:"in",q:"A rectangle has an area of 24 square units and is 6 units long. How wide is it?",
 ans:4,hint:"What times 6 makes 24?",expl:"6 × 4 = 24, so the width is 4 units."},
{lvl:2,sec:"G",type:"in",q:"An L-shape is made from a 3 by 2 rectangle joined to a 2 by 2 square. What is the total area in square units?",
 ans:10,hint:"Work out each piece, then add.",
 expl:"The rectangle is 3 × 2 = 6 and the square is 2 × 2 = 4. Together 6 + 4 = 10 square units."},
{lvl:3,sec:"G",type:"in",q:"A rectangle has an area of 36 square units and a perimeter of 26 units. What is its longer side?",
 ans:9,hint:"Which pair multiplies to 36 and adds to 13?",
 expl:"Half the perimeter is 13, so the sides add to 13 and multiply to 36. That is 9 and 4, so the longer side is 9."}
],

"g3-div": [
{sec:"N",type:"in",q:"24 ÷ 6 = ?",ans:4,expl:"24 ÷ 6 = 4."},
{sec:"N",type:"in",q:"35 ÷ 5 = ?",ans:7,expl:"35 ÷ 5 = 7."},
{sec:"N",type:"mc",q:"Which division matches: 'sharing 18 stickers equally among 3 friends'?",mono:true,
 opts:["18 ÷ 3","3 ÷ 18","18 × 3","18 − 3"],a:0,
 expl:"Sharing equally among 3 means dividing by 3: 18 ÷ 3 = 6 stickers each."},
{sec:"N",type:"in",q:"42 ÷ 7 = ?",ans:6,expl:"42 ÷ 7 = 6."},
{sec:"N",type:"in",q:"A box has 48 pencils split evenly into 6 packs. How many pencils per pack?",ans:8,
 expl:"48 ÷ 6 = 8 pencils per pack."},
{lvl:2,sec:"N",type:"in",q:"56 ÷ 8 = ?",ans:7,expl:"56 ÷ 8 = 7."},
{lvl:2,sec:"N",type:"mc",q:"Which multiplication fact matches 45 ÷ 9 = 5?",mono:true,
 opts:["9 × 5 = 45","45 × 9 = 405","9 − 5 = 4","45 + 9 = 54"],a:0,
 expl:"Division undoes multiplication: 45 ÷ 9 = 5 because 9 × 5 = 45."},
{lvl:3,sec:"N",type:"in",q:"A number divided by 6 gives 9 with none left over. What is the number?",ans:54,
 hint:"Multiply to undo the division.",expl:"9 × 6 = 54."}
],

"g3-round": [
{sec:"N",type:"in",q:"Round 47 to the nearest ten.",ans:50,expl:"47 is closer to 50 than to 40."},
{sec:"N",type:"in",q:"Round 82 to the nearest ten.",ans:80,expl:"82 is closer to 80 than to 90."},
{sec:"N",type:"in",q:"Round 350 to the nearest hundred.",ans:400,
 hint:"350 is exactly halfway — round up.",expl:"Halfway points round up, so 350 rounds to 400."},
{sec:"N",type:"mc",q:"Round 125 to the nearest ten.",opts:["130","120","100","200"],a:0,
 expl:"125 is halfway between 120 and 130, and halfway points round up: 130."},
{sec:"N",type:"in",q:"Round 999 to the nearest hundred.",ans:1000,
 expl:"999 is only 1 away from 1000, so it rounds up to 1000."},
{lvl:2,sec:"N",type:"in",q:"A number rounds to 400 when rounded to the nearest hundred. What is the SMALLEST whole number it could be?",
 ans:350,hint:"Halfway points round up.",expl:"350 is the smallest number that rounds up to 400."},
{lvl:2,sec:"N",type:"in",q:"Round 3,462 to the nearest hundred.",ans:3500,
 expl:"The tens digit is 6, which rounds up: 3,462 rounds to 3,500."},
{lvl:3,sec:"N",type:"mc",q:"Which number rounds to 60 (nearest ten) AND to 100 (nearest hundred)?",mono:true,
 opts:["64","52","65","46"],a:0,
 expl:"64 rounds to 60 (nearest ten) and to 100 (nearest hundred, since it is closer to 100 than to 0). The others fail one test or the other."}
],

"g3-fraccomp": [
{sec:"F",type:"mc",q:"Which is greater: 3/4 or 1/4?",mono:true,
 opts:["3/4","1/4","They are equal","Cannot compare"],a:0,
 expl:"With the same denominator, more pieces means a greater fraction: 3/4 > 1/4."},
{sec:"F",type:"mc",q:"Which symbol makes this true?  2/3 ◯ 2/5",mono:true,opts:[">","<","="],a:0,
 expl:"Same numerator, so fewer pieces (thirds) means each piece is bigger: 2/3 > 2/5."},
{sec:"F",type:"mc",q:"Which is smaller: 1/6 or 1/3?",mono:true,
 opts:["1/6","1/3","They are equal","Cannot compare"],a:0,
 expl:"Cutting something into 6 pieces makes each piece smaller than cutting it into 3."},
{sec:"F",type:"order",q:"Order from smallest to largest.",
 items:["1/2","1/8","1/4"],ansOrder:["1/8","1/4","1/2"],
 expl:"With numerator 1, the bigger the bottom number, the smaller the fraction."},
{sec:"F",type:"mc",q:"Which symbol makes this true?  5/6 ◯ 5/8",mono:true,opts:[">","<","="],a:0,
 expl:"Same numerator, and sixths are bigger pieces than eighths: 5/6 > 5/8."},
{lvl:2,sec:"F",type:"mc",q:"Which is greater: 3/8 or 1/2?",mono:true,
 opts:["1/2","3/8","They are equal","Cannot compare"],a:0,
 expl:"1/2 = 4/8, and 4/8 > 3/8."},
{lvl:2,sec:"F",type:"mc",q:"Which symbol makes this true?  2/3 ◯ 3/4",mono:true,opts:["<",">","="],a:0,
 expl:"Using twelfths: 2/3 = 8/12 and 3/4 = 9/12, so 2/3 < 3/4."},
{lvl:3,sec:"F",type:"mc",q:"Order from LARGEST to smallest:  5/6,  2/3,  3/4",mono:true,
 opts:["5/6, 3/4, 2/3","2/3, 3/4, 5/6","3/4, 5/6, 2/3","5/6, 2/3, 3/4"],a:0,
 expl:"As decimals: 5/6 ≈ 0.83, 3/4 = 0.75, 2/3 ≈ 0.67 — so 5/6, 3/4, 2/3."}
],

"g3-timemin": [
{sec:"M",type:"in",q:"A clock shows 4:37. How many minutes until 4:45?",ans:8,expl:"45 − 37 = 8 minutes."},
{sec:"M",type:"in",q:"A movie starts at 2:50 and ends at 3:15. How many minutes long is it?",ans:25,
 hint:"Count to the hour first, then the rest.",
 expl:"2:50 to 3:00 is 10 minutes, then 3:00 to 3:15 is 15 more: 10 + 15 = 25."},
{sec:"M",type:"mc",q:"Which time is 20 minutes after 5:45?",mono:true,
 opts:["6:05","5:65","6:25","5:20"],a:0,expl:"45 + 20 = 65 minutes, which is 1 hour 5 minutes past 5:00: 6:05."},
{sec:"M",type:"in",q:"A train leaves at 9:05 and arrives at 9:48. How many minutes is the trip?",ans:43,
 expl:"48 − 5 = 43 minutes."},
{sec:"M",type:"mc",q:"It is 11:52. What time will it be in 10 minutes?",mono:true,
 opts:["12:02","11:62","12:00","11:42"],a:0,expl:"52 + 10 = 62 minutes, which rolls over to 12:02."},
{lvl:2,sec:"M",type:"in",q:"A recipe takes 55 minutes and starts at 3:20. How many minutes PAST 4:00 does it finish?",
 ans:15,hint:"Work out the finishing time first.",
 expl:"3:20 + 55 minutes = 4:15, which is 15 minutes past 4:00."},
{lvl:2,sec:"M",type:"in",q:"Two classes are 42 minutes and 38 minutes long, back to back with no break. What is the total time, in minutes?",
 ans:80,expl:"42 + 38 = 80 minutes."},
{lvl:3,sec:"M",type:"in",q:"A bus is scheduled for 8:15 but leaves 12 minutes late, then takes 53 minutes to arrive. How many minutes after 8:15 does it arrive?",
 ans:65,expl:"The delay and the trip both add up: 12 + 53 = 65 minutes after 8:15."}
],

"g3-quads": [
{sec:"G",type:"mc",q:"Which shape has exactly 4 sides?",
 opts:["Quadrilateral","Triangle","Pentagon","Hexagon"],a:0,
 expl:"'Quad' means four — a quadrilateral always has 4 sides."},
{sec:"G",type:"mc",q:"A rectangle is ALSO a ___.",
 opts:["quadrilateral","triangle","pentagon","circle"],a:0,
 expl:"Any 4-sided shape, including a rectangle, is a quadrilateral."},
{sec:"G",type:"mc",q:"Which is true of ALL squares?",
 opts:["4 equal sides and 4 right angles","Only 2 equal sides","3 sides","No right angles"],a:0,
 expl:"A square is defined by having 4 equal sides AND 4 right angles."},
{sec:"G",type:"mc",q:"A shape has 4 sides, opposite sides parallel, but no right angles. What could it be?",
 opts:["A rhombus","A square","A triangle","A circle"],a:0,
 expl:"A rhombus has parallel opposite sides and equal sides, but its angles need not be right angles."},
{sec:"G",type:"mc",q:"Which quadrilateral has exactly one pair of parallel sides?",
 opts:["A trapezoid","A square","A rhombus","A rectangle"],a:0,
 expl:"A trapezoid is defined by having just one pair of parallel sides — the others all have two pairs."},
{lvl:2,sec:"G",type:"mc",q:"Every square is a rectangle, but not every rectangle is a square. Why?",
 opts:["A rectangle does not need all 4 sides equal","A rectangle has no right angles","A square has more sides","They are actually the same shape always"],a:0,
 expl:"A rectangle only requires 4 right angles. A square adds the extra requirement that all 4 sides are equal."},
{lvl:2,sec:"G",type:"mc",q:"Which shape can be BOTH a rhombus and a square?",
 opts:["One with 4 equal sides and 4 right angles","One with only 2 equal sides","One with exactly 3 sides","One with 5 sides and no right angles"],a:0,
 expl:"A shape with 4 equal sides is a rhombus; adding 4 right angles makes it a square too."},
{lvl:3,sec:"G",type:"mc",q:"A shape has 4 right angles. Which additional fact would make it a SQUARE rather than just a rectangle?",
 opts:["It also has all 4 sides equal","It also has parallel sides","It also has exactly 4 sides","It is also a quadrilateral"],a:0,
 expl:"Every rectangle already has parallel sides, 4 sides and is a quadrilateral. Equal sides is the extra fact that makes it a square."}
],

"g3-multprops": [
{sec:"N",type:"mc",q:"Which shows the COMMUTATIVE property?",mono:true,
 opts:["4 × 5 = 5 × 4","4 × (5 × 2) = (4 × 5) × 2","4 × 1 = 4","4 × 0 = 0"],a:0,
 expl:"Commutative means the ORDER of the factors can swap without changing the product."},
{sec:"N",type:"mc",q:"Which shows the ASSOCIATIVE property?",mono:true,
 opts:["(2 × 3) × 4 = 2 × (3 × 4)","2 × 3 = 3 × 2","2 × 1 = 2","2 × 0 = 0"],a:0,
 expl:"Associative means how the factors are GROUPED can change without changing the product."},
{sec:"N",type:"in",q:"Using the commutative property, if 6 × 7 = 42, what is 7 × 6?",ans:42,
 expl:"Swapping the order of the factors never changes the product."},
{sec:"N",type:"mc",q:"Which shows the DISTRIBUTIVE property applied to 6 × 12?",mono:true,
 opts:["6 × (10 + 2) = 6×10 + 6×2","6 × 12 = 12 × 6","6 × 1 = 6","(6×3)×4 = 6×(3×4)"],a:0,
 expl:"The distributive property breaks one factor into parts and multiplies each part separately."},
{sec:"N",type:"in",q:"What is 5 × 1?",ans:5,expl:"Any number times 1 stays the same: 5 × 1 = 5."},
{lvl:2,sec:"N",type:"in",q:"Using the distributive property, 7 × 12 = 7×10 + 7×2. What is 7×10 + 7×2?",
 ans:84,expl:"70 + 14 = 84."},
{lvl:2,sec:"N",type:"mc",q:"Which expression equals 8 × 6 by regrouping the factors differently?",mono:true,
 opts:["(8 × 2) × 3","8 × 6 + 1","8 + 6","6 × 8 × 0"],a:0,
 expl:"(8 × 2) × 3 = 16 × 3 = 48, the same as 8 × 6 = 48 — just grouped differently."},
{lvl:3,sec:"N",type:"in",q:"Using the distributive property, break 9 × 14 into 9×10 + 9×4, then find the total.",
 ans:126,expl:"90 + 36 = 126."}
],

"g3-twostep": [
{sec:"W",type:"in",q:"Maria buys 3 packs of 4 pencils, then gives away 5 pencils. How many does she have left?",
 ans:7,expl:"3 × 4 = 12 pencils, and 12 − 5 = 7 left."},
{sec:"W",type:"in",q:"A store has 6 shelves with 8 books each. 10 books are sold. How many books remain?",
 ans:38,expl:"6 × 8 = 48 books, and 48 − 10 = 38 remain."},
{sec:"W",type:"mc",q:"Which matches: 'Buy 5 bags of 6 marbles, then lose 7 marbles'?",mono:true,
 opts:["5 × 6 − 7","5 × 6 + 7","5 + 6 − 7","5 − 6 × 7"],a:0,
 expl:"Find the total marbles first (5 × 6), then subtract the 7 lost."},
{sec:"W",type:"in",q:"A farmer has 4 rows of 9 plants. 6 plants die. How many plants are left?",
 ans:30,expl:"4 × 9 = 36 plants, and 36 − 6 = 30 left."},
{sec:"W",type:"in",q:"A class of 24 students is split into 4 equal groups. Then 2 students join one group. How many are in that group NOW?",
 ans:8,expl:"24 ÷ 4 = 6 per group, and 6 + 2 = 8."},
{lvl:2,sec:"W",type:"in",q:"A baker makes 7 trays of 12 muffins. He sells 50 muffins. How many are left?",
 ans:34,expl:"7 × 12 = 84 muffins, and 84 − 50 = 34 left."},
{lvl:2,sec:"W",type:"in",q:"3 boxes of 15 crayons are combined with 2 more boxes of 15. How many crayons total?",
 ans:75,expl:"3 + 2 = 5 boxes, and 5 × 15 = 75 crayons."},
{lvl:3,sec:"W",type:"in",q:"A theater has 8 rows of 20 seats. 45 tickets are sold, then 60 more. How many empty seats remain?",
 ans:55,hint:"Find the total seats and the total sold.",
 expl:"8 × 20 = 160 seats. Sold: 45 + 60 = 105. Empty: 160 − 105 = 55."}
],

"g3-patterns": [
{sec:"N",type:"in",q:"What is the next number in the pattern: 5, 10, 15, 20, ___?",ans:25,
 expl:"The rule is 'add 5', so the next number is 20 + 5 = 25."},
{sec:"N",type:"in",q:"What is the next number in the pattern: 2, 4, 8, 16, ___?",ans:32,
 expl:"The rule is 'double it', so the next number is 16 × 2 = 32."},
{sec:"N",type:"mc",q:"What is the RULE for the pattern 3, 6, 9, 12?",
 opts:["Add 3","Add 2","Multiply by 2","Subtract 3"],a:0,
 expl:"Each number is 3 more than the one before it."},
{sec:"N",type:"in",q:"What is the 6th number in the pattern 4, 8, 12, 16, ...?",ans:24,
 expl:"The rule is 'add 4' each time: 4, 8, 12, 16, 20, 24 — the 6th number is 24."},
{sec:"N",type:"mc",q:"Which pattern follows the rule 'subtract 5'?",mono:true,
 opts:["30, 25, 20, 15","5, 10, 15, 20","2, 4, 8, 16","1, 2, 3, 4"],a:0,
 expl:"Each number in 30, 25, 20, 15 is 5 less than the one before."},
{lvl:2,sec:"N",type:"in",q:"A pattern starts at 3 and the rule is 'add 4'. What is the 5th number?",
 ans:19,hint:"List them out: 3, 7, 11, 15, 19.",expl:"3, 7, 11, 15, 19 — the 5th number is 19."},
{lvl:2,sec:"N",type:"mc",q:"A pattern is 1, 4, 9, 16, ___. What comes next?",mono:true,
 opts:["25","20","18","23"],a:0,expl:"These are square numbers (1×1, 2×2, 3×3, 4×4), so next is 5×5 = 25."},
{lvl:3,sec:"N",type:"in",q:"A pattern follows 'multiply by 2, then subtract 1', starting at 3: 3, 5, 9, 17, ___. What is next?",
 ans:33,expl:"17 × 2 = 34, then 34 − 1 = 33."}
],

"g3-add1000": [
{sec:"N",type:"in",q:"456 + 328 = ?",ans:784,expl:"456 + 328 = 784."},
{sec:"N",type:"in",q:"702 − 385 = ?",ans:317,expl:"702 − 385 = 317."},
{sec:"N",type:"in",q:"234 + 567 = ?",ans:801,expl:"234 + 567 = 801."},
{sec:"N",type:"mc",q:"What is 890 − 456?",opts:["434","444","424","440"],a:0,expl:"890 − 456 = 434."},
{sec:"N",type:"in",q:"125 + 275 = ?",ans:400,expl:"125 + 275 = 400."},
{lvl:2,sec:"N",type:"in",q:"A school has 615 students. 89 more enroll. How many students now?",
 ans:704,expl:"615 + 89 = 704."},
{lvl:2,sec:"N",type:"in",q:"A warehouse had 950 boxes. 378 were shipped out. How many remain?",
 ans:572,expl:"950 − 378 = 572."},
{lvl:3,sec:"N",type:"in",q:"Two numbers add to 800. One is 250 more than the other. What is the SMALLER number?",
 ans:275,hint:"If the smaller is x, the larger is x + 250.",
 expl:"x + (x + 250) = 800, so 2x = 550 and x = 275."}
],

"g3-mult10": [
{sec:"N",type:"in",q:"4 × 20 = ?",ans:80,expl:"4 × 20 = 80."},
{sec:"N",type:"in",q:"7 × 30 = ?",ans:210,expl:"7 × 30 = 210."},
{sec:"N",type:"in",q:"6 × 50 = ?",ans:300,expl:"6 × 50 = 300."},
{sec:"N",type:"mc",q:"What is 8 × 40?",opts:["320","300","340","280"],a:0,expl:"8 × 40 = 320."},
{sec:"N",type:"in",q:"9 × 20 = ?",ans:180,expl:"9 × 20 = 180."},
{lvl:2,sec:"N",type:"in",q:"A theater has 30 rows with 8 seats each. How many seats total?",
 ans:240,expl:"30 × 8 = 240 seats."},
{lvl:2,sec:"N",type:"in",q:"12 × 30 = ?",ans:360,expl:"12 × 30 = 360."},
{lvl:3,sec:"N",type:"in",q:"A number times 20 equals 540. What is the number?",ans:27,
 hint:"Divide to undo the multiplication.",expl:"540 ÷ 20 = 27."}
],

"g3-fraceq": [
{sec:"F",type:"mc",q:"Which fraction is EQUIVALENT to 1/2?",mono:true,opts:["2/4","1/4","3/8","1/3"],a:0,
 expl:"2/4 simplifies to 1/2 — same amount, different-sized pieces."},
{sec:"F",type:"mc",q:"Which fraction is EQUIVALENT to 2/3?",mono:true,opts:["4/6","3/4","2/4","1/3"],a:0,
 expl:"4/6 simplifies to 2/3."},
{sec:"F",type:"in",q:"1/2 = __/6. What number goes in the blank?",ans:3,
 expl:"To turn halves into sixths, multiply both parts by 3: 1×3 = 3."},
{sec:"F",type:"mc",q:"Which fraction is NOT equivalent to 3/4?",mono:true,
 opts:["4/5","6/8","9/12","12/16"],a:0,
 expl:"6/8, 9/12 and 12/16 all simplify to 3/4. 4/5 does not."},
{sec:"F",type:"in",q:"2/5 = __/10. What number goes in the blank?",ans:4,
 expl:"Multiply both parts by 2: 2×2 = 4."},
{lvl:2,sec:"F",type:"in",q:"3/4 = 9/__. What number goes in the blank?",ans:12,
 expl:"3 was multiplied by 3 to get 9, so 4 must also be multiplied by 3: 4×3 = 12."},
{lvl:2,sec:"F",type:"mc",q:"Which pair of fractions is equivalent?",mono:true,
 opts:["4/6 and 2/3","4/6 and 1/2","4/6 and 3/4","4/6 and 5/6"],a:0,
 expl:"4/6 simplifies to 2/3 — they are the same amount."},
{lvl:3,sec:"F",type:"in",q:"Two fractions a/6 and 2/3 are equivalent. What is a?",ans:4,
 expl:"2/3 = 4/6 (multiply both parts by 2), so a = 4."}
],

"g3-wholefrac": [
{sec:"F",type:"mc",q:"Which fraction equals the whole number 3?",mono:true,opts:["3/1","1/3","3/3","1/1"],a:0,
 expl:"Any whole number n equals n/1."},
{sec:"F",type:"in",q:"How many fourths make the whole number 2? (2 = __/4)",ans:8,
 expl:"2 wholes is 8 fourths: 2 = 8/4."},
{sec:"F",type:"mc",q:"Which fraction equals 5?",mono:true,opts:["5/1","1/5","5/5","2/5"],a:0,
 expl:"5/1 = 5, since dividing by 1 does not change the value."},
{sec:"F",type:"in",q:"6 = __/3. What number goes in the blank?",ans:18,
 expl:"6 wholes is 18 thirds: 6 = 18/3."},
{sec:"F",type:"mc",q:"Which is the SAME as the whole number 1?",mono:true,
 opts:["4/4","1/4","2/4","3/4"],a:0,expl:"Any fraction with the same numerator and denominator equals 1: 4/4 = 1."},
{lvl:2,sec:"F",type:"in",q:"4 = __/2. What number goes in the blank?",ans:8,
 expl:"4 wholes is 8 halves: 4 = 8/2."},
{lvl:2,sec:"F",type:"mc",q:"Which fraction is the SAME as 7?",mono:true,opts:["7/1","1/7","7/7","14/7"],a:0,
 expl:"7/1 = 7. (14/7 = 2, not 7.)"},
{lvl:3,sec:"F",type:"in",q:"A whole number n equals 24/8. What is n?",ans:3,expl:"24 ÷ 8 = 3."}
],

"g3-perimeter": [
{sec:"G",type:"in",q:"A rectangle is 6 units long and 3 units wide. What is its perimeter?",
 ans:18,expl:"Perimeter = 2 × (6 + 3) = 2 × 9 = 18."},
{sec:"G",type:"in",q:"A square has sides of 5 units. What is its perimeter?",ans:20,
 expl:"A square has 4 equal sides: 4 × 5 = 20."},
{sec:"G",type:"mc",q:"Which formula finds the perimeter of a square?",mono:true,
 opts:["4 × side","side × side","2 × side","side + side"],a:0,
 expl:"A square has 4 equal sides, so its perimeter is 4 times one side's length."},
{sec:"G",type:"in",q:"A rectangle has a perimeter of 24 units and a length of 8 units. What is its width?",
 ans:4,hint:"Half the perimeter is the sum of one length and one width.",
 expl:"24 ÷ 2 = 12, and 12 − 8 = 4."},
{sec:"G",type:"in",q:"A triangle has sides 4, 5 and 6 units. What is its perimeter?",ans:15,
 expl:"4 + 5 + 6 = 15."},
{lvl:2,sec:"G",type:"in",q:"A rectangular garden is 12 m long and has a perimeter of 34 m. What is its width?",
 ans:5,expl:"34 ÷ 2 = 17, and 17 − 12 = 5."},
{lvl:2,sec:"G",type:"in",q:"A regular pentagon (5 equal sides) has a perimeter of 35 units. What is the length of one side?",
 ans:7,expl:"35 ÷ 5 = 7."},
{lvl:3,sec:"G",type:"in",q:"Two rectangles share the same perimeter of 20 units. One is 6 by 4. The other has a width of 2. What is its length?",
 ans:8,hint:"Half the perimeter is length plus width.",
 expl:"20 ÷ 2 = 10, and 10 − 2 = 8."}
],

"g3-volmass": [
{sec:"M",type:"mc",q:"Which unit measures LIQUID VOLUME?",opts:["Liters","Grams","Meters","Degrees"],a:0,
 expl:"Liters measure how much liquid something holds."},
{sec:"M",type:"mc",q:"Which unit measures MASS (weight)?",opts:["Grams","Liters","Meters","Seconds"],a:0,
 expl:"Grams measure how heavy something is."},
{sec:"M",type:"in",q:"A bottle holds 2 liters. Another holds 3 liters. How many liters together?",ans:5,
 expl:"2 + 3 = 5 liters."},
{sec:"M",type:"in",q:"A bag of rice weighs 5 kilograms. Another weighs 3 kilograms. How many kilograms together?",
 ans:8,expl:"5 + 3 = 8 kilograms."},
{sec:"M",type:"mc",q:"Which tool measures how much liquid is in a container?",
 opts:["A measuring cup","A scale","A ruler","A thermometer"],a:0,expl:"A measuring cup is marked to show liquid volume."},
{lvl:2,sec:"M",type:"in",q:"A recipe uses 250 mL of milk per batch. How many mL for 3 batches?",ans:750,
 expl:"250 × 3 = 750 mL."},
{lvl:2,sec:"M",type:"in",q:"A crate holds 12 kilograms of apples. If 4 kilograms are removed, how many remain?",
 ans:8,expl:"12 − 4 = 8 kilograms."},
{lvl:3,sec:"M",type:"in",q:"A container holds 4 liters. It is filled from a jug that pours 500 mL at a time. How many pours does it take to fill it?",
 ans:8,hint:"Convert 4 liters to milliliters first.",expl:"4 liters = 4000 mL, and 4000 ÷ 500 = 8 pours."}
],

"g3-scaled": [
{sec:"M",type:"in",q:"A scaled bar graph shows each square = 2 books. A bar has 5 squares. How many books?",
 ans:10,expl:"5 × 2 = 10 books."},
{sec:"M",type:"in",q:"Using the same scale (1 square = 2 books), how many squares would show 14 books?",
 ans:7,expl:"14 ÷ 2 = 7 squares."},
{sec:"M",type:"mc",q:"On a scaled picture graph, each icon = 5 people, and there are 3 icons. How many people?",
 opts:["15","8","3","5"],a:0,expl:"3 × 5 = 15 people."},
{sec:"M",type:"in",q:"A graph's scale is 1 unit = 10 people. A bar reaches 6 units. How many people?",
 ans:60,expl:"6 × 10 = 60 people."},
{sec:"M",type:"mc",q:"Why do graphs use a SCALE instead of showing every single item?",
 opts:["To fit large numbers into a manageable graph","To make the graph confusing","Scales are required by law","There is no reason"],a:0,
 expl:"A scale lets one square or icon stand for several items, so big totals still fit on the page."},
{lvl:2,sec:"M",type:"in",q:"A graph's scale is 1 square = 4 items. Category A has 3 squares, Category B has 5 squares. How many MORE items does B have?",
 ans:8,expl:"B has 2 more squares than A, and 2 × 4 = 8 more items."},
{lvl:2,sec:"M",type:"in",q:"Using scale 1 square = 3 items, how many squares would represent 21 items?",ans:7,
 expl:"21 ÷ 3 = 7 squares."},
{lvl:3,sec:"M",type:"in",q:"A graph uses scale 1 square = 6 items. Two EQUAL categories together use 8 squares and represent 48 items total. How many squares does EACH category use?",
 ans:4,expl:"8 squares split evenly between 2 equal categories: 8 ÷ 2 = 4 squares each."}
],

"g3-equalarea": [
{sec:"F",type:"mc",q:"A rectangle is divided into 4 equal parts. Each part is what fraction of the whole?",
 opts:["1/4","1/2","1/3","4/4"],a:0,expl:"4 equal parts means each part is 1/4 of the whole."},
{sec:"F",type:"mc",q:"A shape is divided into 3 equal areas. Each part represents ___.",
 opts:["1/3 of the area","3/1 of the area","the whole area","half the area"],a:0,
 expl:"3 equal parts means each one is 1/3 of the total area."},
{sec:"F",type:"mc",q:"Two SAME-SIZE rectangles are cut differently: one into 2 equal parts, the other into 4 equal parts. Which single part is BIGGER?",
 opts:["A part from the 2-part rectangle","A part from the 4-part rectangle","They are equal","Cannot tell"],a:0,
 expl:"Fewer equal parts from the same whole always means each part is bigger."},
{sec:"F",type:"in",q:"A rectangle is split into 6 equal-area parts. What is the denominator of the fraction each part represents?",
 ans:6,expl:"Each of the 6 equal parts is 1/6 of the whole, so the denominator is 6."},
{sec:"F",type:"mc",q:"A square is divided into 4 equal-area triangles from its center. Each triangle is what fraction of the square?",
 opts:["1/4","1/2","1/3","4/1"],a:0,expl:"4 equal triangles means each is 1/4 of the square, regardless of their shape."},
{lvl:2,sec:"F",type:"mc",q:"A rectangle is split into 8 equal-area parts, even though the pieces look different shapes. Each part equals ___.",
 opts:["1/8 of the total area","1/2 of the total area","8 times the area","Cannot be determined"],a:0,
 expl:"Equal AREA is what matters for the fraction, even if the pieces are shaped differently."},
{lvl:2,sec:"F",type:"in",q:"A shape's area is 24 square units, split into 4 equal-area parts. What is the area of EACH part?",
 ans:6,expl:"24 ÷ 4 = 6 square units each."},
{lvl:3,sec:"F",type:"in",q:"A rectangle is divided unevenly into 3 parts by area: 1/6, 1/3, and the rest. What is the THIRD part's numerator (denominator 6)?",
 ans:3,hint:"Convert 1/3 to sixths, then see what's left of the whole.",
 expl:"1/6 + 2/6 = 3/6 used, so 6/6 − 3/6 = 3/6 remains — a numerator of 3."}
],

"g3-areaperim": [
{sec:"G",type:"mc",q:"A rectangle has the SAME perimeter as another, but they can still have ___.",
 opts:["different areas","the same shape always","the same area always","no relationship"],a:0,
 expl:"Perimeter and area measure different things — matching one does not force the other to match."},
{sec:"G",type:"in",q:"Rectangle A is 6 by 2 (perimeter 16). Rectangle B is 4 by 4 (perimeter 16 too). What is Rectangle B's area?",
 ans:16,expl:"4 × 4 = 16."},
{sec:"G",type:"mc",q:"Which statement is TRUE?",
 opts:["Two shapes can have the same perimeter but different areas","Same perimeter always means same area","Same area always means same perimeter","Perimeter and area are the same thing"],a:0,
 expl:"A 6×2 rectangle and a 4×4 rectangle both have perimeter 16, but areas 12 and 16 — proof that perimeter alone doesn't fix area."},
{sec:"G",type:"in",q:"A rectangle has area 20 and one side of 4. What is its perimeter?",
 ans:18,hint:"Find the other side first: 20 ÷ 4.",expl:"The other side is 20 ÷ 4 = 5. Perimeter = 2 × (4 + 5) = 18."},
{sec:"G",type:"mc",q:"You stretch a rectangle to be longer and thinner while keeping the SAME area. What usually happens to the perimeter?",
 opts:["It usually increases","It always stays the same","The area also changes","Nothing changes"],a:0,
 expl:"A longer, thinner rectangle with the same area typically has more perimeter than a squarer one."},
{lvl:2,sec:"G",type:"in",q:"A square and a rectangle both have area 36. The square has side 6 (perimeter 24). The rectangle is 9 by 4. Type the LARGER of the two perimeters.",
 ans:26,expl:"The square's perimeter is 24. The rectangle's is 2 × (9 + 4) = 26, which is larger."},
{lvl:2,sec:"G",type:"in",q:"A rectangle has perimeter 20 and length 7. What is its area?",
 ans:21,hint:"Find the width first.",expl:"Width = 10 − 7 = 3. Area = 7 × 3 = 21."},
{lvl:3,sec:"G",type:"in",q:"Two rectangles both have area 24. One is 6 by 4 (perimeter 20). The other is 8 by 3 (perimeter 22). What is the DIFFERENCE in their perimeters?",
 ans:2,expl:"22 − 20 = 2."}
]
};
