/* Grade 4 advanced / enrichment: number theory, pre-algebra, combinatorics,
   extended geometry and probability. Competition-style (AMC 8 / Kangaroo)
   content with grade-4 wording. */
export const G4_ADV_BANKS = {
"g4-primefact": [
{sec:"T",type:"in",q:"What is the exponent of 2 in the prime factorisation of 24?",ans:3,
 hint:"Keep dividing by 2 until you cannot.",expl:"24 = 2 × 2 × 2 × 3 = 2³ × 3, so the exponent of 2 is 3."},
{sec:"T",type:"mc",q:"Which is the prime factorisation of 36?",mono:true,opts:["2² × 3²","4 × 9","2 × 18","2³ × 3"],a:0,
 expl:"36 = 4 × 9 = 2 × 2 × 3 × 3 = 2² × 3². The other products use numbers that are not prime, or give the wrong value."},
{sec:"T",type:"in",q:"What number is 2³ × 5?",ans:40,hint:"Work out the power first.",expl:"2³ = 8, and 8 × 5 = 40."},
{sec:"T",type:"in",q:"72 can be written as 2ᵃ × 3ᵇ. What is a + b?",ans:5,hint:"72 = 8 × 9.",
 expl:"72 = 8 × 9 = 2³ × 3², so a = 3 and b = 2, giving a + b = 5."},
{lvl:2,sec:"T",type:"in",q:"What is the largest prime factor of 210?",ans:7,hint:"Divide out the small primes first.",
 expl:"210 = 2 × 105 = 2 × 3 × 35 = 2 × 3 × 5 × 7. The largest prime factor is 7."},
{lvl:2,sec:"T",type:"mc",q:"Which number has the prime factorisation 2² × 3 × 5?",opts:["60","30","120","90"],a:0,
 expl:"2² × 3 × 5 = 4 × 3 × 5 = 60."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number whose prime factorisation uses exactly two different primes.",
 opts:["12","30","49","18","7"],aMulti:[0,3],
 expl:"12 = 2² × 3 and 18 = 2 × 3² each use two primes. 30 = 2 × 3 × 5 uses three, 49 = 7² uses one, and 7 is itself prime."},
{lvl:3,sec:"T",type:"in",q:"A number equals 2⁴ × 3². How many factors does it have in total?",ans:15,
 hint:"Each factor is 2 to some power (0 to 4) times 3 to some power (0 to 2).",
 expl:"Choose the power of 2 in 5 ways (0 to 4) and the power of 3 in 3 ways (0 to 2): 5 × 3 = 15 factors."},
{lvl:3,sec:"T",type:"in",q:"What is the smallest whole number n greater than 0 such that 12 × n is a square number?",ans:3,
 hint:"In a square number every prime has an even exponent.",
 expl:"12 = 2² × 3. The 3 needs a partner to make its exponent even, so n = 3 gives 36 = 6²."},
{lvl:3,sec:"T",type:"in",q:"How many factors does 360 have?",ans:24,hint:"Factorise first: 360 = 2³ × 3² × 5.",
 expl:"360 = 2³ × 3² × 5. Add 1 to each exponent and multiply: 4 × 3 × 2 = 24 factors."}
],

"g4-divrules": [
{sec:"T",type:"mc",q:"Which number is divisible by 3?",opts:["741","742","743","745"],a:0,
 hint:"Add the digits.",expl:"7 + 4 + 1 = 12, which is a multiple of 3, so 741 is divisible by 3. The others have digit sums 13, 14 and 16."},
{sec:"T",type:"mc",q:"A number is divisible by 4 when ...",
 opts:["its last two digits form a number divisible by 4","its last digit is 4","its digit sum is divisible by 4","it ends in an even digit"],a:0,
 expl:"Because 100 is a multiple of 4, only the last two digits matter. For example 1,316 ends in 16, so it is divisible by 4."},
{sec:"T",type:"in",q:"Which digit must fill the blank so that 52_ is divisible by 9? Type the digit.",ans:2,
 hint:"The digit sum must be a multiple of 9.",expl:"5 + 2 = 7, and 7 + 2 = 9, so the missing digit is 2 (522 = 9 × 58)."},
{sec:"T",type:"mc",q:"Which number is divisible by 6?",opts:["234","235","244","225"],a:0,
 hint:"It must pass the tests for both 2 and 3.",
 expl:"234 is even and 2 + 3 + 4 = 9 is a multiple of 3, so 234 is divisible by 6. 235 and 225 are odd; 244 has digit sum 10."},
{lvl:2,sec:"T",type:"in",q:"Which digit d makes the three-digit number 5d8 divisible by 11? Type the digit.",ans:2,
 hint:"For 11, alternately add and subtract the digits.",
 expl:"5 − d + 8 = 13 − d must be a multiple of 11, so d = 2. Check: 528 = 11 × 48."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number that divides 1,236 exactly.",opts:["3","4","6","9","8"],aMulti:[0,1,2],
 expl:"Digit sum 12 gives 3 (but not 9). Last two digits 36 give 4. Even and divisible by 3 gives 6. Last three digits 236 are not divisible by 8."},
{lvl:2,sec:"T",type:"in",q:"How many whole numbers from 1 to 100 are divisible by both 4 and 6?",ans:8,
 hint:"Find the smallest number divisible by both.",
 expl:"A number divisible by 4 and 6 is a multiple of 12. The multiples of 12 up to 100 are 12, 24, ..., 96: that is 8 numbers."},
{lvl:3,sec:"T",type:"in",q:"The four-digit number 3A5A (the same digit A twice) is divisible by 9. What digit is A?",ans:5,
 hint:"Write the digit sum with A in it.",
 expl:"The digit sum is 3 + A + 5 + A = 8 + 2A. The only digit making this a multiple of 9 is A = 5 (sum 18). Check: 3555 = 9 × 395."},
{lvl:3,sec:"T",type:"in",q:"What is the smallest number greater than 500 that is divisible by 2, 3, 4, 5 and 6?",ans:540,
 hint:"First find the smallest number divisible by all five.",
 expl:"The least common multiple of 2, 3, 4, 5 and 6 is 60. The first multiple of 60 above 500 is 540."},
{lvl:3,sec:"T",type:"mc",q:"Amara makes five-digit numbers using each of the digits 1, 2, 3, 4, 5 exactly once. How many of the 120 numbers are divisible by 3?",
 opts:["120","40","60","0"],a:0,hint:"What is the digit sum of every such number?",
 expl:"Every arrangement has digit sum 1 + 2 + 3 + 4 + 5 = 15, a multiple of 3. So all 120 numbers are divisible by 3."}
],

"g4-clockmod": [
{sec:"T",type:"in",q:"On a 12-hour clock it is 9 o'clock. What hour will it be 5 hours later?",ans:2,
 hint:"After 12 the clock starts again at 1.",expl:"9 + 5 = 14, and 14 − 12 = 2, so the clock shows 2 o'clock."},
{sec:"T",type:"in",q:"It is 3 o'clock. What hour was it 7 hours ago?",ans:8,hint:"Go back past 12.",
 expl:"Going back 3 hours reaches 12, then 4 more hours back reaches 8 o'clock."},
{sec:"T",type:"mc",q:"On a 12-hour clock, which hour is the same as 15?",opts:["3","15","5","12"],a:0,
 expl:"15 − 12 = 3, so 15 hours after 12 the clock shows 3."},
{sec:"T",type:"mc",q:"Today is Monday. What day of the week will it be in 25 days?",opts:["Friday","Thursday","Saturday","Monday"],a:0,
 hint:"Whole weeks do not change the day.",expl:"25 = 3 × 7 + 4, so it is 4 days after Monday: Friday."},
{lvl:2,sec:"T",type:"in",q:"It is 10 o'clock. What hour will a 12-hour clock show 100 hours later?",ans:2,
 hint:"Every 12 hours the clock returns to the same hour.",
 expl:"100 = 8 × 12 + 4, so only the remainder 4 matters. 10 + 4 = 14, which is 2 o'clock."},
{lvl:2,sec:"T",type:"in",q:"A wheel has 5 positions numbered 0 to 4. It starts at 0 and turns forward 23 positions. Which position does it stop on?",ans:3,
 hint:"Every 5 turns brings it back to 0.",expl:"23 = 4 × 5 + 3, so the wheel stops on position 3."},
{lvl:2,sec:"T",type:"mc",q:"What day of the week is 50 days after a Wednesday?",opts:["Thursday","Tuesday","Wednesday","Friday"],a:0,
 expl:"50 = 7 × 7 + 1, so it is 1 day after Wednesday: Thursday."},
{lvl:3,sec:"T",type:"in",q:"What is the remainder when the product of ten 2s (2 × 2 × ... × 2, ten times) is divided by 7?",ans:2,
 hint:"2 × 2 × 2 = 8 leaves remainder 1 when divided by 7.",
 expl:"Three 2s make 8, which is 1 more than 7. Nine 2s make three groups of 8, remainder 1 × 1 × 1 = 1. One more 2 gives remainder 2. Check: 1024 = 7 × 146 + 2."},
{lvl:3,sec:"T",type:"in",q:"Kenji sets a 12-hour clock to 12 at noon. What hour does it show exactly 1,000 hours later?",ans:4,
 hint:"Find the remainder when 1,000 is divided by 12.",
 expl:"1,000 = 83 × 12 + 4, so the clock has gone round 83 times and then 4 more hours: it shows 4."},
{lvl:3,sec:"T",type:"in",q:"What is the last digit of 7 × 7 × 7 × 7 × 7 × 7 (six 7s multiplied together)?",ans:9,
 hint:"Only the last digit of each step matters.",
 expl:"The last digits of the powers of 7 go 7, 9, 3, 1 and then repeat. The 6th is 9, since 6 = 4 + 2 and the 2nd in the cycle is 9."}
],

"g4-euclid": [
{sec:"T",type:"in",q:"Find the greatest common divisor (GCD) of 48 and 18.",ans:6,hint:"Divide 48 by 18 and look at the remainder.",
 expl:"48 = 2 × 18 + 12, then 18 = 1 × 12 + 6, then 12 = 2 × 6 + 0. The last non-zero remainder is 6."},
{sec:"T",type:"in",q:"In the Euclidean algorithm, 48 ÷ 18 leaves remainder 12, so gcd(48, 18) = gcd(18, ?). Type the missing number.",ans:12,
 expl:"The algorithm replaces the larger number with the remainder: gcd(48, 18) = gcd(18, 12)."},
{sec:"T",type:"mc",q:"The Euclidean algorithm works because gcd(a, b) is always equal to ...",mono:true,
 opts:["gcd(b, remainder of a ÷ b)","gcd(a × b, b)","gcd(a − 1, b)","gcd(a ÷ b, b)"],a:0,
 expl:"Any common divisor of a and b also divides the remainder of a ÷ b, so the pair (b, remainder) has the same GCD."},
{sec:"T",type:"in",q:"Use the algorithm to find gcd(35, 10).",ans:5,expl:"35 = 3 × 10 + 5, then 10 = 2 × 5 + 0, so the GCD is 5."},
{lvl:2,sec:"T",type:"in",q:"Find the GCD of 84 and 36.",ans:12,hint:"Keep dividing and taking remainders until you reach 0.",
 expl:"84 = 2 × 36 + 12, then 36 = 3 × 12 + 0. The GCD is 12."},
{lvl:2,sec:"T",type:"in",q:"Find the GCD of 121 and 55.",ans:11,expl:"121 = 2 × 55 + 11, then 55 = 5 × 11 + 0. The GCD is 11."},
{lvl:2,sec:"T",type:"mc",q:"When the Euclidean algorithm reaches a remainder of 0, the GCD is ...",
 opts:["the last non-zero remainder","the first remainder","the smaller starting number","the last quotient"],a:0,
 expl:"The GCD is the remainder from the step just before the remainder became 0."},
{lvl:3,sec:"T",type:"in",q:"Find the GCD of 1,071 and 462.",ans:21,hint:"1,071 ÷ 462 gives quotient 2.",
 expl:"1071 = 2 × 462 + 147, then 462 = 3 × 147 + 21, then 147 = 7 × 21 + 0. The GCD is 21."},
{lvl:3,sec:"T",type:"in",q:"Two ropes are 252 cm and 180 cm long. Both are cut into pieces of the same length, as long as possible, with nothing left over. How long is each piece, in cm?",ans:36,
 hint:"The piece length must divide both rope lengths.",
 expl:"The answer is gcd(252, 180). 252 = 1 × 180 + 72, 180 = 2 × 72 + 36, 72 = 2 × 36 + 0. Each piece is 36 cm."},
{lvl:3,sec:"T",type:"in",q:"Find the GCD of 1,001 and 91.",ans:91,hint:"Try dividing 1,001 by 91 first.",
 expl:"1001 = 11 × 91 + 0. The remainder is 0 straight away, so the GCD is 91."}
],

"g4-evalexpr": [
{sec:"L",type:"in",q:"(3 + 5) × 2 = ?",ans:16,hint:"Brackets first.",expl:"3 + 5 = 8, then 8 × 2 = 16."},
{sec:"L",type:"in",q:"3 + 5 × 2 = ?",ans:13,hint:"Multiply before you add.",expl:"5 × 2 = 10, then 3 + 10 = 13."},
{sec:"L",type:"in",q:"24 ÷ (2 + 4) = ?",ans:4,expl:"2 + 4 = 6, then 24 ÷ 6 = 4."},
{sec:"L",type:"mc",q:"Which part of 8 − (2 + 3) × 1 is worked out first?",mono:true,opts:["2 + 3","8 − 2","3 × 1","8 − 3"],a:0,
 expl:"Brackets come first, so 2 + 3 is done before the × and the −. The value is 8 − 5 = 3."},
{sec:"L",type:"in",q:"(10 − 4) × (2 + 3) = ?",ans:30,expl:"10 − 4 = 6 and 2 + 3 = 5, then 6 × 5 = 30."},
{lvl:2,sec:"L",type:"in",q:"2 × (3 + 4 × 2) = ?",ans:22,hint:"Inside the brackets, multiply first.",
 expl:"Inside the brackets 4 × 2 = 8, so 3 + 8 = 11. Then 2 × 11 = 22."},
{lvl:2,sec:"L",type:"in",q:"36 ÷ (3 × (5 − 2)) = ?",ans:4,hint:"Start with the innermost brackets.",
 expl:"5 − 2 = 3, then 3 × 3 = 9, then 36 ÷ 9 = 4."},
{lvl:2,sec:"L",type:"mc",q:"Where should brackets go so that 2 + 3 × 4 − 1 equals 19?",mono:true,
 opts:["(2 + 3) × 4 − 1","2 + 3 × (4 − 1)","2 + (3 × 4) − 1","(2 + 3) × (4 − 1)"],a:0,
 expl:"(2 + 3) × 4 − 1 = 5 × 4 − 1 = 19. The others give 11, 13 and 15."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY expression equal to 20.",mono:true,
 opts:["(2 + 3) × 4","2 + 3 × 4","4 × (8 − 3)","(4 × 8) − 3","40 ÷ (1 + 1)"],aMulti:[0,2,4],
 expl:"(2 + 3) × 4 = 20, 4 × (8 − 3) = 20 and 40 ÷ (1 + 1) = 20. The others are 14 and 29."},
{lvl:3,sec:"L",type:"in",q:"Evaluate 100 − (4 × (7 − 2) + 6) ÷ 2.",ans:87,hint:"Work from the inside out, then divide, then subtract.",
 expl:"7 − 2 = 5, 4 × 5 = 20, 20 + 6 = 26, 26 ÷ 2 = 13, and 100 − 13 = 87."},
{lvl:3,sec:"L",type:"in",q:"Priya evaluates (5 + 7) × (9 − 3) ÷ 4. What answer does she get?",ans:18,
 expl:"(5 + 7) = 12 and (9 − 3) = 6, so 12 × 6 = 72, then 72 ÷ 4 = 18."},
{lvl:3,sec:"L",type:"mc",q:"Which expression has the greatest value?",mono:true,
 opts:["(6 + 2) × (5 − 1)","6 + 2 × 5 − 1","(6 + 2 × 5) − 1","6 + 2 × (5 − 1)"],a:0,
 expl:"(6 + 2) × (5 − 1) = 8 × 4 = 32. The others are 15, 15 and 14."}
],

"g4-liketerms": [
{sec:"L",type:"mc",q:"Simplify 3x + 4x.",mono:true,opts:["7x","12x","7x²","7"],a:0,
 expl:"Three x's and four more x's make seven x's: 3x + 4x = 7x."},
{sec:"L",type:"mc",q:"Which pair are like terms?",mono:true,opts:["5y and 2y","5y and 5x","5y and 5","y and y²"],a:0,
 expl:"Like terms have exactly the same letter part. 5y and 2y both have just y."},
{sec:"L",type:"in",q:"When 2n + 5 + 3n is simplified, what number is in front of n (the coefficient)?",ans:5,
 hint:"Collect the terms with n.",expl:"2n + 3n = 5n, so the expression is 5n + 5 and the coefficient is 5."},
{sec:"L",type:"mc",q:"Simplify 6a − 2a + 3.",mono:true,opts:["4a + 3","7a","4a + 3a","8a"],a:0,
 expl:"6a − 2a = 4a. The 3 has no letter, so it cannot be combined: 4a + 3."},
{lvl:2,sec:"L",type:"mc",q:"Simplify 4x + 3y − x + 2y.",mono:true,opts:["3x + 5y","3x + y","5x + 5y","7xy"],a:0,
 expl:"x terms: 4x − x = 3x. y terms: 3y + 2y = 5y. The answer is 3x + 5y."},
{lvl:2,sec:"L",type:"in",q:"7p + 3 − 2p − 8 simplifies to 5p + c. What is c?",ans:-5,hint:"Combine the plain numbers, keeping their signs.",
 expl:"7p − 2p = 5p and 3 − 8 = −5, so the expression is 5p − 5 and c = −5."},
{lvl:2,sec:"L",type:"mc",q:"Simplify 2(x + 3) + 4x.",mono:true,opts:["6x + 6","6x + 3","8x + 3","2x + 7"],a:0,
 hint:"Expand the brackets first.",expl:"2(x + 3) = 2x + 6. Then 2x + 6 + 4x = 6x + 6."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY expression that simplifies to 5m + 2.",mono:true,
 opts:["3m + 2 + 2m","7m − 2m + 2","5m + 2m","m + 4m + 1 + 1","5 + 2m"],aMulti:[0,1,3],
 expl:"3m + 2m = 5m, 7m − 2m = 5m, and m + 4m = 5m with 1 + 1 = 2. But 5m + 2m = 7m, and 5 + 2m is 2m + 5."},
{lvl:3,sec:"L",type:"in",q:"A rectangle has sides x + 3 and 2x. Its perimeter simplifies to ax + b. What is a + b?",ans:12,
 hint:"Perimeter is twice the sum of the two sides.",
 expl:"Perimeter = 2(x + 3) + 2(2x) = 2x + 6 + 4x = 6x + 6. So a = 6, b = 6 and a + b = 12."},
{lvl:3,sec:"L",type:"mc",q:"Simplify 3(2a + b) − 2(a − b).",mono:true,opts:["4a + 5b","4a + b","8a + 5b","4a + 3b"],a:0,
 hint:"Careful with the minus sign in front of the second bracket.",
 expl:"3(2a + b) = 6a + 3b and −2(a − b) = −2a + 2b. Adding: 4a + 5b."},
{lvl:3,sec:"L",type:"in",q:"The expression 4t + 9 + 2t − 3 equals 30. What is t?",ans:4,hint:"Simplify first, then solve.",
 expl:"4t + 2t = 6t and 9 − 3 = 6, so 6t + 6 = 30. Then 6t = 24 and t = 4."}
],

"g4-onestep": [
{sec:"L",type:"in",q:"Solve x + 7 = 15.",ans:8,hint:"Undo the + 7.",expl:"Subtract 7 from both sides: x = 15 − 7 = 8."},
{sec:"L",type:"in",q:"Solve 4y = 36.",ans:9,hint:"4y means 4 × y.",expl:"Divide both sides by 4: y = 36 ÷ 4 = 9."},
{sec:"L",type:"in",q:"Solve n − 9 = 14.",ans:23,expl:"Add 9 to both sides: n = 14 + 9 = 23."},
{sec:"L",type:"mc",q:"To solve x + 5 = 12, what should you do to both sides?",opts:["Subtract 5","Add 5","Divide by 5","Multiply by 5"],a:0,
 expl:"Subtracting 5 undoes the + 5 and leaves x on its own: x = 7."},
{sec:"L",type:"in",q:"Solve m ÷ 6 = 7.",ans:42,hint:"Undo the division.",expl:"Multiply both sides by 6: m = 7 × 6 = 42."},
{lvl:2,sec:"L",type:"in",q:"Solve 48 = 8k.",ans:6,expl:"Divide both sides by 8: k = 48 ÷ 8 = 6."},
{lvl:2,sec:"L",type:"in",q:"Solve x − 3.5 = 10.",ans:13.5,expl:"Add 3.5 to both sides: x = 10 + 3.5 = 13.5."},
{lvl:2,sec:"L",type:"mc",q:"Which equation has the solution t = 5?",mono:true,opts:["3t = 15","t + 5 = 5","t − 5 = 5","5t = 5"],a:0,
 expl:"3 × 5 = 15, so t = 5 works in 3t = 15. The others give t = 0, t = 10 and t = 1."},
{lvl:2,sec:"L",type:"in",q:"Solve 7 + z = 3.",ans:-4,hint:"The answer is below zero.",expl:"Subtract 7 from both sides: z = 3 − 7 = −4."},
{lvl:3,sec:"L",type:"in",q:"Wei thinks of a number, multiplies it by 9 and gets 117. What was the number?",ans:13,
 hint:"Write it as 9n = 117.",expl:"9n = 117, so n = 117 ÷ 9 = 13."},
{lvl:3,sec:"L",type:"in",q:"Solve 5x = 2. Give your answer as a decimal.",ans:0.4,hint:"The answer is less than 1.",
 expl:"x = 2 ÷ 5 = 0.4. Check: 5 × 0.4 = 2."},
{lvl:3,sec:"L",type:"in",q:"An equation of the form x − a = 12 has the solution x = 20. What is a?",ans:8,
 hint:"Put 20 in place of x.",expl:"20 − a = 12, so a = 20 − 12 = 8."}
],

"g4-inequal": [
{sec:"L",type:"mc",q:"Which value of x makes x + 3 < 10 true?",opts:["5","7","8","10"],a:0,
 expl:"5 + 3 = 8, which is less than 10. The others give 10, 11 and 13, which are not less than 10."},
{sec:"L",type:"in",q:"What is the largest whole number n for which n + 4 < 12?",ans:7,hint:"n + 4 must stay below 12.",
 expl:"n must be less than 8, so the largest whole number is 7 (7 + 4 = 11)."},
{sec:"L",type:"mc",q:"Which inequality means 'y is at least 6'?",mono:true,opts:["y ≥ 6","y > 6","y ≤ 6","y < 6"],a:0,
 expl:"'At least 6' includes 6 itself and anything bigger, which is y ≥ 6."},
{sec:"L",type:"in",q:"What is the smallest whole number x for which 3x > 20?",ans:7,expl:"3 × 6 = 18 is not more than 20, but 3 × 7 = 21 is. So x = 7."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY whole number that satisfies 2n − 1 ≤ 9.",opts:["3","5","6","0","7"],aMulti:[0,1,3],
 expl:"2n − 1 ≤ 9 means 2n ≤ 10, so n ≤ 5. That includes 0, 3 and 5 but not 6 or 7."},
{lvl:2,sec:"L",type:"mc",q:"Solve x − 4 > 3.",mono:true,opts:["x > 7","x > −1","x < 7","x > 1"],a:0,
 expl:"Add 4 to both sides: x > 7."},
{lvl:2,sec:"L",type:"in",q:"How many whole numbers k satisfy 10 < 2k < 30?",ans:9,hint:"Divide everything by 2.",
 expl:"10 < 2k < 30 means 5 < k < 15, so k can be 6, 7, ..., 14. That is 9 numbers."},
{lvl:2,sec:"L",type:"order",q:"Order these inequalities by their largest whole-number solution, from smallest to largest.",
 items:["n + 2 < 5","3n < 12","n − 1 ≤ 5","n ÷ 2 ≤ 2"],ansOrder:["n + 2 < 5","3n < 12","n ÷ 2 ≤ 2","n − 1 ≤ 5"],
 expl:"The largest solutions are 2 (n < 3), 3 (n < 4), 4 (n ≤ 4) and 6 (n ≤ 6)."},
{lvl:3,sec:"L",type:"in",q:"Nadia has $50 and wants to buy books that cost $7 each. What is the greatest number of books she can buy?",ans:7,
 hint:"7 × (number of books) must be at most 50.",
 expl:"7b ≤ 50 gives b ≤ 7.14..., so she can buy 7 books for $49. An 8th would cost $56."},
{lvl:3,sec:"L",type:"in",q:"How many whole numbers n satisfy both n + 5 > 8 and 2n < 21?",ans:7,
 hint:"Solve each inequality, then find the overlap.",
 expl:"n + 5 > 8 means n > 3, and 2n < 21 means n < 10.5. So n is 4, 5, 6, 7, 8, 9 or 10: 7 numbers."},
{lvl:3,sec:"L",type:"mc",q:"If x > 4, which statement MUST be true?",mono:true,opts:["2x > 8","x > 5","x − 4 < 0","x ≤ 10"],a:0,
 expl:"Doubling both sides of x > 4 gives 2x > 8. The others can fail, for example when x = 4.5 or x = 20."}
],

"g4-writeeq": [
{sec:"L",type:"mc",q:"'A number n increased by 8 is 20.' Which equation says this?",mono:true,
 opts:["n + 8 = 20","n − 8 = 20","8n = 20","n ÷ 8 = 20"],a:0,
 expl:"'Increased by 8' means add 8, so n + 8 = 20 (and n = 12)."},
{sec:"L",type:"mc",q:"Yusuf has 4 times as many stickers as Mei. Mei has m stickers. How many does Yusuf have?",mono:true,
 opts:["4m","m + 4","m ÷ 4","4 − m"],a:0,
 expl:"'4 times as many' means multiply by 4: Yusuf has 4m stickers."},
{sec:"L",type:"in",q:"Six times a number is 54. What is the number?",ans:9,hint:"Write 6n = 54.",expl:"6n = 54, so n = 54 ÷ 6 = 9."},
{sec:"L",type:"mc",q:"'The product of 7 and a number is 63.' Which equation says this?",mono:true,
 opts:["7n = 63","7 + n = 63","n ÷ 7 = 63","n − 7 = 63"],a:0,
 expl:"A product comes from multiplying, so 7n = 63 (and n = 9)."},
{lvl:2,sec:"L",type:"mc",q:"Diego had d dollars, spent $12 and now has $25. Which equation says this?",mono:true,
 opts:["d − 12 = 25","d + 12 = 25","12 − d = 25","12d = 25"],a:0,
 expl:"Spending takes money away: d − 12 = 25, so he started with $37."},
{lvl:2,sec:"L",type:"in",q:"A number divided by 5 is 11. What is the number?",ans:55,expl:"n ÷ 5 = 11, so n = 11 × 5 = 55."},
{lvl:2,sec:"L",type:"in",q:"Three more than twice a number is 17. What is the number?",ans:7,hint:"Write 2n + 3 = 17.",
 expl:"2n + 3 = 17, so 2n = 14 and n = 7."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY equation that says 'a number less 4 equals 10'.",mono:true,
 opts:["n − 4 = 10","10 = n − 4","4 − n = 10","n + 4 = 10"],aMulti:[0,1],
 expl:"'A number less 4' is n − 4. Both n − 4 = 10 and 10 = n − 4 say the same thing. 4 − n and n + 4 are different."},
{lvl:3,sec:"L",type:"in",q:"Ingrid is 3 years older than her brother. Their ages add up to 25. How old is Ingrid?",ans:14,
 hint:"Let the brother be b, so Ingrid is b + 3.",
 expl:"b + (b + 3) = 25 gives 2b + 3 = 25, so b = 11. Ingrid is 11 + 3 = 14."},
{lvl:3,sec:"L",type:"in",q:"A taxi charges $3 to start plus $2 for each km. A ride cost $19. How many km was the ride?",ans:8,
 hint:"Write 3 + 2k = 19.",expl:"3 + 2k = 19, so 2k = 16 and k = 8 km."},
{lvl:3,sec:"L",type:"mc",q:"Tomas bought 5 pens at p dollars each. He paid with $20 and got $5 change. Which equation says this?",mono:true,
 opts:["5p = 20 − 5","5p = 20 + 5","p = 20 − 5","5 + p = 20"],a:0,
 expl:"The pens cost the $20 minus the $5 change, so 5p = 20 − 5 = 15 and each pen is $3."}
],

"g4-factorial": [
{sec:"K",type:"in",q:"What is 4! (4 factorial)?",ans:24,hint:"Multiply 4 × 3 × 2 × 1.",expl:"4! = 4 × 3 × 2 × 1 = 24."},
{sec:"K",type:"in",q:"In how many different orders can 3 books be placed on a shelf?",ans:6,
 expl:"3 choices for the first spot, 2 for the second, 1 for the last: 3 × 2 × 1 = 6."},
{sec:"K",type:"mc",q:"5! means ...",mono:true,opts:["5 × 4 × 3 × 2 × 1","5 + 4 + 3 + 2 + 1","5 × 5","5 × 4"],a:0,
 expl:"A factorial multiplies all whole numbers from the number down to 1, so 5! = 120."},
{sec:"K",type:"in",q:"Five runners finish a race with no ties. How many different finishing orders are possible?",ans:120,
 expl:"5! = 5 × 4 × 3 × 2 × 1 = 120 orders."},
{lvl:2,sec:"K",type:"in",q:"What is 6! ÷ 4!?",ans:30,hint:"Most of the factors cancel.",expl:"6! ÷ 4! = 720 ÷ 24 = 6 × 5 = 30."},
{lvl:2,sec:"K",type:"in",q:"Gold, silver and bronze medals are given to 6 runners. In how many ways can the medals be awarded?",ans:120,
 hint:"Only three places are filled.",expl:"6 choices for gold, 5 for silver, 4 for bronze: 6 × 5 × 4 = 120."},
{lvl:2,sec:"K",type:"in",q:"How many 3-digit numbers can be made from the digits 1, 2, 3, 4 with no digit repeated?",ans:24,
 expl:"4 choices for the first digit, 3 for the second, 2 for the third: 4 × 3 × 2 = 24."},
{lvl:2,sec:"K",type:"mc",q:"Which is equal to 7!?",mono:true,opts:["7 × 6!","7 × 6","6! + 7","7 × 7!"],a:0,
 expl:"7! = 7 × 6 × 5 × 4 × 3 × 2 × 1 = 7 × 6!, which is 5,040."},
{lvl:3,sec:"K",type:"in",q:"Hana, Elias and 3 other children sit in a row of 5 seats. Hana and Elias must sit next to each other. How many seating orders are there?",ans:48,
 hint:"Treat the two friends as one block, then remember the block can be swapped.",
 expl:"Glue Hana and Elias into one block: 4 things to arrange, 4! = 24 ways. The block can be in 2 orders, so 24 × 2 = 48."},
{lvl:3,sec:"K",type:"in",q:"How many arrangements of the letters M, A, T, H start with a vowel?",ans:6,
 hint:"There is only one vowel.",expl:"A must go first. The other 3 letters can be arranged in 3! = 6 ways."},
{lvl:3,sec:"K",type:"in",q:"How many zeros does 10! end with?",ans:2,hint:"Each zero needs a 2 and a 5 multiplied together.",
 expl:"10! = 3,628,800. The factors 5 and 10 each provide a 5, and there are plenty of 2s, so there are 2 trailing zeros."},
{lvl:3,sec:"K",type:"in",q:"Four different books are placed in a row so that the biggest book is at one of the two ends. How many arrangements are there?",ans:12,
 expl:"The biggest book has 2 possible ends; the other 3 books fill the rest in 3! = 6 ways: 2 × 6 = 12."}
],

"g4-combin": [
{sec:"K",type:"in",q:"How many ways can you choose 2 toppings from a list of 4?",ans:6,hint:"Order does not matter: list the pairs.",
 expl:"With toppings A, B, C, D the pairs are AB, AC, AD, BC, BD, CD: 6 ways."},
{sec:"K",type:"mc",q:"Choosing a team of 3 from 5 people is a combination because ...",
 opts:["order does not matter","order matters","3 is smaller than 5","people are different"],a:0,
 expl:"A team is the same team whichever order you pick the members in, so it is a combination."},
{sec:"K",type:"in",q:"How many different pairs can be formed from 5 children?",ans:10,
 expl:"Each of 5 children can pair with 4 others, giving 5 × 4 = 20, but each pair is counted twice: 20 ÷ 2 = 10."},
{sec:"K",type:"in",q:"How many ways are there to choose 1 prize from 7 prizes?",ans:7,expl:"Choosing 1 from 7 can be done in 7 ways."},
{lvl:2,sec:"K",type:"in",q:"How many ways can 3 books be chosen from 6?",ans:20,hint:"Count ordered choices, then divide by 3!.",
 expl:"6 × 5 × 4 = 120 ordered choices, and each set of 3 appears 3! = 6 times: 120 ÷ 6 = 20."},
{lvl:2,sec:"K",type:"in",q:"A pizza shop offers 6 toppings. How many different 2-topping pizzas can be made?",ans:15,
 expl:"6 × 5 = 30 ordered pairs, divided by 2 because order does not matter: 15 pizzas."},
{lvl:2,sec:"K",type:"mc",q:"Which of these is a combination, NOT a permutation?",
 opts:["choosing 2 flavours for a sundae","awarding 1st and 2nd place","making a 3-digit code","choosing a captain and vice-captain"],a:0,
 expl:"Two flavours together are the same sundae in any order. The other three depend on order or position."},
{lvl:2,sec:"K",type:"in",q:"How many ways can 5 students be chosen from 7 for a trip?",ans:21,
 hint:"Choosing 5 to go is the same as choosing 2 to stay.",expl:"Choosing 2 to stay behind: 7 × 6 ÷ 2 = 21 ways."},
{lvl:3,sec:"K",type:"in",q:"Seven points are marked on a circle. How many triangles have all three corners at these points?",ans:35,
 hint:"Every set of 3 points makes one triangle.",expl:"7 × 6 × 5 = 210 ordered choices, divided by 3! = 6: 35 triangles."},
{lvl:3,sec:"K",type:"in",q:"A club has 4 girls and 3 boys. How many ways can 2 girls and 1 boy be chosen?",ans:18,
 hint:"Count the girls' choices and the boys' choices separately, then multiply.",
 expl:"2 girls from 4: 6 ways. 1 boy from 3: 3 ways. Together 6 × 3 = 18."},
{lvl:3,sec:"K",type:"in",q:"Ten people each shake hands once with everyone else. How many handshakes happen?",ans:45,
 expl:"Each handshake is a pair of people: 10 × 9 ÷ 2 = 45."},
{lvl:3,sec:"K",type:"mc",q:"Leila must pick 2 of 5 colours for a flag. Lior must pick 3 of the same 5 colours. Who has more choices?",
 opts:["They have the same number","Leila","Lior","Cannot tell"],a:0,
 expl:"Picking 3 to use is the same as picking 2 to leave out, so both have 10 choices."}
],

"g4-paths": [
{sec:"K",type:"in",q:"On a grid you may only move right or up. How many paths go from the start to a point 2 steps right and 1 step up?",ans:3,
 hint:"Each path is a list of moves like R, R, U.",expl:"The paths are RRU, RUR and URR: 3 paths."},
{sec:"K",type:"in",q:"Moving only right or up, how many paths lead to the point 2 right and 2 up?",ans:6,
 expl:"Choose which 2 of the 4 moves are 'up': RRUU, RURU, RUUR, URRU, URUR, UURR give 6 paths."},
{sec:"K",type:"mc",q:"Why is counting grid paths a combination problem?",
 opts:["you choose which moves are 'right'","paths can go backwards","every path is a square","you count the corners"],a:0,
 expl:"A path is fixed once you decide which of the moves are 'right' (the rest are 'up'), and the order of choosing does not matter."},
{sec:"K",type:"in",q:"A path must contain exactly 3 moves right and 1 move up. How many different paths are there?",ans:4,
 expl:"The single 'up' can be the 1st, 2nd, 3rd or 4th move: 4 paths."},
{lvl:2,sec:"K",type:"in",q:"How many right-or-up paths go from one corner of a 3 × 3 grid of squares to the opposite corner (3 right, 3 up)?",ans:20,
 hint:"Choose 3 of the 6 moves to be 'up'.",expl:"6 moves, choose 3 to be 'up': 6 × 5 × 4 ÷ (3 × 2 × 1) = 20 paths."},
{lvl:2,sec:"K",type:"in",q:"How many right-or-up paths use exactly 4 moves right and 2 moves up?",ans:15,
 expl:"Choose 2 of the 6 moves to be 'up': 6 × 5 ÷ 2 = 15 paths."},
{lvl:2,sec:"K",type:"mc",q:"When you label each grid point with the number of paths to it, the number at a point equals ...",
 opts:["the sum of the two points before it","its row number","the product of its neighbours","always 1"],a:0,
 expl:"Every path arrives from the point to the left or the point below, so add those two counts. This builds Pascal's triangle."},
{lvl:2,sec:"K",type:"in",q:"How many right-or-up paths go from (0, 0) to (5, 1)?",ans:6,hint:"There is only one 'up' move.",
 expl:"Six moves in total, and the single 'up' can be any one of them: 6 paths."},
{lvl:3,sec:"K",type:"in",q:"How many right-or-up paths cross a 4 × 4 grid of squares from one corner to the opposite corner?",ans:70,
 hint:"Choose 4 of the 8 moves.",expl:"8 moves, choose 4 to be 'up': 8 × 7 × 6 × 5 ÷ (4 × 3 × 2 × 1) = 70."},
{lvl:3,sec:"K",type:"in",q:"How many right-or-up paths from (0, 0) to (3, 3) pass through the point (1, 1)?",ans:12,
 hint:"Count paths to (1, 1), then paths from (1, 1) onward, and multiply.",
 expl:"(0, 0) to (1, 1): 2 paths. (1, 1) to (3, 3): 2 right and 2 up, 6 paths. Total 2 × 6 = 12."},
{lvl:3,sec:"K",type:"in",q:"Chioma walks right or up from (0, 0) to (3, 3) but the point (1, 1) is blocked. How many paths can she take?",ans:8,
 hint:"Subtract the blocked paths from the total.",
 expl:"There are 20 paths in total and 12 of them pass through (1, 1). That leaves 20 − 12 = 8 paths."}
],

"g4-starsbars": [
{sec:"K",type:"in",q:"Five identical sweets are shared between 2 children. Each child may get any number, including zero. How many ways are there?",ans:6,
 hint:"List how many the first child gets.",expl:"The first child can get 0, 1, 2, 3, 4 or 5 and the second gets the rest: 6 ways."},
{sec:"K",type:"in",q:"Four identical apples are shared between 2 children so that each gets at least 1. How many ways are there?",ans:3,
 expl:"The splits are 1 and 3, 2 and 2, 3 and 1: 3 ways."},
{sec:"K",type:"mc",q:"In the stars-and-bars method, the bars stand for ...",
 opts:["the dividers between people's shares","the objects being shared","the number of people","the total count"],a:0,
 expl:"Stars are the objects and bars split them into groups, one group per person. For example **|*|** means shares of 2, 1 and 2."},
{sec:"K",type:"in",q:"Three identical coins are given to 3 children (a child may get none). How many ways are there?",ans:10,
 hint:"Try listing by pattern: 3-0-0, 2-1-0, 1-1-1.",
 expl:"3-0-0 in 3 ways, 2-1-0 in 6 ways, 1-1-1 in 1 way: 3 + 6 + 1 = 10. This matches 3 stars and 2 bars: 5 × 4 ÷ 2 = 10."},
{lvl:2,sec:"K",type:"in",q:"In how many ways can 6 be written as a sum of 3 positive whole numbers, if 1 + 2 + 3 and 3 + 2 + 1 count as different?",ans:10,
 hint:"Put 6 stars in a row; choose 2 of the 5 gaps for bars.",expl:"There are 5 gaps between the 6 stars; choosing 2 gaps for bars gives 5 × 4 ÷ 2 = 10 ways."},
{lvl:2,sec:"K",type:"in",q:"Seven identical marbles are shared among 3 children, and a child may get none. How many ways are there?",ans:36,
 hint:"7 stars and 2 bars: choose where the 2 bars go among 9 places.",expl:"Arrange 7 stars and 2 bars: choose 2 of 9 positions for the bars, 9 × 8 ÷ 2 = 36."},
{lvl:2,sec:"K",type:"mc",q:"Sharing 10 identical balls among 4 boxes (empty boxes allowed) is the same as counting arrangements of ...",mono:true,
 opts:["10 stars and 3 bars","10 stars and 4 bars","4 stars and 10 bars","14 stars"],a:0,
 expl:"Four boxes need 3 dividers. So arrange 10 stars and 3 bars: 13 × 12 × 11 ÷ 6 = 286 ways."},
{lvl:2,sec:"K",type:"in",q:"Five identical stickers are shared between 3 friends so that each gets at least one. How many ways are there?",ans:6,
 expl:"5 stars have 4 gaps; choose 2 gaps for bars: 4 × 3 ÷ 2 = 6. The patterns are 3-1-1 (3 ways) and 2-2-1 (3 ways)."},
{lvl:3,sec:"K",type:"in",q:"Eight identical cookies are shared among 3 children so that each gets at least 2. How many ways are there?",ans:6,
 hint:"Give everyone their 2 first, then share what is left.",
 expl:"Hand out 2 each (6 cookies). The remaining 2 go to 3 children with zero allowed: 2-0-0 in 3 ways and 1-1-0 in 3 ways, total 6."},
{lvl:3,sec:"K",type:"in",q:"How many whole-number solutions (zero allowed) does a + b + c + d = 6 have?",ans:84,
 hint:"6 stars and 3 bars.",expl:"Arrange 6 stars and 3 bars: choose 3 of 9 positions, 9 × 8 × 7 ÷ 6 = 84."},
{lvl:3,sec:"K",type:"in",q:"Oluwaseun buys 6 pieces of fruit from a stall that sells apples, bananas and pears (plenty of each). How many different selections are possible?",ans:28,
 hint:"Only the number of each fruit matters, not the order.",
 expl:"Split 6 pieces among 3 types, zero allowed: 6 stars and 2 bars, 8 × 7 ÷ 2 = 28."}
],

"g4-tri-area": [
{sec:"G",type:"in",q:"A triangle has base 8 cm and height 5 cm. What is its area in cm²?",ans:20,hint:"Half of base × height.",
 expl:"Area = ½ × 8 × 5 = 20 cm²."},
{sec:"G",type:"mc",q:"Which is the formula for the area of a triangle?",mono:true,
 opts:["½ × base × height","base × height","base + height","2 × base × height"],a:0,
 expl:"A triangle is half of a parallelogram with the same base and height, so area = ½ × base × height."},
{sec:"G",type:"in",q:"A right-angled triangle has legs of 6 units and 9 units. What is its area in square units?",ans:27,
 expl:"The legs are the base and height: ½ × 6 × 9 = 27 square units."},
{sec:"G",type:"in",q:"A triangle has base 10 m and height 7 m. What is its area in m²?",ans:35,expl:"½ × 10 × 7 = 35 m²."},
{lvl:2,sec:"G",type:"in",q:"A triangle has area 24 cm² and base 6 cm. What is its height in cm?",ans:8,hint:"Base × height must be double the area.",
 expl:"½ × 6 × h = 24 means 3h = 24, so h = 8 cm."},
{lvl:2,sec:"G",type:"in",q:"A triangle has base 7 cm and height 5 cm. What is its area in cm² (as a decimal)?",ans:17.5,
 expl:"½ × 7 × 5 = 35 ÷ 2 = 17.5 cm²."},
{lvl:2,sec:"G",type:"mc",q:"Two triangles have the same base and the same height but different shapes. Their areas are ...",
 opts:["equal","different","impossible to compare","bigger for the pointier one"],a:0,
 expl:"Area depends only on base and height, so they are equal even if one looks lopsided."},
{lvl:2,sec:"G",type:"in",q:"A 12 cm by 8 cm rectangle is cut along a diagonal. What is the area of each triangle in cm²?",ans:48,
 expl:"The rectangle has area 96 cm² and the diagonal halves it: 48 cm² each."},
{lvl:3,sec:"G",type:"in",q:"A triangle has corners at (0, 0), (6, 0) and (2, 5). What is its area in square units?",ans:15,
 hint:"The base lies along the x-axis; the height is the y-coordinate of the top corner.",
 expl:"Base from (0, 0) to (6, 0) is 6, height is 5: ½ × 6 × 5 = 15 square units."},
{lvl:3,sec:"G",type:"in",q:"A square of side 10 cm has a triangular corner cut off with legs 4 cm and 6 cm. What area in cm² remains?",ans:88,
 hint:"Square minus triangle.",expl:"Square 10 × 10 = 100 cm², triangle ½ × 4 × 6 = 12 cm², so 100 − 12 = 88 cm²."},
{lvl:3,sec:"G",type:"in",q:"A triangle's height is twice its base and its area is 36 cm². What is its base in cm?",ans:6,
 hint:"Write the height as 2 × base.",expl:"½ × b × 2b = b², so b² = 36 and b = 6 cm."},
{lvl:3,sec:"G",type:"in",q:"A triangle with base 12 has area 30. A second triangle has the same height but base 20. What is its area?",ans:50,
 hint:"Find the shared height first.",expl:"½ × 12 × h = 30 gives h = 5. Then ½ × 20 × 5 = 50."}
],

"g4-para-area": [
{sec:"G",type:"in",q:"A parallelogram has base 9 cm and height 4 cm. What is its area in cm²?",ans:36,expl:"Area = base × height = 9 × 4 = 36 cm²."},
{sec:"G",type:"mc",q:"The area of a parallelogram is ...",mono:true,opts:["base × height","½ × base × height","base + height","side × side"],a:0,
 expl:"Cut a triangle from one end and slide it to the other to make a rectangle: area = base × height."},
{sec:"G",type:"in",q:"A trapezoid has parallel sides 6 cm and 10 cm and height 4 cm. What is its area in cm²?",ans:32,
 hint:"Average the parallel sides, then multiply by the height.",expl:"(6 + 10) ÷ 2 = 8, and 8 × 4 = 32 cm²."},
{sec:"G",type:"mc",q:"A parallelogram has sides 8 cm and 5 cm, and the height to the 8 cm side is 4 cm. What is its area?",mono:true,
 opts:["32 cm²","40 cm²","20 cm²","26 cm²"],a:0,
 expl:"Use the base and its matching height, not the slanted side: 8 × 4 = 32 cm²."},
{lvl:2,sec:"G",type:"in",q:"A parallelogram has area 54 cm² and base 9 cm. What is its height in cm?",ans:6,expl:"9 × h = 54, so h = 6 cm."},
{lvl:2,sec:"G",type:"in",q:"A trapezoid has parallel sides 5 cm and 9 cm and height 7 cm. What is its area in cm²?",ans:49,
 expl:"(5 + 9) ÷ 2 = 7, and 7 × 7 = 49 cm²."},
{lvl:2,sec:"G",type:"mc",q:"To see why a parallelogram's area is base × height, cut a triangle off one end and ...",
 opts:["slide it across to form a rectangle","rotate it to form a triangle","fold it to form a square","remove it to halve the area"],a:0,
 expl:"Moving the triangle to the other end makes a rectangle with the same base and height, and the same area."},
{lvl:2,sec:"G",type:"in",q:"A trapezoid has area 40 cm², height 5 cm and one parallel side of 6 cm. How long is the other parallel side, in cm?",ans:10,
 hint:"The average of the parallel sides times 5 is 40.",expl:"(6 + x) ÷ 2 × 5 = 40 gives (6 + x) ÷ 2 = 8, so 6 + x = 16 and x = 10 cm."},
{lvl:3,sec:"G",type:"in",q:"A parallelogram has area 72 cm² and its base is twice its height. What is its height in cm?",ans:6,
 hint:"Write the base as 2 × height.",expl:"2h × h = 72, so h² = 36 and h = 6 cm."},
{lvl:3,sec:"G",type:"in",q:"A garden is a trapezoid with parallel sides 8 m and 14 m and height 5 m. Turf costs $3 per m². What is the total cost in dollars?",ans:165,
 hint:"Find the area first.",expl:"Area = (8 + 14) ÷ 2 × 5 = 11 × 5 = 55 m². Cost = 55 × 3 = $165."},
{lvl:3,sec:"G",type:"mc",q:"A parallelogram and a triangle share the same base and height. The parallelogram's area is ...",
 opts:["twice the triangle's","the same as the triangle's","half the triangle's","four times the triangle's"],a:0,
 expl:"Triangle = ½ × base × height and parallelogram = base × height, so the parallelogram is twice as big."},
{lvl:3,sec:"G",type:"in",q:"A trapezoid has parallel sides 7 cm and 13 cm and area 60 cm². What is its height in cm?",ans:6,
 expl:"(7 + 13) ÷ 2 = 10, and 10 × h = 60, so h = 6 cm."}
],

"g4-circle": [
{sec:"G",type:"in",q:"A circle has radius 5 cm. Using π ≈ 3.14, what is its circumference in cm?",ans:31.4,
 hint:"Circumference = 2 × π × radius.",expl:"2 × 3.14 × 5 = 31.4 cm."},
{sec:"G",type:"mc",q:"Which is the formula for the circumference of a circle?",mono:true,opts:["2 × π × r","π × r²","π × r","2 × π × r²"],a:0,
 expl:"Circumference = π × diameter = 2 × π × r. The formula π × r² is for area."},
{sec:"G",type:"in",q:"A circle has radius 2 cm. Using π ≈ 3.14, what is its area in cm²?",ans:12.56,
 hint:"Area = π × r × r.",expl:"3.14 × 2 × 2 = 12.56 cm²."},
{sec:"G",type:"in",q:"A circle has diameter 7 cm. Using π ≈ 22/7, what is its circumference in cm?",ans:22,
 expl:"Circumference = π × diameter = 22/7 × 7 = 22 cm."},
{lvl:2,sec:"G",type:"in",q:"A circle has radius 10 cm. Using π ≈ 3.14, what is its area in cm²?",ans:314,expl:"3.14 × 10 × 10 = 314 cm²."},
{lvl:2,sec:"G",type:"in",q:"A circle has diameter 14 cm. Using π ≈ 22/7, what is its area in cm²?",ans:154,
 hint:"Halve the diameter to get the radius first.",expl:"Radius = 7 cm. Area = 22/7 × 7 × 7 = 22 × 7 = 154 cm²."},
{lvl:2,sec:"G",type:"mc",q:"If the radius of a circle is doubled, its area ...",
 opts:["is multiplied by 4","is doubled","is multiplied by 8","stays the same"],a:0,
 expl:"Area uses r × r. Doubling r gives 2r × 2r = 4 × r × r, so the area is 4 times bigger."},
{lvl:2,sec:"G",type:"in",q:"A circle has circumference 18.84 cm. Using π ≈ 3.14, what is its radius in cm?",ans:3,
 hint:"Divide by 2π.",expl:"2 × 3.14 = 6.28, and 18.84 ÷ 6.28 = 3 cm."},
{lvl:3,sec:"G",type:"in",q:"A semicircle (half circle) has radius 4 cm. Using π ≈ 3.14, what is its area in cm²?",ans:25.12,
 hint:"Find the full circle's area, then halve it.",expl:"Full circle: 3.14 × 4 × 4 = 50.24 cm². Half of that is 25.12 cm²."},
{lvl:3,sec:"G",type:"in",q:"A wheel has radius 35 cm. Using π ≈ 22/7, how far does it roll in 10 complete turns, in cm?",ans:2200,
 hint:"One turn moves the wheel one circumference.",expl:"Circumference = 2 × 22/7 × 35 = 220 cm. Ten turns: 220 × 10 = 2,200 cm."},
{lvl:3,sec:"G",type:"in",q:"The largest possible circle is cut from a square of side 10 cm. Using π ≈ 3.14, what area in cm² is left over?",ans:21.5,
 hint:"The circle's diameter equals the side of the square.",expl:"Radius = 5 cm, circle area = 3.14 × 25 = 78.5 cm². Left over: 100 − 78.5 = 21.5 cm²."},
{lvl:3,sec:"G",type:"mc",q:"Which has more total area: one circle of radius 4, or two circles of radius 2?",
 opts:["the one big circle","the two small circles","they are equal","cannot tell"],a:0,
 expl:"One circle of radius 4 has area 16π. Two circles of radius 2 have 4π + 4π = 8π. The big circle wins."}
],

"g4-nets": [
{sec:"G",type:"in",q:"A cube has edges of 3 cm. What is its surface area in cm²?",ans:54,hint:"Six identical square faces.",
 expl:"Each face is 3 × 3 = 9 cm², and 6 × 9 = 54 cm²."},
{sec:"G",type:"mc",q:"How many squares are in the net of a cube?",opts:["6","4","8","12"],a:0,expl:"A cube has 6 faces, so its net has 6 squares."},
{sec:"G",type:"in",q:"A box is 4 cm by 3 cm by 2 cm. What is the total area of its net in cm²?",ans:52,
 hint:"There are three pairs of matching faces.",expl:"Faces: 4 × 3 = 12, 4 × 2 = 8, 3 × 2 = 6, each twice: 2 × (12 + 8 + 6) = 52 cm²."},
{sec:"G",type:"mc",q:"What is a net of a solid?",
 opts:["a flat shape that folds into the solid","the inside of the solid","a drawing of the solid","the curved part of the solid"],a:0,
 expl:"A net is the flat pattern of faces that folds up to make the 3D shape."},
{lvl:2,sec:"G",type:"in",q:"A box is 5 cm by 4 cm by 3 cm. What is its surface area in cm²?",ans:94,
 expl:"2 × (5 × 4 + 5 × 3 + 4 × 3) = 2 × (20 + 15 + 12) = 94 cm²."},
{lvl:2,sec:"G",type:"in",q:"A cube has surface area 96 cm². How long is each edge in cm?",ans:4,hint:"First find the area of one face.",
 expl:"One face is 96 ÷ 6 = 16 cm², and 4 × 4 = 16, so each edge is 4 cm."},
{lvl:2,sec:"G",type:"mc",q:"A net is made of 6 squares in one straight row. Does it fold into a cube?",
 opts:["No, faces would overlap","Yes","Only with small squares","Yes, into two cubes"],a:0,
 expl:"Folding a straight strip wraps 4 squares around and the last 2 land on faces already covered, so it cannot close up."},
{lvl:2,sec:"G",type:"in",q:"A net of a square-based pyramid has a 6 cm square base and four triangles, each with base 6 cm and height 5 cm. What is the total surface area in cm²?",ans:96,
 hint:"Square plus four triangles.",expl:"Base 6 × 6 = 36. Each triangle ½ × 6 × 5 = 15, and 4 × 15 = 60. Total 36 + 60 = 96 cm²."},
{lvl:3,sec:"G",type:"in",q:"A closed box measures 10 cm by 6 cm by 4 cm. Wrapping paper costs 2 cents per cm². What does it cost, in cents, to cover the box exactly?",ans:496,
 hint:"Find the surface area first.",expl:"Surface area = 2 × (60 + 40 + 24) = 248 cm². Cost = 248 × 2 = 496 cents."},
{lvl:3,sec:"G",type:"in",q:"An open-top box (no lid) is 5 cm by 5 cm by 3 cm tall. What is the area of its net in cm²?",ans:85,
 hint:"One square base and four rectangular sides.",expl:"Base 5 × 5 = 25. Four sides each 5 × 3 = 15, total 60. Net area 25 + 60 = 85 cm²."},
{lvl:3,sec:"G",type:"in",q:"A triangular prism is 10 cm long. Its triangular ends have base 6 cm and height 4 cm, and the three side rectangles are 10 cm by 6 cm, 10 cm by 5 cm and 10 cm by 5 cm. What is its surface area in cm²?",ans:184,
 hint:"Two triangles plus three rectangles.",expl:"Triangles: 2 × (½ × 6 × 4) = 24. Rectangles: 60 + 50 + 50 = 160. Total 184 cm²."},
{lvl:3,sec:"G",type:"in",q:"Two cubes with 2 cm edges are glued together face to face. What is the surface area of the new solid in cm²?",ans:40,
 hint:"Gluing hides two faces.",expl:"Each cube has 6 × 4 = 24 cm², total 48. Two faces of 4 cm² are hidden: 48 − 8 = 40 cm²."}
],

"g4-volprism": [
{sec:"G",type:"in",q:"A box is 5 cm long, 3 cm wide and 2 cm tall. What is its volume in cm³?",ans:30,expl:"5 × 3 × 2 = 30 cm³."},
{sec:"G",type:"mc",q:"The volume of any prism is ...",opts:["area of base × height","base + height","length × width","2 × area of base"],a:0,
 expl:"A prism is made of identical layers of its base, so volume = area of base × height."},
{sec:"G",type:"in",q:"A cube has edges of 4 cm. What is its volume in cm³?",ans:64,expl:"4 × 4 × 4 = 64 cm³."},
{sec:"G",type:"in",q:"A rectangular prism is 6 cm by 6 cm by 10 cm. What is its volume in cm³?",ans:360,expl:"6 × 6 × 10 = 360 cm³."},
{lvl:2,sec:"G",type:"in",q:"A triangular prism has a base area of 12 cm² and is 7 cm long. What is its volume in cm³?",ans:84,expl:"12 × 7 = 84 cm³."},
{lvl:2,sec:"G",type:"in",q:"A box has volume 120 cm³, length 6 cm and width 5 cm. What is its height in cm?",ans:4,hint:"Find the base area first.",
 expl:"Base area = 6 × 5 = 30 cm², and 120 ÷ 30 = 4 cm."},
{lvl:2,sec:"G",type:"in",q:"A triangular prism has a triangle end with base 8 cm and height 3 cm, and it is 10 cm long. What is its volume in cm³?",ans:120,
 hint:"Area of the triangle first.",expl:"Triangle area = ½ × 8 × 3 = 12 cm². Volume = 12 × 10 = 120 cm³."},
{lvl:2,sec:"G",type:"mc",q:"Which holds more: a 4 × 4 × 4 box or a 2 × 8 × 4 box?",mono:true,
 opts:["they hold the same","the 4 × 4 × 4 box","the 2 × 8 × 4 box","cannot tell"],a:0,
 expl:"4 × 4 × 4 = 64 and 2 × 8 × 4 = 64, so their volumes are equal."},
{lvl:3,sec:"G",type:"in",q:"A fish tank is 50 cm long and 30 cm wide. Water fills it to a depth of 25 cm. How many litres of water is that? (1 litre = 1,000 cm³)",ans:37.5,
 hint:"Use the water depth, not the tank height.",expl:"50 × 30 × 25 = 37,500 cm³, and 37,500 ÷ 1,000 = 37.5 litres."},
{lvl:3,sec:"G",type:"in",q:"A prism's cross-section is an L-shape made from a 3 cm × 5 cm rectangle joined to a 2 cm × 4 cm rectangle. The prism is 10 cm long. What is its volume in cm³?",ans:230,
 hint:"Find the L-shape's area first.",expl:"Cross-section area = 15 + 8 = 23 cm². Volume = 23 × 10 = 230 cm³."},
{lvl:3,sec:"G",type:"in",q:"How many 2 cm cubes fit exactly into a box 8 cm by 6 cm by 4 cm?",ans:24,hint:"Count cubes along each edge.",
 expl:"4 cubes along 8 cm, 3 along 6 cm, 2 along 4 cm: 4 × 3 × 2 = 24 cubes."},
{lvl:3,sec:"G",type:"in",q:"A cube has volume 125 cm³. What is its surface area in cm²?",ans:150,hint:"Find the edge first.",
 expl:"5 × 5 × 5 = 125, so the edge is 5 cm. Surface area = 6 × 25 = 150 cm²."}
],

"g4-exptheo": [
{sec:"S",type:"mc",q:"What is the theoretical probability of rolling a 4 on a fair 6-sided die?",mono:true,opts:["1/6","1/4","4/6","1/2"],a:0,
 expl:"One face out of six equally likely faces shows a 4: 1/6."},
{sec:"S",type:"mc",q:"Aisha flips a coin 20 times and gets 12 heads. What is her experimental probability of heads?",mono:true,
 opts:["12/20","1/2","8/20","12/8"],a:0,
 expl:"Experimental probability = number of heads ÷ number of flips = 12/20."},
{sec:"S",type:"mc",q:"Which describes theoretical probability?",
 opts:["what should happen by reasoning","what did happen in trials","a lucky guess","always one half"],a:0,
 expl:"Theoretical probability is worked out from the equally likely outcomes; experimental probability comes from actual trials."},
{sec:"S",type:"in",q:"A spinner has 5 equal sections. What is the theoretical probability of landing on one particular section, as a decimal?",ans:0.2,
 expl:"1 section out of 5: 1/5 = 0.2."},
{lvl:2,sec:"S",type:"in",q:"Mateo rolls a die 60 times and gets a 6 fifteen times. What is his experimental probability of a 6, as a decimal?",ans:0.25,
 expl:"15/60 = 1/4 = 0.25. The theoretical probability is 1/6, so he got a 6 a little more often than expected."},
{lvl:2,sec:"S",type:"in",q:"A fair coin is flipped 200 times. About how many heads should you expect?",ans:100,
 expl:"Theoretical probability of heads is 1/2, and 1/2 × 200 = 100."},
{lvl:2,sec:"S",type:"mc",q:"Experimental results usually get closer to the theoretical probability when ...",
 opts:["more trials are done","fewer trials are done","the coin is bigger","the results are written down"],a:0,
 expl:"With more trials, chance wobbles even out and the experimental result settles near the theoretical value."},
{lvl:2,sec:"S",type:"in",q:"A fair 6-sided die is rolled 300 times. About how many rolls should show a number greater than 4?",ans:100,
 hint:"Which faces are greater than 4?",expl:"Only 5 and 6 are greater than 4: probability 2/6 = 1/3, and 1/3 × 300 = 100."},
{lvl:3,sec:"S",type:"in",q:"Zainab spun a spinner 50 times: red 22, blue 18, green 10. What is the experimental probability of green, as a decimal?",ans:0.2,
 expl:"10 greens out of 50 spins: 10/50 = 0.2."},
{lvl:3,sec:"S",type:"mc",q:"A spinner with 4 equal colours is spun 40 times and lands on red 19 times. Which is the best conclusion?",
 opts:["surprising but possible","the spinner must be broken","red is always more likely","the theoretical probability changed"],a:0,
 expl:"Theory expects about 10 reds. Getting 19 is unusual but can happen by chance; you would need many more spins to decide the spinner is unfair."},
{lvl:3,sec:"S",type:"in",q:"A bag holds 3 red and 5 blue marbles. A marble is drawn and put back 400 times. About how many red draws are expected?",ans:150,
 hint:"Probability of red times number of draws.",expl:"P(red) = 3/8, and 3/8 × 400 = 150."},
{lvl:3,sec:"S",type:"in",q:"A coin is flipped 50 times and shows heads 30 times. How much bigger is the experimental probability of heads than the theoretical probability? Give a decimal.",ans:0.1,
 hint:"Work out both probabilities, then subtract.",expl:"Experimental = 30/50 = 0.6, theoretical = 0.5. The difference is 0.6 − 0.5 = 0.1."}
],

"g4-simple": [
{sec:"S",type:"mc",q:"A bag has 3 red balls and 2 blue balls. What is the probability of picking a red ball?",mono:true,opts:["3/5","2/5","1/2","3/2"],a:0,
 expl:"3 red out of 5 balls in total: 3/5."},
{sec:"S",type:"in",q:"What is the probability of rolling an even number on a fair 6-sided die, as a decimal?",ans:0.5,
 expl:"2, 4 and 6 are even: 3/6 = 1/2 = 0.5."},
{sec:"S",type:"mc",q:"Which event is impossible?",
 opts:["rolling a 7 on a 6-sided die","rolling a 1 on a 6-sided die","flipping heads on a coin","rolling an even number"],a:0,
 expl:"A 6-sided die only shows 1 to 6, so a 7 has probability 0."},
{sec:"S",type:"mc",q:"One letter is picked at random from the word MATHS. What is the probability it is a vowel?",mono:true,opts:["1/5","2/5","1/4","0"],a:0,
 expl:"MATHS has 5 letters and only A is a vowel: 1/5."},
{lvl:2,sec:"S",type:"in",q:"A spinner has 8 equal sections numbered 1 to 8. What is the probability of spinning a number greater than 6, as a decimal?",ans:0.25,
 expl:"7 and 8 are greater than 6: 2/8 = 1/4 = 0.25."},
{lvl:2,sec:"S",type:"mc",q:"Ten cards are numbered 1 to 10. One is picked at random. What is the probability it shows a prime number?",mono:true,
 opts:["2/5","3/10","1/2","4/9"],a:0,hint:"List the primes up to 10.",
 expl:"The primes are 2, 3, 5 and 7: 4/10 = 2/5."},
{lvl:2,sec:"S",type:"in",q:"A bag has 4 green, 6 yellow and 10 white counters. What is the probability of picking yellow, as a decimal?",ans:0.3,
 expl:"6 yellow out of 20 counters: 6/20 = 0.3."},
{lvl:2,sec:"S",type:"order",q:"Put these events in order from least likely to most likely.",
 items:["rolling a 6 on a fair die","flipping heads on a coin","picking red from 3 red and 1 blue","rolling a number under 7 on a die"],
 ansOrder:["rolling a 6 on a fair die","flipping heads on a coin","picking red from 3 red and 1 blue","rolling a number under 7 on a die"],
 expl:"The probabilities are 1/6, 1/2, 3/4 and 1 (certain)."},
{lvl:3,sec:"S",type:"in",q:"Arjun has a bag of 12 marbles: 5 red and the rest blue. How many blue marbles must he add so that the probability of red becomes 1/4?",ans:8,
 hint:"The red count stays 5; the total must become 4 times that.",
 expl:"For P(red) = 1/4 the total must be 4 × 5 = 20 marbles. 20 − 12 = 8 blue marbles are added."},
{lvl:3,sec:"S",type:"in",q:"A two-digit number from 10 to 99 is chosen at random. What is the probability its two digits are the same, as a decimal?",ans:0.1,
 hint:"How many two-digit numbers are there? How many like 11, 22, ...?",
 expl:"There are 90 two-digit numbers, and 9 of them (11, 22, ..., 99) have equal digits: 9/90 = 0.1."},
{lvl:3,sec:"S",type:"mc",q:"A fair 6-sided die is rolled. Which event has probability exactly 1/3?",
 opts:["rolling a multiple of 3","rolling a number less than 4","rolling a 3","rolling more than 2"],a:0,
 expl:"Multiples of 3 are 3 and 6: 2/6 = 1/3. The others are 3/6, 1/6 and 4/6."},
{lvl:3,sec:"S",type:"in",q:"A bag has only red and blue counters. The probability of red is 0.4 and there are 18 blue counters. How many red counters are there?",ans:12,
 hint:"Blue must be 0.6 of the total.",expl:"Blue is 1 − 0.4 = 0.6 of the total, so total = 18 ÷ 0.6 = 30. Red = 30 − 18 = 12."}
],

"g4-compl": [
{sec:"S",type:"mc",q:"The probability of rain tomorrow is 0.3. What is the probability of no rain?",mono:true,opts:["0.7","0.3","0.6","1.3"],a:0,
 expl:"An event and its complement add to 1: 1 − 0.3 = 0.7."},
{sec:"S",type:"in",q:"The probability of winning a game is 0.25. What is the probability of not winning, as a decimal?",ans:0.75,
 expl:"1 − 0.25 = 0.75."},
{sec:"S",type:"mc",q:"The complement of 'rolling a 6' on a die is ...",
 opts:["rolling 1, 2, 3, 4 or 5","rolling a 1","rolling an even number","rolling a 6 twice"],a:0,
 expl:"The complement is everything that is not a 6, which is rolling 1, 2, 3, 4 or 5."},
{sec:"S",type:"mc",q:"The probabilities of an event and its complement always add up to ...",mono:true,opts:["1","0","2","1/2"],a:0,
 expl:"Either the event happens or it does not, so the two probabilities cover everything and sum to 1."},
{lvl:2,sec:"S",type:"in",q:"A spinner lands on red with probability 3/8. What is the probability of not red, as a decimal?",ans:0.625,
 hint:"Find 5/8 as a decimal.",expl:"1 − 3/8 = 5/8 = 0.625."},
{lvl:2,sec:"S",type:"mc",q:"A bag has 20 marbles and 7 are green. What is the probability of picking a marble that is not green?",mono:true,
 opts:["13/20","7/20","7/13","1/20"],a:0,
 expl:"20 − 7 = 13 marbles are not green: 13/20."},
{lvl:2,sec:"S",type:"in",q:"A 10-sided die is numbered 1 to 10. What is the probability of NOT rolling a multiple of 5, as a decimal?",ans:0.8,
 expl:"The multiples of 5 are 5 and 10, probability 2/10. The complement is 8/10 = 0.8."},
{lvl:2,sec:"S",type:"multi",q:"Select EVERY pair of events that are complements when rolling a fair 6-sided die.",
 opts:["even / odd","less than 3 / 3 or more","a 6 / a 1","prime / composite","multiple of 3 / not a multiple of 3"],aMulti:[0,1,4],
 expl:"Complements cover all outcomes with no overlap. 'A 6 / a 1' misses 2 to 5, and 'prime / composite' misses the number 1."},
{lvl:3,sec:"S",type:"in",q:"Two coins are flipped. What is the probability of getting at least one head, as a decimal?",ans:0.75,
 hint:"First find the probability of no heads at all.",expl:"P(no heads) = P(tails, tails) = 1/4. So P(at least one head) = 1 − 1/4 = 0.75."},
{lvl:3,sec:"S",type:"in",q:"Sofia spins a spinner with 5 equal sections twice. What is the probability the two spins are different, as a decimal?",ans:0.8,
 hint:"Use the complement: both spins the same.",expl:"P(same) = 5/25 = 0.2, since 5 of the 25 pairs match. P(different) = 1 − 0.2 = 0.8."},
{lvl:3,sec:"S",type:"in",q:"A bag has red, blue and green counters only. P(red) = 0.35 and P(blue) = 0.4. What is P(green), as a decimal?",ans:0.25,
 expl:"Red or blue has probability 0.35 + 0.4 = 0.75. Green is the complement: 1 − 0.75 = 0.25."},
{lvl:3,sec:"S",type:"mc",q:"Three coins are flipped. What is the probability that at least one shows tails?",mono:true,opts:["7/8","1/8","3/8","1/2"],a:0,
 hint:"What is the only way to get no tails?",expl:"The only way with no tails is HHH, probability 1/8. So P(at least one tail) = 1 − 1/8 = 7/8."}
]
};
