/* Grade 4 core: multiplicative comparison, multi-step problems, factors and
   primes, patterns, place value to a million, multi-digit multiplication and
   division, fractions and decimals, measurement, line plots, angles, lines,
   classifying figures and symmetry. */
export const G4_CORE_BANKS = {
"g4-multcomp": [
{sec:"N",type:"in",q:"A pencil costs 3 dollars. A book costs 4 times as much. How much does the book cost, in dollars?",ans:12,
 hint:"'Times as much' means multiply.",expl:"4 times as much as 3 is 4 × 3 = 12 dollars."},
{sec:"N",type:"mc",q:"Which statement matches 24 = 6 × 4?",
 opts:["24 is 6 times as many as 4","24 is 6 more than 4","4 is 6 times as many as 24","24 is 4 more than 6"],a:0,
 expl:"6 × 4 = 24 says that 24 is 6 groups of 4, so 24 is 6 times as many as 4."},
{sec:"N",type:"in",q:"Amara has 5 marbles. Kenji has 3 times as many. How many marbles does Kenji have?",ans:15,
 expl:"3 times as many as 5 is 3 × 5 = 15 marbles."},
{sec:"N",type:"mc",q:"Which equation says '35 is 7 times as many as 5'?",mono:true,
 opts:["35 = 7 × 5","35 = 7 + 5","35 − 7 = 5","5 = 7 × 35"],a:0,
 expl:"'7 times as many as 5' is 7 × 5, and that equals 35."},
{lvl:2,sec:"N",type:"in",q:"A tree is 36 feet tall. It is 4 times as tall as a fence. How tall is the fence, in feet?",ans:9,
 hint:"You know the bigger number this time, so use division.",
 expl:"The tree is 4 fences tall, so the fence is 36 ÷ 4 = 9 feet."},
{lvl:2,sec:"N",type:"in",q:"Priya scored 8 points. Mateo scored 40 points. How many times as many points did Mateo score?",ans:5,
 hint:"What times 8 makes 40?",expl:"40 ÷ 8 = 5, so Mateo scored 5 times as many points."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY statement that is true about 6 × 7 = 42.",
 opts:["42 is 6 times as many as 7","42 is 7 times as many as 6","42 is 6 more than 7","7 is 6 times as many as 42"],aMulti:[0,1],
 expl:"6 × 7 and 7 × 6 both make 42, so 42 is 6 times 7 and also 7 times 6. Adding 6 to 7 gives 13, not 42."},
{lvl:3,sec:"N",type:"in",q:"Zainab is 3 times as old as Lior. Their ages add up to 24. How old is Zainab?",ans:18,
 hint:"Lior's age plus 3 lots of Lior's age makes 4 lots.",
 expl:"Zainab's age is 3 parts and Lior's is 1 part, so 4 parts = 24 and 1 part = 6. Zainab is 3 × 6 = 18."},
{lvl:3,sec:"N",type:"in",q:"A red rope is 4 times as long as a blue rope, and it is 27 m longer than the blue rope. How long is the red rope, in metres?",ans:36,
 hint:"The difference is 3 lots of the blue rope.",
 expl:"Red is 4 parts, blue is 1 part, so the difference of 27 m is 3 parts. One part is 9 m and the red rope is 4 × 9 = 36 m."}
],

"g4-multistep": [
{sec:"N",type:"in",q:"Tomas buys 3 packs of 8 stickers and gives away 5. How many stickers does he keep?",ans:19,
 hint:"Find the total first, then subtract.",expl:"3 × 8 = 24 stickers, and 24 − 5 = 19 kept."},
{sec:"N",type:"in",q:"A box holds 6 eggs. Aisha buys 4 boxes and uses 9 eggs for baking. How many eggs are left?",ans:15,
 expl:"4 × 6 = 24 eggs, and 24 − 9 = 15 eggs left."},
{sec:"N",type:"mc",q:"Wei has $20. He buys 3 notebooks at $4 each. Which expression shows how much money he has left?",mono:true,
 opts:["20 − 3 × 4","20 − 3 + 4","20 × 3 − 4","3 × 4 − 20"],a:0,
 expl:"The notebooks cost 3 × 4 dollars, and that is taken away from 20: 20 − 3 × 4 = 8."},
{sec:"N",type:"in",q:"A school orders 5 boxes of 12 pens and 2 boxes of 10 pencils. How many items is that in total?",ans:80,
 expl:"5 × 12 = 60 pens and 2 × 10 = 20 pencils, so 60 + 20 = 80 items."},
{lvl:2,sec:"N",type:"in",q:"Nadia saves $7 each week for 6 weeks, then spends $15. How many dollars does she have left?",ans:27,
 hint:"Work out the savings before the spending.",expl:"6 × 7 = 42 dollars saved, and 42 − 15 = 27 dollars left."},
{lvl:2,sec:"N",type:"in",q:"A bus has 9 rows of 4 seats. 21 seats are taken. How many seats are empty?",ans:15,
 expl:"9 × 4 = 36 seats altogether, and 36 − 21 = 15 are empty."},
{lvl:2,sec:"N",type:"mc",q:"To find the change from $50 after buying 4 tickets at $9 each, which should you work out first?",mono:true,
 opts:["4 × 9","50 − 4","50 − 9","50 × 4"],a:0,
 expl:"You need the cost of the tickets before you can subtract it, so 4 × 9 = 36 comes first. Then 50 − 36 = 14."},
{lvl:3,sec:"N",type:"in",q:"Ingrid has 100 beads. She makes 6 bracelets with 12 beads each, then shares the rest equally into 4 bags. How many beads go in each bag?",ans:7,
 hint:"Three steps: multiply, subtract, divide.",
 expl:"6 × 12 = 72 beads are used, leaving 100 − 72 = 28. Then 28 ÷ 4 = 7 beads in each bag."},
{lvl:3,sec:"N",type:"in",q:"Ravi wants a game that costs $56. He has $20 and earns $6 each week. How many weeks until he can buy it?",ans:6,
 hint:"How much more does he need?",
 expl:"He still needs 56 − 20 = 36 dollars. At 6 dollars a week that takes 36 ÷ 6 = 6 weeks."}
],

"g4-factorpair": [
{sec:"T",type:"mc",q:"Which is a factor pair of 12?",mono:true,opts:["3 and 4","5 and 7","2 and 5","3 and 5"],a:0,
 expl:"A factor pair multiplies to make the number: 3 × 4 = 12."},
{sec:"T",type:"in",q:"How many factors does 10 have?",ans:4,hint:"List every number that divides into 10 exactly.",
 expl:"The factors of 10 are 1, 2, 5 and 10, so it has 4 factors."},
{sec:"T",type:"mc",q:"Which number is prime?",mono:true,opts:["7","9","15","21"],a:0,
 expl:"7 has only the factors 1 and 7. 9 = 3 × 3, 15 = 3 × 5 and 21 = 3 × 7 have extra factors."},
{sec:"T",type:"mc",q:"What is a composite number?",
 opts:["A number with more than two factors","A number with exactly two factors","Any odd number","Any number greater than 10"],a:0,
 expl:"A composite number has more than two factors, like 6 (1, 2, 3, 6). A prime has exactly two."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number that is a factor of 24.",mono:true,opts:["3","6","8","5","9"],aMulti:[0,1,2],
 expl:"24 = 3 × 8 = 6 × 4, so 3, 6 and 8 are factors. 24 ÷ 5 and 24 ÷ 9 leave remainders."},
{lvl:2,sec:"T",type:"in",q:"What is the smallest prime number greater than 20?",ans:23,hint:"Check 21 and 22 first.",
 expl:"21 = 3 × 7 and 22 = 2 × 11, but 23 has no factors except 1 and itself. The answer is 23."},
{lvl:2,sec:"T",type:"mc",q:"Which number is composite?",mono:true,opts:["51","53","59","61"],a:0,
 expl:"51 = 3 × 17, so it is composite. 53, 59 and 61 are all prime."},
{lvl:2,sec:"T",type:"in",q:"How many different factor pairs does 36 have? Count 6 × 6 as one pair.",ans:5,
 hint:"Start with 1 × 36 and work upwards.",
 expl:"The pairs are 1 × 36, 2 × 18, 3 × 12, 4 × 9 and 6 × 6. That is 5 pairs."},
{lvl:3,sec:"T",type:"in",q:"I am an odd two-digit number less than 30. I am a multiple of 7 and I have exactly 4 factors. What am I?",ans:21,
 hint:"List the two-digit multiples of 7 below 30, then check each clue.",
 expl:"The multiples of 7 from 10 to 29 are 14, 21 and 28. Only 21 is odd, and its factors are 1, 3, 7, 21 — exactly four. The number is 21."},
{lvl:3,sec:"T",type:"in",q:"How many prime numbers are there between 30 and 50?",ans:5,
 hint:"Skip every even number and every multiple of 3 or 5.",
 expl:"The primes are 31, 37, 41, 43 and 47, so there are 5."}
],

"g4-seq": [
{sec:"L",type:"in",q:"What is the next number: 4, 8, 12, 16, __?",ans:20,expl:"Each number is 4 more than the last, so 16 + 4 = 20."},
{sec:"L",type:"in",q:"The rule is 'add 6', starting at 5. What is the 4th number in the pattern?",ans:23,
 hint:"Write out the first few terms.",expl:"5, 11, 17, 23 — the 4th number is 23."},
{sec:"L",type:"mc",q:"What is the rule for the pattern 50, 45, 40, 35?",opts:["Subtract 5","Add 5","Subtract 10","Divide by 5"],a:0,
 expl:"Each number is 5 less than the one before, so the rule is subtract 5."},
{sec:"L",type:"mc",q:"A pattern goes triangle, square, square, circle, triangle, square, square, circle, ... What is the 7th shape?",
 opts:["square","triangle","circle","hexagon"],a:0,
 expl:"The unit is 4 shapes long. The 5th is triangle, the 6th and 7th are squares, so the 7th shape is a square."},
{lvl:2,sec:"L",type:"in",q:"A pattern starts at 3 and doubles each time: 3, 6, 12, ... What is the 6th number?",ans:96,
 hint:"Keep doubling.",expl:"3, 6, 12, 24, 48, 96 — the 6th number is 96."},
{lvl:2,sec:"L",type:"mc",q:"The rule is 'add 4' starting at 1: 1, 5, 9, 13, ... Which is true about every number in the pattern?",
 opts:["They are all odd","They are all even","They are all multiples of 4","They all end in 1 or 5"],a:0,
 expl:"Adding 4 to an odd number gives another odd number, so every term is odd. The 3rd term, 9, shows they do not all end in 1 or 5."},
{lvl:2,sec:"L",type:"in",q:"What is the 10th number in the pattern 7, 14, 21, 28, ...?",ans:70,
 hint:"The nth number is n lots of 7.",expl:"The pattern is the multiples of 7, so the 10th is 10 × 7 = 70."},
{lvl:2,sec:"L",type:"order",q:"These numbers come from the pattern 'start at 100, subtract 15'. Put them in order from largest to smallest.",
 items:["55","85","100","70"],ansOrder:["100","85","70","55"],
 expl:"The pattern is 100, 85, 70, 55, and that is already largest to smallest."},
{lvl:3,sec:"L",type:"in",q:"A dot pattern grows 1, 3, 6, 10, ... where each step adds one more dot than the step before. What is the 8th number?",ans:36,
 hint:"The jumps are 2, 3, 4, 5, ...",
 expl:"Add 5, 6, 7, 8 to keep going: 15, 21, 28, 36. The 8th number is 36."},
{lvl:3,sec:"L",type:"in",q:"Hana builds towers by a rule: tower 1 has 2 blocks, tower 2 has 5, tower 3 has 8. How many blocks are in tower 12?",ans:35,
 hint:"How many times is 3 added to get from tower 1 to tower 12?",
 expl:"Each tower has 3 more blocks. Tower 12 is 11 steps after tower 1, so it has 2 + 11 × 3 = 35 blocks."}
],

"g4-placemil": [
{sec:"N",type:"in",q:"What is the value of the digit 7 in 274,315?",ans:70000,
 hint:"Which place is the 7 in?",expl:"The 7 is in the ten-thousands place, so it is worth 70,000."},
{sec:"N",type:"mc",q:"How is 305,012 written in words?",
 opts:["Three hundred five thousand, twelve","Three hundred fifty thousand, twelve","Thirty-five thousand, twelve","Three million, five thousand, twelve"],a:0,
 expl:"305 thousands and 12 ones: three hundred five thousand, twelve."},
{sec:"N",type:"in",q:"Write 600,000 + 40,000 + 2,000 + 300 + 9 as one number.",ans:642309,
 expl:"Put each digit in its place: 642,309. Notice the tens place is 0."},
{sec:"N",type:"mc",q:"Which digit is in the ten-thousands place of 483,927?",mono:true,opts:["8","4","3","9"],a:0,
 expl:"From the right: 7 ones, 2 tens, 9 hundreds, 3 thousands, 8 ten-thousands. The digit is 8."},
{lvl:2,sec:"N",type:"in",q:"Round 456,789 to the nearest ten thousand.",ans:460000,
 hint:"Look at the thousands digit to decide.",expl:"The thousands digit is 6, which is 5 or more, so round up: 460,000."},
{lvl:2,sec:"N",type:"mc",q:"The 5 in 500,000 is worth how many times the 5 in 50,000?",mono:true,opts:["10","100","5","1,000"],a:0,
 expl:"Each place to the left is 10 times bigger: 500,000 = 10 × 50,000."},
{lvl:2,sec:"N",type:"order",q:"Put these numbers in order from smallest to largest.",
 items:["209,999","210,001","98,765","1,000,000"],ansOrder:["98,765","209,999","210,001","1,000,000"],
 expl:"98,765 has only five digits, so it is smallest. 209,999 is just under 210,000, then 210,001, and 1,000,000 has seven digits."},
{lvl:3,sec:"N",type:"in",q:"What is the largest six-digit number you can make using each of the digits 3, 0, 8, 5, 1, 9 exactly once?",ans:985310,
 hint:"Put the biggest digit in the biggest place.",
 expl:"Arrange the digits from largest to smallest: 985,310."},
{lvl:3,sec:"N",type:"in",q:"What is the smallest whole number that rounds to 730,000 when rounded to the nearest ten thousand?",ans:725000,
 hint:"Halfway rounds up.",expl:"Numbers from 725,000 up to 734,999 round to 730,000, so the smallest is 725,000."},
{lvl:3,sec:"N",type:"mc",q:"Which comparison is correct?",mono:true,
 opts:["199,999 < 200,001","310,000 < 301,000","45,000 > 450,000","999,999 > 1,000,000"],a:0,
 expl:"199,999 is less than 200,001. In the others the bigger number is on the wrong side: 310,000 > 301,000, 45,000 < 450,000 and 999,999 < 1,000,000."}
],

"g4-multidig": [
{sec:"N",type:"in",q:"23 × 4 = ?",ans:92,expl:"20 × 4 = 80 and 3 × 4 = 12, so 23 × 4 = 92."},
{sec:"N",type:"in",q:"What is 40 × 30?",ans:1200,hint:"4 × 3, then add the zeros.",expl:"4 × 3 = 12, and 10 × 10 = 100 more, so 40 × 30 = 1,200."},
{sec:"N",type:"in",q:"156 × 3 = ?",ans:468,expl:"100 × 3 = 300, 50 × 3 = 150, 6 × 3 = 18. Total 300 + 150 + 18 = 468."},
{sec:"N",type:"mc",q:"Which is a correct way to break apart 47 × 6?",mono:true,
 opts:["40 × 6 + 7 × 6","40 + 6 × 7","47 + 6 × 6","4 × 6 + 7 × 6"],a:0,
 expl:"Split 47 into 40 + 7 and multiply each part by 6: 40 × 6 + 7 × 6 = 240 + 42 = 282."},
{lvl:2,sec:"N",type:"in",q:"34 × 26 = ?",ans:884,hint:"Do 34 × 20 and 34 × 6 separately.",
 expl:"34 × 20 = 680 and 34 × 6 = 204, so 34 × 26 = 680 + 204 = 884."},
{lvl:2,sec:"N",type:"in",q:"A crate holds 48 apples. How many apples are in 25 crates?",ans:1200,
 expl:"48 × 25: 48 × 100 = 4,800, and a quarter of that is 1,200. So 25 crates hold 1,200 apples."},
{lvl:2,sec:"N",type:"mc",q:"Estimate 62 × 38 by rounding each number to the nearest ten.",opts:["2,400","1,800","3,000","2,000"],a:0,
 expl:"62 rounds to 60 and 38 rounds to 40, so 60 × 40 = 2,400."},
{lvl:2,sec:"N",type:"in",q:"1,234 × 5 = ?",ans:6170,expl:"1,000 × 5 = 5,000, 200 × 5 = 1,000, 34 × 5 = 170. Total 6,170."},
{lvl:3,sec:"N",type:"in",q:"A theatre has 28 rows of 32 seats. On Saturday 750 tickets were sold. How many seats were empty?",ans:146,
 hint:"Find the total number of seats first.",
 expl:"28 × 32 = 896 seats. 896 − 750 = 146 empty seats."},
{lvl:3,sec:"N",type:"in",q:"Sofia's school bought 15 boxes of 24 pencils and 12 boxes of 36 pencils. How many pencils is that altogether?",ans:792,
 hint:"Two multiplications, then add.",
 expl:"15 × 24 = 360 and 12 × 36 = 432. Together 360 + 432 = 792 pencils."},
{lvl:3,sec:"N",type:"multi",q:"Select EVERY product that is greater than 1,000.",mono:true,
 opts:["45 × 25","19 × 52","33 × 31","24 × 41"],aMulti:[0,2],
 expl:"45 × 25 = 1,125 and 33 × 31 = 1,023 are over 1,000. 19 × 52 = 988 and 24 × 41 = 984 are just under."}
],

"g4-divide": [
{sec:"N",type:"in",q:"What is the remainder when 17 is divided by 5?",ans:2,hint:"How many fives fit, and what is left?",
 expl:"3 × 5 = 15, and 17 − 15 = 2. The remainder is 2."},
{sec:"N",type:"in",q:"84 ÷ 4 = ?",ans:21,expl:"80 ÷ 4 = 20 and 4 ÷ 4 = 1, so 84 ÷ 4 = 21."},
{sec:"N",type:"mc",q:"Which division has a remainder of 1?",mono:true,opts:["25 ÷ 4","24 ÷ 4","26 ÷ 2","27 ÷ 3"],a:0,
 expl:"25 ÷ 4 = 6 remainder 1. The others divide exactly: 24 ÷ 4 = 6, 26 ÷ 2 = 13, 27 ÷ 3 = 9."},
{sec:"N",type:"in",q:"What is 96 ÷ 8?",ans:12,expl:"8 × 12 = 96, so 96 ÷ 8 = 12."},
{lvl:2,sec:"N",type:"in",q:"What is the remainder when 125 is divided by 6?",ans:5,
 hint:"Find the biggest multiple of 6 that is not more than 125.",expl:"6 × 20 = 120, and 125 − 120 = 5. The remainder is 5."},
{lvl:2,sec:"N",type:"in",q:"Yusuf shares 74 stickers equally among 6 friends. How many stickers does each friend get?",ans:12,
 expl:"6 × 12 = 72, so each friend gets 12 stickers and 2 are left over."},
{lvl:2,sec:"N",type:"mc",q:"A bus holds 40 students. 175 students are going on a trip. How many buses are needed?",
 opts:["5","4","4 remainder 35","6"],a:0,
 expl:"175 ÷ 40 = 4 remainder 35. Four buses leave 35 students behind, so a 5th bus is needed."},
{lvl:2,sec:"N",type:"in",q:"348 ÷ 4 = ?",ans:87,expl:"320 ÷ 4 = 80 and 28 ÷ 4 = 7, so 348 ÷ 4 = 87."},
{lvl:3,sec:"N",type:"in",q:"Diego has 100 marbles and puts 7 in each bag. After filling as many bags as he can, he shares the leftover marbles equally between his 2 cousins. How many marbles does each cousin get?",ans:1,
 hint:"Find the remainder first.",
 expl:"100 ÷ 7 = 14 remainder 2, so 2 marbles are left over. Shared between 2 cousins, each gets 1."},
{lvl:3,sec:"N",type:"in",q:"A number divided by 9 gives 14 remainder 5. What is the number?",ans:131,
 hint:"Work backwards: multiply, then add the remainder.",expl:"9 × 14 = 126, and 126 + 5 = 131."},
{lvl:3,sec:"N",type:"mc",q:"Femi has 50 muffins and packs them 8 to a box. Which sentence is correct?",
 opts:["6 full boxes with 2 muffins left over","6 full boxes with 8 muffins left over","7 full boxes with 6 muffins left over","5 full boxes with 10 muffins left over"],a:0,
 expl:"50 ÷ 8 = 6 remainder 2: six full boxes use 48 muffins and 2 are left over. A remainder can never be as big as the divisor."}
],

"g4-fracadd": [
{sec:"F",type:"mc",q:"What is 2/5 + 1/5?",mono:true,opts:["3/5","3/10","2/10","1/5"],a:0,
 expl:"Add the numerators and keep the denominator: 2/5 + 1/5 = 3/5."},
{sec:"F",type:"mc",q:"What is 7/8 − 3/8?",mono:true,opts:["4/8","4/16","10/8","3/8"],a:0,
 expl:"7 eighths take away 3 eighths leaves 4 eighths: 4/8."},
{sec:"F",type:"mc",q:"Which sum equals 1 whole?",mono:true,opts:["3/6 + 3/6","1/6 + 2/6","4/6 + 4/6","3/6 + 2/6"],a:0,
 expl:"3/6 + 3/6 = 6/6, and six sixths make one whole."},
{sec:"F",type:"in",q:"3/8 + 4/8 is a number of eighths. How many eighths?",ans:7,
 expl:"3 eighths plus 4 eighths is 7 eighths, so the answer is 7."},
{lvl:2,sec:"F",type:"mc",q:"Mei ate 3/8 of a pizza and Leila ate 2/8. How much of the pizza is left?",mono:true,
 opts:["3/8","5/8","1/8","5/16"],a:0,
 expl:"Together they ate 3/8 + 2/8 = 5/8. The whole pizza is 8/8, so 8/8 − 5/8 = 3/8 is left."},
{lvl:2,sec:"F",type:"mc",q:"Which is another way to write 5/6?",mono:true,opts:["1/6 + 4/6","1/6 + 3/6","5/6 + 1/6","2/6 + 2/6"],a:0,
 expl:"1/6 + 4/6 = 5/6. The others make 4/6, 6/6 and 4/6."},
{lvl:2,sec:"F",type:"in",q:"Arjun walks 3/10 km to school and 3/10 km back. What is the total distance in km, as a decimal?",ans:0.6,
 hint:"3 tenths plus 3 tenths.",expl:"3/10 + 3/10 = 6/10, which is 0.6 km."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY expression that equals 4/7.",mono:true,
 opts:["1/7 + 3/7","6/7 − 2/7","2/7 + 3/7","5/7 − 2/7"],aMulti:[0,1],
 expl:"1/7 + 3/7 = 4/7 and 6/7 − 2/7 = 4/7. The others give 5/7 and 3/7."},
{lvl:3,sec:"F",type:"mc",q:"A recipe needs 5/4 cups of flour. Noor has 3/4 of a cup. How much more flour does she need?",mono:true,
 opts:["2/4 cup","2 cups","8/4 cups","1/4 cup"],a:0,
 expl:"5/4 − 3/4 = 2/4, so she needs 2/4 (half) a cup more."},
{lvl:3,sec:"F",type:"in",q:"A tank was 9/10 full. Elias used 4/10 of a tank on Monday and 2/10 on Tuesday. What fraction of the tank is left? Type the top number of the fraction out of 10.",ans:3,
 hint:"Subtract both amounts from 9/10.",
 expl:"9/10 − 4/10 − 2/10 = 3/10 of the tank is left. The top number is 3."}
],

"g4-mixed": [
{sec:"F",type:"mc",q:"Which mixed number equals 7/4?",mono:true,opts:["1 3/4","1 1/4","2 1/4","7 1/4"],a:0,
 expl:"7/4 is 4/4 + 3/4, and 4/4 is one whole, so 7/4 = 1 3/4."},
{sec:"F",type:"in",q:"Write 2 3/4 as an improper fraction. What is the top number (numerator)?",ans:11,
 hint:"How many quarters are in 2 wholes?",expl:"2 wholes are 8/4, plus 3/4 makes 11/4. The top number is 11."},
{sec:"F",type:"mc",q:"What is 1 2/5 + 2 1/5?",mono:true,opts:["3 3/5","3 2/5","3 3/10","4"],a:0,
 expl:"Add the wholes: 1 + 2 = 3. Add the fractions: 2/5 + 1/5 = 3/5. The total is 3 3/5."},
{sec:"F",type:"mc",q:"Which is the same as 3 1/3?",mono:true,opts:["10/3","4/3","9/3","3/3"],a:0,
 expl:"3 wholes are 9/3, plus 1/3 makes 10/3."},
{lvl:2,sec:"F",type:"mc",q:"What is 4 1/6 − 1 5/6?",mono:true,opts:["2 2/6","3 4/6","2 4/6","3 2/6"],a:0,
 expl:"Change to sixths: 4 1/6 = 25/6 and 1 5/6 = 11/6. 25/6 − 11/6 = 14/6 = 2 2/6."},
{lvl:2,sec:"F",type:"in",q:"Chioma runs 2 1/2 km on Monday and 1 1/2 km on Tuesday. How far does she run in total, in km?",ans:4,
 expl:"2 + 1 = 3 wholes and 1/2 + 1/2 = 1 more whole, so the total is 4 km."},
{lvl:2,sec:"F",type:"order",q:"Put these numbers in order from smallest to largest.",
 items:["7/3","2 1/2","1 3/4","11/4"],ansOrder:["1 3/4","7/3","2 1/2","11/4"],
 expl:"7/3 = 2 1/3 and 11/4 = 2 3/4. So the order is 1 3/4, 2 1/3, 2 1/2, 2 3/4."},
{lvl:3,sec:"F",type:"in",q:"Amara cuts 3 1/4 metres of ribbon from a 5-metre roll. How many metres are left? Give the answer as a decimal.",ans:1.75,
 hint:"5 − 3 1/4, and 1/4 is 0.25.",expl:"5 − 3 = 2, then take away another 1/4: 2 − 1/4 = 1 3/4, which is 1.75 m."},
{lvl:3,sec:"F",type:"mc",q:"A jug holds 2 3/8 litres. Kenji pours in 1 7/8 litres more. How much is in the jug now?",mono:true,
 opts:["4 2/8 litres","3 2/8 litres","4 1/8 litres","4 4/8 litres"],a:0,
 expl:"2 + 1 = 3 wholes and 3/8 + 7/8 = 10/8 = 1 2/8. So the jug holds 3 + 1 2/8 = 4 2/8 litres."},
{lvl:3,sec:"F",type:"in",q:"Three boards are each 1 3/4 feet long. Laid end to end, how long are they in feet? Give a decimal.",ans:5.25,
 hint:"Three wholes and three quarters-of-three.",
 expl:"3 × 1 = 3 and 3 × 3/4 = 9/4 = 2 1/4. Together that is 5 1/4 feet, which is 5.25."}
],

"g4-fracmultw": [
{sec:"F",type:"mc",q:"What is 3 × 1/5?",mono:true,opts:["3/5","1/15","3/15","4/5"],a:0,
 expl:"3 × 1/5 means 1/5 + 1/5 + 1/5 = 3/5."},
{sec:"F",type:"in",q:"What is 4 × 1/2? Type a whole number.",ans:2,expl:"Four halves make 4/2 = 2 wholes."},
{sec:"F",type:"mc",q:"Which is the same as 2/7 + 2/7 + 2/7?",mono:true,opts:["3 × 2/7","2 × 2/7","3 × 7/2","6/21"],a:0,
 expl:"Three lots of 2/7 is 3 × 2/7, which equals 6/7."},
{sec:"F",type:"in",q:"What is 6 × 1/3? Type a whole number.",ans:2,expl:"6 × 1/3 = 6/3 = 2."},
{lvl:2,sec:"F",type:"mc",q:"What is 5 × 3/4?",mono:true,opts:["15/4","15/20","8/4","3/20"],a:0,
 expl:"Multiply the whole number by the numerator: 5 × 3/4 = 15/4, which is 3 3/4."},
{lvl:2,sec:"F",type:"in",q:"Each of 8 friends drinks 3/4 of a litre of juice. How many litres is that altogether?",ans:6,
 hint:"8 × 3 quarters.",expl:"8 × 3/4 = 24/4 = 6 litres."},
{lvl:2,sec:"F",type:"in",q:"Priya runs 2/5 of a mile each day for 5 days. How many miles does she run in total?",ans:2,
 expl:"5 × 2/5 = 10/5 = 2 miles."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY product that is a whole number.",mono:true,
 opts:["4 × 3/4","6 × 2/3","5 × 1/2","3 × 2/5"],aMulti:[0,1],
 expl:"4 × 3/4 = 12/4 = 3 and 6 × 2/3 = 12/3 = 4 are whole. 5 × 1/2 = 5/2 and 3 × 2/5 = 6/5 are not."},
{lvl:3,sec:"F",type:"in",q:"A recipe uses 2/3 of a cup of sugar. Mateo makes 6 batches. How many cups of sugar does he need?",ans:4,
 hint:"6 lots of 2 thirds.",expl:"6 × 2/3 = 12/3 = 4 cups."},
{lvl:3,sec:"F",type:"mc",q:"Zainab walks 3/8 km to the park 5 times in a week. How far does she walk in the week?",mono:true,
 opts:["1 7/8 km","15/40 km","5 3/8 km","1 5/8 km"],a:0,
 expl:"5 × 3/8 = 15/8. Since 8/8 is one whole, 15/8 = 1 7/8 km."},
{lvl:3,sec:"F",type:"in",q:"Lior pours 7 cups of 3/4 of a litre each into a jug. How many litres are in the jug? Give a decimal.",ans:5.25,
 hint:"Find the number of quarters, then change to a decimal.",
 expl:"7 × 3/4 = 21/4 = 5 1/4 litres, and 1/4 = 0.25, so 5.25 litres."}
],

"g4-decnot": [
{sec:"F",type:"mc",q:"Write 7/10 as a decimal.",mono:true,opts:["0.7","0.07","7.0","0.71"],a:0,
 expl:"7 tenths is written with the 7 in the tenths place: 0.7."},
{sec:"F",type:"in",q:"Write 43/100 as a decimal.",ans:0.43,expl:"43 hundredths is 4 tenths and 3 hundredths: 0.43."},
{sec:"F",type:"mc",q:"Which fraction equals 0.09?",mono:true,opts:["9/100","9/10","90/100","9/1000"],a:0,
 expl:"0.09 has 0 tenths and 9 hundredths, so it is 9/100."},
{sec:"F",type:"in",q:"What is 3/10 + 4/100 as a decimal?",ans:0.34,hint:"3 tenths and 4 hundredths.",
 expl:"3/10 = 0.3 and 4/100 = 0.04, so together 0.34."},
{lvl:2,sec:"F",type:"in",q:"Write 2 and 5/100 as a decimal.",ans:2.05,hint:"There are no tenths.",
 expl:"2 wholes, 0 tenths and 5 hundredths: 2.05."},
{lvl:2,sec:"F",type:"mc",q:"Which is the same as 0.6?",mono:true,opts:["60/100","6/100","60/10","6/1000"],a:0,
 expl:"0.6 = 6/10, and 6/10 = 60/100 because 6 tenths is 60 hundredths."},
{lvl:2,sec:"F",type:"in",q:"What is the value of the digit 8 in 0.85? Give it as a decimal.",ans:0.8,
 expl:"The 8 is in the tenths place, so it is worth 8/10 = 0.8."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY value that is equal to 0.5.",mono:true,opts:["5/10","50/100","5/100","0.05"],aMulti:[0,1],
 expl:"0.5 is 5 tenths, which is 5/10 or 50/100. 5/100 and 0.05 are five hundredths."},
{lvl:3,sec:"F",type:"in",q:"Tomas has 3 dollars and 7 cents. Write this as a decimal number of dollars.",ans:3.07,
 hint:"A cent is one hundredth of a dollar.",expl:"7 cents is 7/100 of a dollar, so the amount is 3.07 dollars."},
{lvl:3,sec:"F",type:"mc",q:"Which decimal is exactly halfway between 0.3 and 0.4?",mono:true,opts:["0.35","0.7","0.34","0.5"],a:0,
 expl:"0.3 = 30/100 and 0.4 = 40/100. Halfway is 35/100 = 0.35."},
{lvl:3,sec:"F",type:"in",q:"Wei's number has a 2 in the ones place, a 0 in the tenths place and a 9 in the hundredths place. What is the number?",ans:2.09,
 hint:"Write the places in order: ones, tenths, hundredths.",expl:"2 ones, 0 tenths and 9 hundredths gives 2.09."}
],

"g4-deccomp": [
{sec:"F",type:"mc",q:"Which is greater: 0.5 or 0.45?",mono:true,opts:["0.5","0.45","They are equal"],a:0,
 expl:"0.5 = 0.50 = 50 hundredths, and 50 hundredths is more than 45 hundredths, so 0.5 is greater."},
{sec:"F",type:"mc",q:"Which symbol makes this true? 0.32 ___ 0.23",mono:true,opts:[">","<","="],a:0,
 expl:"Compare the tenths first: 3 tenths is more than 2 tenths, so 0.32 > 0.23."},
{sec:"F",type:"order",q:"Put these decimals in order from smallest to largest.",
 items:["0.7","0.07","0.77","0.17"],ansOrder:["0.07","0.17","0.7","0.77"],
 expl:"In hundredths they are 70, 7, 77 and 17. Smallest to largest: 0.07, 0.17, 0.7, 0.77."},
{sec:"F",type:"mc",q:"Which decimal is the smallest?",mono:true,opts:["0.09","0.9","0.19","0.91"],a:0,
 expl:"0.09 has 0 tenths, so it is smaller than the others, which all have at least 1 tenth."},
{lvl:2,sec:"F",type:"mc",q:"Which decimal is between 0.4 and 0.5?",mono:true,opts:["0.45","0.54","0.35","0.5"],a:0,
 expl:"0.45 is 45 hundredths, which sits between 40 and 50 hundredths."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY decimal that is greater than 0.6.",mono:true,opts:["0.61","0.7","0.59","0.06","0.60"],aMulti:[0,1],
 expl:"0.61 and 0.7 (which is 0.70) are both more than 0.60. 0.59 and 0.06 are less, and 0.60 is equal."},
{lvl:2,sec:"F",type:"order",q:"Order these decimals from largest to smallest.",
 items:["2.5","2.05","2.55","2.15"],ansOrder:["2.55","2.5","2.15","2.05"],
 expl:"Write them all with two decimal places: 2.50, 2.05, 2.55, 2.15. Largest first gives 2.55, 2.5, 2.15, 2.05."},
{lvl:2,sec:"F",type:"in",q:"How many hundredths must be added to 0.38 to make 0.4? Type the number of hundredths.",ans:2,
 hint:"0.4 is 40 hundredths.",expl:"0.4 = 0.40, and 40 − 38 = 2 hundredths."},
{lvl:3,sec:"F",type:"mc",q:"Nadia ran 100 m in 14.09 seconds, Ravi in 14.9 seconds and Ingrid in 14.19 seconds. Who was fastest?",
 opts:["Nadia","Ravi","Ingrid","They tied"],a:0,
 expl:"The fastest runner has the smallest time. 14.09 < 14.19 < 14.90, so Nadia was fastest."},
{lvl:3,sec:"F",type:"in",q:"What is the largest decimal with exactly two decimal places that is less than 0.5?",ans:0.49,
 hint:"Think in hundredths.",expl:"0.5 = 50 hundredths, so the largest number of hundredths below it is 49: 0.49."},
{lvl:3,sec:"F",type:"mc",q:"Which comparison is correct?",mono:true,opts:["0.8 > 0.79","0.3 > 0.30","0.25 > 0.5","0.09 > 0.1"],a:0,
 expl:"0.8 = 0.80, which is more than 0.79. 0.3 and 0.30 are equal, 0.25 < 0.5 and 0.09 < 0.10."}
],

"g4-units": [
{sec:"M",type:"in",q:"How many centimetres are in 3 metres?",ans:300,expl:"1 m = 100 cm, so 3 m = 3 × 100 = 300 cm."},
{sec:"M",type:"in",q:"How many minutes are in 2 hours?",ans:120,expl:"1 hour = 60 minutes, so 2 hours = 120 minutes."},
{sec:"M",type:"mc",q:"Which unit is best for measuring the mass of an elephant?",opts:["kilograms","grams","litres","centimetres"],a:0,
 expl:"Mass is measured in grams or kilograms, and an elephant is very heavy, so kilograms fit best."},
{sec:"M",type:"in",q:"How many grams are in 5 kilograms?",ans:5000,expl:"1 kg = 1,000 g, so 5 kg = 5,000 g."},
{lvl:2,sec:"M",type:"in",q:"A bottle holds 2 litres. How many millilitres is that?",ans:2000,
 expl:"1 litre = 1,000 mL, so 2 litres = 2,000 mL."},
{lvl:2,sec:"M",type:"in",q:"Sofia's lesson starts at 10:45 and lasts 50 minutes. How many minutes past 11:00 does it end?",ans:35,
 hint:"Go to 11:00 first, then add the rest.",
 expl:"From 10:45 to 11:00 is 15 minutes. The other 35 minutes take it to 11:35, so it ends 35 minutes past 11:00."},
{lvl:2,sec:"M",type:"order",q:"Order these lengths from shortest to longest.",
 items:["2 m","150 cm","1 km","30 cm"],ansOrder:["30 cm","150 cm","2 m","1 km"],
 expl:"Change to cm: 2 m = 200 cm and 1 km = 100,000 cm. So 30 cm, 150 cm, 2 m, 1 km."},
{lvl:2,sec:"M",type:"mc",q:"How many ounces are in 2 pounds?",mono:true,opts:["32","16","24","20"],a:0,
 expl:"1 pound = 16 ounces, so 2 pounds = 32 ounces."},
{lvl:3,sec:"M",type:"in",q:"Yusuf's rope is 4 m 25 cm long. He cuts off 180 cm. How long is the rope now, in cm?",ans:245,
 hint:"Change everything to centimetres first.",
 expl:"4 m 25 cm = 425 cm. 425 − 180 = 245 cm."},
{lvl:3,sec:"M",type:"in",q:"A jug holds 1.5 litres. How many 250 mL cups can it fill completely?",ans:6,
 hint:"1.5 litres is 1,500 mL.",expl:"1.5 L = 1,500 mL, and 1,500 ÷ 250 = 6 cups."},
{lvl:3,sec:"M",type:"mc",q:"Which is the greatest amount of time?",
 opts:["3 hours","150 minutes","10,000 seconds","2 hours 55 minutes"],a:0,
 expl:"3 hours = 180 minutes. 150 minutes is less, 2 hours 55 minutes is 175 minutes, and 10,000 seconds is about 167 minutes. So 3 hours is the longest."}
],

"g4-areaform": [
{sec:"G",type:"in",q:"A rectangle is 8 cm long and 5 cm wide. What is its area in square cm?",ans:40,
 expl:"Area = length × width = 8 × 5 = 40 square cm."},
{sec:"G",type:"in",q:"What is the perimeter of a rectangle 8 cm long and 5 cm wide, in cm?",ans:26,
 hint:"Add all four sides.",expl:"Perimeter = 2 × 8 + 2 × 5 = 16 + 10 = 26 cm."},
{sec:"G",type:"mc",q:"Which formula gives the perimeter of a rectangle with length L and width W?",mono:true,
 opts:["2 × L + 2 × W","L × W","L + W","4 × L"],a:0,
 expl:"A rectangle has two lengths and two widths, so the perimeter is 2 × L + 2 × W."},
{sec:"G",type:"in",q:"A square has sides of 9 m. What is its area in square metres?",ans:81,expl:"Area = 9 × 9 = 81 square metres."},
{lvl:2,sec:"G",type:"in",q:"A rectangle has an area of 54 square cm and a width of 6 cm. What is its length in cm?",ans:9,
 hint:"Area ÷ width.",expl:"54 ÷ 6 = 9, so the length is 9 cm."},
{lvl:2,sec:"G",type:"in",q:"A rectangle has a perimeter of 30 m and a length of 10 m. What is its width in m?",ans:5,
 hint:"Half the perimeter is one length plus one width.",
 expl:"Half of 30 is 15, which is length + width. 15 − 10 = 5, so the width is 5 m."},
{lvl:2,sec:"G",type:"mc",q:"A square has a perimeter of 36 cm. What is its area?",
 opts:["81 square cm","36 square cm","144 square cm","9 square cm"],a:0,
 expl:"Each side is 36 ÷ 4 = 9 cm, so the area is 9 × 9 = 81 square cm."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY rectangle with an area of 24 square units.",mono:true,
 opts:["6 by 4","12 by 2","8 by 4","5 by 5"],aMulti:[0,1],
 expl:"6 × 4 = 24 and 12 × 2 = 24. But 8 × 4 = 32 and 5 × 5 = 25."},
{lvl:3,sec:"G",type:"in",q:"Diego's garden is 12 m by 7 m. He paves a 3 m by 4 m patio inside it. How many square metres of the garden are NOT paved?",ans:72,
 hint:"Whole area minus patio area.",expl:"The garden is 12 × 7 = 84 square metres and the patio is 3 × 4 = 12. 84 − 12 = 72 square metres are not paved."},
{lvl:3,sec:"G",type:"in",q:"A rectangle has an area of 36 square cm and a perimeter of 30 cm. What is its longer side in cm?",ans:12,
 hint:"Which two numbers multiply to 36 and add to 15?",
 expl:"Half the perimeter is 15, so the sides add to 15 and multiply to 36. That is 12 and 3, so the longer side is 12 cm."},
{lvl:3,sec:"G",type:"in",q:"An L-shaped room is a 6 m by 4 m rectangle with a 2 m by 3 m rectangle attached to one side. What is its total area in square metres?",ans:30,
 hint:"Find each rectangle's area, then add.",expl:"6 × 4 = 24 and 2 × 3 = 6, so the room is 24 + 6 = 30 square metres."}
],

"g4-lineplot": [
{sec:"S",type:"in",q:"A line plot shows ribbon lengths: 2 Xs above 1/4 in, 3 Xs above 1/2 in and 1 X above 3/4 in. How many ribbons were measured?",ans:6,
 hint:"Each X is one ribbon.",expl:"Count all the Xs: 2 + 3 + 1 = 6 ribbons."},
{sec:"S",type:"mc",q:"On a line plot, what does each X above a number stand for?",
 opts:["One piece of data with that value","The total of all the data","The number itself","The largest value"],a:0,
 expl:"Each X marks one measurement. Stacking Xs shows how many times that value appeared."},
{sec:"S",type:"mc",q:"A line plot of pencil lengths has 4 Xs at 5 1/2 in, 2 Xs at 6 in and 1 X at 6 1/2 in. Which length is most common?",
 opts:["5 1/2 in","6 in","6 1/2 in","7 in"],a:0,
 expl:"The tallest stack of Xs is at 5 1/2 in, with 4 Xs, so that length is most common."},
{sec:"S",type:"in",q:"A line plot has 3 Xs above 1/8, 5 Xs above 2/8 and 2 Xs above 3/8. How many Xs are above 2/8 or 3/8 altogether?",ans:7,
 expl:"5 Xs at 2/8 plus 2 Xs at 3/8 makes 7."},
{lvl:2,sec:"S",type:"mc",q:"A line plot shows insect lengths: 3 Xs at 1/4 in, 2 Xs at 1/2 in, 1 X at 3/4 in and 2 Xs at 1 in. What is the difference between the longest and shortest insect?",
 opts:["3/4 in","1/4 in","1 in","1/2 in"],a:0,
 expl:"The longest is 1 in and the shortest is 1/4 in. 1 − 1/4 = 3/4 in."},
{lvl:2,sec:"S",type:"in",q:"A line plot of daily rainfall has 2 Xs at 1/2 cm, 1 X at 1 cm and 1 X at 1 1/2 cm. What is the total rainfall in cm? Give a decimal.",ans:3.5,
 hint:"Add every X's value.",expl:"1/2 + 1/2 + 1 + 1 1/2 = 3 1/2 cm, which is 3.5 cm."},
{lvl:2,sec:"S",type:"multi",q:"A line plot has 4 Xs at 2/4, 1 X at 3/4 and 3 Xs at 4/4. Select EVERY true statement.",
 opts:["8 pieces of data were recorded","2/4 is the most common value","3/4 is the most common value","There are more Xs at 3/4 than at 4/4"],aMulti:[0,1],
 expl:"4 + 1 + 3 = 8 Xs in total, and the tallest stack (4 Xs) is at 2/4. Only 1 X sits at 3/4, fewer than the 3 at 4/4."},
{lvl:3,sec:"S",type:"in",q:"Five bean sprouts measure 1/2 in, 1/2 in, 1 in, 1 1/2 in and 2 in. On a line plot of these lengths, what is the total length of all the sprouts in inches? Give a decimal.",ans:5.5,
 hint:"Pair up the halves.",expl:"1/2 + 1/2 = 1, and 1 + 1 1/2 + 2 = 4 1/2. Altogether 1 + 4 1/2 = 5 1/2 in, which is 5.5."},
{lvl:3,sec:"S",type:"mc",q:"A line plot of ribbon lengths shows 3 Xs at 1/4 m and 2 Xs at 3/4 m. If all the ribbons are laid end to end, how long are they altogether?",
 opts:["2 1/4 m","1 1/4 m","5 m","1 m"],a:0,
 expl:"3 × 1/4 = 3/4 m and 2 × 3/4 = 6/4 m. Together 9/4 m = 2 1/4 m."},
{lvl:3,sec:"S",type:"in",q:"Hana's line plot of bag masses shows 6 Xs at 1/2 kg, 2 Xs at 1 kg and 1 X at 2 kg. If the 2 kg bag is removed, how many kg are left in total?",ans:5,
 hint:"Six halves make how many wholes?",expl:"6 × 1/2 = 3 kg and 2 × 1 = 2 kg. Without the 2 kg bag the total is 3 + 2 = 5 kg."}
],

"g4-protract": [
{sec:"G",type:"mc",q:"What does a protractor measure?",opts:["Angles in degrees","Length in centimetres","Mass in grams","Time in minutes"],a:0,
 expl:"A protractor is a half-circle tool marked from 0° to 180° for measuring angles."},
{sec:"G",type:"in",q:"How many degrees are in a right angle?",ans:90,expl:"A right angle is a quarter turn, which is 90°."},
{sec:"G",type:"in",q:"How many degrees are in a straight angle?",ans:180,expl:"A straight angle is a half turn, which is 180°."},
{sec:"G",type:"mc",q:"An angle measures 40°. What type of angle is it?",opts:["Acute","Obtuse","Right","Straight"],a:0,
 expl:"An angle less than 90° is acute, so 40° is acute."},
{lvl:2,sec:"G",type:"in",q:"An angle is made of a 35° angle and a 50° angle placed side by side. What is the total angle in degrees?",ans:85,
 hint:"Angles that share a side add together.",expl:"35 + 50 = 85, so the total angle is 85°."},
{lvl:2,sec:"G",type:"in",q:"A right angle is split into two parts. One part is 25°. How many degrees is the other part?",ans:65,
 expl:"A right angle is 90°, so the other part is 90 − 25 = 65°."},
{lvl:2,sec:"G",type:"mc",q:"One ray of an angle points at 0° on the inner scale of a protractor. The other ray lines up with 120 on the inner scale and 60 on the outer scale. What is the angle?",
 opts:["120°","60°","180°","30°"],a:0,
 expl:"Read the same scale where the first ray sits on 0°. That is the inner scale, so the angle is 120°."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY angle that is obtuse.",mono:true,opts:["135°","95°","90°","45°","180°"],aMulti:[0,1],
 expl:"Obtuse angles are more than 90° but less than 180°: 135° and 95°. 90° is right, 45° is acute and 180° is straight."},
{lvl:3,sec:"G",type:"in",q:"A full turn is 360°. Femi turns 90° clockwise, then 135° more clockwise. How many more degrees must she turn clockwise to face her starting direction?",ans:135,
 hint:"How much of the full turn is done?",expl:"90 + 135 = 225° so far. 360 − 225 = 135° more."},
{lvl:3,sec:"G",type:"in",q:"Three angles fit together along a straight line. Two of them measure 48° and 67°. What is the third angle in degrees?",ans:65,
 hint:"The three angles add up to a straight angle.",expl:"48 + 67 = 115, and 180 − 115 = 65°."},
{lvl:3,sec:"G",type:"in",q:"At 3 o'clock the angle between the hands of a clock is 90°. What is the angle between the hands at 1 o'clock, in degrees?",ans:30,
 hint:"The clock face is split into 12 equal parts.",
 expl:"Three hours of the clock face make 90°, so each hour is 90 ÷ 3 = 30°. At 1 o'clock the hands are one hour apart: 30°."}
],

"g4-linesrays": [
{sec:"G",type:"mc",q:"Which figure goes on forever in both directions?",opts:["A line","A ray","A line segment","A point"],a:0,
 expl:"A line has no endpoints and continues forever both ways. A ray stops at one end and a segment at both."},
{sec:"G",type:"mc",q:"How many endpoints does a ray have?",mono:true,opts:["1","2","0","3"],a:0,
 expl:"A ray starts at one endpoint and goes on forever in one direction."},
{sec:"G",type:"mc",q:"Two lines that never meet and stay the same distance apart are called ___.",opts:["parallel","perpendicular","intersecting","curved"],a:0,
 expl:"Lines that never cross are parallel, like railway tracks."},
{sec:"G",type:"mc",q:"Two lines that cross to make right angles are called ___.",opts:["perpendicular","parallel","rays","segments"],a:0,
 expl:"Perpendicular lines meet at 90°, like the corner of a page."},
{sec:"G",type:"in",q:"How many endpoints does a line segment have?",ans:2,expl:"A segment is the part of a line between two endpoints, so it has 2."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY statement that is true.",
 opts:["A line segment has two endpoints","A ray has one endpoint","A line has two endpoints","A point has a length"],aMulti:[0,1],
 expl:"A segment has two endpoints and a ray has one. A line has none, and a point marks a position with no length."},
{lvl:2,sec:"G",type:"mc",q:"An angle is formed by two ___ that share an endpoint.",opts:["rays","points","circles","curves"],a:0,
 expl:"Two rays from the same endpoint (the vertex) make an angle."},
{lvl:2,sec:"G",type:"mc",q:"The capital letter L is drawn with two straight segments. How are those segments related?",
 opts:["They are perpendicular","They are parallel","They never touch","They are both rays"],a:0,
 expl:"The two parts of an L meet at a right angle, so they are perpendicular."},
{lvl:2,sec:"G",type:"in",q:"Points A, B and C lie on a straight line with B between A and C. Segment AB is 6 cm and segment BC is 4 cm. How long is segment AC, in cm?",ans:10,
 expl:"AC is made of AB and BC joined together: 6 + 4 = 10 cm."},
{lvl:3,sec:"G",type:"in",q:"Two parallel lines are crossed by two other lines that are both perpendicular to them. How many crossing points are there?",ans:4,
 hint:"Sketch it: it looks like a tic-tac-toe grid with one row missing.",
 expl:"Each of the 2 perpendicular lines crosses each of the 2 parallel lines once: 2 × 2 = 4 crossing points."},
{lvl:3,sec:"G",type:"mc",q:"Point M is on segment PQ and PM is the same length as MQ. What is M called?",
 opts:["The midpoint","The endpoint","The vertex","The ray"],a:0,
 expl:"A point that splits a segment into two equal parts is its midpoint."},
{lvl:3,sec:"G",type:"in",q:"Rays OA and OB start at point O and make a 70° angle. Ray OC lies between them so that angle AOC is 25°. What is angle COB in degrees?",ans:45,
 hint:"The two smaller angles make up the whole angle.",expl:"Angle AOC + angle COB = 70°, so angle COB = 70 − 25 = 45°."}
],

"g4-classify": [
{sec:"G",type:"mc",q:"A triangle with all three sides equal is called ___.",opts:["equilateral","isosceles","scalene","right"],a:0,
 expl:"Equilateral means 'equal sides'. All three sides and all three angles are equal."},
{sec:"G",type:"mc",q:"Which quadrilateral has exactly one pair of parallel sides?",opts:["Trapezoid","Square","Rectangle","Rhombus"],a:0,
 expl:"A trapezoid has one pair of parallel sides. Squares, rectangles and rhombuses have two pairs."},
{sec:"G",type:"mc",q:"A triangle has one 90° angle. What type of triangle is it?",opts:["Right","Acute","Obtuse","Equilateral"],a:0,
 expl:"A triangle with a right angle is a right triangle."},
{sec:"G",type:"in",q:"How many pairs of parallel sides does a parallelogram have?",ans:2,
 expl:"A parallelogram has two pairs of opposite sides that are parallel."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY shape that always has four right angles.",opts:["Square","Rectangle","Rhombus","Trapezoid"],aMulti:[0,1],
 expl:"Squares and rectangles always have four right angles. A rhombus or trapezoid can have slanted corners."},
{lvl:2,sec:"G",type:"mc",q:"A triangle has sides of 5 cm, 5 cm and 8 cm. What type is it?",opts:["Isosceles","Equilateral","Scalene","Right"],a:0,
 expl:"Two sides are equal and one is different, so it is isosceles."},
{lvl:2,sec:"G",type:"mc",q:"Which statement is always true?",
 opts:["Every square is a rectangle","Every rectangle is a square","Every rhombus is a square","Every trapezoid is a parallelogram"],a:0,
 expl:"A square has four right angles, so it fits the rule for a rectangle. The other way round fails: a 2 by 5 rectangle is not a square."},
{lvl:2,sec:"G",type:"mc",q:"A triangle has angles of 30°, 60° and 90°. Which describes it?",
 opts:["Right and scalene","Right and isosceles","Acute and scalene","Obtuse and scalene"],a:0,
 expl:"The 90° angle makes it right. All three angles are different, so all three sides are different: scalene."},
{lvl:3,sec:"G",type:"mc",q:"A quadrilateral has four equal sides but no right angles. What is it?",
 opts:["A rhombus","A square","A rectangle","A trapezoid"],a:0,
 expl:"Four equal sides make a rhombus. It would only be a square if the angles were right angles too."},
{lvl:3,sec:"G",type:"in",q:"Two angles of a triangle are 70° and 40°. What is the third angle in degrees?",ans:70,
 hint:"The three angles of a triangle add up to a straight angle.",
 expl:"The angles add to 180°: 180 − 70 − 40 = 70°. Two angles are equal, so it is also isosceles."},
{lvl:3,sec:"G",type:"multi",q:"Select EVERY name that correctly describes a square.",opts:["Rectangle","Rhombus","Parallelogram","Triangle"],aMulti:[0,1,2],
 expl:"A square has four right angles (rectangle), four equal sides (rhombus) and two pairs of parallel sides (parallelogram). It has four sides, so it is not a triangle."}
],

"g4-symmetry": [
{sec:"G",type:"in",q:"How many lines of symmetry does a square have?",ans:4,hint:"Try the middles and the diagonals.",
 expl:"A square folds onto itself across two middle lines and two diagonals: 4 lines of symmetry."},
{sec:"G",type:"mc",q:"Which capital letter has a vertical line of symmetry?",mono:true,opts:["A","F","G","J"],a:0,
 expl:"Fold A down the middle and the two halves match. F, G and J do not fold onto themselves."},
{sec:"G",type:"in",q:"How many lines of symmetry does a rectangle that is not a square have?",ans:2,
 expl:"It folds across the two middle lines only. The diagonals do not work, so it has 2."},
{sec:"G",type:"mc",q:"What is a line of symmetry?",
 opts:["A line that splits a shape into two matching halves","A line through the middle of any shape","The longest side of a shape","A line drawn around a shape"],a:0,
 expl:"If you fold along a line of symmetry, the two halves land exactly on top of each other."},
{lvl:2,sec:"G",type:"in",q:"How many lines of symmetry does an equilateral triangle have?",ans:3,
 expl:"One line from each corner to the middle of the opposite side: 3 lines."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY shape that has at least one line of symmetry.",
 opts:["Circle","Isosceles triangle","Scalene triangle","Regular hexagon"],aMulti:[0,1,3],
 expl:"A circle, an isosceles triangle and a regular hexagon all fold onto themselves. A scalene triangle has no equal sides, so no line works."},
{lvl:2,sec:"G",type:"in",q:"How many lines of symmetry does a regular pentagon have?",ans:5,
 hint:"A regular shape has one line for each side.",expl:"A regular polygon has as many lines of symmetry as sides, so 5."},
{lvl:2,sec:"G",type:"mc",q:"Which capital letter has NO line of symmetry?",mono:true,opts:["R","H","O","T"],a:0,
 expl:"R cannot be folded onto itself. H and O have two lines, and T has a vertical one."},
{lvl:3,sec:"G",type:"in",q:"How many lines of symmetry does a regular octagon have?",ans:8,
 expl:"A regular octagon has 8 sides, and a regular polygon has one line of symmetry per side: 8."},
{lvl:3,sec:"G",type:"mc",q:"Which capital letter has both a vertical and a horizontal line of symmetry?",mono:true,opts:["X","B","E","M"],a:0,
 expl:"X folds top to bottom and left to right. B and E fold only top to bottom, and M only left to right."},
{lvl:3,sec:"G",type:"in",q:"A rectangle is made from two identical squares side by side. A small square is then cut from one corner. How many lines of symmetry does the new shape have?",ans:0,
 hint:"Does any fold still match up the missing corner?",
 expl:"The rectangle had 2 lines, but removing one corner breaks both of them. The new shape has 0 lines of symmetry."},
{lvl:3,sec:"G",type:"order",q:"Order these shapes from fewest lines of symmetry to most.",
 items:["square","equilateral triangle","regular hexagon","non-square rectangle"],
 ansOrder:["non-square rectangle","equilateral triangle","square","regular hexagon"],
 expl:"A non-square rectangle has 2, an equilateral triangle 3, a square 4 and a regular hexagon 6."}
]
};
