/* Grade 4. */
export const G4_BANKS = {
"g4-multcomp": [
{sec:"N",type:"in",q:"Write the number: 4 times as many as 9.",ans:36,expl:"4 times 9 is 4 × 9 = 36."},
{sec:"N",type:"mc",q:"Which sentence describes 6 × 8 = 48?",
 opts:["48 is 6 times as many as 8","48 is 8 more than 6","6 is 8 times as many as 48","8 is 6 more than 48"],a:0,
 expl:"A multiplication comparison reads the factors as a 'times as many' relationship: 48 is 6 times as many as 8."},
{sec:"N",type:"in",q:"Sarah has 5 stickers. Tom has 4 times as many. How many does Tom have?",ans:20,
 expl:"4 times 5 is 4 × 5 = 20."},
{sec:"N",type:"mc",q:"36 is 4 times as many as ___.",mono:true,opts:["9","32","144","4"],a:0,
 expl:"36 ÷ 4 = 9, so 36 is 4 times as many as 9."},
{sec:"N",type:"in",q:"A rope is 6 times as long as a 3-foot rope. How long is it, in feet?",ans:18,
 expl:"6 times 3 feet is 6 × 3 = 18 feet."},
{lvl:2,sec:"N",type:"in",q:"Twice a number is 4 times as many as 7. What is the number?",ans:14,
 hint:"Work out 4 times 7 first.",
 expl:"4 × 7 = 28. If twice the number is 28, the number is 28 ÷ 2 = 14."},
{lvl:2,sec:"N",type:"mc",q:"Which equation matches: '32 is 4 times as many as 8'?",mono:true,
 opts:["32 = 4 × 8","32 = 4 + 8","8 = 4 × 32","4 = 32 × 8"],a:0,
 expl:"'4 times as many as 8' means multiply: 4 × 8 = 32."},
{lvl:3,sec:"N",type:"in",q:"A number is 5 times as many as 6. That result is 3 times as many as what number?",
 ans:10,hint:"Find the first result, then work backwards.",
 expl:"5 × 6 = 30, and 30 = 3 × 10, so the number is 10."}
],

"g4-placemil": [
{sec:"N",type:"in",q:"What is the value of the 7 in 372,000? Type the value, like 7000.",ans:70000,
 hint:"Find which place the 7 sits in.",expl:"The 7 is in the ten-thousands place, so its value is 70,000."},
{sec:"N",type:"in",q:"How many ten-thousands are in 250,000?",ans:25,
 expl:"250,000 ÷ 10,000 = 25 ten-thousands."},
{sec:"N",type:"mc",q:"Which number is the largest?",mono:true,
 opts:["512,000","521,000","125,000","215,000"],a:1,
 expl:"Compare hundred-thousands first: 5 beats 1 and 2. Then compare ten-thousands: 2 beats 1, so 521,000 is largest."},
{sec:"N",type:"in",q:"What number is 4 hundred-thousands, 2 ten-thousands, and 5 ones?",ans:420005,
 hint:"Add the place values together.",
 expl:"400,000 + 20,000 + 5 = 420,005."},
{sec:"N",type:"order",q:"Put these numbers in order, smallest first.",
 items:["340,000","304,000","430,000","403,000"],
 ansOrder:["304,000","340,000","403,000","430,000"],
 expl:"Compare the hundred-thousands digit first (3 vs 4), then the next digit."},
{lvl:2,sec:"N",type:"in",q:"What is 10,000 more than 785,000?",ans:795000,
 expl:"785,000 + 10,000 = 795,000."},
{lvl:2,sec:"N",type:"in",q:"Round 648,392 to the nearest ten-thousand.",ans:650000,
 hint:"Look at the thousands digit to decide which way to round.",
 expl:"The thousands digit is 8, which rounds up. 648,392 rounds to 650,000."},
{lvl:3,sec:"N",type:"in",q:"What is 999,999 rounded to the nearest million?",ans:1000000,
 hint:"Which is closer: 0 or 1,000,000?",
 expl:"999,999 is only 1 away from 1,000,000 and 999,999 away from 0, so it rounds up to 1,000,000."}
],

"g4-fracadd": [
{sec:"F",type:"mc",q:"3/8 + 2/8 = ?",mono:true,opts:["5/8","5/16","6/8","1/8"],a:0,
 expl:"With the same denominator, add the numerators: 3 + 2 = 5, so 5/8."},
{sec:"F",type:"mc",q:"7/10 − 4/10 = ?",mono:true,opts:["3/10","11/10","3/20","4/10"],a:0,
 expl:"Subtract the numerators: 7 − 4 = 3, so 3/10."},
{sec:"F",type:"mc",q:"5/6 + 2/6 = ?",mono:true,opts:["1 1/6","7/12","1/6","6/6"],a:0,
 expl:"5 + 2 = 7 sixths, which is more than a whole: 7/6 = 1 1/6."},
{sec:"F",type:"mc",q:"Which pair of fractions has the SAME denominator?",mono:true,
 opts:["3/9 and 5/9","1/2 and 1/3","2/5 and 3/10","4/6 and 4/8"],a:0,
 expl:"3/9 and 5/9 both have 9 on the bottom — the same denominator."},
{sec:"F",type:"mc",q:"4/9 + 3/9 = ?",mono:true,opts:["7/9","7/18","1/9","12/9"],a:0,
 expl:"4 + 3 = 7 ninths, so 7/9."},
{lvl:2,sec:"F",type:"mc",q:"7/8 − 3/8 = ?",mono:true,opts:["4/8","3/16","10/8","1/16"],a:0,
 expl:"7 − 3 = 4 eighths, so 4/8."},
{lvl:2,sec:"F",type:"mc",q:"A pie is cut into 12 equal slices. You eat 5/12 and your friend eats 3/12. What fraction of the pie is left?",
 mono:true,opts:["4/12","8/12","5/12","7/12"],a:0,
 expl:"Together you ate 5/12 + 3/12 = 8/12, so 12/12 − 8/12 = 4/12 is left."},
{lvl:3,sec:"F",type:"mc",q:"3/5 + 1/5 − 2/5 = ?",mono:true,opts:["2/5","4/5","6/5","1/5"],a:0,
 expl:"3 + 1 − 2 = 2 fifths, so 2/5."}
],

"g4-areaform": [
{sec:"G",type:"in",q:"A rectangle is 9 units long and 4 units wide. What is its area, in square units?",ans:36,
 expl:"Area = length × width = 9 × 4 = 36."},
{sec:"G",type:"in",q:"A rectangle has length 12 and width 5. What is its perimeter, in units?",ans:34,
 expl:"Perimeter = 2 × (12 + 5) = 2 × 17 = 34."},
{sec:"G",type:"mc",q:"Which formula finds the perimeter of a rectangle?",mono:true,
 opts:["2 × (length + width)","length × width","length + width","length × width × 2"],a:0,
 expl:"Perimeter is the distance all the way around, which is twice the sum of the two different side lengths."},
{sec:"G",type:"in",q:"A square has a side of 7 units. What is its area, in square units?",ans:49,
 expl:"A square's area is side × side = 7 × 7 = 49."},
{sec:"G",type:"in",q:"A square has a perimeter of 20 units. What is the length of one side?",ans:5,
 hint:"A square has 4 equal sides.",expl:"20 ÷ 4 = 5 units per side."},
{lvl:2,sec:"G",type:"in",q:"A rectangle has an area of 48 square units and a width of 6 units. What is its length?",
 ans:8,hint:"What times 6 makes 48?",expl:"48 ÷ 6 = 8."},
{lvl:2,sec:"G",type:"in",q:"A rectangular garden is 15 m by 8 m. What is its perimeter, in meters?",ans:46,
 expl:"Perimeter = 2 × (15 + 8) = 2 × 23 = 46."},
{lvl:3,sec:"G",type:"in",q:"A rectangle's perimeter is 30 units and its length is twice its width. What is its area, in square units?",
 ans:50,hint:"Let the width be w and the length 2w — write an equation for the perimeter.",
 expl:"2 × (2w + w) = 30, so 6w = 30 and w = 5. Length is 10. Area = 10 × 5 = 50."}
],

"g4-multistep": [
{sec:"W",type:"in",q:"A school orders 8 boxes of pencils with 24 pencils in each box, then gives away 50 pencils. How many pencils are left?",
 ans:142,hint:"Find the total first.",expl:"8 × 24 = 192, then 192 − 50 = 142."},
{sec:"W",type:"in",q:"Tickets cost $6 each. A family buys 5 tickets and pays with a $50 bill. How much change do they get?",
 ans:20,expl:"5 × $6 = $30, and $50 − $30 = $20."},
{sec:"W",type:"mc",q:"Which expression matches: 'Buy 4 packs of 6 apples, then eat 3 apples'?",mono:true,
 opts:["4 × 6 − 3","4 × 6 + 3","4 + 6 − 3","4 − 6 × 3"],a:0,
 expl:"Find the total apples first (4 × 6), then subtract the 3 eaten."},
{sec:"W",type:"in",q:"A theater has 12 rows of 15 seats. 18 seats are empty. How many seats are filled?",
 ans:162,expl:"12 × 15 = 180 seats total, and 180 − 18 = 162 filled."},
{sec:"W",type:"in",q:"A farmer picks 9 baskets of 20 apples each, then sells 45 apples. How many apples are left?",
 ans:135,expl:"9 × 20 = 180 apples, and 180 − 45 = 135."},
{lvl:2,sec:"W",type:"in",q:"A store has 6 shelves with 24 books each. 3 shelves are emptied completely. How many books are left on shelves?",
 ans:72,hint:"Find the total, then the amount removed.",
 expl:"6 × 24 = 144 total. Emptying 3 shelves removes 3 × 24 = 72, leaving 144 − 72 = 72."},
{lvl:2,sec:"W",type:"in",q:"A bus holds 48 passengers. 5 full buses take a class trip, plus one more bus with only 20 passengers. How many passengers total?",
 ans:260,expl:"5 × 48 = 240, plus 20 more makes 260."},
{lvl:3,sec:"W",type:"in",q:"A bakery bakes 15 trays of 24 cookies each, then packs the cookies into boxes of 18. How many FULL boxes can it fill?",
 ans:20,hint:"Find the total cookies first.",expl:"15 × 24 = 360 cookies, and 360 ÷ 18 = 20 full boxes."}
],

"g4-factorpair": [
{sec:"N",type:"mc",q:"Which pair of factors multiplies to 24?",mono:true,
 opts:["4 and 6","5 and 5","3 and 9","2 and 10"],a:0,expl:"4 × 6 = 24."},
{sec:"N",type:"in",q:"12 has these factor pairs: 1×12, 2×6, 3×4. How many factor pairs does 12 have?",
 ans:3,expl:"1×12, 2×6 and 3×4 make 3 pairs."},
{sec:"N",type:"mc",q:"Which number is PRIME?",mono:true,opts:["13","12","15","21"],a:0,
 expl:"13 has only two factors, 1 and 13. The others all have more factors."},
{sec:"N",type:"mc",q:"Which number is COMPOSITE?",mono:true,opts:["18","17","19","23"],a:0,
 expl:"18 has factors besides 1 and itself (like 2, 3, 6, 9). The others are prime."},
{sec:"N",type:"in",q:"What is the smallest factor of 45 that is greater than 1?",ans:3,
 expl:"45 is not even, so 2 is not a factor. But 45 ÷ 3 = 15, so 3 is the smallest factor above 1."},
{lvl:2,sec:"N",type:"in",q:"How many factors does 16 have in total, including 1 and 16?",ans:5,
 expl:"1, 2, 4, 8 and 16 — that is 5 factors."},
{lvl:2,sec:"N",type:"mc",q:"Which number has EXACTLY two factors, making it prime?",mono:true,
 opts:["29","28","27","26"],a:0,expl:"29's only factors are 1 and 29. The others all have more factors."},
{lvl:3,sec:"N",type:"in",q:"A number between 40 and 50 is prime AND one more than a multiple of 6. What is it?",
 ans:43,hint:"Check 41, 43 and 47.",
 expl:"43 − 1 = 42, which is a multiple of 6, and 43 is prime. 41 and 47 do not fit the 'one more than a multiple of 6' rule."}
],

"g4-multidig": [
{sec:"N",type:"in",q:"23 × 4 = ?",ans:92,expl:"23 × 4 = 92."},
{sec:"N",type:"in",q:"56 × 3 = ?",ans:168,expl:"56 × 3 = 168."},
{sec:"N",type:"in",q:"34 × 12 = ?",ans:408,expl:"34 × 12 = 408."},
{sec:"N",type:"mc",q:"What is 45 × 6?",opts:["270","260","280","250"],a:0,expl:"45 × 6 = 270."},
{sec:"N",type:"in",q:"108 × 5 = ?",ans:540,expl:"108 × 5 = 540."},
{lvl:2,sec:"N",type:"in",q:"126 × 4 = ?",ans:504,expl:"126 × 4 = 504."},
{lvl:2,sec:"N",type:"in",q:"A theater sells 235 tickets a day for 6 days. How many tickets total?",
 ans:1410,expl:"235 × 6 = 1410."},
{lvl:3,sec:"N",type:"in",q:"A number times 8 equals 976. What is the number?",ans:122,
 hint:"Divide to undo the multiplication.",expl:"976 ÷ 8 = 122."}
],

"g4-divide": [
{sec:"N",type:"in",q:"27 ÷ 4 = ? Type just the whole-number quotient (ignore the remainder).",
 ans:6,expl:"4 × 6 = 24, which fits into 27 with 3 left over. The quotient is 6."},
{sec:"N",type:"in",q:"What is the REMAINDER when 27 is divided by 4?",ans:3,
 expl:"4 × 6 = 24, and 27 − 24 = 3 left over."},
{sec:"N",type:"in",q:"83 ÷ 9 gives a quotient of 9. What is the remainder?",ans:2,
 expl:"9 × 9 = 81, and 83 − 81 = 2."},
{sec:"N",type:"in",q:"58 ÷ 7 = ? Type just the whole-number quotient.",ans:8,
 expl:"7 × 8 = 56, which fits into 58. The quotient is 8."},
{sec:"N",type:"in",q:"96 counters are put into groups of 7. How many FULL groups are there?",
 ans:13,expl:"7 × 13 = 91, which fits into 96 with 5 left over. That is 13 full groups."},
{lvl:2,sec:"N",type:"in",q:"A baker has 100 rolls to pack into boxes of 8. How many FULL boxes can be packed?",
 ans:12,expl:"8 × 12 = 96, which fits into 100. That is 12 full boxes."},
{lvl:2,sec:"N",type:"in",q:"After packing full boxes of 8 from 100 rolls, how many rolls are left over?",
 ans:4,hint:"12 full boxes use how many rolls?",expl:"12 boxes use 96 rolls, and 100 − 96 = 4 left over."},
{lvl:3,sec:"N",type:"in",q:"A number divided by 6 gives a quotient of 14 and a remainder of 3. What is the number?",
 ans:87,hint:"Multiply the quotient by 6, then add the remainder.",expl:"6 × 14 = 84, and 84 + 3 = 87."}
],

"g4-mixed": [
{sec:"F",type:"mc",q:"Which mixed number equals 7/2?",mono:true,
 opts:["3 1/2","2 1/2","3 1/3","7 1/2"],a:0,expl:"7 ÷ 2 = 3 remainder 1, so 7/2 = 3 1/2."},
{sec:"F",type:"mc",q:"Which improper fraction equals 2 3/4?",mono:true,
 opts:["11/4","10/4","9/4","2/4"],a:0,expl:"2 × 4 + 3 = 11, so 2 3/4 = 11/4."},
{sec:"F",type:"in",q:"2 1/4 + 1 1/4 = ? Type just the whole-number part of the answer.",ans:3,
 expl:"2 1/4 + 1 1/4 = 3 2/4 = 3 1/2. The whole-number part is 3."},
{sec:"F",type:"mc",q:"Which is GREATER: 3 1/4 or 13/4?",mono:true,
 opts:["They are equal","3 1/4 is greater","13/4 is greater","Cannot compare"],a:0,
 expl:"13/4 = 3 1/4 exactly — they are the same amount written two ways."},
{sec:"F",type:"in",q:"How many halves are in 4 1/2? Type just the number.",ans:9,
 expl:"4 1/2 = 9/2, so there are 9 halves."},
{lvl:2,sec:"F",type:"mc",q:"5 3/4 − 2 1/4 = ?",mono:true,opts:["3 1/2","3 1/4","7","3"],a:0,
 expl:"5 3/4 − 2 1/4 = 3 2/4 = 3 1/2."},
{lvl:2,sec:"F",type:"in",q:"Convert 17/5 to a mixed number. Type just the whole-number part.",ans:3,
 expl:"17 ÷ 5 = 3 remainder 2, so 17/5 = 3 2/5. The whole-number part is 3."},
{lvl:3,sec:"F",type:"mc",q:"1 2/3 + 2 1/3 = ?",mono:true,opts:["4","3","5","4 1/3"],a:0,
 expl:"The whole numbers add to 3, and 2/3 + 1/3 = 1 more whole, making 4."}
],

"g4-decnot": [
{sec:"D",type:"in",q:"Write 3 tenths as a decimal.",ans:0.3,expl:"3 tenths = 0.3."},
{sec:"D",type:"in",q:"Write 7 hundredths as a decimal.",ans:0.07,expl:"7 hundredths = 0.07."},
{sec:"D",type:"mc",q:"Which is the same as 0.5?",mono:true,opts:["5/10","5/100","1/5","1/50"],a:0,
 expl:"0.5 means 5 tenths, which is 5/10."},
{sec:"D",type:"in",q:"Write 0.4 as tenths — type just the numerator over 10.",ans:4,
 expl:"0.4 is 4 tenths, so the numerator is 4."},
{sec:"D",type:"mc",q:"Which decimal is the same as 25/100?",opts:["0.25","0.025","2.5","0.0025"],a:0,
 expl:"25 hundredths is written 0.25."},
{lvl:2,sec:"D",type:"in",q:"Write 'three and six tenths' as a decimal.",ans:3.6,expl:"3 and 6 tenths = 3.6."},
{lvl:2,sec:"D",type:"mc",q:"Which is the same as 0.08?",opts:["8 hundredths","8 tenths","8 thousandths","8 ones"],a:0,
 expl:"The second decimal place is the hundredths place, so 0.08 is 8 hundredths."},
{lvl:3,sec:"D",type:"in",q:"Write 'five and two hundredths' as a decimal.",ans:5.02,
 expl:"5 and 2 hundredths = 5.02."}
],

"g4-deccomp": [
{sec:"D",type:"mc",q:"Which symbol makes this true?  0.4 ◯ 0.25",mono:true,opts:[">","<","="],a:0,
 expl:"0.4 = 0.40, and 40 hundredths is more than 25 hundredths."},
{sec:"D",type:"mc",q:"Which symbol makes this true?  0.09 ◯ 0.9",mono:true,opts:["<",">","="],a:0,
 expl:"0.09 is 9 hundredths, far less than 0.9, which is 90 hundredths."},
{sec:"D",type:"order",q:"Order from smallest to largest.",
 items:["0.5","0.05","0.55","0.15"],ansOrder:["0.05","0.15","0.5","0.55"],
 expl:"Compare as hundredths: 5, 15, 50, 55."},
{sec:"D",type:"mc",q:"Which decimal is LARGEST?",mono:true,
 opts:["0.7","0.65","0.599","0.699"],a:0,expl:"0.7 = 0.700, which beats all the others."},
{sec:"D",type:"mc",q:"Which symbol makes this true?  1.2 ◯ 1.20",mono:true,opts:["=","<",">"],a:0,
 expl:"Adding a zero at the end of a decimal does not change its value."},
{lvl:2,sec:"D",type:"order",q:"Order from LARGEST to smallest.",
 items:["2.05","2.5","2.15","2.1"],ansOrder:["2.5","2.15","2.1","2.05"],
 expl:"As hundredths: 250, 215, 210, 205."},
{lvl:2,sec:"D",type:"mc",q:"Which symbol makes this true?  0.3 ◯ 0.30000",mono:true,opts:["=","<",">"],a:0,
 expl:"Extra trailing zeros never change a decimal's value."},
{lvl:3,sec:"D",type:"mc",q:"Which decimal is between 0.45 and 0.5?",mono:true,
 opts:["0.47","0.4","0.55","0.51"],a:0,expl:"0.47 sits between 0.45 and 0.50. The others fall outside that range."}
],

"g4-linesrays": [
{sec:"G",type:"mc",q:"A ___ has two endpoints.",opts:["line segment","line","ray","point"],a:0,
 expl:"A line segment is the part of a line between two fixed endpoints."},
{sec:"G",type:"mc",q:"A ___ has one endpoint and goes on forever in one direction.",
 opts:["ray","line","segment","point"],a:0,expl:"A ray starts at an endpoint and extends forever in only one direction."},
{sec:"G",type:"mc",q:"Which angle measures LESS than 90°?",opts:["Acute","Obtuse","Straight","Right"],a:0,
 expl:"An acute angle is any angle smaller than a right angle (90°)."},
{sec:"G",type:"mc",q:"Two lines that never meet and stay the same distance apart are called ___.",
 opts:["parallel","perpendicular","intersecting","rays"],a:0,
 expl:"Parallel lines run in the same direction and never cross."},
{sec:"G",type:"mc",q:"Two lines that cross at a right angle are called ___.",
 opts:["perpendicular","parallel","rays","segments"],a:0,
 expl:"Perpendicular lines meet to form a 90° angle."},
{lvl:2,sec:"G",type:"mc",q:"An angle that measures exactly 180° is called a ___ angle.",
 opts:["straight","right","acute","obtuse"],a:0,expl:"A straight angle forms a straight line: 180°."},
{lvl:2,sec:"G",type:"mc",q:"Which describes a right angle?",
 opts:["Exactly 90°","Less than 90°","More than 90° but less than 180°","Exactly 180°"],a:0,
 expl:"A right angle is exactly 90°, no more and no less."},
{lvl:3,sec:"G",type:"mc",q:"Two rays share an endpoint and form a 45° angle. What TYPE of angle is this?",
 opts:["Acute","Obtuse","Right","Straight"],a:0,expl:"45° is less than 90°, so it is acute."}
],

"g4-classify": [
{sec:"G",type:"mc",q:"Which shape has 4 equal sides but does not necessarily have right angles?",
 opts:["Rhombus","Square","Rectangle","Circle"],a:0,
 expl:"A rhombus requires 4 equal sides, but its angles can be any measure — a square is a special rhombus with right angles too."},
{sec:"G",type:"mc",q:"Which is true of ALL rectangles?",
 opts:["4 right angles","4 equal sides","No parallel sides","3 sides"],a:0,
 expl:"Every rectangle has 4 right angles by definition, but its sides need not all be equal."},
{sec:"G",type:"mc",q:"A triangle with all 3 sides equal is called ___.",
 opts:["equilateral","isosceles","scalene","right"],a:0,expl:"'Equilateral' means all sides are the same length."},
{sec:"G",type:"mc",q:"A triangle with exactly 2 equal sides is called ___.",
 opts:["isosceles","equilateral","scalene","right"],a:0,expl:"'Isosceles' means exactly two sides match."},
{sec:"G",type:"mc",q:"A triangle with NO equal sides is called ___.",
 opts:["scalene","isosceles","equilateral","right"],a:0,expl:"'Scalene' means every side is a different length."},
{lvl:2,sec:"G",type:"mc",q:"Which shape ALWAYS has 4 right angles?",
 opts:["Rectangle","Rhombus","Parallelogram","Trapezoid"],a:0,
 expl:"A rectangle is defined by having 4 right angles. The others do not require it."},
{lvl:2,sec:"G",type:"mc",q:"A right triangle has ONE angle that measures ___.",
 opts:["90°","180°","45°","60°"],a:0,expl:"'Right triangle' means one of its angles is exactly 90°."},
{lvl:3,sec:"G",type:"mc",q:"A shape has 4 sides, 4 right angles, and 4 equal sides. What is the MOST specific name?",
 opts:["Square","Rectangle","Rhombus","Quadrilateral"],a:0,
 expl:"It qualifies as all four, but 'square' is the most specific — it requires every one of those properties at once."}
],

"g4-symmetry": [
{sec:"G",type:"mc",q:"A shape has a line of symmetry if ___.",
 opts:["folding on the line makes both halves match up","it has exactly 4 sides total","it is a perfectly round circle","it has zero sides at all"],a:0,
 expl:"A line of symmetry is a fold line where the two halves land exactly on top of each other."},
{sec:"G",type:"in",q:"How many lines of symmetry does a square have?",ans:4,
 expl:"A square can be folded along 2 diagonals and 2 through the midpoints of its sides — 4 lines in total."},
{sec:"G",type:"in",q:"How many lines of symmetry does a regular (equilateral) triangle have?",ans:3,
 expl:"Each line runs from a corner to the midpoint of the opposite side — 3 in total."},
{sec:"G",type:"mc",q:"Which letter has a VERTICAL line of symmetry?",mono:true,
 opts:["A","F","G","R"],a:0,expl:"Folding the letter A down the middle makes both halves match."},
{sec:"G",type:"in",q:"How many lines of symmetry does a non-square rectangle have?",ans:2,
 expl:"One line through the middle horizontally, and one vertically — 2 in total."},
{lvl:2,sec:"G",type:"in",q:"How many lines of symmetry does a regular hexagon have?",ans:6,
 expl:"A regular hexagon has one line of symmetry through each pair of opposite corners or sides — 6 in total."},
{lvl:2,sec:"G",type:"mc",q:"Which shape has NO lines of symmetry?",
 opts:["A scalene triangle","A square","A circle","An isosceles triangle"],a:0,
 expl:"A scalene triangle has no matching sides, so no fold line makes the halves match."},
{lvl:3,sec:"G",type:"mc",q:"A shape has exactly 1 line of symmetry. Which is it most likely to be?",
 opts:["An isosceles triangle that is not equilateral","A square with 4 equal sides","A regular hexagon shape","A perfectly round circle"],a:0,
 expl:"An isosceles (non-equilateral) triangle folds evenly only down its single line from the peak to the base's midpoint."}
],

"g4-seq": [
{sec:"N",type:"in",q:"What is the next number: 2, 5, 8, 11, ___?",ans:14,expl:"The rule is 'add 3', so 11 + 3 = 14."},
{sec:"N",type:"mc",q:"What is the RULE for 3, 9, 27, 81?",opts:["Multiply by 3","Add 6","Add 3","Multiply by 9"],a:0,
 expl:"Each number is 3 times the one before it."},
{sec:"N",type:"in",q:"A pattern starts at 5 and the rule is 'add 6'. What is the 4th number?",ans:23,
 hint:"List them: 5, 11, 17, 23.",expl:"5, 11, 17, 23 — the 4th number is 23."},
{sec:"N",type:"mc",q:"Which rule matches the shape pattern: square, pentagon, hexagon, ...?",
 opts:["Add one side each time","Add one color each time","Remove a side each time","No pattern"],a:0,
 expl:"4 sides, then 5, then 6 — each shape gains one more side."},
{sec:"N",type:"in",q:"What is the next number: 100, 90, 80, 70, ___?",ans:60,expl:"The rule is 'subtract 10', so 70 − 10 = 60."},
{lvl:2,sec:"N",type:"in",q:"A pattern is 2, 6, 18, 54, ___. What is next?",ans:162,expl:"The rule is 'multiply by 3': 54 × 3 = 162."},
{lvl:2,sec:"N",type:"mc",q:"Which rule describes 1, 3, 6, 10, 15?",
 opts:["Add one more than the last add (add 2, then 3, then 4...)","Multiply by 2 each time","Subtract 1 each time","Add the same number each time"],a:0,
 expl:"The gaps grow: +2, +3, +4, +5 — each add is one bigger than the last."},
{lvl:3,sec:"N",type:"in",q:"A pattern follows 'double, then add 1': 2, 5, 11, 23, ___. What is next?",ans:47,
 expl:"23 × 2 = 46, then 46 + 1 = 47."}
],

"g4-fracmultw": [
{sec:"F",type:"in",q:"3 × 1/4 = ? Type just the numerator (the denominator stays 4).",ans:3,
 expl:"3 × 1/4 = 3/4, so the numerator is 3."},
{sec:"F",type:"mc",q:"2/3 × 4 = ?",mono:true,opts:["8/3","6/3","2/12","4/3"],a:0,
 expl:"Multiply the numerator by the whole number: 2 × 4 = 8, so 8/3."},
{sec:"F",type:"in",q:"5 × 2/5 = ?",ans:2,expl:"5 × 2/5 = 10/5 = 2."},
{sec:"F",type:"mc",q:"Which expression equals 3/8 × 2?",mono:true,opts:["6/8","3/16","5/8","2/8"],a:0,
 expl:"3 × 2 = 6, so 3/8 × 2 = 6/8."},
{sec:"F",type:"in",q:"4 × 3/4 = ?",ans:3,expl:"4 × 3/4 = 12/4 = 3."},
{lvl:2,sec:"F",type:"mc",q:"A recipe needs 3/4 cup of sugar per batch. How much sugar for 5 batches?",mono:true,
 opts:["15/4 cups","8/4 cups","15/20 cups","3/20 cups"],a:0,expl:"3/4 × 5 = 15/4 cups."},
{lvl:2,sec:"F",type:"in",q:"6 × 5/6 = ?",ans:5,expl:"6 × 5/6 = 30/6 = 5."},
{lvl:3,sec:"F",type:"in",q:"A runner covers 2/3 mile each lap. After 9 laps, how many miles total?",ans:6,
 expl:"2/3 × 9 = 18/3 = 6 miles."}
],

"g4-units": [
{sec:"M",type:"in",q:"How many inches are in 2 feet? (12 in = 1 ft)",ans:24,expl:"2 × 12 = 24 inches."},
{sec:"M",type:"in",q:"How many minutes are in 2 hours?",ans:120,expl:"2 × 60 = 120 minutes."},
{sec:"M",type:"mc",q:"Which is bigger, a meter or a centimeter?",
 opts:["A meter","A centimeter","They are equal","Cannot tell"],a:0,
 expl:"A meter is 100 centimeters — much bigger than one centimeter."},
{sec:"M",type:"in",q:"How many ounces are in 3 pounds? (16 oz = 1 lb)",ans:48,expl:"3 × 16 = 48 ounces."},
{sec:"M",type:"in",q:"How many seconds are in 3 minutes?",ans:180,expl:"3 × 60 = 180 seconds."},
{lvl:2,sec:"M",type:"in",q:"A ribbon is 3 feet long. How many inches is that?",ans:36,expl:"3 × 12 = 36 inches."},
{lvl:2,sec:"M",type:"in",q:"A recipe takes 2 hours and 15 minutes. How many minutes total?",ans:135,
 expl:"2 × 60 = 120, plus 15 more = 135 minutes."},
{lvl:3,sec:"M",type:"in",q:"A race is 5000 meters. How many kilometers is that? (1000 m = 1 km)",ans:5,
 expl:"5000 ÷ 1000 = 5 kilometers."}
],

"g4-lineplot": [
{sec:"M",type:"in",q:"A line plot shows: 2 X's at 1/4 inch, 3 X's at 1/2 inch, 1 X at 3/4 inch. How many data points in total?",
 ans:6,expl:"2 + 3 + 1 = 6 data points."},
{sec:"M",type:"in",q:"Using that plot, what is the total length of the three 1/2-inch measurements added together? Type as a decimal.",
 ans:1.5,expl:"3 × 0.5 = 1.5 inches."},
{sec:"M",type:"mc",q:"On a line plot with fraction measurements, each X on the line usually represents ___.",
 opts:["a fraction of a unit, like 1/4 inch","a whole mile","a whole day","nothing measurable"],a:0,
 expl:"Each X marks one measurement, often to the nearest fraction of an inch."},
{sec:"M",type:"in",q:"A line plot has 4 X's at 1/2 inch and 2 X's at 1 inch. What is the TOTAL length in inches? Type as a decimal.",
 ans:4,expl:"4 × 0.5 = 2, and 2 × 1 = 2. Together: 2 + 2 = 4 inches."},
{sec:"M",type:"mc",q:"Which fraction is the smallest measurement typically marked on a ruler line plot?",mono:true,
 opts:["1/8 inch","1 inch","1/2 inch","2 inches"],a:0,expl:"1/8 inch is the finest, smallest division listed."},
{lvl:2,sec:"M",type:"in",q:"A line plot: 3 X's at 1/4 inch, 2 X's at 3/4 inch. What is the total length in inches? Type as a decimal.",
 ans:2.25,expl:"3 × 0.25 = 0.75, and 2 × 0.75 = 1.5. Together: 0.75 + 1.5 = 2.25 inches."},
{lvl:2,sec:"M",type:"in",q:"Using that same plot (3 X's at 1/4 inch, 2 X's at 3/4 inch), how many data points are there in total?",
 ans:5,expl:"3 + 2 = 5 data points."},
{lvl:3,sec:"M",type:"in",q:"A line plot has data points at 1/4, 1/4, 1/2, 3/4, 3/4, 3/4 inch. What is the total length in inches? Type as a decimal.",
 ans:3.25,expl:"0.25 + 0.25 + 0.5 + 0.75 + 0.75 + 0.75 = 3.25 inches."}
],

"g4-protract": [
{sec:"G",type:"mc",q:"An angle measures 45°. What type of angle is it?",
 opts:["Acute","Right","Obtuse","Straight"],a:0,expl:"An angle under 90° is acute."},
{sec:"G",type:"in",q:"Two angles together make a straight line (180°). One angle is 110°. What is the other?",
 ans:70,expl:"180 − 110 = 70°."},
{sec:"G",type:"mc",q:"Which angle measure is OBTUSE?",mono:true,opts:["120°","45°","90°","30°"],a:0,
 expl:"An obtuse angle is more than 90° and less than 180°: 120° fits."},
{sec:"G",type:"in",q:"An angle of 35° and an angle of 55° are placed together with no overlap. What is their combined measure?",
 ans:90,expl:"35 + 55 = 90°."},
{sec:"G",type:"mc",q:"A right angle measures exactly ___.",opts:["90°","180°","45°","360°"],a:0,
 expl:"A right angle is always exactly 90°."},
{lvl:2,sec:"G",type:"in",q:"Two angles combine to make a right angle (90°). One is 34°. What is the other?",
 ans:56,expl:"90 − 34 = 56°."},
{lvl:2,sec:"G",type:"mc",q:"An angle measures 150°. What type of angle is it?",
 opts:["Obtuse","Acute","Right","Straight"],a:0,expl:"150° is more than 90° and less than 180° — obtuse."},
{lvl:3,sec:"G",type:"in",q:"Three angles around a point add up to 360°. Two of them are 110° and 140°. What is the third?",
 ans:110,expl:"360 − 110 − 140 = 110°."}
]
};
