/* Grade 5 advanced / enrichment: number theory (modular arithmetic, congruences,
   Fermat, Diophantine equations, bases), algebra (multi-step equations,
   inequalities, rate and percent equations, formulas, functions), extended
   geometry (Pythagoras, distance, angle sums, circles, cylinders),
   combinatorics and probability. Competition-style (AMC 8 / Kangaroo) content
   with Grade 5 wording. */
export const G5_ADV_BANKS = {
"g5-modarith": [
{sec:"T",type:"in",q:"What is the remainder when 17 is divided by 5? (This is 17 mod 5.)",ans:2,
 hint:"How many whole fives fit into 17?",expl:"17 = 3 × 5 + 2, so 17 mod 5 = 2."},
{sec:"T",type:"in",q:"What is the remainder when 100 is divided by 7?",ans:2,
 expl:"7 × 14 = 98, and 100 − 98 = 2. The remainder is 2."},
{sec:"T",type:"mc",q:"Which number is congruent to 3 (mod 4)?",mono:true,opts:["11","10","9","12"],a:0,
 expl:"11 = 2 × 4 + 3, so 11 leaves remainder 3. The others leave remainders 2, 1 and 0."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number that leaves remainder 1 when divided by 6.",
 opts:["25","13","20","31"],aMulti:[0,1,3],
 expl:"25 = 24 + 1, 13 = 12 + 1 and 31 = 30 + 1 all leave remainder 1. 20 = 18 + 2 leaves remainder 2."},
{lvl:2,sec:"T",type:"mc",q:"Today is Tuesday. What day of the week will it be in 100 days?",
 opts:["Thursday","Wednesday","Friday","Tuesday"],a:0,hint:"Days repeat every 7.",
 expl:"100 = 14 × 7 + 2, so 100 days is 14 full weeks plus 2 days. Two days after Tuesday is Thursday."},
{lvl:2,sec:"T",type:"in",q:"What is the remainder when 23 × 29 is divided by 5?",ans:2,
 hint:"Reduce each factor mod 5 first.",
 expl:"23 ≡ 3 and 29 ≡ 4 (mod 5), so 23 × 29 ≡ 3 × 4 = 12 ≡ 2 (mod 5). The remainder is 2."},
{lvl:3,sec:"T",type:"in",q:"What is the units digit of 7 to the power 10?",ans:9,
 hint:"Write out the units digits of 7, 7², 7³, 7⁴ and look for a repeating cycle.",
 expl:"Units digits of powers of 7 cycle 7, 9, 3, 1 with period 4. 10 = 2 × 4 + 2, so the units digit matches 7², which is 9."},
{lvl:3,sec:"T",type:"in",q:"What is the remainder when 2 to the power 20 is divided by 7?",ans:4,
 hint:"2³ = 8 is 1 more than a multiple of 7.",
 expl:"2³ = 8 ≡ 1 (mod 7). 2²⁰ = (2³)⁶ × 2² ≡ 1 × 4 = 4 (mod 7). The remainder is 4."},
{lvl:3,sec:"T",type:"in",q:"Find the remainder when 1 + 2 + 3 + ... + 100 is divided by 9.",ans:1,
 hint:"Find the sum first, then think about the digit sum.",
 expl:"1 + 2 + ... + 100 = 100 × 101 ÷ 2 = 5050. Its digit sum is 10, and 10 mod 9 = 1, so the remainder is 1."}
],

"g5-congru": [
{sec:"T",type:"in",q:"Find the smallest positive whole number x such that x + 4 ≡ 1 (mod 6).",ans:3,
 hint:"Subtract 4 from both sides, then add 6 to make it positive.",
 expl:"x ≡ 1 − 4 = −3 ≡ 3 (mod 6). Check: 3 + 4 = 7, and 7 mod 6 = 1. So x = 3."},
{sec:"T",type:"in",q:"Find the smallest positive whole number x such that 3x ≡ 1 (mod 7).",ans:5,
 hint:"Try x = 1, 2, 3, ... and check 3x mod 7.",
 expl:"3 × 5 = 15 = 2 × 7 + 1, so 3 × 5 ≡ 1 (mod 7). Smaller values of x give 3, 6, 2 and 5, none of which is 1. So x = 5."},
{sec:"T",type:"mc",q:"Which value of x satisfies 2x ≡ 4 (mod 10)?",mono:true,opts:["7","3","4","5"],a:0,
 expl:"2 × 7 = 14, and 14 mod 10 = 4. The others give 6, 8 and 0."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY value of x that satisfies 4x ≡ 2 (mod 6).",
 opts:["2","5","1","3"],aMulti:[0,1],
 expl:"4 × 2 = 8 ≡ 2 and 4 × 5 = 20 ≡ 2 (mod 6). But 4 × 1 = 4 and 4 × 3 = 12 ≡ 0, so 1 and 3 do not work."},
{lvl:2,sec:"T",type:"in",q:"A number leaves remainder 2 when divided by 5 and remainder 3 when divided by 7. What is the smallest such positive number?",ans:17,
 hint:"List numbers that are 2 more than a multiple of 5 and test each one.",
 expl:"Numbers ≡ 2 (mod 5) are 2, 7, 12, 17, ... Testing mod 7: 2, 0, 5, 3. The first with remainder 3 is 17."},
{lvl:2,sec:"T",type:"mc",q:"Why does 2x ≡ 3 (mod 4) have no whole-number solution?",
 opts:["2x is always even, but 3 + 4k is odd","x would have to be a fraction, 1.5","There is a solution: x = 1"],a:0,
 expl:"2x is always even, and any number that is 3 more than a multiple of 4 is odd. An even number can never equal an odd one, so there is no solution."},
{lvl:3,sec:"T",type:"in",q:"Solve 5x ≡ 3 (mod 11). Give the smallest positive whole-number solution.",ans:5,
 hint:"Look for a multiple of 5 that is 3 more than a multiple of 11.",
 expl:"5 × 5 = 25 = 2 × 11 + 3, so 5 × 5 ≡ 3 (mod 11). No smaller positive x works, so x = 5."},
{lvl:3,sec:"T",type:"in",q:"Ingrid counts her marbles. In groups of 3 there is 1 left over, in groups of 4 there are 2 left over, and in groups of 5 there are 3 left over. What is the fewest marbles she could have?",ans:58,
 hint:"Notice what happens if you add 2 to the number of marbles.",
 expl:"In each case the remainder is 2 less than the divisor, so adding 2 gives a multiple of 3, 4 and 5, that is a multiple of 60. The smallest positive answer is 60 − 2 = 58."},
{lvl:3,sec:"T",type:"in",q:"How many whole numbers x from 1 to 100 satisfy 3x ≡ 6 (mod 9)?",ans:33,
 hint:"Simplify the congruence by dividing everything, including the modulus, by 3.",
 expl:"3x ≡ 6 (mod 9) is the same as x ≡ 2 (mod 3). The values 2, 5, 8, ..., 98 form an arithmetic list with (98 − 2) ÷ 3 + 1 = 33 terms."}
],

"g5-fermat": [
{sec:"T",type:"mc",q:"Fermat's Little Theorem says: if p is prime and a is not a multiple of p, then a to the power (p − 1) leaves what remainder when divided by p?",
 mono:true,opts:["1","0","a","p − 1"],a:0,
 expl:"The theorem states a^(p−1) ≡ 1 (mod p). For example 2⁴ = 16 ≡ 1 (mod 5)."},
{sec:"T",type:"in",q:"What is the remainder when 2 to the power 6 is divided by 7?",ans:1,
 hint:"7 is prime, so Fermat's Little Theorem applies.",
 expl:"2⁶ = 64 = 9 × 7 + 1, so the remainder is 1, just as Fermat's Little Theorem predicts."},
{sec:"T",type:"in",q:"What is the remainder when 3 to the power 4 is divided by 5?",ans:1,
 expl:"3⁴ = 81 = 16 × 5 + 1. The remainder is 1, matching a^(p−1) ≡ 1 (mod p) with p = 5."},
{lvl:2,sec:"T",type:"in",q:"What is the remainder when 2 to the power 100 is divided by 7?",ans:2,
 hint:"Use 2⁶ ≡ 1 (mod 7) to shrink the exponent.",
 expl:"2⁶ ≡ 1 (mod 7) and 100 = 6 × 16 + 4, so 2¹⁰⁰ ≡ (2⁶)¹⁶ × 2⁴ ≡ 16 ≡ 2 (mod 7). The remainder is 2."},
{lvl:2,sec:"T",type:"in",q:"What is the remainder when 5 to the power 12 is divided by 13?",ans:1,
 expl:"13 is prime and 5 is not a multiple of 13, so by Fermat's Little Theorem 5¹² ≡ 1 (mod 13). The remainder is 1."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY statement that follows from Fermat's Little Theorem.",mono:true,
 opts:["3¹⁰ ≡ 1 (mod 11)","2¹² ≡ 1 (mod 13)","4⁵ ≡ 1 (mod 6)","10⁶ ≡ 1 (mod 7)"],aMulti:[0,1,3],
 expl:"11, 13 and 7 are prime, so the first, second and fourth follow from the theorem. 6 is not prime, and in fact 4⁵ = 1024 leaves remainder 4 when divided by 6."},
{lvl:3,sec:"T",type:"in",q:"101 is prime. What is the remainder when 3 to the power 101 is divided by 101?",ans:3,
 hint:"Split 3¹⁰¹ as 3¹⁰⁰ × 3.",
 expl:"By Fermat, 3¹⁰⁰ ≡ 1 (mod 101). So 3¹⁰¹ = 3¹⁰⁰ × 3 ≡ 1 × 3 = 3 (mod 101). The remainder is 3."},
{lvl:3,sec:"T",type:"in",q:"What is the remainder when 7 to the power 222 is divided by 11?",ans:5,
 hint:"Use 7¹⁰ ≡ 1 (mod 11) and write 222 = 220 + 2.",
 expl:"7¹⁰ ≡ 1 (mod 11), so 7²²² = (7¹⁰)²² × 7² ≡ 49 (mod 11). 49 = 4 × 11 + 5, so the remainder is 5."},
{lvl:3,sec:"T",type:"in",q:"What is the remainder when 2 to the power 50 plus 3 to the power 50 is divided by 5?",ans:3,
 hint:"Handle each power separately using a⁴ ≡ 1 (mod 5), then add.",
 expl:"2⁴ ≡ 1 and 3⁴ ≡ 1 (mod 5). Since 50 = 4 × 12 + 2, 2⁵⁰ ≡ 2² = 4 and 3⁵⁰ ≡ 3² = 9 ≡ 4. The sum is 8 ≡ 3 (mod 5)."}
],

"g5-diophant": [
{sec:"T",type:"mc",q:"Which pair (x, y) of whole numbers satisfies 3x + 5y = 19?",mono:true,
 opts:["(3, 2)","(2, 3)","(4, 1)","(1, 4)"],a:0,
 expl:"3 × 3 + 5 × 2 = 9 + 10 = 19. The other pairs give 21, 17 and 23."},
{sec:"T",type:"in",q:"How many solutions in positive whole numbers (x, y) does x + y = 7 have?",ans:6,
 hint:"x can be any positive number less than 7.",
 expl:"x can be 1, 2, 3, 4, 5 or 6, and y = 7 − x is then positive. That is 6 solutions."},
{sec:"T",type:"in",q:"Mateo buys pens at $2 each and notebooks at $5 each, spending exactly $12 and buying at least one of each. How many pens does he buy?",ans:1,
 hint:"The total is even. What does that tell you about the number of notebooks?",
 expl:"2p + 5n = 12. Since 2p and 12 are even, 5n must be even, so n is even; n = 2 is the only choice with p ≥ 1. Then 2p = 2, so he buys 1 pen."},
{lvl:2,sec:"T",type:"mc",q:"Why does 4x + 6y = 15 have no whole-number solutions?",
 opts:["The left side is always even, 15 is odd","15 is not a multiple of 4","6 is bigger than 4","x and y would both be negative"],a:0,
 expl:"4x and 6y are both even, so their sum is even. 15 is odd, so the equation can never balance."},
{lvl:2,sec:"T",type:"in",q:"How many solutions in positive whole numbers (x, y) does 3x + 4y = 36 have?",ans:2,
 hint:"3x = 36 − 4y must be a multiple of 3, so y must be a multiple of 3.",
 expl:"y must be a multiple of 3. y = 3 gives x = 8; y = 6 gives x = 4; y = 9 gives x = 0, which is not positive. So there are 2 solutions."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY equation that has at least one solution with x and y whole numbers (0 allowed).",mono:true,
 opts:["6x + 9y = 21","6x + 9y = 20","5x + 10y = 35","4x + 8y = 30"],aMulti:[0,2],
 expl:"6x + 9y is always a multiple of 3, so 21 works (x = 2, y = 1) but 20 does not. 5x + 10y is a multiple of 5, so 35 works (x = 7, y = 0). 4x + 8y is a multiple of 4, and 30 is not."},
{lvl:3,sec:"T",type:"in",q:"Aisha has only 7-cent and 11-cent stamps. What is the largest amount of postage, in cents, that she CANNOT make exactly?",ans:59,
 hint:"List the amounts you can make and look for where the gaps stop for good.",
 expl:"Once 7 amounts in a row can be made, everything larger can be too (add 7s). Checking shows 60 to 66 are all possible, but 59 is not: 59 − 11k is never a multiple of 7 for k = 0 to 5. The answer is 59 (which equals 7 × 11 − 7 − 11)."},
{lvl:3,sec:"T",type:"in",q:"How many pairs of positive whole numbers (x, y) satisfy xy − 2x − 3y = 0?",ans:4,
 hint:"Add 6 to both sides and try to factorise the left side.",
 expl:"xy − 2x − 3y + 6 = 6 gives (x − 3)(y − 2) = 6. Positive factor pairs of 6 are 1 × 6, 2 × 3, 3 × 2, 6 × 1, giving (x, y) = (4, 8), (5, 5), (6, 4), (9, 3). Negative pairs make x or y non-positive. That is 4 pairs."},
{lvl:3,sec:"T",type:"in",q:"Yusuf spends exactly $50 on tickets costing $7 for adults and $4 for children. He buys more children's tickets than adult tickets. How many children's tickets does he buy?",ans:9,
 hint:"The number of adult tickets must make 7a even.",
 expl:"7a + 4c = 50. Since 4c and 50 are even, a is even. a = 2 gives c = 9; a = 6 gives c = 2 (fewer than adults, not allowed); a = 0 gives c = 12.5. So he buys 9 children's tickets."}
],

"g5-bases": [
{sec:"T",type:"in",q:"What is the binary number 1011 in base 10?",ans:11,hint:"The place values are 8, 4, 2, 1.",
 expl:"1011 in binary is 8 + 0 + 2 + 1 = 11."},
{sec:"T",type:"in",q:"Write 13 in binary. Type only the binary digits (for example 101).",ans:1101,
 hint:"Which of 8, 4, 2, 1 add up to 13?",
 expl:"13 = 8 + 4 + 1, so the digits for 8, 4, 2, 1 are 1, 1, 0, 1: 1101."},
{sec:"T",type:"mc",q:"Which digits can be used when writing numbers in base 5?",
 opts:["0, 1, 2, 3, 4","1, 2, 3, 4, 5","0, 1, 2, 3, 4, 5","0 and 1 only"],a:0,
 expl:"Base b uses the digits 0 up to b − 1. Base 5 uses 0, 1, 2, 3 and 4."},
{lvl:2,sec:"T",type:"in",q:"What is 243 (base 5) in base 10?",ans:73,hint:"The place values are 25, 5, 1.",
 expl:"2 × 25 + 4 × 5 + 3 × 1 = 50 + 20 + 3 = 73."},
{lvl:2,sec:"T",type:"in",q:"Write 100 (base 10) in base 8. Type only the base-8 digits.",ans:144,
 hint:"The place values in base 8 are 64, 8, 1.",
 expl:"100 = 1 × 64 + 4 × 8 + 4 × 1, so 100 in base 8 is 144."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number that equals 20 in base 10.",mono:true,
 opts:["10100 (base 2)","40 (base 5)","24 (base 8)","201 (base 3)"],aMulti:[0,1,2],
 expl:"10100 (base 2) = 16 + 4 = 20; 40 (base 5) = 4 × 5 = 20; 24 (base 8) = 16 + 4 = 20. But 201 (base 3) = 18 + 0 + 1 = 19."},
{lvl:3,sec:"T",type:"in",q:"In base 2, what is 1101 + 111? Type only the binary digits of the answer.",ans:10100,
 hint:"Convert both to base 10, add, then convert back, or add column by column carrying when you reach 2.",
 expl:"1101 = 13 and 111 = 7, and 13 + 7 = 20. In binary 20 = 16 + 4 = 10100."},
{lvl:3,sec:"T",type:"in",q:"The number written 121 in base b equals 49 in base 10. What is b?",ans:6,
 hint:"Write 121 (base b) as an expression in b, and notice it is a perfect square.",
 expl:"121 (base b) = b² + 2b + 1 = (b + 1)². So (b + 1)² = 49, giving b + 1 = 7 and b = 6. Check: 36 + 12 + 1 = 49."},
{lvl:3,sec:"T",type:"in",q:"What is the largest 3-digit number in base 4, written in base 10?",ans:63,
 hint:"The largest digit in base 4 is 3.",
 expl:"The largest 3-digit base-4 number is 333 (base 4) = 3 × 16 + 3 × 4 + 3 = 48 + 12 + 3 = 63, which is one less than 4³."}
],

"g5-multistep": [
{sec:"L",type:"in",q:"Solve for x: 3x + 5 = 20.",ans:5,hint:"Undo the + 5 first, then the × 3.",
 expl:"Subtract 5 from both sides: 3x = 15. Divide by 3: x = 5."},
{sec:"L",type:"in",q:"Solve for x: 4x − 7 = 21.",ans:7,
 expl:"Add 7 to both sides: 4x = 28. Divide by 4: x = 7."},
{sec:"L",type:"mc",q:"What is the best first step to solve 2x + 9 = 25?",
 opts:["Subtract 9 from both sides","Divide both sides by 2","Add 9 to both sides","Multiply both sides by 2"],a:0,
 expl:"Undo the addition first: subtracting 9 from both sides leaves 2x = 16, which is then easy to divide."},
{lvl:2,sec:"L",type:"in",q:"Solve for x: 5x − 3 = 2x + 12.",ans:5,hint:"Collect the x terms on one side.",
 expl:"Subtract 2x from both sides: 3x − 3 = 12. Add 3: 3x = 15. So x = 5."},
{lvl:2,sec:"L",type:"in",q:"Solve for x: 3(x − 2) = 24.",ans:10,hint:"You can divide both sides by 3 first.",
 expl:"Divide both sides by 3: x − 2 = 8. Add 2: x = 10."},
{lvl:2,sec:"L",type:"in",q:"Solve for x: x ÷ 4 + 3 = 8.",ans:20,
 expl:"Subtract 3 from both sides: x ÷ 4 = 5. Multiply by 4: x = 20."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY equation whose solution is x = 6.",mono:true,
 opts:["2x + 1 = 13","3x − 4 = 14","x ÷ 2 + 5 = 8","4x = 20"],aMulti:[0,1,2],
 expl:"2 × 6 + 1 = 13, 3 × 6 − 4 = 14 and 6 ÷ 2 + 5 = 8 all work. 4x = 20 gives x = 5."},
{lvl:3,sec:"L",type:"in",q:"Priya thinks of a number, doubles it, adds 7, then multiplies the result by 3 to get 63. What was her number?",ans:7,
 hint:"Write the steps as an equation: 3(2n + 7) = 63.",
 expl:"3(2n + 7) = 63, so 2n + 7 = 21, so 2n = 14 and n = 7."},
{lvl:3,sec:"L",type:"in",q:"Solve for x: 2(3x − 1) + 4 = 5x + 11.",ans:9,hint:"Expand the bracket and simplify the left side first.",
 expl:"Expanding: 6x − 2 + 4 = 5x + 11, so 6x + 2 = 5x + 11. Subtract 5x and 2: x = 9."},
{lvl:3,sec:"L",type:"in",q:"The perimeter of a rectangle is 46 cm. Its length is 5 cm more than twice its width. What is the width in cm?",ans:6,
 hint:"Let the width be w and write the length in terms of w.",
 expl:"Length = 2w + 5. Perimeter: 2(w + 2w + 5) = 46, so 3w + 5 = 23, so 3w = 18 and w = 6 cm."}
],

"g5-inequal": [
{sec:"L",type:"mc",q:"On a number line, how is x > 3 shown?",
 opts:["Open circle at 3, shading to the right","Closed circle at 3, shading to the right","Open circle at 3, shading to the left","Closed circle at 3, shading to the left"],a:0,
 expl:"The strict inequality > means 3 itself is not included (open circle), and the numbers greater than 3 lie to the right."},
{sec:"L",type:"mc",q:"Which inequality is shown by a closed (filled) circle at 5 with shading to the left?",mono:true,
 opts:["x ≤ 5","x < 5","x ≥ 5","x > 5"],a:0,
 expl:"A filled circle means 5 is included, and shading to the left means numbers less than 5. That is x ≤ 5."},
{sec:"L",type:"in",q:"What is the smallest whole number that satisfies x > 4.5?",ans:5,
 expl:"Whole numbers greater than 4.5 are 5, 6, 7, ... The smallest is 5."},
{lvl:2,sec:"L",type:"in",q:"Solve 3x − 4 < 11. What is the largest whole number solution?",ans:4,
 hint:"Solve it like an equation, keeping the < sign.",
 expl:"3x < 15, so x < 5. The largest whole number less than 5 is 4."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY value of x that satisfies 2x + 3 ≥ 9.",opts:["3","5","2","0"],aMulti:[0,1],
 expl:"2x ≥ 6 gives x ≥ 3. So 3 and 5 satisfy it; 2 and 0 do not."},
{lvl:2,sec:"L",type:"mc",q:"Solve 5 − x > 2.",mono:true,opts:["x < 3","x > 3","x < −3","x > 7"],a:0,
 hint:"Try adding x to both sides so the x stays positive.",
 expl:"Add x to both sides: 5 > 2 + x. Subtract 2: 3 > x, which is x < 3."},
{lvl:3,sec:"L",type:"in",q:"How many whole numbers satisfy both 2x + 1 > 7 and 3x − 2 ≤ 19?",ans:4,
 hint:"Solve each inequality separately, then find the overlap.",
 expl:"2x + 1 > 7 gives x > 3. 3x − 2 ≤ 19 gives x ≤ 7. The whole numbers 4, 5, 6, 7 satisfy both: 4 numbers."},
{lvl:3,sec:"L",type:"mc",q:"A number line has a closed circle at −2, an open circle at 4, and the segment between them shaded. Which inequality does it show?",mono:true,
 opts:["−2 ≤ x < 4","−2 < x ≤ 4","−2 < x < 4","−2 ≤ x ≤ 4"],a:0,
 expl:"The closed circle at −2 means −2 is included (≤), and the open circle at 4 means 4 is not (<). So −2 ≤ x < 4."},
{lvl:3,sec:"L",type:"in",q:"Nadia has $50. She wants to buy a $14 book and as many $6 pens as she can. At most how many pens can she buy?",ans:6,
 hint:"Write an inequality: 14 + 6p ≤ 50.",
 expl:"14 + 6p ≤ 50 gives 6p ≤ 36, so p ≤ 6. She can buy at most 6 pens."}
],

"g5-rateeq": [
{sec:"L",type:"in",q:"A car travels at 60 km per hour. Using distance = rate × time, how far does it go in 2.5 hours, in km?",ans:150,
 expl:"d = 60 × 2.5 = 150 km."},
{sec:"L",type:"in",q:"What is 15% of 80?",ans:12,hint:"15% = 0.15.",
 expl:"0.15 × 80 = 12."},
{sec:"L",type:"in",q:"Ravi walks 12 km in 3 hours. What is his speed in km per hour?",ans:4,
 expl:"Speed = distance ÷ time = 12 ÷ 3 = 4 km per hour."},
{lvl:2,sec:"L",type:"in",q:"24 is 30% of what number?",ans:80,hint:"Write 0.3 × n = 24 and solve.",
 expl:"0.3n = 24, so n = 24 ÷ 0.3 = 80."},
{lvl:2,sec:"L",type:"in",q:"A jacket costs $60 and is on sale for 25% off. What is the sale price in dollars?",ans:45,
 expl:"25% of 60 is 15, so the sale price is 60 − 15 = $45. (Or 0.75 × 60 = 45.)"},
{lvl:2,sec:"L",type:"mc",q:"Which equation would you solve to find the time t (in hours) for a train at 80 km/h to cover 200 km?",mono:true,
 opts:["80t = 200","200t = 80","t = 80 × 200","80 + t = 200"],a:0,
 expl:"Distance = rate × time, so 200 = 80t. Solving gives t = 2.5 hours."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY statement that is true.",
 opts:["20% of 50 is 10","50% of 20 is 10","10% of 200 is 2","25% of 80 is 20"],aMulti:[0,1,3],
 expl:"0.2 × 50 = 10, 0.5 × 20 = 10 and 0.25 × 80 = 20 are all correct. 10% of 200 is 20, not 2."},
{lvl:3,sec:"L",type:"in",q:"A price rose by 20% to $72. What was the original price in dollars?",ans:60,
 hint:"The new price is 120% of the old price.",
 expl:"1.2 × p = 72, so p = 72 ÷ 1.2 = 60. The original price was $60."},
{lvl:3,sec:"L",type:"in",q:"Two cyclists start 45 km apart and ride towards each other, one at 12 km/h and the other at 18 km/h. After how many hours do they meet? Give a decimal.",ans:1.5,
 hint:"How fast is the gap between them closing?",
 expl:"The gap closes at 12 + 18 = 30 km/h. Solving 30t = 45 gives t = 1.5 hours."},
{lvl:3,sec:"L",type:"in",q:"A shirt is marked up by 50% and then discounted by 20%. The final price is $48. What was the original price in dollars?",ans:40,
 hint:"Multiply the two percentage changes together first.",
 expl:"1.5 × 0.8 = 1.2, so the final price is 1.2 times the original. 1.2p = 48 gives p = 40."}
],

"g5-formulas": [
{sec:"L",type:"mc",q:"Rearrange P = 4s (perimeter of a square) to make s the subject.",mono:true,
 opts:["s = P ÷ 4","s = 4P","s = P − 4","s = 4 ÷ P"],a:0,
 expl:"Divide both sides by 4: s = P ÷ 4."},
{sec:"L",type:"mc",q:"Rearrange d = rt (distance = rate × time) to make t the subject.",mono:true,
 opts:["t = d ÷ r","t = d × r","t = r ÷ d","t = d − r"],a:0,
 expl:"Divide both sides by r: t = d ÷ r."},
{sec:"L",type:"in",q:"Using A = lw, a rectangle has area 54 cm² and length 9 cm. What is its width in cm?",ans:6,
 expl:"w = A ÷ l = 54 ÷ 9 = 6 cm."},
{lvl:2,sec:"L",type:"mc",q:"Rearrange y = 2x + 3 to make x the subject.",mono:true,
 opts:["x = (y − 3) ÷ 2","x = (y + 3) ÷ 2","x = y ÷ 2 − 3","x = 2y − 3"],a:0,
 hint:"Undo the + 3 before undoing the × 2.",
 expl:"Subtract 3: y − 3 = 2x. Divide by 2: x = (y − 3) ÷ 2."},
{lvl:2,sec:"L",type:"in",q:"Using C = 2πr with π ≈ 3.14, a circle has circumference 31.4 cm. What is its radius in cm?",ans:5,
 expl:"r = C ÷ (2π) = 31.4 ÷ 6.28 = 5 cm."},
{lvl:2,sec:"L",type:"mc",q:"Rearrange the triangle area formula A = (1/2)bh to make h the subject.",mono:true,
 opts:["h = 2A ÷ b","h = A ÷ (2b)","h = 2b ÷ A","h = A − b ÷ 2"],a:0,
 expl:"Multiply both sides by 2: 2A = bh. Divide by b: h = 2A ÷ b."},
{lvl:3,sec:"L",type:"in",q:"The formula F = (9/5)C + 32 converts Celsius to Fahrenheit. Rearrange it and find C when F = 77.",ans:25,
 hint:"Subtract 32 first, then undo the multiplication by 9/5.",
 expl:"C = (F − 32) × 5/9. With F = 77: (77 − 32) × 5/9 = 45 × 5/9 = 25."},
{lvl:3,sec:"L",type:"in",q:"The perimeter of a rectangle is P = 2l + 2w. If P = 38 and l = 12, what is w?",ans:7,
 expl:"Rearranging: w = (P − 2l) ÷ 2 = (38 − 24) ÷ 2 = 14 ÷ 2 = 7."},
{lvl:3,sec:"L",type:"multi",q:"Select EVERY formula that is a correct rearrangement of V = lwh.",mono:true,
 opts:["h = V ÷ (lw)","l = V ÷ (wh)","w = Vlh","h = V − lw"],aMulti:[0,1],
 expl:"Dividing V = lwh by the other two variables gives h = V ÷ (lw) and l = V ÷ (wh). The other two are not rearrangements of a product."}
],

"g5-functions": [
{sec:"L",type:"in",q:"A function machine multiplies the input by 3 and then adds 2. What is the output when the input is 4?",ans:14,
 expl:"3 × 4 = 12, then 12 + 2 = 14."},
{sec:"L",type:"in",q:"If f(x) = 2x + 5, what is f(3)?",ans:11,hint:"Replace x with 3.",
 expl:"f(3) = 2 × 3 + 5 = 11."},
{sec:"L",type:"mc",q:"Which rule matches the table: input 1 → 4, input 2 → 7, input 3 → 10?",
 opts:["output = 3 × input + 1","output = input + 3","output = 4 × input","output = 2 × input + 2"],a:0,
 expl:"The output rises by 3 each time, so the rule involves 3 × input. 3 × 1 + 1 = 4, 3 × 2 + 1 = 7, 3 × 3 + 1 = 10."},
{lvl:2,sec:"L",type:"in",q:"If f(x) = x² − 1, what is f(5)?",ans:24,
 expl:"f(5) = 5² − 1 = 25 − 1 = 24."},
{lvl:2,sec:"L",type:"in",q:"A function machine uses the rule output = 4 × input − 3. What input gives an output of 25?",ans:7,
 hint:"Work backwards: undo the − 3, then undo the × 4.",
 expl:"4 × input − 3 = 25, so 4 × input = 28 and the input is 7."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY list of (input, output) pairs that could come from a function (each input has exactly one output).",mono:true,
 opts:["(1, 2), (2, 4), (3, 6)","(1, 5), (2, 5), (3, 5)","(1, 2), (1, 3), (2, 4)","(0, 1), (1, 1), (0, 2)"],aMulti:[0,1],
 expl:"In the first two lists every input appears once, so each has one output (a constant output is allowed). In the third, input 1 gives both 2 and 3; in the fourth, input 0 gives both 1 and 2."},
{lvl:2,sec:"L",type:"mc",q:"Which point lies on the graph of y = 2x − 1?",mono:true,opts:["(3, 5)","(2, 5)","(1, 3)","(4, 6)"],a:0,
 expl:"For x = 3, y = 2 × 3 − 1 = 5, so (3, 5) is on the graph. The others would need y = 3, 1 and 7."},
{lvl:3,sec:"L",type:"in",q:"If f(x) = 3x + 1 and g(x) = x − 2, what is f(g(6))?",ans:13,hint:"Find g(6) first, then put that into f.",
 expl:"g(6) = 6 − 2 = 4, then f(4) = 3 × 4 + 1 = 13."},
{lvl:3,sec:"L",type:"in",q:"A taxi charges $3 plus $2 per km, so cost = 3 + 2k. Wei pays $25. How many km was the ride?",ans:11,
 expl:"3 + 2k = 25, so 2k = 22 and k = 11 km."},
{lvl:3,sec:"L",type:"in",q:"A linear function has f(2) = 7 and f(5) = 16. What is f(10)?",ans:31,
 hint:"How much does the output change for each 1 increase in the input?",
 expl:"From x = 2 to x = 5 the output rises 9 over 3 steps, so 3 per step. f(x) = 3x + 1 (check: 3 × 2 + 1 = 7). f(10) = 31."}
],

"g5-pythag": [
{sec:"G",type:"in",q:"A right triangle has legs 3 cm and 4 cm. What is the length of the hypotenuse in cm?",ans:5,
 hint:"Square the legs, add, then take the square root.",
 expl:"3² + 4² = 9 + 16 = 25, and √25 = 5. The hypotenuse is 5 cm."},
{sec:"G",type:"in",q:"A right triangle has legs 6 and 8. What is the length of the hypotenuse?",ans:10,
 expl:"6² + 8² = 36 + 64 = 100, and √100 = 10."},
{sec:"G",type:"mc",q:"In a right triangle with legs a and b and hypotenuse c, which statement is always true?",mono:true,
 opts:["a² + b² = c²","a + b = c","a² − b² = c²","a × b = c"],a:0,
 expl:"The Pythagorean Theorem says the squares of the legs add to the square of the hypotenuse: a² + b² = c²."},
{lvl:2,sec:"G",type:"in",q:"A right triangle has hypotenuse 13 cm and one leg 5 cm. What is the other leg in cm?",ans:12,
 hint:"Subtract the squares this time.",
 expl:"13² − 5² = 169 − 25 = 144, and √144 = 12. The other leg is 12 cm."},
{lvl:2,sec:"G",type:"in",q:"A 10 m ladder leans against a wall with its foot 6 m from the wall. How far up the wall does it reach, in m?",ans:8,
 expl:"The ladder is the hypotenuse: 10² − 6² = 100 − 36 = 64, so the height is √64 = 8 m."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY set of side lengths that makes a right triangle.",mono:true,
 opts:["5, 12, 13","8, 15, 17","7, 24, 25","6, 7, 8"],aMulti:[0,1,2],
 expl:"25 + 144 = 169 = 13², 64 + 225 = 289 = 17² and 49 + 576 = 625 = 25². But 36 + 49 = 85, which is not 8² = 64."},
{lvl:3,sec:"G",type:"in",q:"A rectangle is 9 cm by 12 cm. What is the length of its diagonal in cm?",ans:15,
 hint:"The diagonal splits the rectangle into two right triangles.",
 expl:"The diagonal is the hypotenuse of a right triangle with legs 9 and 12: 81 + 144 = 225, and √225 = 15 cm."},
{lvl:3,sec:"G",type:"in",q:"The two legs of a right triangle are 20 cm and 21 cm. What is the perimeter of the triangle in cm?",ans:70,
 hint:"Find the hypotenuse first.",
 expl:"20² + 21² = 400 + 441 = 841 = 29², so the hypotenuse is 29. Perimeter = 20 + 21 + 29 = 70 cm."},
{lvl:3,sec:"G",type:"in",q:"Lior walks 5 km north, then 12 km east, then 4 km further north. How far is she from her starting point in a straight line, in km?",ans:15,
 hint:"Combine the two northward parts first.",
 expl:"She ends 9 km north and 12 km east of the start. 9² + 12² = 81 + 144 = 225, so the distance is √225 = 15 km."}
],

"g5-distance": [
{sec:"G",type:"in",q:"What is the distance between the points (2, 3) and (9, 3)?",ans:7,
 hint:"The points are on the same horizontal line.",
 expl:"Both points have y = 3, so the distance is the difference in x: 9 − 2 = 7."},
{sec:"G",type:"in",q:"What is the distance between (0, 0) and (3, 4)?",ans:5,
 expl:"The horizontal change is 3 and the vertical change is 4. √(3² + 4²) = √25 = 5."},
{sec:"G",type:"mc",q:"Which formula gives the distance between (x₁, y₁) and (x₂, y₂)?",mono:true,
 opts:["√((x₂ − x₁)² + (y₂ − y₁)²)","(x₂ − x₁) + (y₂ − y₁)","√((x₂ + x₁)² + (y₂ + y₁)²)","(x₂ − x₁)² + (y₂ − y₁)²"],a:0,
 expl:"The distance is the hypotenuse of a right triangle whose legs are the changes in x and y, so it is √((x₂ − x₁)² + (y₂ − y₁)²)."},
{lvl:2,sec:"G",type:"in",q:"What is the distance between (1, 2) and (7, 10)?",ans:10,
 expl:"Changes: 7 − 1 = 6 and 10 − 2 = 8. √(36 + 64) = √100 = 10."},
{lvl:2,sec:"G",type:"in",q:"What is the distance between (−3, 1) and (2, 13)?",ans:13,hint:"Careful with the negative x-value.",
 expl:"Changes: 2 − (−3) = 5 and 13 − 1 = 12. √(25 + 144) = √169 = 13."},
{lvl:2,sec:"G",type:"mc",q:"Which point is closest to the origin (0, 0)?",mono:true,
 opts:["(3, 2)","(4, 0)","(1, 4)","(−3, −3)"],a:0,hint:"Compare the squared distances; no square roots needed.",
 expl:"Squared distances: 9 + 4 = 13, 16, 1 + 16 = 17, and 9 + 9 = 18. The smallest is 13, for (3, 2)."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY point that is exactly 5 units from (0, 0).",mono:true,
 opts:["(3, 4)","(−5, 0)","(4, −3)","(2, 3)"],aMulti:[0,1,2],
 expl:"3² + 4² = 25, (−5)² + 0² = 25 and 4² + (−3)² = 25, so those three are 5 units away. 2² + 3² = 13, so (2, 3) is not."},
{lvl:3,sec:"G",type:"in",q:"A triangle has vertices (0, 0), (6, 0) and (6, 8). What is its perimeter?",ans:24,
 hint:"Two sides are horizontal or vertical; the third needs the distance formula.",
 expl:"The sides are 6 (from (0, 0) to (6, 0)), 8 (from (6, 0) to (6, 8)) and √(36 + 64) = 10. Perimeter = 6 + 8 + 10 = 24."},
{lvl:3,sec:"G",type:"in",q:"Point A is (2, 5). Point B is (10, y) with y greater than 5, and B is exactly 10 units from A. What is y?",ans:11,
 hint:"The horizontal change is 8. What vertical change makes the distance 10?",
 expl:"The horizontal change is 8, so the vertical change v satisfies 64 + v² = 100, giving v = 6. Then y = 5 + 6 = 11."},
{lvl:3,sec:"G",type:"in",q:"What is the SQUARE of the distance between (−4, 7) and (3, −1)?",ans:113,
 expl:"Changes: 3 − (−4) = 7 and −1 − 7 = −8. The squared distance is 49 + 64 = 113."}
],

"g5-angletri": [
{sec:"G",type:"in",q:"Two angles of a triangle are 50° and 60°. What is the third angle in degrees?",ans:70,
 expl:"The angles of a triangle add to 180°. 180 − 50 − 60 = 70°."},
{sec:"G",type:"in",q:"What is the sum of the interior angles of a quadrilateral, in degrees?",ans:360,
 hint:"A diagonal splits it into two triangles.",
 expl:"A quadrilateral can be split into two triangles by a diagonal, so its angles add to 2 × 180 = 360°."},
{sec:"G",type:"mc",q:"A triangle has angles 90°, 45° and 45°. What kind of triangle is it?",
 opts:["Right isosceles","Equilateral","Scalene","Obtuse"],a:0,
 expl:"It has a right angle, and two equal angles mean two equal sides, so it is a right isosceles triangle."},
{lvl:2,sec:"G",type:"in",q:"Three angles of a quadrilateral are 80°, 95° and 110°. What is the fourth angle in degrees?",ans:75,
 expl:"80 + 95 + 110 = 285, and 360 − 285 = 75°."},
{lvl:2,sec:"G",type:"in",q:"An isosceles triangle has a vertex angle of 40°. What is the size of each base angle in degrees?",ans:70,
 hint:"The two base angles are equal.",
 expl:"The base angles share 180 − 40 = 140°, so each is 70°."},
{lvl:2,sec:"G",type:"in",q:"The angles of a triangle are x, 2x and 3x. What is x in degrees?",ans:30,
 expl:"x + 2x + 3x = 6x = 180, so x = 30°."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY set of angles that could be the three angles of a triangle.",mono:true,
 opts:["30°, 60°, 90°","20°, 70°, 90°","50°, 50°, 90°","60°, 60°, 60°"],aMulti:[0,1,3],
 expl:"The angles must add to 180°. 30 + 60 + 90, 20 + 70 + 90 and 60 + 60 + 60 all do; 50 + 50 + 90 = 190 does not."},
{lvl:3,sec:"G",type:"in",q:"An exterior angle of a triangle is 120°. One of the two opposite interior angles is 45°. What is the other opposite interior angle in degrees?",ans:75,
 hint:"An exterior angle equals the sum of the two opposite interior angles.",
 expl:"The exterior angle equals the sum of the two interior angles not next to it, so the other is 120 − 45 = 75°."},
{lvl:3,sec:"G",type:"in",q:"In parallelogram ABCD, angle A is 3 times angle B. What is angle A in degrees?",ans:135,
 hint:"Angles A and B are next to each other in a parallelogram.",
 expl:"Neighbouring angles in a parallelogram add to 180°. B + 3B = 180 gives B = 45, so A = 135°."},
{lvl:3,sec:"G",type:"in",q:"The angles of a quadrilateral are in the ratio 1 : 2 : 3 : 4. What is the largest angle in degrees?",ans:144,
 expl:"The ratio has 1 + 2 + 3 + 4 = 10 parts, and 360 ÷ 10 = 36° per part. The largest angle is 4 × 36 = 144°."}
],

"g5-circarea": [
{sec:"G",type:"in",q:"A circle has radius 3 cm. Its area is kπ cm². What is k?",ans:9,
 expl:"Area = πr² = π × 3² = 9π cm², so k = 9."},
{sec:"G",type:"in",q:"Using π ≈ 3.14, what is the area of a circle with radius 10 cm, in cm²?",ans:314,
 expl:"Area = πr² ≈ 3.14 × 100 = 314 cm²."},
{sec:"G",type:"mc",q:"Which formula gives the area of a circle?",mono:true,opts:["πr²","2πr","πd","πr"],a:0,
 expl:"The area of a circle is π times the radius squared: πr². (2πr is the circumference.)"},
{lvl:2,sec:"G",type:"in",q:"A circle has diameter 12 cm. Its area is kπ cm². What is k?",ans:36,
 hint:"Find the radius first.",
 expl:"The radius is 6 cm, so the area is π × 6² = 36π cm². k = 36."},
{lvl:2,sec:"G",type:"in",q:"A quarter-circle (a 90° sector) has radius 8 cm. Its area is kπ cm². What is k?",ans:16,
 expl:"The full circle has area 64π. A quarter of that is 16π, so k = 16."},
{lvl:2,sec:"G",type:"mc",q:"A sector has an angle of 60° at the centre. What fraction of the whole circle's area is it?",mono:true,
 opts:["1/6","1/3","1/4","1/60"],a:0,
 expl:"A full turn is 360°, and 60 ÷ 360 = 1/6."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY statement that is true for a circle of radius 2.",mono:true,
 opts:["Area = 4π","Circumference = 4π","Area = 2π","Diameter = 4"],aMulti:[0,1,3],
 expl:"Area = π × 2² = 4π, circumference = 2π × 2 = 4π, and the diameter is 2 × 2 = 4. Area = 2π is wrong."},
{lvl:3,sec:"G",type:"in",q:"A circle of radius 5 has a sector with a centre angle of 72°. The sector's area is kπ. What is k?",ans:5,
 hint:"What fraction of a full turn is 72°?",
 expl:"72 ÷ 360 = 1/5. The full circle has area 25π, so the sector has area 25π ÷ 5 = 5π. k = 5."},
{lvl:3,sec:"G",type:"in",q:"A ring is the region between two circles with the same centre, of radii 7 cm and 4 cm. Its area is kπ cm². What is k?",ans:33,
 hint:"Subtract the small circle's area from the large circle's.",
 expl:"49π − 16π = 33π cm², so k = 33."},
{lvl:3,sec:"G",type:"in",q:"A circle has area 49π cm². Its circumference is kπ cm. What is k?",ans:14,
 hint:"Use the area to find the radius first.",
 expl:"πr² = 49π gives r = 7. Circumference = 2πr = 14π cm, so k = 14."}
],

"g5-cylinder": [
{sec:"G",type:"in",q:"A cylinder has radius 2 cm and height 5 cm. Its volume is kπ cm³. What is k?",ans:20,
 expl:"Volume = πr²h = π × 4 × 5 = 20π cm³, so k = 20."},
{sec:"G",type:"mc",q:"Which formula gives the volume of a cylinder with radius r and height h?",mono:true,
 opts:["πr²h","2πrh","πrh","πr² + h"],a:0,
 expl:"Volume = (area of the circular base) × height = πr² × h."},
{sec:"G",type:"in",q:"Using π ≈ 3.14, find the volume of a cylinder with radius 1 cm and height 10 cm, in cm³.",ans:31.4,
 expl:"Volume = πr²h ≈ 3.14 × 1 × 10 = 31.4 cm³."},
{lvl:2,sec:"G",type:"in",q:"A cylinder has diameter 10 cm and height 3 cm. Its volume is kπ cm³. What is k?",ans:75,
 hint:"Halve the diameter to get the radius.",
 expl:"The radius is 5 cm, so the volume is π × 25 × 3 = 75π cm³. k = 75."},
{lvl:2,sec:"G",type:"in",q:"A cylinder has radius 3 cm and volume 90π cm³. What is its height in cm?",ans:10,
 expl:"π × 9 × h = 90π, so h = 90 ÷ 9 = 10 cm."},
{lvl:2,sec:"G",type:"in",q:"A cylinder with radius 4 cm and height 6 cm has a curved (side) surface area of kπ cm². What is k?",ans:48,
 hint:"Unrolled, the curved surface is a rectangle whose width is the circumference.",
 expl:"Curved surface = circumference × height = 2π × 4 × 6 = 48π cm². k = 48."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY change that exactly doubles the volume of a cylinder.",
 opts:["Doubling the height","Doubling the radius","Doubling the diameter","Halving the radius and doubling the height"],aMulti:[0],
 expl:"Volume = πr²h, so doubling h doubles the volume. Doubling r (or the diameter) multiplies it by 4. Halving r and doubling h gives 1/4 × 2 = 1/2."},
{lvl:3,sec:"G",type:"in",q:"A closed cylinder has radius 5 cm and height 5 cm. Its total surface area (top, bottom and curved side) is kπ cm². What is k?",ans:100,
 hint:"Add two circles and the curved rectangle.",
 expl:"Two ends: 2 × 25π = 50π. Curved side: 2π × 5 × 5 = 50π. Total 100π cm², so k = 100."},
{lvl:3,sec:"G",type:"in",q:"Cylinder A has radius 3 and height 8. Cylinder B has radius 6 and height 2. What is (volume of A) ÷ (volume of B)?",ans:1,
 expl:"A: π × 9 × 8 = 72π. B: π × 36 × 2 = 72π. The volumes are equal, so the ratio is 1."},
{lvl:3,sec:"G",type:"in",q:"Using π ≈ 3.14, a can has radius 4 cm and height 10 cm. A bucket holds 5 litres (1 litre = 1000 cm³). How many full cans of water are needed to fill the bucket?",ans:10,
 hint:"Find one can's volume, then see how many are needed to reach 5000 cm³.",
 expl:"One can holds 3.14 × 16 × 10 = 502.4 cm³. Nine cans give 4521.6 cm³, not enough; ten cans give 5024 cm³. So 10 cans are needed."}
],

"g5-permrep": [
{sec:"K",type:"in",q:"How many different 3-letter codes can be made from the letters A, B and C if letters may be repeated?",ans:27,
 hint:"Each position has the same number of choices.",expl:"There are 3 choices for each of the 3 positions: 3 × 3 × 3 = 27 codes."},
{sec:"K",type:"in",q:"How many different arrangements of the letters in the word 'MOM' are there?",ans:3,
 hint:"Two of the letters are identical, so some arrangements look the same.",
 expl:"3! = 6 arrangements if the letters were all different, but swapping the two identical Ms changes nothing, so divide by 2! = 2. 6 ÷ 2 = 3 (MOM, MMO, OMM)."},
{sec:"K",type:"mc",q:"A 4-digit PIN uses the digits 0 to 9, and digits may repeat. How many different PINs are possible?",mono:true,
 opts:["10,000","5,040","40","10"],a:0,
 expl:"Each of the 4 positions has 10 choices: 10 × 10 × 10 × 10 = 10,000 PINs."},
{lvl:2,sec:"K",type:"in",q:"How many different arrangements of the letters in the word 'BOOK' are there?",ans:12,
 expl:"4! = 24 arrangements of four letters, divided by 2! = 2 for the two identical Os: 24 ÷ 2 = 12."},
{lvl:2,sec:"K",type:"in",q:"How many different arrangements of the letters in the word 'LEVEL' are there?",ans:30,
 hint:"Two letters are each repeated twice.",
 expl:"5! = 120, divided by 2! for the two Ls and 2! for the two Es: 120 ÷ (2 × 2) = 30."},
{lvl:2,sec:"K",type:"mc",q:"Which expression counts the different arrangements of the letters in 'BANANA'?",mono:true,
 opts:["6! ÷ (3! × 2!)","6! ÷ (3! + 2!)","6! × 3! × 2!","6! ÷ (3 × 2)"],a:0,
 expl:"There are 6 letters with 3 As and 2 Ns, so the count is 6! ÷ (3! × 2!) = 720 ÷ 12 = 60."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY word that has exactly 12 different arrangements of its letters.",
 opts:["BOOK","DEED","TREE","PEEP"],aMulti:[0,2],
 expl:"BOOK and TREE each have one repeated pair: 4! ÷ 2! = 12. DEED and PEEP have two repeated pairs: 4! ÷ (2! × 2!) = 6."},
{lvl:3,sec:"K",type:"in",q:"How many different arrangements of the letters in the word 'BALLOON' are there?",ans:1260,
 hint:"Count the repeated letters first.",
 expl:"7 letters with two Ls and two Os: 7! ÷ (2! × 2!) = 5040 ÷ 4 = 1260."},
{lvl:3,sec:"K",type:"in",q:"How many arrangements of the letters in 'APPLE' start with the letter P?",ans:24,
 hint:"Put a P in the first place, then arrange what is left.",
 expl:"After placing a P first, the remaining letters A, P, L, E are all different, so they can be arranged in 4! = 24 ways."},
{lvl:3,sec:"K",type:"in",q:"Kenji walks on a grid. He must make exactly 3 moves right and 2 moves up, in any order. How many different routes can he take?",ans:10,
 hint:"A route is a word made from three Rs and two Us.",
 expl:"Each route is an arrangement of RRRUU: 5! ÷ (3! × 2!) = 120 ÷ 12 = 10 routes."}
],

"g5-combrep": [
{sec:"K",type:"in",q:"An ice-cream shop has 3 flavours. Amara chooses 2 scoops, and both scoops may be the same flavour. Order does not matter. How many different choices does she have?",ans:6,
 hint:"Count the double scoops and the mixed scoops separately.",
 expl:"There are 3 choices with both scoops the same flavour and 3 choices of two different flavours: 3 + 3 = 6."},
{sec:"K",type:"mc",q:"Lior takes 2 marbles from a jar that has lots of red marbles and lots of blue marbles. How many different colour combinations can he get?",mono:true,
 opts:["3","2","4","6"],a:0,
 expl:"The possibilities are red-red, blue-blue and red-blue: 3 combinations."},
{sec:"K",type:"in",q:"How many different collections of 3 coins can you make using only 1-cent coins and 5-cent coins? (There are plenty of each, and order does not matter.)",ans:4,
 expl:"The collections are decided by how many 1-cent coins there are: 0, 1, 2 or 3. That is 4 collections."},
{lvl:2,sec:"K",type:"in",q:"A bakery sells 4 kinds of doughnut. How many different boxes of 2 doughnuts can be made if the two may be the same kind?",ans:10,
 hint:"Split into 'same kind' and 'different kinds'.",
 expl:"4 boxes with two of the same kind, plus 6 boxes with two different kinds (choose 2 kinds from 4): 4 + 6 = 10."},
{lvl:2,sec:"K",type:"in",q:"In how many ways can 5 identical stickers be shared between 2 children, if a child may get none?",ans:6,
 expl:"The first child can get 0, 1, 2, 3, 4 or 5 stickers and the second child gets the rest: 6 ways."},
{lvl:2,sec:"K",type:"mc",q:"In how many ways can 4 identical sweets be shared among 3 children, if a child may get none?",mono:true,
 opts:["15","12","10","6"],a:0,hint:"Fix how many the first child gets, then count the rest.",
 expl:"If the first child gets 0 sweets there are 5 ways to split the rest, then 4, 3, 2 and 1 ways as the first child gets 1, 2, 3 or 4. Total 5 + 4 + 3 + 2 + 1 = 15."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY problem that is a combination with repetition (order does not matter and repeats are allowed).",
 opts:["Choosing 3 scoops from 5 flavours, repeats allowed","Choosing a 3-digit PIN where digits may repeat","Picking 2 different pupils for a team","Buying 4 fruits from a stall selling apples and pears"],aMulti:[0,3],
 expl:"The scoops and the fruits can repeat and their order does not matter. A PIN has order, and picking different pupils has no repeats."},
{lvl:3,sec:"K",type:"in",q:"Ravi has 6 identical coins to put into 3 boxes labelled A, B and C. A box may be left empty. In how many ways can he do this?",ans:28,
 hint:"Count by how many coins box A gets.",
 expl:"If A gets 0 coins, the other 6 can be split between B and C in 7 ways; if A gets 1, in 6 ways; and so on down to 1 way. 7 + 6 + 5 + 4 + 3 + 2 + 1 = 28."},
{lvl:3,sec:"K",type:"in",q:"How many solutions in whole numbers (0 is allowed) does the equation x + y + z = 5 have?",ans:21,
 hint:"Fix x, then count the pairs (y, z).",
 expl:"For x = 0 there are 6 pairs (y, z), for x = 1 there are 5, then 4, 3, 2 and 1. Total 6 + 5 + 4 + 3 + 2 + 1 = 21."},
{lvl:3,sec:"K",type:"in",q:"Sofia buys 4 pastries from a shop that sells 3 kinds. She wants at least one of each kind. How many different purchases can she make?",ans:3,
 hint:"First give each kind one pastry; then decide the extra one.",
 expl:"Three of the pastries must be one of each kind. The fourth pastry can be any of the 3 kinds, so there are 3 purchases: (2,1,1), (1,2,1) and (1,1,2)."}
],

"g5-subsets": [
{sec:"K",type:"in",q:"How many subsets does the set {a, b, c} have, counting the empty set and the whole set?",ans:8,
 hint:"Each element is either in or out.",
 expl:"Each of the 3 elements is either in the subset or not: 2 × 2 × 2 = 8 subsets."},
{sec:"K",type:"mc",q:"Which of these is NOT a subset of {1, 2, 3}?",mono:true,opts:["{2, 4}","{ }","{1, 3}","{1, 2, 3}"],a:0,
 expl:"A subset can only use elements of the set. 4 is not in {1, 2, 3}, so {2, 4} is not a subset. The empty set and the whole set are subsets."},
{sec:"K",type:"in",q:"A set has 5 elements. How many subsets does it have?",ans:32,
 expl:"Each element is in or out, so there are 2⁵ = 32 subsets."},
{lvl:2,sec:"K",type:"in",q:"How many subsets of {1, 2, 3, 4, 5} have exactly 2 elements?",ans:10,
 expl:"Choose 2 of the 5 elements: 5 × 4 ÷ 2 = 10 subsets."},
{lvl:2,sec:"K",type:"in",q:"Priya can put any combination of 4 toppings on a pizza, including no toppings at all. How many different pizzas can she make?",ans:16,
 expl:"Each topping is either on or off: 2⁴ = 16 pizzas."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY true statement about the set {p, q, r, s}.",
 opts:["It has 16 subsets","It has 6 subsets with exactly 2 elements","It has 4 subsets with exactly 3 elements","It has 8 subsets with exactly 1 element"],aMulti:[0,1,2],
 expl:"2⁴ = 16 subsets in total; 6 pairs; 4 triples (leave out one element); but only 4 subsets with one element, not 8."},
{lvl:2,sec:"K",type:"mc",q:"How many subsets of {1, 2, 3, 4} contain the number 1?",mono:true,opts:["8","4","16","15"],a:0,
 hint:"1 is already in; what about the other elements?",
 expl:"1 must be in the subset. Each of 2, 3 and 4 is in or out: 2³ = 8 subsets."},
{lvl:3,sec:"K",type:"in",q:"How many non-empty subsets does a set with 6 elements have?",ans:63,
 expl:"There are 2⁶ = 64 subsets in total. Removing the empty set leaves 63."},
{lvl:3,sec:"K",type:"in",q:"How many subsets of {1, 2, 3, 4, 5, 6} contain at least one even number?",ans:56,
 hint:"Count the subsets with NO even numbers, then subtract.",
 expl:"There are 64 subsets in total. Subsets with no even number are subsets of {1, 3, 5}: 8 of them. 64 − 8 = 56."},
{lvl:3,sec:"K",type:"in",q:"Tomas has 7 different books. He wants to take at least 2 of them on a trip. How many different selections can he make?",ans:120,
 hint:"Start with all subsets, then remove the ones that are too small.",
 expl:"There are 2⁷ = 128 subsets. Remove the empty set and the 7 single-book choices: 128 − 1 − 7 = 120."}
],

"g5-inclexcl": [
{sec:"K",type:"in",q:"In a class, 12 pupils play football, 9 play basketball and 4 play both. How many pupils play at least one of the two sports?",ans:17,
 hint:"The 4 who play both were counted twice.",
 expl:"12 + 9 = 21 counts the 4 'both' pupils twice, so subtract them once: 21 − 4 = 17."},
{sec:"K",type:"mc",q:"Mei counts 8 pupils with a dog and 6 with a cat; 3 pupils have both. Why must she subtract 3 to count pupils with a dog or a cat?",
 opts:["Those 3 pupils were counted twice","Those 3 pupils have no pets","To make the answer smaller","Subtraction is always the last step"],a:0,
 expl:"The 3 pupils with both pets appear in the dog count and in the cat count, so subtracting 3 removes the double count: 8 + 6 − 3 = 11."},
{sec:"K",type:"in",q:"How many whole numbers from 1 to 20 are multiples of 2 or multiples of 3?",ans:13,
 expl:"Multiples of 2: 10. Multiples of 3: 6. Multiples of both (multiples of 6): 3. So 10 + 6 − 3 = 13."},
{lvl:2,sec:"K",type:"in",q:"Of 30 pupils, 18 like apples, 15 like bananas and 7 like both. How many like neither fruit?",ans:4,
 hint:"First find how many like at least one fruit.",
 expl:"At least one fruit: 18 + 15 − 7 = 26. Neither: 30 − 26 = 4."},
{lvl:2,sec:"K",type:"in",q:"How many whole numbers from 1 to 100 are multiples of 3 or multiples of 5?",ans:47,
 expl:"Multiples of 3: 33. Multiples of 5: 20. Multiples of 15: 6. So 33 + 20 − 6 = 47."},
{lvl:2,sec:"K",type:"mc",q:"25 pupils were surveyed. 14 have a brother, 11 have a sister and 5 have neither. How many have both a brother and a sister?",mono:true,
 opts:["5","0","10","3"],a:0,hint:"How many have at least one sibling?",
 expl:"At least one sibling: 25 − 5 = 20. Then 14 + 11 − both = 20, so both = 5."},
{lvl:2,sec:"K",type:"multi",q:"In a group, 10 children own a bike, 8 own a scooter, 3 own both, and everyone owns at least one. Select EVERY true statement.",
 opts:["There are 15 children in the group","7 children own only a bike","5 children own only a scooter","There are 18 children in the group"],aMulti:[0,1,2],
 expl:"Total = 10 + 8 − 3 = 15, not 18. Only a bike: 10 − 3 = 7. Only a scooter: 8 − 3 = 5."},
{lvl:3,sec:"K",type:"in",q:"How many whole numbers from 1 to 60 are NOT multiples of 2 and NOT multiples of 3?",ans:20,
 hint:"Count the numbers that ARE multiples of 2 or 3, then subtract from 60.",
 expl:"Multiples of 2 or 3: 30 + 20 − 10 = 40. So 60 − 40 = 20 numbers are neither."},
{lvl:3,sec:"K",type:"in",q:"In a class of 40, 20 play piano, 18 play guitar and 12 play drums. 8 play piano and guitar, 6 play guitar and drums, 5 play piano and drums, and 3 play all three. How many play none of the three?",ans:6,
 hint:"Add the singles, subtract the pairs, add back the triple.",
 expl:"At least one: 20 + 18 + 12 − 8 − 6 − 5 + 3 = 34. None: 40 − 34 = 6."},
{lvl:3,sec:"K",type:"in",q:"How many whole numbers from 1 to 100 are multiples of 2, 3 or 5?",ans:74,
 hint:"Three sets: use the pairs 6, 10 and 15, and the triple 30.",
 expl:"50 + 33 + 20 − 16 (multiples of 6) − 10 (of 10) − 6 (of 15) + 3 (of 30) = 74."}
],

"g5-pascal": [
{sec:"K",type:"in",q:"Row 4 of Pascal's triangle is 1 4 6 4 1 (row 0 is just '1'). What is the sum of the numbers in row 4?",ans:16,
 expl:"1 + 4 + 6 + 4 + 1 = 16, which is 2⁴."},
{sec:"K",type:"mc",q:"Which of these is row 5 of Pascal's triangle? (Row 0 is '1' and row 1 is '1 1'.)",mono:true,
 opts:["1 5 10 10 5 1","1 5 10 5 1","1 4 6 4 1","1 6 15 20 15 6 1"],a:0,
 expl:"Row 5 comes from adding neighbours in row 4 (1 4 6 4 1): 1, 1+4, 4+6, 6+4, 4+1, 1 = 1 5 10 10 5 1."},
{sec:"K",type:"in",q:"Each number inside Pascal's triangle is the sum of the two numbers above it. Row 5 is 1 5 10 10 5 1. What is the middle number of row 6, directly below the two 10s?",ans:20,
 expl:"10 + 10 = 20."},
{lvl:2,sec:"K",type:"in",q:"What is the third number in row 7 of Pascal's triangle? (The first two numbers are 1 and 7.)",ans:21,
 hint:"Build row 6 first, or think of choosing 2 things from 7.",
 expl:"Row 6 is 1 6 15 20 15 6 1, so the third number of row 7 is 6 + 15 = 21. It is also the number of ways to choose 2 things from 7."},
{lvl:2,sec:"K",type:"in",q:"Row 6 of Pascal's triangle is 1 6 15 20 15 6 1. How many ways are there to choose 2 pupils from a group of 6?",ans:15,
 expl:"The entry for 'choose 2 from 6' is the third number of row 6, which is 15."},
{lvl:2,sec:"K",type:"mc",q:"What is the sum of all the numbers in row 10 of Pascal's triangle?",mono:true,opts:["1024","100","512","2048"],a:0,
 hint:"Look at the sums of the first few rows.",
 expl:"The rows sum to 1, 2, 4, 8, ... so row n sums to 2ⁿ. Row 10 sums to 2¹⁰ = 1024."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY statement that is true about Pascal's triangle.",
 opts:["Every row starts and ends with 1","Each row reads the same backwards as forwards","Every row adds up to a power of 2","Every number in the triangle is odd"],aMulti:[0,1,2],
 expl:"Rows begin and end with 1, are symmetric, and sum to 2ⁿ. Row 2 contains the even number 2, so not every number is odd."},
{lvl:3,sec:"K",type:"in",q:"A row of Pascal's triangle starts 1, 9, ... What is the next number in that row?",ans:36,
 hint:"Which row starts 1, 9? Use the row above it.",
 expl:"This is row 9. Row 8 is 1 8 28 56 70 56 28 8 1, so the third number of row 9 is 8 + 28 = 36."},
{lvl:3,sec:"K",type:"in",q:"Row 8 of Pascal's triangle is 1 8 28 56 70 56 28 8 1. What is the sum of all the numbers in row 8 except the two 1s at the ends?",ans:254,
 expl:"Row 8 sums to 2⁸ = 256. Removing the two 1s leaves 256 − 2 = 254."},
{lvl:3,sec:"K",type:"in",q:"Diego walks from the top-left corner to the bottom-right corner of a grid of 4 by 4 squares, moving only right or down along the grid lines. How many different routes can he take?",ans:70,
 hint:"He needs 4 rights and 4 downs; look at row 8 of the triangle.",
 expl:"Each route is 8 moves with 4 of them 'right'. The number of ways to choose which 4 is the middle entry of row 8: 70."}
],

"g5-compound": [
{sec:"S",type:"in",q:"A fair coin is flipped twice. What is the probability of getting two heads? Write it as a decimal.",ans:0.25,
 hint:"List all the equally likely outcomes.",
 expl:"The outcomes are HH, HT, TH, TT. Only HH works: 1 out of 4 = 0.25."},
{sec:"S",type:"mc",q:"Two fair coins are flipped. What is the probability of getting exactly one head?",mono:true,
 opts:["1/2","1/4","3/4","1/3"],a:0,
 expl:"Of the outcomes HH, HT, TH, TT, two have exactly one head: 2/4 = 1/2."},
{sec:"S",type:"in",q:"Femi rolls a fair 6-sided die and then flips a coin. How many equally likely outcomes are there altogether?",ans:12,
 expl:"6 results for the die × 2 results for the coin = 12 outcomes."},
{lvl:2,sec:"S",type:"mc",q:"Two fair 6-sided dice are rolled. What is the probability that both show a 6?",mono:true,
 opts:["1/36","1/12","1/6","2/6"],a:0,
 expl:"Each die shows 6 with probability 1/6 and the rolls are independent: 1/6 × 1/6 = 1/36."},
{lvl:2,sec:"S",type:"mc",q:"A spinner has 4 equal sections: red, blue, green and yellow. It is spun twice. What is the probability of red first, then blue?",mono:true,
 opts:["1/16","1/8","1/4","2/4"],a:0,
 expl:"P(red) = 1/4 and P(blue) = 1/4, so P(red then blue) = 1/4 × 1/4 = 1/16."},
{lvl:2,sec:"S",type:"in",q:"A bag has 3 red and 2 blue marbles. Elias takes one marble, puts it back, then takes another. What is the probability that both marbles are red? Write it as a decimal.",ans:0.36,
 hint:"Because he puts the first marble back, the second pick has the same chances as the first.",
 expl:"P(red) = 3/5 each time, so P(both red) = 3/5 × 3/5 = 9/25 = 0.36."},
{lvl:2,sec:"S",type:"multi",q:"Select EVERY pair of events that is independent (the first does not change the chances of the second).",
 opts:["Flipping a coin, then rolling a die","Drawing a card and keeping it, then drawing another","Spinning a spinner twice","Eating a sweet from a bag, then taking another"],aMulti:[0,2],
 expl:"A coin and a die, or two spins, do not affect each other. Keeping a card or eating a sweet changes what is left, so the second event depends on the first."},
{lvl:3,sec:"S",type:"in",q:"Two fair 6-sided dice are rolled. The probability that the total is 7 can be written as k/36. What is k?",ans:6,
 hint:"List the pairs that add to 7.",
 expl:"The pairs are (1,6), (2,5), (3,4), (4,3), (5,2), (6,1): 6 of the 36 outcomes, so k = 6."},
{lvl:3,sec:"S",type:"in",q:"A fair coin is flipped 3 times. What is the probability of getting at least one tail? Write it as a decimal.",ans:0.875,
 hint:"Find the chance of the opposite: no tails at all.",
 expl:"P(no tails) = P(HHH) = 1/8. So P(at least one tail) = 1 − 1/8 = 7/8 = 0.875."},
{lvl:3,sec:"S",type:"mc",q:"Hana spins two spinners. Spinner A has 3 equal sections numbered 1, 2, 3. Spinner B has 4 equal sections numbered 1, 2, 3, 4. What is the probability that the two numbers she gets are equal?",mono:true,
 opts:["1/4","1/3","3/7","1/12"],a:0,
 expl:"There are 3 × 4 = 12 outcomes. The equal ones are (1,1), (2,2), (3,3): 3/12 = 1/4."}
],

"g5-expected": [
{sec:"S",type:"in",q:"A fair 6-sided die is rolled many times. What is the expected value (the long-run average) of one roll?",ans:3.5,
 hint:"Average the six equally likely results.",
 expl:"(1 + 2 + 3 + 4 + 5 + 6) ÷ 6 = 21 ÷ 6 = 3.5."},
{sec:"S",type:"mc",q:"What does the expected value of a game tell you?",
 opts:["The average result over many plays","The most likely result on one play","The largest result that can happen","The result you get on the first play"],a:0,
 expl:"Expected value is the average you would get if you played many, many times. It may not be a result that can actually happen on one play."},
{sec:"S",type:"in",q:"A fair coin is flipped. Heads wins 4 points and tails wins 0 points. What is the expected number of points per flip?",ans:2,
 expl:"Half the flips give 4 points and half give 0: 1/2 × 4 + 1/2 × 0 = 2 points."},
{lvl:2,sec:"S",type:"in",q:"A spinner has 4 equal sections labelled 1, 2, 3 and 8. What is the expected value of one spin?",ans:3.5,
 expl:"Each section has probability 1/4: (1 + 2 + 3 + 8) ÷ 4 = 14 ÷ 4 = 3.5."},
{lvl:2,sec:"S",type:"in",q:"Yusuf rolls a fair 6-sided die. He wins $6 if it shows a 6 and nothing otherwise. What are his expected winnings per roll, in dollars?",ans:1,
 expl:"P(6) = 1/6, so the expected winnings are 1/6 × $6 = $1."},
{lvl:2,sec:"S",type:"mc",q:"A raffle sells 100 tickets and has one prize of $50. What is the expected value of one ticket?",mono:true,
 opts:["$0.50","$5","$50","$2"],a:0,
 expl:"Each ticket wins with probability 1/100, so its expected value is 1/100 × $50 = $0.50."},
{lvl:2,sec:"S",type:"in",q:"A bag has 2 gold coins worth 10 points each and 3 silver coins worth 5 points each. Noor takes one coin at random. What is the expected number of points they get?",ans:7,
 hint:"Weight each value by its probability.",
 expl:"P(gold) = 2/5 and P(silver) = 3/5: 2/5 × 10 + 3/5 × 5 = 4 + 3 = 7 points."},
{lvl:3,sec:"S",type:"in",q:"A game costs $2 to play. You roll a fair die: a 6 wins $12, a 5 wins $3, and anything else wins nothing. What is the expected profit per game, in dollars? (Profit means winnings minus the cost.)",ans:0.5,
 hint:"Find the expected winnings first, then take away the cost.",
 expl:"Expected winnings: 1/6 × 12 + 1/6 × 3 = 2 + 0.5 = $2.50. Profit: 2.50 − 2 = $0.50."},
{lvl:3,sec:"S",type:"in",q:"Three fair coins are flipped. What is the expected number of heads?",ans:1.5,
 hint:"Each coin gives half a head on average.",
 expl:"Each coin contributes 0.5 heads on average, so 3 × 0.5 = 1.5. Checking with outcomes: (0×1 + 1×3 + 2×3 + 3×1) ÷ 8 = 12 ÷ 8 = 1.5."},
{lvl:3,sec:"S",type:"multi",q:"A spinner has 5 equal sections showing 0, 0, 5, 5 and 10. Select EVERY true statement.",
 opts:["The expected value is 4","The expected value is 5","In 100 spins you would expect about 400 points in total","The expected value must be one of the numbers on the spinner"],aMulti:[0,2],
 expl:"(0 + 0 + 5 + 5 + 10) ÷ 5 = 20 ÷ 5 = 4, so 100 spins give about 400 points. The expected value is an average and need not appear on the spinner."}
],

"g5-geoprob": [
{sec:"S",type:"in",q:"A square target has side 10 cm, and a square bullseye of side 5 cm sits in the middle. A dart lands at a random point on the target. What is the probability it lands in the bullseye? Write it as a decimal.",ans:0.25,
 hint:"Compare the two areas.",
 expl:"Bullseye area 25 cm² out of 100 cm²: 25 ÷ 100 = 0.25."},
{sec:"S",type:"mc",q:"A rectangular board is 8 units by 6 units. A shaded rectangle on it is 4 units by 3 units. A point is chosen at random on the board. What is the probability it is in the shaded part?",mono:true,
 opts:["1/4","1/2","1/8","1/3"],a:0,
 expl:"Shaded area 12 out of total area 48: 12/48 = 1/4."},
{sec:"S",type:"in",q:"A point is chosen at random on a number line segment from 0 to 10. What is the probability that it lies between 2 and 5? Write it as a decimal.",ans:0.3,
 expl:"The part from 2 to 5 has length 3 out of 10: 3 ÷ 10 = 0.3."},
{lvl:2,sec:"S",type:"mc",q:"A circle of radius 2 is drawn inside a square of side 4, touching all four sides. A point is chosen at random inside the square. What is the probability it is inside the circle?",mono:true,
 opts:["π/4","1/4","π/2","1/2"],a:0,
 expl:"Circle area = π × 2² = 4π; square area = 16. Probability = 4π/16 = π/4."},
{lvl:2,sec:"S",type:"in",q:"A rectangle is 12 cm by 5 cm. A triangle inside it has one long side of the rectangle as its base and its top corner on the opposite side. A random point in the rectangle is chosen. What is the probability it is inside the triangle? Write it as a decimal.",ans:0.5,
 hint:"The triangle's base and height match the rectangle's sides.",
 expl:"Triangle area = 1/2 × 12 × 5 = 30 cm²; rectangle area = 60 cm². 30 ÷ 60 = 0.5."},
{lvl:2,sec:"S",type:"in",q:"A board is a rectangle 10 cm by 4 cm with a shaded square of side 4 cm at one end. Leila throws a bean bag that lands at a random point on the board. What is the probability she hits the shaded square? Write it as a decimal.",ans:0.4,
 expl:"Shaded area 16 cm² out of 40 cm²: 16 ÷ 40 = 0.4."},
{lvl:2,sec:"S",type:"multi",q:"Select EVERY statement that is true for geometric probability.",
 opts:["Probability = (favourable area) ÷ (total area)","Doubling every length of the target and the bullseye leaves the probability the same","A bigger shaded region always means a smaller probability","The probability depends on the colour of the shape"],aMulti:[0,1],
 expl:"Probability is the ratio of areas. Doubling all lengths multiplies both areas by 4, so the ratio does not change. A bigger favourable region raises the probability, and colour is irrelevant."},
{lvl:3,sec:"S",type:"in",q:"A square target of side 8 has a circular bullseye of radius 2 at its centre. The probability that a random point lands in the bullseye can be written as π/n. What is n?",ans:16,
 hint:"Write the circle's area in terms of π and divide by the square's area.",
 expl:"Circle area = 4π; square area = 64. Probability = 4π/64 = π/16, so n = 16."},
{lvl:3,sec:"S",type:"in",q:"Oluwaseun picks a random point inside a 10 by 10 square. What is the probability that the point is within 1 unit of the left edge OR within 1 unit of the bottom edge? Write it as a decimal.",ans:0.19,
 hint:"Careful: the corner where the two strips overlap should be counted only once.",
 expl:"Left strip area 10, bottom strip area 10, overlap (a 1 by 1 corner) area 1: 10 + 10 − 1 = 19. Probability = 19 ÷ 100 = 0.19."},
{lvl:3,sec:"S",type:"in",q:"A point is chosen at random on a number line from 0 to 20. What is the probability that it is more than 3 units away from 10? Write it as a decimal.",ans:0.7,
 hint:"Which parts of the line are close to 10?",
 expl:"Points from 7 to 13 are within 3 units of 10, a length of 6. The rest has length 20 − 6 = 14, so the probability is 14 ÷ 20 = 0.7."}
],

"g5-condition": [
{sec:"S",type:"mc",q:"A fair 6-sided die is rolled and you are told the result is even. What is the probability it is a 6?",mono:true,
 opts:["1/3","1/6","1/2","1/4"],a:0,
 expl:"The result must be 2, 4 or 6, which are equally likely. One of the three is a 6: 1/3."},
{sec:"S",type:"mc",q:"A bag has 4 red and 6 blue marbles. Wei takes out a red marble and keeps it. What is the probability that the next marble he takes is also red?",mono:true,
 opts:["1/3","2/5","4/9","1/2"],a:0,
 hint:"What is left in the bag now?",
 expl:"After removing a red marble there are 3 red and 6 blue, 9 in total: 3/9 = 1/3."},
{sec:"S",type:"in",q:"In a school, 10 pupils are in Year 5 and 4 of them walk to school. A pupil chosen at random from the whole school turns out to be in Year 5. What is the probability that they walk to school? Write it as a decimal.",ans:0.4,
 expl:"We only look at the 10 Year 5 pupils. 4 of them walk: 4 ÷ 10 = 0.4."},
{lvl:2,sec:"S",type:"mc",q:"Two fair coins are flipped. You are told that at least one of them is heads. What is the probability that both are heads?",mono:true,
 opts:["1/3","1/2","1/4","2/3"],a:0,
 hint:"Which outcomes are still possible after the information?",
 expl:"The outcomes with at least one head are HH, HT and TH. Only HH has both heads: 1/3."},
{lvl:2,sec:"S",type:"in",q:"Two fair 6-sided dice are rolled and you are told the total is 8. What is the probability that both dice show a 4? Write it as a decimal.",ans:0.2,
 hint:"List the pairs that add to 8.",
 expl:"The pairs with total 8 are (2,6), (3,5), (4,4), (5,3), (6,2). One of these five is (4,4): 1/5 = 0.2."},
{lvl:2,sec:"S",type:"in",q:"A bag has 3 red and 2 blue marbles. Mateo takes two marbles, one after the other, without putting the first back. What is the probability that both are red? Write it as a decimal.",ans:0.3,
 expl:"P(first red) = 3/5. Then 2 red remain out of 4, so P(second red) = 2/4. 3/5 × 2/4 = 6/20 = 0.3."},
{lvl:2,sec:"S",type:"multi",q:"Select EVERY situation where the second event depends on what happened in the first.",
 opts:["Drawing two cards without replacing the first","Taking two marbles from a bag without putting the first back","Flipping a coin twice","Rolling a die, then spinning a spinner"],aMulti:[0,1],
 expl:"Not replacing a card or a marble changes what is left, so the second pick depends on the first. Coin flips, dice and spinners do not affect each other."},
{lvl:3,sec:"S",type:"in",q:"A card is drawn at random from cards numbered 1 to 20. You are told the number is greater than 12. What is the probability that it is a multiple of 4? Write it as a decimal.",ans:0.25,
 hint:"First list the cards that are still possible.",
 expl:"The possible cards are 13 to 20, which is 8 cards. The multiples of 4 among them are 16 and 20: 2/8 = 0.25."},
{lvl:3,sec:"S",type:"in",q:"Chioma has two bags. Bag A holds 2 red and 2 blue marbles; bag B holds 1 red and 3 blue. She picks a bag at random, then takes one marble from it. What is the probability the marble is red? Write it as a decimal.",ans:0.375,
 hint:"Work out each bag's case separately, then add.",
 expl:"Bag A: 1/2 × 2/4 = 1/4. Bag B: 1/2 × 1/4 = 1/8. Total: 1/4 + 1/8 = 3/8 = 0.375."},
{lvl:3,sec:"S",type:"mc",q:"Two fair 6-sided dice are rolled and you are told the two numbers are different. What is the probability that the total is 7?",mono:true,
 opts:["1/5","1/6","1/7","1/3"],a:0,
 hint:"How many outcomes have different numbers? How many of those total 7?",
 expl:"36 − 6 doubles = 30 outcomes with different numbers. All 6 ways to make 7 use different numbers: 6/30 = 1/5."},
{lvl:3,sec:"S",type:"in",q:"A box has 5 chocolates: 2 dark and 3 milk. Aisha eats one at random, then takes a second one at random. What is the probability that the SECOND chocolate is milk? Write it as a decimal.",ans:0.6,
 hint:"Consider both possibilities for the first chocolate.",
 expl:"First dark then milk: 2/5 × 3/4 = 6/20. First milk then milk: 3/5 × 2/4 = 6/20. Total 12/20 = 0.6."}
]
};
