/* Grade 5 core: expressions and patterns, decimals to thousandths, two-digit
   divisors, fractions with unlike denominators, multiplying and dividing
   fractions, unit conversion, line plots, volume, the coordinate plane and
   the hierarchy of shapes. */
export const G5_CORE_BANKS = {
"g5-express": [
{sec:"L",type:"in",q:"Evaluate 3 × (4 + 2).",ans:18,hint:"Do the part in brackets first.",
 expl:"Brackets first: 4 + 2 = 6. Then 3 × 6 = 18."},
{sec:"L",type:"in",q:"Evaluate 20 − (6 + 4) ÷ 2.",ans:15,hint:"Brackets, then division, then subtraction.",
 expl:"6 + 4 = 10, then 10 ÷ 2 = 5, and 20 − 5 = 15."},
{sec:"L",type:"mc",q:"Which expression means 'add 8 and 7, then multiply the result by 3'?",mono:true,
 opts:["3 × (8 + 7)","3 × 8 + 7","8 + 7 × 3","(3 × 8) + 7"],a:0,
 expl:"The addition must happen first, so it goes in brackets: 3 × (8 + 7)."},
{sec:"L",type:"mc",q:"Without calculating, how does 2 × (36 + 14) compare with 36 + 14?",
 opts:["It is twice as large","It is 2 more","It is half as large","It is the same"],a:0,
 expl:"Multiplying a bracket by 2 doubles whatever is inside, so it is twice as large."},
{lvl:2,sec:"L",type:"in",q:"Evaluate [(9 − 3) × 4] + 5 × 2.",ans:34,hint:"Work out the square bracket and the 5 × 2 separately, then add.",
 expl:"(9 − 3) × 4 = 6 × 4 = 24 and 5 × 2 = 10. Then 24 + 10 = 34."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY expression that equals 24.",mono:true,
 opts:["(2 + 4) × 4","2 + 4 × 4","48 ÷ (4 − 2)","48 ÷ 4 − 2"],aMulti:[0,2],
 expl:"(2 + 4) × 4 = 6 × 4 = 24 and 48 ÷ (4 − 2) = 48 ÷ 2 = 24. The others give 18 and 10."},
{lvl:2,sec:"L",type:"order",q:"Order these expressions by value, from smallest to largest.",
 items:["(2 + 3) × 5","2 × 3 + 5","2 + 3 × 5","2 × (3 + 5)"],
 ansOrder:["2 × 3 + 5","2 × (3 + 5)","2 + 3 × 5","(2 + 3) × 5"],
 expl:"2 × 3 + 5 = 11, 2 × (3 + 5) = 16, 2 + 3 × 5 = 17 and (2 + 3) × 5 = 25."},
{lvl:3,sec:"L",type:"in",q:"Priya buys 3 notebooks at $4 each and 2 pens at $3 each. She pays with a $20 note. How many dollars change does she get?",
 ans:2,hint:"Write one expression: 20 minus the notebooks minus the pens.",
 expl:"20 − (3 × 4) − (2 × 3) = 20 − 12 − 6 = 2 dollars."},
{lvl:3,sec:"L",type:"mc",q:"Add one pair of brackets to 36 − 12 ÷ 3 + 1 so that its value is 9. Which is correct?",mono:true,
 opts:["(36 − 12) ÷ 3 + 1","36 − 12 ÷ (3 + 1)","36 − (12 ÷ 3 + 1)","(36 − 12) ÷ (3 + 1)"],a:0,
 expl:"(36 − 12) ÷ 3 + 1 = 24 ÷ 3 + 1 = 8 + 1 = 9. The others give 33, 31 and 6."}
],

"g5-patterns": [
{sec:"L",type:"in",q:"A pattern starts at 0 and adds 3 each time. What is its 5th term?",ans:12,
 hint:"Write out the first five terms.",expl:"The terms are 0, 3, 6, 9, 12. The 5th term is 12."},
{sec:"L",type:"in",q:"Pattern A: 0, 2, 4, 6. Pattern B: 0, 6, 12, 18. Each term of B is how many times the matching term of A?",ans:3,
 expl:"6 is 3 × 2, 12 is 3 × 4 and 18 is 3 × 6. Each B term is 3 times the A term."},
{sec:"L",type:"mc",q:"The rule is 'start at 5, add 4'. Which sequence follows it?",mono:true,
 opts:["5, 9, 13, 17","5, 10, 15, 20","5, 4, 3, 2","4, 9, 14, 19"],a:0,
 expl:"Starting at 5 and adding 4 each time gives 5, 9, 13, 17."},
{sec:"L",type:"mc",q:"Pattern A: 1, 2, 3, 4. Pattern B: 4, 8, 12, 16. Which ordered pair (A, B) is made from the 3rd terms?",mono:true,
 opts:["(3, 12)","(12, 3)","(3, 4)","(4, 16)"],a:0,
 expl:"The 3rd term of A is 3 and the 3rd term of B is 12, so the pair is (3, 12)."},
{lvl:2,sec:"L",type:"in",q:"Two sequences both start at 0. One adds 6 each time and the other adds 2. What is the 8th term of the 'add 6' sequence?",ans:42,
 hint:"The first term is 0, so how many times has 6 been added by the 8th term?",
 expl:"By the 8th term, 6 has been added 7 times: 7 × 6 = 42."},
{lvl:2,sec:"L",type:"multi",q:"Pattern A: 0, 4, 8, 12, ... Pattern B: 0, 8, 16, 24, ... Select EVERY true statement.",
 opts:["Each term of B is double the matching term of A","Each term of B is 4 more than the matching term of A","Both patterns add the same amount each time","The ordered pair (12, 24) belongs to the patterns"],aMulti:[0,3],
 expl:"B adds 8 while A adds 4, so B's terms are double A's, and the 4th terms give the pair (12, 24). The first pair is (0, 0), so B is not always 4 more."},
{lvl:2,sec:"L",type:"order",q:"These ordered pairs come from the rule 'y is 3 times x'. Order them from smallest y-value to largest.",
 items:["(7, 21)","(2, 6)","(5, 15)","(9, 27)"],ansOrder:["(2, 6)","(5, 15)","(7, 21)","(9, 27)"],
 expl:"The y-values are 6, 15, 21 and 27, so the order is (2, 6), (5, 15), (7, 21), (9, 27)."},
{lvl:3,sec:"L",type:"in",q:"Pattern A: 3, 6, 9, 12, ... Pattern B: 5, 10, 15, 20, ... At which term number is the B term first more than 40 greater than the A term?",ans:21,
 hint:"Look at how the gap between the patterns grows each step.",
 expl:"The gap is 2, 4, 6, 8, ... so at term n the gap is 2 × n. The gap first passes 40 when 2 × n = 42, at term 21."},
{lvl:3,sec:"L",type:"in",q:"A rule makes ordered pairs: the second number is 4 times the first number, plus 1. If the second number is 37, what is the first number?",ans:9,
 hint:"Undo the rule: subtract first, then divide.",expl:"37 − 1 = 36 and 36 ÷ 4 = 9, so the first number is 9."}
],

"g5-thousandth": [
{sec:"N",type:"in",q:"In the number 4.562, which digit is in the thousandths place?",ans:2,
 expl:"After the decimal point come tenths (5), hundredths (6), thousandths (2). The digit is 2."},
{sec:"N",type:"mc",q:"Which number is 'three and forty-seven thousandths'?",mono:true,
 opts:["3.047","3.47","3.407","30.47"],a:0,
 expl:"Forty-seven thousandths is 47/1000 = 0.047, so the number is 3.047."},
{sec:"N",type:"in",q:"Write 0.6 + 0.05 + 0.008 as a single decimal.",ans:0.658,
 expl:"6 tenths, 5 hundredths and 8 thousandths together make 0.658."},
{sec:"N",type:"mc",q:"Which comparison is correct?",mono:true,
 opts:["0.35 > 0.305","0.305 > 0.35","0.035 > 0.305","0.35 = 0.305"],a:0,
 expl:"0.35 is 0.350, which is more than 0.305 because 50 thousandths beats 5 thousandths. So 0.35 > 0.305."},
{lvl:2,sec:"N",type:"in",q:"Round 6.483 to the nearest tenth.",ans:6.5,hint:"Look at the hundredths digit to decide.",
 expl:"The hundredths digit is 8, which is 5 or more, so the tenths digit rounds up: 6.5."},
{lvl:2,sec:"N",type:"order",q:"Order these decimals from smallest to largest.",
 items:["0.5","0.052","0.502","0.25"],ansOrder:["0.052","0.25","0.5","0.502"],
 expl:"Write them all with three places: 0.500, 0.052, 0.502, 0.250. In order: 0.052, 0.25, 0.5, 0.502."},
{lvl:2,sec:"N",type:"mc",q:"The 5 in 0.35 is worth how many times the 5 in 0.305?",
 opts:["10 times","100 times","1/10 as much","The same"],a:0,
 expl:"In 0.35 the 5 is 5 hundredths; in 0.305 it is 5 thousandths. A hundredth is 10 times a thousandth."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY value that equals 0.750.",
 opts:["0.75","0.705","seventy-five hundredths","7 tenths + 5 hundredths"],aMulti:[0,2,3],
 expl:"0.750 is 75 hundredths, which is 0.75, or 7 tenths and 5 hundredths. 0.705 has a 0 in the hundredths place, so it is different."},
{lvl:3,sec:"N",type:"in",q:"A number has whole-number part 5 and three decimal places. Its hundredths digit is 0, its tenths digit is twice its thousandths digit, and its three decimal digits add up to 9. What is the number?",ans:5.603,
 hint:"Call the thousandths digit t. What is the tenths digit in terms of t?",
 expl:"If the thousandths digit is t, the tenths digit is 2t, and 2t + 0 + t = 9 gives t = 3. So the number is 5.603."},
{lvl:3,sec:"N",type:"in",q:"What is the smallest number with exactly three decimal places that rounds to 2.5 when rounded to the nearest tenth?",ans:2.45,
 hint:"Rounding to 2.5 means the number is at least halfway from 2.4.",
 expl:"Any number from 2.450 up to 2.549 rounds to 2.5. The smallest is 2.450, written 2.45."}
],

"g5-decops": [
{sec:"N",type:"in",q:"3.45 + 2.8 = ?",ans:6.25,hint:"Line up the decimal points.",
 expl:"3.45 + 2.80 = 6.25."},
{sec:"N",type:"in",q:"9.6 − 4.75 = ?",ans:4.85,expl:"9.60 − 4.75 = 4.85."},
{sec:"N",type:"in",q:"0.6 × 4 = ?",ans:2.4,expl:"6 tenths × 4 = 24 tenths = 2.4."},
{sec:"N",type:"mc",q:"Kenji estimates 4.9 × 6.1. Which is the best estimate?",mono:true,
 opts:["30","24","36","3"],a:0,
 expl:"4.9 is close to 5 and 6.1 is close to 6, so the product is close to 5 × 6 = 30."},
{lvl:2,sec:"N",type:"in",q:"1.5 × 2.4 = ?",ans:3.6,hint:"Multiply 15 × 24, then place the decimal point.",
 expl:"15 × 24 = 360. There are two decimal places in total, so the answer is 3.60 = 3.6."},
{lvl:2,sec:"N",type:"in",q:"7.2 ÷ 0.6 = ?",ans:12,hint:"How many 0.6s fit in 7.2? Try scaling both by 10.",
 expl:"7.2 ÷ 0.6 is the same as 72 ÷ 6 = 12."},
{lvl:2,sec:"N",type:"mc",q:"Which has the same value as 3.6 ÷ 0.4?",mono:true,
 opts:["36 ÷ 4","3.6 ÷ 4","36 ÷ 0.4","0.36 ÷ 4"],a:0,
 expl:"Multiplying both numbers by 10 does not change the quotient: 3.6 ÷ 0.4 = 36 ÷ 4 = 9."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY calculation with an answer of 1.2.",mono:true,
 opts:["0.3 × 4","4.8 ÷ 4","0.6 + 0.6","2 − 0.08"],aMulti:[0,1,2],
 expl:"0.3 × 4 = 1.2, 4.8 ÷ 4 = 1.2 and 0.6 + 0.6 = 1.2. But 2 − 0.08 = 1.92."},
{lvl:3,sec:"N",type:"in",q:"Nadia buys 3 pencils at $0.85 each and a ruler for $1.20. She pays with $5. How much change does she get, in dollars?",ans:1.25,
 hint:"Find the total cost first.",expl:"3 × 0.85 = 2.55, plus 1.20 makes 3.75. Then 5 − 3.75 = 1.25 dollars."},
{lvl:3,sec:"N",type:"in",q:"A ribbon 6.3 m long is cut into pieces that are each 0.45 m long. How many pieces are there?",ans:14,
 hint:"Scale both lengths by 100 to work in whole centimetres.",
 expl:"6.3 m is 630 cm and 0.45 m is 45 cm. 630 ÷ 45 = 14 pieces."},
{lvl:3,sec:"N",type:"in",q:"A rectangle is 2.5 cm long and 1.8 cm wide. A square of side 1.5 cm is cut out of it. What area in square cm is left?",ans:2.25,
 hint:"Work out both areas, then subtract.",
 expl:"The rectangle is 2.5 × 1.8 = 4.5 sq cm and the square is 1.5 × 1.5 = 2.25 sq cm. 4.5 − 2.25 = 2.25 sq cm left."}
],

"g5-twodigit": [
{sec:"N",type:"in",q:"672 ÷ 21 = ?",ans:32,hint:"How many 21s in 67? Then bring down the 2.",
 expl:"21 × 30 = 630, leaving 42, and 21 × 2 = 42. So 672 ÷ 21 = 32."},
{sec:"N",type:"in",q:"945 ÷ 15 = ?",ans:63,expl:"15 × 60 = 900, leaving 45, and 15 × 3 = 45. So the answer is 63."},
{sec:"N",type:"mc",q:"Which is the best estimate for 1,782 ÷ 29?",mono:true,
 opts:["60","30","600","6"],a:0,
 expl:"Round to 1,800 ÷ 30 = 60."},
{sec:"N",type:"in",q:"1,248 ÷ 24 = ?",ans:52,expl:"24 × 50 = 1,200, leaving 48, and 24 × 2 = 48. So 1,248 ÷ 24 = 52."},
{lvl:2,sec:"N",type:"in",q:"What is the remainder when 500 is divided by 32?",ans:20,
 hint:"Find the biggest multiple of 32 that fits under 500.",
 expl:"32 × 15 = 480, and 500 − 480 = 20. The remainder is 20."},
{lvl:2,sec:"N",type:"in",q:"A school orders 1,530 pencils packed in boxes of 45. How many boxes is that?",ans:34,
 expl:"45 × 30 = 1,350, leaving 180, and 45 × 4 = 180. So there are 34 boxes."},
{lvl:2,sec:"N",type:"mc",q:"Diego divides 2,976 by 48 and gets 62. Which check shows the answer is right?",mono:true,
 opts:["48 × 62 = 2,976","48 + 62 = 2,976","2,976 − 48 = 62","62 ÷ 48 = 2,976"],a:0,
 expl:"Division is checked by multiplying back: 48 × 62 = 2,880 + 96 = 2,976, so the answer is correct."},
{lvl:2,sec:"N",type:"order",q:"Order these quotients from smallest to largest.",
 items:["840 ÷ 12","990 ÷ 11","816 ÷ 24","1,000 ÷ 25"],ansOrder:["816 ÷ 24","1,000 ÷ 25","840 ÷ 12","990 ÷ 11"],
 expl:"816 ÷ 24 = 34, 1,000 ÷ 25 = 40, 840 ÷ 12 = 70 and 990 ÷ 11 = 90."},
{lvl:3,sec:"N",type:"in",q:"Zainab has 1,875 stickers to put on sheets of 36. After filling as many sheets as she can, how many stickers are left over?",ans:3,
 hint:"You only need the remainder.",expl:"36 × 52 = 1,872, so 52 full sheets use 1,872 stickers and 1,875 − 1,872 = 3 are left over."},
{lvl:3,sec:"N",type:"in",q:"A number divided by 27 gives a quotient of 41 with remainder 13. What is the number?",ans:1120,
 hint:"Multiply back, then add the remainder.",expl:"27 × 41 = 1,107, and adding the remainder gives 1,107 + 13 = 1,120."},
{lvl:3,sec:"N",type:"in",q:"1,000 people are going on a trip in coaches that each seat 48. What is the smallest number of coaches needed?",ans:21,
 hint:"A part-full coach still counts as a coach.",
 expl:"48 × 20 = 960 seats is not enough for 1,000 people; 40 people would still need a seat. So 21 coaches are needed."}
],

"g5-unlike": [
{sec:"F",type:"mc",q:"1/2 + 1/4 = ?",mono:true,opts:["3/4","2/6","1/6","2/4"],a:0,
 expl:"1/2 is the same as 2/4, so 2/4 + 1/4 = 3/4."},
{sec:"F",type:"in",q:"What is the least common denominator for adding 1/3 and 1/4?",ans:12,
 hint:"Find the smallest number in both times tables.",expl:"The smallest multiple of both 3 and 4 is 12."},
{sec:"F",type:"mc",q:"2/3 − 1/6 = ?",mono:true,opts:["1/2","1/3","1/6","2/3"],a:0,
 expl:"2/3 = 4/6, so 4/6 − 1/6 = 3/6 = 1/2."},
{sec:"F",type:"in",q:"1/2 + 3/10 = ? Give your answer as a decimal.",ans:0.8,
 expl:"1/2 = 5/10, so 5/10 + 3/10 = 8/10 = 0.8."},
{lvl:2,sec:"F",type:"mc",q:"3/4 + 2/5 = ?",mono:true,opts:["1 3/20","5/9","1 1/20","23/9"],a:0,
 hint:"Use twentieths.",expl:"3/4 = 15/20 and 2/5 = 8/20. 15/20 + 8/20 = 23/20 = 1 3/20."},
{lvl:2,sec:"F",type:"mc",q:"5/6 − 3/8 = ?",mono:true,opts:["11/24","2/14","1/3","9/24"],a:0,
 hint:"Use twenty-fourths.",expl:"5/6 = 20/24 and 3/8 = 9/24. 20/24 − 9/24 = 11/24."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY sum that is greater than 1.",mono:true,
 opts:["1/2 + 2/3","1/4 + 3/8","3/5 + 1/2","1/3 + 1/6"],aMulti:[0,2],
 expl:"1/2 + 2/3 = 7/6 and 3/5 + 1/2 = 11/10 are both over 1. 1/4 + 3/8 = 5/8 and 1/3 + 1/6 = 1/2 are under 1."},
{lvl:2,sec:"F",type:"in",q:"2 1/4 + 1 1/2 = ? Give your answer as a decimal.",ans:3.75,
 expl:"2 1/4 = 2.25 and 1 1/2 = 1.5. Adding gives 3.75."},
{lvl:3,sec:"F",type:"mc",q:"Amara walked 3/4 km to the shop and 5/8 km to the park. How much further, in km, was the walk to the shop?",mono:true,
 opts:["1/8","1/4","2/12","1/2"],a:0,hint:"Change 3/4 into eighths.",
 expl:"3/4 = 6/8, and 6/8 − 5/8 = 1/8 km further."},
{lvl:3,sec:"F",type:"mc",q:"Lior spends 1/3 of the day asleep and 1/4 of the day at school. What fraction of the day is left for everything else?",mono:true,
 opts:["5/12","7/12","2/7","1/12"],a:0,hint:"Add the two fractions first, then take them away from one whole.",
 expl:"1/3 + 1/4 = 4/12 + 3/12 = 7/12 of the day, so 12/12 − 7/12 = 5/12 is left."},
{lvl:3,sec:"F",type:"in",q:"Mei needs 2 1/2 cups of flour but has only 1 3/4 cups. How many more cups does she need? Give a decimal.",ans:0.75,
 hint:"Change both mixed numbers into quarters.",expl:"2 1/2 = 10/4 and 1 3/4 = 7/4. 10/4 − 7/4 = 3/4 cup, which is 0.75."}
],

"g5-fracmult": [
{sec:"F",type:"mc",q:"1/2 × 1/3 = ?",mono:true,opts:["1/6","2/5","1/5","2/3"],a:0,
 expl:"Multiply tops and bottoms: 1 × 1 = 1 and 2 × 3 = 6, so the answer is 1/6."},
{sec:"F",type:"in",q:"3/4 × 8 = ?",ans:6,hint:"Find 1/4 of 8 first.",
 expl:"1/4 of 8 is 2, so 3/4 of 8 is 3 × 2 = 6."},
{sec:"F",type:"mc",q:"2/3 × 3/5 = ?",mono:true,opts:["2/5","5/8","6/8","3/15"],a:0,
 expl:"2 × 3 = 6 and 3 × 5 = 15, so the product is 6/15, which simplifies to 2/5."},
{sec:"F",type:"mc",q:"Without multiplying, which statement about 5/6 × 9 is true?",
 opts:["The answer is less than 9","The answer is more than 9","The answer equals 9","The answer is exactly 5"],a:0,
 expl:"Multiplying by a fraction less than 1 makes the number smaller, so 5/6 × 9 is less than 9."},
{lvl:2,sec:"F",type:"in",q:"A recipe uses 2/3 cup of sugar. Tomas makes 6 batches. How many cups of sugar does he use?",ans:4,
 expl:"2/3 × 6 = 12/3 = 4 cups."},
{lvl:2,sec:"F",type:"in",q:"3/5 × 2 1/2 = ? Give a decimal.",ans:1.5,hint:"Turn the mixed number into an improper fraction first.",
 expl:"2 1/2 = 5/2, so 3/5 × 5/2 = 15/10 = 1.5."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY product that is smaller than 3/4.",mono:true,
 opts:["3/4 × 1/2","3/4 × 1","3/4 × 2/3","3/4 × 5/4"],aMulti:[0,2],
 expl:"Multiplying by a number less than 1 shrinks 3/4, so 3/4 × 1/2 and 3/4 × 2/3 are smaller. Multiplying by 1 keeps it the same and by 5/4 makes it bigger."},
{lvl:2,sec:"F",type:"mc",q:"A garden bed is 2/3 m long and 3/4 m wide. What is its area in m²?",mono:true,
 opts:["1/2","5/12","6/7","1/6"],a:0,
 expl:"Area = 2/3 × 3/4 = 6/12 = 1/2 m²."},
{lvl:2,sec:"F",type:"order",q:"Order these products from smallest to largest.",
 items:["5/6 × 12","3/4 × 12","7/8 × 12","2/3 × 12"],ansOrder:["2/3 × 12","3/4 × 12","5/6 × 12","7/8 × 12"],
 expl:"2/3 × 12 = 8, 3/4 × 12 = 9, 5/6 × 12 = 10 and 7/8 × 12 = 10.5."},
{lvl:3,sec:"F",type:"in",q:"Yusuf has 24 marbles. He gives 1/3 of them to Hana, then 3/4 of what is left to Ravi. How many marbles does Yusuf have left?",ans:4,
 hint:"Find how many are left after the first gift before working out the second.",
 expl:"1/3 of 24 is 8, leaving 16. 3/4 of 16 is 12, leaving 16 − 12 = 4 marbles."},
{lvl:3,sec:"F",type:"in",q:"A jug holds 2 1/2 cups. Ingrid pours out 3/5 of it, then drinks 1/2 of what she poured. How many cups did she drink? Give a decimal.",ans:0.75,
 hint:"Work out the amount poured first.",
 expl:"3/5 × 2 1/2 = 3/5 × 5/2 = 3/2 = 1.5 cups poured. Half of 1.5 is 0.75 cups."},
{lvl:3,sec:"F",type:"mc",q:"A number is multiplied by 7/8, and then the result is multiplied by 8/7. Compared with the starting number, the final result is",
 opts:["exactly the same","a little smaller","a little larger","zero"],a:0,
 expl:"7/8 × 8/7 = 56/56 = 1, and multiplying by 1 leaves the number unchanged."}
],

"g5-fracdiv": [
{sec:"F",type:"in",q:"4 ÷ 1/2 = ?",ans:8,hint:"How many halves are in 4 wholes?",
 expl:"Each whole has 2 halves, so 4 wholes have 4 × 2 = 8 halves."},
{sec:"F",type:"mc",q:"1/3 ÷ 4 = ?",mono:true,opts:["1/12","4/3","3/4","1/7"],a:0,
 expl:"Splitting 1/3 into 4 equal parts gives pieces of 1/12 each, because 1/3 × 1/4 = 1/12."},
{sec:"F",type:"in",q:"How many 1/4-cup scoops does it take to fill a 3-cup container?",ans:12,
 expl:"Each cup takes 4 scoops, so 3 cups take 3 × 4 = 12 scoops."},
{sec:"F",type:"mc",q:"Which story matches 1/2 ÷ 3?",
 opts:["Half a cake shared by 3 people","3 cakes shared by 2 people","Half of 3 cakes","3 halves of a cake"],a:0,
 expl:"1/2 ÷ 3 means splitting a half into 3 equal parts, like half a cake shared by 3 people."},
{lvl:2,sec:"F",type:"in",q:"1/5 ÷ 2 = ? Give a decimal.",ans:0.1,
 expl:"Half of 1/5 is 1/10, which is 0.1."},
{lvl:2,sec:"F",type:"in",q:"6 ÷ 1/3 = ?",ans:18,hint:"Count the thirds in each whole.",
 expl:"There are 3 thirds in each whole, so 6 wholes contain 6 × 3 = 18 thirds."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY calculation with an answer of 20.",mono:true,
 opts:["5 ÷ 1/4","4 ÷ 1/5","1/4 ÷ 5","10 ÷ 1/2"],aMulti:[0,1,3],
 expl:"5 ÷ 1/4 = 5 × 4 = 20, 4 ÷ 1/5 = 4 × 5 = 20 and 10 ÷ 1/2 = 10 × 2 = 20. But 1/4 ÷ 5 = 1/20."},
{lvl:2,sec:"F",type:"mc",q:"Which is the same as 1/6 ÷ 3?",mono:true,
 opts:["1/6 × 1/3","1/6 × 3","6 × 3","3 ÷ 1/6"],a:0,
 expl:"Dividing by 3 is the same as multiplying by 1/3, so 1/6 ÷ 3 = 1/6 × 1/3 = 1/18."},
{lvl:3,sec:"F",type:"in",q:"Elias has 5 m of ribbon. He cuts it into pieces that are each 1/4 m long, then gives away 6 pieces. How many pieces does he keep?",ans:14,
 hint:"First find how many pieces he cuts.",expl:"5 ÷ 1/4 = 5 × 4 = 20 pieces. Giving away 6 leaves 20 − 6 = 14."},
{lvl:3,sec:"F",type:"in",q:"Half a pizza is shared equally among 4 friends. Each share is a unit fraction of the whole pizza. Type the bottom number of that fraction.",ans:8,
 hint:"1/2 ÷ 4 gives a unit fraction.",expl:"1/2 ÷ 4 = 1/2 × 1/4 = 1/8 of the pizza, so the bottom number is 8."},
{lvl:3,sec:"F",type:"in",q:"Chioma pours 3 cups of juice into glasses that each hold 1/3 cup. Noor then drinks 2 full glasses. How many full glasses are left?",ans:7,
 hint:"Work out how many glasses she filled first.",
 expl:"3 ÷ 1/3 = 3 × 3 = 9 glasses. After 2 are drunk, 9 − 2 = 7 remain."}
],

"g5-fracword": [
{sec:"F",type:"mc",q:"Sofia ate 1/4 of a pizza and Arjun ate 3/8 of it. What fraction of the pizza did they eat altogether?",mono:true,
 opts:["5/8","4/12","1/3","7/8"],a:0,
 expl:"1/4 = 2/8, so 2/8 + 3/8 = 5/8 of the pizza."},
{sec:"F",type:"in",q:"A class has 30 students and 2/5 of them walk to school. How many students walk?",ans:12,
 expl:"1/5 of 30 is 6, so 2/5 of 30 is 2 × 6 = 12 students."},
{sec:"F",type:"mc",q:"Wei had 7/8 of a bag of rice and used 1/2 of a bag for dinner. What fraction of a bag is left?",mono:true,
 opts:["3/8","6/8","1/4","1/8"],a:0,
 expl:"1/2 = 4/8, so 7/8 − 4/8 = 3/8 of a bag is left."},
{sec:"F",type:"in",q:"Femi runs 1/2 km every day for 9 days. How far does he run in total, in km? Give a decimal.",ans:4.5,
 expl:"1/2 × 9 = 9/2 = 4.5 km."},
{lvl:2,sec:"F",type:"in",q:"A recipe needs 1 1/3 cups of milk. Leila makes three times the recipe. How many cups of milk does she need?",ans:4,
 expl:"1 1/3 = 4/3, and 4/3 × 3 = 4 cups."},
{lvl:2,sec:"F",type:"mc",q:"Priya read 2/5 of a book on Monday and 1/3 of it on Tuesday. What fraction of the book is still left to read?",mono:true,
 opts:["4/15","11/15","2/8","1/2"],a:0,hint:"Use fifteenths.",
 expl:"2/5 + 1/3 = 6/15 + 5/15 = 11/15 read, so 15/15 − 11/15 = 4/15 is left."},
{lvl:2,sec:"F",type:"in",q:"Mateo has a 12 m rope and uses 3/4 of it to tie up a boat. How many m of rope does he use?",ans:9,
 expl:"1/4 of 12 is 3, so 3/4 of 12 is 9 m."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY calculation that gives 3/4 of a pizza.",mono:true,
 opts:["1/2 + 1/4","3 × 1/4","1 − 1/4","1/2 × 1/4"],aMulti:[0,1,2],
 expl:"1/2 + 1/4 = 3/4, 3 × 1/4 = 3/4 and 1 − 1/4 = 3/4. But 1/2 × 1/4 = 1/8."},
{lvl:3,sec:"F",type:"in",q:"Kenji has $60. He spends 1/4 of it on a book and then 2/5 of what is left on lunch. How many dollars does he have left?",ans:27,
 hint:"Work out what is left after the book before finding the lunch cost.",
 expl:"1/4 of 60 is 15, leaving 45. 2/5 of 45 is 18, leaving 45 − 18 = 27 dollars."},
{lvl:3,sec:"F",type:"mc",q:"Aisha eats 1/3 of a cake and Oluwaseun eats 1/4 of the same cake. They give half of what is left to Zainab. What fraction of the whole cake does Zainab get?",mono:true,
 opts:["5/24","5/12","1/2","7/24"],a:0,hint:"Find the fraction left after both have eaten, then halve it.",
 expl:"1/3 + 1/4 = 7/12 eaten, so 5/12 is left. Half of 5/12 is 5/24."},
{lvl:3,sec:"F",type:"in",q:"A jar is 2/3 full and contains 18 cups of water. How many cups does the jar hold when it is completely full?",ans:27,
 hint:"If 2/3 is 18 cups, what is 1/3?",expl:"2/3 of the jar is 18 cups, so 1/3 is 9 cups and the full jar is 3 × 9 = 27 cups."}
],

"g5-convert": [
{sec:"M",type:"in",q:"How many centimetres are in 3.5 m?",ans:350,hint:"There are 100 cm in 1 m.",
 expl:"3.5 × 100 = 350 cm."},
{sec:"M",type:"in",q:"How many grams are in 2.4 kg?",ans:2400,expl:"1 kg = 1,000 g, so 2.4 × 1,000 = 2,400 g."},
{sec:"M",type:"mc",q:"Which is the same as 1,500 mL?",mono:true,opts:["1.5 L","15 L","0.15 L","150 L"],a:0,
 expl:"1,000 mL = 1 L, so 1,500 mL = 1.5 L."},
{sec:"M",type:"in",q:"How many inches are in 4 feet?",ans:48,expl:"1 foot = 12 inches, so 4 × 12 = 48 inches."},
{lvl:2,sec:"M",type:"in",q:"Convert 3 hours 25 minutes into minutes.",ans:205,
 expl:"3 × 60 = 180 minutes, plus 25 gives 205 minutes."},
{lvl:2,sec:"M",type:"in",q:"A parcel weighs 4 lb 6 oz. How many ounces is that in total?",ans:70,hint:"1 lb = 16 oz.",
 expl:"4 × 16 = 64 oz, plus 6 oz makes 70 oz."},
{lvl:2,sec:"M",type:"order",q:"Order these lengths from shortest to longest.",
 items:["0.4 km","350 m","4,500 cm","3.9 m"],ansOrder:["3.9 m","4,500 cm","350 m","0.4 km"],
 expl:"In metres: 3.9 m, 4,500 cm = 45 m, 350 m, 0.4 km = 400 m."},
{lvl:2,sec:"M",type:"in",q:"A recipe needs 0.75 L of milk. Hana has cartons that each hold 250 mL. How many cartons does she need?",ans:3,
 expl:"0.75 L = 750 mL, and 750 ÷ 250 = 3 cartons."},
{lvl:3,sec:"M",type:"in",q:"Ravi runs 2.5 km on Monday and 1,800 m on Tuesday. How many metres does he run in total?",ans:4300,
 hint:"Change both distances to the same unit before adding.",
 expl:"2.5 km = 2,500 m. 2,500 + 1,800 = 4,300 m."},
{lvl:3,sec:"M",type:"in",q:"A ribbon is 3 yards long. It is cut into pieces 8 inches long. How many whole pieces can be cut?",ans:13,
 hint:"Change yards to feet, then to inches.",
 expl:"3 yards = 9 feet = 108 inches. 108 ÷ 8 = 13.5, so 13 whole pieces can be cut."},
{lvl:3,sec:"M",type:"in",q:"Noor drinks 4 glasses of water a day, and each glass holds 250 mL. How many litres does Noor drink in a week?",ans:7,
 hint:"Find the daily amount in mL first, then the weekly amount.",
 expl:"4 × 250 = 1,000 mL = 1 L a day. In 7 days that is 7 L."}
],

"g5-lineplot": [
{sec:"M",type:"in",q:"A line plot shows worm lengths in inches: 1/2 has 3 Xs, 3/4 has 4 Xs and 1 has 2 Xs. How many worms were measured?",ans:9,
 hint:"Each X is one worm.",expl:"Count all the Xs: 3 + 4 + 2 = 9 worms."},
{sec:"M",type:"mc",q:"A line plot of ribbon lengths in metres has 2 Xs above 1/4, 5 Xs above 1/2 and 3 Xs above 3/4. Which length appears most often?",mono:true,
 opts:["1/2","1/4","3/4","1"],a:0,
 expl:"The tallest column of Xs is above 1/2, with 5 ribbons."},
{sec:"M",type:"in",q:"A line plot shows rainfall in inches for 5 days: 1/4, 1/4, 1/2, 1/2 and 1/2. What is the total rainfall in inches? Give a decimal.",ans:2,
 expl:"1/4 + 1/4 = 1/2, and with three more halves the total is 4 halves = 2 inches."},
{sec:"M",type:"mc",q:"Which marks should the number line have for a line plot of the measurements 1/8, 1/4, 3/8 and 1/2 inch?",
 opts:["Eighths from 0 to 1","Whole numbers from 0 to 10","Tenths from 0 to 1","Halves only"],a:0,
 expl:"All the measurements can be written in eighths (1/8, 2/8, 3/8, 4/8), so marks in eighths fit every value."},
{lvl:2,sec:"M",type:"in",q:"Pencil lengths in inches on a line plot: 5 1/2 has 2 Xs, 6 has 3 Xs and 6 1/2 has 1 X. What is the difference in inches between the longest and shortest pencil? Give a decimal.",ans:1,
 expl:"The longest is 6 1/2 and the shortest is 5 1/2, so the difference is 6.5 − 5.5 = 1 inch."},
{lvl:2,sec:"M",type:"in",q:"Bags of flour on a line plot: 1/2 kg has 4 Xs, 3/4 kg has 2 Xs and 1 kg has 2 Xs. What is the total mass of all the bags in kg? Give a decimal.",ans:5.5,
 hint:"Multiply each mass by its number of Xs, then add.",
 expl:"4 × 1/2 = 2, 2 × 3/4 = 1.5 and 2 × 1 = 2. Total 2 + 1.5 + 2 = 5.5 kg."},
{lvl:2,sec:"M",type:"multi",q:"A line plot of jump distances in metres: 1 1/4 has 1 X, 1 1/2 has 3 Xs, 1 3/4 has 2 Xs and 2 has 2 Xs. Select EVERY true statement.",
 opts:["8 jumps were recorded","The most common distance was 1 1/2 m","The longest jump was 1 3/4 m","Exactly half the jumps were under 1 3/4 m"],aMulti:[0,1,3],
 expl:"1 + 3 + 2 + 2 = 8 jumps; 1 1/2 has the most Xs; 1 + 3 = 4 of the 8 jumps are under 1 3/4 m. The longest jump was 2 m, not 1 3/4 m."},
{lvl:2,sec:"M",type:"order",q:"A line plot of ribbon lengths shows 6 Xs at 1/4 m, 2 Xs at 1/2 m, 3 Xs at 3/4 m and 2 Xs at 1 m. Order the lengths by the TOTAL amount of ribbon at each length, smallest total first.",
 items:["1/4 m","1/2 m","3/4 m","1 m"],ansOrder:["1/2 m","1/4 m","1 m","3/4 m"],
 expl:"Totals: 1/2 m × 2 = 1 m, 1/4 m × 6 = 1.5 m, 1 m × 2 = 2 m, 3/4 m × 3 = 2.25 m."},
{lvl:3,sec:"M",type:"in",q:"Six beakers hold water. A line plot shows 2 Xs at 1/4 cup, 2 Xs at 1/2 cup and 2 Xs at 3/4 cup. If all the water were shared equally among the 6 beakers, how many cups would each hold? Give a decimal.",ans:0.5,
 hint:"Find the total first, then divide by the number of beakers.",
 expl:"Total = 2 × 1/4 + 2 × 1/2 + 2 × 3/4 = 0.5 + 1 + 1.5 = 3 cups. 3 ÷ 6 = 0.5 cup each."},
{lvl:3,sec:"M",type:"in",q:"A line plot shows the heights of 10 bean plants in inches: two are 2 1/4, five are 2 1/2 and three are 3. What is the total height of all the plants in inches? Give a decimal.",ans:26,
 hint:"Multiply each height by how many plants have it.",
 expl:"2 × 2.25 = 4.5, 5 × 2.5 = 12.5 and 3 × 3 = 9. Total 4.5 + 12.5 + 9 = 26 inches."},
{lvl:3,sec:"M",type:"mc",q:"A line plot shows the masses of 4 mice in ounces: three at 3/8 and one at 7/8. If the total mass were split equally, how much would each mouse weigh in ounces?",mono:true,
 opts:["1/2","5/8","3/8","1"],a:0,hint:"Add all four masses, then divide by 4.",
 expl:"3 × 3/8 = 9/8, plus 7/8 makes 16/8 = 2 oz. 2 ÷ 4 = 1/2 oz each."}
],

"g5-volume": [
{sec:"G",type:"in",q:"A box is 4 cm long, 3 cm wide and 2 cm tall. What is its volume in cubic cm?",ans:24,
 hint:"Multiply the three dimensions.",expl:"Volume = 4 × 3 × 2 = 24 cubic cm."},
{sec:"G",type:"mc",q:"Volume is measured in which kind of units?",
 opts:["Cubic units","Square units","Units of length","Degrees"],a:0,
 expl:"Volume counts unit cubes filling a solid, so it uses cubic units such as cubic cm."},
{sec:"G",type:"in",q:"A prism is built from unit cubes. Its bottom layer is 5 cubes by 3 cubes and there are 4 layers. How many cubes are used?",ans:60,
 expl:"Each layer has 5 × 3 = 15 cubes, and 4 layers make 15 × 4 = 60 cubes."},
{sec:"G",type:"mc",q:"Which formula gives the volume of a rectangular prism?",mono:true,
 opts:["length × width × height","length + width + height","2 × (length + width)","length × width"],a:0,
 expl:"The base area is length × width, and multiplying by the height counts every layer: V = l × w × h."},
{lvl:2,sec:"G",type:"in",q:"A cube has edges of 5 cm. What is its volume in cubic cm?",ans:125,
 expl:"All edges are equal, so V = 5 × 5 × 5 = 125 cubic cm."},
{lvl:2,sec:"G",type:"in",q:"A rectangular tank has a base area of 30 square cm and a volume of 210 cubic cm. How tall is it in cm?",ans:7,
 hint:"Volume = base area × height.",expl:"210 ÷ 30 = 7, so the tank is 7 cm tall."},
{lvl:2,sec:"G",type:"in",q:"An L-shaped solid is made from a 4 cm × 2 cm × 3 cm box joined to a 2 cm × 2 cm × 3 cm box. What is its total volume in cubic cm?",ans:36,
 hint:"Find each box's volume, then add.",expl:"4 × 2 × 3 = 24 and 2 × 2 × 3 = 12. Together 24 + 12 = 36 cubic cm."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY box (dimensions in cm) with a volume of 48 cubic cm.",mono:true,
 opts:["6 × 4 × 2","8 × 3 × 2","4 × 4 × 4","12 × 2 × 2"],aMulti:[0,1,3],
 expl:"6 × 4 × 2 = 48, 8 × 3 × 2 = 48 and 12 × 2 × 2 = 48. But 4 × 4 × 4 = 64."},
{lvl:2,sec:"G",type:"order",q:"Order these prisms (dimensions in cm) from smallest volume to largest.",
 items:["3 × 3 × 3","2 × 5 × 3","1 × 4 × 6","4 × 4 × 2"],ansOrder:["1 × 4 × 6","3 × 3 × 3","2 × 5 × 3","4 × 4 × 2"],
 expl:"The volumes are 24, 27, 30 and 32 cubic cm."},
{lvl:3,sec:"G",type:"in",q:"A box measures 10 cm by 6 cm by 4 cm. It is packed full of cubes with 2 cm edges. How many cubes fit inside?",ans:30,
 hint:"How many cubes fit along each edge?",
 expl:"Along the edges fit 10 ÷ 2 = 5, 6 ÷ 2 = 3 and 4 ÷ 2 = 2 cubes. 5 × 3 × 2 = 30 cubes."},
{lvl:3,sec:"G",type:"in",q:"A pool is 8 m long, 4 m wide and 1.5 m deep. The water is already 1 m deep. How many cubic metres of water are needed to fill the pool to the top?",ans:16,
 hint:"Only the empty part needs filling.",
 expl:"The empty part is 1.5 − 1 = 0.5 m deep. 8 × 4 × 0.5 = 16 cubic metres."}
],

"g5-coord": [
{sec:"G",type:"pair",q:"Start at the origin. Move 3 units right and 5 units up. Write the point you reach as an ordered pair.",ansP:[3,5],
 expl:"Right gives the x-coordinate and up gives the y-coordinate, so the point is (3, 5)."},
{sec:"G",type:"mc",q:"In the ordered pair (4, 7), what does the 4 tell you?",
 opts:["Move 4 units right from the origin","Move 4 units up from the origin","Move 4 units left from the origin","The point is 4 units from (7, 4)"],a:0,
 expl:"The first number is the x-coordinate, the distance to the right of the origin."},
{sec:"G",type:"pair",q:"Point P is 6 units to the right of the origin and 0 units up. Write its coordinates.",ansP:[6,0],
 expl:"x = 6 and y = 0, so P is (6, 0), which lies on the x-axis."},
{sec:"G",type:"mc",q:"Which point lies on the y-axis?",mono:true,opts:["(0, 5)","(5, 0)","(5, 5)","(1, 5)"],a:0,
 expl:"Points on the y-axis have an x-coordinate of 0, so (0, 5) is on the y-axis."},
{lvl:2,sec:"G",type:"pair",q:"Start at (2, 3). Move 4 units right and 1 unit up. Where do you land?",ansP:[6,4],
 expl:"Add 4 to x and 1 to y: (2 + 4, 3 + 1) = (6, 4)."},
{lvl:2,sec:"G",type:"in",q:"How many units apart are the points (3, 8) and (3, 2)?",ans:6,
 hint:"They have the same x-coordinate, so the distance is straight up and down.",
 expl:"Both points are on the vertical line x = 3, so the distance is 8 − 2 = 6 units."},
{lvl:2,sec:"G",type:"pair",q:"Three corners of a rectangle are (1, 1), (5, 1) and (5, 4). Write the fourth corner.",ansP:[1,4],
 hint:"The missing corner shares an x with one corner and a y with another.",
 expl:"The fourth corner sits above (1, 1) at the same height as (5, 4), so it is (1, 4)."},
{lvl:2,sec:"G",type:"multi",q:"The points (1, 2), (2, 4) and (3, 6) follow one rule. Select EVERY point that follows the same rule.",mono:true,
 opts:["(4, 8)","(5, 10)","(6, 3)","(0, 1)"],aMulti:[0,1],
 expl:"In each pair y is double x. (4, 8) and (5, 10) fit; (6, 3) and (0, 1) do not."},
{lvl:3,sec:"G",type:"pair",q:"Tomas walks from (1, 2) to (7, 2), then turns and walks the same distance straight up. Write where he stops.",ansP:[7,8],
 hint:"How far did he walk on the first leg?",
 expl:"The first leg is 7 − 1 = 6 units. Going 6 units up from (7, 2) reaches (7, 8)."},
{lvl:3,sec:"G",type:"in",q:"A square has corners at (2, 3), (6, 3), (6, 7) and (2, 7). What is its perimeter in units?",ans:16,
 hint:"Find one side length from two corners that share a coordinate.",
 expl:"From (2, 3) to (6, 3) is 4 units, so each side is 4 and the perimeter is 4 × 4 = 16 units."},
{lvl:3,sec:"G",type:"pair",q:"Point A is (3, 5). Point B is 2 units left of A and 4 units up. Point C is 6 units right of B. Write the coordinates of C.",ansP:[7,9],
 hint:"Find B first.",expl:"B = (3 − 2, 5 + 4) = (1, 9). Then C = (1 + 6, 9) = (7, 9)."}
],

"g5-hierarchy": [
{sec:"G",type:"mc",q:"Every square is also a ...",opts:["rectangle","triangle","pentagon","circle"],a:0,
 expl:"A square has four right angles and opposite sides equal, so it meets every rule for a rectangle."},
{sec:"G",type:"mc",q:"Which statement is true?",
 opts:["All rectangles are parallelograms","All parallelograms are rectangles","All rhombuses are squares","All trapezoids are rectangles"],a:0,
 expl:"A rectangle has two pairs of parallel sides, so it is always a parallelogram. The other statements fail for tilted shapes."},
{sec:"G",type:"in",q:"How many pairs of parallel sides does a parallelogram have?",ans:2,
 expl:"By definition both pairs of opposite sides are parallel, so it has 2 pairs."},
{sec:"G",type:"mc",q:"A quadrilateral has four equal sides but no right angles. What is it called?",
 opts:["rhombus","square","rectangle","trapezoid"],a:0,
 expl:"Four equal sides make a rhombus. With right angles it would also be a square, but here it has none."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY name that correctly describes a square.",
 opts:["Rectangle","Rhombus","Parallelogram","Triangle"],aMulti:[0,1,2],
 expl:"A square has four right angles (rectangle), four equal sides (rhombus) and two pairs of parallel sides (parallelogram). It has four sides, not three."},
{lvl:2,sec:"G",type:"mc",q:"A shape is a rectangle. Which property MUST it have?",
 opts:["Four right angles","Four equal sides","Exactly one pair of parallel sides","All angles of 60°"],a:0,
 expl:"Every rectangle has four right angles. Its sides need not all be equal, and it has two pairs of parallel sides."},
{lvl:2,sec:"G",type:"order",q:"Order these shape groups from the most general to the most specific.",
 items:["Square","Quadrilateral","Rectangle","Parallelogram"],ansOrder:["Quadrilateral","Parallelogram","Rectangle","Square"],
 expl:"Each group is inside the one before: all squares are rectangles, all rectangles are parallelograms, all parallelograms are quadrilaterals."},
{lvl:2,sec:"G",type:"mc",q:"Which kind of triangle is impossible?",
 opts:["A right equilateral triangle","A right isosceles triangle","An obtuse scalene triangle","An acute isosceles triangle"],a:0,
 expl:"An equilateral triangle has three 60° angles, so it can never have a 90° angle. The other three all exist."},
{lvl:3,sec:"G",type:"mc",q:"Ingrid says 'a rhombus with four right angles is a square'. Elias says 'a rectangle with four equal sides is a square'. Who is correct?",
 opts:["Both of them","Only Ingrid","Only Elias","Neither of them"],a:0,
 expl:"A square is exactly a shape with four equal sides and four right angles. Each of them starts with one property and adds the other, so both are right."},
{lvl:3,sec:"G",type:"multi",q:"Select EVERY statement that is ALWAYS true.",
 opts:["A square is a rhombus","A rhombus is a square","A rectangle is a parallelogram","A trapezoid is a parallelogram"],aMulti:[0,2],
 expl:"Squares have four equal sides, so they are rhombuses; rectangles have two pairs of parallel sides, so they are parallelograms. A tilted rhombus is not a square, and a trapezoid need not have two parallel pairs."},
{lvl:3,sec:"G",type:"in",q:"Sofia draws a quadrilateral with exactly one pair of parallel sides. What is the greatest number of right angles it can have?",ans:2,
 hint:"Try drawing one side perpendicular to both parallel sides.",
 expl:"One side can be perpendicular to both parallel sides, giving 2 right angles. A third right angle would force the other pair of sides parallel too, which is not allowed. So the greatest is 2."}
]
};
