/* Grade 5. */
export const G5_BANKS = {
"g5-express": [
{sec:"P",type:"in",q:"Evaluate: 3 + 4 × 2",ans:11,hint:"Multiply before you add.",
 expl:"Do 4 × 2 = 8 first, then 3 + 8 = 11."},
{sec:"P",type:"in",q:"Evaluate: (5 + 3) × 2",ans:16,expl:"Parentheses first: 5 + 3 = 8, then 8 × 2 = 16."},
{sec:"P",type:"mc",q:"Which expression equals 20?",mono:true,
 opts:["4 × (3 + 2)","4 × 3 + 2","4 + 3 × 2","4 × 3 − 2"],a:0,
 expl:"4 × (3 + 2) = 4 × 5 = 20. The others give 14, 10 and 10."},
{sec:"P",type:"in",q:"Evaluate: 18 − 2 × 5",ans:8,hint:"Multiply before you subtract.",
 expl:"2 × 5 = 10 first, then 18 − 10 = 8."},
{sec:"P",type:"in",q:"Evaluate: (10 − 4) × (3 + 1)",ans:24,
 expl:"Each parenthesis first: 10 − 4 = 6 and 3 + 1 = 4, then 6 × 4 = 24."},
{lvl:2,sec:"P",type:"in",q:"Evaluate: 2 × (6 + 4) − 5",ans:15,
 expl:"6 + 4 = 10, then 2 × 10 = 20, then 20 − 5 = 15."},
{lvl:2,sec:"P",type:"mc",q:"Which expression represents 'add 5 and 3, then double the result'?",mono:true,
 opts:["2 × (5 + 3)","2 × 5 + 3","5 + 3 × 2","(2 × 5) + 3"],a:0,
 expl:"'Then double the result' means the addition happens first, inside parentheses, before multiplying by 2."},
{lvl:3,sec:"P",type:"in",q:"Evaluate: 3 × [(8 − 2) + (5 × 2)]",ans:48,
 hint:"Work the innermost parts first.",
 expl:"8 − 2 = 6 and 5 × 2 = 10, so inside the brackets: 6 + 10 = 16. Then 3 × 16 = 48."}
],

"g5-decops": [
{sec:"D",type:"in",q:"3.4 + 2.8 = ?",ans:6.2,expl:"3.4 + 2.8 = 6.2."},
{sec:"D",type:"in",q:"7.5 − 3.2 = ?",ans:4.3,expl:"7.5 − 3.2 = 4.3."},
{sec:"D",type:"in",q:"0.6 × 5 = ?",ans:3,expl:"0.6 × 5 = 3."},
{sec:"D",type:"mc",q:"Which is 4.25 + 1.5?",opts:["5.75","5.65","4.4","5.25"],a:0,
 expl:"4.25 + 1.50 = 5.75."},
{sec:"D",type:"in",q:"12.6 ÷ 3 = ?",ans:4.2,expl:"12.6 ÷ 3 = 4.2."},
{lvl:2,sec:"D",type:"in",q:"2.35 × 4 = ?",ans:9.4,expl:"2.35 × 4 = 9.4."},
{lvl:2,sec:"D",type:"in",q:"A ribbon is 8.4 m long. It is cut into pieces 1.2 m each. How many pieces are there?",
 ans:7,expl:"8.4 ÷ 1.2 = 7 pieces."},
{lvl:3,sec:"D",type:"in",q:"A runner's three times were 12.45, 11.9 and 12.05 seconds. What is the total time, in seconds?",
 ans:36.4,expl:"12.45 + 11.9 + 12.05 = 36.4 seconds."}
],

"g5-unlike": [
{sec:"F",type:"mc",q:"1/2 + 1/3 = ?",mono:true,opts:["5/6","2/5","1/6","2/6"],a:0,
 expl:"The LCD of 2 and 3 is 6: 3/6 + 2/6 = 5/6."},
{sec:"F",type:"mc",q:"3/4 − 1/6 = ?",mono:true,opts:["7/12","2/12","5/12","1/12"],a:0,
 expl:"The LCD of 4 and 6 is 12: 9/12 − 2/12 = 7/12."},
{sec:"F",type:"mc",q:"Which is the LCD of 1/4 and 1/6?",mono:true,opts:["12","24","10","6"],a:0,
 expl:"The smallest number both 4 and 6 divide into evenly is 12."},
{sec:"F",type:"mc",q:"2/3 + 1/4 = ?",mono:true,opts:["11/12","3/7","9/12","1/12"],a:0,
 expl:"The LCD of 3 and 4 is 12: 8/12 + 3/12 = 11/12."},
{sec:"F",type:"mc",q:"5/6 − 1/2 = ?",mono:true,opts:["1/3","1/6","2/3","1/2"],a:0,
 expl:"The LCD of 6 and 2 is 6: 5/6 − 3/6 = 2/6, which simplifies to 1/3."},
{lvl:2,sec:"F",type:"mc",q:"3/5 + 1/4 = ?",mono:true,opts:["17/20","4/9","13/20","1/20"],a:0,
 expl:"The LCD of 5 and 4 is 20: 12/20 + 5/20 = 17/20."},
{lvl:2,sec:"F",type:"mc",q:"7/8 − 2/3 = ?",mono:true,opts:["5/24","9/24","5/11","1/24"],a:0,
 expl:"The LCD of 8 and 3 is 24: 21/24 − 16/24 = 5/24."},
{lvl:3,sec:"F",type:"mc",q:"1/2 + 1/3 + 1/6 = ?",mono:true,opts:["1","5/6","1/6","2"],a:0,
 expl:"The LCD of 2, 3 and 6 is 6: 3/6 + 2/6 + 1/6 = 6/6, which equals 1 whole."}
],

"g5-thousandth": [
{sec:"N",type:"in",q:"What is the value of the 5 in 3.256? Type as a decimal, like 0.05.",ans:0.05,
 expl:"The 5 sits in the hundredths place: 5 hundredths = 0.05."},
{sec:"N",type:"in",q:"Write 'four and seven thousandths' as a decimal.",ans:4.007,
 expl:"4 and 7 thousandths = 4.007."},
{sec:"N",type:"mc",q:"Which decimal is the SAME as 2.400?",opts:["2.4","2.04","24","0.24"],a:0,
 expl:"Trailing zeros after the last meaningful digit do not change a decimal's value."},
{sec:"N",type:"in",q:"Round 5.678 to the nearest hundredth.",ans:5.68,
 expl:"The thousandths digit is 8, which rounds the hundredths digit up: 5.68."},
{sec:"N",type:"mc",q:"Which number has a digit in the thousandths place?",
 opts:["0.125","1.25","12.5","125"],a:0,
 expl:"0.125 has three decimal places: tenths, hundredths, and thousandths (the 5)."},
{lvl:2,sec:"N",type:"in",q:"Round 3.4562 to the nearest thousandth.",ans:3.456,
 expl:"The ten-thousandths digit is 2, which rounds down: 3.456."},
{lvl:2,sec:"N",type:"mc",q:"Which symbol makes this true?  0.5 ◯ 0.500",opts:["=","<",">"],a:0,
 expl:"Trailing zeros do not change the value: 0.5 and 0.500 are equal."},
{lvl:3,sec:"N",type:"in",q:"What is 10 times 0.045?",ans:0.45,
 hint:"Multiplying by 10 shifts every digit one place value to the left.",
 expl:"Multiplying by 10 moves the decimal point one place right: 0.045 × 10 = 0.45."}
],

"g5-fracmult": [
{sec:"F",type:"mc",q:"1/2 × 1/3 = ?",mono:true,opts:["1/6","1/5","2/5","1/3"],a:0,
 expl:"Multiply numerators and denominators: (1×1)/(2×3) = 1/6."},
{sec:"F",type:"mc",q:"2/3 × 3/4 = ?",mono:true,opts:["1/2","5/7","6/7","3/4"],a:0,
 expl:"(2×3)/(3×4) = 6/12, which simplifies to 1/2."},
{sec:"F",type:"in",q:"3/4 of 8 = ?",ans:6,expl:"3/4 × 8 = 24/4 = 6."},
{sec:"F",type:"mc",q:"Multiplying a whole number by a fraction less than 1 makes the result ___.",
 opts:["smaller than the whole number","larger than the whole number","always 1","always 0"],a:0,
 expl:"Taking a fraction of something less than the whole always gives less than the original amount."},
{sec:"F",type:"in",q:"1/2 × 10 = ?",ans:5,expl:"1/2 × 10 = 10/2 = 5."},
{lvl:2,sec:"F",type:"mc",q:"3/5 × 2/3 = ?",mono:true,opts:["2/5","5/8","6/8","1/2"],a:0,
 expl:"(3×2)/(5×3) = 6/15, which simplifies to 2/5."},
{lvl:2,sec:"F",type:"in",q:"2/3 of 18 = ?",ans:12,expl:"2/3 × 18 = 36/3 = 12."},
{lvl:3,sec:"F",type:"mc",q:"1/4 × 2/3 × 3/2 = ?",mono:true,opts:["1/4","1/2","1/8","3/4"],a:0,
 expl:"Multiply straight across: (1×2×3)/(4×3×2) = 6/24, which simplifies to 1/4."}
],

"g5-fracdiv": [
{sec:"F",type:"in",q:"1/2 ÷ 4 = ? Type just the denominator of the answer (the numerator is 1).",
 ans:8,expl:"1/2 ÷ 4 = 1/8, so the denominator is 8."},
{sec:"F",type:"in",q:"1/3 ÷ 2 = ? Type just the denominator of the answer.",ans:6,
 expl:"1/3 ÷ 2 = 1/6, so the denominator is 6."},
{sec:"F",type:"mc",q:"6 ÷ 1/3 = ?",opts:["18","2","3","6"],a:0,
 expl:"Dividing by a fraction multiplies by its reciprocal: 6 × 3 = 18."},
{sec:"F",type:"in",q:"4 ÷ 1/2 = ?",ans:8,expl:"4 × 2 = 8."},
{sec:"F",type:"mc",q:"Which expression equals 1/5 ÷ 3?",mono:true,
 opts:["1/15","3/5","5/3","1/8"],a:0,expl:"1/5 ÷ 3 = 1/5 × 1/3 = 1/15."},
{lvl:2,sec:"F",type:"in",q:"1/4 ÷ 5 = ? Type just the denominator of the answer.",ans:20,
 expl:"1/4 ÷ 5 = 1/20, so the denominator is 20."},
{lvl:2,sec:"F",type:"in",q:"8 ÷ 1/4 = ?",ans:32,expl:"8 × 4 = 32."},
{lvl:3,sec:"F",type:"in",q:"A ribbon that is 1/3 yard long is cut into pieces that are 1/9 yard each. How many pieces?",
 ans:3,hint:"Dividing by a fraction multiplies by its reciprocal.",
 expl:"(1/3) ÷ (1/9) = 1/3 × 9 = 3 pieces."}
],

"g5-convert": [
{sec:"M",type:"in",q:"How many centimeters are in 5 meters? (100 cm = 1 m)",ans:500,
 expl:"5 × 100 = 500 centimeters."},
{sec:"M",type:"in",q:"How many grams are in 3 kilograms? (1000 g = 1 kg)",ans:3000,
 expl:"3 × 1000 = 3000 grams."},
{sec:"M",type:"mc",q:"Which is equal to 2.5 liters?",opts:["2500 mL","250 mL","25 mL","25000 mL"],a:0,
 expl:"1 liter = 1000 mL, so 2.5 liters = 2500 mL."},
{sec:"M",type:"in",q:"How many minutes are in 3 hours?",ans:180,expl:"3 × 60 = 180 minutes."},
{sec:"M",type:"in",q:"How many millimeters are in 4 centimeters? (10 mm = 1 cm)",ans:40,
 expl:"4 × 10 = 40 millimeters."},
{lvl:2,sec:"M",type:"in",q:"A ribbon is 250 cm long. How many meters is that?",ans:2.5,
 expl:"250 ÷ 100 = 2.5 meters."},
{lvl:2,sec:"M",type:"in",q:"A recipe needs 1500 mL of water. How many liters is that?",ans:1.5,
 expl:"1500 ÷ 1000 = 1.5 liters."},
{lvl:3,sec:"M",type:"in",q:"A runner covers 3.2 kilometers. How many meters is that?",ans:3200,
 expl:"3.2 × 1000 = 3200 meters."}
],

"g5-patterns": [
{sec:"N",type:"in",q:"Pattern A starts at 0, rule 'add 2': 0, 2, 4, 6. What is the 4th term?",ans:6,
 expl:"0, 2, 4, 6 — the 4th term listed is 6."},
{sec:"N",type:"in",q:"Pattern B starts at 0, rule 'add 4': 0, 4, 8, 12. What is the 3rd term?",ans:8,
 expl:"0, 4, 8 — the 3rd term is 8."},
{sec:"N",type:"mc",q:"Pattern A's terms are 0, 2, 4, 6, 8. Pattern B's are 0, 4, 8, 12, 16. What is true about matching terms?",
 opts:["B's term is always twice A's term","They are always equal","A's term is always bigger","There is no relationship"],a:0,
 expl:"Each B term (4, 8, 12, 16) is exactly double the matching A term (2, 4, 6, 8)."},
{sec:"N",type:"in",q:"Pattern A starts at 0 and adds 2. What is its 3rd term?",ans:4,
 expl:"0, 2, 4 — the 3rd term is 4."},
{sec:"N",type:"mc",q:"Two patterns start at 0: one adds 3, one adds 6. What is always true of matching terms?",
 opts:["The 'adds 6' term is double the 'adds 3' term","They are equal","There is no relation","The 'adds 3' term is bigger"],a:0,
 expl:"Since 6 is double 3, every term in the second pattern is double the matching term in the first."},
{lvl:2,sec:"N",type:"in",q:"Pattern X starts at 1, rule 'add 3': 1, 4, 7, 10. What is the 5th term?",ans:13,
 expl:"1, 4, 7, 10, 13 — the 5th term is 13."},
{lvl:2,sec:"N",type:"in",q:"Pattern Y starts at 2, rule 'add 5': 2, 7, 12, 17. What is the 4th term?",ans:17,
 expl:"2, 7, 12, 17 — the 4th term is 17."},
{lvl:3,sec:"N",type:"in",q:"At the 3rd term, Pattern A (add 2 from 0) is 4 and Pattern B (add 3 from 0) is 6. What is the DIFFERENCE between them?",
 ans:2,expl:"6 − 4 = 2."}
],

"g5-twodigit": [
{sec:"N",type:"in",q:"252 ÷ 12 = ?",ans:21,expl:"252 ÷ 12 = 21."},
{sec:"N",type:"in",q:"180 ÷ 15 = ?",ans:12,expl:"180 ÷ 15 = 12."},
{sec:"N",type:"in",q:"364 ÷ 26 = ?",ans:14,expl:"364 ÷ 26 = 14."},
{sec:"N",type:"mc",q:"What is 480 ÷ 24?",opts:["20","18","24","16"],a:0,expl:"480 ÷ 24 = 20."},
{sec:"N",type:"in",q:"675 ÷ 27 = ?",ans:25,expl:"675 ÷ 27 = 25."},
{lvl:2,sec:"N",type:"in",q:"A school orders 936 pencils in boxes of 24. How many boxes?",ans:39,
 expl:"936 ÷ 24 = 39 boxes."},
{lvl:2,sec:"N",type:"in",q:"812 ÷ 28 = ?",ans:29,expl:"812 ÷ 28 = 29."},
{lvl:3,sec:"N",type:"in",q:"A number divided by 35 gives 18 with no remainder. What is the number?",ans:630,
 expl:"18 × 35 = 630."}
],

"g5-fracword": [
{sec:"F",type:"in",q:"A recipe needs 3/4 cup of flour. You want to make 1/2 the recipe. How much flour, as a decimal?",
 ans:0.375,expl:"3/4 × 1/2 = 3/8 = 0.375 cups."},
{sec:"F",type:"in",q:"You have 5/6 of a pizza and eat 1/3 of the whole pizza. How much is left? Type just the numerator (denominator 6).",
 ans:3,hint:"Turn 1/3 into sixths first.",expl:"1/3 = 2/6, so 5/6 − 2/6 = 3/6 is left."},
{sec:"F",type:"mc",q:"A ribbon is 3/4 yard long. You cut it into pieces that are 1/8 yard each. How many pieces?",
 opts:["6","3","8","4"],a:0,expl:"(3/4) ÷ (1/8) = 3/4 × 8 = 6 pieces."},
{sec:"F",type:"in",q:"You walk 2/3 mile, then 1/6 mile more. How far in total? Type just the numerator (denominator 6).",
 ans:5,hint:"Turn 2/3 into sixths first.",expl:"2/3 = 4/6, so 4/6 + 1/6 = 5/6 mile."},
{sec:"F",type:"in",q:"A tank is 3/5 full. You use 1/5 of the tank. What fraction is left? Type just the numerator (denominator 5).",
 ans:2,expl:"3/5 − 1/5 = 2/5."},
{lvl:2,sec:"F",type:"in",q:"A garden is 3/4 planted. Half of the planted area is flowers. What fraction of the WHOLE garden is flowers? Type as a decimal.",
 ans:0.375,expl:"3/4 × 1/2 = 3/8 = 0.375."},
{lvl:2,sec:"F",type:"in",q:"A recipe serves 6 people using 3/4 cup of rice. How much rice per person? Type as a decimal.",
 ans:0.125,expl:"3/4 ÷ 6 = 3/24 = 1/8 = 0.125 cups."},
{lvl:3,sec:"F",type:"in",q:"A tank starts 1/2 full. Water equal to 1/3 of the tank's capacity is added. What fraction of the tank is now full? Type as a decimal rounded to 2 places.",
 ans:0.83,expl:"1/2 + 1/3 = 5/6 ≈ 0.83."}
],

"g5-lineplot": [
{sec:"M",type:"in",q:"A line plot shows liquid measurements in cups: 3 X's at 1/4 cup, 2 X's at 1/2 cup. What is the TOTAL amount in cups? Type as a decimal.",
 ans:1.75,expl:"3 × 0.25 = 0.75, and 2 × 0.5 = 1. Together: 0.75 + 1 = 1.75 cups."},
{sec:"M",type:"in",q:"That total of 1.75 cups is redistributed EQUALLY among the 5 data points. How much per point? Type as a decimal.",
 ans:0.35,expl:"1.75 ÷ 5 = 0.35 cups."},
{sec:"M",type:"mc",q:"Dividing a line plot's total amount by the number of data points gives the ___.",
 opts:["average amount per point","biggest value","smallest value","total again"],a:0,
 expl:"That is exactly what an average (mean) is."},
{sec:"M",type:"in",q:"A line plot shows 4 X's at 1/3 cup and 2 X's at 2/3 cup. What is the total in cups? Type as a decimal, rounded to 2 places.",
 ans:2.67,expl:"4 × (1/3) + 2 × (2/3) = 4/3 + 4/3 = 8/3 ≈ 2.67 cups."},
{sec:"M",type:"in",q:"Using that same plot (4 X's at 1/3 cup, 2 X's at 2/3 cup), how many data points are there?",
 ans:6,expl:"4 + 2 = 6 data points."},
{lvl:2,sec:"M",type:"in",q:"A line plot has 5 X's at 1/2 inch and 3 X's at 1/4 inch. What is the total length, in inches? Type as a decimal.",
 ans:3.25,expl:"5 × 0.5 = 2.5, and 3 × 0.25 = 0.75. Together: 2.5 + 0.75 = 3.25 inches."},
{lvl:2,sec:"M",type:"in",q:"Using that plot, how many total data points are there?",ans:8,
 expl:"5 + 3 = 8 data points."},
{lvl:3,sec:"M",type:"in",q:"A line plot's total is 4.5 cups across 9 equal data points. How much is each data point, in cups? Type as a decimal.",
 ans:0.5,expl:"4.5 ÷ 9 = 0.5 cups."}
],

"g5-volume": [
{sec:"G",type:"in",q:"A box is 4 units long, 3 wide, and 2 tall. What is its volume in cubic units?",
 ans:24,expl:"4 × 3 × 2 = 24 cubic units."},
{sec:"G",type:"in",q:"A cube has sides of 5 units. What is its volume?",ans:125,expl:"5 × 5 × 5 = 125 cubic units."},
{sec:"G",type:"mc",q:"Which formula finds the volume of a rectangular prism?",mono:true,
 opts:["length × width × height","2 × (length + width)","length + width + height","length × width"],a:0,
 expl:"Volume of a box is the product of all three dimensions."},
{sec:"G",type:"in",q:"A box has a volume of 60 cubic units, length 5 and width 4. What is its height?",
 ans:3,expl:"60 ÷ (5 × 4) = 60 ÷ 20 = 3."},
{sec:"G",type:"in",q:"A box is 6 by 2 by 2. What is its volume?",ans:24,expl:"6 × 2 × 2 = 24 cubic units."},
{lvl:2,sec:"G",type:"in",q:"Two boxes are stacked: one is 3×2×2 = 12 cubic units, the other is 4×2×2 = 16 cubic units. What is their combined volume?",
 ans:28,expl:"12 + 16 = 28 cubic units."},
{lvl:2,sec:"G",type:"in",q:"A tank holds 100 cubic units. Half of it is filled. How many cubic units of water are in it?",
 ans:50,expl:"100 ÷ 2 = 50 cubic units."},
{lvl:3,sec:"G",type:"in",q:"A rectangular prism has volume 192 cubic units. Its length is 6 and its width is twice its height. What is its height?",
 ans:4,hint:"Let the height be h, so the width is 2h.",
 expl:"6 × 2h × h = 192, so 12h² = 192, h² = 16, and h = 4."}
],

"g5-coord": [
{sec:"G",type:"mc",q:"In an ordered pair (3, 5), which number tells you how far to move ALONG the x-axis?",
 opts:["3","5","Both","Neither"],a:0,expl:"The first number in an ordered pair is always the x-coordinate."},
{sec:"G",type:"in",q:"What is the x-coordinate of the point (7, 2)?",ans:7,expl:"The first number, 7, is the x-coordinate."},
{sec:"G",type:"in",q:"What is the y-coordinate of the point (7, 2)?",ans:2,expl:"The second number, 2, is the y-coordinate."},
{sec:"G",type:"mc",q:"The point (0, 0) is called the ___.",
 opts:["origin","x-axis","y-axis","quadrant"],a:0,expl:"(0, 0) is always the origin, where the axes cross."},
{sec:"G",type:"pair",q:"Plot the point 4 right and 2 up from the origin. Write it as an ordered pair.",ansP:[4,2],
 expl:"4 right sets x = 4, and 2 up sets y = 2: (4, 2)."},
{lvl:2,sec:"G",type:"pair",q:"A point is 3 units right and 5 units up from the origin. Write its ordered pair.",ansP:[3,5],
 expl:"3 right and 5 up gives (3, 5)."},
{lvl:2,sec:"G",type:"in",q:"Two points share the same y-coordinate of 6. One point is (2, 6). What is the y-coordinate of the OTHER point?",
 ans:6,expl:"Sharing the same y-coordinate means both points have y = 6."},
{lvl:3,sec:"G",type:"pair",q:"A rectangle has three corners at (0, 0), (5, 0) and (5, 3). What is the 4th corner?",ansP:[0,3],
 expl:"The 4th corner shares its x with (0, 0) and its y with (5, 3): (0, 3)."}
],

"g5-hierarchy": [
{sec:"G",type:"mc",q:"Every square is also a ___.",opts:["rectangle","triangle","pentagon","circle"],a:0,
 expl:"A square meets every requirement of a rectangle (4 right angles), plus more."},
{sec:"G",type:"mc",q:"Every rectangle is also a ___.",opts:["parallelogram","triangle","circle","pentagon"],a:0,
 expl:"A rectangle has two pairs of parallel sides, which makes it a parallelogram too."},
{sec:"G",type:"mc",q:"Is every rhombus a square?",opts:["No, only some are","Yes, always","No, never","Cannot tell"],a:0,
 expl:"A rhombus only needs 4 equal sides — it becomes a square only if its angles are also all right angles."},
{sec:"G",type:"mc",q:"Is every parallelogram a rectangle?",opts:["No, only some are","Yes, always","No, never","Cannot tell"],a:0,
 expl:"A parallelogram only needs two pairs of parallel sides — it becomes a rectangle only with right angles too."},
{sec:"G",type:"mc",q:"Which is the MOST general category that includes squares, rectangles, and rhombuses?",
 opts:["Parallelogram","Triangle","Circle","Pentagon"],a:0,
 expl:"Squares, rectangles and rhombuses all have two pairs of parallel sides, making them all parallelograms."},
{lvl:2,sec:"G",type:"mc",q:"A shape is a quadrilateral with 2 pairs of parallel sides. What MUST it be, at minimum?",
 opts:["A parallelogram","A square","A rectangle","A rhombus"],a:0,
 expl:"Two pairs of parallel sides is exactly the definition of a parallelogram — nothing more is guaranteed yet."},
{lvl:2,sec:"G",type:"mc",q:"Which statement is TRUE?",
 opts:["All squares are rhombuses, but not all rhombuses are squares","All rhombuses are squares","No squares are rhombuses","Squares and rhombuses are unrelated"],a:0,
 expl:"A square satisfies every rhombus requirement (4 equal sides) plus right angles, so it is a special rhombus."},
{lvl:3,sec:"G",type:"mc",q:"Order these from MOST specific to LEAST specific: square, quadrilateral, rectangle.",mono:true,
 opts:["Square, rectangle, quadrilateral","Quadrilateral, rectangle, square","Rectangle, square, quadrilateral","Square, quadrilateral, rectangle"],a:0,
 expl:"A square is the narrowest category, a rectangle is broader, and quadrilateral is the broadest of the three."}
]
};
