/* Grade 6 advanced / enrichment: number theory, algebra, extended geometry,
   combinatorics and probability at AMC 8 / Math Kangaroo level. */
export const G6_ADV_BANKS = {
"g6-modexp": [
{sec:"T",type:"in",q:"What is the remainder when 2^10 is divided by 7?",ans:2,
 hint:"Find a small power of 2 that leaves remainder 1.",
 expl:"2^3 = 8 leaves remainder 1, so 2^9 = (2^3)^3 leaves remainder 1 and 2^10 = 2^9 × 2 leaves remainder 2."},
{sec:"T",type:"mc",q:"Which number is the inverse of 3 modulo 7, meaning 3 × ? leaves remainder 1 when divided by 7?",
 mono:true,opts:["5","3","4","2"],a:0,expl:"3 × 5 = 15 = 2 × 7 + 1, so 5 is the inverse of 3 modulo 7."},
{sec:"T",type:"in",q:"What is the last digit of 7^4?",ans:1,hint:"Square 7, then square the result.",
 expl:"7^2 = 49 and 7^4 = 49^2 = 2401, so the last digit is 1."},
{lvl:2,sec:"T",type:"in",q:"Find the remainder when 3^100 is divided by 5.",ans:1,
 hint:"Look at the remainders of 3, 9, 27, 81 and spot the cycle.",
 expl:"3^4 = 81 leaves remainder 1 when divided by 5. Since 100 = 4 × 25, 3^100 = (3^4)^25 also leaves remainder 1."},
{lvl:2,sec:"T",type:"mc",q:"Which number has NO inverse modulo 12?",mono:true,opts:["8","5","7","11"],a:0,
 hint:"An inverse exists only when the number shares no factor with 12.",
 expl:"8 and 12 share the factor 4, so 8 × k is always a multiple of 4 and can never leave remainder 1. The others are coprime to 12."},
{lvl:2,sec:"T",type:"in",q:"What is the inverse of 4 modulo 9? Give a number from 1 to 8.",ans:7,
 hint:"Try 4 × 1, 4 × 2, ... and look for a remainder of 1.",
 expl:"4 × 7 = 28 = 3 × 9 + 1, so the inverse of 4 modulo 9 is 7."},
{lvl:3,sec:"T",type:"in",q:"What is the remainder when 7^2024 is divided by 100?",ans:1,
 hint:"Compute 7^4 first and think about its last two digits.",
 expl:"7^4 = 2401 leaves remainder 1 when divided by 100. Since 2024 = 4 × 506, 7^2024 = (7^4)^506 leaves remainder 1."},
{lvl:3,sec:"T",type:"in",q:"Solve 5x ≡ 3 (mod 11). Give the answer x from 0 to 10.",ans:5,
 hint:"First find the inverse of 5 modulo 11, then multiply both sides by it.",
 expl:"5 × 9 = 45 = 4 × 11 + 1, so the inverse of 5 is 9. Then x ≡ 3 × 9 = 27 ≡ 5. Check: 5 × 5 = 25 = 22 + 3."},
{lvl:3,sec:"T",type:"multi",q:"Select EVERY power of 2 that leaves remainder 1 when divided by 5.",
 mono:true,opts:["2^4","2^8","2^6","2^10"],aMulti:[0,1],
 expl:"2^4 = 16 and 2^8 = 256 both end in 6, one more than a multiple of 5. 2^6 = 64 and 2^10 = 1024 leave remainder 4."}
],

"g6-crt": [
{sec:"T",type:"in",q:"Find the smallest positive number that leaves remainder 1 when divided by 3 and remainder 2 when divided by 5.",
 ans:7,hint:"List numbers that leave remainder 2 when divided by 5 and test each.",
 expl:"Numbers with remainder 2 mod 5 are 2, 7, 12, ... and 7 = 2 × 3 + 1 also leaves remainder 1 mod 3. The answer is 7."},
{sec:"T",type:"mc",q:"A number leaves remainder 3 when divided by 4 and remainder 3 when divided by 5. Which could it be?",
 mono:true,opts:["23","13","18","27"],a:0,
 expl:"23 = 5 × 4 + 3 and 23 = 4 × 5 + 3, so 23 works. 13 leaves 1 mod 4, 18 leaves 2 mod 4 and 27 leaves 2 mod 5."},
{sec:"T",type:"in",q:"What is the smallest positive number that is 1 more than a multiple of 4 and also 1 more than a multiple of 6?",
 ans:13,hint:"Think about the least common multiple.",
 expl:"The number is 1 more than a common multiple of 4 and 6. The least common multiple is 12, so the answer is 13."},
{lvl:2,sec:"T",type:"in",q:"Find the smallest positive x with x ≡ 2 (mod 3), x ≡ 3 (mod 5) and x ≡ 2 (mod 7).",ans:23,
 hint:"Combine the mod 3 and mod 7 conditions first.",
 expl:"x ≡ 2 mod 3 and mod 7 means x ≡ 2 (mod 21): 2, 23, 44, ... The first with remainder 3 mod 5 is 23."},
{lvl:2,sec:"T",type:"mc",q:"Why does the system x ≡ 1 (mod 4), x ≡ 2 (mod 6) have no solution?",
 opts:["Any solution would be both odd and even","4 and 6 are both even so CRT never works","6 is not a prime number","The remainders are too small"],a:0,
 expl:"x ≡ 1 (mod 4) forces x to be odd, while x ≡ 2 (mod 6) forces x to be even. No number is both, so there is no solution."},
{lvl:2,sec:"T",type:"in",q:"How many positive numbers below 100 leave remainder 2 when divided by 6 and remainder 5 when divided by 9?",ans:5,
 hint:"Find the first solution, then notice solutions repeat every lcm(6, 9).",
 expl:"Numbers with remainder 5 mod 9 are 5, 14, 23, ... and 14 also leaves remainder 2 mod 6. Solutions repeat every 18: 14, 32, 50, 68, 86. That is 5 numbers."},
{lvl:3,sec:"T",type:"in",q:"Kenji counts his marbles. In rows of 3 there is 1 left over, in rows of 5 there are 4 left over, and in rows of 7 there are 6 left over. What is the fewest marbles he could have?",
 ans:34,hint:"Notice the rows of 5 and rows of 7 are each one short of a full row.",
 expl:"Remainders 4 mod 5 and 6 mod 7 mean the number is 1 less than a multiple of 35: 34, 69, ... Since 34 = 11 × 3 + 1, the answer is 34."},
{lvl:3,sec:"T",type:"in",q:"Find the smallest positive number that leaves remainder 1 when divided by each of 2, 3, 4, 5 and 6, but is exactly divisible by 7.",
 ans:301,hint:"The number is 1 more than a multiple of 60.",
 expl:"The number is 60k + 1. Testing 61, 121, 181, 241 gives remainders when divided by 7, but 301 = 7 × 43. The answer is 301."},
{lvl:3,sec:"T",type:"order",q:"Each system has a smallest positive solution. Put the systems in order from the smallest solution to the largest.",
 items:["x ≡ 3 (mod 4), x ≡ 0 (mod 5)","x ≡ 1 (mod 2), x ≡ 0 (mod 3)","x ≡ 2 (mod 5), x ≡ 1 (mod 3)"],
 ansOrder:["x ≡ 1 (mod 2), x ≡ 0 (mod 3)","x ≡ 2 (mod 5), x ≡ 1 (mod 3)","x ≡ 3 (mod 4), x ≡ 0 (mod 5)"],
 hint:"Solve each system separately before ordering.",
 expl:"The solutions are 3 (odd multiple of 3), 7 (7 = 5 + 2 and 7 = 6 + 1) and 15 (multiple of 5 with remainder 3 mod 4), so the order is 3, 7, 15."}
],

"g6-diophant": [
{sec:"T",type:"mc",q:"Which pair (x, y) of whole numbers is a solution of 3x + 5y = 19?",mono:true,
 opts:["(3, 2)","(2, 3)","(4, 1)","(1, 4)"],a:0,
 expl:"3 × 3 + 5 × 2 = 9 + 10 = 19. The other pairs give 21, 17 and 23."},
{sec:"T",type:"in",q:"How many pairs of positive whole numbers (x, y) satisfy x + 2y = 10?",ans:4,
 hint:"Try y = 1, 2, 3, ... and see what x must be.",
 expl:"y = 1, 2, 3, 4 gives x = 8, 6, 4, 2. For y = 5, x would be 0, which is not positive. There are 4 pairs."},
{sec:"T",type:"mc",q:"Why does 4x + 6y = 15 have no whole-number solutions?",
 opts:["The left side is always even","15 is odd so x must be odd","4 and 6 are too large","x and y would have to be equal"],a:0,
 expl:"4x and 6y are both even, so their sum is even. It can never equal 15, which is odd."},
{lvl:2,sec:"T",type:"in",q:"Stamps cost 5 cents and 7 cents. Priya pays exactly 51 cents using both kinds. How many 7-cent stamps does she use?",
 ans:3,hint:"Try each number of 7-cent stamps and see whether what is left is a multiple of 5.",
 expl:"With three 7-cent stamps she spends 21 cents, leaving 30 cents = six 5-cent stamps. No other count of 7-cent stamps leaves a multiple of 5 under 51. She uses 3."},
{lvl:2,sec:"T",type:"in",q:"Using only 3-cent and 5-cent stamps, what is the largest amount in cents that CANNOT be made?",ans:7,
 hint:"Check 1, 2, 3, ... and notice that once three amounts in a row work, everything after works.",
 expl:"3, 5, 6 and 8, 9, 10 can be made, and adding 3 to 8, 9, 10 covers everything larger. Neither 7 nor 4 can be made, so the largest is 7."},
{lvl:2,sec:"T",type:"mc",q:"For which value of c does 6x + 9y = c have an integer solution?",mono:true,
 opts:["c = 30","c = 20","c = 10","c = 25"],a:0,
 expl:"6x + 9y is always a multiple of gcd(6, 9) = 3. Only 30 is a multiple of 3: for example x = 5, y = 0."},
{lvl:3,sec:"T",type:"in",q:"Lior buys pens at $3 each and notebooks at $7 each. He spends exactly $52 and buys at least one of each. How many different ways could he do this?",
 ans:3,hint:"The money spent on notebooks must leave a multiple of 3.",
 expl:"1 notebook leaves $45 = 15 pens, 4 notebooks leave $24 = 8 pens, 7 notebooks leave $3 = 1 pen. 10 notebooks cost too much. There are 3 ways."},
{lvl:3,sec:"T",type:"in",q:"Find the smallest positive whole number x for which 7x − 4y = 1 has a positive whole-number solution y.",ans:3,
 hint:"7x must be 1 more than a multiple of 4.",
 expl:"7 × 1 = 7 and 7 × 2 = 14 are not 1 more than a multiple of 4, but 7 × 3 = 21 = 4 × 5 + 1. So x = 3 with y = 5."},
{lvl:3,sec:"T",type:"multi",q:"Select EVERY value of c for which 4x + 10y = c has a solution in integers.",mono:true,
 opts:["6","20","7","15"],aMulti:[0,1],
 expl:"4x + 10y is always even, and every even number works since 4 × 3 − 10 × 1 = 2. So 6 and 20 work; 7 and 15 are odd."}
],

"g6-basearith": [
{sec:"T",type:"in",q:"Add in base 5: 23 (base 5) + 14 (base 5). Type the answer as a base-5 numeral.",ans:42,
 hint:"In base 5, a column carries when it reaches 5.",
 expl:"Units: 3 + 4 = 7 = 1 five and 2, write 2 carry 1. Fives: 2 + 1 + 1 = 4. The sum is 42 (base 5), which is 22 in base 10."},
{sec:"T",type:"mc",q:"Which of these is NOT a valid numeral in base 4?",mono:true,opts:["134","123","301","210"],a:0,
 expl:"Base 4 uses only the digits 0, 1, 2 and 3. The numeral 134 contains a 4, so it is not valid."},
{sec:"T",type:"in",q:"Convert 1011 (base 2) to base 10.",ans:11,hint:"The place values are 8, 4, 2, 1.",
 expl:"1 × 8 + 0 × 4 + 1 × 2 + 1 × 1 = 11."},
{lvl:2,sec:"T",type:"in",q:"Multiply in base 2: 101 × 11 (both base 2). Type the answer as a base-2 numeral.",ans:1111,
 hint:"You can convert to base 10, multiply, and convert back.",
 expl:"101 (base 2) = 5 and 11 (base 2) = 3, and 5 × 3 = 15 = 8 + 4 + 2 + 1 = 1111 (base 2)."},
{lvl:2,sec:"T",type:"in",q:"Subtract in base 8: 52 (base 8) − 27 (base 8). Type the answer as a base-8 numeral.",ans:23,
 hint:"When you borrow in base 8, you borrow eight, not ten.",
 expl:"Units: 2 − 7 needs a borrow, 10 − 7 = 3 (that is 8 + 2 − 7). Eights: 4 − 2 = 2. The answer is 23 (base 8), which is 19 in base 10."},
{lvl:2,sec:"T",type:"mc",q:"In base 6, what is 5 + 5?",mono:true,opts:["14","10","12","A"],a:0,
 expl:"5 + 5 = 10 in base 10, and 10 = 1 six + 4, so it is written 14 in base 6."},
{lvl:2,sec:"T",type:"in",q:"In some base b, the numeral 25 (base b) equals 17 in base 10. What is b?",ans:6,
 hint:"Write 25 (base b) as 2 × b + 5.",expl:"2b + 5 = 17 gives 2b = 12, so b = 6. Check: 2 × 6 + 5 = 17."},
{lvl:3,sec:"T",type:"in",q:"In which base b does the multiplication 3 × 4 = 20 hold?",ans:6,
 hint:"20 (base b) means 2 groups of b.",
 expl:"3 × 4 = 12 in base 10, and 20 (base b) = 2b, so 2b = 12 and b = 6."},
{lvl:3,sec:"T",type:"in",q:"Add in base 3: 2102 (base 3) + 1221 (base 3). Type the answer as a base-3 numeral.",ans:11100,
 hint:"Work column by column from the right, carrying whenever a column reaches 3.",
 expl:"Units 2 + 1 = 3, write 0 carry 1. Threes 0 + 2 + 1 = 3, write 0 carry 1. Nines 1 + 2 + 1 = 4, write 1 carry 1. Twenty-sevens 2 + 1 + 1 = 4, write 1 carry 1. Result 11100 (base 3) = 117."},
{lvl:3,sec:"T",type:"mc",q:"For every base b of 3 or more, the numeral 121 (base b) is always which kind of number?",
 opts:["A perfect square","A prime number","An odd number","A multiple of 3"],a:0,
 hint:"Write 121 (base b) as an expression in b and try to factor it.",
 expl:"121 (base b) = b² + 2b + 1 = (b + 1)², so it is always a perfect square. For example 121 (base 3) = 16 = 4²."}
],

"g6-contfrac": [
{sec:"T",type:"in",q:"Evaluate 1 + 1/(2 + 1/2). Give the answer as a decimal.",ans:1.4,
 hint:"Work from the inside out: simplify 2 + 1/2 first.",
 expl:"2 + 1/2 = 5/2, so 1/(5/2) = 2/5, and 1 + 2/5 = 7/5 = 1.4."},
{sec:"T",type:"mc",q:"Which continued fraction is equal to 7/3?",mono:true,
 opts:["2 + 1/3","3 + 1/2","1 + 1/(2 + 1/3)","2 + 1/(1 + 1/3)"],a:0,
 expl:"7/3 = 2 remainder 1, so 7/3 = 2 + 1/3. The others equal 7/2, 10/7 and 11/4."},
{sec:"T",type:"in",q:"Write 9/4 as a continued fraction [a; b], meaning a + 1/b. What is b?",ans:4,
 hint:"Split 9/4 into a whole number and a fraction with numerator 1.",
 expl:"9/4 = 2 + 1/4, so a = 2 and b = 4."},
{lvl:2,sec:"T",type:"in",q:"The continued fraction of 17/5 is [3; a, b]. What is a?",ans:2,
 hint:"Take out the whole part, then flip the leftover fraction and repeat.",
 expl:"17/5 = 3 + 2/5. Flip 2/5 to get 5/2 = 2 + 1/2. So 17/5 = [3; 2, 2] and a = 2."},
{lvl:2,sec:"T",type:"in",q:"Evaluate the continued fraction [2; 1, 4], which means 2 + 1/(1 + 1/4). Give the answer as a decimal.",ans:2.8,
 hint:"Simplify 1 + 1/4 first, then take its reciprocal.",
 expl:"1 + 1/4 = 5/4, its reciprocal is 4/5, and 2 + 4/5 = 2.8."},
{lvl:2,sec:"T",type:"mc",q:"The Euclidean algorithm gives 45 = 2 × 19 + 7, 19 = 2 × 7 + 5, 7 = 1 × 5 + 2, 5 = 2 × 2 + 1. What is the continued fraction of 45/19?",
 mono:true,opts:["[2; 2, 1, 2, 2]","[2; 2, 1, 2]","[2; 1, 2, 2, 1]","[1; 2, 2, 1, 2]"],a:0,
 expl:"The quotients in each division step, 2, 2, 1, 2, 2, are exactly the terms of the continued fraction: 45/19 = [2; 2, 1, 2, 2]."},
{lvl:3,sec:"T",type:"in",q:"The convergents of √2 = [1; 2, 2, 2, ...] begin 1/1, 3/2, 7/5, 17/12. What is the numerator of the next convergent?",ans:41,
 hint:"Each numerator is twice the previous one plus the one before that.",
 expl:"Numerators follow 1, 3, 7, 17, ... where each is 2 × previous + the one before: 2 × 17 + 7 = 41. The convergent is 41/29."},
{lvl:3,sec:"T",type:"in",q:"Let x = 1 + 1/(1 + 1/(1 + ...)) continue forever, so x = 1 + 1/x. What is the value of x² − x?",ans:1,
 hint:"Multiply both sides of x = 1 + 1/x by x.",
 expl:"Multiplying x = 1 + 1/x by x gives x² = x + 1, so x² − x = 1. (This x is the golden ratio.)"},
{lvl:3,sec:"T",type:"mc",q:"The infinite continued fraction [2; 2, 2, 2, ...] equals which number?",mono:true,
 opts:["1 + √2","√2","2 + √2","√5"],a:0,
 hint:"Call the value x and notice that x = 2 + 1/x.",
 expl:"If x = 2 + 1/x then x² − 2x − 1 = 0, so x = 1 + √2 (the positive root). Check: 1 + √2 ≈ 2.414 and 2 + 1/2.414 ≈ 2.414."}
],

"g6-perfect": [
{sec:"T",type:"mc",q:"A perfect number equals the sum of its proper divisors (all divisors except itself). Which of these is perfect?",
 mono:true,opts:["6","8","10","12"],a:0,
 expl:"The proper divisors of 6 are 1, 2 and 3, and 1 + 2 + 3 = 6. The sums for 8, 10 and 12 are 7, 8 and 16."},
{sec:"T",type:"in",q:"The proper divisors of 12 are 1, 2, 3, 4 and 6. What is their sum?",ans:16,
 expl:"1 + 2 + 3 + 4 + 6 = 16, which is more than 12, so 12 is abundant."},
{sec:"T",type:"mc",q:"Is 15 abundant, deficient or perfect?",opts:["Deficient","Abundant","Perfect"],a:0,
 hint:"Add the proper divisors and compare the total with 15.",
 expl:"The proper divisors of 15 are 1, 3 and 5, with sum 9. Since 9 < 15, the number 15 is deficient."},
{lvl:2,sec:"T",type:"in",q:"What is the smallest abundant number?",ans:12,
 hint:"Check the divisor sums of the numbers from 1 upward.",
 expl:"Every number below 12 has a proper-divisor sum at most itself (6 is perfect). For 12 the sum is 1 + 2 + 3 + 4 + 6 = 16 > 12."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY abundant number.",mono:true,opts:["18","20","16","14"],aMulti:[0,1],
 expl:"18: 1 + 2 + 3 + 6 + 9 = 21 > 18. 20: 1 + 2 + 4 + 5 + 10 = 22 > 20. 16 gives 15 and 14 gives 10, so those are deficient."},
{lvl:2,sec:"T",type:"in",q:"After 6, what is the next perfect number?",ans:28,
 hint:"It is less than 30 and even.",
 expl:"The proper divisors of 28 are 1, 2, 4, 7 and 14, and 1 + 2 + 4 + 7 + 14 = 28."},
{lvl:3,sec:"T",type:"in",q:"How many of the numbers from 1 to 30 are abundant?",ans:5,
 hint:"Primes and prime powers are never abundant, so focus on numbers with several small factors.",
 expl:"The abundant numbers up to 30 are 12, 18, 20, 24 (sum 36) and 30 (sum 42). That is 5 numbers."},
{lvl:3,sec:"T",type:"in",q:"When 2^p − 1 is prime, the number 2^(p−1) × (2^p − 1) is perfect. What perfect number does p = 5 give?",ans:496,
 hint:"Compute 2^4 and 2^5 − 1, then multiply.",
 expl:"2^4 = 16 and 2^5 − 1 = 31, which is prime. So the perfect number is 16 × 31 = 496."},
{lvl:3,sec:"T",type:"mc",q:"Why must every multiple of an abundant number also be abundant?",
 opts:["Scaling the smaller number's divisors already gives a sum that is too big","All even numbers are abundant","Bigger numbers always have bigger divisor sums","It must have more prime factors"],a:0,
 expl:"If n is abundant and m = kn, then k times each proper divisor of n is a proper divisor of m, and 1 is too. Their sum already exceeds m, so m is abundant."}
],

"g6-bothsides": [
{sec:"L",type:"in",q:"Solve 5x + 3 = 2x + 12.",ans:3,hint:"Collect the x terms on one side first.",
 expl:"Subtract 2x: 3x + 3 = 12. Subtract 3: 3x = 9, so x = 3."},
{sec:"L",type:"in",q:"Solve 7x − 4 = 3x + 16.",ans:5,expl:"Subtract 3x: 4x − 4 = 16. Add 4: 4x = 20, so x = 5."},
{sec:"L",type:"mc",q:"What is a sensible first step to solve 4x + 9 = x + 21?",
 opts:["Subtract x from both sides","Divide both sides by 4","Add 9 to both sides","Multiply both sides by x"],a:0,
 expl:"Subtracting x from both sides collects the variable terms: 3x + 9 = 21. Dividing by 4 first would create fractions."},
{lvl:2,sec:"L",type:"in",q:"Solve 3(x + 2) = 5x − 8.",ans:7,hint:"Expand the bracket first.",
 expl:"3x + 6 = 5x − 8. Add 8 and subtract 3x: 14 = 2x, so x = 7."},
{lvl:2,sec:"L",type:"in",q:"Solve 2x − 7 = 6x + 5.",ans:-3,hint:"The answer is negative.",
 expl:"Subtract 2x: −7 = 4x + 5. Subtract 5: −12 = 4x, so x = −3."},
{lvl:2,sec:"L",type:"mc",q:"How many solutions does 3x + 5 = 3x − 2 have?",opts:["None","One","Two","Infinitely many"],a:0,
 expl:"Subtracting 3x from both sides gives 5 = −2, which is never true. There are no solutions."},
{lvl:3,sec:"L",type:"in",q:"Zainab has $40 saved and adds $6 each week. Tomas has $10 saved and adds $9 each week. After how many weeks will they have the same amount?",
 ans:10,hint:"Write an expression for each person's savings after w weeks and set them equal.",
 expl:"40 + 6w = 10 + 9w. Subtract 6w and 10: 30 = 3w, so w = 10 weeks. Both then have $100."},
{lvl:3,sec:"L",type:"in",q:"Solve (x + 4)/3 = (2x − 1)/2. Give the answer as a decimal.",ans:2.75,
 hint:"Cross-multiply to clear the fractions.",
 expl:"2(x + 4) = 3(2x − 1), so 2x + 8 = 6x − 3. Then 11 = 4x and x = 2.75."},
{lvl:3,sec:"L",type:"mc",q:"For which value of k does 4x + k = 2(2x + 3) have infinitely many solutions?",mono:true,
 opts:["6","3","0","No value"],a:0,
 hint:"Expand the right side and compare it with the left side.",
 expl:"The right side is 4x + 6. The equation is true for every x exactly when both sides are identical, so k = 6."}
],

"g6-compound": [
{sec:"L",type:"mc",q:"Which list contains only numbers that satisfy −2 < x ≤ 3?",mono:true,
 opts:["−1, 0, 3","−2, 0, 3","−1, 3, 4","−3, 0, 1"],a:0,
 expl:"x must be bigger than −2 (so −2 and −3 are out) and at most 3 (so 4 is out). Only −1, 0, 3 all fit."},
{sec:"L",type:"in",q:"How many integers satisfy 1 ≤ x < 7?",ans:6,hint:"Is 7 included?",
 expl:"The integers are 1, 2, 3, 4, 5, 6. Since 7 is not included, there are 6."},
{sec:"L",type:"mc",q:"Which number is in the solution set of 'x < 2 or x > 5'?",mono:true,opts:["7","3","2","5"],a:0,
 expl:"A number needs to satisfy at least one part. 7 > 5 works. 3 is between, and 2 and 5 are not strictly less than 2 or greater than 5."},
{lvl:2,sec:"L",type:"in",q:"Solve 3 < 2x + 1 ≤ 11. What is the largest integer x that works?",ans:5,
 hint:"Subtract 1 from all three parts, then divide by 2.",
 expl:"Subtract 1: 2 < 2x ≤ 10. Divide by 2: 1 < x ≤ 5. The largest integer is 5."},
{lvl:2,sec:"L",type:"mc",q:"Solve −7 ≤ 3x − 1 < 8.",mono:true,
 opts:["−2 ≤ x < 3","−2 < x ≤ 3","−6 ≤ x < 9","−3 < x ≤ 2"],a:0,
 expl:"Add 1 to all parts: −6 ≤ 3x < 9. Divide by 3: −2 ≤ x < 3."},
{lvl:2,sec:"L",type:"in",q:"How many integers satisfy −5 < 2x < 9?",ans:7,hint:"Divide everything by 2, then list the integers.",
 expl:"−2.5 < x < 4.5, so x can be −2, −1, 0, 1, 2, 3, 4. That is 7 integers."},
{lvl:3,sec:"L",type:"in",q:"A temperature T in degrees satisfies 10 ≤ (T − 4)/2 < 20. How many whole-number values of T are possible?",ans:20,
 hint:"Multiply all parts by 2, then add 4.",
 expl:"Multiply by 2: 20 ≤ T − 4 < 40. Add 4: 24 ≤ T < 44. The whole numbers from 24 to 43 give 20 values."},
{lvl:3,sec:"L",type:"multi",q:"Select EVERY value of x that satisfies 'x ≤ −1 or 2x − 3 > 5'.",mono:true,
 opts:["−1","5","0","4"],aMulti:[0,1],
 expl:"2x − 3 > 5 means x > 4. So the solutions are x ≤ −1 or x > 4: −1 and 5 work, but 0 and 4 do not."},
{lvl:3,sec:"L",type:"mc",q:"Which compound inequality has NO solution at all?",mono:true,
 opts:["x < 1 and x > 4","x > 1 and x < 4","x < 1 or x > 4","x > 1 or x < 4"],a:0,
 expl:"No number is both less than 1 and greater than 4 at the same time. The 'or' versions and 1 < x < 4 all have solutions."}
],

"g6-literal": [
{sec:"L",type:"mc",q:"Solve A = lw for w.",mono:true,opts:["w = A/l","w = A − l","w = Al","w = l/A"],a:0,
 expl:"Divide both sides by l: w = A/l."},
{sec:"L",type:"mc",q:"Solve P = 2l + 2w for l.",mono:true,
 opts:["l = (P − 2w)/2","l = P − 2w","l = (P + 2w)/2","l = 2P − w"],a:0,
 expl:"Subtract 2w from both sides: 2l = P − 2w. Divide by 2: l = (P − 2w)/2."},
{sec:"L",type:"in",q:"Using d = rt, a car travels d = 150 km in t = 2.5 hours. Find the speed r in km per hour.",ans:60,
 hint:"Rearrange to r = d/t.",expl:"r = d/t = 150 ÷ 2.5 = 60 km per hour."},
{lvl:2,sec:"L",type:"mc",q:"Solve C = 5(F − 32)/9 for F.",mono:true,
 opts:["F = 9C/5 + 32","F = 5C/9 + 32","F = 9(C + 32)/5","F = (9C − 32)/5"],a:0,
 expl:"Multiply by 9: 9C = 5(F − 32). Divide by 5: 9C/5 = F − 32. Add 32: F = 9C/5 + 32."},
{lvl:2,sec:"L",type:"in",q:"The volume of a box is V = lwh. If V = 240, l = 8 and w = 5, find h.",ans:6,
 hint:"Rearrange to h = V/(lw).",expl:"lw = 40, so h = 240 ÷ 40 = 6."},
{lvl:2,sec:"L",type:"mc",q:"Solve 3x + 2y = 12 for y.",mono:true,
 opts:["y = (12 − 3x)/2","y = 12 − 3x/2","y = (12 + 3x)/2","y = 6 − 3x"],a:0,
 expl:"Subtract 3x: 2y = 12 − 3x. Divide by 2: y = (12 − 3x)/2, which is the same as 6 − 1.5x."},
{lvl:3,sec:"L",type:"mc",q:"Solve ax + b = cx for x.",mono:true,
 opts:["x = b/(c − a)","x = b/(a − c)","x = (c − a)/b","x = −b/(c + a)"],a:0,
 hint:"Get both x terms on the same side, then factor out x.",
 expl:"Subtract ax: b = cx − ax = x(c − a). Divide by (c − a): x = b/(c − a)."},
{lvl:3,sec:"L",type:"in",q:"The sum of the first n counting numbers is S = n(n + 1)/2. If S = 78, what is n?",ans:12,
 hint:"n(n + 1) must equal 156; look for two consecutive numbers with that product.",
 expl:"Multiply by 2: n(n + 1) = 156. Since 12 × 13 = 156, n = 12."},
{lvl:3,sec:"L",type:"in",q:"Money grows by A = P(1 + r)². If A = 121 and P = 100, find the rate r as a decimal.",ans:0.1,
 hint:"Divide by P first, then take a square root.",
 expl:"(1 + r)² = 121/100 = 1.21, so 1 + r = 1.1 and r = 0.1."}
],

"g6-slope": [
{sec:"L",type:"in",q:"What is the slope of the line through (1, 2) and (4, 11)?",ans:3,
 hint:"Slope = change in y ÷ change in x.",expl:"Slope = (11 − 2)/(4 − 1) = 9/3 = 3."},
{sec:"L",type:"mc",q:"What is the slope of the line y = −2x + 5?",mono:true,opts:["−2","5","2","−5"],a:0,
 expl:"In y = mx + b, the slope is m, the number multiplying x. Here m = −2."},
{sec:"L",type:"in",q:"What is the y-intercept of the line y = 3x − 7?",ans:-7,
 expl:"When x = 0, y = −7, so the line crosses the y-axis at −7."},
{lvl:2,sec:"L",type:"in",q:"Find the slope of the line through (−2, 5) and (4, 2). Give the answer as a decimal.",ans:-0.5,
 hint:"Be careful with the signs when subtracting.",
 expl:"Slope = (2 − 5)/(4 − (−2)) = −3/6 = −0.5."},
{lvl:2,sec:"L",type:"mc",q:"Which line is parallel to y = 4x + 1?",mono:true,
 opts:["y = 4x − 3","y = −4x + 1","y = x + 4","y = 0.25x + 1"],a:0,
 expl:"Parallel lines have the same slope. Only y = 4x − 3 also has slope 4."},
{lvl:2,sec:"L",type:"pair",q:"A line has slope 2 and passes through (1, 3). At which point does it cross the y-axis? Give the point (x, y).",
 ansP:[0,1],hint:"Use y = 2x + b and substitute the known point to find b.",
 expl:"3 = 2 × 1 + b gives b = 1, so the line is y = 2x + 1 and it crosses the y-axis at (0, 1)."},
{lvl:3,sec:"L",type:"in",q:"A line passes through (2, 3) and (6, 11). What is y on this line when x = 10?",ans:19,
 hint:"Find the slope, then keep stepping along the line.",
 expl:"Slope = 8/4 = 2. From (6, 11), moving 4 more in x adds 8 to y: 11 + 8 = 19. (The line is y = 2x − 1.)"},
{lvl:3,sec:"L",type:"mc",q:"Which slope describes a line that falls as x increases and is steeper than y = −x?",mono:true,
 opts:["−3","−0.5","3","0"],a:0,
 expl:"A falling line has a negative slope, and steeper means a bigger size than 1. Only −3 is negative with size greater than 1."},
{lvl:3,sec:"L",type:"in",q:"The line 3x + 4y = 24 crosses the x-axis and the y-axis. What is the area of the triangle it makes with the two axes, in square units?",
 ans:24,hint:"Find the two intercepts first.",
 expl:"At y = 0, x = 8; at x = 0, y = 6. The right triangle has legs 8 and 6, so its area is ½ × 8 × 6 = 24."}
],

"g6-systems": [
{sec:"L",type:"in",q:"If x + y = 10 and x − y = 4, what is x?",ans:7,hint:"Add the two equations.",
 expl:"Adding gives 2x = 14, so x = 7 (and y = 3)."},
{sec:"L",type:"in",q:"If y = 2x and x + y = 12, what is y?",ans:8,hint:"Substitute 2x for y.",
 expl:"x + 2x = 12, so 3x = 12 and x = 4. Then y = 2 × 4 = 8."},
{sec:"L",type:"mc",q:"Which pair (x, y) solves both x + 2y = 7 and 3x − y = 7?",mono:true,
 opts:["(3, 2)","(1, 3)","(2, 1)","(5, 1)"],a:0,
 expl:"3 + 2 × 2 = 7 and 3 × 3 − 2 = 7, so (3, 2) works. (1, 3) and (5, 1) fit the first equation only."},
{lvl:2,sec:"L",type:"in",q:"Solve 2x + 3y = 12 and 4x − 3y = 6. What is x?",ans:3,hint:"The y terms cancel when you add.",
 expl:"Adding the equations gives 6x = 18, so x = 3 (and y = 2)."},
{lvl:2,sec:"L",type:"in",q:"Three pens and two pencils cost $11. One pen and two pencils cost $5. What does one pen cost in dollars?",ans:3,
 hint:"Subtract one purchase from the other.",
 expl:"Subtracting the second purchase from the first removes the pencils: 2 pens cost $6, so a pen costs $3 (and a pencil $1)."},
{lvl:2,sec:"L",type:"mc",q:"How many solutions does the system y = 2x + 1 and y = 2x − 3 have?",
 opts:["None","One","Two","Infinitely many"],a:0,
 expl:"Both lines have slope 2 but different intercepts, so they are parallel and never meet. There are no solutions."},
{lvl:3,sec:"L",type:"in",q:"The sum of two numbers is 45. The larger is 3 more than twice the smaller. What is the larger number?",ans:31,
 hint:"Call the smaller number s and write the larger in terms of s.",
 expl:"s + (2s + 3) = 45, so 3s = 42 and s = 14. The larger number is 2 × 14 + 3 = 31."},
{lvl:3,sec:"L",type:"in",q:"Mateo has 20 coins, all nickels (5 cents) and dimes (10 cents), worth $1.55 in total. How many dimes does he have?",ans:11,
 hint:"Write one equation for the number of coins and one for their value in cents.",
 expl:"n + d = 20 and 5n + 10d = 155. Substituting n = 20 − d: 100 + 5d = 155, so d = 11. Check: 9 nickels and 11 dimes make 45 + 110 = 155 cents."},
{lvl:3,sec:"L",type:"mc",q:"For which value of k do 2x + 4y = 8 and x + 2y = k have infinitely many solutions?",mono:true,
 opts:["4","8","2","16"],a:0,
 hint:"Divide the first equation by 2 and compare.",
 expl:"Halving the first equation gives x + 2y = 4. The two equations describe the same line only when k = 4."}
],

"g6-pythag": [
{sec:"G",type:"in",q:"A right triangle has legs 6 and 8. What is the length of the hypotenuse?",ans:10,
 hint:"Square the legs, add, then take the square root.",expl:"6² + 8² = 36 + 64 = 100, and √100 = 10."},
{sec:"G",type:"in",q:"A right triangle has hypotenuse 13 and one leg 5. What is the other leg?",ans:12,
 hint:"Subtract the squares this time.",expl:"13² − 5² = 169 − 25 = 144, and √144 = 12."},
{sec:"G",type:"mc",q:"A triangle has sides 7, 24 and 25. Is it a right triangle?",
 opts:["Yes, 7² + 24² = 25²","No, 7 + 24 ≠ 25","No, 25 is too large","Yes, all sides are odd"],a:0,
 expl:"By the converse of the Pythagorean theorem: 49 + 576 = 625 = 25², so the triangle is right-angled."},
{lvl:2,sec:"G",type:"mc",q:"Which set of side lengths does NOT form a right triangle?",mono:true,
 opts:["5, 6, 7","3, 4, 5","8, 15, 17","9, 12, 15"],a:0,
 expl:"5² + 6² = 61, which is not 7² = 49. The other three sets satisfy a² + b² = c²."},
{lvl:2,sec:"G",type:"in",q:"A 10 m ladder leans against a wall with its foot 6 m from the wall. How high up the wall, in m, does it reach?",ans:8,
 hint:"The ladder is the hypotenuse.",expl:"10² − 6² = 100 − 36 = 64, so the height is √64 = 8 m."},
{lvl:2,sec:"G",type:"in",q:"A rectangle is 9 cm by 12 cm. What is the length of its diagonal in cm?",ans:15,
 expl:"The diagonal is the hypotenuse of a 9-12 right triangle: 81 + 144 = 225, and √225 = 15 cm."},
{lvl:3,sec:"G",type:"in",q:"A triangle has sides 10, 10 and 12. What is its area in square units?",ans:48,
 hint:"Draw the height to the side of length 12; it splits that side in half.",
 expl:"The height splits the base into 6 and 6. Height² = 10² − 6² = 64, so the height is 8 and the area is ½ × 12 × 8 = 48."},
{lvl:3,sec:"G",type:"mc",q:"A triangle has sides 4, 7 and 9. Is it acute, right or obtuse?",
 opts:["Obtuse","Right","Acute","Cannot tell"],a:0,
 hint:"Compare the square of the longest side with the sum of the other two squares.",
 expl:"4² + 7² = 16 + 49 = 65, which is less than 9² = 81. When the longest side squared is larger, the triangle is obtuse."},
{lvl:3,sec:"G",type:"in",q:"A box is 3 by 4 by 12 units. What is the length of the longest straight rod that fits inside it, corner to corner?",ans:13,
 hint:"Use the theorem twice: first across the base, then up to the far corner.",
 expl:"The base diagonal is √(3² + 4²) = 5. The space diagonal is √(5² + 12²) = √169 = 13."}
],

"g6-specialtri": [
{sec:"G",type:"mc",q:"In a 45-45-90 triangle with both legs equal to 1, what is the hypotenuse?",mono:true,
 opts:["√2","2","1","√3"],a:0,expl:"1² + 1² = 2, so the hypotenuse is √2."},
{sec:"G",type:"in",q:"In a 30-60-90 triangle the shortest side is 5. What is the hypotenuse?",ans:10,
 hint:"The hypotenuse is a fixed multiple of the short leg.",
 expl:"In a 30-60-90 triangle the hypotenuse is twice the short leg: 2 × 5 = 10."},
{sec:"G",type:"mc",q:"What is the ratio of the sides of a 30-60-90 triangle, from shortest to longest?",mono:true,
 opts:["1 : √3 : 2","1 : 1 : √2","1 : 2 : 3","1 : √2 : √3"],a:0,
 expl:"The short leg, long leg and hypotenuse are in the ratio 1 : √3 : 2. Check: 1 + 3 = 4 = 2²."},
{lvl:2,sec:"G",type:"in",q:"The hypotenuse of a 45-45-90 triangle is 8√2. How long is each leg?",ans:8,
 hint:"The hypotenuse is leg × √2.",expl:"Leg × √2 = 8√2, so each leg is 8."},
{lvl:2,sec:"G",type:"in",q:"A 30-60-90 triangle has hypotenuse 14. The longer leg is a√3. What is a?",ans:7,
 hint:"Find the short leg first.",expl:"The short leg is half the hypotenuse, 7, and the long leg is short leg × √3 = 7√3. So a = 7."},
{lvl:2,sec:"G",type:"mc",q:"What is the length of the diagonal of a square with side 6?",mono:true,
 opts:["6√2","12","6√3","3√2"],a:0,
 expl:"The diagonal splits the square into two 45-45-90 triangles with legs 6, so the diagonal is 6√2."},
{lvl:3,sec:"G",type:"in",q:"An equilateral triangle has side 10. Its height can be written as a√3. What is a?",ans:5,
 hint:"The height splits the triangle into two 30-60-90 triangles.",
 expl:"Each half is a 30-60-90 triangle with short leg 5, so the height (long leg) is 5√3. Thus a = 5."},
{lvl:3,sec:"G",type:"in",q:"An equilateral triangle has side 12. Its area can be written as b√3. What is b?",ans:36,
 hint:"Find the height using a 30-60-90 triangle, then use ½ × base × height.",
 expl:"The height is 6√3. Area = ½ × 12 × 6√3 = 36√3, so b = 36."},
{lvl:3,sec:"G",type:"mc",q:"The short leg of a 30-60-90 triangle is √3. What is the longer leg?",mono:true,
 opts:["3","√6","2√3","6"],a:0,
 expl:"Longer leg = short leg × √3 = √3 × √3 = 3."}
],

"g6-apothem": [
{sec:"G",type:"mc",q:"What is the apothem of a regular polygon?",
 opts:["Distance from the centre to the midpoint of a side","Distance from the centre to a vertex","The length of one side","Half of the perimeter"],a:0,
 expl:"The apothem is the perpendicular distance from the centre to a side. It is the height of each of the triangles the polygon splits into."},
{sec:"G",type:"in",q:"A regular hexagon has perimeter 36 cm and apothem 5.2 cm. Using area = ½ × apothem × perimeter, find its area in cm².",ans:93.6,
 expl:"Area = ½ × 5.2 × 36 = 93.6 cm²."},
{sec:"G",type:"in",q:"A regular pentagon has side 8 cm and apothem 5.5 cm. What is its area in cm²?",ans:110,
 hint:"Find the perimeter first.",expl:"Perimeter = 5 × 8 = 40 cm. Area = ½ × 5.5 × 40 = 110 cm²."},
{lvl:2,sec:"G",type:"in",q:"A regular hexagon has side 6. It splits into six equilateral triangles, and its apothem is a√3. What is a?",ans:3,
 hint:"The apothem is the height of an equilateral triangle with side 6.",
 expl:"The height of an equilateral triangle with side 6 is 3√3 (half of 6 is 3, times √3). So a = 3."},
{lvl:2,sec:"G",type:"in",q:"A square has apothem 4. What is its area?",ans:64,
 hint:"How does the apothem of a square relate to its side?",
 expl:"The apothem of a square is half its side, so the side is 8 and the area is 8 × 8 = 64."},
{lvl:2,sec:"G",type:"order",q:"Put these regular polygons in order of their interior angle, from smallest to largest.",
 items:["square","pentagon","triangle","hexagon"],ansOrder:["triangle","square","pentagon","hexagon"],
 hint:"More sides means each corner is flatter.",
 expl:"The interior angles are 60° (triangle), 90° (square), 108° (pentagon) and 120° (hexagon)."},
{lvl:2,sec:"G",type:"mc",q:"What is each interior angle of a regular octagon?",mono:true,opts:["135°","120°","140°","108°"],a:0,
 expl:"The angle sum is (8 − 2) × 180° = 1080°, and 1080° ÷ 8 = 135°."},
{lvl:3,sec:"G",type:"in",q:"A regular hexagon has apothem 5√3. Its area can be written as b√3. What is b?",ans:150,
 hint:"First find the side: the apothem of a regular hexagon is side × √3 ÷ 2.",
 expl:"Side × √3 ÷ 2 = 5√3 gives side 10 and perimeter 60. Area = ½ × 5√3 × 60 = 150√3, so b = 150."},
{lvl:3,sec:"G",type:"in",q:"A regular polygon has area 96 and apothem 4. What is its perimeter?",ans:48,
 hint:"Rearrange area = ½ × apothem × perimeter.",expl:"96 = ½ × 4 × P = 2P, so P = 48."},
{lvl:3,sec:"G",type:"in",q:"A regular octagon has area 80 and perimeter 32. What is its apothem?",ans:5,
 expl:"80 = ½ × a × 32 = 16a, so the apothem a = 5."}
],

"g6-solids": [
{sec:"G",type:"in",q:"A rectangular prism is 4 by 5 by 6 units. What is its volume in cubic units?",ans:120,
 expl:"Volume = 4 × 5 × 6 = 120 cubic units."},
{sec:"G",type:"in",q:"A cylinder has radius 3 and height 7. Its volume is aπ cubic units. What is a?",ans:63,
 hint:"Volume = π × r² × h.",expl:"π × 3² × 7 = 63π, so a = 63."},
{sec:"G",type:"mc",q:"A pyramid and a prism have the same base and the same height. The pyramid's volume is what fraction of the prism's?",
 opts:["One third","One half","The same","Twice"],a:0,
 expl:"A pyramid (or cone) has one third of the volume of the prism (or cylinder) with the same base and height."},
{lvl:2,sec:"G",type:"in",q:"A square pyramid has a 6 by 6 base and height 8. What is its volume in cubic units?",ans:96,
 hint:"Volume = ⅓ × base area × height.",expl:"Base area = 36. Volume = ⅓ × 36 × 8 = 96."},
{lvl:2,sec:"G",type:"in",q:"A cone has radius 4 and height 9. Its volume is aπ cubic units. What is a?",ans:48,
 hint:"Volume = ⅓ × π × r² × h.",expl:"⅓ × π × 16 × 9 = 48π, so a = 48."},
{lvl:2,sec:"G",type:"mc",q:"What is the surface area of a cube with edge 5?",mono:true,opts:["150","125","100","25"],a:0,
 expl:"Each of the 6 faces has area 25, so the surface area is 6 × 25 = 150. (125 is the volume.)"},
{lvl:3,sec:"G",type:"in",q:"A closed cylinder has radius 5 and height 10. Its total surface area is aπ. What is a?",ans:150,
 hint:"Add the two circular ends to the curved surface, which unrolls into a rectangle.",
 expl:"Ends: 2 × π × 5² = 50π. Curved surface: 2π × 5 × 10 = 100π. Total = 150π, so a = 150."},
{lvl:3,sec:"G",type:"in",q:"A cone has radius 3 and height 4. Its total surface area (curved part πrl plus base) is aπ. What is a?",ans:24,
 hint:"Find the slant height l with the Pythagorean theorem first.",
 expl:"Slant height l = √(3² + 4²) = 5. Curved surface = π × 3 × 5 = 15π, base = 9π, total 24π. So a = 24."},
{lvl:3,sec:"G",type:"multi",q:"Select EVERY solid whose volume is exactly 100 cubic units.",
 opts:["Prism with base area 20 and height 5","Pyramid with base area 30 and height 10","Cube with edge 5","Cone with base area 60 and height 5"],aMulti:[0,1,3],
 expl:"Prism: 20 × 5 = 100. Pyramid: ⅓ × 30 × 10 = 100. Cone: ⅓ × 60 × 5 = 100. The cube is 5³ = 125."}
],

"g6-transvers": [
{sec:"G",type:"mc",q:"Two parallel lines are cut by a transversal. Corresponding angles are always...",
 opts:["Equal","Supplementary","Complementary","Right angles"],a:0,
 expl:"Corresponding angles sit in the same position at each parallel line, so they are equal."},
{sec:"G",type:"in",q:"Two parallel lines are cut by a transversal. One angle is 65°. What is its alternate interior angle, in degrees?",ans:65,
 expl:"Alternate interior angles between parallel lines are equal, so it is also 65°."},
{sec:"G",type:"in",q:"Two parallel lines are cut by a transversal. One angle is 120°. What is the co-interior (same-side interior) angle, in degrees?",ans:60,
 hint:"Co-interior angles add to a straight angle.",expl:"Co-interior angles are supplementary: 180° − 120° = 60°."},
{lvl:2,sec:"G",type:"in",q:"Two parallel lines are cut by a transversal. A pair of alternate interior angles measure (3x + 10)° and (5x − 30)°. Find x.",ans:20,
 hint:"Alternate interior angles are equal.",expl:"3x + 10 = 5x − 30, so 40 = 2x and x = 20. Both angles are 70°."},
{lvl:2,sec:"G",type:"mc",q:"When two parallel lines are cut by a transversal, which pair of angles must be supplementary?",
 opts:["Co-interior angles","Corresponding angles","Alternate interior angles","Vertical angles"],a:0,
 expl:"Co-interior (same-side interior) angles add to 180°. The other pairs listed are equal."},
{lvl:2,sec:"G",type:"in",q:"Two parallel lines are cut by a transversal. Co-interior angles measure (2x)° and (x + 30)°. Find x.",ans:50,
 hint:"Their sum is 180°.",expl:"2x + x + 30 = 180, so 3x = 150 and x = 50. The angles are 100° and 80°."},
{lvl:3,sec:"G",type:"in",q:"Two parallel lines are cut by a transversal. Corresponding angles measure (7x − 20)° and (4x + 40)°. What is the size of each angle, in degrees?",ans:120,
 hint:"Solve for x first, then substitute back.",
 expl:"7x − 20 = 4x + 40 gives 3x = 60, so x = 20. Each angle is 7 × 20 − 20 = 120°."},
{lvl:3,sec:"G",type:"mc",q:"Lines m and n are cut by a transversal, and a pair of co-interior angles measure 72° and 108°. What can you conclude?",
 opts:["m and n are parallel","m and n are perpendicular","m and n meet at an angle of 36°","Nothing can be concluded"],a:0,
 expl:"72° + 108° = 180°. When co-interior angles are supplementary, the converse tells us the lines are parallel."},
{lvl:3,sec:"G",type:"in",q:"Line AB is parallel to line CD. Point P lies between the lines. Angle BAP is 30° and angle DCP is 40°. What is angle APC, in degrees?",ans:70,
 hint:"Draw a line through P parallel to AB and use alternate angles twice.",
 expl:"A line through P parallel to both lines splits angle APC into two alternate angles of 30° and 40°. So angle APC = 30° + 40° = 70°."}
],

"g6-transform": [
{sec:"G",type:"pair",q:"The point (3, −2) is reflected in the x-axis. Give the image point (x, y).",ansP:[3,2],
 hint:"Reflecting in the x-axis flips the sign of one coordinate.",
 expl:"A reflection in the x-axis keeps x and changes the sign of y: (3, −2) becomes (3, 2)."},
{sec:"G",type:"pair",q:"The point (2, 5) is translated 3 units left and 4 units up. Give the image point (x, y).",ansP:[-1,9],
 expl:"Left 3 subtracts 3 from x, up 4 adds 4 to y: (2 − 3, 5 + 4) = (−1, 9)."},
{sec:"G",type:"mc",q:"Which transformation changes the size of a shape?",opts:["Dilation","Rotation","Reflection","Translation"],a:0,
 expl:"A dilation enlarges or shrinks a shape by a scale factor. The other three are rigid motions that keep size and shape."},
{lvl:2,sec:"G",type:"pair",q:"The point (−2, 4) is dilated from the origin with scale factor 3. Give the image point (x, y).",ansP:[-6,12],
 hint:"Multiply both coordinates by the scale factor.",expl:"(−2 × 3, 4 × 3) = (−6, 12)."},
{lvl:2,sec:"G",type:"pair",q:"The point (4, 1) is rotated 90° anticlockwise about the origin. Give the image point (x, y).",ansP:[-1,4],
 hint:"A 90° anticlockwise turn sends (x, y) to (−y, x).",expl:"Using (x, y) → (−y, x): (4, 1) becomes (−1, 4)."},
{lvl:2,sec:"G",type:"in",q:"A triangle has area 5 square units. It is dilated with scale factor 3. What is the area of the image, in square units?",ans:45,
 hint:"Lengths scale by 3; what happens to area?",
 expl:"Area scales by the square of the factor: 5 × 3² = 45 square units."},
{lvl:3,sec:"G",type:"pair",q:"The point (1, 6) is reflected in the line y = x and then translated 2 units right. Give the final point (x, y).",ansP:[8,1],
 hint:"Reflecting in y = x swaps the coordinates.",
 expl:"Reflecting in y = x gives (6, 1). Translating 2 right gives (8, 1)."},
{lvl:3,sec:"G",type:"in",q:"A square with side 4 is dilated with scale factor 0.5. What is the perimeter of the image?",ans:8,
 expl:"Each side becomes 4 × 0.5 = 2, so the perimeter is 4 × 2 = 8."},
{lvl:3,sec:"G",type:"mc",q:"Which single transformation maps (2, 3) to (−3, 2)?",
 opts:["A 90° anticlockwise rotation about the origin","A reflection in the x-axis","A 180° rotation about the origin","A reflection in the y-axis"],a:0,
 hint:"Try each rule on (2, 3) and see which lands on (−3, 2).",
 expl:"A 90° anticlockwise rotation sends (x, y) to (−y, x), so (2, 3) goes to (−3, 2). The others give (2, −3), (−2, −3) and (−2, 3)."}
],

"g6-permcomb": [
{sec:"K",type:"in",q:"In how many different orders can 4 different books be placed on a shelf?",ans:24,
 hint:"Multiply the choices for each position.",expl:"4 × 3 × 2 × 1 = 4! = 24."},
{sec:"K",type:"in",q:"How many ways are there to choose 2 toppings from 5 for a pizza?",ans:10,
 hint:"Order does not matter here.",expl:"C(5, 2) = (5 × 4)/(2 × 1) = 10."},
{sec:"K",type:"mc",q:"Which of these is a combination problem, where order does not matter?",
 opts:["Choosing 3 students for a committee","Awarding gold, silver and bronze medals","Making a 4-digit PIN code","Arranging the letters of a word"],a:0,
 expl:"A committee is the same group no matter the order chosen, so it is a combination. Medals, PINs and letter orders all depend on order."},
{lvl:2,sec:"K",type:"in",q:"Six runners compete. In how many ways can first, second and third place be awarded?",ans:120,
 hint:"This is a permutation of 3 from 6.",expl:"P(6, 3) = 6 × 5 × 4 = 120."},
{lvl:2,sec:"K",type:"in",q:"Nadia picks 3 flavours from 8 for a sundae. How many different sets of flavours can she choose?",ans:56,
 expl:"C(8, 3) = (8 × 7 × 6)/(3 × 2 × 1) = 336/6 = 56."},
{lvl:2,sec:"K",type:"mc",q:"Which expression equals C(10, 3)?",mono:true,
 opts:["C(10, 7)","C(10, 3) × 3","P(10, 3)","C(3, 10)"],a:0,
 expl:"Choosing 3 to include is the same as choosing 7 to leave out, so C(10, 3) = C(10, 7) = 120."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY expression that equals 20.",mono:true,
 opts:["C(6, 3)","P(5, 2)","C(5, 2)","4!"],aMulti:[0,1],
 expl:"C(6, 3) = 120/6 = 20 and P(5, 2) = 5 × 4 = 20. C(5, 2) = 10 and 4! = 24."},
{lvl:3,sec:"K",type:"in",q:"A committee needs 2 of 5 teachers and 3 of 6 students. How many different committees are possible?",ans:200,
 hint:"Count the teacher choices and the student choices, then multiply.",
 expl:"C(5, 2) = 10 and C(6, 3) = 20, so there are 10 × 20 = 200 committees."},
{lvl:3,sec:"K",type:"in",q:"How many different arrangements of the letters of LEVEL are there?",ans:30,
 hint:"Some letters repeat, so divide out the repeats.",
 expl:"5 letters give 5! = 120 orders, but L appears twice and E appears twice: 120/(2! × 2!) = 30."},
{lvl:3,sec:"K",type:"in",q:"Five friends sit in a row. Amara and Wei insist on sitting next to each other. How many seating orders are possible?",ans:48,
 hint:"Treat the pair as one block, then remember the block can be in two orders.",
 expl:"Gluing the pair together leaves 4 blocks to arrange: 4! = 24. The pair can swap places, so 24 × 2 = 48."}
],

"g6-binomial": [
{sec:"K",type:"in",q:"What is the coefficient of x² in the expansion of (x + 1)^4?",ans:6,
 hint:"Look at row 4 of Pascal's triangle.",expl:"(x + 1)^4 = x^4 + 4x³ + 6x² + 4x + 1, so the coefficient is C(4, 2) = 6."},
{sec:"K",type:"mc",q:"Which is row 5 of Pascal's triangle (the coefficients of (a + b)^5)?",mono:true,
 opts:["1 5 10 10 5 1","1 4 6 4 1","1 5 10 5 1","1 6 15 20 15 6 1"],a:0,
 expl:"Each entry is the sum of the two above it: from 1 4 6 4 1 we get 1 5 10 10 5 1."},
{sec:"K",type:"in",q:"What is the sum of all the coefficients in the expansion of (x + 1)^6?",ans:64,
 hint:"Substitute x = 1.",expl:"Putting x = 1 gives (1 + 1)^6 = 2^6 = 64."},
{lvl:2,sec:"K",type:"in",q:"What is the coefficient of x³ in the expansion of (x + 2)^5?",ans:40,
 hint:"The term is C(5, 3) × x³ × 2².",expl:"C(5, 3) × 2² = 10 × 4 = 40."},
{lvl:2,sec:"K",type:"mc",q:"What is the expansion of (a + b)³?",mono:true,
 opts:["a³ + 3a²b + 3ab² + b³","a³ + b³","a³ + 2a²b + 2ab² + b³","a³ + 3ab + b³"],a:0,
 expl:"Row 3 of Pascal's triangle is 1 3 3 1, giving a³ + 3a²b + 3ab² + b³."},
{lvl:2,sec:"K",type:"in",q:"What is the coefficient of x² in the expansion of (2x + 1)^4?",ans:24,
 hint:"Remember the 2 gets squared as well.",expl:"C(4, 2) × (2x)² = 6 × 4x² = 24x², so the coefficient is 24."},
{lvl:3,sec:"K",type:"in",q:"What is the coefficient of x²y³ in the expansion of (x + y)^5?",ans:10,
 expl:"The coefficient is C(5, 2) = C(5, 3) = 10."},
{lvl:3,sec:"K",type:"in",q:"What is the coefficient of x^4 in the expansion of (x − 1)^7?",ans:-35,
 hint:"Watch the sign: the other factor is (−1) raised to a power.",
 expl:"The term is C(7, 4) × x^4 × (−1)³ = 35 × (−1) × x^4, so the coefficient is −35."},
{lvl:3,sec:"K",type:"mc",q:"What is the middle term of the expansion of (x + y)^6?",mono:true,
 opts:["20x³y³","15x³y³","20x²y⁴","6x³y³"],a:0,
 expl:"Row 6 of Pascal's triangle is 1 6 15 20 15 6 1. The middle entry, 20, goes with x³y³."}
],

"g6-symmetry": [
{sec:"K",type:"in",q:"In how many different ways can 3 people sit around a round table, if arrangements that are rotations of each other count as the same?",ans:2,
 hint:"Fix one person's seat and arrange the rest.",
 expl:"Fix one person; the other two can sit in 2! = 2 orders. So there are 2 arrangements."},
{sec:"K",type:"mc",q:"Why are there fewer ways to seat people around a circle than in a row?",
 opts:["Rotations of the same arrangement count once","People can sit closer together","There are fewer seats in a circle","Circles have no corners"],a:0,
 expl:"Turning the whole table does not change who sits next to whom, so each circular arrangement matches several row arrangements."},
{sec:"K",type:"in",q:"How many ways can 5 people sit around a round table, counting rotations as the same?",ans:24,
 expl:"Fix one person to remove rotations, then arrange the other 4: 4! = 24."},
{lvl:2,sec:"K",type:"in",q:"A bracelet has 4 different beads. Rotating or flipping the bracelet gives the same bracelet. How many different bracelets are possible?",ans:3,
 hint:"Start with circular arrangements, then halve for flips.",
 expl:"Circular arrangements: 3! = 6. Each bracelet can be flipped over, pairing them up: 6 ÷ 2 = 3."},
{lvl:2,sec:"K",type:"in",q:"Each corner of a square is painted black or white. Colourings that are rotations of each other count as the same. How many different colourings are there?",ans:6,
 hint:"Count by how many corners are black.",
 expl:"0 black: 1 way. 1 black: 1. 2 black: 2 (adjacent or opposite). 3 black: 1. 4 black: 1. Total 6."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY shape that has exactly 4 rotational symmetries (counting the full turn).",
 opts:["Square","A four-armed pinwheel","Rectangle","Regular hexagon"],aMulti:[0,1],
 expl:"A square and a four-armed pinwheel look the same after turns of 90°, 180°, 270° and 360°. A rectangle has 2 and a regular hexagon has 6."},
{lvl:3,sec:"K",type:"in",q:"Six people sit around a round table. Kenji and Hana must sit next to each other. How many arrangements are there, counting rotations as the same?",ans:48,
 hint:"Glue the pair into one block, seat the blocks in a circle, then let the pair swap.",
 expl:"With the pair as one block there are 5 blocks: (5 − 1)! = 24 circular orders. The pair can swap, so 24 × 2 = 48."},
{lvl:3,sec:"K",type:"in",q:"Eight people sit around a round table. Two of them refuse to sit next to each other. How many arrangements are there, counting rotations as the same?",ans:3600,
 hint:"Count all arrangements, then subtract those where the two sit together.",
 expl:"All arrangements: 7! = 5040. Together: (7 − 1)! × 2 = 1440. Apart: 5040 − 1440 = 3600."},
{lvl:3,sec:"K",type:"mc",q:"Each corner of an equilateral triangle is painted red or blue. Rotations and flips count as the same. How many different colourings are there?",
 mono:true,opts:["4","8","6","2"],a:0,
 expl:"Only the number of red corners matters: 0, 1, 2 or 3 red. Any two colourings with the same count can be turned or flipped onto each other. That is 4."}
],

"g6-recursion": [
{sec:"K",type:"in",q:"The Fibonacci sequence starts 1, 1, 2, 3, 5, 8, ... where each term is the sum of the two before. What is the 10th term?",ans:55,
 expl:"Continuing: 13, 21, 34, 55. The 10th term is 55."},
{sec:"K",type:"in",q:"A sequence has a(1) = 3 and each next term is 2 × (previous term) − 1. What is a(4)?",ans:17,
 hint:"Work out a(2) and a(3) first.",expl:"a(2) = 5, a(3) = 9, a(4) = 2 × 9 − 1 = 17."},
{sec:"K",type:"mc",q:"Which recursive rule produces 2, 6, 18, 54, ...?",mono:true,
 opts:["a(n+1) = 3 × a(n)","a(n+1) = a(n) + 4","a(n+1) = 2 × a(n)","a(n+1) = a(n) + 3"],a:0,
 expl:"Each term is 3 times the one before: 2, 6, 18, 54."},
{lvl:2,sec:"K",type:"in",q:"Sofia climbs a staircase of 6 steps, taking 1 or 2 steps at a time. How many different ways can she climb it?",ans:13,
 hint:"Ways(n) = Ways(n − 1) + Ways(n − 2), depending on the last step size.",
 expl:"Ways for 1, 2, 3, 4, 5, 6 steps are 1, 2, 3, 5, 8, 13. So there are 13 ways."},
{lvl:2,sec:"K",type:"in",q:"What is the sum of the first 8 Fibonacci numbers: 1 + 1 + 2 + 3 + 5 + 8 + 13 + 21?",ans:54,
 hint:"The sum of the first n Fibonacci numbers is one less than a Fibonacci number.",
 expl:"1 + 1 + 2 + 3 + 5 + 8 + 13 + 21 = 54, which is F(10) − 1 = 55 − 1."},
{lvl:2,sec:"K",type:"mc",q:"For Fibonacci numbers, F(n + 2) − F(n) always equals which of these?",mono:true,
 opts:["F(n + 1)","F(n − 1)","2F(n)","F(n + 3)"],a:0,
 expl:"Since F(n + 2) = F(n + 1) + F(n), subtracting F(n) leaves F(n + 1)."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY number that is a Fibonacci number.",mono:true,opts:["21","34","27","15"],aMulti:[0,1],
 expl:"The sequence runs 1, 1, 2, 3, 5, 8, 13, 21, 34, 55. So 21 and 34 are in it; 27 and 15 are not."},
{lvl:3,sec:"K",type:"in",q:"In the Tower of Hanoi puzzle, the fewest moves for n discs is T(n) = 2 × T(n − 1) + 1 with T(1) = 1. What is T(6)?",ans:63,
 hint:"Build up from T(1) one step at a time.",
 expl:"T(1) = 1, T(2) = 3, T(3) = 7, T(4) = 15, T(5) = 31, T(6) = 63. (In general T(n) = 2^n − 1.)"},
{lvl:3,sec:"K",type:"in",q:"How many ways are there to tile a 2 by 8 board with 1 by 2 dominoes?",ans:34,
 hint:"The rightmost column is either one vertical domino or two horizontal ones.",
 expl:"Ways for widths 1 to 8 follow the Fibonacci pattern 1, 2, 3, 5, 8, 13, 21, 34. So 34 tilings."},
{lvl:3,sec:"K",type:"in",q:"A sequence follows a(n) = a(n − 1) + a(n − 2) but starts a(1) = 1, a(2) = 3. What is a(8)?",ans:47,
 expl:"1, 3, 4, 7, 11, 18, 29, 47. So a(8) = 47. (These are the Lucas numbers.)"}
],

"g6-catalan": [
{sec:"K",type:"in",q:"How many different valid ways are there to arrange 2 pairs of brackets? For example ()() is valid but )(() is not.",ans:2,
 expl:"The valid arrangements are ()() and (()). That is 2, the second Catalan number."},
{sec:"K",type:"mc",q:"Which sequence is the start of the Catalan numbers?",mono:true,
 opts:["1, 1, 2, 5, 14, 42","1, 1, 2, 3, 5, 8","1, 2, 4, 8, 16, 32","1, 3, 6, 10, 15, 21"],a:0,
 expl:"The Catalan numbers are 1, 1, 2, 5, 14, 42, 132, ... The others are Fibonacci, powers of 2 and triangular numbers."},
{sec:"K",type:"in",q:"How many valid arrangements are there of 3 pairs of brackets?",ans:5,
 hint:"List them systematically, starting with ((())).",
 expl:"((())), (()()), (())(), ()(()), ()()(). That is 5."},
{sec:"K",type:"multi",q:"Select EVERY number that is a Catalan number.",mono:true,opts:["14","42","21","10"],aMulti:[0,1],
 expl:"The Catalan numbers are 1, 1, 2, 5, 14, 42, 132, ... so 14 and 42 are Catalan; 21 and 10 are not."},
{lvl:2,sec:"K",type:"in",q:"The nth Catalan number is C(2n, n)/(n + 1). Use this formula to find the Catalan number for n = 4.",ans:14,
 hint:"C(8, 4) = 70.",expl:"C(8, 4)/(4 + 1) = 70/5 = 14."},
{lvl:2,sec:"K",type:"mc",q:"In how many ways can a convex pentagon be cut into triangles using diagonals that do not cross?",mono:true,
 opts:["5","6","10","4"],a:0,
 expl:"From each of the 5 vertices you can draw both diagonals, giving 5 triangulations. This is the Catalan number for n = 3."},
{lvl:2,sec:"K",type:"mc",q:"Catalan numbers satisfy C(4) = C(0)C(3) + C(1)C(2) + C(2)C(1) + C(3)C(0). Which sum is this?",mono:true,
 opts:["1×5 + 1×2 + 2×1 + 5×1","1×5 + 1×2 + 2×1","5 + 2 + 1","1 + 2 + 5 + 14"],a:0,
 expl:"With C(0) = 1, C(1) = 1, C(2) = 2, C(3) = 5 the sum is 5 + 2 + 2 + 5 = 14, which is C(4)."},
{lvl:3,sec:"K",type:"in",q:"How many paths go from (0, 0) to (5, 5) using only right and up steps, never rising above the diagonal line y = x?",ans:42,
 hint:"These paths are counted by a Catalan number.",
 expl:"Paths staying on or below the diagonal from (0, 0) to (n, n) are counted by the nth Catalan number. For n = 5 that is 42."},
{lvl:3,sec:"K",type:"in",q:"How many valid arrangements are there of 6 pairs of brackets?",ans:132,
 hint:"Continue the Catalan sequence, or use C(12, 6)/7.",
 expl:"The 6th Catalan number is C(12, 6)/7 = 924/7 = 132."},
{lvl:3,sec:"K",type:"mc",q:"Which of these is NOT counted by the Catalan numbers?",
 opts:["Ways to choose 2 items from n","Valid bracket sequences","Triangulations of a convex polygon","Non-crossing handshakes around a circle"],a:0,
 expl:"Choosing 2 from n gives the triangular numbers 1, 3, 6, 10. The other three are classic Catalan counts."}
],

"g6-replace": [
{sec:"S",type:"mc",q:"A bag has 3 red and 2 blue marbles. Two are drawn WITHOUT replacement. If the first is red, what is the probability the second is also red?",
 mono:true,opts:["1/2","3/5","3/4","2/5"],a:0,
 expl:"After removing one red, 2 red and 2 blue remain, so the probability is 2/4 = 1/2."},
{sec:"S",type:"mc",q:"Ravi draws a card, puts it back and shuffles, then draws again. This is called drawing...",
 opts:["With replacement","Without replacement","Dependently","In order"],a:0,
 expl:"Putting the card back means the second draw is from the full deck again: that is drawing with replacement."},
{sec:"S",type:"multi",q:"Select EVERY situation that is WITHOUT replacement.",
 opts:["Dealing two cards from a deck","Picking two students for a team","Rolling a die twice","Spinning a spinner twice"],aMulti:[0,1],
 expl:"A dealt card and a chosen student are not put back, so the second pick has fewer options. Dice and spinners reset every time."},
{sec:"S",type:"in",q:"A bag has 4 red and 6 blue marbles. One is drawn, replaced, then another is drawn. What is the probability both are red, as a decimal?",ans:0.16,
 hint:"With replacement the two draws are independent.",expl:"0.4 × 0.4 = 0.16."},
{lvl:2,sec:"S",type:"in",q:"A bag has 2 red and 3 blue marbles. Two are drawn without replacement. What is the probability both are red, as a decimal?",ans:0.1,
 hint:"The second probability uses 4 marbles, not 5.",expl:"2/5 × 1/4 = 2/20 = 0.1."},
{lvl:2,sec:"S",type:"mc",q:"A bag has 3 red and 3 blue marbles. Two are drawn without replacement. What is the probability of one red and one blue?",
 mono:true,opts:["3/5","1/2","1/4","2/5"],a:0,
 hint:"Red then blue and blue then red both count.",
 expl:"Red then blue: 3/6 × 3/5 = 9/30. Blue then red is also 9/30. Total 18/30 = 3/5."},
{lvl:2,sec:"S",type:"in",q:"A drawer has 3 black socks and 1 white sock. Two are pulled out without replacement. What is the probability both are black, as a decimal?",ans:0.5,
 expl:"3/4 × 2/3 = 6/12 = 0.5."},
{lvl:3,sec:"S",type:"in",q:"A bag has 2 red and 3 blue marbles. Two are drawn without replacement. What is the probability at least one is blue, as a decimal?",ans:0.9,
 hint:"Find the probability of the opposite event first.",
 expl:"The only way to get no blue is red, red: 2/5 × 1/4 = 0.1. So P(at least one blue) = 1 − 0.1 = 0.9."},
{lvl:3,sec:"S",type:"mc",q:"A box holds 4 working bulbs and 1 faulty one. Aisha tests two bulbs without replacement. What is the probability she finds the faulty bulb?",
 mono:true,opts:["2/5","1/5","1/4","3/5"],a:0,
 hint:"When would she NOT find it?",
 expl:"P(both working) = 4/5 × 3/4 = 3/5, so P(faulty found) = 1 − 3/5 = 2/5."},
{lvl:3,sec:"S",type:"in",q:"Five raffle tickets include 2 winners. Two tickets are drawn without replacement. What is the probability exactly one is a winner, as a decimal?",ans:0.6,
 hint:"Winner then loser, or loser then winner.",
 expl:"2/5 × 3/4 + 3/5 × 2/4 = 6/20 + 6/20 = 12/20 = 0.6."}
],

"g6-bayes": [
{sec:"S",type:"mc",q:"What does P(A | B) mean?",
 opts:["The probability of A given that B happened","The probability of A and B both happening","The probability of A or B","The probability of B given A"],a:0,
 expl:"The vertical bar means 'given'. P(A | B) is the probability of A once we know B has happened."},
{sec:"S",type:"in",q:"In a class of 30, 20 students play football and 8 of those also play chess. A football player is picked at random. What is the probability they play chess, as a decimal?",ans:0.4,
 hint:"Only the 20 football players are in the running.",expl:"8 out of the 20 football players play chess: 8/20 = 0.4."},
{sec:"S",type:"in",q:"A fair die is rolled and you are told the result is greater than 2. What is the probability it is a 4, as a decimal?",ans:0.25,
 hint:"How many results are greater than 2?",expl:"The possible results are 3, 4, 5, 6. One of these four is a 4: 1/4 = 0.25."},
{lvl:2,sec:"S",type:"in",q:"Of 50 students, 30 like pizza, and 21 of those also like tacos. Given a student likes pizza, what is the probability they also like tacos, as a decimal?",ans:0.7,
 expl:"P(tacos | pizza) = 21/30 = 0.7."},
{lvl:2,sec:"S",type:"mc",q:"Which formula gives the conditional probability P(A | B)?",mono:true,
 opts:["P(A and B) / P(B)","P(A and B) / P(A)","P(A) × P(B)","P(A) + P(B)"],a:0,
 expl:"Restrict to the cases where B happens and ask how often A happens too: P(A | B) = P(A and B) / P(B)."},
{lvl:2,sec:"S",type:"in",q:"P(rain) = 0.3. If it rains, Elias is late with probability 0.5; if not, with probability 0.1. What is the probability he is late, as a decimal?",ans:0.22,
 hint:"Add the two ways of being late: rain and late, no rain and late.",
 expl:"0.3 × 0.5 + 0.7 × 0.1 = 0.15 + 0.07 = 0.22."},
{lvl:2,sec:"S",type:"multi",q:"A fair die is rolled. Select EVERY pair of events that is independent.",
 opts:["'even' and 'less than 5'","'even' and 'multiple of 3'","'even' and 'odd'","'more than 4' and 'less than 3'"],aMulti:[0,1],
 hint:"Independent means P(A and B) = P(A) × P(B).",
 expl:"P(even and less than 5) = 2/6 = 1/2 × 2/3 and P(even and multiple of 3) = 1/6 = 1/2 × 1/3, so those pairs are independent. The last two pairs cannot happen together, so they are not."},
{lvl:3,sec:"S",type:"in",q:"P(rain) = 0.2. Leila is late with probability 0.6 if it rains and 0.1 if not. Today she is late. What is the probability it rained, as a decimal?",ans:0.6,
 hint:"Compare the 'rain and late' probability with the total 'late' probability.",
 expl:"P(rain and late) = 0.2 × 0.6 = 0.12. P(late) = 0.12 + 0.8 × 0.1 = 0.20. So P(rain | late) = 0.12/0.20 = 0.6."},
{lvl:3,sec:"S",type:"in",q:"Box A holds 3 gold and 1 silver coin; box B holds 1 gold and 3 silver. A box is chosen at random and a coin drawn from it is gold. What is the probability the box was A, as a decimal?",ans:0.75,
 hint:"Work out P(A and gold) and P(B and gold).",
 expl:"P(A and gold) = 0.5 × 0.75 = 0.375 and P(B and gold) = 0.5 × 0.25 = 0.125. So P(A | gold) = 0.375/0.5 = 0.75."},
{lvl:3,sec:"S",type:"mc",q:"1% of people have a condition. A test detects it in 90% of those who have it, but also gives a false positive to 10% of those who do not. Out of 1000 people, what is the probability that a person who tests positive really has the condition?",
 mono:true,opts:["1/12","9/10","1/100","9/100"],a:0,
 hint:"Count how many of the 1000 test positive from each group.",
 expl:"10 people have it and 9 test positive; 990 do not and 99 test positive. Positives: 108, of whom 9 have it: 9/108 = 1/12."}
],

"g6-randvar": [
{sec:"S",type:"in",q:"A fair six-sided die is rolled. What is the expected value of the number shown? Give a decimal.",ans:3.5,
 hint:"Average the six equally likely outcomes.",expl:"(1 + 2 + 3 + 4 + 5 + 6)/6 = 21/6 = 3.5."},
{sec:"S",type:"in",q:"In a game you win $5 with probability 0.2 and nothing otherwise. What are your expected winnings in dollars?",ans:1,
 expl:"0.2 × 5 + 0.8 × 0 = 1 dollar."},
{sec:"S",type:"mc",q:"What is a random variable?",
 opts:["A number whose value depends on chance","A variable in an equation","A number that never changes","A letter used for unknowns"],a:0,
 expl:"A random variable assigns a number to each outcome of a chance experiment, such as the total when two dice are rolled."},
{lvl:2,sec:"S",type:"in",q:"Let X be the number of heads in 3 flips of a fair coin. What is the expected value of X? Give a decimal.",ans:1.5,
 hint:"Each flip contributes half a head on average.",expl:"Each flip has expected value 0.5 heads, so 3 flips give 3 × 0.5 = 1.5."},
{lvl:2,sec:"S",type:"in",q:"A spinner lands on 1 with probability 0.5, on 2 with probability 0.3 and on 5 with probability 0.2. What is the expected value? Give a decimal.",ans:2.1,
 expl:"1 × 0.5 + 2 × 0.3 + 5 × 0.2 = 0.5 + 0.6 + 1.0 = 2.1."},
{lvl:2,sec:"S",type:"multi",q:"X takes the values 1, 2, 3. Select EVERY list that is a valid set of probabilities for X.",mono:true,
 opts:["0.2, 0.3, 0.5","0.5, 0.25, 0.25","0.4, 0.4, 0.4","0.6, 0.5, −0.1"],aMulti:[0,1],
 expl:"Probabilities must each be between 0 and 1 and add to 1. The first two lists add to 1; the third adds to 1.2 and the fourth has a negative value."},
{lvl:2,sec:"S",type:"mc",q:"A raffle sells 100 tickets at $2 each and gives one prize of $150. What is the expected profit for someone buying one ticket?",mono:true,
 opts:["−$0.50","$0.50","−$2","$1.50"],a:0,
 expl:"Expected prize = 150/100 = $1.50. Subtracting the $2 cost gives −$0.50."},
{lvl:3,sec:"S",type:"in",q:"Two fair dice are rolled and X is their total. What is the expected value of X?",ans:7,
 hint:"Expected values add.",expl:"Each die has expected value 3.5, so the total has expected value 3.5 + 3.5 = 7."},
{lvl:3,sec:"S",type:"in",q:"Yusuf rolls a fair die. If it shows an even number he wins that many dollars; if odd he loses $3. What is his expected result in dollars? Give a decimal.",ans:0.5,
 hint:"Handle the three even results and the three odd results separately.",
 expl:"Even: (2 + 4 + 6)/6 = 2. Odd: −3 × 3/6 = −1.5. Expected result = 2 − 1.5 = 0.5 dollars."},
{lvl:3,sec:"S",type:"mc",q:"A game pays $12 if a fair die shows a 6 and nothing otherwise. What entry fee makes the game fair (expected profit zero)?",mono:true,
 opts:["$2","$1","$6","$12"],a:0,
 expl:"Expected payout = 12 × 1/6 = $2, so a $2 fee makes the expected profit zero."}
],

"g6-distrib": [
{sec:"S",type:"in",q:"A fair coin is flipped 3 times. What is the probability of exactly 2 heads? Give a decimal.",ans:0.375,
 hint:"Count the outcomes with exactly two heads out of 8.",
 expl:"HHT, HTH, THH are 3 of the 8 equally likely outcomes: 3/8 = 0.375."},
{sec:"S",type:"mc",q:"Which of these is a binomial situation (a fixed number of identical trials, counting successes)?",
 opts:["Counting heads in 10 coin flips","Rolling a die once","Flipping until the first head","Measuring a person's height"],a:0,
 expl:"Ten flips are a fixed number of independent trials with the same success chance; counting heads is binomial."},
{sec:"S",type:"in",q:"A fair coin is flipped until the first head appears. What is the probability the first head is on the 3rd flip? Give a decimal.",ans:0.125,
 hint:"You need tail, tail, head in that order.",expl:"1/2 × 1/2 × 1/2 = 1/8 = 0.125."},
{lvl:2,sec:"S",type:"in",q:"A fair coin is flipped 4 times. What is the probability of exactly 1 head? Give a decimal.",ans:0.25,
 hint:"How many of the 16 outcomes have one head?",expl:"C(4, 1) = 4 outcomes out of 16: 4/16 = 0.25."},
{lvl:2,sec:"S",type:"in",q:"A fair coin is flipped until a head appears. On average, how many flips does that take?",ans:2,
 hint:"For a geometric setting the mean is 1 divided by the success probability.",
 expl:"The expected number of trials until the first success is 1/p = 1/(1/2) = 2 flips."},
{lvl:2,sec:"S",type:"mc",q:"A fair die is rolled 30 times. What is the expected number of sixes?",mono:true,opts:["5","6","30","1/6"],a:0,
 expl:"For a binomial count the expected value is n × p = 30 × 1/6 = 5."},
{lvl:2,sec:"S",type:"multi",q:"A fair coin is flipped 5 times and X is the number of heads. Select EVERY true statement.",
 mono:true,opts:["The expected value of X is 2.5","P(X = 0) = 1/32","P(X = 5) = 5/32","X could equal 6"],aMulti:[0,1],
 expl:"E[X] = 5 × 1/2 = 2.5 and P(no heads) = (1/2)^5 = 1/32. P(5 heads) is also 1/32, not 5/32, and X can be at most 5."},
{lvl:3,sec:"S",type:"in",q:"A spinner gives a win with probability 0.2 on each spin. What is the probability the first win comes on the 3rd spin? Give a decimal.",ans:0.128,
 hint:"Lose, lose, then win.",expl:"0.8 × 0.8 × 0.2 = 0.128."},
{lvl:3,sec:"S",type:"in",q:"A biased coin lands heads with probability 0.3. It is flipped 3 times. What is the probability of exactly 2 heads? Give a decimal.",ans:0.189,
 hint:"There are 3 orders for two heads and one tail.",expl:"C(3, 2) × 0.3² × 0.7 = 3 × 0.09 × 0.7 = 0.189."},
{lvl:3,sec:"S",type:"mc",q:"A fair die is rolled 4 times. Which expression gives the probability of at least one six?",mono:true,
 opts:["1 − (5/6)⁴","4 × (1/6)","(1/6)⁴","1 − (1/6)⁴"],a:0,
 hint:"Think about the opposite: no sixes at all.",
 expl:"P(no six in 4 rolls) = (5/6)⁴, so P(at least one six) = 1 − (5/6)⁴ ≈ 0.518."}
]
};
