/* Grade 6 core: ratio-based unit conversion, fraction division, decimal
   operations, exponents and expressions, equations and inequalities,
   dependent/independent variables, area, volume with fractional edges,
   coordinate polygons, nets and surface area, and introductory statistics. */
export const G6_CORE_BANKS = {
"g6-unitconv": [
{sec:"R",type:"in",q:"1 kilometre is 1000 metres. How many metres are in 3.5 km?",ans:3500,
 hint:"Multiply by the number of metres in one kilometre.",expl:"3.5 × 1000 = 3500 metres."},
{sec:"R",type:"in",q:"There are 12 inches in a foot. How many inches are in 7 feet?",ans:84,
 expl:"Each foot is 12 inches, so 7 × 12 = 84 inches."},
{sec:"R",type:"mc",q:"Which ratio would you multiply 500 cm by to convert it to metres?",mono:true,
 opts:["1 m / 100 cm","100 cm / 1 m","1 cm / 100 m","100 m / 1 cm"],a:0,
 expl:"To cancel the cm you need cm on the bottom: 500 cm × (1 m / 100 cm) = 5 m."},
{sec:"R",type:"in",q:"A recipe needs 2.5 litres of juice. How many millilitres is that?",ans:2500,
 hint:"There are 1000 mL in a litre.",expl:"2.5 × 1000 = 2500 mL."},
{lvl:2,sec:"R",type:"in",q:"Amara runs at 8 metres per second. How many metres does she run in 2 minutes?",ans:960,
 hint:"Change the minutes to seconds first.",expl:"2 minutes is 120 seconds, and 8 × 120 = 960 metres."},
{lvl:2,sec:"R",type:"in",q:"A car travels 90 km in 1 hour. What is its speed in metres per minute?",ans:1500,
 hint:"Convert km to m, then hours to minutes.",expl:"90 km = 90,000 m, and 90,000 ÷ 60 minutes = 1500 m per minute."},
{lvl:2,sec:"R",type:"mc",q:"Which of these lengths is the longest?",mono:true,
 opts:["2.5 km","2400 m","240,000 cm","24,000 dm"],a:0,
 expl:"In metres: 2.5 km = 2500 m, 240,000 cm = 2400 m and 24,000 dm = 2400 m. So 2.5 km is the longest."},
{lvl:3,sec:"R",type:"in",q:"Kenji's garden hose delivers 3 litres every 20 seconds. How many litres does it deliver in 1 hour?",ans:540,
 hint:"How many 20-second periods are in an hour?",
 expl:"An hour is 3600 seconds, which is 3600 ÷ 20 = 180 periods. 180 × 3 = 540 litres."},
{lvl:3,sec:"R",type:"order",q:"Put these speeds in order from slowest to fastest.",
 items:["10 m/s","30 km/h","720 m/min","1 km/min"],ansOrder:["30 km/h","10 m/s","720 m/min","1 km/min"],
 hint:"Convert everything to metres per second.",
 expl:"30 km/h = 30,000 ÷ 3600 ≈ 8.3 m/s, 10 m/s stays 10, 720 m/min = 12 m/s and 1 km/min = 1000 ÷ 60 ≈ 16.7 m/s."}
],

"g6-fracdiv": [
{sec:"F",type:"in",q:"How many 1/4-cup scoops of flour are in 3 cups?",ans:12,
 hint:"How many quarters are in one cup?",expl:"3 ÷ 1/4 = 3 × 4 = 12 scoops."},
{sec:"F",type:"mc",q:"What is 2/3 ÷ 4/5?",mono:true,opts:["5/6","8/15","6/5","3/10"],a:0,
 expl:"Dividing by 4/5 is multiplying by 5/4: 2/3 × 5/4 = 10/12 = 5/6."},
{sec:"F",type:"mc",q:"To divide by 3/8, you multiply by which fraction?",mono:true,opts:["8/3","3/8","1/8","8/1"],a:0,
 expl:"Dividing by a fraction is the same as multiplying by its reciprocal, which flips it: 3/8 becomes 8/3."},
{sec:"F",type:"in",q:"What is 5 ÷ 1/2?",ans:10,expl:"There are 2 halves in each whole, so 5 ÷ 1/2 = 5 × 2 = 10."},
{lvl:2,sec:"F",type:"mc",q:"What is 3/4 ÷ 9/10?",mono:true,opts:["5/6","27/40","6/5","9/10"],a:0,
 expl:"3/4 × 10/9 = 30/36, which simplifies to 5/6."},
{lvl:2,sec:"F",type:"in",q:"Priya has 4 1/2 metres of ribbon. She cuts it into pieces that are 3/4 metre long. How many pieces does she get?",ans:6,
 hint:"Write 4 1/2 as an improper fraction first.",expl:"9/2 ÷ 3/4 = 9/2 × 4/3 = 36/6 = 6 pieces."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY expression that equals 6.",mono:true,
 opts:["3 ÷ 1/2","2 ÷ 1/3","4 ÷ 2/3","1/2 ÷ 3"],aMulti:[0,1,2],
 expl:"3 ÷ 1/2 = 6, 2 ÷ 1/3 = 6 and 4 ÷ 2/3 = 4 × 3/2 = 6. But 1/2 ÷ 3 = 1/6."},
{lvl:3,sec:"F",type:"in",q:"A jug holds 2/3 of a litre. How many full jugs are needed to pour 6 litres into a bucket?",ans:9,
 hint:"Divide the total by the size of one jug.",expl:"6 ÷ 2/3 = 6 × 3/2 = 9 jugs."},
{lvl:3,sec:"F",type:"mc",q:"Mateo walked 5/6 of a mile in 1/4 of an hour. At that rate, how many miles does he walk in one hour?",mono:true,
 opts:["3 1/3","5/24","2 2/3","4"],a:0,
 hint:"Distance divided by time gives the rate.",expl:"5/6 ÷ 1/4 = 5/6 × 4 = 20/6 = 10/3 = 3 1/3 miles per hour."}
],

"g6-decimals": [
{sec:"N",type:"in",q:"3.25 + 12.8 = ?",ans:16.05,hint:"Line up the decimal points.",expl:"3.25 + 12.80 = 16.05."},
{sec:"N",type:"in",q:"20 − 7.36 = ?",ans:12.64,expl:"20.00 − 7.36 = 12.64."},
{sec:"N",type:"in",q:"4.5 × 2.2 = ?",ans:9.9,hint:"Multiply 45 × 22, then place the decimal point.",
 expl:"45 × 22 = 990. There are two decimal places in total, so the answer is 9.90 = 9.9."},
{sec:"N",type:"in",q:"9.6 ÷ 0.4 = ?",ans:24,hint:"Multiply both numbers by 10 first.",expl:"9.6 ÷ 0.4 = 96 ÷ 4 = 24."},
{lvl:2,sec:"N",type:"in",q:"1.25 × 0.8 = ?",ans:1,expl:"125 × 8 = 1000, and with three decimal places that is 1.000 = 1."},
{lvl:2,sec:"N",type:"in",q:"A bottle holds 0.75 litres. How many bottles are needed to hold 13.5 litres?",ans:18,
 hint:"Divide, or think of how many three-quarters make 13.5.",expl:"13.5 ÷ 0.75 = 1350 ÷ 75 = 18 bottles."},
{lvl:2,sec:"N",type:"mc",q:"The digits of 3.6 × 2.15 are 774. Where does the decimal point go?",mono:true,
 opts:["7.74","77.4","0.774","774"],a:0,
 expl:"3.6 is about 4 and 2.15 is about 2, so the product is about 8. The answer is 7.74."},
{lvl:3,sec:"N",type:"in",q:"Zainab buys 3 notebooks at $2.45 each and pays with a $10 note. How much change does she get, in dollars?",ans:2.65,
 hint:"Find the total cost first.",expl:"3 × 2.45 = 7.35, and 10 − 7.35 = 2.65 dollars."},
{lvl:3,sec:"N",type:"in",q:"A rectangle is 4.8 cm long and has an area of 15.36 square cm. What is its width in cm?",ans:3.2,
 hint:"Area = length × width.",expl:"15.36 ÷ 4.8 = 1536 ÷ 480 = 3.2 cm."},
{lvl:3,sec:"N",type:"multi",q:"Select EVERY statement that is true.",mono:true,
 opts:["0.5 × 0.5 is less than 0.5","6 ÷ 0.5 is greater than 6","2.4 × 10 = 2.40","1.5 ÷ 3 = 5"],aMulti:[0,1],
 expl:"0.5 × 0.5 = 0.25, which is less than 0.5, and 6 ÷ 0.5 = 12, which is more than 6. 2.4 × 10 = 24 and 1.5 ÷ 3 = 0.5."}
],

"g6-exprexp": [
{sec:"L",type:"in",q:"What is 2⁵ (2 to the power of 5)?",ans:32,hint:"Multiply five 2s together.",
 expl:"2 × 2 × 2 × 2 × 2 = 32."},
{sec:"L",type:"in",q:"Evaluate 3² + 4².",ans:25,expl:"3² = 9 and 4² = 16, so 9 + 16 = 25."},
{sec:"L",type:"mc",q:"Which expression means 5 × 5 × 5 × 5?",mono:true,opts:["5⁴","4⁵","5 × 4","20"],a:0,
 expl:"Four copies of 5 multiplied together is 5 to the power of 4, written 5⁴."},
{sec:"L",type:"in",q:"Evaluate 10³ − 10².",ans:900,expl:"10³ = 1000 and 10² = 100, so 1000 − 100 = 900."},
{lvl:2,sec:"L",type:"in",q:"Evaluate 2 × 3² + 4.",ans:22,hint:"Powers come before multiplying and adding.",
 expl:"3² = 9, then 2 × 9 = 18, then 18 + 4 = 22."},
{lvl:2,sec:"L",type:"in",q:"If x = 3, what is the value of x³ − 2x?",ans:21,expl:"3³ = 27 and 2 × 3 = 6, so 27 − 6 = 21."},
{lvl:2,sec:"L",type:"mc",q:"Which is the correct first step to evaluate 4 + 6 × 2²?",
 opts:["Work out 2²","Add 4 + 6","Multiply 6 × 2","Add 4 + 2"],a:0,
 expl:"The order of operations does powers first: 2² = 4, then 6 × 4 = 24, then 4 + 24 = 28."},
{lvl:3,sec:"L",type:"in",q:"Evaluate (5 − 2)³ + 12 ÷ 2² × 3.",ans:36,hint:"Brackets, then powers, then divide and multiply from left to right.",
 expl:"(5 − 2)³ = 27. Then 12 ÷ 4 = 3 and 3 × 3 = 9. Finally 27 + 9 = 36."},
{lvl:3,sec:"L",type:"order",q:"Put these values in order from smallest to largest.",
 items:["2⁵","5²","3³","4²"],ansOrder:["4²","5²","3³","2⁵"],hint:"Work out each power.",
 expl:"4² = 16, 5² = 25, 3³ = 27 and 2⁵ = 32."},
{lvl:3,sec:"L",type:"in",q:"A positive number is squared and then 7 is subtracted. The result is 57. What is the number?",ans:8,
 hint:"Undo the subtraction first.",expl:"The square must be 57 + 7 = 64, and 8² = 64, so the number is 8."}
],

"g6-equivexpr": [
{sec:"L",type:"mc",q:"Which expression is equivalent to 3(x + 4)?",mono:true,opts:["3x + 12","3x + 4","x + 12","3x + 7"],a:0,
 expl:"Use the distributive property: 3 × x + 3 × 4 = 3x + 12."},
{sec:"L",type:"mc",q:"Simplify 5y + 2y − 3y.",mono:true,opts:["4y","10y","4","7y − 3"],a:0,
 expl:"Combine like terms: 5 + 2 − 3 = 4, so the result is 4y."},
{sec:"L",type:"mc",q:"Which expression is equivalent to 6a + 9?",mono:true,opts:["3(2a + 3)","3(2a + 9)","6(a + 9)","15a"],a:0,
 expl:"The common factor of 6a and 9 is 3, and 3(2a + 3) = 6a + 9."},
{sec:"L",type:"in",q:"Simplify 4x + 7 + 2x − 3. What is the coefficient of x?",ans:6,
 hint:"Collect the x terms together.",expl:"4x + 2x = 6x and 7 − 3 = 4, giving 6x + 4. The coefficient of x is 6."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY expression equivalent to 2(3n + 1) + n.",mono:true,
 opts:["7n + 2","6n + 2 + n","6n + 3","8n + 1"],aMulti:[0,1],
 expl:"2(3n + 1) = 6n + 2, so the expression is 6n + 2 + n = 7n + 2."},
{lvl:2,sec:"L",type:"mc",q:"Which expression is equivalent to 12x − 8?",mono:true,
 opts:["4(3x − 2)","4(3x − 8)","2(6x − 8)","12(x − 8)"],a:0,
 expl:"4(3x − 2) = 12x − 8. The others expand to 12x − 32, 12x − 16 and 12x − 96."},
{lvl:2,sec:"L",type:"in",q:"If 3(2x + 5) is written in the form ax + b, what is b?",ans:15,
 expl:"3(2x + 5) = 6x + 15, so b = 15."},
{lvl:3,sec:"L",type:"mc",q:"Simplify 4(2m − 3) − 2(m − 5).",mono:true,opts:["6m − 2","6m − 22","10m − 2","6m + 2"],a:0,
 hint:"Watch the signs when you distribute the −2.",
 expl:"4(2m − 3) = 8m − 12 and −2(m − 5) = −2m + 10. Together: 8m − 2m − 12 + 10 = 6m − 2."},
{lvl:3,sec:"L",type:"in",q:"A rectangle has length x + 5 and width x. Its perimeter is written as ax + b. What is a + b?",ans:14,
 hint:"Perimeter is twice the length plus twice the width.",
 expl:"Perimeter = 2(x + 5) + 2x = 2x + 10 + 2x = 4x + 10. So a = 4, b = 10 and a + b = 14."},
{lvl:3,sec:"L",type:"mc",q:"Tomas says 2(x + 3) and 2x + 3 are equivalent. Which statement is correct?",
 opts:["They differ for every value of x","They are equal for every value of x","They are equal only when x = 0","They are equal only when x = 3"],a:0,
 expl:"2(x + 3) = 2x + 6, which is always 3 more than 2x + 3, so the two expressions are never equal."}
],

"g6-onevar": [
{sec:"L",type:"in",q:"Solve x + 9 = 23.",ans:14,hint:"Subtract 9 from both sides.",expl:"x = 23 − 9 = 14."},
{sec:"L",type:"in",q:"Solve 4y = 52.",ans:13,expl:"Divide both sides by 4: y = 52 ÷ 4 = 13."},
{sec:"L",type:"in",q:"Solve n ÷ 6 = 7.",ans:42,hint:"Undo dividing by 6.",expl:"Multiply both sides by 6: n = 7 × 6 = 42."},
{sec:"L",type:"mc",q:"Which inequality says 'x is less than 8'?",mono:true,opts:["x < 8","x ≤ 8","x > 8","x ≥ 8"],a:0,
 expl:"'Less than' is the < symbol, so x < 8. The ≤ symbol would mean less than or equal to."},
{lvl:2,sec:"L",type:"in",q:"Aisha has 36 stickers, which is 4 times as many as Wei. Solve 4w = 36 to find how many stickers Wei has.",ans:9,
 expl:"4w = 36, so w = 36 ÷ 4 = 9 stickers."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY value that is a solution of x > 4.5.",mono:true,opts:["5","4.6","4.5","4"],aMulti:[0,1],
 expl:"5 and 4.6 are both greater than 4.5. 4.5 itself is not greater than 4.5, and 4 is smaller."},
{lvl:2,sec:"L",type:"mc",q:"A go-kart ride allows riders whose height h, in cm, is at least 120. Which inequality shows this?",mono:true,
 opts:["h ≥ 120","h > 120","h ≤ 120","h < 120"],a:0,
 expl:"'At least 120' includes 120 itself, so the inequality is h ≥ 120."},
{lvl:3,sec:"L",type:"in",q:"Oluwaseun bought 3 identical pens and a $2.50 notebook, spending $9.25 in total. What is the price of one pen in dollars?",ans:2.25,
 hint:"Write the equation 3p + 2.50 = 9.25.",expl:"3p + 2.50 = 9.25, so 3p = 6.75 and p = 2.25 dollars."},
{lvl:3,sec:"L",type:"in",q:"A number is multiplied by 6, and the result is 3 less than 45. What is the number?",ans:7,
 hint:"Work out what 6 times the number equals first.",expl:"6n = 45 − 3 = 42, so n = 42 ÷ 6 = 7."},
{lvl:3,sec:"L",type:"mc",q:"Which inequality has 5 as a solution but does NOT have 6 as a solution?",mono:true,
 opts:["x < 6","x > 5","x ≥ 6","x < 5"],a:0,
 expl:"5 < 6 is true and 6 < 6 is false, so x < 6 works. x > 5 and x ≥ 6 both include 6, and x < 5 leaves out 5."}
],

"g6-relation": [
{sec:"L",type:"mc",q:"Ingrid earns $8 for each hour she works. Which is the dependent variable?",
 opts:["Her total pay","The number of hours","The amount $8","The day of the week"],a:0,
 expl:"Her total pay depends on how many hours she works, so pay is the dependent variable."},
{sec:"L",type:"mc",q:"Tickets cost $4 each. Which equation shows the total cost c for t tickets?",mono:true,
 opts:["c = 4t","t = 4c","c = t + 4","c = 4"],a:0,
 expl:"Each ticket adds $4, so the cost is 4 times the number of tickets: c = 4t."},
{sec:"L",type:"in",q:"The equation d = 60t gives the distance d in km after t hours. What is d when t = 2.5?",ans:150,
 expl:"d = 60 × 2.5 = 150 km."},
{sec:"L",type:"mc",q:"In the equation y = x + 7, which variable is the independent variable?",mono:true,opts:["x","y","7","x + 7"],a:0,
 expl:"You choose x freely, and y is worked out from it, so x is independent and y is dependent."},
{lvl:2,sec:"L",type:"mc",q:"A table shows x = 1, 2, 3, 4 and y = 5, 10, 15, 20. Which equation matches the table?",mono:true,
 opts:["y = 5x","y = x + 4","y = x + 5","y = 4x + 1"],a:0,
 expl:"Each y is 5 times its x: 5 × 1 = 5, 5 × 2 = 10 and so on, so y = 5x."},
{lvl:2,sec:"L",type:"in",q:"The equation y = 3x + 2 relates x and y. What is y when x = 6?",ans:20,expl:"y = 3 × 6 + 2 = 18 + 2 = 20."},
{lvl:2,sec:"L",type:"mc",q:"Ravi fills a pool and the water depth rises 2 cm every minute. Which statement is correct?",
 opts:["Depth depends on time","Time depends on depth","Neither depends on the other","Depth is the independent variable"],a:0,
 expl:"The depth is worked out from how long the water has been running, so depth is dependent and time is independent."},
{lvl:3,sec:"L",type:"in",q:"A taxi fare follows the rule f = ak + b. Travelling 1 km costs $5, 2 km costs $7 and 3 km costs $9. What is the fare, in dollars, for 10 km?",ans:23,
 hint:"How much does each extra kilometre add?",
 expl:"Each km adds $2, so a = 2, and then 2 × 1 + b = 5 gives b = 3. For 10 km: 2 × 10 + 3 = 23 dollars."},
{lvl:3,sec:"L",type:"in",q:"Sofia's plant is 4 cm tall and grows 1.5 cm each week, so its height is h = 4 + 1.5w. After how many weeks is it 19 cm tall?",ans:10,
 hint:"Solve 4 + 1.5w = 19.",expl:"1.5w = 19 − 4 = 15, so w = 15 ÷ 1.5 = 10 weeks."},
{lvl:3,sec:"L",type:"multi",q:"Select EVERY point (x, y) that fits the equation y = 2x − 1.",mono:true,
 opts:["(3, 5)","(0, −1)","(2, 4)","(4, 7)"],aMulti:[0,1,3],
 expl:"2 × 3 − 1 = 5, 2 × 0 − 1 = −1 and 2 × 4 − 1 = 7 all work. But 2 × 2 − 1 = 3, not 4."}
],

"g6-polyarea": [
{sec:"G",type:"in",q:"A triangle has a base of 10 cm and a height of 6 cm. What is its area in square cm?",ans:30,
 hint:"Half of base times height.",expl:"Area = 10 × 6 ÷ 2 = 30 square cm."},
{sec:"G",type:"in",q:"A parallelogram has a base of 9 m and a height of 4 m. What is its area in square metres?",ans:36,
 expl:"A parallelogram's area is base × height = 9 × 4 = 36 square metres."},
{sec:"G",type:"mc",q:"Which formula gives the area of a trapezium with parallel sides a and b and height h?",mono:true,
 opts:["(a + b) × h ÷ 2","a × b × h","(a + b) × h","a × h ÷ 2"],a:0,
 expl:"A trapezium is half of a parallelogram with base a + b, so its area is (a + b) × h ÷ 2."},
{sec:"G",type:"in",q:"A trapezium has parallel sides of 8 cm and 12 cm and a height of 5 cm. What is its area in square cm?",ans:50,
 expl:"(8 + 12) × 5 ÷ 2 = 20 × 5 ÷ 2 = 50 square cm."},
{lvl:2,sec:"G",type:"in",q:"A right triangle has legs of 7 cm and 24 cm. What is its area in square cm?",ans:84,
 hint:"The two legs are the base and the height.",expl:"7 × 24 ÷ 2 = 168 ÷ 2 = 84 square cm."},
{lvl:2,sec:"G",type:"in",q:"A kite is made from two triangles sharing a base of 10 cm. Their heights are 3 cm and 7 cm. What is the kite's area in square cm?",ans:50,
 hint:"Find each triangle's area and add.",expl:"10 × 3 ÷ 2 = 15 and 10 × 7 ÷ 2 = 35, so the kite's area is 15 + 35 = 50 square cm."},
{lvl:2,sec:"G",type:"in",q:"A triangle has an area of 42 square cm and a base of 12 cm. What is its height in cm?",ans:7,
 hint:"Double the area, then divide by the base.",expl:"Base × height = 2 × 42 = 84, so the height is 84 ÷ 12 = 7 cm."},
{lvl:3,sec:"G",type:"in",q:"A hexagon is made from a 6 cm by 4 cm rectangle with a triangle of height 3 cm attached to each 6 cm side. What is the total area in square cm?",ans:42,
 hint:"Split the shape into a rectangle and two triangles.",
 expl:"The rectangle is 6 × 4 = 24. Each triangle is 6 × 3 ÷ 2 = 9. Total: 24 + 9 + 9 = 42 square cm."},
{lvl:3,sec:"G",type:"in",q:"A parallelogram has an area of 72 square cm and a base of 9 cm. A triangle has the same base and the same height. What is the triangle's area in square cm?",ans:36,
 hint:"You do not need to find the height.",expl:"A triangle with the same base and height is half the parallelogram: 72 ÷ 2 = 36 square cm."},
{lvl:3,sec:"G",type:"multi",q:"Select EVERY shape whose area is 24 square units.",
 opts:["Triangle: base 8, height 6","Parallelogram: base 6, height 4","Trapezium: parallel sides 5 and 7, height 4","Triangle: base 6, height 4"],aMulti:[0,1,2],
 expl:"8 × 6 ÷ 2 = 24, 6 × 4 = 24 and (5 + 7) × 4 ÷ 2 = 24. The last triangle is 6 × 4 ÷ 2 = 12."}
],

"g6-volfrac": [
{sec:"G",type:"in",q:"A box is 4 cm by 2.5 cm by 3 cm. What is its volume in cubic cm?",ans:30,
 hint:"Multiply the three edge lengths.",expl:"4 × 2.5 × 3 = 30 cubic cm."},
{sec:"G",type:"mc",q:"A cube has edges of 1/2 unit. What is its volume?",mono:true,
 opts:["1/8 cubic unit","1/2 cubic unit","1/6 cubic unit","3/2 cubic units"],a:0,
 expl:"1/2 × 1/2 × 1/2 = 1/8 cubic unit."},
{sec:"G",type:"in",q:"How many cubes with 1/2-cm edges fit exactly inside a cube with 1-cm edges?",ans:8,
 hint:"Think about how many fit along each edge.",expl:"Two fit along each edge, so 2 × 2 × 2 = 8 small cubes."},
{sec:"G",type:"in",q:"A rectangular prism is 2 1/2 m long, 2 m wide and 1 m high. What is its volume in cubic metres?",ans:5,
 expl:"2 1/2 × 2 × 1 = 5 cubic metres."},
{lvl:2,sec:"G",type:"in",q:"A fish tank is 3/4 m by 1/2 m by 2/3 m. What is its volume in cubic metres, written as a decimal?",ans:0.25,
 hint:"Multiply the fractions, then convert.",expl:"3/4 × 1/2 × 2/3 = 6/24 = 1/4 = 0.25 cubic metres."},
{lvl:2,sec:"G",type:"in",q:"How many cubes with 1/3-inch edges are needed to fill a box that is 2 inches by 1 inch by 1 inch?",ans:54,
 hint:"Three cubes fit along each inch.",expl:"6 fit along the 2-inch edge and 3 along each 1-inch edge: 6 × 3 × 3 = 54 cubes."},
{lvl:2,sec:"G",type:"mc",q:"A prism has a volume of 7 1/2 cubic cm, a length of 3 cm and a width of 2 1/2 cm. What is its height?",
 opts:["1 cm","2 cm","1/2 cm","3 cm"],a:0,
 expl:"The base area is 3 × 2 1/2 = 7 1/2 square cm, so the height is 7 1/2 ÷ 7 1/2 = 1 cm."},
{lvl:3,sec:"G",type:"in",q:"A box 3 1/2 cm by 2 cm by 1 1/2 cm is packed with cubes of edge 1/2 cm. How many cubes are needed?",ans:84,
 hint:"Count cubes along each edge, then multiply.",expl:"Along the edges: 7, 4 and 3 cubes. 7 × 4 × 3 = 84 cubes."},
{lvl:3,sec:"G",type:"in",q:"Yusuf's prism is 2 1/4 inches long, 2 inches wide and 4 inches tall. Hana's prism has the same volume and a 3 inch by 3 inch base. How tall is Hana's prism in inches?",ans:2,
 hint:"Find the volume of the first prism.",expl:"2 1/4 × 2 × 4 = 18 cubic inches. Hana's base is 9 square inches, so the height is 18 ÷ 9 = 2 inches."},
{lvl:3,sec:"G",type:"multi",q:"Select EVERY set of edge lengths that gives a volume of 3 cubic units.",mono:true,
 opts:["1/2 × 2 × 3","1 1/2 × 1 × 2","3/4 × 4 × 1","1/3 × 3 × 1"],aMulti:[0,1,2],
 expl:"1/2 × 2 × 3 = 3, 1 1/2 × 1 × 2 = 3 and 3/4 × 4 × 1 = 3. But 1/3 × 3 × 1 = 1."}
],

"g6-coordpoly": [
{sec:"G",type:"pair",q:"A rectangle has vertices at (1, 1), (5, 1) and (5, 4). Write the fourth vertex as an ordered pair.",ansP:[1,4],
 hint:"It shares its x with one corner and its y with another.",expl:"The fourth corner sits above (1, 1) at the same height as (5, 4): (1, 4)."},
{sec:"G",type:"in",q:"What is the distance between the points (2, 3) and (2, 10)?",ans:7,
 hint:"The x-coordinates are the same.",expl:"The points are on a vertical line, so the distance is 10 − 3 = 7 units."},
{sec:"G",type:"in",q:"A rectangle has vertices (0, 0), (6, 0), (6, 3) and (0, 3). What is its area in square units?",ans:18,
 expl:"The width is 6 and the height is 3, so the area is 6 × 3 = 18 square units."},
{sec:"G",type:"mc",q:"Points (−3, 2) and (5, 2) are two corners of a shape. How long is the side joining them?",
 opts:["8 units","2 units","3 units","5 units"],a:0,
 expl:"They are on the same horizontal line. From −3 to 5 is 3 + 5 = 8 units."},
{lvl:2,sec:"G",type:"in",q:"A square has vertices (−2, −2), (3, −2), (3, 3) and (−2, 3). What is its perimeter in units?",ans:20,
 hint:"Find one side length first.",expl:"Each side is 3 − (−2) = 5 units, so the perimeter is 4 × 5 = 20 units."},
{lvl:2,sec:"G",type:"pair",q:"Points A(1, 2), B(5, 2) and C(1, 6) are three corners of a square. Write the fourth corner D as an ordered pair.",ansP:[5,6],
 hint:"D is directly above B and directly right of C.",expl:"The square is 4 units wide and 4 tall, so D is at (5, 6)."},
{lvl:2,sec:"G",type:"in",q:"A triangle has vertices (0, 0), (8, 0) and (3, 5). What is its area in square units?",ans:20,
 hint:"The base is along the x-axis.",expl:"The base is 8 and the height is 5, so the area is 8 × 5 ÷ 2 = 20 square units."},
{lvl:3,sec:"G",type:"in",q:"An L-shape has vertices (0, 0), (6, 0), (6, 2), (2, 2), (2, 5) and (0, 5). What is its area in square units?",ans:18,
 hint:"Cut it into two rectangles.",expl:"A 6 by 2 rectangle (12) plus a 2 by 3 rectangle on top (6) gives 12 + 6 = 18 square units."},
{lvl:3,sec:"G",type:"in",q:"A trapezium has vertices (1, 1), (9, 1), (7, 5) and (3, 5). What is its area in square units?",ans:24,
 hint:"Find the two parallel sides and the height.",expl:"The parallel sides are 8 and 4 units long and the height is 4, so the area is (8 + 4) × 4 ÷ 2 = 24 square units."},
{lvl:3,sec:"G",type:"pair",q:"A rectangle has (−3, −2) and (5, −2) as its bottom corners and an area of 40 square units. Write the top-right corner as an ordered pair.",ansP:[5,3],
 hint:"Use the width to find the height.",expl:"The width is 8, so the height is 40 ÷ 8 = 5. The top-right corner is 5 above (5, −2), at (5, 3)."}
],

"g6-netsurf": [
{sec:"G",type:"in",q:"A cube has edges of 3 cm. What is its surface area in square cm?",ans:54,
 hint:"Six equal square faces.",expl:"Each face is 3 × 3 = 9 square cm, and 6 × 9 = 54 square cm."},
{sec:"G",type:"mc",q:"The net of a rectangular prism is made up of how many rectangles?",opts:["6","4","8","5"],a:0,
 expl:"A rectangular prism has 6 faces, so its net shows 6 rectangles."},
{sec:"G",type:"in",q:"A box is 5 cm by 4 cm by 2 cm. What is its surface area in square cm?",ans:76,
 hint:"Faces come in matching pairs.",expl:"The faces are 5 × 4 = 20, 5 × 2 = 10 and 4 × 2 = 8, each twice: 2 × (20 + 10 + 8) = 76 square cm."},
{sec:"G",type:"mc",q:"Which set of shapes folds into a triangular prism?",
 opts:["2 triangles and 3 rectangles","4 triangles","6 squares","1 square and 4 triangles"],a:0,
 expl:"A triangular prism has two triangular ends joined by three rectangular faces."},
{lvl:2,sec:"G",type:"in",q:"A square pyramid has a 6 cm by 6 cm base and four triangular faces, each with a height of 5 cm. What is its surface area in square cm?",ans:96,
 hint:"Base plus four triangles.",expl:"The base is 36. Each triangle is 6 × 5 ÷ 2 = 15, so 36 + 4 × 15 = 96 square cm."},
{lvl:2,sec:"G",type:"in",q:"A triangular prism has two triangular ends, each with base 6 cm and height 4 cm, and three rectangular faces measuring 6 by 10 cm, 5 by 10 cm and 5 by 10 cm. What is its surface area in square cm?",ans:184,
 hint:"Add all five faces.",expl:"The ends are 2 × (6 × 4 ÷ 2) = 24. The rectangles are 60 + 50 + 50 = 160. Total: 24 + 160 = 184 square cm."},
{lvl:2,sec:"G",type:"mc",q:"A cube has a surface area of 150 square cm. What is the length of one edge?",
 opts:["5 cm","25 cm","6 cm","12.5 cm"],a:0,
 expl:"Each of the 6 faces is 150 ÷ 6 = 25 square cm, and 5 × 5 = 25, so the edge is 5 cm."},
{lvl:3,sec:"G",type:"in",q:"Diego paints every face of a 10 cm by 8 cm by 6 cm box except the bottom. How many square cm does he paint?",ans:296,
 hint:"Find the whole surface area, then remove one face.",
 expl:"Total surface area is 2 × (80 + 60 + 48) = 376. The bottom is 10 × 8 = 80, so he paints 376 − 80 = 296 square cm."},
{lvl:3,sec:"G",type:"in",q:"A cube with 4 cm edges is cut in half into two identical 4 cm by 4 cm by 2 cm prisms. What is the total surface area of both pieces in square cm?",ans:128,
 hint:"Cutting creates two new faces.",expl:"The cube had 6 × 16 = 96 square cm. The cut adds two new 4 × 4 faces: 96 + 32 = 128 square cm."},
{lvl:3,sec:"G",type:"multi",q:"Select EVERY statement that is true about a cube with 2 cm edges.",
 opts:["Its surface area is 24 square cm","Its net is made of 6 squares","Its surface area is 8 square cm","Each face has an area of 2 square cm"],aMulti:[0,1],
 expl:"Each face is 2 × 2 = 4 square cm and there are 6 faces, so the surface area is 24 square cm. 8 is the volume."}
],

"g6-statq": [
{sec:"S",type:"mc",q:"Which of these is a statistical question?",
 opts:["How many pets do students in my class have?","How many pets does Femi have?","How old is my teacher?","What is 7 × 8?"],a:0,
 expl:"A statistical question expects answers that vary. Different students have different numbers of pets."},
{sec:"S",type:"mc",q:"A statistical question is a question that...",
 opts:["expects answers that vary","has exactly one answer","is only about numbers","cannot be answered"],a:0,
 expl:"Statistical questions anticipate variability in the data collected to answer them."},
{sec:"S",type:"multi",q:"Select EVERY question that is statistical.",
 opts:["How tall are the players on the team?","How long do Grade 6 students sleep each night?","How many days are in a week?","What is Mei's shoe size?"],aMulti:[0,1],
 expl:"Heights and sleep times vary from person to person. A week always has 7 days, and one person's shoe size is a single answer."},
{sec:"S",type:"mc",q:"Which question would give data with variability?",
 opts:["How far do students travel to school?","How many legs does a dog have?","How many minutes are in an hour?","What year is it now?"],a:0,
 expl:"Students live at different distances, so the answers vary. The others each have one fixed answer."},
{lvl:2,sec:"S",type:"mc",q:"Leila asks every student in her class how many siblings they have. What does the set of answers show?",
 opts:["Variability in the data","One fixed answer","No useful information","Only her own siblings"],a:0,
 expl:"Different students give different numbers, so the answers show variability, which is what makes the question statistical."},
{lvl:2,sec:"S",type:"mc",q:"Which change turns 'What is Arjun's favourite colour?' into a statistical question?",
 opts:["Ask every student in the school","Ask Arjun a second time","Ask about his favourite food instead","Ask for his favourite number"],a:0,
 expl:"Asking many people means the answers can vary. Asking one person still gives just one answer."},
{lvl:2,sec:"S",type:"order",q:"Put these steps of a statistical investigation in order, from first to last.",
 items:["Collect the data","Answer the question","Ask a statistical question","Display and analyse the data"],
 ansOrder:["Ask a statistical question","Collect the data","Display and analyse the data","Answer the question"],
 expl:"You start with a question, gather data to answer it, organise and analyse the data, and finally answer the question."},
{lvl:3,sec:"S",type:"mc",q:"Noor wants to know the typical number of books read by Grade 6 students last month. Which plan gives the best data?",
 opts:["Ask a random sample of Grade 6 students","Ask her three best friends","Ask one Grade 6 student","Ask the librarian to guess"],a:0,
 expl:"A random sample of the group being studied gives data that varies and represents the whole grade."},
{lvl:3,sec:"S",type:"multi",q:"Select EVERY statement that is true about the question 'How many minutes do students at this school spend on homework?'",
 opts:["It is a statistical question","The answers are expected to vary","It has one correct answer","Asking one student answers it"],aMulti:[0,1],
 expl:"Homework time differs from student to student, so the question is statistical and needs data from many students."},
{lvl:3,sec:"S",type:"mc",q:"A survey asked 'How many hours do you sleep?' and all 30 people answered 8. Which statement is true?",
 opts:["Statistical question; this data shows no variability","The question cannot be statistical","The data must have been recorded wrongly","A survey with equal answers is not data"],a:0,
 expl:"The question is still statistical because answers could vary; this particular data set just happened to have no spread."}
],

"g6-centervar": [
{sec:"S",type:"in",q:"Find the mean of 4, 8, 6, 10 and 7.",ans:7,hint:"Add them up and divide by how many there are.",
 expl:"4 + 8 + 6 + 10 + 7 = 35, and 35 ÷ 5 = 7."},
{sec:"S",type:"in",q:"Find the median of 3, 9, 5, 12 and 7.",ans:7,hint:"Put the numbers in order first.",
 expl:"In order: 3, 5, 7, 9, 12. The middle value is 7."},
{sec:"S",type:"in",q:"Find the range of 15, 22, 9, 30 and 18.",ans:21,expl:"Range = largest − smallest = 30 − 9 = 21."},
{sec:"S",type:"mc",q:"Which measure is the value that appears most often in a data set?",opts:["Mode","Mean","Median","Range"],a:0,
 expl:"The mode is the most frequent value. The mean and median are other measures of centre, and the range measures spread."},
{lvl:2,sec:"S",type:"in",q:"Find the median of 6, 2, 9, 4, 11 and 7.",ans:6.5,hint:"With an even count, average the two middle values.",
 expl:"In order: 2, 4, 6, 7, 9, 11. The two middle values are 6 and 7, so the median is (6 + 7) ÷ 2 = 6.5."},
{lvl:2,sec:"S",type:"in",q:"Chioma's test scores are 82, 90, 76 and 88. What score on a fifth test would give her a mean of 85?",ans:89,
 hint:"What total do five scores need for a mean of 85?",expl:"Five scores with mean 85 total 425. She has 336 so far, so she needs 425 − 336 = 89."},
{lvl:2,sec:"S",type:"mc",q:"Data: 2, 3, 3, 4, 50. Which measure of centre is most affected by the value 50?",opts:["Mean","Median","Mode","None of them"],a:0,
 expl:"The mean uses every value, so 50 pulls it up to 12.4. The median (3) and mode (3) are unaffected."},
{lvl:2,sec:"S",type:"multi",q:"Select EVERY measure that describes variability (spread).",opts:["Range","Interquartile range","Mean","Median"],aMulti:[0,1],
 expl:"Range and interquartile range describe how spread out the data is. Mean and median describe the centre."},
{lvl:3,sec:"S",type:"in",q:"Find the mean absolute deviation of 2, 4, 6 and 8.",ans:2,
 hint:"Find the mean, then the distance of each value from it.",
 expl:"The mean is 5. The distances are 3, 1, 1 and 3, which total 8, and 8 ÷ 4 = 2."},
{lvl:3,sec:"S",type:"in",q:"Find the interquartile range of 5, 7, 8, 10, 12 and 20.",ans:5,
 hint:"Find the median of the lower half and of the upper half.",
 expl:"The lower half 5, 7, 8 has median 7 and the upper half 10, 12, 20 has median 12. IQR = 12 − 7 = 5."},
{lvl:3,sec:"S",type:"in",q:"Five numbers have a mean of 12. Four of them are 9, 11, 14 and 15. What is the fifth number?",ans:11,
 hint:"Work out the total of all five numbers first.",expl:"Five numbers with mean 12 total 60. The four known add to 49, so the fifth is 60 − 49 = 11."},
{lvl:3,sec:"S",type:"mc",q:"Two classes both have a mean score of 70. Class A's scores go from 65 to 75; Class B's go from 40 to 100. Which statement is true?",
 opts:["Class B has greater variability","Class A has greater variability","The classes have equal variability","Class B has a higher mean"],a:0,
 expl:"The means are equal, but Class B's range is 60 while Class A's is only 10, so Class B's scores are more spread out."}
],

"g6-displays": [
{sec:"S",type:"in",q:"A dot plot shows 3 dots above 5, 4 dots above 6 and 1 dot above 7. How many data values are there in total?",ans:8,
 hint:"Each dot is one value.",expl:"3 + 4 + 1 = 8 data values."},
{sec:"S",type:"mc",q:"In a histogram, what does the height of each bar show?",
 opts:["How many values fall in that interval","The mean of that interval","The largest value in the data","The order the data was collected"],a:0,
 expl:"A histogram groups data into intervals, and each bar's height is the count (frequency) of values in that interval."},
{sec:"S",type:"mc",q:"What does the box in a box plot represent?",
 opts:["The middle 50% of the data","The whole data set","The mean of the data","The most common value"],a:0,
 expl:"The box runs from the lower quartile to the upper quartile, which contains the middle half of the data."},
{sec:"S",type:"in",q:"A box plot has a minimum of 4, lower quartile 8, median 12, upper quartile 15 and maximum 20. What is the range?",ans:16,
 expl:"Range = maximum − minimum = 20 − 4 = 16."},
{lvl:2,sec:"S",type:"in",q:"A box plot has a lower quartile of 8 and an upper quartile of 15. What is the interquartile range?",ans:7,
 hint:"It is the length of the box.",expl:"IQR = 15 − 8 = 7."},
{lvl:2,sec:"S",type:"in",q:"A histogram has bars for ages 0–9 (5 people), 10–19 (8 people) and 20–29 (3 people). How many people are aged 10 or older?",ans:11,
 hint:"Add the bars from 10 upwards.",expl:"8 + 3 = 11 people."},
{lvl:2,sec:"S",type:"mc",q:"Which display shows the exact value of every piece of data in a small data set?",
 opts:["Dot plot","Histogram","Box plot","Five-number summary"],a:0,
 expl:"A dot plot has one dot per value. Histograms group values into intervals and box plots only show five summary values."},
{lvl:2,sec:"S",type:"order",q:"Put these parts of a box plot in order from left to right, as they appear on the plot.",
 items:["Median","Minimum","Maximum","Lower quartile","Upper quartile"],
 ansOrder:["Minimum","Lower quartile","Median","Upper quartile","Maximum"],
 expl:"A box plot reads from the smallest value up: minimum, lower quartile, median, upper quartile, maximum."},
{lvl:3,sec:"S",type:"in",q:"A dot plot shows 2 dots at 1, 3 dots at 2, 4 dots at 3 and 1 dot at 4. What is the mean of the data? Give a decimal.",ans:2.4,
 hint:"Multiply each value by its number of dots.",expl:"The total is 2 + 6 + 12 + 4 = 24 over 10 dots, so the mean is 24 ÷ 10 = 2.4."},
{lvl:3,sec:"S",type:"in",q:"A box plot of 40 students' scores has a median of 60 and an upper quartile of 75. About how many students scored above 75?",ans:10,
 hint:"What fraction of the data is above the upper quartile?",expl:"About a quarter of the data lies above the upper quartile: 40 ÷ 4 = 10 students."},
{lvl:3,sec:"S",type:"multi",q:"Select EVERY value you can read directly from a box plot.",
 opts:["The median","The range","The mean","The exact number of data values"],aMulti:[0,1],
 expl:"The line in the box gives the median and the whisker ends give the minimum and maximum, hence the range. The mean and the count are not shown."}
]
};
