/* Grade 6 (additions beyond the coordinate-plane, ratios and percent banks
   that live directly in questions.mjs). */
export const G6_BANKS = {
"g6-unitconv": [
{sec:"R",type:"in",q:"There are 100 centimeters in a meter. How many centimeters are in 3 meters?",
 ans:300,expl:"3 × 100 = 300 centimeters."},
{sec:"R",type:"in",q:"A recipe uses 2 cups. If 1 cup = 8 ounces, how many ounces is that?",
 ans:16,expl:"2 × 8 = 16 ounces."},
{sec:"R",type:"mc",q:"Which ratio converts feet to inches? (1 foot = 12 inches)",mono:true,
 opts:["12 inches : 1 foot","1 inch : 12 feet","1 foot : 1 inch","12 feet : 1 inch"],a:0,
 expl:"The conversion ratio matches the definition: 12 inches for every 1 foot."},
{sec:"R",type:"in",q:"A car travels 60 miles per hour. How many miles in 3 hours?",ans:180,
 expl:"60 × 3 = 180 miles."},
{sec:"R",type:"in",q:"16 ounces = 1 pound. How many ounces are in 2 pounds?",ans:32,
 expl:"2 × 16 = 32 ounces."},
{lvl:2,sec:"R",type:"in",q:"A recipe needs 1.5 pounds of flour. If 1 pound = 16 ounces, how many ounces is that?",
 ans:24,expl:"1.5 × 16 = 24 ounces."},
{lvl:2,sec:"R",type:"in",q:"A car uses gas at a rate of 1 gallon per 25 miles. How many gallons for 150 miles?",
 ans:6,expl:"150 ÷ 25 = 6 gallons."},
{lvl:3,sec:"R",type:"in",q:"A pipe fills at 3 liters per minute. How many liters in 2.5 hours?",
 ans:450,hint:"Convert the hours to minutes first.",
 expl:"2.5 hours = 150 minutes, and 150 × 3 = 450 liters."}
],

"g6-decimals": [
{sec:"D",type:"in",q:"4.75 + 3.6 = ?",ans:8.35,expl:"4.75 + 3.60 = 8.35."},
{sec:"D",type:"in",q:"12.4 − 5.75 = ?",ans:6.65,expl:"12.40 − 5.75 = 6.65."},
{sec:"D",type:"in",q:"2.5 × 1.4 = ?",ans:3.5,expl:"2.5 × 1.4 = 3.5."},
{sec:"D",type:"mc",q:"What is 9.6 ÷ 1.2?",opts:["8","7.2","9.6","10.8"],a:0,
 expl:"9.6 ÷ 1.2 = 8, since 1.2 × 8 = 9.6."},
{sec:"D",type:"in",q:"0.75 × 8 = ?",ans:6,expl:"0.75 × 8 = 6."},
{lvl:2,sec:"D",type:"in",q:"3.25 × 4 = ?",ans:13,expl:"3.25 × 4 = 13."},
{lvl:2,sec:"D",type:"in",q:"A stack of 5 boards is 12.5 cm thick. How thick is ONE board, in cm?",
 ans:2.5,expl:"12.5 ÷ 5 = 2.5 cm."},
{lvl:3,sec:"D",type:"in",q:"A runner's average pace is 6.4 minutes per mile. How many minutes for 3.5 miles?",
 ans:22.4,expl:"6.4 × 3.5 = 22.4 minutes."}
],

"g6-exprexp": [
{sec:"P",type:"in",q:"Evaluate: 3²",ans:9,expl:"3² means 3 × 3 = 9."},
{sec:"P",type:"in",q:"Evaluate: 2⁴",ans:16,expl:"2⁴ means 2 × 2 × 2 × 2 = 16."},
{sec:"P",type:"mc",q:"Which expression equals 5 × 5 × 5?",mono:true,
 opts:["5³","5 × 3","3⁵","15"],a:0,expl:"Three factors of 5 is written as 5 with an exponent of 3: 5³."},
{sec:"P",type:"in",q:"Evaluate: 10³",ans:1000,expl:"10³ = 10 × 10 × 10 = 1000."},
{sec:"P",type:"in",q:"Evaluate: 6² − 4²",ans:20,expl:"6² = 36 and 4² = 16, so 36 − 16 = 20."},
{lvl:2,sec:"P",type:"in",q:"Evaluate: 2³ × 3²",ans:72,expl:"2³ = 8 and 3² = 9, so 8 × 9 = 72."},
{lvl:2,sec:"P",type:"mc",q:"Which is equivalent to 4⁰?",opts:["1","0","4","Undefined"],a:0,
 expl:"Any nonzero number raised to the power of 0 equals 1."},
{lvl:3,sec:"P",type:"in",q:"Evaluate: (2 + 3)² − 2³",ans:17,
 expl:"(2 + 3)² = 5² = 25, and 2³ = 8, so 25 − 8 = 17."}
],

"g6-onevar": [
{sec:"P",type:"in",q:"Solve for x: x + 7 = 15",ans:8,expl:"15 − 7 = 8."},
{sec:"P",type:"in",q:"Solve for x: 3x = 21",ans:7,expl:"21 ÷ 3 = 7."},
{sec:"P",type:"mc",q:"Which value of x makes 2x − 4 = 10 true?",mono:true,
 opts:["7","6","3","5"],a:0,expl:"2 × 7 − 4 = 14 − 4 = 10."},
{sec:"P",type:"in",q:"Solve for x: x/4 = 9",ans:36,expl:"9 × 4 = 36."},
{sec:"P",type:"mc",q:"Which inequality means 'x is at most 5'?",mono:true,
 opts:["x ≤ 5","x < 5","x ≥ 5","x = 5"],a:0,
 expl:"'At most 5' includes 5 itself, which is what ≤ means."},
{lvl:2,sec:"P",type:"in",q:"Solve for x: 5x + 3 = 28",ans:5,expl:"28 − 3 = 25, and 25 ÷ 5 = 5."},
{lvl:2,sec:"P",type:"mc",q:"Which value of x satisfies x − 6 > 2?",mono:true,
 opts:["10","8","6","2"],a:0,expl:"x must be greater than 8. Only 10 satisfies that."},
{lvl:3,sec:"P",type:"in",q:"Solve for x: 2(x + 3) = 16",ans:5,
 expl:"2x + 6 = 16, so 2x = 10 and x = 5."}
],

"g6-fracdiv": [
{sec:"F",type:"mc",q:"1/2 ÷ 1/4 = ?",mono:true,opts:["2","1/8","8","1/2"],a:0,
 expl:"Dividing by a fraction multiplies by its reciprocal: 1/2 × 4 = 2."},
{sec:"F",type:"in",q:"3 ÷ 1/3 = ?",ans:9,expl:"3 × 3 = 9."},
{sec:"F",type:"mc",q:"2/3 ÷ 1/6 = ?",mono:true,opts:["4","2/18","1/4","12"],a:0,
 expl:"2/3 × 6 = 12/3 = 4."},
{sec:"F",type:"in",q:"5/6 ÷ 5/6 = ?",ans:1,expl:"Any nonzero number divided by itself is 1."},
{sec:"F",type:"mc",q:"Which expression means 'how many 1/4s fit in 3'?",mono:true,
 opts:["3 ÷ 1/4","1/4 ÷ 3","3 × 1/4","1/4 × 3"],a:0,
 expl:"'How many of X fit in Y' is division: Y ÷ X."},
{lvl:2,sec:"F",type:"mc",q:"3/4 ÷ 2/3 = ?",mono:true,opts:["9/8","1/2","6/12","8/9"],a:0,
 expl:"3/4 × 3/2 = 9/8."},
{lvl:2,sec:"F",type:"in",q:"A ribbon is 5/6 yard long. Pieces are cut 1/6 yard each. How many pieces?",
 ans:5,expl:"(5/6) ÷ (1/6) = 5."},
{lvl:3,sec:"F",type:"in",q:"A recipe uses 7/8 cup of flour per batch. How many batches can you make with 3.5 cups?",
 ans:4,hint:"Divide the total flour by the amount per batch.",
 expl:"3.5 ÷ (7/8) = 3.5 × 8/7 = 4 batches."}
],

"g6-equivexpr": [
{sec:"P",type:"mc",q:"Which expression is equivalent to 3(x + 4)?",mono:true,
 opts:["3x + 12","3x + 4","x + 12","3x + 7"],a:0,expl:"Distribute the 3: 3 × x + 3 × 4 = 3x + 12."},
{sec:"P",type:"mc",q:"Which is equivalent to 2x + 3x?",mono:true,opts:["5x","6x","2x + 3","5x²"],a:0,
 expl:"Combine like terms: 2x + 3x = 5x."},
{sec:"P",type:"in",q:"Simplify: 4x + 2x − x. What is the coefficient of x?",ans:5,
 expl:"4 + 2 − 1 = 5, so the simplified expression is 5x."},
{sec:"P",type:"mc",q:"Which expression is equivalent to 6x + 9?",mono:true,
 opts:["3(2x + 3)","3(2x + 9)","6(x + 9)","9(6x + 1)"],a:0,
 expl:"Factor out 3: 3(2x + 3) = 6x + 9."},
{sec:"P",type:"mc",q:"Are 2(x + 5) and 2x + 5 equivalent?",opts:["No","Yes","Only if x=0","Only if x=5"],a:0,
 expl:"2(x + 5) = 2x + 10, which is not the same as 2x + 5 for any general x."},
{lvl:2,sec:"P",type:"mc",q:"Which expression is equivalent to 5x − 2x + 7?",mono:true,
 opts:["3x + 7","3x","7x + 7","5x + 7"],a:0,expl:"5x − 2x = 3x, so the expression is 3x + 7."},
{lvl:2,sec:"P",type:"in",q:"If 4(x + 3) = 4x + k, what is k?",ans:12,expl:"4 × 3 = 12."},
{lvl:3,sec:"P",type:"mc",q:"Which expression is NOT equivalent to 8x + 12?",mono:true,
 opts:["4(2x + 4)","4(2x + 3)","2(4x + 6)","4x + 4x + 12"],a:0,
 expl:"4(2x + 4) = 8x + 16, not 8x + 12. The others all simplify correctly to 8x + 12."}
],

"g6-relation": [
{sec:"P",type:"mc",q:"In the equation y = 3x, which variable DEPENDS on the other?",
 opts:["y depends on x","x depends on y","Neither depends","Both are independent"],a:0,
 expl:"y's value is determined by whatever x is, so y is the dependent variable."},
{sec:"P",type:"in",q:"If y = 2x and x = 5, what is y?",ans:10,expl:"2 × 5 = 10."},
{sec:"P",type:"mc",q:"A car's distance depends on the time it travels. Which is the INDEPENDENT variable?",
 opts:["Time","Distance","Speed limit","Car color"],a:0,
 expl:"Time is chosen freely; distance depends on how much time has passed."},
{sec:"P",type:"in",q:"The cost is c = 4n, where n is the number of items. If n = 6, what is c?",ans:24,
 expl:"4 × 6 = 24."},
{sec:"P",type:"mc",q:"Which is a real-world example of a dependent variable?",
 opts:["Your pay, which depends on hours worked","The day of the week","Your name","The color of your shirt"],a:0,
 expl:"Pay changes based on hours worked, so it depends on that other quantity."},
{lvl:2,sec:"P",type:"in",q:"y = 5x − 3. If x = 4, what is y?",ans:17,expl:"5 × 4 = 20, then 20 − 3 = 17."},
{lvl:2,sec:"P",type:"mc",q:"In a table where hours worked increases and pay increases too, pay is the ___ variable.",
 opts:["dependent","independent","constant","unrelated"],a:0,
 expl:"Pay changes in response to hours worked, making it dependent."},
{lvl:3,sec:"P",type:"in",q:"The relationship is y = 2x + 1. For what value of x does y = 15?",ans:7,
 expl:"15 = 2x + 1, so 2x = 14 and x = 7."}
],

"g6-polyarea": [
{sec:"G",type:"in",q:"A triangle has base 8 and height 5. What is its area?",ans:20,
 expl:"Area = 1/2 × base × height = 1/2 × 8 × 5 = 20."},
{sec:"G",type:"in",q:"A parallelogram has base 6 and height 4. What is its area?",ans:24,
 expl:"Area = base × height = 6 × 4 = 24."},
{sec:"G",type:"mc",q:"Which formula finds the area of a triangle?",mono:true,
 opts:["1/2 × base × height","base × height","2 × base × height","base + height"],a:0,
 expl:"A triangle's area is half of a same-base, same-height parallelogram's area."},
{sec:"G",type:"in",q:"A trapezoid has parallel sides 5 and 9, and height 4. What is its area?",ans:28,
 hint:"Area = 1/2 × (sum of parallel sides) × height.",
 expl:"1/2 × (5 + 9) × 4 = 1/2 × 14 × 4 = 28."},
{sec:"G",type:"in",q:"A parallelogram has an area of 45 and a base of 9. What is its height?",ans:5,
 expl:"45 ÷ 9 = 5."},
{lvl:2,sec:"G",type:"in",q:"A triangle has an area of 24 and a base of 8. What is its height?",ans:6,
 hint:"Area = 1/2 × base × height.",expl:"24 = 1/2 × 8 × h, so 24 = 4h and h = 6."},
{lvl:2,sec:"G",type:"in",q:"A trapezoid has parallel sides 6 and 10, and an area of 40. What is its height?",ans:5,
 expl:"40 = 1/2 × (6 + 10) × h = 8h, so h = 5."},
{lvl:3,sec:"G",type:"in",q:"A figure is made of a rectangle (6 by 4) and a triangle on top with base 6 and height 3. What is the TOTAL area?",
 ans:33,expl:"Rectangle: 6 × 4 = 24. Triangle: 1/2 × 6 × 3 = 9. Together: 24 + 9 = 33."}
],

"g6-volfrac": [
{sec:"G",type:"in",q:"A box is 3 by 2 by 1/2 units. What is its volume?",ans:3,expl:"3 × 2 × 0.5 = 3 cubic units."},
{sec:"G",type:"in",q:"A box has length 4, width 1/2, height 2. What is its volume?",ans:4,
 expl:"4 × 0.5 × 2 = 4 cubic units."},
{sec:"G",type:"mc",q:"How do you find the volume of a box with fractional edge lengths?",
 opts:["Multiply length times width times height","Just add all three edges together","It simply cannot be calculated","Only whole-number edges can be used"],a:0,
 expl:"The volume formula works the same way whether the edges are whole numbers or fractions."},
{sec:"G",type:"in",q:"A box is 2 by 2 by 3/4. What is its volume?",ans:3,expl:"2 × 2 × 0.75 = 3 cubic units."},
{sec:"G",type:"in",q:"A box has volume 6 cubic units, length 4, width 1/2. What is its height?",ans:3,
 expl:"6 ÷ (4 × 0.5) = 6 ÷ 2 = 3."},
{lvl:2,sec:"G",type:"in",q:"A box is 1/2 by 1/2 by 8. What is its volume?",ans:2,expl:"0.5 × 0.5 × 8 = 2 cubic units."},
{lvl:2,sec:"G",type:"in",q:"A fish tank is 5 by 2 by 3/2. What is its volume?",ans:15,expl:"5 × 2 × 1.5 = 15 cubic units."},
{lvl:3,sec:"G",type:"in",q:"A box has volume 10, and its length and width are both 2. What is its height, as a decimal?",
 ans:2.5,expl:"10 ÷ (2 × 2) = 10 ÷ 4 = 2.5."}
],

"g6-coordpoly": [
{sec:"G",type:"in",q:"A rectangle has corners (1,1), (5,1), (5,4), (1,4). What is its length (the horizontal side)?",
 ans:4,expl:"5 − 1 = 4."},
{sec:"G",type:"in",q:"Using that same rectangle, what is its width (the vertical side)?",ans:3,
 expl:"4 − 1 = 3."},
{sec:"G",type:"in",q:"What is the AREA of that rectangle?",ans:12,expl:"4 × 3 = 12."},
{sec:"G",type:"mc",q:"A polygon's vertices are all plotted on the coordinate plane. What can you find directly from the coordinates?",
 opts:["Side lengths and area","The color of the shape","The polygon's name only","Nothing useful"],a:0,
 expl:"Differences in x and y coordinates give side lengths, which lead to perimeter and area."},
{sec:"G",type:"in",q:"Two points (2,3) and (2,8) share the same x-coordinate. What is the distance between them?",
 ans:5,expl:"Same x-coordinate means a vertical distance: 8 − 3 = 5."},
{lvl:2,sec:"G",type:"in",q:"A square has corners at (0,0), (6,0), (6,6), (0,6). What is its perimeter?",
 ans:24,expl:"Each side is 6 units: 4 × 6 = 24."},
{lvl:2,sec:"G",type:"in",q:"A rectangle has corners (-2,1), (3,1), (3,5), (-2,5). What is its area?",
 ans:20,hint:"Find the length and width from the coordinates first.",
 expl:"Length = 3 − (−2) = 5. Width = 5 − 1 = 4. Area = 5 × 4 = 20."},
{lvl:3,sec:"G",type:"in",q:"A rectangle has one pair of corners at (1,2) and (7,2), and its area is 24. What is its height?",
 ans:4,hint:"Find the length first, then divide the area by it.",
 expl:"Length = 7 − 1 = 6. Height = 24 ÷ 6 = 4."}
],

"g6-netsurf": [
{sec:"G",type:"in",q:"A cube has sides of 3 units. What is the area of ONE face?",ans:9,expl:"3 × 3 = 9."},
{sec:"G",type:"in",q:"A cube has sides of 4 units. What is its TOTAL surface area (6 faces)?",ans:96,
 expl:"One face is 4 × 4 = 16. Six faces: 6 × 16 = 96."},
{sec:"G",type:"mc",q:"A net is a shape that ___.",
 opts:["unfolds into a flat pattern of a 3D solid","is only for triangles","cannot be folded","is always a circle"],a:0,
 expl:"A net is the 2D pattern that folds up into a 3D solid."},
{sec:"G",type:"in",q:"A rectangular box is 2 by 3 by 4. What is the area of the 2-by-3 face?",ans:6,
 expl:"2 × 3 = 6."},
{sec:"G",type:"in",q:"A rectangular box has how many faces in total?",ans:6,
 expl:"A rectangular box always has 6 faces: top, bottom, and 4 sides."},
{lvl:2,sec:"G",type:"in",q:"A rectangular box is 2 by 3 by 4. What is its TOTAL surface area?",ans:52,
 hint:"Add up the areas of all 6 faces: two of each 2×3, 2×4, and 3×4.",
 expl:"2×(2×3) + 2×(2×4) + 2×(3×4) = 12 + 16 + 24 = 52."},
{lvl:2,sec:"G",type:"in",q:"A cube's total surface area is 150 square units. What is the area of ONE face?",ans:25,
 expl:"150 ÷ 6 = 25."},
{lvl:3,sec:"G",type:"in",q:"A cube's total surface area is 96. What is the length of one side?",ans:4,
 hint:"Find the area of one face first, then find its side.",
 expl:"One face is 96 ÷ 6 = 16 square units, and √16 = 4."}
],

"g6-statq": [
{sec:"S",type:"mc",q:"Which is a STATISTICAL question?",
 opts:["How old are the students in my class?","How old am I?","What is 5 + 5?","What color is my shirt?"],a:0,
 expl:"A statistical question expects a variety of answers across a group, like the ages of many students."},
{sec:"S",type:"mc",q:"Which question expects ONE fixed answer, and so is NOT statistical?",
 opts:["How many days are in January?","How tall are the trees in the park?","How much do the students in my class weigh?","How many pets do my friends have?"],a:0,
 expl:"January always has 31 days — there is no variability to measure."},
{sec:"S",type:"mc",q:"A statistical question is one that ___.",
 opts:["anticipates variability in the answers","always has the same answer","has no numbers","is about one single object"],a:0,
 expl:"Statistical questions expect the data to vary, which is what makes them worth studying."},
{sec:"S",type:"mc",q:"Which is a statistical question about a single student, Sam?",
 opts:["None of these — a group is needed for variability","How tall is Sam right now?","What is Sam's full name?","What grade is Sam currently in?"],a:0,
 expl:"A question about one fixed fact has no variability, so it is not statistical."},
{sec:"S",type:"mc",q:"Which of these is STATISTICAL?",
 opts:["What are the heights of the players on the team?","How many players are on the team?","What is the team's name?","Who is the coach?"],a:0,
 expl:"Heights vary player to player, giving a spread of data worth studying."},
{lvl:2,sec:"S",type:"mc",q:"Which rewrite turns the non-statistical question 'How old is my dog?' into a statistical one?",
 opts:["How old are the dogs in my neighborhood?","How old am I?","What breed is my dog?","Where is my dog?"],a:0,
 expl:"Asking about many dogs introduces variability, which is what makes it statistical."},
{lvl:2,sec:"S",type:"mc",q:"A survey asks a whole class 'What is your favorite color?' Why is this statistical?",
 opts:["Different students will give different answers","Everyone has the same favorite color","It has a numeric answer","It's about one person"],a:0,
 expl:"Because answers vary across the class, this is exactly the kind of variability a statistical question expects."},
{lvl:3,sec:"S",type:"mc",q:"Which question is BEST suited for a statistics project?",
 opts:["What is the range of test scores in my class?","What is 2 + 2?","What is my locker number?","What day is today?"],a:0,
 expl:"Test scores vary across the class, giving real data to analyze — the others each have one fixed answer."}
],

"g6-centervar": [
{sec:"S",type:"in",q:"Find the mean of 4, 6, 8. (Add them, then divide by 3.)",ans:6,
 expl:"(4 + 6 + 8) ÷ 3 = 18 ÷ 3 = 6."},
{sec:"S",type:"in",q:"Find the median of 3, 7, 5, 9, 1. (Order them first, then find the middle.)",ans:5,
 expl:"Ordered: 1, 3, 5, 7, 9. The middle value is 5."},
{sec:"S",type:"mc",q:"Which measure is the MIDDLE value when data is ordered?",
 opts:["Median","Mean","Range","Mode"],a:0,expl:"'Median' means the middle — the value with equal numbers of data points above and below."},
{sec:"S",type:"in",q:"Find the range of 2, 9, 4, 15, 7. (Largest minus smallest.)",ans:13,
 expl:"15 − 2 = 13."},
{sec:"S",type:"in",q:"Find the mode of 2, 3, 3, 5, 3, 7. (The most frequent value.)",ans:3,
 expl:"3 appears three times, more than any other value."},
{lvl:2,sec:"S",type:"in",q:"Find the mean of 10, 20, 30, 40.",ans:25,expl:"(10+20+30+40) ÷ 4 = 100 ÷ 4 = 25."},
{lvl:2,sec:"S",type:"mc",q:"A data set is 5, 5, 6, 8, 100. Which measure is LESS affected by the outlier, 100?",
 opts:["Median","Mean","Range","Sum"],a:0,
 expl:"The median (6) barely moves with one extreme value, while the mean gets pulled way up."},
{lvl:3,sec:"S",type:"in",q:"A data set has mean 20 across 5 values. One value is removed, and the mean of the remaining 4 is 18. What was the value removed?",
 ans:28,hint:"Find both totals first, then subtract.",
 expl:"Original total: 20 × 5 = 100. New total: 18 × 4 = 72. Removed value: 100 − 72 = 28."}
],

"g6-displays": [
{sec:"S",type:"mc",q:"Which display uses dots stacked above a number line to show frequency?",
 opts:["Dot plot","Pie chart","Bar chart of categories","Line graph"],a:0,
 expl:"A dot plot stacks one dot per data point above its value on a number line."},
{sec:"S",type:"mc",q:"A histogram groups data into ___.",
 opts:["ranges called bins","exact single values only","colors","random order"],a:0,
 expl:"A histogram groups numeric data into equal-width ranges, or bins."},
{sec:"S",type:"mc",q:"Which part of a box plot shows the median?",
 opts:["The line inside the box","The whiskers","The box's width","The dots outside"],a:0,
 expl:"The line dividing the box marks the median of the data."},
{sec:"S",type:"mc",q:"Which display is BEST for showing the SHAPE of a large data set, like heights of 100 people?",
 opts:["A histogram","A single dot plot with 100 separate dots","A pie chart","A single bar"],a:0,
 expl:"A histogram groups the data into bins, making patterns visible that 100 individual dots would not."},
{sec:"S",type:"mc",q:"In a box plot, the whiskers show ___.",
 opts:["the data's spread outside the middle 50%","only the average value","only the most common value","nothing meaningful at all"],a:0,
 expl:"The whiskers extend to the minimum and maximum, showing the data's full spread beyond the box."},
{lvl:2,sec:"S",type:"mc",q:"A dot plot shows most dots clustered near 20 with a few near 5. What does this tell you?",
 opts:["Most data values are close to 20","All data values are exactly 20","There is no pattern","The mean must be 5"],a:0,
 expl:"A cluster near 20 means most of the data sits close to that value."},
{lvl:2,sec:"S",type:"mc",q:"Which statistic does a box plot NOT directly show?",
 opts:["The exact mean","The median","The minimum","The maximum"],a:0,
 expl:"A box plot shows the five-number summary (min, quartiles, median, max) — the mean is not one of those marks."},
{lvl:3,sec:"S",type:"mc",q:"A histogram has bins of width 10: [0-10), [10-20), [20-30). 5 values fall in [10-20). What does that bar's HEIGHT represent?",
 opts:["The count of values in that range (5)","The value 15 itself","The width of the bin","The total of all bins"],a:0,
 expl:"A histogram's bar height shows how many data points fall in that bin, not any single value."}
]
};
