/* Grade 7 advanced / enrichment: number theory (modular powers, totient,
   Pythagorean triples, continued fractions, RSA), algebra (absolute value,
   systems, quadratics, graphs, exponentials), extended geometry (proofs,
   triangle centres, circle theorems, Heron, solids, coordinates),
   combinatorics (inclusion-exclusion, generating functions, partitions,
   graphs, Ramsey) and probability (Bayes, joint distributions, variance,
   named distributions, Markov chains). Competition style (AMC 8, MATHCOUNTS,
   Kangaroo); every numeric answer is an integer or exact decimal. */
export const G7_ADV_BANKS = {
"g7-modpow": [
{sec:"T",type:"in",q:"What is the remainder when 2^10 is divided by 7?",ans:2,
 hint:"Find a small power of 2 that leaves remainder 1.",
 expl:"2^3 = 8 ≡ 1 (mod 7), so 2^9 = (2^3)^3 ≡ 1 and 2^10 ≡ 2. The remainder is 2."},
{sec:"T",type:"in",q:"What is the remainder when 3^5 is divided by 11?",ans:1,
 expl:"3^5 = 243 = 22 × 11 + 1, so the remainder is 1."},
{sec:"T",type:"mc",q:"Which number is the inverse of 3 modulo 7 (that is, 3 × ? ≡ 1 mod 7)?",mono:true,
 opts:["5","3","4","2"],a:0,hint:"Multiply each option by 3 and look at the remainder mod 7.",
 expl:"3 × 5 = 15 = 2 × 7 + 1, so 3 × 5 ≡ 1 (mod 7). The inverse of 3 is 5."},
{lvl:2,sec:"T",type:"in",q:"What is the last digit of 7^100?",ans:1,
 hint:"The last digits of powers of 7 repeat in a cycle. Find its length.",
 expl:"Powers of 7 end in 7, 9, 3, 1, 7, 9, 3, 1, ... a cycle of length 4. Since 100 is a multiple of 4, 7^100 ends in 1."},
{lvl:2,sec:"T",type:"in",q:"Find the inverse of 7 modulo 26. Give the answer between 1 and 25.",ans:15,
 hint:"You want 7 × d to be one more than a multiple of 26.",
 expl:"7 × 15 = 105 = 4 × 26 + 1, so 7 × 15 ≡ 1 (mod 26). The inverse is 15."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number that has an inverse modulo 12.",mono:true,
 opts:["5","7","8","9"],aMulti:[0,1],hint:"A number has an inverse mod n exactly when it shares no factor with n.",
 expl:"An inverse exists only when the number is coprime to 12. gcd(5,12) = gcd(7,12) = 1, but 8 and 9 share factors 4 and 3 with 12. So 5 and 7."},
{lvl:3,sec:"T",type:"in",q:"What is the remainder when 5^123 is divided by 13?",ans:8,
 hint:"Compute 5^2 mod 13 first; it is one less than a multiple of 13.",
 expl:"5^2 = 25 ≡ −1 (mod 13), so 5^4 ≡ 1. Since 123 = 4 × 30 + 3, 5^123 ≡ 5^3 = 125 = 9 × 13 + 8. The remainder is 8."},
{lvl:3,sec:"T",type:"in",q:"Solve 4x ≡ 3 (mod 9). Give the solution x with 0 ≤ x ≤ 8.",ans:3,
 hint:"First find the inverse of 4 mod 9, then multiply both sides by it.",
 expl:"4 × 7 = 28 ≡ 1 (mod 9), so the inverse of 4 is 7. Then x ≡ 7 × 3 = 21 ≡ 3 (mod 9). Check: 4 × 3 = 12 ≡ 3. So x = 3."}
],

"g7-euler": [
{sec:"T",type:"in",q:"Euler's totient φ(n) counts the numbers from 1 to n that are coprime to n. What is φ(10)?",ans:4,
 hint:"List the numbers from 1 to 10 that share no factor with 10.",
 expl:"The numbers coprime to 10 are 1, 3, 7 and 9, so φ(10) = 4."},
{sec:"T",type:"in",q:"What is φ(12)?",ans:4,
 expl:"The numbers up to 12 sharing no factor with 12 are 1, 5, 7 and 11, so φ(12) = 4."},
{sec:"T",type:"mc",q:"Fermat's little theorem says that for a prime p and a number a not divisible by p:",mono:true,
 opts:["a^(p−1) ≡ 1 (mod p)","a^p ≡ 1 (mod p)","a^(p+1) ≡ a (mod p)","a^(p−1) ≡ 0 (mod p)"],a:0,
 expl:"Fermat's little theorem: a^(p−1) ≡ 1 (mod p) whenever p is prime and p does not divide a. For example 2^6 = 64 ≡ 1 (mod 7)."},
{lvl:2,sec:"T",type:"in",q:"Use the formula φ(n) = n × (1 − 1/p) × (1 − 1/q) × ... over the distinct primes of n to find φ(36).",ans:12,
 hint:"36 = 2² × 3², so only the primes 2 and 3 matter.",
 expl:"φ(36) = 36 × (1/2) × (2/3) = 12."},
{lvl:2,sec:"T",type:"in",q:"What is the remainder when 2^100 is divided by 11?",ans:1,
 hint:"11 is prime, so use Fermat's little theorem with exponent 10.",
 expl:"By Fermat, 2^10 ≡ 1 (mod 11). Then 2^100 = (2^10)^10 ≡ 1^10 = 1. The remainder is 1."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY value of n for which φ(n) = n − 1.",mono:true,
 opts:["7","9","13","15"],aMulti:[0,2],hint:"When is every number below n coprime to n?",
 expl:"φ(n) = n − 1 exactly when n is prime, because then every smaller positive number is coprime to n. 7 and 13 are prime; 9 = 3² and 15 = 3 × 5 are not."},
{lvl:3,sec:"T",type:"in",q:"Euler's theorem says a^φ(n) ≡ 1 (mod n) when gcd(a, n) = 1. What is the remainder when 3^1000 is divided by 100?",ans:1,
 hint:"Work out φ(100) first and see how many times it divides 1000.",
 expl:"φ(100) = 100 × (1/2) × (4/5) = 40, and 1000 = 25 × 40. So 3^1000 = (3^40)^25 ≡ 1 (mod 100). The remainder is 1."},
{lvl:3,sec:"T",type:"in",q:"What is the smallest integer n > 1 with φ(n) = 8?",ans:15,
 hint:"Check the totients of 9, 10, 11, ... one at a time.",
 expl:"φ(9) = 6, φ(10) = 4, φ(11) = 10, φ(12) = 4, φ(13) = 12, φ(14) = 6 and φ(15) = φ(3) × φ(5) = 2 × 4 = 8. So n = 15."}
],

"g7-triples": [
{sec:"T",type:"in",q:"A right triangle has legs 5 and 12. What is the hypotenuse?",ans:13,
 expl:"5² + 12² = 25 + 144 = 169 = 13², so the hypotenuse is 13."},
{sec:"T",type:"mc",q:"Which of these is a Pythagorean triple?",mono:true,
 opts:["(7, 24, 25)","(4, 5, 6)","(6, 7, 8)","(5, 10, 15)"],a:0,
 hint:"Check whether the two smaller squares add to the largest square.",
 expl:"7² + 24² = 49 + 576 = 625 = 25², so (7, 24, 25) is a Pythagorean triple. The others fail: for example 4² + 5² = 41 ≠ 36."},
{sec:"T",type:"in",q:"The triple (8, 15, c) is a Pythagorean triple. Find c.",ans:17,
 expl:"8² + 15² = 64 + 225 = 289 = 17², so c = 17."},
{lvl:2,sec:"T",type:"in",q:"Euclid's formula makes a triple from integers m > n: a = m² − n², b = 2mn, c = m² + n². What is c when m = 5 and n = 2?",ans:29,
 hint:"Just substitute into c = m² + n².",
 expl:"c = 5² + 2² = 25 + 4 = 29. (The full triple is (21, 20, 29), and 21² + 20² = 441 + 400 = 841 = 29².)"},
{lvl:2,sec:"T",type:"multi",q:"A triple is primitive if the three numbers share no common factor. Select EVERY primitive triple.",mono:true,
 opts:["(3, 4, 5)","(6, 8, 10)","(20, 21, 29)","(9, 12, 15)"],aMulti:[0,2],
 hint:"Look for a common factor of all three numbers.",
 expl:"(6, 8, 10) = 2 × (3, 4, 5) and (9, 12, 15) = 3 × (3, 4, 5) share a factor. (3, 4, 5) and (20, 21, 29) have no common factor, so they are primitive."},
{lvl:2,sec:"T",type:"in",q:"A right triangle has integer sides and hypotenuse 25, but its legs are not 15 and 20. What is its shorter leg?",ans:7,
 hint:"Find another way to write 625 as a sum of two squares.",
 expl:"625 = 49 + 576 = 7² + 24², so the triangle is (7, 24, 25) and the shorter leg is 7."},
{lvl:3,sec:"T",type:"in",q:"How many primitive Pythagorean triples have hypotenuse less than 30?",ans:5,
 hint:"Use c = m² + n² with m > n coprime and not both odd. List the possible (m, n).",
 expl:"(m, n) = (2,1), (3,2), (4,1), (4,3), (5,2) give c = 5, 13, 17, 25, 29; the next, (5,4) and (6,1), give 41 and 37. So there are 5: (3,4,5), (5,12,13), (8,15,17), (7,24,25), (20,21,29)."},
{lvl:3,sec:"T",type:"in",q:"A right triangle with integer sides has one leg equal to 11. What is its hypotenuse?",ans:61,
 hint:"Write 11² = c² − b² = (c − b)(c + b). Since 11 is prime, there is only one way to split 121.",
 expl:"11² = 121 = (c − b)(c + b). The only factor pair is 1 × 121, so c − b = 1 and c + b = 121, giving c = 61 and b = 60. Check: 11² + 60² = 121 + 3600 = 3721 = 61²."},
{lvl:3,sec:"T",type:"mc",q:"For every Pythagorean triple (a, b, c), the product a × b × c is always divisible by which number?",mono:true,
 opts:["60","30","24","100"],a:0,hint:"Test the smallest triple (3, 4, 5). Then check that no larger claim can hold.",
 expl:"One leg is always a multiple of 3, one side a multiple of 4, and one side a multiple of 5, so abc is divisible by 3 × 4 × 5 = 60. The triple (3, 4, 5) has product exactly 60, so nothing larger works."}
],

"g7-contfrac": [
{sec:"T",type:"in",q:"The continued fraction [1; 4] means 1 + 1/4. Write it as a decimal.",ans:1.25,
 expl:"1 + 1/4 = 1.25."},
{sec:"T",type:"mc",q:"Which continued fraction equals 7/3?",mono:true,
 opts:["[2; 3]","[3; 2]","[2; 1, 3]","[1; 2, 3]"],a:0,hint:"Split 7/3 into a whole part plus a fraction less than 1.",
 expl:"7/3 = 2 + 1/3, so 7/3 = [2; 3]."},
{sec:"T",type:"in",q:"The continued fraction of 17/5 is [3; 2, x]. What is x?",ans:2,
 hint:"17/5 = 3 + 2/5, and 2/5 = 1/(5/2). Keep going.",
 expl:"17/5 = 3 + 2/5 = 3 + 1/(5/2) = 3 + 1/(2 + 1/2), so 17/5 = [3; 2, 2] and x = 2."},
{lvl:2,sec:"T",type:"in",q:"√2 = [1; 2, 2, 2, ...]. Its convergents are 1, 3/2, 7/5, 17/12, ... Write the third convergent 7/5 as a decimal.",ans:1.4,
 expl:"7/5 = 1.4, already close to √2 ≈ 1.4142."},
{lvl:2,sec:"T",type:"mc",q:"The infinite continued fraction [1; 1, 1, 1, ...] equals which number?",mono:true,
 opts:["(1 + √5)/2","√2","3/2","2"],a:0,hint:"Call it x. Then x = 1 + 1/x. Solve that equation.",
 expl:"If x = [1; 1, 1, ...] then x = 1 + 1/x, so x² − x − 1 = 0 and x = (1 + √5)/2, the golden ratio."},
{lvl:2,sec:"T",type:"in",q:"Evaluate [0; 1, 4] = 0 + 1/(1 + 1/4) as a decimal.",ans:0.8,
 hint:"Work from the inside out: first 1 + 1/4.",
 expl:"1 + 1/4 = 5/4, and 1/(5/4) = 4/5 = 0.8."},
{lvl:3,sec:"T",type:"in",q:"π = [3; 7, 15, 1, 292, ...]. The convergent [3; 7] is 22/7. What is the numerator of the next convergent, [3; 7, 15]?",ans:333,
 hint:"Compute 3 + 1/(7 + 1/15) as a single fraction.",
 expl:"7 + 1/15 = 106/15, so [3; 7, 15] = 3 + 15/106 = 333/106. The numerator is 333."},
{lvl:3,sec:"T",type:"in",q:"e = [2; 1, 2, 1, 1, 4, ...]. Using the rule q_n = a_n × q_(n−1) + q_(n−2), what is the denominator of the convergent [2; 1, 2, 1, 1]?",ans:7,
 hint:"Start the denominators with 1 for [2], then 1 for [2; 1], and apply the rule three more times.",
 expl:"Denominators: 1, 1, then 2 × 1 + 1 = 3, then 1 × 3 + 1 = 4, then 1 × 4 + 3 = 7. The convergent is 19/7 ≈ 2.714, and its denominator is 7."},
{lvl:3,sec:"T",type:"order",q:"The convergents of √2 alternate above and below it. Put these in order from smallest to largest.",
 items:["3/2","7/5","17/12","√2"],ansOrder:["7/5","√2","17/12","3/2"],
 hint:"3/2 = 1.5, 7/5 = 1.4, 17/12 ≈ 1.4167 and √2 ≈ 1.4142.",
 expl:"7/5 = 1.4 is below √2 ≈ 1.4142, while 17/12 ≈ 1.4167 and 3/2 = 1.5 are above it. Smallest to largest: 7/5, √2, 17/12, 3/2."}
],

"g7-rsa": [
{sec:"T",type:"mc",q:"In RSA, what does the public key consist of?",
 opts:["The modulus n and the exponent e","The two primes p and q","The private exponent d","The value of φ(n)"],a:0,
 expl:"The public key is the pair (n, e). The primes p, q, the totient φ(n) and the private exponent d must all stay secret."},
{sec:"T",type:"in",q:"Nadia picks the primes p = 3 and q = 11 for a tiny RSA key. What is her modulus n?",ans:33,
 expl:"n = p × q = 3 × 11 = 33."},
{sec:"T",type:"in",q:"For primes p = 5 and q = 11, RSA needs φ(n) = (p − 1)(q − 1). What is φ(n)?",ans:40,
 expl:"φ(n) = (5 − 1)(11 − 1) = 4 × 10 = 40."},
{lvl:2,sec:"T",type:"in",q:"With n = 33 and φ(n) = 20, the public exponent is e = 3. The private exponent d satisfies 3d ≡ 1 (mod 20). Find d with 1 ≤ d < 20.",ans:7,
 hint:"Try multiples of 3 until one is one more than a multiple of 20.",
 expl:"3 × 7 = 21 = 20 + 1, so d = 7."},
{lvl:2,sec:"T",type:"in",q:"Encrypt the message m = 4 using the public key n = 33, e = 3: compute c = m^e mod n.",ans:31,
 hint:"Find 4³ and take its remainder on division by 33.",
 expl:"4³ = 64 = 33 + 31, so c = 31."},
{lvl:2,sec:"T",type:"multi",q:"φ(n) = 20. Select EVERY value that is a valid public exponent e (it must be coprime to φ(n)).",mono:true,
 opts:["3","5","7","9"],aMulti:[0,2,3],hint:"Find the gcd of each option with 20.",
 expl:"gcd(3,20) = gcd(7,20) = gcd(9,20) = 1, so 3, 7 and 9 work. 5 divides 20, so it cannot be used."},
{lvl:3,sec:"T",type:"in",q:"A message was encrypted with n = 55, e = 3 and the ciphertext is c = 13. Find the original message m (0 ≤ m < 55).",ans:7,
 hint:"Either compute d from φ(55) = 40, or test small m to find one with m³ ≡ 13 (mod 55).",
 expl:"φ(55) = 4 × 10 = 40 and 3 × 27 = 81 ≡ 1 (mod 40), so d = 27 and m = 13^27 mod 55. Checking directly: 7³ = 343 = 6 × 55 + 13, so m = 7."},
{lvl:3,sec:"T",type:"in",q:"Elias sees the public key n = 91, e = 5. He factorises n, finds φ(n), and computes the private exponent d with 5d ≡ 1 (mod φ(n)). What is d (1 ≤ d < φ(n))?",ans:29,
 hint:"91 = 7 × 13. Then φ(n) = 6 × 12.",
 expl:"91 = 7 × 13, so φ(n) = 6 × 12 = 72. We need 5d ≡ 1 (mod 72): 5 × 29 = 145 = 2 × 72 + 1, so d = 29."},
{lvl:3,sec:"T",type:"mc",q:"Why is RSA considered secure when n is a few hundred digits long?",
 opts:["Splitting such an n into its primes p × q takes far too long","Computing m^e mod n is impossible for large n","The public key is kept secret from attackers","φ(n) does not exist when n is very large"],a:0,
 expl:"Anyone can multiply p and q to get n, but recovering p and q from a huge n (factorising) has no known fast method. Without p and q, an attacker cannot find φ(n) or d."}
],

"g7-absval": [
{sec:"L",type:"in",q:"Solve |x − 3| = 5. Enter the larger solution.",ans:8,
 hint:"x − 3 could be 5 or −5.",
 expl:"x − 3 = 5 gives x = 8, and x − 3 = −5 gives x = −2. The larger solution is 8."},
{sec:"L",type:"mc",q:"What are the solutions of |x| = 4?",mono:true,
 opts:["x = 4 or x = −4","x = 4 only","x = −4 only","No solution"],a:0,
 expl:"|x| = 4 means x is 4 units from 0, so x = 4 or x = −4."},
{sec:"L",type:"in",q:"Solve |2x + 1| = 7. Enter the negative solution.",ans:-4,
 hint:"Set 2x + 1 equal to −7.",
 expl:"2x + 1 = −7 gives 2x = −8, so x = −4. (The other solution, from 2x + 1 = 7, is x = 3.)"},
{lvl:2,sec:"L",type:"in",q:"Solve |x − 2| = |x − 8|.",ans:5,
 hint:"Which number is the same distance from 2 and from 8?",
 expl:"|x − 2| = |x − 8| means x is equally far from 2 and 8, so x is their midpoint, 5."},
{lvl:2,sec:"L",type:"mc",q:"How many solutions does |x + 3| = −2 have?",
 opts:["None","One","Two","Infinitely many"],a:0,
 expl:"An absolute value is never negative, so |x + 3| = −2 has no solutions."},
{lvl:2,sec:"L",type:"in",q:"What is the sum of the solutions of |3x − 6| = 9?",ans:4,
 hint:"Solve 3x − 6 = 9 and 3x − 6 = −9 separately.",
 expl:"3x − 6 = 9 gives x = 5; 3x − 6 = −9 gives x = −1. The sum is 5 + (−1) = 4."},
{lvl:3,sec:"L",type:"in",q:"Solve |x − 1| + |x − 5| = 10. Enter the product of the two solutions.",ans:-16,
 hint:"For x above 5 both expressions are positive; for x below 1 both are negative. Between them the sum is a constant 4.",
 expl:"For x > 5: (x − 1) + (x − 5) = 2x − 6 = 10, so x = 8. For x < 1: (1 − x) + (5 − x) = 6 − 2x = 10, so x = −2. The product is 8 × (−2) = −16."},
{lvl:3,sec:"L",type:"in",q:"How many integers x satisfy |x − 4| ≤ 3?",ans:7,
 hint:"Think of the integers within distance 3 of 4.",
 expl:"|x − 4| ≤ 3 means 1 ≤ x ≤ 7, which contains the 7 integers 1, 2, 3, 4, 5, 6, 7."},
{lvl:3,sec:"L",type:"multi",q:"Select EVERY equation that has exactly one solution.",mono:true,
 opts:["|x − 2| = 0","|x| = 3","|x + 1| = −1","|2x − 4| = 0"],aMulti:[0,3],
 hint:"An absolute value equal to 0 pins down one value; a positive value gives two; a negative value gives none.",
 expl:"|x − 2| = 0 forces x = 2 and |2x − 4| = 0 forces x = 2: one solution each. |x| = 3 has two solutions and |x + 1| = −1 has none."}
],

"g7-systems": [
{sec:"L",type:"in",q:"Solve the system x + y = 10 and x − y = 4. What is x?",ans:7,
 hint:"Add the two equations together.",
 expl:"Adding gives 2x = 14, so x = 7 (and y = 3)."},
{sec:"L",type:"in",q:"If 2x + y = 11 and x = 3, what is y?",ans:5,
 expl:"Substitute x = 3: 6 + y = 11, so y = 5."},
{sec:"L",type:"mc",q:"Which pair of equations has NO solution?",mono:true,
 opts:["y = 2x + 1 and y = 2x − 3","y = 2x + 1 and y = 3x + 1","y = x and y = −x","x + y = 4 and 2x + 2y = 8"],a:0,
 hint:"Parallel lines never meet.",
 expl:"y = 2x + 1 and y = 2x − 3 have the same slope and different intercepts: parallel lines with no common point. The last pair is the same line twice (infinitely many solutions)."},
{lvl:2,sec:"L",type:"in",q:"Solve 3x + 2y = 16 and x − 2y = 0. What is the product xy?",ans:8,
 hint:"Adding the equations eliminates y.",
 expl:"Adding: 4x = 16, so x = 4. Then 4 − 2y = 0 gives y = 2, and xy = 8."},
{lvl:2,sec:"L",type:"in",q:"Three variables: x + y + z = 12, x + y = 7 and y + z = 9. What is y?",ans:4,
 hint:"Compare the first equation with each of the others to find z and x.",
 expl:"From the first two equations z = 12 − 7 = 5. Then y = 9 − 5 = 4 (and x = 3)."},
{lvl:2,sec:"L",type:"in",q:"Priya buys 3 pens and 2 notebooks for $13. Wei buys 1 pen and 2 notebooks for $9. What is the price of one notebook in dollars?",ans:3.5,
 hint:"Subtract the second purchase from the first to find the cost of 2 pens.",
 expl:"Subtracting: 2 pens cost $4, so a pen is $2. Then 2 + 2n = 9 gives 2n = 7, so a notebook costs $3.50."},
{lvl:3,sec:"L",type:"in",q:"x + y = 5, y + z = 7 and x + z = 8. What is the product xyz?",ans:30,
 hint:"Add all three equations to find x + y + z first.",
 expl:"Adding gives 2(x + y + z) = 20, so x + y + z = 10. Then z = 10 − 5 = 5, x = 10 − 7 = 3, y = 10 − 8 = 2, and xyz = 30."},
{lvl:3,sec:"L",type:"in",q:"Amara is twice as old as Kenji. In 6 years the sum of their ages will be 42. How old is Amara now?",ans:20,
 hint:"Let Kenji be k years old, so Amara is 2k. Write an equation for the ages in 6 years.",
 expl:"(2k + 6) + (k + 6) = 42 gives 3k + 12 = 42, so k = 10. Amara is 2 × 10 = 20."},
{lvl:3,sec:"L",type:"mc",q:"How many solutions does the system x + y + z = 6, 2x + 2y + 2z = 12 have?",
 opts:["Infinitely many","Exactly one","None","Exactly two"],a:0,
 hint:"Divide the second equation by 2.",
 expl:"The second equation is just the first multiplied by 2, so there is really only one equation in three unknowns. Any (x, y, z) with x + y + z = 6 works: infinitely many solutions."}
],

"g7-factorquad": [
{sec:"L",type:"mc",q:"Factorise x² + 5x + 6.",mono:true,
 opts:["(x + 2)(x + 3)","(x + 1)(x + 6)","(x − 2)(x − 3)","(x + 5)(x + 1)"],a:0,
 hint:"Find two numbers that multiply to 6 and add to 5.",
 expl:"2 × 3 = 6 and 2 + 3 = 5, so x² + 5x + 6 = (x + 2)(x + 3)."},
{sec:"L",type:"in",q:"x² + 7x + 12 = (x + 3)(x + p). What is p?",ans:4,
 expl:"We need 3 × p = 12 and 3 + p = 7, so p = 4."},
{sec:"L",type:"mc",q:"Factorise x² − 9.",mono:true,
 opts:["(x − 3)(x + 3)","(x − 3)²","(x + 3)²","(x − 9)(x + 1)"],a:0,
 hint:"This is a difference of two squares.",
 expl:"x² − 9 = x² − 3² = (x − 3)(x + 3)."},
{lvl:2,sec:"L",type:"in",q:"x² − 5x − 14 = (x − 7)(x + q). What is q?",ans:2,
 hint:"The two numbers must multiply to −14 and add to −5.",
 expl:"−7 × 2 = −14 and −7 + 2 = −5, so q = 2."},
{lvl:2,sec:"L",type:"mc",q:"Factorise 2x² + 7x + 3.",mono:true,
 opts:["(2x + 1)(x + 3)","(2x + 3)(x + 1)","(2x − 1)(x − 3)","(x + 1)(x + 3)"],a:0,
 hint:"Expand each option and compare the x term.",
 expl:"(2x + 1)(x + 3) = 2x² + 6x + x + 3 = 2x² + 7x + 3."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY expression that is a perfect square trinomial.",mono:true,
 opts:["x² + 6x + 9","x² − 4x + 4","x² + 2x + 4","x² + 8x + 12"],aMulti:[0,1],
 hint:"A perfect square looks like (x + a)² = x² + 2ax + a².",
 expl:"x² + 6x + 9 = (x + 3)² and x² − 4x + 4 = (x − 2)². In x² + 2x + 4 the constant would need to be 1, and x² + 8x + 12 would need 16."},
{lvl:3,sec:"L",type:"in",q:"For how many positive integers b can x² + bx + 24 be factorised into two factors with integer coefficients?",ans:4,
 hint:"b must be the sum of a pair of positive factors of 24.",
 expl:"The factor pairs of 24 are 1 × 24, 2 × 12, 3 × 8 and 4 × 6, giving b = 25, 14, 11 and 10. So there are 4 values."},
{lvl:3,sec:"L",type:"in",q:"Factorise x⁴ − 5x² + 4 completely. What is the largest value of x that makes the expression equal to 0?",ans:2,
 hint:"Treat x² as the variable first: it factorises like a quadratic in x².",
 expl:"x⁴ − 5x² + 4 = (x² − 1)(x² − 4) = (x − 1)(x + 1)(x − 2)(x + 2). The zeros are ±1 and ±2, so the largest is 2."},
{lvl:3,sec:"L",type:"in",q:"6x² − 11x − 10 = (2x − 5)(ax + b) for integers a and b. What is a + b?",ans:5,
 hint:"Match the x² coefficient to find a, then the constant to find b.",
 expl:"2x × ax = 6x² gives a = 3, and −5 × b = −10 gives b = 2. Check: (2x − 5)(3x + 2) = 6x² + 4x − 15x − 10 = 6x² − 11x − 10. So a + b = 5."}
],

"g7-solvequad": [
{sec:"L",type:"in",q:"Solve x² = 49. Enter the positive solution.",ans:7,
 expl:"7² = 49 and (−7)² = 49, so the positive solution is 7."},
{sec:"L",type:"in",q:"Solve x² − 5x + 6 = 0. Enter the larger solution.",ans:3,
 hint:"Factorise: which two numbers multiply to 6 and add to 5?",
 expl:"x² − 5x + 6 = (x − 2)(x − 3) = 0, so x = 2 or x = 3. The larger is 3."},
{sec:"L",type:"mc",q:"What are the solutions of x² + x − 12 = 0?",mono:true,
 opts:["x = 3 or x = −4","x = −3 or x = 4","x = 3 or x = 4","x = −3 or x = −4"],a:0,
 expl:"x² + x − 12 = (x + 4)(x − 3), so x = −4 or x = 3."},
{lvl:2,sec:"L",type:"in",q:"x² − 6x + 9 = 0 has one repeated solution. What is it?",ans:3,
 hint:"The left side is a perfect square.",
 expl:"x² − 6x + 9 = (x − 3)², so the only solution is x = 3."},
{lvl:2,sec:"L",type:"in",q:"Without solving, find the product of the two solutions of x² + 3x − 10 = 0.",ans:-10,
 hint:"For x² + bx + c = 0, the product of the roots equals c.",
 expl:"For x² + bx + c = 0 the roots multiply to c, so the product is −10. (Indeed the roots are 2 and −5.)"},
{lvl:2,sec:"L",type:"mc",q:"How many real solutions does x² + 2x + 5 = 0 have?",
 opts:["None","One","Two","Infinitely many"],a:0,
 hint:"Compute the discriminant b² − 4ac.",
 expl:"The discriminant is 2² − 4 × 1 × 5 = 4 − 20 = −16, which is negative, so there are no real solutions."},
{lvl:2,sec:"L",type:"in",q:"Complete the square to solve x² + 8x = 20. Enter the positive solution.",ans:2,
 hint:"Add 16 to both sides.",
 expl:"x² + 8x + 16 = 36, so (x + 4)² = 36 and x + 4 = ±6. That gives x = 2 or x = −10; the positive one is 2."},
{lvl:3,sec:"L",type:"in",q:"A rectangle is 3 cm longer than it is wide and has area 40 cm². What is its width in cm?",ans:5,
 hint:"Let the width be w and write the area as w(w + 3).",
 expl:"w(w + 3) = 40 gives w² + 3w − 40 = 0 = (w + 8)(w − 5). Since w must be positive, the width is 5 cm."},
{lvl:3,sec:"L",type:"in",q:"Solve 2x² − 3x − 5 = 0. Enter the larger solution as a decimal.",ans:2.5,
 hint:"Try factorising as (2x + ?)(x + ?), or use the quadratic formula with a = 2, b = −3, c = −5.",
 expl:"2x² − 3x − 5 = (2x − 5)(x + 1), so x = 5/2 or x = −1. The larger solution is 2.5."},
{lvl:3,sec:"L",type:"in",q:"Sofia throws a ball whose height after t seconds is h = 20t − 5t² metres. After how many seconds does it hit the ground (h = 0, t > 0)?",ans:4,
 hint:"Factor out 5t.",
 expl:"20t − 5t² = 5t(4 − t) = 0, so t = 0 (the throw) or t = 4. The ball lands after 4 seconds."}
],

"g7-graphquad": [
{sec:"L",type:"in",q:"What is the y-intercept of the line y = 2x + 3?",ans:3,
 expl:"At x = 0, y = 3, so the y-intercept is 3."},
{sec:"L",type:"pair",q:"What is the vertex of the parabola y = (x − 2)² + 1? Give it as a coordinate pair.",ansP:[2,1],
 hint:"In vertex form y = (x − h)² + k, the vertex is (h, k).",
 expl:"The form y = (x − h)² + k has vertex (h, k), so the vertex is (2, 1)."},
{sec:"L",type:"mc",q:"Which way does the parabola y = −x² + 4 open?",
 opts:["Downward","Upward","To the left","To the right"],a:0,
 expl:"The coefficient of x² is negative, so the parabola opens downward with its highest point at (0, 4)."},
{lvl:2,sec:"L",type:"in",q:"What is the x-coordinate of the vertex of y = x² − 4x + 3?",ans:2,
 hint:"The vertex has x = −b/(2a).",
 expl:"x = −b/(2a) = 4/2 = 2. (The vertex is (2, −1).)"},
{lvl:2,sec:"L",type:"pair",q:"Find the vertex of y = x² − 6x + 5 as a coordinate pair.",ansP:[3,-4],
 hint:"Find the x-coordinate with −b/(2a), then substitute it back.",
 expl:"x = 6/2 = 3, and y = 9 − 18 + 5 = −4. The vertex is (3, −4)."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY point that lies on the line y = 3x − 1.",mono:true,
 opts:["(2, 5)","(0, −1)","(1, 3)","(−1, −4)"],aMulti:[0,1,3],
 hint:"Substitute each x-value and see whether you get the y-value.",
 expl:"3(2) − 1 = 5, 3(0) − 1 = −1 and 3(−1) − 1 = −4 all match. But 3(1) − 1 = 2, not 3, so (1, 3) is off the line."},
{lvl:3,sec:"L",type:"in",q:"The parabola y = x² and the line y = x + 2 cross at two points. What is the larger x-coordinate of a crossing point?",ans:2,
 hint:"Set x² = x + 2 and solve.",
 expl:"x² − x − 2 = 0 = (x − 2)(x + 1), so the crossings are at x = 2 and x = −1. The larger is 2."},
{lvl:3,sec:"L",type:"in",q:"How far apart are the two x-intercepts of y = x² − 2x − 8?",ans:6,
 hint:"Factorise to find where y = 0.",
 expl:"x² − 2x − 8 = (x − 4)(x + 2), so the intercepts are at x = 4 and x = −2, a distance 4 − (−2) = 6 apart."},
{lvl:3,sec:"L",type:"in",q:"What is the maximum value of y on the graph of y = −2(x + 1)² + 5?",ans:5,
 hint:"The squared term is never negative; what happens when it is zero?",
 expl:"−2(x + 1)² is at most 0, reached at x = −1. So the maximum value of y is 5, at the vertex (−1, 5)."}
],

"g7-exponen": [
{sec:"L",type:"in",q:"A colony of 5 bacteria doubles every hour. How many bacteria are there after 4 hours?",ans:80,
 expl:"5 × 2⁴ = 5 × 16 = 80 bacteria."},
{sec:"L",type:"in",q:"Yusuf puts $1000 in an account that grows 10% each year. How many dollars does he have after 2 years?",ans:1210,
 hint:"Multiply by 1.1 for each year.",
 expl:"1000 × 1.1 × 1.1 = 1000 × 1.21 = $1210."},
{sec:"L",type:"mc",q:"The formula y = 200 × (0.8)^t describes which kind of change?",
 opts:["Decay of 20% each step","Growth of 80% each step","Decay of 80% each step","Growth of 20% each step"],a:0,
 expl:"Multiplying by 0.8 keeps 80% of the amount, so 20% is lost each step: a 20% decay."},
{lvl:2,sec:"L",type:"in",q:"A substance has a half-life of 3 days. Starting from 160 g, how many grams remain after 12 days?",ans:10,
 hint:"How many half-lives fit in 12 days?",
 expl:"12 days is 4 half-lives, so 160 → 80 → 40 → 20 → 10. There are 10 g left."},
{lvl:2,sec:"L",type:"in",q:"A town of 4000 people grows by 5% per year. What is its population after 2 years?",ans:4410,
 hint:"Multiply by 1.05 twice.",
 expl:"4000 × 1.05 = 4200, and 4200 × 1.05 = 4410."},
{lvl:2,sec:"L",type:"in",q:"A number starts at 3 and doubles repeatedly. How many doublings does it take to reach 3072?",ans:10,
 hint:"Divide 3072 by 3 and write the result as a power of 2.",
 expl:"3072 ÷ 3 = 1024 = 2^10, so it takes 10 doublings."},
{lvl:3,sec:"L",type:"in",q:"A car bought for $20 000 loses 25% of its value every year. What is it worth in dollars after 3 years?",ans:8437.5,
 hint:"Each year it keeps 75% of its value.",
 expl:"20000 × 0.75³ = 20000 × 0.421875 = $8437.50."},
{lvl:3,sec:"L",type:"mc",q:"For very large x, which of these grows the fastest?",mono:true,
 opts:["y = 2^x","y = x³","y = 100x","y = x²"],a:0,
 hint:"Compare the values at x = 20 or x = 30.",
 expl:"Exponential growth beats every polynomial eventually. At x = 30, 2^30 is over a billion, while 30³ = 27 000 and 100 × 30 = 3000."},
{lvl:3,sec:"L",type:"in",q:"A population of 50 insects triples every 4 hours. After how many hours will it reach 4050?",ans:16,
 hint:"First find how many triplings are needed: 4050 ÷ 50 is a power of 3.",
 expl:"4050 ÷ 50 = 81 = 3⁴, so 4 triplings are needed, taking 4 × 4 = 16 hours."}
],

"g7-proofs": [
{sec:"P",type:"mc",q:"Which of these is NOT a valid rule for proving two triangles congruent?",
 opts:["SSA","SSS","SAS","ASA"],a:0,
 hint:"One of these can match two different triangles.",
 expl:"SSA (two sides and a non-included angle) can be satisfied by two different triangles, so it does not prove congruence. SSS, SAS and ASA do."},
{sec:"P",type:"mc",q:"Two triangles have two pairs of equal angles. What can you conclude?",
 opts:["They are similar","They are congruent","They are right-angled","They are isosceles"],a:0,
 expl:"Two equal angle pairs force the third pair to be equal too (angles sum to 180°), so the triangles are similar (AA). They need not be the same size."},
{sec:"P",type:"mc",q:"One triangle has sides 3, 4, 5 and another has sides 6, 8, 10. How are they related?",
 opts:["Similar with scale factor 2","Congruent","Not similar","Similar with scale factor 3"],a:0,
 expl:"Each side of the second is exactly 2 times the matching side of the first, so they are similar with scale factor 2 (SSS similarity)."},
{lvl:2,sec:"P",type:"in",q:"Triangle ABC is similar to triangle DEF with AB = 4, DE = 10 and BC = 6. What is EF?",ans:15,
 hint:"Find the scale factor from AB to DE.",
 expl:"The scale factor is 10 ÷ 4 = 2.5, so EF = 6 × 2.5 = 15."},
{lvl:2,sec:"P",type:"order",q:"Put the steps of this proof in order from first to last. Claim: in triangle ABC with AB = AC, angle B = angle C.",
 items:["Draw the bisector of angle A, meeting BC at M","AB = AC (given), AM is common, and angle BAM = angle CAM","Triangles ABM and ACM are congruent (SAS)","So angle B = angle C (matching parts of congruent triangles)"],
 ansOrder:["Draw the bisector of angle A, meeting BC at M","AB = AC (given), AM is common, and angle BAM = angle CAM","Triangles ABM and ACM are congruent (SAS)","So angle B = angle C (matching parts of congruent triangles)"],
 hint:"A proof starts with a construction, lists what is equal, applies a congruence rule, then draws the conclusion.",
 expl:"First construct the bisector, then list the three equal pairs (side, angle, side), then apply SAS to get congruence, and finally read off that angle B = angle C."},
{lvl:2,sec:"P",type:"mc",q:"After proving two triangles congruent, the statement 'matching parts of congruent triangles are equal' lets you conclude that:",
 opts:["Any pair of matching sides or angles are equal","The two triangles are also similar","Only the areas of the two triangles are equal","Both triangles are right-angled"],a:0,
 expl:"Congruent triangles are identical copies, so every matching side and every matching angle is equal. That is how a congruence proof produces new equal lengths or angles."},
{lvl:3,sec:"P",type:"in",q:"At the same moment, Lior (1.8 m tall) casts a 3 m shadow and a tree casts a 25 m shadow. Using similar triangles, how tall is the tree in metres?",ans:15,
 hint:"The two right triangles (object, shadow, sun ray) are similar because the sun's rays are parallel.",
 expl:"The triangles are similar, so height ÷ shadow is the same: 1.8 ÷ 3 = 0.6. The tree is 0.6 × 25 = 15 m tall."},
{lvl:3,sec:"P",type:"mc",q:"In parallelogram ABCD the diagonals meet at O. To prove AO = CO you show triangles AOB and COD are congruent, using AB = CD and two pairs of alternate angles. Which rule applies?",
 opts:["ASA","SSS","SAS","RHS"],a:0,
 hint:"Count what you have: one side and the two angles at its ends.",
 expl:"Angle OAB = angle OCD and angle OBA = angle ODC (alternate angles, since AB ∥ CD), with the side AB = CD between them. That is ASA, so the triangles are congruent and AO = CO."},
{lvl:3,sec:"P",type:"multi",q:"Select EVERY set of facts that guarantees two triangles are congruent.",
 opts:["Three pairs of equal sides","Two pairs of equal sides and the angle between them equal","Three pairs of equal angles","Right triangles with equal hypotenuses and one pair of equal legs"],aMulti:[0,1,3],
 hint:"Equal angles alone fix only the shape, not the size.",
 expl:"SSS, SAS and RHS all guarantee congruence. Three equal angles (AAA) only give similarity: an enlarged copy has the same angles but is not congruent."}
],

"g7-centers": [
{sec:"G",type:"mc",q:"The centroid of a triangle is the point where which three lines meet?",
 opts:["The medians","The altitudes","The perpendicular bisectors","The angle bisectors"],a:0,
 expl:"A median joins a vertex to the midpoint of the opposite side. The three medians meet at the centroid, the triangle's balance point."},
{sec:"G",type:"mc",q:"The circumcentre of a triangle is the same distance from:",
 opts:["The three vertices","The three sides","The three midpoints","The three altitudes"],a:0,
 expl:"The circumcentre is the centre of the circle through all three vertices, so it is equidistant from the vertices."},
{sec:"G",type:"in",q:"The centroid divides each median in the ratio 2 : 1, with the longer part next to the vertex. A median is 12 cm long. How far, in cm, is the centroid from the vertex?",ans:8,
 expl:"Two thirds of 12 cm is 8 cm, so the centroid is 8 cm from the vertex (and 4 cm from the midpoint)."},
{lvl:2,sec:"G",type:"mc",q:"Where is the circumcentre of a right-angled triangle?",
 opts:["At the midpoint of the hypotenuse","At the right-angle vertex","At the centroid","Outside the triangle, beyond the hypotenuse"],a:0,
 hint:"Think of the angle-in-a-semicircle theorem in reverse.",
 expl:"A right angle is inscribed in a semicircle, so the hypotenuse is a diameter of the circumcircle. Its midpoint is the circumcentre."},
{lvl:2,sec:"G",type:"mc",q:"The Euler line of a non-equilateral triangle passes through three of these centres. Which one is generally NOT on it?",
 opts:["Incentre","Centroid","Orthocentre","Circumcentre"],a:0,
 expl:"Euler showed the orthocentre, centroid and circumcentre are always collinear. The incentre lies on that line only in special cases (such as isosceles triangles)."},
{lvl:2,sec:"G",type:"in",q:"On the Euler line, the centroid G lies between the orthocentre H and circumcentre O with HG = 2 × GO. If HO = 9 cm, what is GO in cm?",ans:3,
 hint:"HO is split into parts in the ratio 2 : 1.",
 expl:"HG + GO = 9 and HG = 2 GO, so 3 GO = 9 and GO = 3 cm."},
{lvl:3,sec:"G",type:"in",q:"A triangle has vertices at (0, 0), (6, 0) and (0, 8). How far is its circumcentre from the origin?",ans:5,
 hint:"The triangle is right-angled at the origin; where is the circumcentre of a right triangle?",
 expl:"The hypotenuse joins (6, 0) and (0, 8), so the circumcentre is its midpoint (3, 4). Its distance from (0, 0) is √(9 + 16) = 5, which is also the circumradius."},
{lvl:3,sec:"G",type:"in",q:"The incentre is the centre of the circle touching all three sides. For a right triangle with legs a, b and hypotenuse c, the inradius is (a + b − c)/2. Find the inradius of a 5-12-13 triangle.",ans:2,
 expl:"(5 + 12 − 13)/2 = 4/2 = 2. Check with area = r × semi-perimeter: 30 = 2 × 15."},
{lvl:3,sec:"G",type:"multi",q:"In an equilateral triangle, select EVERY centre that coincides with the centroid.",
 opts:["Incentre","Circumcentre","Orthocentre","A vertex"],aMulti:[0,1,2],
 hint:"By symmetry each median is also an altitude, an angle bisector and a perpendicular bisector.",
 expl:"In an equilateral triangle every median is also an altitude, an angle bisector and a perpendicular bisector, so the centroid, incentre, circumcentre and orthocentre are all the same point. It is not a vertex."}
],

"g7-circthm": [
{sec:"G",type:"in",q:"Points A and B are on a circle with centre O, and angle AOB = 100°. Point C is on the major arc. What is angle ACB in degrees?",ans:50,
 hint:"The angle at the centre is twice the angle at the circumference on the same arc.",
 expl:"The angle at the centre is double the angle at the circumference, so angle ACB = 100 ÷ 2 = 50°."},
{sec:"G",type:"in",q:"AB is a diameter of a circle and C is any other point on the circle. What is angle ACB in degrees?",ans:90,
 expl:"The angle in a semicircle is a right angle, so angle ACB = 90°."},
{sec:"G",type:"in",q:"ABCD is a cyclic quadrilateral (all four vertices on a circle) with angle A = 70°. What is angle C in degrees?",ans:110,
 hint:"Opposite angles of a cyclic quadrilateral are supplementary.",
 expl:"Opposite angles of a cyclic quadrilateral add to 180°, so angle C = 180 − 70 = 110°."},
{lvl:2,sec:"G",type:"in",q:"A tangent from point P touches a circle with centre O at T. If OT = 6 and OP = 10, what is the length PT?",ans:8,
 hint:"The radius meets the tangent at a right angle.",
 expl:"OT ⊥ PT, so by Pythagoras PT = √(10² − 6²) = √64 = 8."},
{lvl:2,sec:"G",type:"in",q:"Two tangents from point P touch a circle with centre O at A and B. If angle APB = 50°, what is angle AOB in degrees?",ans:130,
 hint:"In quadrilateral PAOB two of the angles are right angles.",
 expl:"Angles OAP and OBP are both 90° (radius ⊥ tangent), so in quadrilateral PAOB angle AOB = 360 − 90 − 90 − 50 = 130°."},
{lvl:2,sec:"G",type:"mc",q:"Which statement is a correct circle theorem?",
 opts:["Opposite angles of a cyclic quadrilateral add to 180°","Opposite angles of a cyclic quadrilateral are equal","The angle at the centre is half the angle at the circumference","Two tangents from the same point have different lengths"],a:0,
 expl:"Opposite angles of a cyclic quadrilateral are supplementary. The centre angle is double (not half) the circumference angle, and tangents from one external point are equal."},
{lvl:3,sec:"G",type:"in",q:"Chords AB and CD of a circle cross at P inside the circle. AP = 4, PB = 9 and CP = 6. What is PD?",ans:6,
 hint:"For crossing chords, AP × PB = CP × PD.",
 expl:"AP × PB = CP × PD gives 4 × 9 = 6 × PD, so PD = 36 ÷ 6 = 6."},
{lvl:3,sec:"G",type:"in",q:"Points C and D lie on a circle on opposite sides of chord AB. If angle ACB = 65°, what is angle ADB in degrees?",ans:115,
 hint:"A, C, B, D form a cyclic quadrilateral.",
 expl:"ACBD is a cyclic quadrilateral and angles ACB and ADB are opposite, so angle ADB = 180 − 65 = 115°."},
{lvl:3,sec:"G",type:"multi",q:"Select EVERY statement that is always true for a tangent to a circle.",
 opts:["It meets the radius at the point of contact at 90°","Two tangents from the same external point are equal in length","It passes through the centre of the circle","It bisects every chord it meets"],aMulti:[0,1],
 expl:"A tangent is perpendicular to the radius at the point of contact, and the two tangents from an external point are equal. A tangent never passes through the centre and has no special relation to chords."}
],

"g7-heron": [
{sec:"G",type:"in",q:"A triangle has sides 5, 6 and 7. What is its semi-perimeter s?",ans:9,
 expl:"s = (5 + 6 + 7)/2 = 18/2 = 9."},
{sec:"G",type:"in",q:"Use Heron's formula, area = √(s(s − a)(s − b)(s − c)), to find the area of the triangle with sides 3, 4 and 5.",ans:6,
 hint:"First find s = (3 + 4 + 5)/2.",
 expl:"s = 6, so area = √(6 × 3 × 2 × 1) = √36 = 6. (It is a right triangle, and ½ × 3 × 4 = 6 agrees.)"},
{sec:"G",type:"mc",q:"Which expression is Heron's formula for the area of a triangle with sides a, b, c and semi-perimeter s?",mono:true,
 opts:["√(s(s − a)(s − b)(s − c))","s(s − a)(s − b)(s − c)","√(abc)/s","(a + b + c)/2"],a:0,
 expl:"Heron's formula is area = √(s(s − a)(s − b)(s − c)), where s = (a + b + c)/2 is the semi-perimeter."},
{lvl:2,sec:"G",type:"in",q:"Find the area of the triangle with sides 13, 14 and 15.",ans:84,
 hint:"s = 21. Multiply 21 × 8 × 7 × 6 and take the square root.",
 expl:"s = 21, so area = √(21 × 8 × 7 × 6) = √7056 = 84."},
{lvl:2,sec:"G",type:"in",q:"Find the area of the isosceles triangle with sides 5, 5 and 6.",ans:12,
 expl:"s = 8, so area = √(8 × 3 × 3 × 2) = √144 = 12. (Check: the height to the base 6 is 4, and ½ × 6 × 4 = 12.)"},
{lvl:2,sec:"G",type:"multi",q:"Heron's formula gives zero or an impossible square root when the sides cannot form a triangle. Select EVERY set of lengths that does NOT make a real triangle.",mono:true,
 opts:["1, 2, 3","2, 3, 4","5, 5, 10","4, 7, 8"],aMulti:[0,2],
 hint:"The two shorter sides must add to more than the longest side.",
 expl:"1 + 2 = 3 and 5 + 5 = 10: in both cases the two short sides only just reach the long side, so the triangle is flat (Heron gives s − c = 0). 2, 3, 4 and 4, 7, 8 are fine."},
{lvl:3,sec:"G",type:"in",q:"A triangle has sides 13, 14 and 15. Use its area to find the height drawn to the side of length 14.",ans:12,
 hint:"Area = ½ × base × height, and Heron gives the area as 84.",
 expl:"Heron: s = 21, area = √(21 × 8 × 7 × 6) = 84. Then ½ × 14 × h = 84 gives h = 12."},
{lvl:3,sec:"G",type:"in",q:"Find the area of the triangle with sides 6, 25 and 29.",ans:60,
 hint:"s = 30, and one of the factors is very small.",
 expl:"s = 30, so area = √(30 × 24 × 5 × 1) = √3600 = 60."},
{lvl:3,sec:"G",type:"in",q:"The inradius r of a triangle satisfies area = r × s. Find the inradius of the triangle with sides 13, 14 and 15.",ans:4,
 hint:"You know the area from Heron's formula and s = 21.",
 expl:"Area = 84 and s = 21, so r = 84 ÷ 21 = 4."}
],

"g7-frustum": [
{sec:"G",type:"in",q:"A sphere has radius 3 cm. Its volume is kπ cm³. What is k?",ans:36,
 hint:"Volume of a sphere = (4/3)πr³.",
 expl:"(4/3) × π × 3³ = (4/3) × 27π = 36π, so k = 36."},
{sec:"G",type:"in",q:"A cone has base radius 3 cm and height 4 cm. Its volume is kπ cm³. What is k?",ans:12,
 hint:"Volume of a cone = (1/3)πr²h.",
 expl:"(1/3) × π × 9 × 4 = 12π, so k = 12."},
{sec:"G",type:"mc",q:"Which formula gives the surface area of a sphere of radius r?",mono:true,
 opts:["4πr²","πr²","(4/3)πr³","2πr²"],a:0,
 expl:"The surface area of a sphere is 4πr², four times the area of a circle with the same radius."},
{lvl:2,sec:"G",type:"in",q:"A cone has radius 3 cm, height 4 cm and slant height 5 cm. Its curved surface area is kπ cm². What is k?",ans:15,
 hint:"Curved surface area of a cone = π × r × slant height.",
 expl:"π × 3 × 5 = 15π, so k = 15."},
{lvl:2,sec:"G",type:"in",q:"A cone of height 6 cm and base radius 4 cm is cut parallel to its base halfway up, removing the top. The remaining frustum has volume kπ cm³. What is k?",ans:28,
 hint:"Subtract the small top cone (height 3, radius 2) from the whole cone.",
 expl:"Whole cone: (1/3)π × 16 × 6 = 32π. Top cone: (1/3)π × 4 × 3 = 4π. Frustum: 32π − 4π = 28π, so k = 28."},
{lvl:2,sec:"G",type:"in",q:"A hemisphere (half a sphere) has radius 6 cm. Its volume is kπ cm³. What is k?",ans:144,
 expl:"A full sphere would be (4/3)π × 216 = 288π, so the hemisphere is 144π and k = 144."},
{lvl:3,sec:"G",type:"in",q:"A frustum has base radius 5 cm, top radius 2 cm and height 6 cm. Using V = (1/3)πh(R² + Rr + r²), its volume is kπ cm³. What is k?",ans:78,
 expl:"(1/3) × π × 6 × (25 + 10 + 4) = 2π × 39 = 78π, so k = 78."},
{lvl:3,sec:"G",type:"in",q:"A sphere of radius 6 cm has exactly the same volume as a cone of base radius 6 cm. What is the height of the cone in cm?",ans:24,
 hint:"Set (4/3)π × 6³ equal to (1/3)π × 6² × h.",
 expl:"Sphere: (4/3)π × 216 = 288π. Cone: (1/3)π × 36 × h = 12πh. So 12h = 288 and h = 24 cm."},
{lvl:3,sec:"G",type:"mc",q:"Mei doubles the radius of a sphere. By what factor does its volume multiply?",mono:true,
 opts:["8","2","4","6"],a:0,hint:"Volume depends on the cube of the radius.",
 expl:"Volume is proportional to r³, so doubling r multiplies the volume by 2³ = 8."}
],

"g7-coordgeo": [
{sec:"G",type:"in",q:"What is the distance between the points (1, 2) and (4, 6)?",ans:5,
 hint:"Use the distance formula, or draw a right triangle with legs 3 and 4.",
 expl:"The horizontal change is 3 and the vertical change is 4, so the distance is √(9 + 16) = 5."},
{sec:"G",type:"pair",q:"What is the midpoint of the segment joining (2, 3) and (8, 7)?",ansP:[5,5],
 expl:"Average the coordinates: ((2 + 8)/2, (3 + 7)/2) = (5, 5)."},
{sec:"G",type:"in",q:"What is the slope of the line through (1, 1) and (4, 7)?",ans:2,
 expl:"Slope = (7 − 1)/(4 − 1) = 6/3 = 2."},
{lvl:2,sec:"G",type:"mc",q:"A line has slope 2/3. What is the slope of a line perpendicular to it?",mono:true,
 opts:["−3/2","3/2","−2/3","2/3"],a:0,
 hint:"Perpendicular slopes multiply to −1.",
 expl:"The perpendicular slope is the negative reciprocal: −3/2, since (2/3) × (−3/2) = −1."},
{lvl:2,sec:"G",type:"pair",q:"A(0, 0), B(4, 0) and C(6, 3) are three vertices of parallelogram ABCD, in that order. Find the coordinates of D.",ansP:[2,3],
 hint:"D = A + C − B, because the diagonals bisect each other.",
 expl:"D = A + C − B = (0 + 6 − 4, 0 + 3 − 0) = (2, 3). Check: AB and DC are both 4 units long and horizontal."},
{lvl:2,sec:"G",type:"in",q:"What is the area of the triangle with vertices (0, 0), (6, 0) and (2, 5)?",ans:15,
 hint:"The base along the x-axis has length 6.",
 expl:"Base = 6 and height = 5 (the y-coordinate of the third vertex), so area = ½ × 6 × 5 = 15."},
{lvl:3,sec:"G",type:"in",q:"Use the shoelace formula to find the area of the triangle with vertices (1, 1), (5, 2) and (3, 6).",ans:9,
 hint:"Area = ½|x₁y₂ − x₂y₁ + x₂y₃ − x₃y₂ + x₃y₁ − x₁y₃|.",
 expl:"½|(1×2 − 5×1) + (5×6 − 3×2) + (3×1 − 1×6)| = ½|−3 + 24 − 3| = ½ × 18 = 9."},
{lvl:3,sec:"G",type:"in",q:"The point (3, k) with k > 0 lies on the circle x² + y² = 25. What is k?",ans:4,
 expl:"9 + k² = 25 gives k² = 16, so k = 4."},
{lvl:3,sec:"G",type:"in",q:"Find the perpendicular bisector of the segment from (1, 2) to (5, 6). Where does it cross the x-axis? Enter the x-coordinate.",ans:7,
 hint:"It passes through the midpoint and is perpendicular to the segment (slope 1).",
 expl:"The midpoint is (3, 4) and the segment has slope 1, so the bisector has slope −1: y − 4 = −(x − 3), or y = −x + 7. Setting y = 0 gives x = 7."},
{lvl:3,sec:"G",type:"multi",q:"Select EVERY point that is exactly 5 units from the origin.",mono:true,
 opts:["(3, 4)","(−5, 0)","(4, 4)","(0, −5)"],aMulti:[0,1,3],
 expl:"√(9 + 16) = 5, √25 = 5 and √25 = 5 for the first, second and fourth. But (4, 4) is √32 ≈ 5.66 from the origin."}
],

"g7-inclexcl3": [
{sec:"K",type:"in",q:"|A| = 20, |B| = 15, |C| = 10, |A∩B| = 5, |A∩C| = 4, |B∩C| = 3 and |A∩B∩C| = 2. How many elements are in A ∪ B ∪ C?",ans:35,
 hint:"Add the singles, subtract the pairs, add back the triple.",
 expl:"20 + 15 + 10 − 5 − 4 − 3 + 2 = 35."},
{sec:"K",type:"mc",q:"Which is the inclusion-exclusion formula for |A ∪ B ∪ C|?",mono:true,
 opts:["|A|+|B|+|C|−|A∩B|−|A∩C|−|B∩C|+|A∩B∩C|","|A|+|B|+|C|−|A∩B∩C|","|A|+|B|+|C|−|A∩B|−|A∩C|−|B∩C|","|A|+|B|+|C|+|A∩B|+|A∩C|+|B∩C|−|A∩B∩C|"],a:0,
 expl:"Adding the three sets counts pairwise overlaps twice, so subtract them; that removes the triple overlap entirely, so add it back once."},
{sec:"K",type:"in",q:"In a class of 30, 12 play football, 10 play tennis and 8 play chess. 4 play football and tennis, 3 football and chess, 2 tennis and chess, and 1 plays all three. How many play none of them?",ans:8,
 hint:"First count how many play at least one.",
 expl:"At least one: 12 + 10 + 8 − 4 − 3 − 2 + 1 = 22. So 30 − 22 = 8 play none."},
{lvl:2,sec:"K",type:"in",q:"How many integers from 1 to 100 are divisible by 2, 3 or 5?",ans:74,
 hint:"Count multiples of 2, 3, 5, then of 6, 10, 15, then of 30.",
 expl:"50 + 33 + 20 − 16 − 10 − 6 + 3 = 74."},
{lvl:2,sec:"K",type:"in",q:"How many integers from 1 to 60 are divisible by NONE of 2, 3 and 5?",ans:16,
 hint:"Count those divisible by at least one, then subtract from 60.",
 expl:"At least one: 30 + 20 + 12 − 10 − 6 − 4 + 2 = 44. So 60 − 44 = 16 are divisible by none (they are 1, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 49, 53, 59)."},
{lvl:2,sec:"K",type:"in",q:"All 40 students in a club like at least one of art, band or drama. 20 like art, 25 band, 15 drama; 10 like art and band, 8 art and drama, 6 band and drama. How many like all three?",ans:4,
 hint:"Set the union equal to 40 and solve for the triple overlap.",
 expl:"40 = 20 + 25 + 15 − 10 − 8 − 6 + x = 36 + x, so x = 4."},
{lvl:3,sec:"K",type:"in",q:"|A| = 20, |B| = 15, |C| = 10, |A∩B| = 5, |A∩C| = 4, |B∩C| = 3, |A∩B∩C| = 2. How many elements are in EXACTLY one of the three sets?",ans:27,
 hint:"Exactly one = (sum of singles) − 2 × (sum of pairs) + 3 × (triple).",
 expl:"Each pairwise overlap is removed twice and the triple overlap put back three times: 45 − 2 × 12 + 3 × 2 = 45 − 24 + 6 = 27."},
{lvl:3,sec:"K",type:"in",q:"With |A∩B| = 5, |A∩C| = 4, |B∩C| = 3 and |A∩B∩C| = 2, how many elements are in EXACTLY two of the three sets?",ans:6,
 hint:"Each pair-count also includes the elements in all three sets.",
 expl:"Elements in all three are counted in each of the three pair-counts, so exactly two = (5 + 4 + 3) − 3 × 2 = 6."},
{lvl:3,sec:"K",type:"in",q:"How many 3-letter strings using only the letters A, B and C (repeats allowed) are missing at least one of the three letters?",ans:21,
 hint:"Let A₁ be the strings with no A, and so on. Apply inclusion-exclusion to the three sets.",
 expl:"Strings missing a given letter: 2³ = 8 each, giving 3 × 8 = 24. Missing two given letters: 1 each, giving 3. Missing all three: 0. So 24 − 3 + 0 = 21 (out of 27; only 6 strings use all three letters)."}
],

"g7-genfunc": [
{sec:"K",type:"in",q:"What is the coefficient of x² in the expansion of (1 + x)⁴?",ans:6,
 hint:"Use Pascal's triangle, row 4.",
 expl:"(1 + x)⁴ = 1 + 4x + 6x² + 4x³ + x⁴, so the coefficient is 6 = C(4, 2)."},
{sec:"K",type:"mc",q:"Which generating function has coefficients 1, 1, 1, 1, ... (that is, equals 1 + x + x² + x³ + ...)?",mono:true,
 opts:["1/(1 − x)","1/(1 + x)","1 − x","x/(1 − x)"],a:0,
 hint:"Multiply each option by (1 − x) and see what is left.",
 expl:"(1 − x)(1 + x + x² + ...) = 1, because everything cancels except the leading 1. So 1 + x + x² + ... = 1/(1 − x)."},
{sec:"K",type:"in",q:"Expand (1 + x + x²)(1 + x). What is the coefficient of x²?",ans:2,
 expl:"(1 + x + x²)(1 + x) = 1 + 2x + 2x² + x³. The x² terms come from x·x and x²·1, so the coefficient is 2."},
{lvl:2,sec:"K",type:"in",q:"Two dice are rolled. The number of ways to get a total of 6 is the coefficient of x⁶ in (x + x² + x³ + x⁴ + x⁵ + x⁶)². What is it?",ans:5,
 hint:"List the pairs (a, b) with a + b = 6.",
 expl:"The pairs are (1,5), (2,4), (3,3), (4,2), (5,1): 5 ways, so the coefficient of x⁶ is 5."},
{lvl:2,sec:"K",type:"in",q:"What is the coefficient of x³ in (1 + x)⁶?",ans:20,
 hint:"It is C(6, 3).",
 expl:"The coefficient of x^k in (1 + x)^n is C(n, k), so it is C(6, 3) = 20."},
{lvl:2,sec:"K",type:"mc",q:"The coefficient of xⁿ in (1 + x)(1 + x²)(1 + x⁴) counts what?",
 opts:["Ways to write n as a sum of distinct numbers from {1, 2, 4}","Ways to write n using any number of 1s, 2s and 4s","The number of divisors of n","The number of ways to order n objects"],a:0,
 hint:"Each factor lets you use its power either once or not at all.",
 expl:"From each factor you pick either 1 (do not use that part) or the power (use it once), so xⁿ collects the ways to write n as a sum of distinct parts from {1, 2, 4}. Every n from 0 to 7 has exactly one such way."},
{lvl:3,sec:"K",type:"in",q:"Ravi packs a bag with at most 2 apples, at most 1 banana and any number of cherries. The number of bags with exactly 3 pieces of fruit is the coefficient of x³ in (1 + x + x²)(1 + x)(1 + x + x² + ...). What is it?",ans:6,
 hint:"First expand (1 + x + x²)(1 + x). Multiplying by 1/(1 − x) turns coefficients into running totals.",
 expl:"(1 + x + x²)(1 + x) = 1 + 2x + 2x² + x³. Multiplying by 1 + x + x² + ... makes each coefficient the sum of all earlier ones, so the x³ coefficient is 1 + 2 + 2 + 1 = 6."},
{lvl:3,sec:"K",type:"in",q:"The coefficient of xⁿ in 1/(1 − x)³ is C(n + 2, 2). What is the coefficient of x⁴?",ans:15,
 hint:"C(6, 2).",
 expl:"C(4 + 2, 2) = C(6, 2) = 15. This is the number of ways to write 4 as an ordered sum of three non-negative integers."},
{lvl:3,sec:"K",type:"mc",q:"Which generating function counts the ways to make n cents using any number of 1-cent and 5-cent coins?",mono:true,
 opts:["1/((1 − x)(1 − x⁵))","(1 + x)(1 + x⁵)","1/(1 − x⁶)","(1 − x)(1 − x⁵)"],a:0,
 hint:"Each coin type contributes a factor 1 + x^v + x^2v + ... for its value v.",
 expl:"1-cent coins give 1 + x + x² + ... = 1/(1 − x) and 5-cent coins give 1 + x⁵ + x¹⁰ + ... = 1/(1 − x⁵). Multiply: 1/((1 − x)(1 − x⁵))."}
],

"g7-partitions": [
{sec:"K",type:"in",q:"A partition of n writes n as a sum of positive integers, order not mattering. How many partitions does 4 have?",ans:5,
 hint:"Start with 4 itself, then 3 + 1, and keep going.",
 expl:"4, 3+1, 2+2, 2+1+1, 1+1+1+1: five partitions, so p(4) = 5."},
{sec:"K",type:"in",q:"How many partitions does 5 have?",ans:7,
 expl:"5, 4+1, 3+2, 3+1+1, 2+2+1, 2+1+1+1, 1+1+1+1+1: p(5) = 7."},
{sec:"K",type:"mc",q:"Which of these is NOT a partition of 6?",mono:true,
 opts:["4 + 3","3 + 2 + 1","6","2 + 2 + 2"],a:0,
 expl:"4 + 3 = 7, not 6. The other three all sum to 6."},
{lvl:2,sec:"K",type:"in",q:"How many partitions of 7 have exactly 3 parts?",ans:4,
 hint:"Start with the largest possible first part, 5.",
 expl:"5+1+1, 4+2+1, 3+3+1, 3+2+2: four partitions."},
{lvl:2,sec:"K",type:"in",q:"How many partitions of 8 use distinct parts (no part repeated)?",ans:6,
 hint:"Start from 8 alone and work down, never repeating a number.",
 expl:"8, 7+1, 6+2, 5+3, 5+2+1, 4+3+1: six partitions into distinct parts."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY partition of 5 whose parts are all distinct.",mono:true,
 opts:["5","4 + 1","3 + 2","3 + 1 + 1"],aMulti:[0,1,2],
 expl:"5, 4 + 1 and 3 + 2 use no repeated part. 3 + 1 + 1 repeats the 1."},
{lvl:3,sec:"K",type:"in",q:"Euler proved that the number of partitions of n into odd parts equals the number into distinct parts. How many partitions of 6 use only odd parts?",ans:4,
 hint:"The odd parts available are 1, 3 and 5.",
 expl:"5+1, 3+3, 3+1+1+1, 1+1+1+1+1+1: four partitions. Check: the distinct-part partitions of 6 are 6, 5+1, 4+2, 3+2+1, also four."},
{lvl:3,sec:"K",type:"in",q:"How many partitions does 7 have in total?",ans:15,
 hint:"Organise them by the size of the largest part: 7, then 6, then 5, ...",
 expl:"Largest part 7: 1. Largest 6: 1. Largest 5: 2 (5+2, 5+1+1). Largest 4: 3 (4+3, 4+2+1, 4+1+1+1). Largest 3: 4 (3+3+1, 3+2+2, 3+2+1+1, 3+1+1+1+1). Largest 2: 3. Largest 1: 1. Total 1+1+2+3+4+3+1 = 15."},
{lvl:3,sec:"K",type:"mc",q:"Draw the partition 4 + 2 + 1 as rows of dots (a Ferrers diagram) and read the columns instead. Which partition do the columns give (the conjugate)?",mono:true,
 opts:["3 + 2 + 1 + 1","4 + 2 + 1","3 + 3 + 1","2 + 2 + 2 + 1"],a:0,
 hint:"Column k has one dot for every row of length at least k.",
 expl:"Rows of 4, 2, 1 dots have column heights 3, 2, 1, 1 (three rows reach column 1, two reach column 2, one reaches columns 3 and 4). The conjugate is 3 + 2 + 1 + 1."}
],

"g7-graphtheo": [
{sec:"K",type:"in",q:"A graph has 7 edges. What is the sum of the degrees of all its vertices?",ans:14,
 hint:"Each edge has two ends.",
 expl:"Every edge contributes 1 to the degree of each of its two endpoints, so the degree sum is 2 × 7 = 14 (the handshake lemma)."},
{sec:"K",type:"in",q:"The complete graph K₄ has 4 vertices, every pair joined by an edge. How many edges does it have?",ans:6,
 expl:"Each of the 4 vertices connects to 3 others, giving 4 × 3 = 12 edge-ends, or 6 edges. Equivalently C(4, 2) = 6."},
{sec:"K",type:"mc",q:"A connected graph has an Euler circuit (a closed walk using every edge exactly once) exactly when:",
 opts:["Every vertex has even degree","Every vertex has odd degree","It has exactly two odd-degree vertices","It has no cycles"],a:0,
 hint:"Each time the walk passes through a vertex it uses two edges there.",
 expl:"Each visit to a vertex uses one edge in and one out, so every degree must be even. (Exactly two odd vertices gives an Euler path, not a circuit.)"},
{lvl:2,sec:"K",type:"in",q:"A tree (a connected graph with no cycles) has 12 vertices. How many edges does it have?",ans:11,
 hint:"A tree always has one fewer edge than vertices.",
 expl:"A tree with n vertices has n − 1 edges, so 12 vertices means 11 edges."},
{lvl:2,sec:"K",type:"in",q:"A complete graph has 21 edges. How many vertices does it have?",ans:7,
 hint:"Solve n(n − 1)/2 = 21.",
 expl:"n(n − 1)/2 = 21 means n(n − 1) = 42 = 7 × 6, so n = 7."},
{lvl:2,sec:"K",type:"mc",q:"Can a graph have vertices of degrees 3, 3, 3, 3 and 1?",
 opts:["No, the degree sum is odd","Yes, it is a tree","Yes, it is a complete graph","No, because 1 is too small"],a:0,
 hint:"Add up the degrees and think about the handshake lemma.",
 expl:"The degrees add to 13, but the degree sum must be twice the number of edges, so it must be even. No such graph exists."},
{lvl:3,sec:"K",type:"in",q:"A connected planar graph is drawn with no crossing edges. It has 8 vertices and 12 edges. Using Euler's formula V − E + F = 2, how many faces does it have (counting the outside face)?",ans:6,
 expl:"8 − 12 + F = 2, so F = 6. (A cube's edge graph is an example: 8 corners, 12 edges, 6 faces.)"},
{lvl:3,sec:"K",type:"in",q:"At a party of 6 people, everyone shakes hands with exactly 3 others. How many handshakes take place?",ans:9,
 hint:"Each handshake is an edge with two ends.",
 expl:"The degree sum is 6 × 3 = 18, and each handshake counts twice in that sum, so there are 18 ÷ 2 = 9 handshakes."},
{lvl:3,sec:"K",type:"multi",q:"Select EVERY graph that has an Euler circuit.",
 opts:["A cycle with 5 vertices","K₅ (the complete graph on 5 vertices)","K₄ (the complete graph on 4 vertices)","A path with 4 vertices"],aMulti:[0,1],
 hint:"Work out the degree of a vertex in each graph.",
 expl:"In a 5-cycle every degree is 2 and in K₅ every degree is 4: all even, so both have Euler circuits. In K₄ every degree is 3 and a path has two vertices of degree 1, so those do not."},
{lvl:3,sec:"K",type:"in",q:"The complete bipartite graph K₃,₄ has 3 vertices on one side, 4 on the other, and every cross-pair joined. How many edges does it have?",ans:12,
 expl:"Each of the 3 vertices on the left joins all 4 on the right, giving 3 × 4 = 12 edges."}
],

"g7-ramsey": [
{sec:"K",type:"in",q:"A drawer holds socks in 3 colours. Ingrid pulls socks out in the dark. How many must she take to be certain of a matching pair?",ans:4,
 hint:"Pigeonhole principle: what is the worst case?",
 expl:"She could get 3 socks all of different colours, but the 4th must repeat a colour. So 4 socks."},
{sec:"K",type:"mc",q:"What is the smallest number of people at a party that guarantees either 3 mutual friends or 3 mutual strangers?",mono:true,
 opts:["6","5","3","9"],a:0,
 expl:"This is the Ramsey number R(3, 3) = 6. With 6 people one of the two patterns is unavoidable; with 5 it can be avoided."},
{sec:"K",type:"in",q:"10 pigeons fly into 3 pigeonholes. At least how many pigeons must share the fullest hole?",ans:4,
 hint:"If every hole had at most 3, how many pigeons could there be?",
 expl:"3 holes with at most 3 pigeons each hold at most 9, so with 10 pigeons some hole has at least 4."},
{lvl:2,sec:"K",type:"mc",q:"How can you show that 5 people are NOT enough to guarantee 3 mutual friends or 3 mutual strangers?",
 opts:["Arrange them in a pentagon: neighbours are friends, everyone else strangers","Make every pair of the five people friends","Make every pair of the five people strangers","Show that any arrangement of 5 people works"],a:0,
 hint:"You need one specific arrangement with no friend-triangle and no stranger-triangle.",
 expl:"With friends around the pentagon's sides and strangers along its diagonals, no three people are all friends and no three are all strangers. So 5 can fail, which is why R(3, 3) = 6 and not 5."},
{lvl:2,sec:"K",type:"in",q:"In the proof that R(3, 3) = 6, pick one of the 6 people. Each of the other 5 is a friend or a stranger. At least how many of those 5 must be the same kind?",ans:3,
 hint:"Pigeonhole with 5 objects in 2 boxes.",
 expl:"Splitting 5 people into two groups, one group has at least 3 (since 2 + 2 = 4 < 5). Those 3 are the key to finding a triangle."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY number that equals one of the Ramsey numbers R(3, 3) or R(3, 4).",mono:true,
 opts:["6","9","7","8"],aMulti:[0,1],
 expl:"R(3, 3) = 6 and R(3, 4) = 9: nine people guarantee 3 mutual friends or 4 mutual strangers."},
{lvl:3,sec:"K",type:"in",q:"Colour every edge of K₆ (6 points, all 15 edges) red or blue. Whatever you do, at least how many triangles are guaranteed to be all one colour?",ans:2,
 hint:"Ramsey guarantees one; a counting argument shows you can never stop at one.",
 expl:"R(3, 3) = 6 guarantees at least one single-colour triangle, and counting the non-monochromatic angles at each vertex shows there are always at least 2. Colourings with exactly 2 exist, so the answer is 2."},
{lvl:3,sec:"K",type:"mc",q:"R(4, 4) is the smallest group size that guarantees 4 mutual friends or 4 mutual strangers. What is it?",mono:true,
 opts:["18","10","16","25"],a:0,
 expl:"R(4, 4) = 18. There is a clever colouring of K₁₇ with no single-colour K₄, but K₁₈ always contains one."},
{lvl:3,sec:"K",type:"in",q:"Tomas picks numbers from 1 to 8 without replacement. How many must he pick to be certain that two of them add up to 9?",ans:5,
 hint:"Group the numbers into pairs that sum to 9.",
 expl:"The pairs {1,8}, {2,7}, {3,6}, {4,5} are 4 pigeonholes. Four picks could take one from each pair, but a 5th pick must complete a pair. So 5."}
],

"g7-bayes": [
{sec:"S",type:"in",q:"P(A and B) = 0.2 and P(B) = 0.5. What is P(A | B), the probability of A given B?",ans:0.4,
 hint:"P(A | B) = P(A and B) ÷ P(B).",
 expl:"P(A | B) = 0.2 ÷ 0.5 = 0.4."},
{sec:"S",type:"mc",q:"Which is Bayes' rule?",mono:true,
 opts:["P(A|B) = P(B|A) × P(A) ÷ P(B)","P(A|B) = P(B|A)","P(A|B) = P(A) × P(B)","P(A|B) = P(B) ÷ P(A)"],a:0,
 expl:"Bayes' rule reverses a conditional probability: P(A|B) = P(B|A) × P(A) ÷ P(B)."},
{sec:"S",type:"in",q:"Bag 1 has 3 red and 1 blue marble; Bag 2 has 1 red and 3 blue. Hana picks a bag at random and draws a red marble. What is the probability she used Bag 1?",ans:0.75,
 hint:"Compare the chance of red via Bag 1 with the total chance of red.",
 expl:"P(red via Bag 1) = 0.5 × 0.75 = 0.375 and P(red via Bag 2) = 0.5 × 0.25 = 0.125. So P(Bag 1 | red) = 0.375 ÷ 0.5 = 0.75."},
{lvl:2,sec:"S",type:"in",q:"10% of a population has a condition. A test is positive for 90% of people who have it, and also positive for 10% of people who do not. Someone tests positive. What is the probability they have the condition?",ans:0.5,
 hint:"Compute P(positive and has it) and P(positive and does not have it).",
 expl:"P(positive and has it) = 0.1 × 0.9 = 0.09. P(positive and does not) = 0.9 × 0.1 = 0.09. So P(has it | positive) = 0.09 ÷ 0.18 = 0.5."},
{lvl:2,sec:"S",type:"in",q:"Out of 1000 people, 1% have a disease and the test catches all of them. It also gives a false positive to 10% of the healthy people. How many of the people who test positive are actually healthy?",ans:99,
 hint:"How many people are healthy? Take 10% of that.",
 expl:"10 people are sick and 990 are healthy. 10% of 990 = 99 healthy people test positive (so 99 of the 109 positives are false alarms)."},
{lvl:2,sec:"S",type:"mc",q:"The base-rate fallacy is the mistake of:",
 opts:["Forgetting how rare the condition is to begin with","Forgetting how accurate the test is","Assuming a test result is always right","Adding probabilities instead of multiplying"],a:0,
 expl:"Even an accurate test gives mostly false positives when the condition is rare, because the healthy group is so much bigger. Ignoring that prior probability is the base-rate fallacy."},
{lvl:3,sec:"S",type:"in",q:"A box holds two coins: one fair and one with heads on both sides. Diego picks one at random and flips it twice, getting heads both times. What is the probability he picked the double-headed coin?",ans:0.8,
 hint:"P(two heads | fair) = 0.25 and P(two heads | double-headed) = 1.",
 expl:"P(HH via double) = 0.5 × 1 = 0.5 and P(HH via fair) = 0.5 × 0.25 = 0.125. So P(double | HH) = 0.5 ÷ 0.625 = 0.8."},
{lvl:3,sec:"S",type:"in",q:"Half of all emails are spam. The word 'prize' appears in 36% of spam and 4% of non-spam. An email contains 'prize'. What is the probability it is spam?",ans:0.9,
 hint:"Find P(prize and spam) and P(prize and not spam).",
 expl:"P(prize and spam) = 0.5 × 0.36 = 0.18; P(prize and not spam) = 0.5 × 0.04 = 0.02. So P(spam | prize) = 0.18 ÷ 0.20 = 0.9."},
{lvl:3,sec:"S",type:"mc",q:"Three doors hide one prize. You pick a door; the host, who knows where the prize is, opens a different door showing no prize and offers a switch. What is the probability of winning if you switch?",mono:true,
 opts:["2/3","1/2","1/3","1"],a:0,
 hint:"Your first pick is wrong 2/3 of the time. What happens then if you switch?",
 expl:"Your first choice is right with probability 1/3. Whenever it is wrong (probability 2/3) the host's reveal leaves the prize behind the other door, so switching wins with probability 2/3."}
],

"g7-joint": [
{sec:"S",type:"in",q:"In a joint distribution table, P(X = 1, Y = 1) = 0.2 and P(X = 1, Y = 2) = 0.3, and Y takes only the values 1 and 2. What is the marginal probability P(X = 1)?",ans:0.5,
 hint:"Add across the row for X = 1.",
 expl:"P(X = 1) = 0.2 + 0.3 = 0.5."},
{sec:"S",type:"mc",q:"How do you get a marginal distribution from a joint probability table?",
 opts:["Add the joint probabilities along each row or column","Multiply the joint probabilities in each row","Divide each cell by the number of cells","Take the largest joint probability"],a:0,
 expl:"Summing a row gives the probability of that X-value regardless of Y (and likewise for columns). The totals are written in the margins, hence the name."},
{sec:"S",type:"in",q:"A joint table has four cells with probabilities 0.1, 0.2, 0.3 and one unknown. What is the unknown probability?",ans:0.4,
 expl:"All cells must add to 1, so the missing cell is 1 − 0.6 = 0.4."},
{lvl:2,sec:"S",type:"in",q:"X and Y are independent with P(X = 1) = 0.4 and P(Y = 1) = 0.5. What is the joint probability P(X = 1, Y = 1)?",ans:0.2,
 hint:"For independent variables, joint = product of marginals.",
 expl:"P(X = 1, Y = 1) = 0.4 × 0.5 = 0.2."},
{lvl:2,sec:"S",type:"mc",q:"A joint table has P(0,0) = 0.1, P(0,1) = 0.3, P(1,0) = 0.15, P(1,1) = 0.45 for (X, Y). Are X and Y independent?",
 opts:["Yes, every cell equals the product of its marginals","No, because the cells are not all equal","No, because P(1,1) is the largest cell","Cannot be decided from a table"],a:0,
 hint:"Find P(X = 0), P(Y = 0) and so on, then multiply.",
 expl:"P(X = 0) = 0.4, P(X = 1) = 0.6, P(Y = 0) = 0.25, P(Y = 1) = 0.75. Then 0.4 × 0.25 = 0.1, 0.4 × 0.75 = 0.3, 0.6 × 0.25 = 0.15, 0.6 × 0.75 = 0.45: every cell matches, so they are independent."},
{lvl:2,sec:"S",type:"in",q:"From a joint table, P(X = 0, Y = 1) = 0.3 and the marginal P(X = 0) = 0.4. What is the conditional probability P(Y = 1 | X = 0)?",ans:0.75,
 hint:"Divide the joint probability by the marginal of the condition.",
 expl:"P(Y = 1 | X = 0) = 0.3 ÷ 0.4 = 0.75."},
{lvl:3,sec:"S",type:"in",q:"Three fair coins are flipped. Let X be the number of heads among the first two coins and Y the total number of heads. What is P(X = 1, Y = 2)?",ans:0.25,
 hint:"X = 1 and Y = 2 means exactly one head in the first two flips AND the third flip is a head.",
 expl:"P(exactly one head in two flips) = 0.5, and the third coin must be a head, probability 0.5. Joint probability = 0.5 × 0.5 = 0.25."},
{lvl:3,sec:"S",type:"in",q:"A joint table for (X, Y) has P(0,0) = 0.15, P(0,1) = 0.25, P(1,0) = 0.35, P(1,1) = 0.25. What is P(X = 1 | Y = 0)?",ans:0.7,
 hint:"First find the marginal P(Y = 0) by adding the Y = 0 column.",
 expl:"P(Y = 0) = 0.15 + 0.35 = 0.5, so P(X = 1 | Y = 0) = 0.35 ÷ 0.5 = 0.7."},
{lvl:3,sec:"S",type:"multi",q:"For the table P(0,0) = 0.15, P(0,1) = 0.25, P(1,0) = 0.35, P(1,1) = 0.25, select EVERY true statement.",mono:true,
 opts:["P(X = 1) = 0.6","P(Y = 1) = 0.5","X and Y are independent","P(X = 0) = 0.5"],aMulti:[0,1],
 hint:"Compute the marginals, then test one cell against the product of its marginals.",
 expl:"P(X = 1) = 0.35 + 0.25 = 0.6 and P(Y = 1) = 0.25 + 0.25 = 0.5 are true, so P(X = 0) = 0.4 (not 0.5). Independence fails: P(1,1) = 0.25 but P(X = 1) × P(Y = 1) = 0.3."}
],

"g7-variance": [
{sec:"S",type:"in",q:"What is the expected value of a single roll of a fair six-sided die?",ans:3.5,
 expl:"(1 + 2 + 3 + 4 + 5 + 6)/6 = 21/6 = 3.5."},
{sec:"S",type:"in",q:"X equals 1 with probability 0.3 and 5 with probability 0.7. What is E[X]?",ans:3.8,
 hint:"Multiply each value by its probability and add.",
 expl:"E[X] = 1 × 0.3 + 5 × 0.7 = 0.3 + 3.5 = 3.8."},
{sec:"S",type:"mc",q:"Which formula gives the variance of X?",mono:true,
 opts:["E[X²] − (E[X])²","(E[X])² − E[X²]","E[X] − E[X²]","(E[X²])² − E[X]"],a:0,
 expl:"Var(X) = E[(X − μ)²], which simplifies to E[X²] − (E[X])²."},
{lvl:2,sec:"S",type:"in",q:"A fair coin is flipped once. X = 1 for heads and 0 for tails. What is the variance of X?",ans:0.25,
 hint:"E[X] = 0.5 and E[X²] = 0.5.",
 expl:"E[X] = 0.5 and E[X²] = 0.5 (since X² = X), so Var(X) = 0.5 − 0.25 = 0.25."},
{lvl:2,sec:"S",type:"in",q:"X takes the values 0, 1, 2 with probabilities 0.25, 0.5, 0.25. What is Var(X)?",ans:0.5,
 hint:"E[X] = 1. Find E[X²] and subtract 1².",
 expl:"E[X] = 0 + 0.5 + 0.5 = 1. E[X²] = 0 + 0.5 + 4 × 0.25 = 1.5. Var(X) = 1.5 − 1 = 0.5."},
{lvl:2,sec:"S",type:"in",q:"Var(X) = 4. What is Var(3X + 2)?",ans:36,
 hint:"Adding a constant does nothing; multiplying by a scales the variance by a².",
 expl:"Var(3X + 2) = 3² × Var(X) = 9 × 4 = 36. The + 2 shifts every value but does not change the spread."},
{lvl:3,sec:"S",type:"in",q:"Femi pays $2 to play a game. With probability 0.1 they win $10; otherwise they win nothing. What is the expected profit in dollars? (Enter a negative number for a loss.)",ans:-1,
 hint:"Expected winnings minus the cost.",
 expl:"Expected winnings = 0.1 × 10 = $1. Subtract the $2 cost: expected profit = −$1."},
{lvl:3,sec:"S",type:"in",q:"X is 2 with probability 0.5 and 6 with probability 0.5. What is the standard deviation of X?",ans:2,
 hint:"Find the variance, then take the square root.",
 expl:"E[X] = 4, and each value is 2 away from the mean, so Var(X) = 0.5 × 4 + 0.5 × 4 = 4 and SD = √4 = 2."},
{lvl:3,sec:"S",type:"in",q:"A fair coin is flipped 4 times. Each flip contributes variance 0.25 to the number of heads. What is the variance of the total number of heads?",ans:1,
 hint:"Variances of independent variables add.",
 expl:"The four flips are independent, so Var(total) = 4 × 0.25 = 1."},
{lvl:3,sec:"S",type:"multi",q:"Select EVERY statement that is always true.",mono:true,
 opts:["Var(X + Y) = Var(X) + Var(Y) when X and Y are independent","E[X + Y] = E[X] + E[Y]","Var(2X) = 2 Var(X)","Var(X + 5) = Var(X) + 5"],aMulti:[0,1],
 hint:"Expectation is always additive; variance scales with the square of a multiplier and ignores shifts.",
 expl:"Expectations always add, and variances add for independent variables. But Var(2X) = 4 Var(X), and adding 5 to X leaves the variance unchanged."}
],

"g7-distrib": [
{sec:"S",type:"in",q:"A fair coin is flipped 3 times. What is the probability of exactly 2 heads? Give a decimal.",ans:0.375,
 hint:"Count the outcomes with exactly two heads out of the 8 possible outcomes.",
 expl:"HHT, HTH, THH are 3 of the 8 equally likely outcomes: 3/8 = 0.375. This is the binomial probability C(3, 2) × 0.5³."},
{sec:"S",type:"mc",q:"Which distribution models the number of trials up to and including the first success?",
 opts:["Geometric","Binomial","Poisson","Uniform"],a:0,
 expl:"The geometric distribution counts how many trials it takes to get the first success. Binomial counts successes in a fixed number of trials."},
{sec:"S",type:"in",q:"A binomial variable has n = 20 trials with success probability p = 0.3. What is its mean?",ans:6,
 hint:"Mean = np.",
 expl:"Mean = np = 20 × 0.3 = 6."},
{lvl:2,sec:"S",type:"in",q:"Each shot has a 0.2 chance of hitting the target. What is the probability that the first hit comes on the 3rd shot? Give a decimal.",ans:0.128,
 hint:"Two misses then a hit.",
 expl:"P = 0.8 × 0.8 × 0.2 = 0.128."},
{lvl:2,sec:"S",type:"in",q:"Zainab rolls a die until she gets a 1 or a 2 (probability 1/3 on each roll). On average, how many rolls does she need?",ans:3,
 hint:"The mean of a geometric distribution is 1/p.",
 expl:"For a geometric distribution the expected number of trials is 1/p = 1 ÷ (1/3) = 3."},
{lvl:2,sec:"S",type:"mc",q:"Which situation is best modelled by a Poisson distribution?",
 opts:["The number of emails arriving in one hour","The number of heads in 10 coin flips","The number of flips until the first head","The result of a single die roll"],a:0,
 expl:"Poisson models counts of events happening at a steady average rate over an interval, like emails per hour. Coin-flip counts are binomial and waiting for the first head is geometric."},
{lvl:3,sec:"S",type:"in",q:"A fair coin is flipped 4 times. What is the probability of at least 3 heads? Give a decimal.",ans:0.3125,
 hint:"Add the probabilities of exactly 3 heads and exactly 4 heads.",
 expl:"Exactly 3 heads: C(4, 3) = 4 outcomes; exactly 4: 1 outcome. That is 5 of 16 outcomes: 5/16 = 0.3125."},
{lvl:3,sec:"S",type:"in",q:"A binomial variable has n = 10 and p = 0.2. What is its variance?",ans:1.6,
 hint:"Variance = np(1 − p).",
 expl:"Var = np(1 − p) = 10 × 0.2 × 0.8 = 1.6."},
{lvl:3,sec:"S",type:"in",q:"For a Poisson variable with mean λ, P(X = k) = e^(−λ) λ^k / k!. If λ = 3, what is P(X = 1) ÷ P(X = 0)?",ans:3,
 hint:"The e^(−λ) factors cancel.",
 expl:"P(X = 1) = e^(−3) × 3 and P(X = 0) = e^(−3), so the ratio is 3."},
{lvl:3,sec:"S",type:"multi",q:"Select EVERY situation that fits a binomial model.",
 opts:["The number of sixes in 12 rolls of a die","The number of correct guesses on 10 true/false questions","The number of rolls until the first six","The time between two phone calls"],aMulti:[0,1],
 hint:"Binomial needs a fixed number of independent yes/no trials with the same success chance.",
 expl:"Twelve rolls and ten guesses are fixed numbers of independent trials with the same success probability: binomial. Rolls until the first six is geometric, and a waiting time is not a count at all."}
],

"g7-markov": [
{sec:"S",type:"in",q:"In a weather chain, a sunny day is followed by a sunny day with probability 0.8, and a rainy day by a sunny day with probability 0.4. Today is sunny. What is the probability tomorrow is sunny?",ans:0.8,
 expl:"The chain only looks at today's state. From sunny, P(sunny tomorrow) = 0.8."},
{sec:"S",type:"mc",q:"In a transition matrix, each row lists the probabilities of moving from one state to each state. What must be true of every row?",
 opts:["Its entries add to 1","Its entries add to 0","All its entries are equal","Its diagonal entry is 0"],a:0,
 expl:"From any state you must go somewhere, so the probabilities in a row add to 1."},
{sec:"S",type:"in",q:"Sunny → sunny has probability 0.8 and rainy → sunny has probability 0.4. Today is sunny. What is the probability it is sunny in 2 days?",ans:0.72,
 hint:"Sunny-sunny-sunny or sunny-rainy-sunny.",
 expl:"P = 0.8 × 0.8 + 0.2 × 0.4 = 0.64 + 0.08 = 0.72."},
{lvl:2,sec:"S",type:"in",q:"A row of a transition matrix reads 0.3, ?, 0.5. What is the missing entry?",ans:0.2,
 expl:"The row must sum to 1, so the missing entry is 1 − 0.3 − 0.5 = 0.2."},
{lvl:2,sec:"S",type:"in",q:"A machine is either working (W) or broken (B). Each day W → W with probability 0.9 and B → W with probability 0.3. In the long run, what fraction of days is it working?",ans:0.75,
 hint:"The stationary fraction w satisfies w = 0.9w + 0.3(1 − w).",
 expl:"w = 0.9w + 0.3(1 − w) gives 0.4w = 0.3, so w = 0.75. In the long run it works 75% of days."},
{lvl:2,sec:"S",type:"mc",q:"The Markov property says the next state depends on:",
 opts:["Only the current state","The whole history of past states","Only the starting state","Nothing at all"],a:0,
 expl:"A Markov chain has no memory beyond the present: the probabilities of the next state depend only on where it is now."},
{lvl:3,sec:"S",type:"in",q:"A frog hops between pads A, B and C. From A it always hops to B. From B it hops to A or to C with probability 0.5 each. C is home, and it stops there. Starting at A, what is the expected number of hops to reach C?",ans:4,
 hint:"Let a and b be the expected hops from A and from B. Then a = 1 + b and b = 1 + 0.5a.",
 expl:"a = 1 + b and b = 1 + 0.5a. Substituting: b = 1 + 0.5(1 + b) = 1.5 + 0.5b, so b = 3 and a = 4 hops."},
{lvl:3,sec:"S",type:"in",q:"A chain has states A and B with A → A 0.5, A → B 0.5, B → A 0.2, B → B 0.8. Starting in A, what is the probability of being in B after 2 steps?",ans:0.65,
 hint:"Two routes: A → A → B and A → B → B.",
 expl:"P = 0.5 × 0.5 + 0.5 × 0.8 = 0.25 + 0.40 = 0.65."},
{lvl:3,sec:"S",type:"in",q:"A chain has states A and B with A → B 0.4 (so A → A 0.6) and B → A 0.6 (so B → B 0.4). In the long run, what fraction of the time is the chain in A?",ans:0.6,
 hint:"Solve a = 0.6a + 0.6(1 − a).",
 expl:"a = 0.6a + 0.6(1 − a) gives a = 0.6. So the chain is in A 60% of the time."},
{lvl:3,sec:"S",type:"multi",q:"Select EVERY list that could be a row of a transition matrix.",mono:true,
 opts:["0.2, 0.3, 0.5","0.5, 0.5, 0","0.4, 0.4, 0.4","0.7, 0.5, −0.2"],aMulti:[0,1],
 expl:"A row needs non-negative entries adding to 1. 0.2 + 0.3 + 0.5 = 1 and 0.5 + 0.5 + 0 = 1 work; 0.4 × 3 = 1.2 is too big and a negative probability is impossible."}
]
};
