/* Grade 7 core: unit rates with fractions, proportional relationships,
   percent applications, rational-number operations, decimal expansions,
   expressions and equations, scale drawings, constructions, circles, angles,
   solids, sampling and probability. */
export const G7_CORE_BANKS = {
"g7-unitfrac": [
{sec:"R",type:"in",q:"Amara walks 1/2 mile in 1/4 hour. What is her speed in miles per hour?",ans:2,
 hint:"Divide the distance by the time.",expl:"1/2 ÷ 1/4 = 1/2 × 4 = 2, so she walks 2 miles per hour."},
{sec:"R",type:"in",q:"A recipe uses 3/4 cup of sugar for every 1/2 cup of flour. How many cups of sugar are used per cup of flour? Give a decimal.",
 ans:1.5,hint:"Divide sugar by flour.",expl:"3/4 ÷ 1/2 = 3/4 × 2 = 3/2 = 1.5 cups of sugar per cup of flour."},
{sec:"R",type:"mc",q:"Which calculation gives the unit rate, in km per hour, for 2/3 km travelled in 1/6 hour?",mono:true,
 opts:["2/3 ÷ 1/6","2/3 × 1/6","1/6 ÷ 2/3","2/3 − 1/6"],a:0,
 expl:"A unit rate is distance per one hour, so divide distance by time: 2/3 ÷ 1/6 = 4 km per hour."},
{sec:"R",type:"multi",q:"Select EVERY rate that equals 4 km per hour.",
 opts:["2 km in 1/2 hour","1/2 km in 1/8 hour","1 km in 1/2 hour","3 km in 3/4 hour"],aMulti:[0,1,3],
 expl:"2 ÷ 1/2 = 4, 1/2 ÷ 1/8 = 4 and 3 ÷ 3/4 = 4. But 1 ÷ 1/2 = 2, so that one is only 2 km per hour."},
{lvl:2,sec:"R",type:"in",q:"Kenji paints 2/5 of a wall in 1/3 hour. At that rate, what fraction of the wall does he paint in one hour? Give a decimal.",
 ans:1.2,hint:"Divide the fraction of wall by the fraction of an hour.",expl:"2/5 ÷ 1/3 = 2/5 × 3 = 6/5 = 1.2 walls per hour."},
{lvl:2,sec:"R",type:"mc",q:"A car uses 1/8 of a tank of fuel to drive 1/4 of a trip. How much fuel does the whole trip need?",
 opts:["1/2 tank","1/32 tank","1/4 tank","2 tanks"],a:0,
 expl:"Fuel per whole trip = 1/8 ÷ 1/4 = 1/8 × 4 = 1/2 tank."},
{lvl:3,sec:"R",type:"in",q:"Hose A fills 1/2 of a pool in 2/3 hour. Hose B fills 1/4 of a pool in 1/5 hour. Together, how many pools per hour do they fill?",
 ans:2,hint:"Find each hose's rate in pools per hour first, then add.",
 expl:"Hose A: 1/2 ÷ 2/3 = 3/4 pool per hour. Hose B: 1/4 ÷ 1/5 = 5/4 pool per hour. Together 3/4 + 5/4 = 2 pools per hour."},
{lvl:3,sec:"R",type:"mc",q:"Which is the better buy: 3/4 kg of rice for $2.40, or 2/3 kg of rice for $2? Compare the cost per kg.",
 opts:["2/3 kg for $2, at $3.00 per kg","3/4 kg for $2.40, at $3.20 per kg","They cost the same per kg","3/4 kg for $2.40, at $1.80 per kg"],a:0,
 hint:"Divide each price by its weight.",
 expl:"$2.40 ÷ 3/4 = $2.40 × 4/3 = $3.20 per kg. $2 ÷ 2/3 = $2 × 3/2 = $3.00 per kg. The 2/3 kg bag is cheaper per kg."}
],

"g7-propor": [
{sec:"R",type:"mc",q:"What does the graph of a proportional relationship always look like?",
 opts:["A straight line through the origin","Any straight line","A line with y-intercept 2","A curve through the origin"],a:0,
 expl:"In a proportional relationship y = kx, so when x = 0, y = 0. The graph is a straight line through (0, 0)."},
{sec:"R",type:"in",q:"y is proportional to x, and y = 12 when x = 3. What is the constant of proportionality?",ans:4,
 hint:"Divide y by x.",expl:"k = y ÷ x = 12 ÷ 3 = 4."},
{sec:"R",type:"in",q:"A table shows x = 2, 5, 8 with y = 7, 17.5, 28. The relationship is proportional. What is y ÷ x?",ans:3.5,
 expl:"7 ÷ 2 = 3.5, 17.5 ÷ 5 = 3.5 and 28 ÷ 8 = 3.5, so the constant is 3.5."},
{sec:"R",type:"multi",q:"Select EVERY equation that shows y proportional to x.",mono:true,
 opts:["y = 5x","y = x + 5","y = 0.5x","y = 5/x"],aMulti:[0,2],
 expl:"Proportional means y = kx for a constant k. y = 5x and y = 0.5x fit. y = x + 5 has an added constant and y = 5/x is not a multiple of x."},
{lvl:2,sec:"R",type:"mc",q:"Which table shows a proportional relationship?",
 opts:["x: 1, 2, 3; y: 4, 8, 12","x: 1, 2, 3; y: 4, 5, 6","x: 1, 2, 3; y: 2, 4, 7","x: 1, 2, 3; y: 1, 4, 9"],a:0,
 hint:"Check whether y ÷ x is the same for every pair.",
 expl:"In the first table y ÷ x is 4 every time. The others give changing ratios, so they are not proportional."},
{lvl:2,sec:"R",type:"in",q:"Mateo earns $52 for 4 hours of work at a constant rate. How much does he earn for 7 hours, in dollars?",ans:91,
 hint:"Find the pay for one hour first.",expl:"k = 52 ÷ 4 = 13 dollars per hour, so 7 hours earns 7 × 13 = $91."},
{lvl:2,sec:"R",type:"mc",q:"The point (1, r) lies on the graph of a proportional relationship. What does r tell you?",
 opts:["The unit rate","The starting value","The x-intercept","The largest value"],a:0,
 expl:"When x = 1, y = k × 1 = k. So the y-value at x = 1 is the constant of proportionality, the unit rate."},
{lvl:3,sec:"R",type:"in",q:"A proportional graph passes through (4, 10). Zainab says it must also pass through (10, 25), and she is right. Another point on the graph has x = 14. What is its y-value?",
 ans:35,hint:"Find the constant from (4, 10).",expl:"k = 10 ÷ 4 = 2.5. Check: 10 × 2.5 = 25. So when x = 14, y = 14 × 2.5 = 35."},
{lvl:3,sec:"R",type:"mc",q:"Line A goes through (0, 0) and (2, 9). Line B goes through (0, 0) and (3, 12). Which line has the greater constant of proportionality?",
 opts:["Line A, with k = 4.5","Line B, with k = 4","Both have k = 4.5","Neither is proportional"],a:0,
 expl:"Line A: k = 9 ÷ 2 = 4.5. Line B: k = 12 ÷ 3 = 4. Line A is steeper with the greater constant."}
],

"g7-percentapp": [
{sec:"R",type:"in",q:"A $40 jacket is discounted by 25%. What is the sale price in dollars?",ans:30,
 hint:"You pay 75% of the price.",expl:"25% of $40 is $10, so the sale price is $40 − $10 = $30."},
{sec:"R",type:"in",q:"Aisha deposits $500 at 4% simple interest per year. How much interest does she earn in one year, in dollars?",ans:20,
 expl:"Interest = 500 × 0.04 × 1 = $20."},
{sec:"R",type:"mc",q:"A price is marked up by 30%. Which multiplier gives the new price?",mono:true,opts:["1.3","0.3","0.7","30"],a:0,
 expl:"100% + 30% = 130% = 1.3, so multiply the old price by 1.3."},
{sec:"R",type:"multi",q:"Select EVERY expression that gives the price of an $80 item after a 15% discount.",mono:true,
 opts:["80 − 0.15 × 80","0.85 × 80","80 × 0.15","80 ÷ 0.85"],aMulti:[0,1],
 expl:"Subtracting 15% of 80 from 80, or taking 85% of 80, both give $68. 80 × 0.15 is only the discount, and dividing by 0.85 makes the price bigger."},
{lvl:2,sec:"R",type:"in",q:"A phone costs $240 after a 20% discount. What was the original price in dollars?",ans:300,
 hint:"$240 is 80% of the original.",expl:"The sale price is 80% of the original, so original = 240 ÷ 0.8 = $300."},
{lvl:2,sec:"R",type:"in",q:"Wei borrows $1200 at 5% simple interest per year for 3 years. What total interest does he pay, in dollars?",ans:180,
 hint:"Interest = principal × rate × time.",expl:"1200 × 0.05 × 3 = $180 of interest."},
{lvl:2,sec:"R",type:"mc",q:"A restaurant bill is $60. Sales tax is 8% and the tip is 15%, both worked out on the $60. What is the total paid?",
 opts:["$73.80","$72.60","$73.00","$74.40"],a:0,
 expl:"Tax: 0.08 × 60 = $4.80. Tip: 0.15 × 60 = $9. Total: 60 + 4.80 + 9 = $73.80."},
{lvl:3,sec:"R",type:"in",q:"A store buys a bike for $200, marks it up by 40%, then later discounts the marked-up price by 25%. What is the final price in dollars?",
 ans:210,hint:"Apply the markup first, then the discount to the new price.",
 expl:"After the markup: 200 × 1.4 = $280. After the discount: 280 × 0.75 = $210."},
{lvl:3,sec:"R",type:"mc",q:"Account P pays 6% simple interest per year for 2 years. Account Q pays 4% simple interest per year for 3 years. With the same deposit, which earns more interest?",
 opts:["They earn the same","Account P","Account Q","It depends on the deposit"],a:0,
 hint:"Work out the total percentage earned by each.",
 expl:"P earns 6% × 2 = 12% of the deposit. Q earns 4% × 3 = 12% of the deposit. They earn exactly the same."}
],

"g7-ratops": [
{sec:"N",type:"in",q:"−7 + 12 = ?",ans:5,expl:"Starting at −7 and moving up 12 lands on 5."},
{sec:"N",type:"in",q:"−3.5 − 4.25 = ?",ans:-7.75,hint:"Subtracting a positive moves further left.",expl:"−3.5 − 4.25 = −(3.5 + 4.25) = −7.75."},
{sec:"N",type:"in",q:"(−6) × (−4) = ?",ans:24,expl:"A negative times a negative is positive: (−6) × (−4) = 24."},
{sec:"N",type:"in",q:"−18 ÷ 3 = ?",ans:-6,expl:"18 ÷ 3 = 6, and a negative divided by a positive is negative, so −6."},
{sec:"N",type:"mc",q:"Which expression is equal to 5 − (−3)?",mono:true,opts:["5 + 3","5 − 3","−5 + 3","−5 − 3"],a:0,
 expl:"Subtracting a negative is the same as adding its opposite, so 5 − (−3) = 5 + 3 = 8."},
{lvl:2,sec:"N",type:"in",q:"−2/3 + 1/6 = ? Give a decimal.",ans:-0.5,hint:"Use sixths.",
 expl:"−2/3 = −4/6, and −4/6 + 1/6 = −3/6 = −1/2 = −0.5."},
{lvl:2,sec:"N",type:"mc",q:"What is (−3/4) × (2/5)?",mono:true,opts:["−3/10","3/10","−6/9","−1/2"],a:0,
 expl:"Multiply tops and bottoms: −6/20 = −3/10. Negative times positive is negative."},
{lvl:2,sec:"N",type:"order",q:"Put these numbers in order from smallest to largest.",
 items:["−2.5","−3/2","0.4","−1/4"],ansOrder:["−2.5","−3/2","−1/4","0.4"],
 expl:"−3/2 = −1.5 and −1/4 = −0.25. From smallest: −2.5, −1.5, −0.25, then 0.4."},
{lvl:3,sec:"N",type:"in",q:"The temperature starts at −3°C, drops 1.5°C every hour for 4 hours, then rises 2.25°C. What is the final temperature in °C?",
 ans:-6.75,hint:"Find the total drop first.",expl:"Total drop: 4 × 1.5 = 6. Then −3 − 6 = −9, and −9 + 2.25 = −6.75°C."},
{lvl:3,sec:"N",type:"in",q:"Lior's bank balance is −$44. He deposits $120, then spends 3/4 of the new balance. What is his balance now, in dollars?",
 ans:19,hint:"Find the balance after the deposit, then keep one quarter of it.",
 expl:"−44 + 120 = 76. Spending 3/4 leaves 1/4: 76 × 1/4 = $19."}
],

"g7-todecimal": [
{sec:"N",type:"in",q:"Write 3/8 as a decimal.",ans:0.375,hint:"Divide 3 by 8.",expl:"3 ÷ 8 = 0.375, a terminating decimal."},
{sec:"N",type:"mc",q:"Which fraction gives a repeating decimal?",mono:true,opts:["1/3","1/4","1/5","1/8"],a:0,
 expl:"1/3 = 0.333..., which repeats forever. 1/4 = 0.25, 1/5 = 0.2 and 1/8 = 0.125 all terminate."},
{sec:"N",type:"mc",q:"Which decimal equals 5/6?",mono:true,opts:["0.8333...","0.8555...","0.8666...","0.8"],a:0,
 expl:"5 ÷ 6 = 0.8333..., with the 3 repeating."},
{sec:"N",type:"multi",q:"Select EVERY fraction that terminates as a decimal.",mono:true,
 opts:["7/20","5/12","9/16","4/15"],aMulti:[0,2],
 expl:"7/20 = 0.35 and 9/16 = 0.5625 terminate because 20 and 16 have only 2s and 5s as prime factors. 12 and 15 contain a factor of 3, so 5/12 and 4/15 repeat."},
{sec:"N",type:"in",q:"Write 7/4 as a decimal.",ans:1.75,expl:"7 ÷ 4 = 1.75."},
{lvl:2,sec:"N",type:"mc",q:"A fraction in lowest terms terminates as a decimal exactly when its denominator has which prime factors only?",
 opts:["2 and 5","2 and 3","3 and 5","Any primes"],a:0,
 expl:"A decimal terminates when the denominator divides a power of 10, and 10 = 2 × 5. So only 2s and 5s are allowed."},
{lvl:2,sec:"N",type:"mc",q:"Which fraction equals 0.4545... (with 45 repeating)?",mono:true,opts:["5/11","9/20","45/100","5/12"],a:0,
 hint:"Try dividing the top by the bottom for each option.",
 expl:"5 ÷ 11 = 0.4545... . Also 45/99 simplifies to 5/11."},
{lvl:2,sec:"N",type:"in",q:"Use long division to write 11/40 as a decimal.",ans:0.275,expl:"11 ÷ 40 = 0.275. Check: 40 × 0.275 = 11."},
{lvl:3,sec:"N",type:"in",q:"What is the 50th digit after the decimal point in the decimal expansion of 4/7?",ans:7,
 hint:"Find the repeating block first, then use its length.",
 expl:"4/7 = 0.571428571428..., repeating every 6 digits. 50 = 6 × 8 + 2, so the 50th digit is the 2nd digit of the block, which is 7."},
{lvl:3,sec:"N",type:"in",q:"Write 0.3636... (with 36 repeating) as a fraction in lowest terms. What is its denominator?",ans:11,
 hint:"A two-digit repeating block goes over 99.",expl:"0.3636... = 36/99 = 4/11, so the denominator is 11."}
],

"g7-expand": [
{sec:"L",type:"in",q:"Expand 3(x + 4). What is the constant term?",ans:12,hint:"Multiply 3 by each term inside.",expl:"3(x + 4) = 3x + 12, so the constant term is 12."},
{sec:"L",type:"mc",q:"Expand 5(2x − 3).",mono:true,opts:["10x − 15","10x − 3","7x − 8","10x + 15"],a:0,
 expl:"5 × 2x = 10x and 5 × (−3) = −15, so 5(2x − 3) = 10x − 15."},
{sec:"L",type:"mc",q:"Factor 6x + 9.",mono:true,opts:["3(2x + 3)","6(x + 3)","3(2x + 9)","9(x + 1)"],a:0,
 expl:"The greatest common factor of 6 and 9 is 3: 6x + 9 = 3(2x + 3)."},
{sec:"L",type:"in",q:"Simplify 4(x + 2) + 2x. What is the coefficient of x?",ans:6,expl:"4(x + 2) + 2x = 4x + 8 + 2x = 6x + 8. The coefficient of x is 6."},
{lvl:2,sec:"L",type:"mc",q:"Expand −2(3x − 5).",mono:true,opts:["−6x + 10","−6x − 10","6x − 10","−5x + 3"],a:0,
 hint:"Watch the sign when multiplying by −2.",expl:"−2 × 3x = −6x and −2 × (−5) = +10, so the result is −6x + 10."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY expression equivalent to 12x − 18.",mono:true,
 opts:["6(2x − 3)","3(4x − 6)","2(6x − 9)","6(2x − 18)"],aMulti:[0,1,2],
 expl:"6(2x − 3), 3(4x − 6) and 2(6x − 9) all expand to 12x − 18. 6(2x − 18) = 12x − 108."},
{lvl:2,sec:"L",type:"in",q:"Simplify 3(2x + 1) − 2(x − 4). What is the constant term?",ans:11,
 hint:"Expand both brackets, then collect like terms.",expl:"6x + 3 − 2x + 8 = 4x + 11. The constant term is 11."},
{lvl:3,sec:"L",type:"mc",q:"Factor 0.5x + 1.5 using the greatest common factor.",mono:true,
 opts:["0.5(x + 3)","0.5(x + 1.5)","1.5(x + 1)","5(x + 3)"],a:0,
 expl:"Both terms share the factor 0.5: 0.5x + 1.5 = 0.5(x + 3). Check: 0.5 × 3 = 1.5."},
{lvl:3,sec:"L",type:"in",q:"The expression 4(x + 3) − (x − 7) simplifies to ax + b. What is a + b?",ans:22,
 hint:"Subtracting a bracket changes both signs inside it.",expl:"4x + 12 − x + 7 = 3x + 19, so a = 3, b = 19 and a + b = 22."},
{lvl:3,sec:"L",type:"mc",q:"A rectangle has length 2x + 5 and width 3. Which fully simplified expression gives its perimeter?",mono:true,
 opts:["4x + 16","6x + 15","4x + 10","2x + 8"],a:0,
 expl:"Perimeter = 2(2x + 5) + 2(3) = 4x + 10 + 6 = 4x + 16."}
],

"g7-multistep": [
{sec:"L",type:"in",q:"Solve 3x + 5 = 20.",ans:5,hint:"Undo the +5 first.",expl:"3x = 15, so x = 5."},
{sec:"L",type:"in",q:"Solve 2(x − 4) = 10.",ans:9,hint:"Divide both sides by 2 first.",expl:"x − 4 = 5, so x = 9."},
{sec:"L",type:"order",q:"Put the steps in order to solve 4x − 7 = 13, from first to last.",
 items:["Add 7 to both sides to get 4x = 20","Divide both sides by 4","Write the solution x = 5"],
 ansOrder:["Add 7 to both sides to get 4x = 20","Divide both sides by 4","Write the solution x = 5"],
 expl:"Undo the subtraction first (add 7), then undo the multiplication (divide by 4), which gives x = 5."},
{sec:"L",type:"in",q:"Hana buys 3 notebooks at the same price and a $2 pen, spending $14 in total. What does one notebook cost, in dollars?",ans:4,
 hint:"Take away the pen first.",expl:"3n + 2 = 14, so 3n = 12 and n = $4."},
{lvl:2,sec:"L",type:"in",q:"Solve 0.5x + 3 = 7.5.",ans:9,expl:"0.5x = 4.5, so x = 4.5 ÷ 0.5 = 9."},
{lvl:2,sec:"L",type:"in",q:"Solve (x + 6) ÷ 3 = 4.",ans:6,hint:"Multiply both sides by 3 first.",expl:"x + 6 = 12, so x = 6."},
{lvl:2,sec:"L",type:"mc",q:"Ravi is 3 years older than twice his cousin's age. Ravi is 19. Which equation finds the cousin's age c?",mono:true,
 opts:["2c + 3 = 19","2c − 3 = 19","c + 3 = 19","3c + 2 = 19"],a:0,
 expl:"Twice the cousin's age is 2c, and 3 more than that is 2c + 3, which equals 19. Solving gives c = 8."},
{lvl:3,sec:"L",type:"in",q:"A taxi charges $3 plus $1.50 per km. Sofia paid $16.50. How many km did she travel?",ans:9,
 hint:"Subtract the fixed charge, then divide.",expl:"3 + 1.5k = 16.5, so 1.5k = 13.5 and k = 9 km."},
{lvl:3,sec:"L",type:"in",q:"Three consecutive whole numbers add up to 48. What is the largest of them?",ans:17,
 hint:"Call the smallest n and write the other two in terms of n.",
 expl:"n + (n + 1) + (n + 2) = 3n + 3 = 48, so n = 15. The numbers are 15, 16 and 17, and the largest is 17."},
{lvl:3,sec:"L",type:"mc",q:"A rectangle has perimeter 46 cm and its length is 5 cm more than its width. What is its width?",
 opts:["9 cm","14 cm","11.5 cm","18 cm"],a:0,hint:"Write the length as w + 5 and use the perimeter formula.",
 expl:"2w + 2(w + 5) = 46, so 4w + 10 = 46, 4w = 36 and w = 9 cm."}
],

"g7-eqineq": [
{sec:"L",type:"in",q:"Solve 2x − 3 = 11.",ans:7,expl:"2x = 14, so x = 7."},
{sec:"L",type:"mc",q:"Solve x + 4 > 9.",mono:true,opts:["x > 5","x < 5","x > 13","x ≥ 5"],a:0,
 expl:"Subtract 4 from both sides: x > 5. The sign stays the same."},
{sec:"L",type:"mc",q:"When you multiply or divide both sides of an inequality by a negative number, what must you do?",
 opts:["Reverse the inequality sign","Keep the sign the same","Add the number back","Make both sides positive"],a:0,
 expl:"Multiplying or dividing by a negative flips the order of the numbers, so the inequality sign must be reversed."},
{sec:"L",type:"mc",q:"Which describes the graph of x ≥ −1 on a number line?",
 opts:["Closed circle at −1, shaded to the right","Open circle at −1, shaded to the right","Closed circle at −1, shaded to the left","Open circle at 1, shaded to the right"],a:0,
 expl:"≥ includes −1, so the circle is closed, and the solutions are −1 and everything larger, to the right."},
{lvl:2,sec:"L",type:"mc",q:"Solve −2x + 5 > 11.",mono:true,opts:["x < −3","x > −3","x < 3","x > 8"],a:0,
 hint:"You will need to divide by a negative.",expl:"−2x > 6. Dividing by −2 reverses the sign: x < −3."},
{lvl:2,sec:"L",type:"in",q:"What is the smallest whole number x that satisfies 3x + 2 > 14?",ans:5,
 hint:"Solve the inequality, then pick the first whole number that works.",expl:"3x > 12, so x > 4. The smallest whole number greater than 4 is 5."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY value that satisfies 2x − 1 < 7.",mono:true,
 opts:["−3","0","3.5","4","5"],aMulti:[0,1,2],
 expl:"2x < 8, so x < 4. −3, 0 and 3.5 are less than 4; 4 and 5 are not."},
{lvl:3,sec:"L",type:"in",q:"Yusuf has $50. He wants a $14 book and as many $6 posters as he can afford. What is the greatest number of posters he can buy?",ans:6,
 hint:"Write an inequality with p posters.",expl:"14 + 6p ≤ 50, so 6p ≤ 36 and p ≤ 6. He can buy 6 posters."},
{lvl:3,sec:"L",type:"mc",q:"Ingrid earns $12 per hour. After paying a $28 fee she needs at least $200 left for a trip. Which inequality finds the hours h she must work?",mono:true,
 opts:["12h − 28 ≥ 200","12h + 28 ≥ 200","12h − 28 ≤ 200","28h − 12 ≥ 200"],a:0,
 expl:"Earnings are 12h. After the $28 fee she has 12h − 28, which must be at least 200: 12h − 28 ≥ 200, so h ≥ 19."},
{lvl:3,sec:"L",type:"in",q:"Solve −(x − 4) ÷ 2 ≥ 3. What is the largest possible value of x?",ans:-2,
 hint:"Clear the ÷ 2 first, then deal with the negative sign.",
 expl:"−(x − 4) ≥ 6, so x − 4 ≤ −6 (the sign flips), giving x ≤ −2. The largest value is −2."}
],

"g7-scaledraw": [
{sec:"G",type:"in",q:"A map has scale 1 cm : 5 km. Two towns are 4 cm apart on the map. How far apart are they in km?",ans:20,
 expl:"Each cm stands for 5 km, so 4 cm is 4 × 5 = 20 km."},
{sec:"G",type:"in",q:"A drawing uses scale 1 : 50. A wall is 3 m long in real life. How long is it in the drawing, in cm?",ans:6,
 hint:"Change 3 m to cm first.",expl:"3 m = 300 cm, and 300 ÷ 50 = 6 cm in the drawing."},
{sec:"G",type:"mc",q:"A scale factor of 1/4 is applied to a drawing. What happens?",
 opts:["Every length becomes 1/4 as long","Every length becomes 4 times as long","Only the width changes","The angles become smaller"],a:0,
 expl:"A scale factor multiplies every length by the same amount, here 1/4. Angles never change under scaling."},
{sec:"G",type:"in",q:"On a plan, a room is 6 cm by 4 cm at scale 1 cm : 2 m. What is the real area of the room in square metres?",ans:96,
 hint:"Convert each side to metres before finding the area.",expl:"Real sides are 12 m and 8 m, so the area is 12 × 8 = 96 square metres."},
{lvl:2,sec:"G",type:"in",q:"A model car is 12 cm long and the real car is 4.8 m long. What is the scale factor from model to real (real length ÷ model length)?",ans:40,
 hint:"Use the same unit for both lengths.",expl:"4.8 m = 480 cm, and 480 ÷ 12 = 40. The scale is 1 : 40."},
{lvl:2,sec:"G",type:"mc",q:"A drawing is enlarged by a scale factor of 3. Its area becomes how many times as large?",mono:true,opts:["9","3","6","27"],a:0,
 expl:"Both length and width are tripled, so the area is multiplied by 3 × 3 = 9."},
{lvl:2,sec:"G",type:"in",q:"A rectangle on a scale drawing is 5 cm by 8 cm. The real rectangle has a shorter side of 20 m. What is its longer side in m?",ans:32,
 hint:"Find the scale factor from the shorter side.",expl:"20 ÷ 5 = 4, so each cm is 4 m. The longer side is 8 × 4 = 32 m."},
{lvl:2,sec:"G",type:"order",q:"The same building is drawn at each scale below. Order the drawings from smallest to largest.",
 items:["1 : 200","1 : 50","1 : 100"],ansOrder:["1 : 200","1 : 100","1 : 50"],
 expl:"At 1 : 200 each drawn cm stands for 200 cm, so the drawing is tiny. 1 : 100 is twice as big and 1 : 50 is biggest."},
{lvl:3,sec:"G",type:"in",q:"Map A has scale 1 cm : 4 km and Map B has scale 1 cm : 10 km. A road is 15 cm long on Map A. How long is it on Map B, in cm?",ans:6,
 hint:"Find the real length first.",expl:"Real length: 15 × 4 = 60 km. On Map B: 60 ÷ 10 = 6 cm."},
{lvl:3,sec:"G",type:"in",q:"A drawing of a garden is 10 cm by 7 cm at scale 1 : 300. Fencing costs $8 per metre. What does it cost to fence the whole real garden, in dollars?",
 ans:816,hint:"Find the real sides in metres, then the perimeter.",
 expl:"Real sides: 10 × 300 = 3000 cm = 30 m and 7 × 300 = 2100 cm = 21 m. Perimeter = 2(30 + 21) = 102 m, costing 102 × 8 = $816."}
],

"g7-construct": [
{sec:"G",type:"mc",q:"Can a triangle have sides of 3 cm, 4 cm and 8 cm?",
 opts:["No, because 3 + 4 < 8","Yes, any three lengths work","Yes, because 8 is the longest","No, because 8 is even"],a:0,
 expl:"The two shorter sides must add to more than the longest side. 3 + 4 = 7 is less than 8, so the sides cannot meet."},
{sec:"G",type:"mc",q:"Which set of angles can form a triangle?",
 opts:["60°, 70°, 50°","90°, 90°, 10°","100°, 50°, 40°","45°, 45°, 100°"],a:0,
 expl:"The angles of a triangle add to 180°. Only 60 + 70 + 50 = 180 works; the others add to 190°."},
{sec:"G",type:"in",q:"Two angles of a triangle are 35° and 80°. What is the third angle in degrees?",ans:65,
 expl:"180 − 35 − 80 = 65°."},
{sec:"G",type:"multi",q:"Select EVERY set of side lengths that can form a triangle.",mono:true,
 opts:["5, 5, 9","2, 3, 5","7, 10, 4","1, 1, 3"],aMulti:[0,2],
 expl:"5 + 5 > 9 and 4 + 7 > 10, so those work. 2 + 3 = 5 makes a flat line, and 1 + 1 < 3 cannot close."},
{lvl:2,sec:"G",type:"mc",q:"Three side lengths are given and they can form a triangle. How many different triangles can be made from them?",
 opts:["Exactly one","Exactly two","Infinitely many","None"],a:0,
 expl:"Three side lengths fix the triangle completely: any triangle with those sides is a copy of the same shape."},
{lvl:2,sec:"G",type:"mc",q:"Only three angles are given: 50°, 60° and 70°. How many different-sized triangles can be drawn with these angles?",
 opts:["Infinitely many","Exactly one","Exactly three","None"],a:0,
 expl:"Angles fix the shape but not the size. The triangle can be scaled up or down, so there are infinitely many."},
{lvl:2,sec:"G",type:"in",q:"Two sides of a triangle are 6 cm and 10 cm. What is the largest whole-number length, in cm, that the third side can have?",ans:15,
 hint:"The third side must be shorter than the other two added together.",expl:"The third side must be less than 6 + 10 = 16, so the largest whole number is 15 cm."},
{lvl:3,sec:"G",type:"in",q:"Two sides of a triangle are 6 cm and 10 cm. How many different whole-number lengths, in cm, are possible for the third side?",ans:11,
 hint:"Find both the smallest and the largest possible length.",
 expl:"The third side must be more than 10 − 6 = 4 and less than 6 + 10 = 16, so it can be any whole number from 5 to 15. That is 11 lengths."},
{lvl:3,sec:"G",type:"mc",q:"Tomas draws a triangle with two sides of 5 cm and a 40° angle between them. Which is true?",
 opts:["Exactly one triangle is possible","Two different triangles are possible","No triangle is possible","Infinitely many triangles are possible"],a:0,
 expl:"Two sides and the angle between them fix the triangle: the third side must join the ends of the two given sides in one way."},
{lvl:3,sec:"G",type:"in",q:"An isosceles triangle has a 40° angle between its two equal sides. Diego draws a line that cuts this angle in half and reaches the opposite side. What is the largest angle, in degrees, in each of the two smaller triangles?",
 ans:90,hint:"Find the base angles first, then the angles of one small triangle.",
 expl:"The base angles are (180 − 40) ÷ 2 = 70° each. Each small triangle has angles 20°, 70° and 180 − 20 − 70 = 90°. The largest is 90°."}
],

"g7-circles": [
{sec:"G",type:"in",q:"A circle has radius 5 cm. Using π ≈ 3.14, what is its circumference in cm?",ans:31.4,
 hint:"Circumference = 2πr.",expl:"C = 2 × 3.14 × 5 = 31.4 cm."},
{sec:"G",type:"in",q:"A circle has diameter 10 cm. Using π ≈ 3.14, what is its area in square cm?",ans:78.5,
 hint:"Use the radius, not the diameter.",expl:"r = 5, so A = 3.14 × 5 × 5 = 78.5 square cm."},
{sec:"G",type:"mc",q:"Which formula gives the area of a circle?",mono:true,opts:["πr²","2πr","πd","πr"],a:0,
 expl:"Area = π × radius squared. 2πr and πd both give the circumference."},
{lvl:2,sec:"G",type:"in",q:"A circular pond has circumference 62.8 m. Using π ≈ 3.14, what is its diameter in m?",ans:20,
 hint:"Circumference = π × diameter.",expl:"d = 62.8 ÷ 3.14 = 20 m."},
{lvl:2,sec:"G",type:"mc",q:"A circle has area 49π square cm. What is its circumference?",mono:true,opts:["14π cm","7π cm","49π cm","98π cm"],a:0,
 expl:"πr² = 49π gives r = 7, so C = 2π × 7 = 14π cm."},
{lvl:2,sec:"G",type:"in",q:"A semicircle has radius 4 cm. Using π ≈ 3.14, what is its area in square cm?",ans:25.12,
 hint:"Find the full circle's area, then halve it.",expl:"Full circle: 3.14 × 16 = 50.24. Half of that is 25.12 square cm."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY statement that is true for all circles.",
 opts:["Circumference ÷ diameter = π","Diameter = 2 × radius","Area = circumference × radius","Area = π × diameter²"],aMulti:[0,1],
 expl:"π is defined as circumference ÷ diameter, and the diameter is twice the radius. Area is πr², which is half of circumference × radius, and π × d² would be four times too big."},
{lvl:3,sec:"G",type:"in",q:"A wheel has diameter 70 cm. Using π ≈ 3.14, how many full turns does it make travelling 439.6 m?",ans:200,
 hint:"One turn covers one circumference. Watch the units.",
 expl:"Circumference = 3.14 × 70 = 219.8 cm = 2.198 m. 439.6 ÷ 2.198 = 200 turns."},
{lvl:3,sec:"G",type:"in",q:"The largest possible circle is cut from a square of side 10 cm. Using π ≈ 3.14, what area in square cm is left over?",ans:21.5,
 hint:"The circle's diameter equals the side of the square.",
 expl:"The circle has radius 5, area 3.14 × 25 = 78.5. The square is 100, so 100 − 78.5 = 21.5 square cm is left."},
{lvl:3,sec:"G",type:"mc",q:"Which has the greater total area: one circle of radius 6 cm, or two circles of radius 3 cm each?",
 opts:["The radius-6 circle, by 18π square cm","The two radius-3 circles, by 18π square cm","They have equal area","The radius-6 circle, by 9π square cm"],a:0,
 expl:"Radius 6: 36π. Two of radius 3: 2 × 9π = 18π. The single big circle has 36π − 18π = 18π more."}
],

"g7-anglerel": [
{sec:"G",type:"in",q:"Two angles are complementary. One is 35°. What is the other, in degrees?",ans:55,
 hint:"Complementary angles add to a right angle.",expl:"90 − 35 = 55°."},
{sec:"G",type:"in",q:"Two angles are supplementary. One is 112°. What is the other, in degrees?",ans:68,
 hint:"Supplementary angles make a straight line.",expl:"180 − 112 = 68°."},
{sec:"G",type:"mc",q:"Two straight lines cross. One of the angles is 50°. What is the angle vertically opposite it?",
 opts:["50°","130°","40°","100°"],a:0,
 expl:"Vertically opposite angles are equal, so it is also 50°. The angles next to it are 130°."},
{sec:"G",type:"mc",q:"Angles x and y are adjacent and together form a straight line. Which must be true?",mono:true,
 opts:["x + y = 180°","x + y = 90°","x = y","x + y = 360°"],a:0,
 expl:"Angles on a straight line add to 180°, so x + y = 180°."},
{lvl:2,sec:"G",type:"in",q:"Two angles are complementary and one is twice the other. What is the larger angle, in degrees?",ans:60,
 hint:"Call the smaller angle x.",expl:"x + 2x = 90, so x = 30 and the larger angle is 60°."},
{lvl:2,sec:"G",type:"in",q:"Angles of (3x + 10)° and (2x − 5)° are supplementary. What is x?",ans:35,
 hint:"Add the expressions and set them equal to 180.",expl:"3x + 10 + 2x − 5 = 5x + 5 = 180, so 5x = 175 and x = 35."},
{lvl:2,sec:"G",type:"multi",q:"Two straight lines cross, making angles of 70° and 110°. Select EVERY true statement.",
 opts:["The 70° and 110° angles are supplementary","There are two 70° angles","The 70° and 110° angles are vertical angles","There are three 110° angles"],aMulti:[0,1],
 expl:"Crossing lines make two pairs of equal vertical angles: two 70° and two 110°. A 70° next to a 110° makes a straight line, so they are supplementary, not vertical."},
{lvl:3,sec:"G",type:"in",q:"Three angles fit together along a straight line: 2x°, (x + 20)° and (x − 8)°. What is x?",ans:42,
 hint:"The three angles add to a straight angle.",expl:"2x + x + 20 + x − 8 = 4x + 12 = 180, so 4x = 168 and x = 42."},
{lvl:3,sec:"G",type:"in",q:"Two lines cross. One angle is (4x − 20)° and the angle vertically opposite it is (2x + 30)°. What is the size, in degrees, of an angle adjacent to them?",ans:100,
 hint:"Vertical angles are equal; use that to find x first.",
 expl:"4x − 20 = 2x + 30 gives x = 25, so the angle is 4(25) − 20 = 80°. The adjacent angle is 180 − 80 = 100°."},
{lvl:3,sec:"G",type:"mc",q:"Angle A is complementary to angle B, and angle B is supplementary to angle C. Angle A is 25°. What is angle C?",
 opts:["115°","65°","155°","25°"],a:0,hint:"Find angle B first.",
 expl:"B = 90 − 25 = 65°. Then C = 180 − 65 = 115°."}
],

"g7-solids": [
{sec:"G",type:"in",q:"A box is 3 cm by 4 cm by 5 cm. What is its volume in cubic cm?",ans:60,expl:"Volume = 3 × 4 × 5 = 60 cubic cm."},
{sec:"G",type:"in",q:"A cube has edges of 3 cm. What is its surface area in square cm?",ans:54,
 hint:"A cube has six identical faces.",expl:"Each face is 3 × 3 = 9, and 6 × 9 = 54 square cm."},
{sec:"G",type:"in",q:"A triangular prism has a base triangle of area 12 square cm and a length of 10 cm. What is its volume in cubic cm?",ans:120,
 hint:"Volume of a prism = base area × length.",expl:"12 × 10 = 120 cubic cm."},
{lvl:2,sec:"G",type:"in",q:"A rectangular box is 8 cm by 3 cm by 2 cm. What is its surface area in square cm?",ans:92,
 hint:"There are three pairs of matching faces.",expl:"Faces: 8 × 3 = 24, 8 × 2 = 16, 3 × 2 = 6. Surface area = 2(24 + 16 + 6) = 92 square cm."},
{lvl:2,sec:"G",type:"in",q:"A triangular prism has a right-triangle base with sides 3 cm, 4 cm and 5 cm, and it is 10 cm long. What is its total surface area in square cm?",ans:132,
 hint:"Two triangles plus three rectangles.",
 expl:"Each triangle: 1/2 × 3 × 4 = 6, so 12 for both. Rectangles: (3 + 4 + 5) × 10 = 120. Total 12 + 120 = 132 square cm."},
{lvl:2,sec:"G",type:"mc",q:"A cube has volume 64 cubic cm. What is its surface area?",
 opts:["96 square cm","64 square cm","48 square cm","16 square cm"],a:0,hint:"Find the edge length first.",
 expl:"4 × 4 × 4 = 64, so each edge is 4 cm. Surface area = 6 × 16 = 96 square cm."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY solid with a volume of 48 cubic cm.",
 opts:["A 2 cm by 4 cm by 6 cm box","A cube with 4 cm edges","A prism with base area 8 square cm and height 6 cm","A 3 cm by 4 cm by 5 cm box"],aMulti:[0,2],
 expl:"2 × 4 × 6 = 48 and 8 × 6 = 48. The cube is 64 and the last box is 60."},
{lvl:3,sec:"G",type:"in",q:"An open-topped cardboard box is 10 cm long, 6 cm wide and 4 cm tall. How much cardboard is needed, in square cm?",ans:188,
 hint:"There is no top face.",expl:"Bottom: 10 × 6 = 60. Sides: 2(10 × 4) + 2(6 × 4) = 80 + 48 = 128. Total 60 + 128 = 188 square cm."},
{lvl:3,sec:"G",type:"in",q:"A box 12 cm by 8 cm by 5 cm is packed with solid cubes of edge 2 cm. What is the greatest number of cubes that fit?",ans:48,
 hint:"Think about how many cubes fit along each edge, not just the volumes.",
 expl:"Along the edges: 12 ÷ 2 = 6, 8 ÷ 2 = 4, and only 2 layers fit in 5 cm. So 6 × 4 × 2 = 48 cubes (dividing the volumes would wrongly give 60)."},
{lvl:3,sec:"G",type:"mc",q:"Every edge of a cube is doubled. By what factors are its surface area and its volume multiplied?",
 opts:["Area × 4, volume × 8","Area × 2, volume × 2","Area × 8, volume × 4","Area × 2, volume × 8"],a:0,
 expl:"Each face's area is multiplied by 2 × 2 = 4, and the volume by 2 × 2 × 2 = 8."}
],

"g7-sampling": [
{sec:"S",type:"mc",q:"A school wants to know students' favourite lunch. Which sample is most likely to represent the whole school?",
 opts:["50 students picked at random from the whole school","50 students from the football team","50 students found in the library","The first 50 students who volunteer"],a:0,
 expl:"A random sample from the whole population gives every student the same chance of being chosen, so it is most likely to be representative."},
{sec:"S",type:"mc",q:"Why do statisticians usually study a sample instead of the whole population?",
 opts:["Surveying everyone is often too costly or slow","Samples are always more accurate","Populations are always too small","Samples remove all uncertainty"],a:0,
 expl:"Reaching every member of a large population takes too much time and money, and a good random sample gives a useful estimate."},
{sec:"S",type:"in",q:"In a random sample of 40 marbles from a jar, 6 are red. The jar holds 600 marbles. Estimate how many are red.",ans:90,
 hint:"Find the fraction of the sample that is red.",expl:"6/40 of the sample is red, so about 6/40 × 600 = 90 red marbles."},
{sec:"S",type:"multi",q:"Select EVERY method that gives a random sample of a school's students.",
 opts:["Draw names from a box of all students","Use a random-number generator on student IDs","Ask your closest friends","Survey people leaving the gym"],aMulti:[0,1],
 expl:"Drawing names or random IDs gives every student an equal chance. Friends and gym users are chosen for a reason, so they are not random."},
{lvl:2,sec:"S",type:"in",q:"Earlier, 200 fish in a lake were tagged. A later random sample of 50 fish includes 4 tagged fish. Estimate the total number of fish in the lake.",ans:2500,
 hint:"The fraction tagged in the sample estimates the fraction tagged in the lake.",
 expl:"4/50 of the sample is tagged, so 200 tagged fish should be 4/50 of the lake: 200 ÷ 4 × 50 = 2500 fish."},
{lvl:2,sec:"S",type:"mc",q:"Two random samples of 20 students each gave mean heights of 152 cm and 155 cm. What best explains the difference?",
 opts:["Random samples naturally vary","One sample was measured wrongly","The population changed between samples","Larger means come from larger samples"],a:0,
 expl:"Different random samples give slightly different results. This sampling variability is expected and is not a mistake."},
{lvl:2,sec:"S",type:"mc",q:"Which change makes an estimate from a random sample more reliable?",
 opts:["Taking a larger random sample","Taking a smaller random sample","Choosing only volunteers","Sampling only one class"],a:0,
 expl:"Larger random samples vary less from sample to sample, so their estimates are closer to the true population value."},
{lvl:3,sec:"S",type:"in",q:"In a random sample of 80 voters, 36 support building a park. The town has 6000 voters. Estimate how many support the park.",ans:2700,
 hint:"Write the sample support as a fraction of 80.",expl:"36/80 = 0.45, and 0.45 × 6000 = 2700 voters."},
{lvl:3,sec:"S",type:"mc",q:"Noor surveys 100 people at a train station at 8 am, asking whether they drive to work. What is the biggest problem with her sample?",
 opts:["People at a station are unlikely to be typical","100 people is far too few","She asked at the wrong time of year","She should have asked only drivers"],a:0,
 expl:"People at a train station at 8 am are mostly taking the train, so the sample is biased and does not represent all workers."},
{lvl:3,sec:"S",type:"in",q:"A batch has 2000 light bulbs. One random sample of 25 bulbs has 2 faulty; a second random sample of 25 has 3 faulty. Using both samples together, estimate the number of faulty bulbs in the batch.",
 ans:200,hint:"Combine the two samples into one before estimating.",
 expl:"Together: 5 faulty out of 50, which is 1/10. So about 1/10 × 2000 = 200 faulty bulbs."}
],

"g7-probmodel": [
{sec:"S",type:"in",q:"A fair six-sided die is rolled. What is the probability of rolling an even number? Give a decimal.",ans:0.5,
 expl:"Three of the six outcomes (2, 4, 6) are even, so P = 3/6 = 0.5."},
{sec:"S",type:"mc",q:"A bag has 3 red, 2 blue and 5 green marbles. One is picked at random. What is the probability it is blue?",mono:true,
 opts:["1/5","2/5","1/2","2/8"],a:0,
 expl:"There are 10 marbles and 2 are blue: 2/10 = 1/5."},
{sec:"S",type:"in",q:"A spinner has 8 equal sections numbered 1 to 8. What is the probability of spinning a multiple of 4? Give a decimal.",ans:0.25,
 hint:"Which numbers from 1 to 8 are multiples of 4?",expl:"4 and 8 are multiples of 4, so P = 2/8 = 0.25."},
{sec:"S",type:"mc",q:"An event has probability 0.9. Which describes it best?",
 opts:["Likely but not certain","Certain","Unlikely","Impossible"],a:0,
 expl:"0.9 is close to 1 but not equal to it, so the event is likely but could still fail to happen."},
{lvl:2,sec:"S",type:"in",q:"A fair coin is flipped 200 times. About how many heads would you expect?",ans:100,
 expl:"P(heads) = 1/2, so expect 1/2 × 200 = 100 heads."},
{lvl:2,sec:"S",type:"mc",q:"A drawing pin is dropped 50 times and lands point-up 30 times. What is the best estimate of the probability that it lands point-up?",mono:true,
 opts:["0.6","0.5","0.3","0.4"],a:0,
 expl:"Experimental probability = 30/50 = 0.6."},
{lvl:2,sec:"S",type:"multi",q:"A bag holds 4 white and 6 black counters. One is drawn at random. Select EVERY correct statement.",mono:true,
 opts:["P(black) = 0.6","P(white) = 0.4","P(white or black) = 1","P(black) = 0.5","P(white) = 4/6"],aMulti:[0,1,2],
 expl:"There are 10 counters. P(black) = 6/10 = 0.6, P(white) = 4/10 = 0.4, and every counter is white or black, so that probability is 1."},
{lvl:2,sec:"S",type:"mc",q:"A model says P(red) = 1/4 for a spinner. In 40 spins it lands on red 12 times. Which statement fits best?",
 opts:["12 out of 40 is close to 1/4, as expected","The spinner must be unfair","The model predicted exactly 12 reds","Probability cannot be tested"],a:0,
 expl:"The model predicts about 10 reds in 40 spins. Getting 12 is a normal amount of variation, not evidence that the spinner is unfair."},
{lvl:3,sec:"S",type:"in",q:"A bag has only red and blue marbles. P(red) = 0.35 and there are 26 blue marbles. How many marbles are in the bag?",ans:40,
 hint:"Find P(blue) first.",expl:"P(blue) = 1 − 0.35 = 0.65. If 0.65 of the bag is 26 marbles, the bag holds 26 ÷ 0.65 = 40 marbles."},
{lvl:3,sec:"S",type:"in",q:"Elias rolls a fair die 300 times. How many more times should he expect a number greater than 2 than a number less than 2?",ans:150,
 hint:"Work out each expected count separately.",
 expl:"Greater than 2: 4/6 × 300 = 200 times. Less than 2 (only a 1): 1/6 × 300 = 50 times. The difference is 200 − 50 = 150."},
{lvl:3,sec:"S",type:"mc",q:"A spinner has three unequal sections A, B and C. P(A) = 0.5 and P(B) is twice P(C). What is P(C)?",mono:true,
 opts:["1/6","1/3","1/4","1/5"],a:0,hint:"The three probabilities add to 1.",
 expl:"P(B) + P(C) = 0.5. If P(C) = c then 2c + c = 3c = 0.5, so c = 1/6."}
],

"g7-compound": [
{sec:"S",type:"in",q:"Two fair coins are flipped. What is the probability that both land heads? Give a decimal.",ans:0.25,
 hint:"List all the outcomes first.",expl:"The outcomes are HH, HT, TH, TT. Only one of four is HH, so P = 1/4 = 0.25."},
{sec:"S",type:"mc",q:"A coin is flipped and a six-sided die is rolled. How many outcomes are in the sample space?",mono:true,opts:["12","8","6","2"],a:0,
 expl:"2 coin results × 6 die results = 12 outcomes."},
{sec:"S",type:"in",q:"Two fair dice are rolled. How many of the 36 outcomes have a total of 7?",ans:6,
 hint:"List the pairs that add to 7.",expl:"(1,6), (2,5), (3,4), (4,3), (5,2) and (6,1): six outcomes."},
{sec:"S",type:"multi",q:"A coin is flipped twice. Select EVERY outcome that includes at least one tail.",mono:true,
 opts:["HH","HT","TH","TT"],aMulti:[1,2,3],
 expl:"HT, TH and TT each contain a tail. Only HH has none."},
{lvl:2,sec:"S",type:"mc",q:"A spinner with 4 equal colours is spun twice. What is the probability of getting the same colour both times?",mono:true,
 opts:["1/4","1/16","1/2","1/8"],a:0,
 expl:"There are 16 equally likely pairs and 4 of them match (red-red, blue-blue, and so on): 4/16 = 1/4."},
{lvl:2,sec:"S",type:"in",q:"Three fair coins are flipped. What is the probability of exactly two heads? Give a decimal.",ans:0.375,
 hint:"There are 8 outcomes in total.",expl:"HHT, HTH and THH are the outcomes with exactly two heads: 3/8 = 0.375."},
{lvl:2,sec:"S",type:"in",q:"A bag has 2 red and 3 blue marbles. Mei picks one, puts it back, and picks again. What is the probability that both picks are blue? Give a decimal.",ans:0.36,
 hint:"Putting the marble back means the second pick has the same chances as the first.",expl:"P(blue) = 3/5 each time, so P(both blue) = 3/5 × 3/5 = 9/25 = 0.36."},
{lvl:3,sec:"S",type:"in",q:"Leila picks two marbles without replacement from a bag with 3 green and 2 yellow marbles. What is the probability that both are green? Give a decimal.",ans:0.3,
 hint:"After the first green is taken, both the count of greens and the total change.",
 expl:"P(first green) = 3/5. Then 2 greens remain out of 4: P = 2/4. So 3/5 × 2/4 = 6/20 = 0.3."},
{lvl:3,sec:"S",type:"in",q:"A basketball player scores 70% of free throws. A simulation uses a random digit 0-9 for each throw, with 0-6 meaning a hit, and runs three throws 1000 times. About how many trials should show three hits?",
 ans:343,hint:"Find the probability of three hits in a row, then scale to 1000 trials.",
 expl:"P(hit) = 7/10. P(three hits) = 0.7 × 0.7 × 0.7 = 0.343, so about 0.343 × 1000 = 343 trials."},
{lvl:3,sec:"S",type:"mc",q:"Two fair dice are rolled. Which is more likely: a total of 8, or a product of 12?",
 opts:["A total of 8, with 5 outcomes out of 36","A product of 12, with 5 outcomes out of 36","They are equally likely","A product of 12, with 6 outcomes out of 36"],a:0,
 hint:"List the ordered pairs for each event.",
 expl:"Total 8: (2,6), (3,5), (4,4), (5,3), (6,2) — five outcomes. Product 12: (2,6), (3,4), (4,3), (6,2) — four outcomes. A total of 8 is more likely."}
]
};
