/* Grade 7. */
export const G7_BANKS = {
"g7-unitfrac": [
{sec:"R",type:"in",q:"A hose fills 3/4 of a tank in 1/2 hour. At that rate, how many tanks per hour? Type as a decimal.",
 ans:1.5,hint:"Divide the fraction of tank by the fraction of hour.",
 expl:"(3/4) ÷ (1/2) = 3/4 × 2 = 1.5 tanks per hour."},
{sec:"R",type:"in",q:"A recipe uses 1/2 cup of oil for every 1/4 cup of vinegar. How many cups of oil per cup of vinegar?",
 ans:2,expl:"(1/2) ÷ (1/4) = 1/2 × 4 = 2."},
{sec:"R",type:"mc",q:"Which expression finds the unit rate for '2/3 mile in 1/3 hour'?",mono:true,
 opts:["(2/3) ÷ (1/3)","(1/3) ÷ (2/3)","(2/3) × (1/3)","(2/3) + (1/3)"],a:0,
 expl:"A unit rate is 'amount per one hour', so divide the miles by the hours."},
{sec:"R",type:"in",q:"A painter covers 1/4 of a wall in 1/8 hour. How many walls per hour?",
 ans:2,expl:"(1/4) ÷ (1/8) = 1/4 × 8 = 2."},
{sec:"R",type:"in",q:"3/8 of a pizza feeds 1/2 of a group. How many pizzas would feed the WHOLE group? Type as a decimal.",
 ans:0.75,expl:"(3/8) ÷ (1/2) = 3/8 × 2 = 6/8 = 0.75."},
{lvl:2,sec:"R",type:"in",q:"A car uses 3/5 gallon to go 1/4 of a trip. How many gallons for the WHOLE trip?",
 ans:2.4,expl:"(3/5) ÷ (1/4) = 3/5 × 4 = 12/5 = 2.4."},
{lvl:2,sec:"R",type:"in",q:"A worker paints 5/6 of a room in 2/3 hour. How many rooms per hour? Type as a decimal.",
 ans:1.25,expl:"(5/6) ÷ (2/3) = 5/6 × 3/2 = 15/12 = 1.25."},
{lvl:3,sec:"R",type:"in",q:"A hose fills 5/8 of a tank in 5/6 hour. At that rate, how many tanks per hour? Type as a decimal.",
 ans:0.75,expl:"(5/8) ÷ (5/6) = 5/8 × 6/5 = 30/40 = 0.75."}
],

"g7-propor": [
{sec:"R",type:"mc",q:"A table shows: x = 2, y = 6;  x = 4, y = 12;  x = 6, y = 18. Is y proportional to x?",
 opts:["Yes, y = 3x","No","Only sometimes","Cannot tell"],a:0,
 expl:"y ÷ x is always 3, a constant ratio — that is what makes it proportional."},
{sec:"R",type:"in",q:"If y is proportional to x with constant of proportionality 5, what is y when x = 8?",
 ans:40,expl:"y = 5 × 8 = 40."},
{sec:"R",type:"mc",q:"Which equation shows a proportional relationship?",mono:true,
 opts:["y = 4x","y = 4x + 1","y = x²","y = 4/x"],a:0,
 expl:"A proportional relationship has the form y = kx, with no added constant and no exponent."},
{sec:"R",type:"in",q:"A recipe is proportional: 3 cups of flour makes 12 cookies. How many cookies from 5 cups of flour?",
 ans:20,hint:"Find cookies per cup first.",expl:"12 ÷ 3 = 4 cookies per cup, and 4 × 5 = 20."},
{sec:"R",type:"mc",q:"On a graph, a proportional relationship always passes through which point?",mono:true,
 opts:["(0, 0)","(1, 1)","(0, 1)","(1, 0)"],a:0,
 expl:"y = kx always gives y = 0 when x = 0, so the line passes through the origin."},
{lvl:2,sec:"R",type:"in",q:"y is proportional to x. When x = 6, y = 15. What is the constant of proportionality? Type as a decimal.",
 ans:2.5,expl:"15 ÷ 6 = 2.5."},
{lvl:2,sec:"R",type:"mc",q:"Which table is NOT proportional?",mono:true,
 opts:["x: 1, 2, 3  y: 5, 10, 16","x: 1, 2, 3  y: 5, 10, 15","x: 2, 4, 6  y: 3, 6, 9","x: 1, 2, 3  y: 2, 4, 6"],a:0,
 expl:"Every other table keeps y ÷ x constant. The first one breaks the pattern at 16."},
{lvl:3,sec:"R",type:"in",q:"A car uses gas proportionally to distance: 8 gallons for 200 miles. How many gallons for 350 miles?",
 ans:14,hint:"Find the gallons per mile first.",
 expl:"8 ÷ 200 = 0.04 gallons per mile, and 0.04 × 350 = 14."}
],

"g7-ratops": [
{sec:"N",type:"in",q:"−8 + 5 = ?",ans:-3,expl:"−8 + 5 = −3."},
{sec:"N",type:"in",q:"−3 − 7 = ?",ans:-10,expl:"−3 − 7 = −10."},
{sec:"N",type:"in",q:"−4 × −6 = ?",ans:24,expl:"A negative times a negative is positive: −4 × −6 = 24."},
{sec:"N",type:"mc",q:"What is −12 ÷ 4?",opts:["−3","3","−48","48"],a:0,
 expl:"A negative divided by a positive is negative: −12 ÷ 4 = −3."},
{sec:"N",type:"in",q:"6 + (−9) = ?",ans:-3,expl:"6 + (−9) = −3."},
{lvl:2,sec:"N",type:"in",q:"−2.5 + 4.75 = ?",ans:2.25,expl:"−2.5 + 4.75 = 2.25."},
{lvl:2,sec:"N",type:"in",q:"(−3) × (−2) × (−1) = ?",ans:-6,
 hint:"Multiply two at a time.",expl:"(−3) × (−2) = 6, and 6 × (−1) = −6."},
{lvl:3,sec:"N",type:"in",q:"A submarine at −120 feet rises 45 feet, then dives 60 feet. What is its final depth?",
 ans:-135,expl:"−120 + 45 = −75, then −75 − 60 = −135."}
],

"g7-percentapp": [
{sec:"R",type:"in",q:"A shirt costs $40 and is marked up 25%. What is the new price?",ans:50,
 expl:"25% of $40 is $10, so the new price is $40 + $10 = $50."},
{sec:"R",type:"in",q:"A jacket costs $80 with a 15% discount. What is the sale price?",ans:68,
 expl:"15% of $80 is $12, so the sale price is $80 − $12 = $68."},
{sec:"R",type:"in",q:"You invest $200 at 5% simple interest for 1 year. How much interest do you earn?",
 ans:10,expl:"5% of $200 is $10."},
{sec:"R",type:"mc",q:"Which expression finds the total price after a 20% markup on $50?",mono:true,
 opts:["50 × 1.20","50 × 0.20","50 − 20","50 × 0.80"],a:0,
 expl:"A 20% markup means the new price is 120% of the original: 50 × 1.20."},
{sec:"R",type:"in",q:"A $60 item is discounted 10%. What is the discount amount in dollars?",ans:6,
 expl:"10% of $60 is $6."},
{lvl:2,sec:"R",type:"in",q:"A price increases from $40 to $50. What is the percent increase?",ans:25,
 expl:"The increase is $10 on an original $40: 10/40 = 25%."},
{lvl:2,sec:"R",type:"in",q:"You borrow $500 at 8% simple interest for 2 years. How much interest do you owe?",
 ans:80,expl:"500 × 0.08 × 2 = 80."},
{lvl:3,sec:"R",type:"in",q:"A $100 item is discounted 20%, then the sale price is marked up 20%. What is the final price?",
 ans:96,expl:"$100 × 0.80 = $80 after the discount, then $80 × 1.20 = $96 after the markup."}
],

"g7-todecimal": [
{sec:"N",type:"in",q:"Write 1/4 as a decimal.",ans:0.25,expl:"1 ÷ 4 = 0.25."},
{sec:"N",type:"in",q:"Write 1/3 as a decimal, rounded to 3 places.",ans:0.333,expl:"1 ÷ 3 = 0.333..., which repeats forever."},
{sec:"N",type:"mc",q:"Which fraction has a TERMINATING decimal?",mono:true,opts:["1/8","1/3","1/7","1/6"],a:0,
 expl:"1/8 = 0.125 stops. 1/3, 1/7 and 1/6 all repeat forever."},
{sec:"N",type:"in",q:"Write 3/8 as a decimal.",ans:0.375,expl:"3 ÷ 8 = 0.375."},
{sec:"N",type:"mc",q:"Which fraction has a REPEATING decimal?",mono:true,opts:["1/6","1/4","1/5","1/2"],a:0,
 expl:"1/6 = 0.1666..., which repeats. The others terminate."},
{lvl:2,sec:"N",type:"in",q:"Write 5/8 as a decimal.",ans:0.625,expl:"5 ÷ 8 = 0.625."},
{lvl:2,sec:"N",type:"mc",q:"Why does 1/3 have a repeating decimal but 1/4 does not?",
 opts:["4 is built only from 2's, but 3 is a different prime","Because 1/3 is the bigger fraction","Because 1/4 happens to be even","There is no real reason for it"],a:0,
 expl:"A fraction terminates exactly when its denominator's only prime factors are 2 and/or 5. 4 = 2×2 qualifies; 3 does not."},
{lvl:3,sec:"N",type:"in",q:"Write 7/8 as a decimal.",ans:0.875,expl:"7 ÷ 8 = 0.875."}
],

"g7-expand": [
{sec:"P",type:"mc",q:"Expand: 3(x + 5)",mono:true,opts:["3x + 15","3x + 5","x + 15","3x + 8"],a:0,
 expl:"Distribute: 3 × x + 3 × 5 = 3x + 15."},
{sec:"P",type:"mc",q:"Expand: −2(x − 4)",mono:true,opts:["−2x + 8","−2x − 8","−2x + 4","2x − 8"],a:0,
 expl:"−2 × x + (−2) × (−4) = −2x + 8."},
{sec:"P",type:"mc",q:"Factor: 4x + 12",mono:true,opts:["4(x + 3)","4(x + 12)","x(4 + 12)","2(2x + 12)"],a:0,
 expl:"4 is the greatest common factor of 4x and 12: 4(x + 3) = 4x + 12."},
{sec:"P",type:"in",q:"Expand 5(2x + 3) and find the coefficient of x.",ans:10,
 expl:"5 × 2x = 10x, so the coefficient is 10."},
{sec:"P",type:"mc",q:"Factor: 6x + 9",mono:true,opts:["3(2x + 3)","3(2x + 9)","6(x + 9)","9(6x + 1)"],a:0,
 expl:"3 is the GCF of 6x and 9: 3(2x + 3) = 6x + 9."},
{lvl:2,sec:"P",type:"mc",q:"Expand (x + 2)(x + 3) — just find the constant term.",mono:true,
 opts:["6","5","2","3"],a:0,expl:"The constant term comes from 2 × 3 = 6."},
{lvl:2,sec:"P",type:"in",q:"Factor 15x + 25, and find the GCF used.",ans:5,expl:"5 is the greatest common factor of 15 and 25."},
{lvl:3,sec:"P",type:"mc",q:"Which is the fully factored form of 12x + 18?",mono:true,
 opts:["6(2x + 3)","2(6x + 9)","3(4x + 6)","12(x + 1.5)"],a:0,
 expl:"6 is the greatest common factor of 12 and 18, so 6(2x + 3) is fully factored."}
],

"g7-multistep": [
{sec:"P",type:"in",q:"Solve: 2x + 5 = 15",ans:5,expl:"2x = 10, so x = 5."},
{sec:"P",type:"in",q:"Solve: 3x − 4 = 11",ans:5,expl:"3x = 15, so x = 5."},
{sec:"P",type:"in",q:"Solve: 2(x + 3) = 14",ans:4,expl:"2x + 6 = 14, so 2x = 8 and x = 4."},
{sec:"P",type:"mc",q:"A phone plan costs $20 plus $0.10 per text. Which expression gives the cost for x texts?",mono:true,
 opts:["20 + 0.10x","20x + 0.10","0.10 + 20x","20 − 0.10x"],a:0,
 expl:"The fixed $20 plus 10 cents for each of x texts."},
{sec:"P",type:"in",q:"A plan costs 20 + 0.10x. If the bill is $35, how many texts (x) were sent?",ans:150,
 expl:"35 = 20 + 0.10x, so 15 = 0.10x and x = 150."},
{lvl:2,sec:"P",type:"in",q:"Solve: 5x − 3 = 3x + 7",ans:5,expl:"2x = 10, so x = 5."},
{lvl:2,sec:"P",type:"in",q:"Three consecutive integers add to 72. What is the smallest one?",ans:23,
 hint:"Let the smallest be x, then x+1 and x+2.",expl:"x + (x+1) + (x+2) = 72, so 3x + 3 = 72 and x = 23."},
{lvl:3,sec:"P",type:"in",q:"Solve: 4(x − 2) = 2(x + 4)",ans:8,expl:"4x − 8 = 2x + 8, so 2x = 16 and x = 8."}
],

"g7-eqineq": [
{sec:"P",type:"mc",q:"Solve: x + 4 > 9. Which describes the solution?",mono:true,
 opts:["x > 5","x < 5","x = 5","x > 13"],a:0,expl:"Subtract 4 from both sides: x > 5."},
{sec:"P",type:"in",q:"Solve: 3x = 21",ans:7,expl:"21 ÷ 3 = 7."},
{sec:"P",type:"mc",q:"Solve: −2x < 8. What happens to the inequality sign?",
 opts:["It flips, because we divide by a negative","It stays the same","It becomes an equal sign","Nothing changes"],a:0,
 expl:"Dividing (or multiplying) an inequality by a negative number always flips its direction."},
{sec:"P",type:"in",q:"Solve: x − 7 = 12",ans:19,expl:"x = 12 + 7 = 19."},
{sec:"P",type:"mc",q:"Which value of x satisfies 2x + 1 ≤ 9?",mono:true,opts:["4","5","6","10"],a:0,
 expl:"2(4) + 1 = 9, which satisfies ≤ 9. The others all exceed 9."},
{lvl:2,sec:"P",type:"mc",q:"Solve: −3x + 5 > −4. Which describes the solution?",mono:true,
 opts:["x < 3","x > 3","x < −3","x > −3"],a:0,
 expl:"−3x > −9, and dividing by −3 flips the sign: x < 3."},
{lvl:2,sec:"P",type:"in",q:"Solve: 2(x − 3) = 10",ans:8,expl:"2x − 6 = 10, so 2x = 16 and x = 8."},
{lvl:3,sec:"P",type:"mc",q:"Solve: 5 − 2x ≥ 1. Which describes the solution?",mono:true,
 opts:["x ≤ 2","x ≥ 2","x ≤ −2","x ≥ −2"],a:0,
 expl:"−2x ≥ −4, and dividing by −2 flips the sign: x ≤ 2."}
],

"g7-scaledraw": [
{sec:"G",type:"in",q:"A map uses a scale of 1 inch = 50 miles. Two cities are 3 inches apart on the map. How far apart in reality, in miles?",
 ans:150,expl:"3 × 50 = 150 miles."},
{sec:"G",type:"in",q:"A scale drawing shows a room at 1 inch = 4 feet. The room is 5 inches wide on the drawing. How wide is the real room, in feet?",
 ans:20,expl:"5 × 4 = 20 feet."},
{sec:"G",type:"mc",q:"A blueprint scale is 1:100. If a wall is 5 cm on the blueprint, how long is it in real life, in cm?",
 opts:["500","105","20","95"],a:0,expl:"5 × 100 = 500 cm."},
{sec:"G",type:"in",q:"A model car is built at 1:24 scale. If the model is 8 inches long, how long is the real car, in inches?",
 ans:192,expl:"8 × 24 = 192 inches."},
{sec:"G",type:"mc",q:"In a scale drawing, if the scale factor is greater than 1, the drawing is ___ than real life.",
 opts:["larger","smaller","the same size","impossible"],a:0,
 expl:"A scale factor greater than 1 means the drawing has been enlarged."},
{lvl:2,sec:"G",type:"in",q:"A scale drawing uses 2 cm = 5 m. A wall measures 8 cm on the drawing. How long is the real wall, in meters?",
 ans:20,hint:"Find how many meters each cm represents first.",expl:"Each cm is 2.5 m, so 8 × 2.5 = 20 meters."},
{lvl:2,sec:"G",type:"in",q:"The real distance between two towns is 300 miles. On a map with scale 1 inch = 60 miles, how many inches apart are they?",
 ans:5,expl:"300 ÷ 60 = 5 inches."},
{lvl:3,sec:"G",type:"in",q:"A scale model is built at 1:50. The real height of a building is 150 meters. How tall is the model, in meters?",
 ans:3,expl:"150 ÷ 50 = 3 meters."}
],

"g7-construct": [
{sec:"G",type:"mc",q:"Which tool is used to draw a circle of a specific radius?",
 opts:["A compass","A protractor","A ruler only","Scissors"],a:0,expl:"A compass is designed to draw circles and arcs at a fixed radius."},
{sec:"G",type:"mc",q:"Which tool measures angles?",opts:["A protractor","A compass","A ruler","A calculator"],a:0,
 expl:"A protractor is marked in degrees for measuring angles."},
{sec:"G",type:"mc",q:"To construct a triangle from 3 given side lengths, you must check that ___.",
 opts:["the two shorter sides add to more than the longest","all sides are equal","one angle is 90°","the sides are all different lengths"],a:0,
 expl:"This is the triangle inequality — without it, the sides cannot close up into a triangle."},
{sec:"G",type:"mc",q:"Can a triangle be constructed with sides 2, 3, and 7?",
 opts:["No, 2 + 3 is not greater than 7","Yes, any three lengths work","Only if it's a right triangle","Only with a protractor"],a:0,
 expl:"2 + 3 = 5, which is less than 7, so these sides cannot form a triangle."},
{sec:"G",type:"mc",q:"Given two angles and the side between them, can you construct a UNIQUE triangle?",
 opts:["Yes","No","Only sometimes","Never"],a:0,expl:"ASA (angle-side-angle) always determines exactly one triangle."},
{lvl:2,sec:"G",type:"mc",q:"Which set of conditions does NOT always determine a unique triangle?",
 opts:["Three angles (AAA) only","Three sides (SSS)","Two sides and the included angle (SAS)","Two angles and the included side (ASA)"],a:0,
 expl:"AAA fixes the shape but not the size — infinitely many similar triangles share the same three angles."},
{lvl:2,sec:"G",type:"mc",q:"Can a triangle be constructed with sides 5, 5, and 11?",
 opts:["No, 5 + 5 is not greater than 11","Yes","Only if it's isosceles","Only with a compass"],a:0,
 expl:"5 + 5 = 10, which is less than 11, so these sides cannot close into a triangle."},
{lvl:3,sec:"G",type:"mc",q:"Given three side lengths that DO satisfy the triangle inequality, how many different (non-congruent) triangles can be formed?",
 opts:["Exactly one","Infinitely many","Zero","Exactly two"],a:0,
 expl:"SSS (three sides) always determines exactly one possible triangle shape."}
],

"g7-circles": [
{sec:"G",type:"in",q:"A circle has a radius of 5. What is its diameter?",ans:10,expl:"Diameter = 2 × radius = 2 × 5 = 10."},
{sec:"G",type:"in",q:"A circle has a diameter of 14. What is its radius?",ans:7,expl:"Radius = diameter ÷ 2 = 14 ÷ 2 = 7."},
{sec:"G",type:"in",q:"A circle has radius 7. What is its circumference? Use π ≈ 22/7.",ans:44,
 expl:"C = 2 × (22/7) × 7 = 44."},
{sec:"G",type:"in",q:"A circle has radius 3. What is its area? Use π ≈ 3.14, type as a decimal.",ans:28.26,
 expl:"A = 3.14 × 3² = 3.14 × 9 = 28.26."},
{sec:"G",type:"mc",q:"Which formula gives the circumference of a circle?",mono:true,
 opts:["2πr","πr²","πr","2πr²"],a:0,expl:"Circumference is 2 times π times the radius."},
{lvl:2,sec:"G",type:"in",q:"A circle has diameter 20. Using π ≈ 3.14, what is its circumference? Type as a decimal.",
 ans:62.8,expl:"C = π × diameter = 3.14 × 20 = 62.8."},
{lvl:2,sec:"G",type:"in",q:"A circle has radius 10. Using π ≈ 3.14, what is its area? Type as a decimal.",
 ans:314,expl:"A = 3.14 × 10² = 314."},
{lvl:3,sec:"G",type:"in",q:"A circle's circumference is 31.4 units. Using π ≈ 3.14, what is its radius?",
 ans:5,expl:"31.4 = 2 × 3.14 × r, so r = 31.4 ÷ 6.28 = 5."}
],

"g7-anglerel": [
{sec:"G",type:"in",q:"Two angles are complementary and one is 35°. What is the other?",ans:55,
 expl:"Complementary angles add to 90°: 90 − 35 = 55."},
{sec:"G",type:"in",q:"Two angles are supplementary and one is 110°. What is the other?",ans:70,
 expl:"Supplementary angles add to 180°: 180 − 110 = 70."},
{sec:"G",type:"mc",q:"Vertical angles are always ___.",
 opts:["equal","complementary","supplementary","right angles"],a:0,
 expl:"Vertical angles (formed by two crossing lines) are always congruent."},
{sec:"G",type:"in",q:"Two angles form a straight line. One is 3 times the other. What is the SMALLER angle?",
 ans:45,hint:"The two angles add to 180°.",expl:"x + 3x = 180, so 4x = 180 and x = 45."},
{sec:"G",type:"mc",q:"When two parallel lines are cut by a transversal, corresponding angles are ___.",
 opts:["equal","supplementary","complementary","always 90°"],a:0,
 expl:"Corresponding angles formed by a transversal across parallel lines are always congruent."},
{lvl:2,sec:"G",type:"in",q:"Two complementary angles have a ratio of 1:2. What is the SMALLER angle?",
 ans:30,expl:"x + 2x = 90, so 3x = 90 and x = 30."},
{lvl:2,sec:"G",type:"in",q:"Two supplementary angles have a ratio of 2:3. What is the LARGER angle?",
 ans:108,expl:"2x + 3x = 180, so x = 36. The larger angle is 3 × 36 = 108."},
{lvl:3,sec:"G",type:"in",q:"Three angles around a point sum to 360°. Two are equal and the third is 120°. What is the measure of ONE of the two equal angles?",
 ans:120,expl:"360 − 120 = 240, split evenly: 240 ÷ 2 = 120."}
],

"g7-solids": [
{sec:"G",type:"in",q:"A cylinder has radius 3 and height 5. Using π ≈ 3.14, what is its volume? Type as a decimal.",
 ans:141.3,expl:"V = 3.14 × 3² × 5 = 3.14 × 9 × 5 = 141.3."},
{sec:"G",type:"in",q:"A rectangular prism is 4 by 3 by 2. What is its surface area?",ans:52,
 expl:"2×(4×3) + 2×(4×2) + 2×(3×2) = 24 + 16 + 12 = 52."},
{sec:"G",type:"mc",q:"Which formula gives the volume of a cylinder?",mono:true,
 opts:["πr²h","2πrh","πr²","2πr"],a:0,expl:"Volume of a cylinder is the circular base's area times its height."},
{sec:"G",type:"in",q:"A cone has radius 3 and height 4. Volume = 1/3 × π × r² × h. Using π ≈ 3.14, what is the volume? Type as a decimal.",
 ans:37.68,expl:"1/3 × 3.14 × 9 × 4 = 37.68."},
{sec:"G",type:"in",q:"A cube has a side of 6. What is its volume?",ans:216,expl:"6 × 6 × 6 = 216."},
{lvl:2,sec:"G",type:"in",q:"A cylinder has volume 157 and height 5. Using π ≈ 3.14, what is r²? Type as a decimal.",
 ans:10,hint:"Divide the volume by π times the height.",expl:"157 ÷ (3.14 × 5) = 157 ÷ 15.7 = 10."},
{lvl:2,sec:"G",type:"in",q:"A rectangular prism has volume 120, length 6, and width 4. What is its height?",
 ans:5,expl:"120 ÷ (6 × 4) = 120 ÷ 24 = 5."},
{lvl:3,sec:"G",type:"in",q:"A cylinder's volume is 401.92, using π ≈ 3.14 and height 8. What is the radius?",
 ans:4,hint:"Find r² first, then take its square root.",
 expl:"401.92 ÷ (3.14 × 8) = 401.92 ÷ 25.12 = 16, and √16 = 4."}
],

"g7-sampling": [
{sec:"S",type:"mc",q:"Which is an example of a RANDOM sample of a school?",
 opts:["Picking 30 students with a random number generator from the full roster","Asking only the students in one class","Asking only your friends","Surveying only students who volunteer"],a:0,
 expl:"A true random sample gives every member of the population an equal chance of being chosen."},
{sec:"S",type:"mc",q:"Why is random sampling important?",
 opts:["It helps the sample represent the whole population fairly","It's faster than any other method","It always gives the exact true value","It removes the need for math"],a:0,
 expl:"Random sampling avoids systematically favoring any group, so the sample better reflects the whole population."},
{sec:"S",type:"mc",q:"A survey only asks students in the chess club about favorite sports. This sample is ___.",
 opts:["biased, not representative","perfectly random","large enough to trust","the best possible method"],a:0,
 expl:"Chess club members are not a random cross-section of the school, so the results are biased."},
{sec:"S",type:"mc",q:"Which sample size tends to give a MORE reliable estimate?",
 opts:["A larger random sample","A smaller random sample","Any sample size works equally","Sample size doesn't matter"],a:0,
 expl:"Larger random samples tend to more closely reflect the true population."},
{sec:"S",type:"mc",q:"A pollster wants to estimate how a whole city will vote. What should they avoid?",
 opts:["Surveying only one neighborhood","Using random sampling","Using a large sample","Sampling from voter records"],a:0,
 expl:"One neighborhood may not represent the whole city's views, introducing bias."},
{lvl:2,sec:"S",type:"mc",q:"Two random samples of the same population give slightly different results. Why?",
 opts:["Random samples naturally vary from sample to sample","One sample must be wrong","Random sampling doesn't work","The population changed"],a:0,
 expl:"Sampling variability is expected — different random samples rarely give identical results, even from the same population."},
{lvl:2,sec:"S",type:"mc",q:"Which method reduces bias in a school survey about lunch preferences?",
 opts:["Randomly selecting students from the entire school","Asking only students in the cafeteria at noon","Asking only 5th graders","Asking only students who like the current menu"],a:0,
 expl:"Sampling from the entire school population avoids favoring any one group's opinions."},
{lvl:3,sec:"S",type:"mc",q:"A researcher wants to estimate average height in a city using a sample of 50 people. Which method gives the LEAST bias?",
 opts:["Randomly selecting 50 people from city records","Measuring 50 people at a basketball game","Measuring 50 people at a preschool","Measuring the researcher's 50 friends"],a:0,
 expl:"City records cover the whole population, so a random selection from them best represents everyone."}
],

"g7-probmodel": [
{sec:"S",type:"in",q:"A fair coin is flipped. What is the probability of heads? Type as a decimal.",ans:0.5,
 expl:"1 favorable outcome out of 2 possible: 1/2 = 0.5."},
{sec:"S",type:"in",q:"A fair 6-sided die is rolled. What is the probability of rolling a 4? Type as a decimal, rounded to 2 places.",
 ans:0.17,expl:"1/6 ≈ 0.17."},
{sec:"S",type:"mc",q:"A probability MODEL assigns probabilities to ___.",
 opts:["every possible outcome of an event","only the most likely outcome","only impossible outcomes","nothing measurable"],a:0,
 expl:"A complete probability model covers the full sample space of outcomes."},
{sec:"S",type:"in",q:"A spinner has 4 equal sections: red, blue, green, yellow. What is the probability of landing on blue? Type as a decimal.",
 ans:0.25,expl:"1 out of 4 equal sections: 1/4 = 0.25."},
{sec:"S",type:"mc",q:"If a probability model is fair, all outcomes are ___.",
 opts:["equally likely","never possible","always certain","random and unequal"],a:0,
 expl:"'Fair' means no outcome is favored over any other."},
{lvl:2,sec:"S",type:"in",q:"A bag has 3 red and 7 blue marbles. What is the probability of picking blue? Type as a decimal.",
 ans:0.7,expl:"7 blue out of 10 total: 7/10 = 0.7."},
{lvl:2,sec:"S",type:"mc",q:"You roll a die 60 times and expect about 10 fours, since 1/6 of 60 is 10. This expectation comes from ___.",
 opts:["the theoretical probability model","only from actually observing many rolls","pure guessing","nothing mathematical"],a:0,
 expl:"Theoretical probability predicts this count before any rolling happens, based on the model alone."},
{lvl:3,sec:"S",type:"in",q:"A weighted coin lands heads 70% of the time. In 200 flips, about how many heads would you EXPECT?",
 ans:140,expl:"0.70 × 200 = 140."}
],

"g7-compound": [
{sec:"S",type:"in",q:"A coin is flipped twice. How many possible outcomes are there in total? (HH, HT, TH, TT)",
 ans:4,expl:"There are 4 possible outcomes when listed out."},
{sec:"S",type:"in",q:"Two dice are rolled. How many total possible outcomes are there?",ans:36,
 expl:"6 outcomes for the first die times 6 for the second: 6 × 6 = 36."},
{sec:"S",type:"in",q:"A coin is flipped and a die is rolled. How many total outcomes?",ans:12,
 expl:"2 outcomes for the coin times 6 for the die: 2 × 6 = 12."},
{sec:"S",type:"mc",q:"Which lists ALL outcomes of flipping a coin twice?",mono:true,
 opts:["HH, HT, TH, TT","HH, TT","HT, TH","H, T"],a:0,expl:"All four combinations of two flips must be listed to be complete."},
{sec:"S",type:"in",q:"Two dice are rolled. Rolling a sum of 2 only happens one way (1+1) out of 36 total outcomes. Type the denominator of that probability, in lowest terms with numerator 1.",
 ans:36,expl:"1 way out of 36 total outcomes."},
{lvl:2,sec:"S",type:"in",q:"A coin is flipped 3 times. How many total possible outcomes are there?",ans:8,
 expl:"2 × 2 × 2 = 8."},
{lvl:2,sec:"S",type:"in",q:"Two dice are rolled. How many ways can the sum equal 7? (1+6, 2+5, 3+4, 4+3, 5+2, 6+1)",
 ans:6,expl:"There are 6 combinations that add to 7."},
{lvl:3,sec:"S",type:"in",q:"Two dice are rolled. What is the probability of getting a sum of 7? Type as a decimal, rounded to 3 places.",
 ans:0.167,expl:"6 out of 36 outcomes: 6/36 = 1/6 ≈ 0.167."}
]
};
