/* Grade 8 advanced / enrichment: number theory, algebra, extended geometry
   (incl. trigonometry), combinatorics and probability. Competition-style
   content (AMC 8 / MATHCOUNTS / Kangaroo flavour) worded for Grade 8. */
export const G8_ADV_BANKS = {
"g8-modfull": [
{sec:"T",type:"in",q:"What is the remainder when 2^10 is divided by 7?",ans:2,hint:"Find a small power of 2 that leaves remainder 1.",
 expl:"2³ = 8 ≡ 1 (mod 7), so 2^10 = (2³)³ × 2 ≡ 1 × 2 = 2. The remainder is 2."},
{sec:"T",type:"mc",q:"Which number satisfies x ≡ 2 (mod 3) and x ≡ 3 (mod 5)?",mono:true,opts:["11","8","13","5"],a:1,
 expl:"8 ÷ 3 leaves 2 and 8 ÷ 5 leaves 3, so x = 8 works. 11 leaves 1 (mod 5), 13 leaves 1 (mod 3), 5 leaves 0 (mod 5)."},
{sec:"T",type:"in",q:"Find the smallest positive integer x with x ≡ 1 (mod 4) and x ≡ 2 (mod 5).",ans:17,
 hint:"List numbers that are 2 more than a multiple of 5 and test each one.",
 expl:"Numbers ≡ 2 (mod 5) are 2, 7, 12, 17, … Checking mod 4: 2 → 2, 7 → 3, 12 → 0, 17 → 1. So x = 17."},
{lvl:2,sec:"T",type:"in",q:"Find the inverse of 7 modulo 26, i.e. the number d between 1 and 25 with 7d ≡ 1 (mod 26).",ans:15,
 hint:"Look for a multiple of 7 that is one more than a multiple of 26.",
 expl:"7 × 15 = 105 = 4 × 26 + 1, so 7 × 15 ≡ 1 (mod 26). The inverse is 15."},
{lvl:2,sec:"T",type:"mc",q:"How many solutions does 2x ≡ 4 (mod 6) have with x in {0, 1, 2, 3, 4, 5}?",opts:["1","2","3","0"],a:1,
 expl:"gcd(2, 6) = 2 divides 4, so there are exactly 2 solutions: x = 2 (2 × 2 = 4) and x = 5 (2 × 5 = 10 ≡ 4)."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY statement that is true.",
 opts:["If a ≡ b (mod m) then a² ≡ b² (mod m)","x ≡ 1 (mod 6) and x ≡ 2 (mod 4) has a solution","Any remainders mod 8 and mod 12 can be combined into one solution","x ≡ 3 (mod 7), x ≡ 5 (mod 11) has exactly one solution mod 77"],
 aMulti:[0,3],
 expl:"Congruences can be multiplied, so squares stay congruent. x ≡ 1 (mod 6) is odd but x ≡ 2 (mod 4) is even, so no solution. 8 and 12 share a factor 4, so the CRT does not apply. 7 and 11 are coprime, so there is exactly one solution mod 77."},
{lvl:3,sec:"T",type:"in",q:"A number leaves remainder 2 when divided by 3, remainder 3 when divided by 5 and remainder 2 when divided by 7. What is the smallest such positive number?",ans:23,
 hint:"Combine two of the conditions first, then test candidates against the third.",
 expl:"Remainder 2 mod 3 and 2 mod 7 means x ≡ 2 (mod 21): 2, 23, 44, … Of these, 23 leaves remainder 3 when divided by 5. The answer is 23."},
{lvl:3,sec:"T",type:"in",q:"What is the remainder when 7^2024 is divided by 100?",ans:1,hint:"Compute 7⁴ mod 100 first.",
 expl:"7⁴ = 2401 ≡ 1 (mod 100). Since 2024 = 4 × 506, 7^2024 = (7⁴)^506 ≡ 1. The remainder is 1."},
{lvl:3,sec:"T",type:"in",q:"Find the remainder when 3^100 is divided by 13.",ans:3,hint:"3³ = 27 is close to a multiple of 13.",
 expl:"3³ = 27 ≡ 1 (mod 13). 100 = 3 × 33 + 1, so 3^100 = (3³)^33 × 3 ≡ 3. The remainder is 3."}
],

"g8-quadres": [
{sec:"T",type:"mc",q:"Which of these is a quadratic residue modulo 7 (a nonzero square mod 7)?",opts:["3","2","5","6"],a:1,
 expl:"The squares mod 7 are 1² = 1, 2² = 4, 3² = 9 ≡ 2, 4² = 16 ≡ 2, 5² ≡ 4, 6² ≡ 1. So the residues are 1, 2 and 4; the answer is 2."},
{sec:"T",type:"in",q:"How many nonzero quadratic residues are there modulo 11?",ans:5,hint:"Square each of 1 to 10 and count the distinct results.",
 expl:"For an odd prime p there are (p − 1)/2 nonzero residues. Mod 11 they are 1, 4, 9, 5, 3 — that is 5 residues."},
{sec:"T",type:"in",q:"Find the smallest positive integer x with x² ≡ 2 (mod 7).",ans:3,expl:"1² = 1, 2² = 4, 3² = 9 = 7 + 2, so x = 3."},
{lvl:2,sec:"T",type:"mc",q:"x² ≡ −1 (mod p) has a solution only when p = 2 or p ≡ 1 (mod 4). For which prime below does it have a solution?",opts:["13","7","11","19"],a:0,
 expl:"13 ≡ 1 (mod 4) while 7, 11 and 19 are all 3 mod 4. Indeed 5² = 25 = 26 − 1 ≡ −1 (mod 13)."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY prime p for which 2 is a quadratic residue mod p.",opts:["7","17","5","11"],aMulti:[0,1],
 expl:"3² = 9 ≡ 2 (mod 7) and 6² = 36 ≡ 2 (mod 17). The squares mod 5 are 1 and 4, and mod 11 they are 1, 3, 4, 5, 9 — no 2. (2 is a residue exactly when p ≡ ±1 mod 8.)"},
{lvl:2,sec:"T",type:"in",q:"Euler's criterion: a is a residue mod p exactly when a^((p−1)/2) ≡ 1. Compute 3^5 mod 11.",ans:1,
 hint:"3^5 = 243; divide by 11.",expl:"243 = 22 × 11 + 1, so 3^5 ≡ 1 (mod 11). This confirms 3 is a residue mod 11 (5² = 25 ≡ 3)."},
{lvl:3,sec:"T",type:"in",q:"How many values of x from 0 to 14 satisfy x² ≡ 4 (mod 15)?",ans:4,hint:"Split into mod 3 and mod 5 and use the CRT.",
 expl:"x² ≡ 1 (mod 3) has 2 solutions and x² ≡ 4 (mod 5) has 2, giving 2 × 2 = 4 solutions mod 15: x = 2, 7, 8, 13 (e.g. 7² = 49 = 45 + 4)."},
{lvl:3,sec:"T",type:"mc",q:"Which statement about x² ≡ 3 (mod 13) is correct?",
 opts:["Exactly two solutions, x = 4 and x = 9","No solutions at all","Exactly one solution, x = 3","Four solutions, one per residue"],a:0,
 expl:"4² = 16 ≡ 3 and 9² = 81 = 78 + 3 ≡ 3 (mod 13). A nonzero square mod a prime always has exactly two roots, x and p − x."},
{lvl:3,sec:"T",type:"in",q:"Use Euler's criterion to decide if 2 is a residue mod 13: compute 2^6 mod 13.",ans:12,
 hint:"2^6 = 64; a result of p − 1 means 'not a residue'.",expl:"64 = 5 × 13 − 1, so 2^6 ≡ 12 ≡ −1 (mod 13). Therefore 2 is not a quadratic residue mod 13, matching 13 ≡ 5 (mod 8)."}
],

"g8-pell": [
{sec:"T",type:"mc",q:"Which pair (x, y) is the smallest positive solution of Pell's equation x² − 2y² = 1?",mono:true,opts:["(2, 1)","(1, 1)","(3, 2)","(5, 3)"],a:2,
 expl:"3² − 2 × 2² = 9 − 8 = 1. The others give 4 − 2 = 2, 1 − 2 = −1 and 25 − 18 = 7."},
{sec:"T",type:"in",q:"Find x in the smallest positive integer solution of x² − 3y² = 1.",ans:2,hint:"Try y = 1 first.",
 expl:"With y = 1, x² = 3 + 1 = 4, so x = 2. The fundamental solution is (2, 1)."},
{sec:"T",type:"in",q:"Find x in the smallest positive integer solution of x² − 5y² = 1.",ans:9,hint:"Try y = 1, 2, 3, … until 5y² + 1 is a perfect square.",
 expl:"5y² + 1 gives 6, 21, 46, 81 for y = 1, 2, 3, 4. Only 81 = 9² is a square, so x = 9 (and y = 4)."},
{lvl:2,sec:"T",type:"in",q:"Starting from (3, 2), the next solution of x² − 2y² = 1 comes from (3 + 2√2)². What is the new x?",ans:17,
 hint:"Expand (3 + 2√2)² and separate the whole-number part from the √2 part.",
 expl:"(3 + 2√2)² = 9 + 12√2 + 8 = 17 + 12√2, so the next solution is (17, 12): 289 − 2 × 144 = 1."},
{lvl:2,sec:"T",type:"mc",q:"Which pair is NOT a solution of x² − 2y² = 1?",mono:true,opts:["(7, 5)","(17, 12)","(99, 70)","(3, 2)"],a:0,
 expl:"7² − 2 × 5² = 49 − 50 = −1, so (7, 5) solves the negative Pell equation instead. The other three all give exactly 1."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY value of d for which x² − dy² = 1 has infinitely many positive integer solutions.",opts:["2","4","7","9"],aMulti:[0,2],
 expl:"Pell's equation has infinitely many solutions whenever d is not a perfect square. 4 and 9 are squares: x² − (2y)² = 1 forces x − 2y = x + 2y = 1, so y = 0."},
{lvl:3,sec:"T",type:"in",q:"The positive solutions of x² − 3y² = 1 in increasing order start (2, 1), (7, 4), … What is x in the third solution?",ans:26,
 hint:"Multiply (2 + √3) by (7 + 4√3).",
 expl:"(2 + √3)(7 + 4√3) = 14 + 8√3 + 7√3 + 12 = 26 + 15√3, giving (26, 15). Check: 676 − 3 × 225 = 1."},
{lvl:3,sec:"T",type:"in",q:"The triangular numbers 1 and 36 are perfect squares. Using Pell's equation, what is the next triangular number that is a perfect square?",ans:1225,
 hint:"n(n + 1)/2 = m² becomes (2n + 1)² − 2(2m)² = 1; use the solutions (3, 2), (17, 12), (99, 70).",
 expl:"The solution (99, 70) gives 2n + 1 = 99, so n = 49, and 2m = 70, so m = 35. Then 49 × 50/2 = 1225 = 35²."},
{lvl:3,sec:"T",type:"mc",q:"Why does x² − 2y² = 1 tell us about approximations of √2?",
 opts:["Rearranging gives x/y ≈ √2 with error shrinking as y grows","Because x and y are both even","Because √2 = 3/2 exactly","Because x − y is always 1"],a:0,
 expl:"x² = 2y² + 1 means (x/y)² = 2 + 1/y², so x/y is very close to √2 for large y: 99/70 = 1.41428…, while √2 = 1.41421…"}
],

"g8-flt": [
{sec:"T",type:"mc",q:"Fermat's Last Theorem states that aⁿ + bⁿ = cⁿ has no solutions in positive integers for which values of n?",mono:true,opts:["n > 2","n = 2","n = 1","every n"],a:0,
 expl:"For n = 1 (e.g. 1 + 2 = 3) and n = 2 (Pythagorean triples) there are many solutions. Fermat's theorem, proved by Wiles in 1995, covers every exponent n > 2."},
{sec:"T",type:"in",q:"How many solutions in positive integers does 3x + 5y = 30 have?",ans:1,hint:"y must make 30 − 5y a multiple of 3.",
 expl:"3x = 30 − 5y, so y must be a multiple of 3. y = 3 gives x = 5; y = 6 gives x = 0, which is not positive. Just 1 solution."},
{sec:"T",type:"mc",q:"Does 6x + 9y = 20 have any integer solutions?",
 opts:["No — 3 does not divide 20","Yes, x = 1 and y = 2","Yes, infinitely many","No — 20 is even"],a:0,
 expl:"6x + 9y is always a multiple of gcd(6, 9) = 3, but 20 is not a multiple of 3. So there are no integer solutions."},
{lvl:2,sec:"T",type:"in",q:"How many ordered pairs of positive integers (x, y) satisfy x² − y² = 15?",ans:2,hint:"Factor the left side as (x − y)(x + y).",
 expl:"(x − y)(x + y) = 15 with x − y < x + y: 1 × 15 gives (8, 7) and 3 × 5 gives (4, 1). That is 2 pairs."},
{lvl:2,sec:"T",type:"mc",q:"Which equation has NO integer solutions?",mono:true,opts:["x² + y² = 2023","x² + y² = 25","x² + y² = 50","x² + y² = 13"],a:0,
 expl:"Squares are 0 or 1 mod 4, so x² + y² is 0, 1 or 2 mod 4. 2023 = 4 × 505 + 3 is 3 mod 4. The others: 3² + 4², 1² + 7², 2² + 3²."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY equation that has a solution in positive integers.",mono:true,
 opts:["x³ + y³ = z³","x² + y² = z²","x⁴ + y⁴ = z⁴","x² + y³ = z²"],aMulti:[1,3],
 expl:"3² + 4² = 5² and 1² + 2³ = 3² work. Cubes and fourth powers are ruled out by Fermat's Last Theorem (the n = 4 case was proved by Fermat himself)."},
{lvl:3,sec:"T",type:"in",q:"How many ordered pairs of positive integers (x, y) satisfy 1/x + 1/y = 1/6?",ans:9,
 hint:"Clear fractions and rewrite as (x − 6)(y − 6) = a constant.",
 expl:"xy = 6x + 6y gives (x − 6)(y − 6) = 36. Both factors must be positive (negative factors would need a product of 36 with each below 6, impossible), so count the divisors of 36: 9 pairs."},
{lvl:3,sec:"T",type:"in",q:"How many ordered pairs of positive integers (x, y) satisfy xy = 2x + 2y?",ans:3,hint:"Use Simon's favourite factoring trick.",
 expl:"xy − 2x − 2y + 4 = 4, so (x − 2)(y − 2) = 4. Factor pairs 1 × 4, 2 × 2, 4 × 1 give (3, 6), (4, 4), (6, 3): 3 pairs."},
{lvl:3,sec:"T",type:"mc",q:"Why does x² + y² = 4z + 3 have no integer solutions?",
 opts:["Squares are 0 or 1 mod 4, so x² + y² is never 3 mod 4","Because 3 is a prime number","Because z would have to be negative","Fermat's Last Theorem forbids it"],a:0,
 expl:"Even squares are 0 mod 4 and odd squares are 1 mod 4, so x² + y² can only be 0, 1 or 2 mod 4, while 4z + 3 is 3 mod 4."}
],

"g8-primality": [
{sec:"T",type:"mc",q:"To test whether 97 is prime by trial division, you only need to try primes up to which number?",opts:["7","11","13","48"],a:0,
 expl:"A composite number has a prime factor at most its square root. √97 ≈ 9.8, so testing 2, 3, 5 and 7 is enough — none divide 97, so it is prime."},
{sec:"T",type:"in",q:"Find the smallest prime factor of 221.",ans:13,hint:"Test primes up to √221 ≈ 14.9.",
 expl:"221 is not divisible by 2, 3, 5, 7 or 11, but 221 = 13 × 17. The smallest prime factor is 13."},
{sec:"T",type:"in",q:"Fermat's little theorem says a^(p−1) ≡ 1 (mod p) for prime p and a not divisible by p. Compute 2^10 mod 11.",ans:1,
 expl:"2^10 = 1024 = 93 × 11 + 1, so 2^10 ≡ 1 (mod 11), just as the theorem predicts for the prime 11."},
{lvl:2,sec:"T",type:"in",q:"Compute 2^14 mod 15. (A result other than 1 proves 15 is composite.)",ans:4,hint:"2⁴ = 16 is one more than a multiple of 15.",
 expl:"2⁴ ≡ 1 (mod 15), so 2^14 = (2⁴)³ × 2² ≡ 4. Since 4 ≠ 1, the Fermat test shows 15 is not prime."},
{lvl:2,sec:"T",type:"mc",q:"2^340 ≡ 1 (mod 341), yet 341 = 11 × 31. What is 341 called?",
 opts:["A Fermat pseudoprime to base 2","A Mersenne prime","A perfect number","A twin prime"],a:0,
 expl:"A composite number that passes the Fermat test for some base is a pseudoprime to that base. 341 is the smallest pseudoprime to base 2."},
{lvl:2,sec:"T",type:"multi",q:"Select EVERY number that is prime.",opts:["91","101","111","127"],aMulti:[1,3],
 expl:"91 = 7 × 13 and 111 = 3 × 37. 101 and 127 have no prime factor up to their square roots (10 and 11), so they are prime."},
{lvl:3,sec:"T",type:"in",q:"Using the sieve of Eratosthenes, how many primes are there below 60?",ans:17,hint:"Cross out multiples of 2, 3, 5 and 7, then count what is left.",
 expl:"The primes are 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59 — that is 17 primes."},
{lvl:3,sec:"T",type:"in",q:"The Miller–Rabin test writes n − 1 = 2^s × d with d odd. For n = 97, what is s?",ans:5,hint:"Keep dividing 96 by 2.",
 expl:"96 = 2 × 48 = 4 × 24 = 8 × 12 = 16 × 6 = 32 × 3, so 96 = 2^5 × 3 and s = 5."},
{lvl:3,sec:"T",type:"in",q:"Wilson's theorem says (p − 1)! ≡ −1 (mod p) for prime p. What is 10! mod 11?",ans:10,
 hint:"A remainder of −1 is the same as a remainder of p − 1.",
 expl:"Since 11 is prime, 10! ≡ −1 (mod 11), and −1 ≡ 10. So 10! leaves remainder 10 when divided by 11."}
],

"g8-rsa": [
{sec:"T",type:"in",q:"An RSA key uses the primes p = 3 and q = 11. What is φ(n) = (p − 1)(q − 1)?",ans:20,
 expl:"φ(n) = (3 − 1)(11 − 1) = 2 × 10 = 20."},
{sec:"T",type:"mc",q:"With φ(n) = 20, which of these is a valid public exponent e (it must be coprime to 20)?",opts:["4","3","5","10"],a:1,
 expl:"gcd(3, 20) = 1, so e = 3 works. 4, 5 and 10 all share a factor with 20."},
{sec:"T",type:"multi",q:"Select EVERY item that is part of the PUBLIC key in RSA.",opts:["n = pq","the exponent e","the prime p","the exponent d"],aMulti:[0,1],
 expl:"The public key is (n, e). The primes p, q and the decryption exponent d must stay secret, since anyone who knows them can decrypt."},
{lvl:2,sec:"T",type:"in",q:"Encrypt the message m = 2 with n = 33 and e = 3. What is the ciphertext c = m^e mod n?",ans:8,
 expl:"2³ = 8, and 8 < 33, so c = 8."},
{lvl:2,sec:"T",type:"in",q:"Find the decryption exponent d for e = 3 and φ(n) = 20, i.e. the d with 3d ≡ 1 (mod 20).",ans:7,
 hint:"Look for a multiple of 3 that is one more than a multiple of 20.",expl:"3 × 7 = 21 = 20 + 1, so d = 7."},
{lvl:2,sec:"T",type:"in",q:"Decrypt c = 8 using d = 7 and n = 33: compute 8^7 mod 33.",ans:2,hint:"8² = 64 ≡ −2 (mod 33); build up from there.",
 expl:"8² ≡ −2, so 8⁴ ≡ 4 and 8^6 ≡ −8. Then 8^7 ≡ −8 × 8 = −64 ≡ −64 + 66 = 2. The message m = 2 is recovered."},
{lvl:3,sec:"T",type:"in",q:"With p = 7, q = 11 and e = 7, find the decryption exponent d (1 ≤ d < 60).",ans:43,hint:"First compute φ(n), then solve 7d ≡ 1 mod φ(n).",
 expl:"φ(n) = 6 × 10 = 60. 7 × 43 = 301 = 5 × 60 + 1, so d = 43."},
{lvl:3,sec:"T",type:"in",q:"Encrypt m = 3 with n = 77 and e = 7. What is 3^7 mod 77?",ans:31,hint:"3^7 = 2187; subtract the largest multiple of 77.",
 expl:"3^7 = 2187 and 77 × 28 = 2156, so 2187 − 2156 = 31. The ciphertext is 31."},
{lvl:3,sec:"T",type:"mc",q:"Why is RSA considered secure even though n is public?",
 opts:["Factoring a large n is very slow","Because e is kept secret","Because n itself is prime","Because φ(n) equals n"],a:0,
 expl:"Finding d requires φ(n) = (p − 1)(q − 1), which needs the factors of n. For n with hundreds of digits, no known method factors it in a reasonable time."}
],

"g8-polynom": [
{sec:"L",type:"in",q:"What is the remainder when p(x) = x³ − 2x² + 3x − 5 is divided by (x − 2)?",ans:1,hint:"The remainder theorem says the remainder is p(2).",
 expl:"By the remainder theorem the remainder is p(2) = 8 − 8 + 6 − 5 = 1."},
{sec:"L",type:"mc",q:"Which of these is a factor of x³ − 6x² + 11x − 6?",mono:true,opts:["x − 1","x + 1","x − 4","x + 2"],a:0,
 expl:"p(1) = 1 − 6 + 11 − 6 = 0, so by the factor theorem (x − 1) is a factor. In fact the polynomial is (x − 1)(x − 2)(x − 3)."},
{sec:"L",type:"in",q:"Find the value of k for which (x − 3) is a factor of x² − 5x + k.",ans:6,hint:"A factor (x − 3) means substituting x = 3 gives 0.",
 expl:"p(3) = 9 − 15 + k must equal 0, so k = 6. Check: x² − 5x + 6 = (x − 2)(x − 3)."},
{lvl:2,sec:"L",type:"in",q:"p(x) = 2x³ + x² − 13x + 6 has p(2) = 0. Factor it completely and give its smallest root.",ans:-3,
 hint:"Divide by (x − 2), then factor the remaining quadratic.",
 expl:"Dividing by (x − 2) leaves 2x² + 5x − 3 = (2x − 1)(x + 3). The roots are 2, 1/2 and −3, so the smallest is −3."},
{lvl:2,sec:"L",type:"mc",q:"What is the degree of the product (x² + 1)(x³ − x)(x + 2)?",opts:["6","5","7","4"],a:0,
 expl:"Degrees add when polynomials are multiplied: 2 + 3 + 1 = 6."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY polynomial that has (x + 2) as a factor.",mono:true,opts:["x² − 4","x³ + 8","x² + 4","x² − 2x"],aMulti:[0,1],
 expl:"Substitute x = −2: 4 − 4 = 0 and −8 + 8 = 0, so the first two work. x² + 4 gives 8 and x² − 2x gives 4 + 4 = 8, so neither has (x + 2) as a factor."},
{lvl:3,sec:"L",type:"in",q:"A polynomial p(x) satisfies p(1) = 3 and p(−1) = 7. When p(x) is divided by x² − 1 the remainder is ax + b. Find b.",ans:5,
 hint:"The remainder has degree less than 2, and it must agree with p at x = 1 and x = −1.",
 expl:"p(x) = (x² − 1)q(x) + ax + b, so p(1) = a + b = 3 and p(−1) = −a + b = 7. Adding gives 2b = 10, so b = 5 (and a = −2)."},
{lvl:3,sec:"L",type:"in",q:"The polynomial x³ + ax² + bx − 6 has both (x − 1) and (x + 3) as factors. Find a.",ans:4,
 hint:"Substitute x = 1 and x = −3 to get two equations in a and b.",
 expl:"p(1) = 0 gives a + b = 5 and p(−3) = 0 gives 9a − 3b = 33, i.e. 3a − b = 11. Adding: 4a = 16, so a = 4 (and b = 1). Check: (x − 1)(x + 3)(x + 2) = x³ + 4x² + x − 6."},
{lvl:3,sec:"L",type:"mc",q:"A cubic with leading coefficient 1 has roots 1, 2 and −3. What is its constant term?",opts:["6","−6","5","−5"],a:0,
 expl:"The cubic is (x − 1)(x − 2)(x + 3). Its constant term is (−1)(−2)(3) = 6."}
],

"g8-rational": [
{sec:"L",type:"mc",q:"Simplify (x² − 9)/(x − 3) for x ≠ 3.",mono:true,opts:["x + 3","x − 3","x + 9","x² − 3"],a:0,
 expl:"x² − 9 = (x − 3)(x + 3). Cancelling the common factor (x − 3) leaves x + 3."},
{sec:"L",type:"in",q:"Evaluate (x² − 4)/(x + 2) when x = 5.",ans:3,expl:"(25 − 4)/(5 + 2) = 21/7 = 3. Equivalently the expression simplifies to x − 2 = 3."},
{sec:"L",type:"mc",q:"For which value of x is 1/(x − 4) + 2/(x + 1) undefined?",opts:["4","2","1","0"],a:0,
 expl:"A fraction is undefined when its denominator is 0. x − 4 = 0 at x = 4 (and x + 1 = 0 at x = −1). Of the choices, only 4 makes a denominator zero."},
{lvl:2,sec:"L",type:"mc",q:"Write 1/x + 1/(x + 1) as a single fraction.",mono:true,opts:["(2x + 1)/(x(x + 1))","2/(2x + 1)","1/(x(x + 1))","(x + 1)/x"],a:0,
 expl:"Use the common denominator x(x + 1): (x + 1)/(x(x + 1)) + x/(x(x + 1)) = (2x + 1)/(x(x + 1))."},
{lvl:2,sec:"L",type:"in",q:"Solve x/(x − 2) = 3.",ans:3,hint:"Multiply both sides by (x − 2), then check that the solution does not make the denominator 0.",
 expl:"x = 3(x − 2) = 3x − 6, so 2x = 6 and x = 3. Check: 3/(3 − 2) = 3."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY expression equal to (x² − x)/(x² − 1) for x ≠ ±1.",mono:true,opts:["x/(x + 1)","(x − 1)/(x + 1)","1 − 1/(x + 1)","x/(x − 1)"],aMulti:[0,2],
 expl:"(x² − x)/(x² − 1) = x(x − 1)/((x − 1)(x + 1)) = x/(x + 1). Also 1 − 1/(x + 1) = (x + 1 − 1)/(x + 1) = x/(x + 1). The other two differ (test x = 2: 2/3 versus 1/3 and 2)."},
{lvl:3,sec:"L",type:"in",q:"Find the positive solution of 2/(x − 1) + 3/(x + 1) = 3.",ans:2,hint:"Multiply through by (x − 1)(x + 1) and solve the resulting quadratic.",
 expl:"2(x + 1) + 3(x − 1) = 3(x² − 1) gives 5x − 1 = 3x² − 3, so 3x² − 5x − 2 = 0 = (3x + 1)(x − 2). The positive solution is x = 2: 2/1 + 3/3 = 3."},
{lvl:3,sec:"L",type:"in",q:"Using 1/(n(n + 1)) = 1/n − 1/(n + 1), find 1/(1×2) + 1/(2×3) + … + 1/(9×10) as a decimal.",ans:0.9,
 hint:"Write each term as a difference and watch the middle terms cancel.",
 expl:"The sum telescopes: (1 − 1/2) + (1/2 − 1/3) + … + (1/9 − 1/10) = 1 − 1/10 = 0.9."},
{lvl:3,sec:"L",type:"mc",q:"Solve x/(x − 3) = 3/(x − 3) + 2.",opts:["No solution","x = 3","x = 0","x = −3"],a:0,
 expl:"Multiplying by (x − 3) gives x = 3 + 2(x − 3), so x = 3. But x = 3 makes the denominators zero, so it is extraneous and there is no solution."}
],

"g8-radicaleq": [
{sec:"L",type:"in",q:"Solve √(x + 5) = 4.",ans:11,expl:"Square both sides: x + 5 = 16, so x = 11. Check: √16 = 4."},
{sec:"L",type:"in",q:"Solve √(2x − 1) = 3.",ans:5,hint:"Square both sides first.",expl:"2x − 1 = 9, so 2x = 10 and x = 5. Check: √9 = 3."},
{sec:"L",type:"mc",q:"Why must you check answers after squaring both sides of an equation?",
 opts:["Squaring can add solutions that fail the original","Squaring always removes one solution","Square roots are always negative","Squaring changes the variable name"],a:0,
 expl:"Squaring turns a = b and a = −b into the same equation a² = b², so extra 'extraneous' solutions can appear. Each answer must be tested in the original equation."},
{lvl:2,sec:"L",type:"mc",q:"Solve √(x + 7) = x − 5.",opts:["x = 9 only","x = 2 only","x = 2 or x = 9","No solution"],a:0,
 expl:"Squaring: x + 7 = x² − 10x + 25, so x² − 11x + 18 = (x − 2)(x − 9) = 0. x = 2 gives √9 = 3 but x − 5 = −3, so it fails. x = 9 gives √16 = 4 = 9 − 5. Only x = 9."},
{lvl:2,sec:"L",type:"in",q:"Solve ∛(x − 2) = 3.",ans:29,hint:"Undo a cube root by cubing.",expl:"Cube both sides: x − 2 = 27, so x = 29."},
{lvl:2,sec:"L",type:"in",q:"Solve √x + 2 = x.",ans:4,hint:"Isolate the square root before squaring, then test each candidate.",
 expl:"√x = x − 2 gives x = x² − 4x + 4, so x² − 5x + 4 = (x − 1)(x − 4) = 0. x = 1 fails (1 + 2 ≠ 1); x = 4 works (2 + 2 = 4)."},
{lvl:3,sec:"L",type:"in",q:"Solve √(x + 1) + √(x − 2) = 3.",ans:3,hint:"Move one root to the other side before squaring.",
 expl:"√(x + 1) = 3 − √(x − 2). Squaring: x + 1 = 9 − 6√(x − 2) + x − 2, so 6√(x − 2) = 6 and x − 2 = 1. Thus x = 3; check √4 + √1 = 3."},
{lvl:3,sec:"L",type:"in",q:"The equation √(3x + 1) − √(x − 1) = 2 has more than one solution. What is the sum of all its solutions?",ans:6,
 hint:"After squaring once you can factor out √(x − 1); do not divide it away.",
 expl:"√(3x + 1) = 2 + √(x − 1); squaring gives 2x − 2 = 4√(x − 1), so x − 1 = 2√(x − 1). With t = √(x − 1): t² = 2t, so t = 0 or t = 2, giving x = 1 or x = 5. Both check (2 − 0 = 2 and 4 − 2 = 2), so the sum is 6."},
{lvl:3,sec:"L",type:"multi",q:"Select EVERY equation that has NO real solution.",mono:true,opts:["√x = −2","√(x − 1) = 0","√(x + 4) + 1 = 0","√(2x) = 4"],aMulti:[0,2],
 expl:"A square root is never negative, so √x = −2 and √(x + 4) = −1 are impossible. √(x − 1) = 0 has x = 1 and √(2x) = 4 has x = 8."}
],

"g8-vieta": [
{sec:"L",type:"in",q:"What is the discriminant b² − 4ac of x² − 6x + 5 = 0?",ans:16,expl:"b² − 4ac = 36 − 20 = 16. Since it is a positive square, the roots are rational: 1 and 5."},
{sec:"L",type:"mc",q:"How many real roots does x² + 4x + 7 = 0 have?",opts:["0","1","2","3"],a:0,
 expl:"The discriminant is 16 − 28 = −12 < 0, so there are no real roots."},
{sec:"L",type:"in",q:"What is the sum of the roots of x² − 7x + 10 = 0?",ans:7,hint:"Vieta: the sum of the roots is −b/a.",
 expl:"The sum of the roots is −b/a = 7. Indeed the roots are 2 and 5."},
{sec:"L",type:"in",q:"What is the product of the roots of 2x² + 3x − 5 = 0? Give a decimal.",ans:-2.5,hint:"Vieta: the product of the roots is c/a.",
 expl:"The product is c/a = −5/2 = −2.5. Check: the roots are 1 and −2.5."},
{lvl:2,sec:"L",type:"in",q:"If r and s are the roots of x² − 5x + 6 = 0, find r² + s².",ans:13,hint:"Use r² + s² = (r + s)² − 2rs.",
 expl:"r + s = 5 and rs = 6, so r² + s² = 25 − 12 = 13. (The roots 2 and 3 confirm 4 + 9 = 13.)"},
{lvl:2,sec:"L",type:"in",q:"For which positive value of k does x² + kx + 9 = 0 have exactly one real root?",ans:6,
 hint:"Exactly one root means the discriminant is 0.",expl:"k² − 36 = 0, so k = 6. Then x² + 6x + 9 = (x + 3)²."},
{lvl:2,sec:"L",type:"mc",q:"Which quadratic with leading coefficient 1 has roots 3 and −5?",mono:true,opts:["x² + 2x − 15","x² − 2x − 15","x² + 2x + 15","x² − 15x + 2"],a:0,
 expl:"The sum of the roots is −2 and the product is −15, so the quadratic is x² − (sum)x + product = x² + 2x − 15."},
{lvl:3,sec:"L",type:"in",q:"If r and s are the roots of x² − 4x + 1 = 0, find 1/r + 1/s.",ans:4,hint:"Combine into one fraction: (r + s)/(rs).",
 expl:"1/r + 1/s = (r + s)/(rs) = 4/1 = 4."},
{lvl:3,sec:"L",type:"in",q:"If r and s are the roots of x² − 3x − 2 = 0, find r³ + s³.",ans:45,hint:"r³ + s³ = (r + s)³ − 3rs(r + s).",
 expl:"r + s = 3 and rs = −2, so r³ + s³ = 27 − 3(−2)(3) = 27 + 18 = 45."},
{lvl:3,sec:"L",type:"multi",q:"Select EVERY statement that is true for x² + bx + c = 0 with roots r and s.",mono:true,
 opts:["r + s = −b","rs = c","r − s = b","c < 0 means the roots have opposite signs"],aMulti:[0,1,3],
 expl:"Vieta gives r + s = −b and rs = c. The difference r − s is not determined by b alone. If c = rs < 0 then one root is positive and the other negative."}
],

"g8-nonlinear": [
{sec:"L",type:"in",q:"How many points do the graphs of y = x² and y = 4 have in common?",ans:2,expl:"x² = 4 gives x = 2 or x = −2, so the two graphs meet at (2, 4) and (−2, 4): 2 points."},
{sec:"L",type:"in",q:"Solve the system y = x² and y = 2x + 3. What is the larger x-value of the two solutions?",ans:3,hint:"Set the two expressions for y equal.",
 expl:"x² = 2x + 3 gives x² − 2x − 3 = (x − 3)(x + 1) = 0, so x = 3 or x = −1. The larger is 3 (with y = 9)."},
{sec:"L",type:"mc",q:"How many points do y = x² + 1 and y = x − 1 have in common?",opts:["0","1","2","3"],a:0,
 expl:"x² + 1 = x − 1 gives x² − x + 2 = 0, whose discriminant 1 − 8 < 0. The line never reaches the parabola: 0 points."},
{lvl:2,sec:"L",type:"in",q:"The circle x² + y² = 25 and the line y = x + 1 meet at two points. What is the sum of their x-coordinates?",ans:-1,
 hint:"Substitute y = x + 1 into the circle equation.",
 expl:"x² + (x + 1)² = 25 gives 2x² + 2x − 24 = 0, so x² + x − 12 = (x + 4)(x − 3) = 0. The x-values are 3 and −4, with sum −1."},
{lvl:2,sec:"L",type:"mc",q:"Which point lies on both y = x² − 4 and y = 3x?",mono:true,opts:["(4, 12)","(2, 6)","(4, 8)","(−1, 3)"],a:0,
 expl:"x² − 4 = 3x gives x² − 3x − 4 = (x − 4)(x + 1) = 0, so x = 4 or x = −1. At x = 4, y = 12, and (4, 12) is on both."},
{lvl:2,sec:"L",type:"in",q:"Two numbers x and y satisfy xy = 12 and x + y = 7, with x > y. Find x.",ans:4,hint:"The numbers are the roots of t² − 7t + 12 = 0.",
 expl:"t² − 7t + 12 = (t − 3)(t − 4), so the numbers are 3 and 4. The larger one is x = 4."},
{lvl:3,sec:"L",type:"in",q:"Positive numbers x and y satisfy x² + y² = 20 and xy = 8. Find x + y.",ans:6,hint:"Expand (x + y)².",
 expl:"(x + y)² = x² + y² + 2xy = 20 + 16 = 36, so x + y = 6 (both numbers are positive). In fact x and y are 2 and 4."},
{lvl:3,sec:"L",type:"in",q:"For which value of k does the line y = x + k touch the parabola y = x² at exactly one point? Give a decimal.",ans:-0.25,
 hint:"Exactly one common point means the quadratic you get has discriminant 0.",
 expl:"x² = x + k gives x² − x − k = 0, with discriminant 1 + 4k. Setting 1 + 4k = 0 gives k = −0.25; the line is tangent at (0.5, 0.25)."},
{lvl:3,sec:"L",type:"multi",q:"Select EVERY system that has exactly two solutions.",mono:true,
 opts:["y = x² and y = x + 2","y = x² and y = −1","x² + y² = 1 and y = 2","y = x² − 1 and y = 0"],aMulti:[0,3],
 expl:"x² = x + 2 has roots 2 and −1 (two points). x² = −1 has none. y = 2 misses the unit circle entirely. x² − 1 = 0 gives x = ±1 (two points)."}
],

"g8-inequal": [
{sec:"L",type:"mc",q:"Solve x² < 9.",mono:true,opts:["−3 < x < 3","x < 3","x > 3 or x < −3","x < −3"],a:0,
 expl:"x² < 9 means |x| < 3, so x lies strictly between −3 and 3. Test x = 0: 0 < 9 is true; test x = 4: 16 < 9 is false."},
{sec:"L",type:"in",q:"How many integers satisfy x² − 5x + 4 < 0?",ans:2,hint:"Factor and find where the product of the factors is negative.",
 expl:"(x − 1)(x − 4) < 0 exactly when 1 < x < 4. The integers 2 and 3 work: 2 integers."},
{sec:"L",type:"mc",q:"Solve (x − 2)(x + 3) > 0.",mono:true,opts:["x < −3 or x > 2","−3 < x < 2","x > 2","x > −3"],a:0,
 expl:"The product of the factors is positive when both are positive (x > 2) or both are negative (x < −3). Between the roots, e.g. x = 0, the product is −6 < 0."},
{lvl:2,sec:"L",type:"in",q:"How many integers satisfy x² ≤ 20?",ans:9,expl:"x² ≤ 20 means −√20 ≤ x ≤ √20, and √20 ≈ 4.47. The integers from −4 to 4 work: 9 integers."},
{lvl:2,sec:"L",type:"mc",q:"Solve (x − 1)/(x + 2) ≥ 0.",mono:true,opts:["x < −2 or x ≥ 1","−2 < x ≤ 1","x ≥ 1","x ≤ −2 or x ≥ 1"],a:0,
 expl:"The sign changes at x = 1 and x = −2. For x < −2 both parts are negative (positive quotient); for x ≥ 1 both are positive. x = −2 must be excluded because it makes the denominator zero."},
{lvl:2,sec:"L",type:"in",q:"What is the smallest positive integer x for which x² − 2x − 15 > 0?",ans:6,hint:"Factor the quadratic first.",
 expl:"(x − 5)(x + 3) > 0 holds for x > 5 or x < −3. The smallest positive integer above 5 is 6."},
{lvl:3,sec:"L",type:"in",q:"How many integers satisfy 1/(x − 3) ≥ 1/2?",ans:2,hint:"You cannot simply cross-multiply: consider the sign of x − 3.",
 expl:"If x − 3 < 0 the left side is negative, so no solutions. If x − 3 > 0, multiplying by 2(x − 3) gives 2 ≥ x − 3, so 3 < x ≤ 5. The integers are 4 and 5: 2 integers."},
{lvl:3,sec:"L",type:"in",q:"For how many integer values of k does the inequality x² + kx + 9 < 0 have NO solution?",ans:13,
 hint:"The parabola opens upward; it never dips below zero exactly when it has at most one root.",
 expl:"No solution means the discriminant k² − 36 ≤ 0, so −6 ≤ k ≤ 6. That is 13 integer values of k."},
{lvl:3,sec:"L",type:"multi",q:"Select EVERY value of x that satisfies (x² − 4)/(x − 1) < 0.",opts:["−3","0","1.5","3"],aMulti:[0,2],
 expl:"The sign changes at −2, 1 and 2. At x = −3: 5/(−4) < 0. At x = 0: (−4)/(−1) = 4 > 0. At x = 1.5: (−1.75)/0.5 < 0. At x = 3: 5/2 > 0."}
],

"g8-series": [
{sec:"L",type:"in",q:"What is the sum of the first 20 positive integers, 1 + 2 + … + 20?",ans:210,hint:"Pair the first and last terms.",
 expl:"The sum of 1 to n is n(n + 1)/2, so 20 × 21/2 = 210."},
{sec:"L",type:"in",q:"An arithmetic sequence starts 5, 9, 13, … What is its 15th term?",ans:61,hint:"The nth term is the first term plus (n − 1) common differences.",
 expl:"The common difference is 4, so the 15th term is 5 + 14 × 4 = 61."},
{sec:"L",type:"mc",q:"A geometric sequence starts 3, 6, 12, 24, … What is the next term?",opts:["48","36","30","72"],a:0,
 expl:"Each term is double the previous one, so the next term is 24 × 2 = 48."},
{lvl:2,sec:"L",type:"in",q:"Find the sum 2 + 4 + 8 + … + 512.",ans:1022,hint:"The sum of a doubling series is one less than the next term, minus the first term.",
 expl:"This is a geometric series with 9 terms (2 up to 2⁹ = 512). The sum is 2(2⁹ − 1)/(2 − 1) = 2 × 511 = 1022."},
{lvl:2,sec:"L",type:"in",q:"Find the sum of the infinite series 6 + 2 + 2/3 + 2/9 + …",ans:9,hint:"Use a/(1 − r) for an infinite geometric series with |r| < 1.",
 expl:"The first term is 6 and the ratio is 1/3, so the sum is 6/(1 − 1/3) = 6/(2/3) = 9."},
{lvl:2,sec:"L",type:"mc",q:"A sequence is defined by aₙ = 2n² + 1. Which term equals 73?",opts:["6th","5th","7th","8th"],a:0,
 expl:"2n² + 1 = 73 gives n² = 36, so n = 6. The 6th term is 73."},
{lvl:2,sec:"L",type:"order",q:"Put these sums in order from smallest to largest.",items:["1 + 2 + … + 10","2 + 4 + 8 + 16 + 32","1 + 3 + 9 + 27"],
 ansOrder:["1 + 3 + 9 + 27","1 + 2 + … + 10","2 + 4 + 8 + 16 + 32"],
 expl:"1 + 3 + 9 + 27 = 40, 1 + 2 + … + 10 = 55 and 2 + 4 + 8 + 16 + 32 = 62. So the order is 40, 55, 62."},
{lvl:3,sec:"L",type:"in",q:"Find the sum of all multiples of 3 between 1 and 100.",ans:1683,hint:"Factor out 3 and use the formula for 1 + 2 + … + n.",
 expl:"3 + 6 + … + 99 = 3(1 + 2 + … + 33) = 3 × (33 × 34/2) = 3 × 561 = 1683."},
{lvl:3,sec:"L",type:"in",q:"Priya drops a ball from 8 m. Each bounce reaches half the previous height. In metres, what total vertical distance does it travel before coming to rest?",ans:24,
 hint:"It falls 8 m, then goes up and down 4 m, up and down 2 m, and so on.",
 expl:"After the first 8 m fall, every bounce adds up-and-down travel: 2(4 + 2 + 1 + …) = 2 × 8 = 16. Total: 8 + 16 = 24 m."},
{lvl:3,sec:"L",type:"in",q:"In an arithmetic sequence the 3rd term is 10 and the 7th term is 22. What is the sum of the first 10 terms?",ans:175,
 hint:"First find the common difference from the gap between the 3rd and 7th terms.",
 expl:"Four steps take 10 to 22, so d = 3 and the first term is 10 − 2 × 3 = 4. S₁₀ = 10/2 × (2 × 4 + 9 × 3) = 5 × 35 = 175."}
],

"g8-complex": [
{sec:"L",type:"in",q:"By definition of the imaginary unit, what number is i²?",ans:-1,expl:"The imaginary unit i is defined so that i² = −1."},
{sec:"L",type:"mc",q:"Compute (3 + 2i) + (1 − 5i).",mono:true,opts:["4 − 3i","4 + 7i","2 + 7i","4 − 7i"],a:0,
 expl:"Add real parts and imaginary parts separately: (3 + 1) + (2 − 5)i = 4 − 3i."},
{sec:"L",type:"in",q:"What is the real part of (2 + i)(3 − i)?",ans:7,hint:"Expand like binomials and use i² = −1.",
 expl:"(2 + i)(3 − i) = 6 − 2i + 3i − i² = 6 + i + 1 = 7 + i. The real part is 7."},
{lvl:2,sec:"L",type:"in",q:"Find the modulus |3 + 4i|.",ans:5,hint:"The modulus is the distance from 0 to the point (3, 4).",expl:"|3 + 4i| = √(3² + 4²) = √25 = 5."},
{lvl:2,sec:"L",type:"mc",q:"What is i^2025?",mono:true,opts:["i","−i","1","−1"],a:0,
 expl:"Powers of i repeat every 4: i, −1, −i, 1. Since 2025 = 4 × 506 + 1, i^2025 = i¹ = i."},
{lvl:2,sec:"L",type:"in",q:"What is the imaginary part of (1 + i)²?",ans:2,expl:"(1 + i)² = 1 + 2i + i² = 1 + 2i − 1 = 2i. The imaginary part is 2."},
{lvl:2,sec:"L",type:"mc",q:"What are the solutions of x² + 4 = 0?",mono:true,opts:["2i and −2i","2 and −2","4i and −4i","i and −i"],a:0,
 expl:"x² = −4, so x = ±√(−4) = ±2i. Check: (2i)² = 4i² = −4."},
{lvl:3,sec:"L",type:"in",q:"Compute (1 + i)⁸.",ans:16,hint:"First find (1 + i)², then raise that to the 4th power.",
 expl:"(1 + i)² = 2i, so (1 + i)⁸ = (2i)⁴ = 16 × i⁴ = 16 × 1 = 16."},
{lvl:3,sec:"L",type:"in",q:"The equation x² − 2x + 5 = 0 has roots a ± bi with b > 0. Find b.",ans:2,hint:"Use the quadratic formula; the discriminant is negative.",
 expl:"x = (2 ± √(4 − 20))/2 = (2 ± √(−16))/2 = (2 ± 4i)/2 = 1 ± 2i. So b = 2."},
{lvl:3,sec:"L",type:"multi",q:"Select EVERY statement that is true.",mono:true,opts:["i³ = −i","(2 + i)(2 − i) = 5","|z| can be negative","(1 + i)/(1 − i) = i"],aMulti:[0,1,3],
 expl:"i³ = i² × i = −i. (2 + i)(2 − i) = 4 − i² = 5. A modulus is a distance, never negative. (1 + i)/(1 − i) = (1 + i)²/((1 − i)(1 + i)) = 2i/2 = i."}
],

"g8-ceva": [
{sec:"G",type:"mc",q:"What is a cevian of a triangle?",
 opts:["A segment from a vertex to the opposite side","A line through the centre of a circle","The longest side of the triangle","A segment joining two midpoints"],a:0,
 expl:"A cevian joins a vertex to a point on the opposite side (or its extension). Medians, altitudes and angle bisectors are all cevians."},
{sec:"G",type:"in",q:"In triangle ABC the cevians AD, BE and CF meet at one point. BD = 4, DC = 2, CE = 1 and EA = 4. Find the ratio AF/FB.",ans:2,
 hint:"Ceva: (BD/DC) × (CE/EA) × (AF/FB) = 1 for concurrent cevians.",
 expl:"(4/2) × (1/4) × (AF/FB) = 1 gives (1/2)(AF/FB) = 1, so AF/FB = 2."},
{sec:"G",type:"in",q:"D, E and F are the midpoints of BC, CA and AB. What is the value of the product (BD/DC) × (CE/EA) × (AF/FB)?",ans:1,
 expl:"Each ratio is 1 because each point is a midpoint, so the product is 1 × 1 × 1 = 1 — consistent with the medians being concurrent (Ceva)."},
{lvl:2,sec:"G",type:"in",q:"In triangle ABC, cevians AD, BE and CF are concurrent, with BD = 3, DC = 6, CE = 4, EA = 2 and AB = 12. Find AF.",ans:6,
 hint:"Use Ceva to find AF/FB, then split AB in that ratio.",
 expl:"(3/6)(4/2)(AF/FB) = 1 gives AF/FB = 1, so F is the midpoint of AB and AF = 6."},
{lvl:2,sec:"G",type:"in",q:"In triangle ABC, AB = 6, AC = 9 and BC = 10. The angle bisector from A meets BC at D. Find BD.",ans:4,
 hint:"The angle bisector theorem: BD/DC = AB/AC.",
 expl:"BD/DC = 6/9 = 2/3, so BD is 2/5 of BC: BD = (2/5) × 10 = 4."},
{lvl:2,sec:"G",type:"mc",q:"Menelaus: a straight line crosses the lines BC, CA and AB of triangle ABC at D, E and F. Using unsigned lengths, what does (BD/DC) × (CE/EA) × (AF/FB) equal?",opts:["1","2","0","−2"],a:0,
 expl:"Menelaus' theorem says the product of the three ratios is 1 in unsigned lengths (it is −1 with signed lengths, since an odd number of the points lie outside the sides)."},
{lvl:3,sec:"G",type:"in",q:"A line passes through D on BC with BD = 2, DC = 4 and through E on CA with CE = 3, EA = 3, then meets line AB extended at F. Find AF/FB.",ans:2,
 hint:"Apply Menelaus' theorem with unsigned lengths.",
 expl:"(2/4)(3/3)(AF/FB) = 1 gives (1/2)(AF/FB) = 1, so AF/FB = 2. Since F is beyond B, AF is twice FB."},
{lvl:3,sec:"G",type:"in",q:"In triangle ABC, D is the midpoint of BC and E lies on CA with CE = 1, EA = 2. AD and BE meet at P. Find AP/PD.",ans:4,
 hint:"Use mass points: put equal masses on B and C, then balance E.",
 expl:"Masses B = C = 2 make D their balance point (mass 4). For E to balance, mass A × EA = mass C × CE, so A = 1. Then AP/PD = mass D / mass A = 4."},
{lvl:3,sec:"G",type:"mc",q:"Points D, E, F lie on the sides BC, CA, AB of a triangle and (BD/DC)(CE/EA)(AF/FB) = 1. What follows by the converse of Ceva?",
 opts:["AD, BE and CF are concurrent","The triangle is equilateral","D, E and F are collinear","AD is an altitude"],a:0,
 expl:"The converse of Ceva's theorem: if the product of the ratios equals 1 for points on the sides, the three cevians pass through a single point."}
],

"g8-power": [
{sec:"G",type:"in",q:"Chords AB and CD of a circle cross at P inside the circle. AP = 3, PB = 8 and CP = 4. Find PD.",ans:6,hint:"Intersecting chords: AP × PB = CP × PD.",
 expl:"3 × 8 = 4 × PD, so PD = 24/4 = 6."},
{sec:"G",type:"mc",q:"In a cyclic quadrilateral, what do two opposite angles add up to?",opts:["180°","90°","360°","270°"],a:0,
 expl:"Opposite angles of a cyclic quadrilateral are supplementary: each pair sums to 180°, because together they subtend the whole circle."},
{sec:"G",type:"in",q:"ABCD is a cyclic quadrilateral with angle A = 75°. What is angle C in degrees?",ans:105,expl:"Opposite angles of a cyclic quadrilateral sum to 180°, so C = 180° − 75° = 105°."},
{lvl:2,sec:"G",type:"in",q:"From a point P outside a circle, a secant meets the circle at A and B with PA = 4 and PB = 9. A tangent from P touches the circle at T. Find PT.",ans:6,
 hint:"Tangent–secant: PT² = PA × PB.",expl:"PT² = 4 × 9 = 36, so PT = 6."},
{lvl:2,sec:"G",type:"in",q:"Two secants from an external point P meet a circle at A, B and at C, D. PA = 3, PB = 12 and PC = 4. Find PD.",ans:9,
 hint:"Both secants give the same power of the point: PA × PB = PC × PD.",expl:"3 × 12 = 36 = 4 × PD, so PD = 9."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY quadrilateral that is always cyclic.",opts:["Rectangle","Isosceles trapezium","Rhombus that is not a square","Square"],aMulti:[0,1,3],
 expl:"Rectangles and squares have opposite angles 90° + 90° = 180°, and an isosceles trapezium has supplementary opposite angles. A non-square rhombus has opposite angles equal but not 90°, so they cannot sum to 180°."},
{lvl:3,sec:"G",type:"in",q:"Point P is 10 cm from the centre of a circle of radius 6 cm. What is the length in cm of a tangent from P to the circle?",ans:8,
 hint:"The power of P is (distance to centre)² − r²; it equals the tangent length squared.",
 expl:"The tangent, radius and centre line form a right triangle: PT² = 10² − 6² = 64, so PT = 8 cm."},
{lvl:3,sec:"G",type:"in",q:"A chord of a circle has length 16 cm. Its midpoint M is 2 cm from the nearest point of the circle. Find the radius in cm.",ans:17,
 hint:"Extend the perpendicular through M into a diameter and use intersecting chords.",
 expl:"The diameter through M is cut into pieces 2 and 2r − 2. Intersecting chords: 8 × 8 = 2(2r − 2), so 64 = 4r − 4 and r = 17 cm."},
{lvl:3,sec:"G",type:"in",q:"Equilateral triangle ABC is inscribed in a circle. P lies on the arc BC not containing A, with PB = 3 and PC = 5. Find PA.",ans:8,
 hint:"Apply Ptolemy's theorem to the cyclic quadrilateral ABPC.",
 expl:"Ptolemy: PA × BC = PB × AC + PC × AB. All sides of the triangle are equal, so PA = PB + PC = 3 + 5 = 8."},
{lvl:3,sec:"G",type:"mc",q:"In cyclic quadrilateral ABCD, angle ABD = 40°. Which other angle must also be 40°?",mono:true,opts:["∠ACD","∠ADB","∠BAD","∠BCD"],a:0,
 expl:"Angles ABD and ACD both stand on the arc AD, and angles in the same segment are equal. So ∠ACD = 40°."}
],

"g8-trig": [
{sec:"G",type:"in",q:"A right triangle has legs 3 and 4 and hypotenuse 5. What is the sine of the angle opposite the side of length 3? Give a decimal.",ans:0.6,
 hint:"sine = opposite ÷ hypotenuse.",expl:"sin = opposite/hypotenuse = 3/5 = 0.6."},
{sec:"G",type:"mc",q:"What is tan 45°?",mono:true,opts:["1","0.5","√2","0"],a:0,
 expl:"In a 45°–45°–90° triangle the two legs are equal, so tan 45° = opposite/adjacent = 1."},
{sec:"G",type:"in",q:"What is sin 30° as a decimal?",ans:0.5,expl:"In a 30°–60°–90° triangle the side opposite 30° is half the hypotenuse, so sin 30° = 0.5."},
{lvl:2,sec:"G",type:"in",q:"A right triangle has hypotenuse 10 and one angle of 30°. How long is the side opposite the 30° angle?",ans:5,
 expl:"opposite = hypotenuse × sin 30° = 10 × 0.5 = 5."},
{lvl:2,sec:"G",type:"in",q:"Two sides of a triangle are 5 and 8 and the angle between them is 60°. Find the third side.",ans:7,
 hint:"Law of cosines: c² = a² + b² − 2ab cos C, with cos 60° = 0.5.",
 expl:"c² = 25 + 64 − 2 × 5 × 8 × 0.5 = 89 − 40 = 49, so c = 7."},
{lvl:2,sec:"G",type:"mc",q:"In triangle ABC, angle A = 30°, angle B = 90° and side a (opposite A) is 4. Use the law of sines to find side b.",opts:["8","2","4","6"],a:0,
 expl:"a/sin A = b/sin B gives 4/0.5 = b/1, so b = 8. (Side b is the hypotenuse, twice the side opposite 30°.)"},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY statement that is true.",mono:true,opts:["sin 60° = cos 30°","tan θ = sin θ / cos θ","sin² θ + cos² θ = 1","sin 90° = 0"],aMulti:[0,1,2],
 expl:"Sine of an angle equals cosine of its complement, tan is sin over cos, and the Pythagorean identity always holds. sin 90° = 1, not 0."},
{lvl:3,sec:"G",type:"in",q:"A triangle has sides 4, 5 and 6. Find the cosine of the angle opposite the side of length 6, as a decimal.",ans:0.125,
 hint:"Rearrange the law of cosines: cos C = (a² + b² − c²)/(2ab).",
 expl:"cos C = (16 + 25 − 36)/(2 × 4 × 5) = 5/40 = 0.125."},
{lvl:3,sec:"G",type:"in",q:"Two sides of a triangle are 6 cm and 10 cm and the angle between them is 30°. What is the area in cm²?",ans:15,
 hint:"Area = ½ab sin C.",expl:"Area = ½ × 6 × 10 × sin 30° = 30 × 0.5 = 15 cm²."},
{lvl:3,sec:"G",type:"in",q:"A triangle has sides 3, 5 and 7. What is the size in degrees of its largest angle?",ans:120,
 hint:"The largest angle is opposite the longest side; use the law of cosines and recall which angle has cosine −0.5.",
 expl:"cos C = (9 + 25 − 49)/(2 × 3 × 5) = −15/30 = −0.5, and the angle with cosine −0.5 is 120°."}
],

"g8-euler": [
{sec:"G",type:"in",q:"A cube has V = 8 vertices, E = 12 edges and F = 6 faces. Compute V − E + F.",ans:2,expl:"8 − 12 + 6 = 2. Euler's formula gives 2 for every convex polyhedron."},
{sec:"G",type:"in",q:"A convex polyhedron has 6 vertices and 12 edges. How many faces does it have?",ans:8,hint:"Use V − E + F = 2.",
 expl:"F = 2 − V + E = 2 − 6 + 12 = 8. This is the octahedron."},
{sec:"G",type:"mc",q:"How many Platonic solids are there?",opts:["5","4","6","8"],a:0,
 expl:"Exactly five: tetrahedron, cube, octahedron, dodecahedron and icosahedron."},
{sec:"G",type:"mc",q:"Which Platonic solid has 20 faces?",opts:["Icosahedron","Dodecahedron","Octahedron","Tetrahedron"],a:0,
 expl:"The icosahedron has 20 triangular faces ('icosa' means twenty). The dodecahedron has 12, the octahedron 8 and the tetrahedron 4."},
{lvl:2,sec:"G",type:"in",q:"A dodecahedron has 12 pentagonal faces. How many edges does it have?",ans:30,hint:"Each edge is shared by two faces.",
 expl:"12 faces × 5 edges each counts every edge twice, so E = 60/2 = 30."},
{lvl:2,sec:"G",type:"in",q:"An icosahedron has 20 triangular faces and 30 edges. How many vertices does it have?",ans:12,hint:"Use Euler's formula.",
 expl:"V = 2 − F + E = 2 − 20 + 30 = 12."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY pair that are dual solids (faces of one correspond to vertices of the other).",
 opts:["Cube and octahedron","Dodecahedron and icosahedron","Tetrahedron and cube","Tetrahedron and itself"],aMulti:[0,1,3],
 expl:"The cube (6 faces, 8 vertices) and octahedron (8 faces, 6 vertices) are duals, as are the dodecahedron (12 faces, 20 vertices) and icosahedron (20 faces, 12 vertices). The tetrahedron (4 faces, 4 vertices) is self-dual."},
{lvl:3,sec:"G",type:"in",q:"A classic football is a polyhedron with 12 pentagons and 20 hexagons. How many vertices does it have?",ans:60,
 hint:"Count the edges first (each edge belongs to two faces), then use Euler's formula.",
 expl:"E = (12 × 5 + 20 × 6)/2 = 180/2 = 90 and F = 32, so V = 2 − 32 + 90 = 60."},
{lvl:3,sec:"G",type:"in",q:"A convex polyhedron has 8 vertices and every face is a triangle. How many edges does it have?",ans:18,
 hint:"Triangular faces give 3F = 2E; combine this with Euler's formula.",
 expl:"F = 2E/3, so 8 − E + 2E/3 = 2, giving E/3 = 6 and E = 18 (with F = 12)."},
{lvl:3,sec:"G",type:"mc",q:"Why is there no Platonic solid with regular hexagonal faces?",
 opts:["Three hexagons at a vertex already fill 360°","Hexagons cannot be regular","Hexagons have too many edges to share","Six faces cannot meet at a vertex"],a:0,
 expl:"Each angle of a regular hexagon is 120°, so three meeting at a vertex make 360° — flat, with no room to fold into a solid. Fewer than three faces cannot form a corner."}
],

"g8-vectors": [
{sec:"G",type:"in",q:"Let u = (2, 3) and v = (−1, 4). What is the x-component of 2u − v?",ans:5,hint:"Scale u first, then subtract component by component.",
 expl:"2u = (4, 6) and 2u − v = (4 + 1, 6 − 4) = (5, 2). The x-component is 5."},
{sec:"G",type:"in",q:"What is the length (magnitude) of the vector (6, 8)?",ans:10,expl:"|(6, 8)| = √(6² + 8²) = √100 = 10."},
{sec:"G",type:"mc",q:"Which vector is parallel to (2, −1)?",mono:true,opts:["(−4, 2)","(1, 2)","(2, 1)","(4, 2)"],a:0,
 expl:"Parallel vectors are scalar multiples of each other: (−4, 2) = −2 × (2, −1). The others are not multiples of (2, −1)."},
{lvl:2,sec:"G",type:"in",q:"Compute the dot product (3, 4) · (2, −1).",ans:2,expl:"Multiply matching components and add: 3 × 2 + 4 × (−1) = 6 − 4 = 2."},
{lvl:2,sec:"G",type:"in",q:"A point moves along x = 2 + 3t, y = 1 − t. What is y at the moment when x = 11?",ans:-2,hint:"Find t from the x-equation first.",
 expl:"2 + 3t = 11 gives t = 3, so y = 1 − 3 = −2."},
{lvl:2,sec:"G",type:"mc",q:"Which Cartesian equation describes the parametric line x = 1 + 2t, y = 3 + 4t?",mono:true,opts:["y = 2x + 1","y = 4x + 3","y = 2x − 1","y = x + 2"],a:0,
 expl:"t = (x − 1)/2, so y = 3 + 4(x − 1)/2 = 3 + 2x − 2 = 2x + 1. Check t = 0: the point (1, 3) satisfies y = 2x + 1."},
{lvl:2,sec:"G",type:"pair",q:"Give the vector from A(1, 2) to B(4, −3) as (x, y).",ansP:[3,-5],hint:"Subtract the coordinates of A from those of B.",
 expl:"AB = B − A = (4 − 1, −3 − 2) = (3, −5)."},
{lvl:3,sec:"G",type:"in",q:"What is the angle in degrees between the vectors (1, 0) and (1, 1)?",ans:45,hint:"cos θ = (u · v)/(|u| |v|).",
 expl:"u · v = 1, |u| = 1 and |v| = √2, so cos θ = 1/√2 and θ = 45°."},
{lvl:3,sec:"G",type:"in",q:"For which value of k is (k, 6) perpendicular to (3, −2)?",ans:4,hint:"Perpendicular vectors have dot product 0.",
 expl:"3k + 6 × (−2) = 0 gives 3k = 12, so k = 4."},
{lvl:3,sec:"G",type:"in",q:"Lior steers a boat from the origin with constant velocity (3, 4) metres per second. After how many seconds is he 25 m from the start?",ans:5,
 hint:"First find the speed, which is the magnitude of the velocity.",
 expl:"The speed is |(3, 4)| = 5 m/s, so covering 25 m takes 25/5 = 5 seconds (at the point (15, 20))."},
{lvl:3,sec:"G",type:"multi",q:"Select EVERY vector that is perpendicular to (2, 5).",mono:true,opts:["(5, −2)","(−5, 2)","(2, 5)","(5, 2)"],aMulti:[0,1],
 expl:"Dot products with (2, 5): 10 − 10 = 0, −10 + 10 = 0, 4 + 25 = 29, 10 + 10 = 20. Only the first two give 0."}
],

"g8-noneuclid": [
{sec:"G",type:"mc",q:"On a flat plane the angles of a triangle add to 180°. What is true of a triangle drawn on a sphere?",
 opts:["The angles add to more than 180°","The angles add to exactly 180°","The angles add to less than 180°","The angles add to exactly 360°"],a:0,
 expl:"Spherical triangles bulge outward, so their angle sum exceeds 180°. The larger the triangle relative to the sphere, the bigger the excess."},
{sec:"G",type:"mc",q:"In hyperbolic geometry, how many lines through a point P not on line L never meet L?",opts:["Infinitely many","Exactly one","None","Exactly two"],a:0,
 expl:"Euclid's parallel postulate (exactly one parallel) is replaced in hyperbolic geometry by: there are infinitely many lines through P that never meet L."},
{sec:"G",type:"in",q:"A triangle on a globe has a vertex at the North Pole and two vertices on the equator a quarter of the way around. All three angles are right angles. What is the angle sum in degrees?",ans:270,
 expl:"Three right angles give 90° + 90° + 90° = 270°, which is 90° more than a flat triangle — the 'angular excess'."},
{lvl:2,sec:"G",type:"in",q:"On a sphere, a triangle's area is proportional to its angular excess (angle sum − 180°). A triangle with three 90° angles covers 1/8 of the sphere. What fraction of the sphere does a triangle with three 120° angles cover? Give a decimal.",ans:0.25,
 hint:"Compare the two excesses.",
 expl:"The first excess is 90° and the second is 360° − 180° = 180°, twice as much. So the area is 2 × 1/8 = 1/4 = 0.25 of the sphere."},
{lvl:2,sec:"G",type:"mc",q:"Which curve plays the role of a 'straight line' on a sphere?",opts:["A great circle","A circle of latitude near a pole","A small circle","A spiral"],a:0,
 expl:"Great circles (like the equator) are the shortest paths between points on a sphere, so they are the geodesics, the spherical version of straight lines."},
{lvl:2,sec:"G",type:"in",q:"A hyperbolic triangle has angles 50°, 60° and 40°. Its 'defect' is 180° minus the angle sum. What is the defect in degrees?",ans:30,
 expl:"The angle sum is 50 + 60 + 40 = 150°, so the defect is 180° − 150° = 30°. In hyperbolic geometry the defect measures area."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY statement that is true in spherical geometry.",
 opts:["Any two great circles meet","Triangle angle sums exceed 180°","There are parallel lines","Rectangles exist"],aMulti:[0,1],
 expl:"Two great circles always cross (in two antipodal points), so there are no parallels. Angle sums exceed 180°. A quadrilateral with four right angles would have angle sum exactly 360°, which is impossible on a sphere."},
{lvl:3,sec:"G",type:"in",q:"Walk 10 000 km south from the North Pole to the equator, turn 90° and walk 10 000 km along the equator, then turn 90° and walk 10 000 km back to the pole. Earth's circumference is about 40 000 km. What fraction of Earth's surface does this triangle enclose? Give a decimal.",ans:0.125,
 hint:"Each leg is a quarter of a great circle; think of the sphere cut by three perpendicular planes.",
 expl:"The three legs are quarter great circles meeting at right angles, so the triangle is one octant of the sphere: 1/8 = 0.125."},
{lvl:3,sec:"G",type:"mc",q:"Why can Euclid's parallel postulate not be proved from his other four postulates?",
 opts:["Consistent geometries exist in which it is false","Euclid never wrote it down","It holds only for small triangles","It is a definition, not a postulate"],a:0,
 expl:"Spherical and hyperbolic geometry satisfy the other postulates but not the parallel postulate. If it followed from them, no such geometry could exist."},
{lvl:3,sec:"G",type:"in",q:"On a sphere, a triangle's area as a fraction of the whole surface equals its angular excess divided by 720°. A triangle has angles 90°, 90° and 36°. What fraction of the sphere does it cover? Give a decimal.",ans:0.05,
 hint:"First compute the excess: angle sum − 180°.",
 expl:"The excess is 216° − 180° = 36°, so the fraction is 36/720 = 0.05. (Check the rule with the octant: 90/720 = 1/8.)"}
],

"g8-genfunc": [
{sec:"K",type:"mc",q:"Which generating function has coefficients 1, 1, 1, 1, … (that is, 1 + x + x² + x³ + …)?",mono:true,opts:["1/(1 − x)","1 + x","x/(1 − x)","1/(1 + x)"],a:0,
 expl:"The geometric series 1 + x + x² + … sums to 1/(1 − x). (x/(1 − x) starts at x, and 1/(1 + x) has alternating signs.)"},
{sec:"K",type:"in",q:"What is the coefficient of x² in (1 + x)⁴?",ans:6,hint:"Use the binomial coefficients from row 4 of Pascal's triangle.",
 expl:"(1 + x)⁴ = 1 + 4x + 6x² + 4x³ + x⁴, so the coefficient is C(4, 2) = 6."},
{sec:"K",type:"in",q:"The Fibonacci numbers satisfy F₁ = 1, F₂ = 1 and Fₙ = Fₙ₋₁ + Fₙ₋₂. What is F₁₀?",ans:55,
 expl:"1, 1, 2, 3, 5, 8, 13, 21, 34, 55 — the 10th term is 55."},
{lvl:2,sec:"K",type:"in",q:"What is the coefficient of x³ in (1 + x + x²)(1 + x)³?",ans:7,hint:"Expand (1 + x)³ first, then collect every way to make x³.",
 expl:"(1 + x)³ = 1 + 3x + 3x² + x³. The x³ terms come from 1 × x³, x × 3x² and x² × 3x: 1 + 3 + 3 = 7."},
{lvl:2,sec:"K",type:"in",q:"A sequence satisfies a₁ = 1 and aₙ = 2aₙ₋₁ + 1. What is a₅?",ans:31,
 expl:"a₂ = 3, a₃ = 7, a₄ = 15, a₅ = 31. (In general aₙ = 2ⁿ − 1.)"},
{lvl:2,sec:"K",type:"mc",q:"The number of ways to make 6 cents from 1-cent and 2-cent coins is the coefficient of x⁶ in 1/((1 − x)(1 − x²)). What is it?",opts:["4","3","6","7"],a:0,
 expl:"Choose how many 2-cent coins to use: 0, 1, 2 or 3, and fill the rest with 1-cent coins. That is 4 ways."},
{lvl:2,sec:"K",type:"in",q:"How many ways are there to write 5 as an ordered sum of 1s and 2s (for example 1 + 2 + 2 and 2 + 1 + 2 are different)?",ans:8,
 hint:"Let cₙ be the count for n; the first part is 1 or 2, so cₙ = cₙ₋₁ + cₙ₋₂.",
 expl:"c₁ = 1, c₂ = 2, c₃ = 3, c₄ = 5, c₅ = 8. These are Fibonacci numbers."},
{lvl:3,sec:"K",type:"in",q:"The generating function (x + x² + x³ + x⁴ + x⁵ + x⁶)² counts the sums of two dice. What is the coefficient of x⁷?",ans:6,
 hint:"Count the pairs (a, b) with 1 ≤ a, b ≤ 6 and a + b = 7.",
 expl:"The pairs are (1, 6), (2, 5), (3, 4), (4, 3), (5, 2), (6, 1) — 6 of them, so the coefficient is 6."},
{lvl:3,sec:"K",type:"in",q:"A sequence satisfies a₀ = 0, a₁ = 1 and aₙ = 3aₙ₋₁ − 2aₙ₋₂. What is a₆?",ans:63,hint:"Compute the terms one at a time, or spot that aₙ = 2ⁿ − 1.",
 expl:"a₂ = 3, a₃ = 7, a₄ = 15, a₅ = 31, a₆ = 63. The closed form is aₙ = 2ⁿ − 1."},
{lvl:3,sec:"K",type:"multi",q:"Select EVERY statement that is true about G(x) = 1/(1 − 2x).",
 opts:["The coefficient of xⁿ is 2ⁿ","G(x) = 1 + 2x + 4x² + …","The coefficient of x³ is 6","It generates the sequence 1, 2, 4, 8, …"],aMulti:[0,1,3],
 expl:"1/(1 − 2x) = 1 + 2x + (2x)² + (2x)³ + …, so the coefficient of xⁿ is 2ⁿ and the sequence is 1, 2, 4, 8, … The coefficient of x³ is 8, not 6."}
],

"g8-polya": [
{sec:"K",type:"in",q:"How many rotational symmetries does a square have, counting the 'do nothing' rotation?",ans:4,expl:"Rotations by 0°, 90°, 180° and 270° — 4 in total."},
{sec:"K",type:"mc",q:"Burnside's lemma says the number of distinct patterns (up to symmetry) equals which quantity?",
 opts:["The average number of colourings fixed by a symmetry","The total colourings divided by 2","The number of symmetries","The number of colourings fixed by the identity"],a:0,
 expl:"Burnside: count, for each symmetry, how many colourings it leaves unchanged; then average over all symmetries."},
{sec:"K",type:"in",q:"Each corner of a square is coloured black or white. Counting two colourings as the same if a rotation turns one into the other, how many different colourings are there?",ans:6,
 hint:"Burnside: identity fixes 16, the 90° and 270° rotations fix 2 each, 180° fixes 4.",
 expl:"(16 + 2 + 4 + 2)/4 = 24/4 = 6. They are: all white, all black, one black, two adjacent black, two opposite black, three black."},
{lvl:2,sec:"K",type:"in",q:"A necklace has 3 beads, each red or blue, and can be rotated. How many different necklaces are there?",ans:4,
 hint:"The identity fixes all 8 colourings; each of the two other rotations fixes only the single-colour ones.",
 expl:"Burnside: (8 + 2 + 2)/3 = 4. They are: 3 red, 2 red 1 blue, 1 red 2 blue, 3 blue."},
{lvl:2,sec:"K",type:"in",q:"The corners of a square are coloured with 3 colours. How many colourings are left unchanged by the 180° rotation?",ans:9,
 hint:"The 180° rotation swaps opposite corners, so it has 2 cycles of corners.",
 expl:"Opposite corners must match, so each of the 2 pairs is chosen freely: 3² = 9 colourings."},
{lvl:2,sec:"K",type:"mc",q:"A bracelet has 4 beads, each black or white. It can be rotated AND flipped over (8 symmetries). How many different bracelets are there?",opts:["6","4","8","16"],a:0,
 expl:"Fixed colourings: identity 16; 90° and 270° rotations 2 each; 180° rotation 4; the two diagonal flips 8 each; the two edge flips 4 each. Total 48, divided by 8 symmetries gives 6."},
{lvl:3,sec:"K",type:"in",q:"A necklace has 6 beads, each red or blue, and can be rotated (but not flipped). How many different necklaces are there?",ans:14,
 hint:"A rotation by k positions splits the beads into gcd(k, 6) cycles; each cycle must be one colour.",
 expl:"Fixed colourings: identity 2⁶ = 64; rotations by 1 and 5 give 2 each; by 2 and 4 give 2² = 4 each; by 3 gives 2³ = 8. Sum 84, divided by 6 gives 14."},
{lvl:3,sec:"K",type:"in",q:"Each face of a cube is painted black or white. Two cubes count as the same if one can be rotated into the other. How many different painted cubes are there?",ans:10,
 hint:"The cube has 24 rotations; group them by type and count the face cycles of each.",
 expl:"Burnside over the 24 rotations: identity 64; six 90°/270° face turns fix 8 each; three 180° face turns fix 16 each; eight vertex turns fix 4 each; six edge turns fix 8 each. (64 + 48 + 48 + 32 + 48)/24 = 240/24 = 10."},
{lvl:3,sec:"K",type:"mc",q:"A 2 × 2 grid of squares is coloured with 3 colours. Counting rotations of the whole grid as the same, how many colourings are there?",opts:["24","21","27","81"],a:0,
 expl:"Identity fixes 3⁴ = 81; the 90° and 270° rotations fix 3 each (all squares equal); the 180° rotation fixes 3² = 9. (81 + 3 + 9 + 3)/4 = 96/4 = 24."}
],

"g8-planar": [
{sec:"K",type:"in",q:"A connected planar graph is drawn with 5 vertices and 7 edges. How many faces does the drawing have, counting the outside region?",ans:4,
 hint:"Euler: V − E + F = 2.",expl:"F = 2 − V + E = 2 − 5 + 7 = 4."},
{sec:"K",type:"mc",q:"The Four Colour Theorem says any map can be coloured, with neighbouring regions different, using at most how many colours?",opts:["4","3","5","6"],a:0,
 expl:"Four colours always suffice for a planar map. Some maps genuinely need all four."},
{sec:"K",type:"in",q:"What is the chromatic number (fewest colours so that joined vertices differ) of a triangle graph?",ans:3,
 expl:"All three vertices are joined to each other, so all three need different colours: 3."},
{lvl:2,sec:"K",type:"mc",q:"Which graph is NOT planar?",opts:["K5, the complete graph on 5 vertices","K4, the complete graph on 4 vertices","A cycle with 6 vertices","A tree with 10 vertices"],a:0,
 expl:"K5 cannot be drawn without crossings (it has 10 edges, more than the planar limit 3V − 6 = 9). K4 can be drawn with one vertex inside a triangle; cycles and trees are planar."},
{lvl:2,sec:"K",type:"in",q:"A simple planar graph with V ≥ 3 vertices has at most 3V − 6 edges. What is the maximum number of edges for 8 vertices?",ans:18,expl:"3 × 8 − 6 = 18 edges."},
{lvl:2,sec:"K",type:"in",q:"What is the chromatic number of a cycle with 7 vertices?",ans:3,hint:"Try alternating two colours around the cycle.",
 expl:"Alternating two colours around an odd cycle makes the first and last vertices clash, so a third colour is needed: 3."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY graph that can be properly coloured with just 2 colours.",opts:["A cycle with 8 vertices","Any tree","A cycle with 5 vertices","K4"],aMulti:[0,1],
 expl:"Even cycles and trees have no odd cycles, so two colours suffice. An odd cycle needs 3 colours and K4 needs 4."},
{lvl:3,sec:"K",type:"in",q:"K5 has 5 vertices and 10 edges. By how many edges does it exceed the planar maximum 3V − 6?",ans:1,
 expl:"3 × 5 − 6 = 9, and 10 − 9 = 1. Even one edge too many proves K5 is not planar."},
{lvl:3,sec:"K",type:"in",q:"K3,3 has 6 vertices and 9 edges. If it were planar, how many faces would Euler's formula force it to have?",ans:5,
 hint:"Use V − E + F = 2; then notice a bipartite graph has no triangles.",
 expl:"F = 2 − 6 + 9 = 5. Every face would need at least 4 edges, requiring 2E ≥ 4F, i.e. 18 ≥ 20 — impossible, so K3,3 is not planar."},
{lvl:3,sec:"K",type:"in",q:"A planar graph with 10 vertices is drawn so that every face, including the outer one, is a triangle. How many edges does it have?",ans:24,
 hint:"Every edge borders exactly two triangular faces, so 3F = 2E.",
 expl:"With F = 2E/3, Euler gives 10 − E + 2E/3 = 2, so E/3 = 8 and E = 24 (the maximum 3V − 6)."},
{lvl:3,sec:"K",type:"mc",q:"A map is drawn on a page so that every region shares a border with every other region. What is the largest possible number of regions?",opts:["4","5","6","3"],a:0,
 expl:"Regions that all touch each other correspond to a complete graph; K4 is planar but K5 is not, so at most 4 regions."}
],

"g8-ramsey": [
{sec:"K",type:"mc",q:"Among any 6 people there are always 3 mutual friends or 3 mutual strangers. This fact is written R(3, 3) = ?",opts:["6","5","3","9"],a:0,
 expl:"The Ramsey number R(3, 3) = 6: six people always contain a triangle of friends or a triangle of strangers, and 5 people need not."},
{sec:"K",type:"in",q:"In a group of 6 people, pick one person. Each of the other 5 is either a friend or a stranger to that person. At least how many of the 5 are of the same kind?",ans:3,
 hint:"Pigeonhole: 5 people into 2 categories.",expl:"Splitting 5 into two groups, one group has at least 3 (since 2 + 2 = 4 < 5)."},
{sec:"K",type:"mc",q:"Why is R(3, 3) greater than 5?",
 opts:["The 5-cycle colouring has no one-colour triangle","Because 5 is an odd number","Because 5 people make only 10 pairs","Because R(3, 3) must be even"],a:0,
 expl:"Colour the edges of a pentagon red and its 5 diagonals blue: neither colour contains a triangle. So 5 people are not enough."},
{lvl:2,sec:"K",type:"in",q:"R(2, k) = k for every k, because either two people are friends or everyone is a stranger to everyone. What is R(2, 7)?",ans:7,
 expl:"Among 7 people, either some pair are friends (giving 2 mutual friends) or all 7 are mutual strangers. So R(2, 7) = 7."},
{lvl:2,sec:"K",type:"mc",q:"What is R(3, 4), the smallest group guaranteeing 3 mutual friends or 4 mutual strangers?",opts:["9","7","12","8"],a:0,
 expl:"R(3, 4) = 9. It is known that 8 people can avoid both patterns, but 9 cannot."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY statement that is true.",opts:["R(3, 3) = 6","R(4, 4) = 18","R(5, 5) is known exactly","R(a, b) = R(b, a)"],aMulti:[0,1,3],
 expl:"R(3, 3) = 6 and R(4, 4) = 18 are known. Swapping the colours shows R(a, b) = R(b, a). R(5, 5) is still unknown — only that it lies between 43 and 46."},
{lvl:2,sec:"K",type:"mc",q:"In a 2-coloured K6, vertex P has red edges to A, B and C. If none of AB, BC, CA is red, what must exist?",
 opts:["A blue triangle ABC","A red triangle ABC","No triangle at all","A red and a blue triangle"],a:0,
 expl:"Each of AB, BC and CA is blue, so ABC is a blue triangle. (If any were red, it would form a red triangle with P.) This is the key step in proving R(3, 3) = 6."},
{lvl:3,sec:"K",type:"in",q:"Every 2-colouring of the 15 edges of K6 contains one-colour triangles. What is the smallest number of one-colour triangles that every such colouring must contain?",ans:2,
 hint:"One triangle is guaranteed by R(3, 3) = 6; can a clever colouring stop at one?",
 expl:"Counting 'mixed' angles at each vertex shows at most 18 non-monochromatic triangles out of 20, so at least 2 are one-colour. Some colourings achieve exactly 2."},
{lvl:3,sec:"K",type:"in",q:"A standard bound is R(k, k) ≤ C(2k − 2, k − 1). For k = 4 this gives R(4, 4) ≤ C(6, 3). What is C(6, 3)?",ans:20,
 expl:"C(6, 3) = 6 × 5 × 4/(3 × 2 × 1) = 20. The true value R(4, 4) = 18 is a little smaller than this bound."},
{lvl:3,sec:"K",type:"in",q:"With three relationship types (friend, stranger, rival), R(3, 3, 3) = 17. What is the smallest group size that guarantees 3 people who are all pairwise the same type?",ans:17,
 hint:"The Ramsey number itself is the answer to 'smallest group size that guarantees it'.",
 expl:"By definition R(3, 3, 3) = 17 means 17 people always contain a one-type triangle, while 16 people can avoid it. So the answer is 17."}
],

"g8-designs": [
{sec:"K",type:"in",q:"A 3 × 3 magic square uses each of 1 to 9 once. What is its magic constant (the sum of each row)?",ans:15,
 hint:"Divide the total of 1 to 9 among the three rows.",expl:"1 + 2 + … + 9 = 45, spread over 3 rows, so each row sums to 45/3 = 15."},
{sec:"K",type:"mc",q:"A Latin square of order 3 has each symbol exactly once in every row and column. Which grid (rows separated by /) is a Latin square?",mono:true,
 opts:["ABC / BCA / CAB","ABC / ABC / ABC","ABC / CBA / ACB","AAB / BBC / CCA"],a:0,
 expl:"ABC / BCA / CAB has A, B, C once in each row and each column. The second repeats columns, the third has A twice in column 1, and the fourth repeats letters in rows."},
{sec:"K",type:"in",q:"A 4 × 4 magic square uses each of 1 to 16 once. What is its magic constant?",ans:34,
 expl:"1 + 2 + … + 16 = 136, spread over 4 rows, so each row sums to 136/4 = 34."},
{lvl:2,sec:"K",type:"in",q:"In every 3 × 3 magic square using 1 to 9, what number is in the centre?",ans:5,
 hint:"Add the two diagonals and the middle row and column: the centre is counted four times.",
 expl:"Those four lines sum to 4 × 15 = 60 and cover all nine numbers (45) plus the centre three extra times, so 3 × centre = 15 and the centre is 5."},
{lvl:2,sec:"K",type:"in",q:"An n × n magic square using 1 to n² has magic constant n(n² + 1)/2. What is the magic constant for n = 5?",ans:65,
 expl:"5 × (25 + 1)/2 = 5 × 13 = 65."},
{lvl:2,sec:"K",type:"in",q:"How many different 3 × 3 Latin squares can be made with the symbols A, B, C?",ans:12,
 hint:"Fix the first row as ABC and count, then multiply by the number of ways to reorder the symbols.",
 expl:"With first row ABC the second row must be BCA or CAB, and each forces the third row: 2 squares. Any of the 3! = 6 orderings of the symbols can appear in row 1, giving 6 × 2 = 12."},
{lvl:2,sec:"K",type:"mc",q:"In a 3 × 3 magic square using 1 to 9, which number can never sit in a corner?",opts:["1","2","4","8"],a:0,
 expl:"The corners of the standard square are 2, 4, 6 and 8. The number 1 must pair with 5 and 9 in a line, and 9 needs two more lines through it, which only a middle-edge position for 1 allows."},
{lvl:2,sec:"K",type:"multi",q:"Select EVERY statement that is true about the 3 × 3 magic square using 1 to 9.",
 opts:["Every row sums to 15","The centre is 5","Every corner is odd","The four corners sum to 20"],aMulti:[0,1,3],
 expl:"Rows sum to 45/3 = 15 and the centre is 5. The corners are the even numbers 2, 4, 6 and 8, which add to 20."},
{lvl:3,sec:"K",type:"in",q:"In a 3 × 3 magic square using 1 to 9, the top-left entry is 8 and the centre is 5. What is the bottom-right entry?",ans:2,
 hint:"The main diagonal is one of the lines that must sum to 15.",expl:"The diagonal 8 + 5 + x = 15 gives x = 2."},
{lvl:3,sec:"K",type:"in",q:"Every entry of a 3 × 3 magic square (constant 15) is doubled and then 1 is added. What is the new magic constant?",ans:33,
 hint:"Apply the change to each of the three numbers in a row.",expl:"A row a + b + c = 15 becomes (2a + 1) + (2b + 1) + (2c + 1) = 2 × 15 + 3 = 33."},
{lvl:3,sec:"K",type:"in",q:"How many 3 × 3 magic squares using 1 to 9 are there, if rotations and reflections are counted as different?",ans:8,
 hint:"There is essentially one square; count its symmetric images.",
 expl:"There is exactly one square up to symmetry, and a square has 8 symmetries (4 rotations, each with or without a reflection), giving 8 magic squares."},
{lvl:3,sec:"K",type:"mc",q:"Euler's '36 officers' puzzle asks for a 6 × 6 grid of officers from 6 ranks and 6 regiments, with every rank and every regiment once in each row and column. What is known?",
 opts:["It is impossible — no such square exists","It can be done in exactly one way","It can be done in 36 ways","It works only if ranks are ignored"],a:0,
 expl:"A solution would be a pair of orthogonal Latin squares of order 6. Tarry proved in 1901 that none exists, confirming Euler's guess; orders 3, 4, 5 and 7 all work."}
],

"g8-pgf": [
{sec:"S",type:"mc",q:"X is the number of heads in one toss of a fair coin. Which is its probability generating function G(t) = Σ P(X = k) tᵏ?",mono:true,
 opts:["0.5 + 0.5t","0.5t","1 + t","t/2 + t²/2"],a:0,
 expl:"P(X = 0) = 0.5 and P(X = 1) = 0.5, so G(t) = 0.5t⁰ + 0.5t¹ = 0.5 + 0.5t."},
{sec:"S",type:"in",q:"For any probability generating function G(t), what is the value of G(1)?",ans:1,hint:"Substituting t = 1 adds up all the probabilities.",
 expl:"G(1) = Σ P(X = k) × 1ᵏ = Σ P(X = k) = 1."},
{sec:"S",type:"in",q:"A random variable has G(t) = 0.2 + 0.5t + 0.3t². What is P(X = 1)?",ans:0.5,expl:"P(X = k) is the coefficient of tᵏ, so P(X = 1) = 0.5."},
{lvl:2,sec:"S",type:"in",q:"If G(t) = 0.2 + 0.5t + 0.3t², find the mean E[X] = G′(1).",ans:1.1,hint:"Differentiate term by term, then substitute t = 1.",
 expl:"G′(t) = 0.5 + 0.6t, so G′(1) = 1.1. Check directly: 0 × 0.2 + 1 × 0.5 + 2 × 0.3 = 1.1."},
{lvl:2,sec:"S",type:"in",q:"Two fair coins are tossed. Expand (0.5 + 0.5t)² to find the probability of exactly 2 heads.",ans:0.25,
 expl:"(0.5 + 0.5t)² = 0.25 + 0.5t + 0.25t². The coefficient of t² is 0.25."},
{lvl:2,sec:"S",type:"mc",q:"X and Y are independent with PGFs G_X and G_Y. What is the PGF of X + Y?",mono:true,opts:["G_X(t) × G_Y(t)","G_X(t) + G_Y(t)","G_X(G_Y(t))","G_X(t) − G_Y(t)"],a:0,
 expl:"For independent variables, E[t^(X+Y)] = E[t^X] E[t^Y], so PGFs multiply — just as the coin example (0.5 + 0.5t)² shows."},
{lvl:2,sec:"S",type:"multi",q:"Select EVERY expression that is a valid probability generating function.",mono:true,opts:["0.3 + 0.7t","0.5 + 0.5t + 0.5t²","t³","1.2 − 0.2t"],aMulti:[0,2],
 expl:"Coefficients must be non-negative and add to 1. 0.3 + 0.7t works; t³ is a variable that always equals 3. The second adds to 1.5 and the last has a negative coefficient."},
{lvl:3,sec:"S",type:"in",q:"Four fair coins are tossed, so the PGF is (0.5 + 0.5t)⁴. What is the probability of exactly 2 heads?",ans:0.375,
 hint:"The coefficient of t² is C(4, 2) × 0.5⁴.",expl:"C(4, 2) = 6, so the coefficient of t² is 6/16 = 0.375."},
{lvl:3,sec:"S",type:"in",q:"For G(t) = 0.25 + 0.5t + 0.25t², use Var(X) = G″(1) + G′(1) − G′(1)² to find the variance.",ans:0.5,
 hint:"Find G′ and G″, then evaluate both at t = 1.",
 expl:"G′(t) = 0.5 + 0.5t gives G′(1) = 1; G″(t) = 0.5. Var(X) = 0.5 + 1 − 1 = 0.5."},
{lvl:3,sec:"S",type:"in",q:"The number of fair-coin tosses needed to get the first head has PGF G(t) = t/(2 − t). Find the mean, G′(1).",ans:2,
 hint:"Use the quotient rule on t/(2 − t).",
 expl:"G′(t) = [(2 − t) + t]/(2 − t)² = 2/(2 − t)², so G′(1) = 2/1 = 2. On average it takes 2 tosses."}
],

"g8-randwalk": [
{sec:"S",type:"in",q:"A walker starts at 0 and each second moves +1 or −1 with equal probability. What is the probability of being back at 0 after 2 steps? Give a decimal.",ans:0.5,
 expl:"The walker returns only with one step each way: (+1, −1) or (−1, +1). That is 2 of the 4 equally likely paths, so 0.5."},
{sec:"S",type:"mc",q:"After 3 steps of ±1 starting from 0, which positions are possible?",mono:true,opts:["−3, −1, 1, 3","−2, 0, 2","−3 to 3, all integers","0 only"],a:0,
 expl:"Three odd steps give an odd total: with u ups and 3 − u downs the position is 2u − 3, i.e. −3, −1, 1 or 3."},
{sec:"S",type:"in",q:"What is the probability that a ±1 random walk is at 0 after 4 steps? Give a decimal.",ans:0.375,hint:"Count paths with exactly 2 ups among 4 steps.",
 expl:"C(4, 2) = 6 of the 16 paths have two ups and two downs, so 6/16 = 0.375."},
{lvl:2,sec:"S",type:"in",q:"Gambler's ruin: in a fair game a player with $3 bets $1 at a time and stops at $10 or $0. What is the probability of reaching $10? Give a decimal.",ans:0.3,
 hint:"In a fair game the probability of reaching the target is start ÷ target.",expl:"P(reach 10 from 3) = 3/10 = 0.3."},
{lvl:2,sec:"S",type:"in",q:"In a fair game a player starts with $2 and stops at $8 or $0. What is the probability of going broke? Give a decimal.",ans:0.75,
 expl:"The chance of reaching 8 is 2/8 = 0.25, so the chance of ruin is 1 − 0.25 = 0.75."},
{lvl:2,sec:"S",type:"in",q:"For a symmetric ±1 random walk, the expected value of (position)² after n steps is n. What is the expected squared position after 25 steps?",ans:25,
 expl:"Each step contributes 1 to the expected square (the cross terms average to 0), so E[X²] = 25 after 25 steps."},
{lvl:2,sec:"S",type:"mc",q:"A gambler plays a fair game against an opponent with unlimited money and never stops. What is the probability of eventual ruin?",opts:["1","0","0.5","It depends on the starting stake"],a:0,
 expl:"With target N the ruin probability is 1 − i/N, which tends to 1 as N grows without bound. Ruin is certain in the long run."},
{lvl:3,sec:"S",type:"in",q:"How many 6-step paths of ±1 steps starting at 0 end at +2?",ans:15,hint:"Ending at +2 needs 4 ups and 2 downs; choose where the ups go.",
 expl:"u − (6 − u) = 2 gives u = 4, so choose 4 of the 6 steps to be ups: C(6, 4) = 15 paths."},
{lvl:3,sec:"S",type:"in",q:"How many 4-step paths of ±1 steps start at 0, end at 0, and never go below 0?",ans:2,hint:"Write out the sequences of U and D with two of each.",
 expl:"The sequences with two U and two D that never dip below 0 are UUDD and UDUD (UDDU, DUUD, DUDU, DDUU all go negative). That is 2 paths, the Catalan number C₂."},
{lvl:3,sec:"S",type:"in",q:"Ravi starts with $4 and Mei with $6. They bet $1 a round on a fair coin until one of them has everything. In a fair game with total N the expected number of rounds from a stake i is i(N − i). What is the expected number of rounds?",ans:24,
 expl:"N = 10 and i = 4, so the expected duration is 4 × 6 = 24 rounds."},
{lvl:3,sec:"S",type:"multi",q:"Select EVERY true statement about the symmetric ±1 random walk on the integers.",
 opts:["It returns to 0 eventually with probability 1","After an odd number of steps the position is odd","The expected position is always 0","It never moves more than 10 from the start"],aMulti:[0,1,2],
 expl:"In one dimension the symmetric walk is recurrent, so a return is certain. Parity of the position matches parity of the step count. Each step has mean 0, so the expected position is 0. Nothing bounds the walk."}
],

"g8-continuous": [
{sec:"S",type:"in",q:"X is uniformly distributed on [0, 10]. What is P(X < 3)? Give a decimal.",ans:0.3,expl:"For a uniform distribution, probability is length ÷ total length: 3/10 = 0.3."},
{sec:"S",type:"mc",q:"X has a continuous distribution. What is P(X = 2.5) exactly?",opts:["0","0.5","1","It depends on the density"],a:0,
 expl:"For a continuous variable, probability is area under the density curve. A single point has zero width, so its probability is 0."},
{sec:"S",type:"in",q:"X is uniformly distributed on [2, 8]. What is its mean?",ans:5,expl:"The mean of a uniform distribution is the midpoint: (2 + 8)/2 = 5."},
{lvl:2,sec:"S",type:"in",q:"X has density f(x) = 2x on [0, 1]. What is P(X < 0.5)? Give a decimal.",ans:0.25,hint:"The area under the line from 0 to 0.5 is a triangle.",
 expl:"The region is a triangle with base 0.5 and height f(0.5) = 1: area = ½ × 0.5 × 1 = 0.25."},
{lvl:2,sec:"S",type:"in",q:"X is uniform on [0, 4]. What is P(1 < X < 3.5)? Give a decimal.",ans:0.625,expl:"The interval has length 2.5 out of 4, so the probability is 2.5/4 = 0.625."},
{lvl:2,sec:"S",type:"mc",q:"A density is f(x) = c for 0 ≤ x ≤ 5 and 0 elsewhere. What must c be?",opts:["0.2","5","1","0.5"],a:0,
 expl:"The total area must be 1: c × 5 = 1, so c = 0.2."},
{lvl:2,sec:"S",type:"in",q:"The variance of a uniform distribution on [a, b] is (b − a)²/12. What is the variance for the uniform distribution on [0, 6]?",ans:3,
 expl:"(6 − 0)²/12 = 36/12 = 3."},
{lvl:3,sec:"S",type:"in",q:"Amara and Kenji each arrive at a café at a random time, independently and uniformly, within the same hour. What is the probability they arrive within 30 minutes of each other? Give a decimal.",ans:0.75,
 hint:"Draw the unit square of arrival times and shade where |x − y| ≤ 0.5.",
 expl:"In the unit square the region |x − y| > 0.5 is two corner triangles of area ½ × 0.5 × 0.5 each, total 0.25. So the probability is 1 − 0.25 = 0.75."},
{lvl:3,sec:"S",type:"in",q:"X has density f(x) = x/8 on [0, 4]. What is P(X < 3)? Give a decimal.",ans:0.5625,hint:"The area under the line from 0 to 3 is a triangle.",
 expl:"Triangle with base 3 and height f(3) = 3/8: area = ½ × 3 × 3/8 = 9/16 = 0.5625. (Check the total: ½ × 4 × 0.5 = 1.)"},
{lvl:3,sec:"S",type:"in",q:"X is uniform on [0, 1] and Y = X². What is P(Y < 0.25)? Give a decimal.",ans:0.5,hint:"Translate the event about Y into an event about X.",
 expl:"Y < 0.25 exactly when X < 0.5 (since X ≥ 0), and P(X < 0.5) = 0.5. Note that Y is not uniform even though X is."},
{lvl:3,sec:"S",type:"multi",q:"Select EVERY function that is a valid probability density.",mono:true,
 opts:["f(x) = 0.5 on [0, 2]","f(x) = x on [0, 2]","f(x) = 2x on [0, 1]","f(x) = −1 on [0, 1]"],aMulti:[0,2],
 expl:"A density must be non-negative with total area 1. 0.5 × 2 = 1 and the triangle under 2x on [0, 1] has area 1. The area under x on [0, 2] is 2, and a density cannot be negative."}
],

"g8-clt": [
{sec:"S",type:"mc",q:"The Central Limit Theorem says that, for large samples, the distribution of the sample mean is approximately which shape?",opts:["Normal (bell-shaped)","Uniform","The same shape as the population","Strongly skewed"],a:0,
 expl:"Whatever the population looks like, averages of many independent draws follow an approximately normal, bell-shaped distribution."},
{sec:"S",type:"in",q:"A population has mean 50 and standard deviation 10. For samples of size 25, what is the standard deviation of the sample mean (the standard error)?",ans:2,
 hint:"Standard error = σ/√n.",expl:"10/√25 = 10/5 = 2."},
{sec:"S",type:"in",q:"A population has mean 50. What is the mean of the sampling distribution of the sample mean?",ans:50,
 expl:"The sample mean is an unbiased estimate: its expected value equals the population mean, 50."},
{lvl:2,sec:"S",type:"in",q:"A fair die has mean 3.5. What is the expected value of the total of 100 rolls?",ans:350,expl:"Expected values add: 100 × 3.5 = 350."},
{lvl:2,sec:"S",type:"in",q:"A population has standard deviation 12. What sample size makes the standard error of the mean equal to 1?",ans:144,
 hint:"Solve 12/√n = 1.",expl:"√n = 12, so n = 144."},
{lvl:2,sec:"S",type:"mc",q:"A sample mean has standard error 2. About what percentage of samples give a mean within 2 of the population mean?",opts:["About 68%","About 95%","About 50%","About 99.7%"],a:0,
 expl:"Within 2 is within one standard error. By the 68–95–99.7 rule for a normal distribution, that is about 68%."},
{lvl:2,sec:"S",type:"mc",q:"If the sample size is increased from 25 to 100, the standard error of the mean is divided by what?",opts:["2","4","10","It stays the same"],a:0,
 expl:"Standard error is σ/√n. Multiplying n by 4 multiplies √n by 2, so the standard error halves."},
{lvl:3,sec:"S",type:"in",q:"A fair coin is tossed 400 times. The number of heads has mean 200 and standard deviation √(400 × 0.5 × 0.5). Using the 68–95–99.7 rule, about what percentage of the time is the number of heads between 180 and 220?",ans:95,
 hint:"Work out the standard deviation first and see how many of them 20 is.",
 expl:"The standard deviation is √100 = 10, so 180 to 220 is within 2 standard deviations of the mean: about 95%."},
{lvl:3,sec:"S",type:"in",q:"Zainab measures a population with mean 100 and standard deviation 15, using samples of size 36. Using the 95% rule (two standard errors), what is the upper limit of the usual range for her sample mean?",ans:105,
 hint:"First compute σ/√n, then double it.",
 expl:"The standard error is 15/6 = 2.5, so two standard errors is 5. The upper limit is 100 + 5 = 105."},
{lvl:3,sec:"S",type:"multi",q:"Select EVERY statement that is true about the Central Limit Theorem.",
 opts:["It applies even when the population is not normal","Larger samples give a smaller standard error","The sample mean always equals the population mean","It requires the draws to be independent"],aMulti:[0,1,3],
 expl:"The theorem works for any population with finite variance, needs independent draws, and the standard error σ/√n shrinks as n grows. The sample mean varies around the population mean; it does not equal it exactly."}
],

"g8-entropy": [
{sec:"S",type:"in",q:"What is the entropy, in bits, of one toss of a fair coin?",ans:1,expl:"Two equally likely outcomes give log₂ 2 = 1 bit."},
{sec:"S",type:"in",q:"A fair 8-sided die is rolled. What is the entropy of the result in bits?",ans:3,hint:"For n equally likely outcomes the entropy is log₂ n.",
 expl:"log₂ 8 = 3 bits: you need 3 yes/no questions to pin down the result."},
{sec:"S",type:"mc",q:"Which of these has the highest entropy?",opts:["A fair coin","A coin with P(heads) = 0.9","A coin that always lands heads","A coin with P(heads) = 0.99"],a:0,
 expl:"Entropy measures uncertainty and is largest when outcomes are equally likely. A fair coin has 1 bit; the biased coins have less and the certain coin has 0."},
{lvl:2,sec:"S",type:"in",q:"Outcomes have probabilities 1/2, 1/4 and 1/4. Compute the entropy Σ p log₂(1/p) in bits.",ans:1.5,
 hint:"log₂(1/p) is 1 for p = 1/2 and 2 for p = 1/4.",expl:"(1/2)(1) + (1/4)(2) + (1/4)(2) = 0.5 + 0.5 + 0.5 = 1.5 bits."},
{lvl:2,sec:"S",type:"in",q:"An event is certain to happen. What is the entropy of this outcome in bits?",ans:0,
 expl:"With p = 1, p log₂(1/p) = 1 × log₂ 1 = 0. No uncertainty means no information is gained."},
{lvl:2,sec:"S",type:"in",q:"Outcomes have probabilities 1/2, 1/4, 1/8 and 1/8. What is the entropy in bits?",ans:1.75,
 hint:"log₂(1/p) equals 1, 2, 3 and 3 for these probabilities.",
 expl:"(1/2)(1) + (1/4)(2) + (1/8)(3) + (1/8)(3) = 0.5 + 0.5 + 0.375 + 0.375 = 1.75 bits."},
{lvl:2,sec:"S",type:"mc",q:"A random outcome has entropy 2 bits. What does this mean?",
 opts:["About 2 yes/no questions are needed on average","There are exactly 2 possible outcomes","Each outcome has probability 1/2","Two coins were tossed"],a:0,
 expl:"Entropy in bits is the average number of well-chosen yes/no questions needed to identify the outcome. Four equally likely outcomes, for example, give 2 bits."},
{lvl:3,sec:"S",type:"in",q:"Tomas thinks of a whole number from 1 to 64. How many yes/no questions are guaranteed to be enough to find it?",ans:6,
 hint:"Each question can at best halve the number of possibilities.",expl:"Halving 64 six times reaches 1: 64 → 32 → 16 → 8 → 4 → 2 → 1. So log₂ 64 = 6 questions."},
{lvl:3,sec:"S",type:"in",q:"A balance scale has three possible outcomes per weighing (left heavier, right heavier, balanced). One of 12 coins is heavier than the rest. What is the minimum number of weighings that guarantees finding it?",ans:3,
 hint:"k weighings can distinguish at most 3ᵏ cases.",
 expl:"Two weighings distinguish at most 3² = 9 cases, fewer than 12. Three weighings allow 27 ≥ 12, and a scheme with 3 weighings exists (split 4-4-4, then 2-1-1). So 3."},
{lvl:3,sec:"S",type:"in",q:"A spinner with 4 equally likely results is spun and, independently, a fair coin is tossed. What is the entropy of the combined result in bits?",ans:3,
 hint:"Entropy of independent events adds.",expl:"The spinner gives log₂ 4 = 2 bits and the coin 1 bit. Independent, so 2 + 1 = 3 bits (equivalently log₂ 8 = 3)."},
{lvl:3,sec:"S",type:"multi",q:"Select EVERY statement that is true about entropy.",
 opts:["Among n outcomes, the uniform distribution has the most entropy","Entropy can be negative","Entropy of independent events adds","A certain event has entropy 0"],aMulti:[0,2,3],
 expl:"Entropy is maximised by equal probabilities, adds over independent events, and is 0 for a certain event. Each term p log₂(1/p) is non-negative, so entropy is never negative."}
]
};
