/* Grade 8 core: the number system (irrationals, exponents, scientific
   notation), expressions & equations, functions, geometry (transformations,
   similarity, Pythagoras, solids) and bivariate statistics. */
export const G8_CORE_BANKS = {
"g8-irrational": [
{sec:"N",type:"mc",q:"Which of these numbers is irrational?",mono:true,opts:["√2","0.75","1/3","√9"],a:0,
 expl:"√2 cannot be written as a fraction of whole numbers and its decimal never ends or repeats. 0.75 = 3/4, 1/3 is already a fraction and √9 = 3."},
{sec:"N",type:"in",q:"√20 lies between two consecutive whole numbers. Type the smaller one.",ans:4,
 hint:"Which square numbers sit either side of 20?",
 expl:"4² = 16 and 5² = 25, and 16 < 20 < 25, so √20 is between 4 and 5. The smaller is 4."},
{sec:"N",type:"mc",q:"Which decimal represents a rational number?",mono:true,opts:["0.333…","π","√5","0.1010010001…"],a:0,
 expl:"A repeating decimal such as 0.333… equals a fraction (1/3), so it is rational. π and √5 never repeat, and 0.1010010001… has a pattern that never repeats a fixed block."},
{sec:"N",type:"mc",q:"Which fraction equals the repeating decimal 0.666…?",mono:true,opts:["2/3","3/5","6/10","5/8"],a:0,
 expl:"Let x = 0.666…; then 10x = 6.666…, so 9x = 6 and x = 6/9 = 2/3."},
{lvl:2,sec:"N",type:"in",q:"√50 lies between two consecutive whole numbers. Type the larger one.",ans:8,
 hint:"Compare 50 with 49 and 64.",expl:"7² = 49 and 8² = 64, so √50 is between 7 and 8. The larger is 8."},
{lvl:2,sec:"N",type:"order",q:"Put these numbers in order from smallest to largest.",
 items:["√10","3","π","3.5"],ansOrder:["3","π","√10","3.5"],
 expl:"π ≈ 3.14 and √10 ≈ 3.16 (since 3.16² ≈ 9.99). So the order is 3, π, √10, 3.5."},
{lvl:2,sec:"N",type:"mc",q:"Which decimal is the best approximation of √3?",mono:true,opts:["1.732","1.5","1.414","2.236"],a:0,
 expl:"1.732² ≈ 3.0002, so √3 ≈ 1.732. (1.414 is √2 and 2.236 is √5.)"},
{lvl:3,sec:"N",type:"in",q:"Estimate √40 to one decimal place.",ans:6.3,
 hint:"Square 6.3 and 6.4 and see which is closer to 40.",
 expl:"6.3² = 39.69 and 6.4² = 40.96. 40 is closer to 39.69, so √40 ≈ 6.3."},
{lvl:3,sec:"N",type:"multi",q:"Select EVERY number that is irrational.",mono:true,opts:["√8","√16","π/2","0.121212…"],aMulti:[0,2],
 expl:"√8 = 2√2 and π/2 are irrational. √16 = 4 and 0.121212… = 12/99 = 4/33 are rational."},
{lvl:3,sec:"N",type:"in",q:"Write 0.363636… as a fraction in lowest terms. What is the numerator plus the denominator?",ans:15,
 hint:"Multiply by 100 and subtract to remove the repeating part.",
 expl:"100x − x = 36, so x = 36/99 = 4/11. Then 4 + 11 = 15."}
],

"g8-radicals": [
{sec:"N",type:"in",q:"Write 2⁻³ as a decimal.",ans:0.125,hint:"A negative exponent means a reciprocal.",
 expl:"2⁻³ = 1/2³ = 1/8 = 0.125."},
{sec:"N",type:"in",q:"3⁴ × 3² can be written as a single power of 3. What is the exponent?",ans:6,
 hint:"Same base: add the exponents.",expl:"3⁴ × 3² = 3⁴⁺² = 3⁶, so the exponent is 6."},
{sec:"N",type:"mc",q:"What is the value of 5⁰?",mono:true,opts:["1","0","5","1/5"],a:0,
 expl:"Any non-zero number raised to the power 0 equals 1, because 5³ ÷ 5³ = 5⁰ and also equals 1."},
{sec:"N",type:"in",q:"What is √144?",ans:12,expl:"12 × 12 = 144, so √144 = 12."},
{sec:"N",type:"in",q:"What is the cube root of 64?",ans:4,hint:"Which number multiplied by itself three times gives 64?",
 expl:"4 × 4 × 4 = 64, so the cube root of 64 is 4."},
{lvl:2,sec:"N",type:"mc",q:"Which expression is equal to (2³)²?",mono:true,opts:["2⁶","2⁵","2⁹","2⁸"],a:0,
 expl:"A power of a power multiplies the exponents: (2³)² = 2³ˣ² = 2⁶ = 64."},
{lvl:2,sec:"N",type:"in",q:"Solve x² = 81, where x is positive.",ans:9,expl:"The positive square root of 81 is 9, since 9² = 81."},
{lvl:2,sec:"N",type:"in",q:"Evaluate 10⁷ ÷ 10⁴.",ans:1000,hint:"Same base: subtract the exponents.",
 expl:"10⁷ ÷ 10⁴ = 10⁷⁻⁴ = 10³ = 1000."},
{lvl:2,sec:"N",type:"mc",q:"Which is equal to 4⁻²?",mono:true,opts:["1/16","−16","−8","1/8"],a:0,
 expl:"4⁻² = 1/4² = 1/16. A negative exponent does not make the number negative."},
{lvl:3,sec:"N",type:"in",q:"If 2ˣ × 2⁵ = 2¹², what is x?",ans:7,hint:"Adding exponents on the left must give 12.",
 expl:"2ˣ × 2⁵ = 2ˣ⁺⁵, so x + 5 = 12 and x = 7."},
{lvl:3,sec:"N",type:"in",q:"Solve (x + 1)² = 49, where x is positive.",ans:6,hint:"First find the positive square root of 49.",
 expl:"x + 1 = 7 (taking the positive root), so x = 6."},
{lvl:3,sec:"N",type:"in",q:"Simplify (2⁵ × 2⁻²) ÷ 2⁻¹ and give its value.",ans:16,
 hint:"Combine all the exponents first.",expl:"2⁵ × 2⁻² = 2³, and 2³ ÷ 2⁻¹ = 2³⁻⁽⁻¹⁾ = 2⁴ = 16."}
],

"g8-scinot": [
{sec:"N",type:"mc",q:"Write 45,000 in scientific notation.",mono:true,opts:["4.5 × 10⁴","45 × 10³","4.5 × 10³","0.45 × 10⁵"],a:0,
 expl:"The first factor must be at least 1 and less than 10: 45,000 = 4.5 × 10,000 = 4.5 × 10⁴."},
{sec:"N",type:"in",q:"What is 3.2 × 10³ written as an ordinary number?",ans:3200,expl:"3.2 × 1000 = 3200."},
{sec:"N",type:"in",q:"What is 7 × 10⁻² written as a decimal?",ans:0.07,hint:"10⁻² = 1/100.",
 expl:"7 × 10⁻² = 7 ÷ 100 = 0.07."},
{sec:"N",type:"mc",q:"Which number is correctly written in scientific notation?",mono:true,
 opts:["6.02 × 10²³","60.2 × 10²²","0.602 × 10²⁴","602 × 10²¹"],a:0,
 expl:"Only 6.02 × 10²³ has a first factor between 1 and 10. The others equal the same value but are not in the standard form."},
{lvl:2,sec:"N",type:"in",q:"0.00058 is written as 5.8 × 10ⁿ. What is n?",ans:-4,hint:"Count how many places the decimal point moves.",
 expl:"The decimal point moves 4 places to the right to get 5.8, so 0.00058 = 5.8 × 10⁻⁴ and n = −4."},
{lvl:2,sec:"N",type:"in",q:"(3 × 10⁴) × (2 × 10³) = 6 × 10ⁿ. What is n?",ans:7,
 expl:"Multiply the front numbers (3 × 2 = 6) and add the exponents (4 + 3 = 7), so n = 7."},
{lvl:2,sec:"N",type:"order",q:"Put these numbers in order from smallest to largest.",
 items:["2.5 × 10³","9 × 10²","1.1 × 10⁴","3 × 10³"],ansOrder:["9 × 10²","2.5 × 10³","3 × 10³","1.1 × 10⁴"],
 expl:"As ordinary numbers they are 2500, 900, 11,000 and 3000. Smallest to largest: 900, 2500, 3000, 11,000."},
{lvl:2,sec:"N",type:"mc",q:"What is (8 × 10⁶) ÷ (4 × 10²)?",mono:true,opts:["2 × 10⁴","2 × 10³","4 × 10⁴","2 × 10⁸"],a:0,
 expl:"Divide the front numbers (8 ÷ 4 = 2) and subtract the exponents (6 − 2 = 4): 2 × 10⁴."},
{lvl:3,sec:"N",type:"in",q:"The Moon is about 3.8 × 10⁵ km away. A probe travels 2 × 10³ km every hour. How many hours does the trip take?",ans:190,
 hint:"Divide the distance by the speed.",
 expl:"(3.8 × 10⁵) ÷ (2 × 10³) = 1.9 × 10² = 190 hours."},
{lvl:3,sec:"N",type:"in",q:"4 × 10⁵ + 3 × 10⁴ = a × 10⁵. What is a?",ans:4.3,
 hint:"Rewrite 3 × 10⁴ with an exponent of 5 first.",
 expl:"3 × 10⁴ = 0.3 × 10⁵, so the sum is 4.3 × 10⁵ and a = 4.3."},
{lvl:3,sec:"N",type:"in",q:"How many times larger is 6 × 10⁸ than 3 × 10⁵?",ans:2000,
 expl:"(6 × 10⁸) ÷ (3 × 10⁵) = 2 × 10³ = 2000 times larger."}
],

"g8-propgraph": [
{sec:"L",type:"in",q:"A line passes through (0, 0) and (4, 12). What is its slope?",ans:3,
 hint:"Slope = rise ÷ run.",expl:"Rise 12 over run 4 gives slope 12 ÷ 4 = 3."},
{sec:"L",type:"mc",q:"Which graph shows a proportional relationship?",
 opts:["A straight line through the origin","A straight line crossing the y-axis at 5","A curve through the origin","A horizontal line at y = 3"],a:0,
 expl:"A proportional relationship y = kx is a straight line, and it must pass through (0, 0)."},
{sec:"L",type:"in",q:"The graph of y = 2.5x is a line through the origin. What is its slope?",ans:2.5,
 expl:"In y = kx the constant k is the slope (and the unit rate), so the slope is 2.5."},
{sec:"L",type:"in",q:"What is the slope of the line through (2, 5) and (6, 13)?",ans:2,
 hint:"Change in y divided by change in x.",expl:"(13 − 5) ÷ (6 − 2) = 8 ÷ 4 = 2."},
{lvl:2,sec:"L",type:"in",q:"What is the slope of the line through (−2, 4) and (2, −4)?",ans:-2,
 hint:"Be careful with the signs.",expl:"(−4 − 4) ÷ (2 − (−2)) = −8 ÷ 4 = −2."},
{lvl:2,sec:"L",type:"mc",q:"Line A is y = 4x. Line B passes through (1, 5) and (2, 10). Which line is steeper?",
 opts:["Line B","Line A","They are equally steep","Neither line has a slope"],a:0,
 expl:"Line B has slope (10 − 5) ÷ (2 − 1) = 5, which is greater than 4, so Line B is steeper."},
{lvl:2,sec:"L",type:"in",q:"A line passes through (0, 0) and (6, 9). Give its slope as a decimal.",ans:1.5,
 expl:"9 ÷ 6 = 1.5."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY equation whose graph is a proportional relationship.",mono:true,
 opts:["y = 3x","y = x/2","y = 2x + 1","y = x²"],aMulti:[0,1],
 expl:"y = 3x and y = x/2 are of the form y = kx. y = 2x + 1 does not pass through the origin and y = x² is not a straight line."},
{lvl:3,sec:"L",type:"in",q:"A line through the origin passes through (8, 6). What is y when x = 20?",ans:15,
 hint:"Find the unit rate first.",expl:"The slope is 6 ÷ 8 = 0.75, so y = 0.75 × 20 = 15."},
{lvl:3,sec:"L",type:"in",q:"On the line y = 1.5x, the rise between x = 0 and x = 2 is 3. What is the rise between x = 4 and x = 10?",ans:9,
 hint:"The slope is the same between any two points on the line.",
 expl:"The run is 10 − 4 = 6 and the slope is 1.5, so the rise is 1.5 × 6 = 9."},
{lvl:3,sec:"L",type:"in",q:"Two similar right triangles are drawn under the same straight line. The small one has rise 4 and run 6; the large one has run 15. What is its rise?",ans:10,
 hint:"Matching sides of similar triangles are in the same ratio.",
 expl:"The slope is 4/6 = 2/3 for both triangles, so the rise is (2/3) × 15 = 10."}
],

"g8-linear": [
{sec:"L",type:"in",q:"Solve 3x + 5 = 20.",ans:5,hint:"Undo the + 5 first.",expl:"3x = 15, so x = 5."},
{sec:"L",type:"in",q:"Solve 4x − 7 = 2x + 9.",ans:8,hint:"Collect the x terms on one side.",
 expl:"Subtract 2x: 2x − 7 = 9. Add 7: 2x = 16, so x = 8."},
{sec:"L",type:"mc",q:"Which is a correct first step for solving 2(x + 3) = 14?",mono:true,
 opts:["2x + 6 = 14","2x + 3 = 14","x + 3 = 28","2x + 6 = 28"],a:0,
 expl:"Expanding the bracket multiplies both terms by 2: 2(x + 3) = 2x + 6. (Dividing both sides by 2 to get x + 3 = 7 also works.)"},
{sec:"L",type:"in",q:"Solve x/3 + 2 = 6.",ans:12,expl:"x/3 = 4, so x = 4 × 3 = 12."},
{lvl:2,sec:"L",type:"in",q:"Solve 5(x − 2) = 3x + 4.",ans:7,hint:"Expand the bracket, then collect terms.",
 expl:"5x − 10 = 3x + 4, so 2x = 14 and x = 7."},
{lvl:2,sec:"L",type:"mc",q:"How many solutions does 3x + 2 = 3x + 5 have?",
 opts:["None","Exactly one","Infinitely many","Two"],a:0,
 expl:"Subtracting 3x from both sides leaves 2 = 5, which is never true, so there is no solution."},
{lvl:2,sec:"L",type:"mc",q:"How many solutions does 2(x + 4) = 2x + 8 have?",
 opts:["Infinitely many","None","Exactly one","Two"],a:0,
 expl:"Expanding gives 2x + 8 = 2x + 8, which is true for every value of x."},
{lvl:2,sec:"L",type:"in",q:"Solve 0.4x + 1.2 = 3.6.",ans:6,expl:"0.4x = 2.4, so x = 2.4 ÷ 0.4 = 6."},
{lvl:3,sec:"L",type:"in",q:"Solve 2(3x − 1) − 4(x + 2) = 8.",ans:9,hint:"Expand both brackets carefully, watching the signs.",
 expl:"6x − 2 − 4x − 8 = 8 gives 2x − 10 = 8, so 2x = 18 and x = 9."},
{lvl:3,sec:"L",type:"in",q:"Mateo has $50 and saves $8 each week. Nadia has $20 and saves $13 each week. After how many weeks will they have the same amount?",ans:6,
 hint:"Write an expression for each person's money after w weeks and set them equal.",
 expl:"50 + 8w = 20 + 13w gives 30 = 5w, so w = 6 weeks (both then have $98)."},
{lvl:3,sec:"L",type:"mc",q:"For which value of k does 4x + k = 2(2x + 3) have infinitely many solutions?",mono:true,
 opts:["6","3","0","12"],a:0,
 expl:"2(2x + 3) = 4x + 6. The equation is true for every x only when both sides are identical, so k = 6."}
],

"g8-systems": [
{sec:"L",type:"in",q:"Solve the system y = x + 3 and y = 2x. What is x?",ans:3,hint:"Both expressions equal y, so set them equal.",
 expl:"x + 3 = 2x, so x = 3 (and y = 6)."},
{sec:"L",type:"mc",q:"Which point is a solution to BOTH x + y = 7 and x − y = 1?",mono:true,
 opts:["(4, 3)","(3, 4)","(5, 2)","(6, 1)"],a:0,
 expl:"Check (4, 3): 4 + 3 = 7 and 4 − 3 = 1. Both equations hold. The others fail the second equation."},
{sec:"L",type:"in",q:"Solve x + y = 10 and x − y = 4. What is x?",ans:7,hint:"Add the two equations together.",
 expl:"Adding gives 2x = 14, so x = 7 (and y = 3)."},
{sec:"L",type:"in",q:"Solve y = 3x and x + y = 16. What is y?",ans:12,hint:"Substitute 3x in place of y.",
 expl:"x + 3x = 16, so x = 4 and y = 3 × 4 = 12."},
{lvl:2,sec:"L",type:"in",q:"Solve 2x + y = 11 and x + y = 7. What is y?",ans:3,hint:"Subtract one equation from the other.",
 expl:"Subtracting gives x = 4, then 4 + y = 7, so y = 3."},
{lvl:2,sec:"L",type:"mc",q:"How many solutions do y = 2x + 1 and y = 2x − 3 have?",
 opts:["None","One","Infinitely many","Two"],a:0,
 expl:"The lines have the same slope but different y-intercepts, so they are parallel and never meet."},
{lvl:2,sec:"L",type:"in",q:"Solve 3x + 2y = 16 and x − 2y = 0. What is x + y?",ans:6,
 hint:"Adding the equations removes y.",expl:"Adding gives 4x = 16, so x = 4 and then 2y = 4, so y = 2. x + y = 6."},
{lvl:2,sec:"L",type:"mc",q:"Which system has infinitely many solutions?",mono:true,
 opts:["y = x + 2 and 2y = 2x + 4","y = x + 2 and y = x + 3","y = x + 2 and y = 2x + 2","y = x and y = −x"],a:0,
 expl:"2y = 2x + 4 is just y = x + 2 doubled, so the two equations describe the same line and share every point."},
{lvl:3,sec:"L",type:"in",q:"Three adult tickets and two child tickets cost $31. One adult ticket and two child tickets cost $17. What is the cost of one adult ticket in dollars?",ans:7,
 hint:"Subtract the second purchase from the first.",
 expl:"Subtracting gives 2 adult tickets = $14, so an adult ticket is $7 (and a child ticket is $5)."},
{lvl:3,sec:"L",type:"in",q:"The sum of two numbers is 25 and their difference is 7. What is their product?",ans:144,
 hint:"Find both numbers first.",expl:"Adding x + y = 25 and x − y = 7 gives 2x = 32, so x = 16 and y = 9. The product is 16 × 9 = 144."},
{lvl:3,sec:"L",type:"in",q:"Aisha buys 4 pens and 3 notebooks for $18. Yusuf buys 2 pens and 5 notebooks for $23. What is the price of one notebook in dollars?",ans:4,
 hint:"Double the second purchase so the pens match.",
 expl:"Doubling gives 4p + 10n = 46. Subtract 4p + 3n = 18: 7n = 28, so a notebook costs $4 (and a pen $1.50)."}
],

"g8-funcdef": [
{sec:"L",type:"mc",q:"Which set of (input, output) pairs is a function?",mono:true,
 opts:["(1,2), (2,4), (3,6)","(1,2), (1,3), (2,4)","(2,5), (2,6), (3,7)","(0,1), (0,2), (0,3)"],a:0,
 expl:"In a function each input has exactly one output. Only the first set never repeats an input with a different output."},
{sec:"L",type:"mc",q:"What must be true for a relation to be a function?",
 opts:["Each input has exactly one output","Each output has exactly one input","Inputs and outputs are all different","The graph is a straight line"],a:0,
 expl:"A function assigns exactly one output to every input. Outputs may repeat and the graph need not be a line."},
{sec:"L",type:"in",q:"If f(x) = 3x − 4, what is f(5)?",ans:11,expl:"f(5) = 3 × 5 − 4 = 15 − 4 = 11."},
{sec:"L",type:"mc",q:"A table gives y = 5 for every input x = 2, 4, 6, 8. Is this a function?",
 opts:["Yes, every input has one output","No, the outputs repeat","No, the inputs are all different","Only when x is 0"],a:0,
 expl:"Repeated outputs are fine. Each input still has exactly one output, so it is a function (a constant one)."},
{lvl:2,sec:"L",type:"in",q:"A function's rule is 'square the input, then add 1'. What is the output when the input is 4?",ans:17,
 expl:"4² + 1 = 16 + 1 = 17."},
{lvl:2,sec:"L",type:"mc",q:"Which graph does NOT represent a function?",
 opts:["A circle","A slanted straight line","A U-shaped curve opening upward","A horizontal line"],a:0,
 expl:"A vertical line crosses a circle at two points, so one input would have two outputs. That fails the vertical line test."},
{lvl:2,sec:"L",type:"multi",q:"Select EVERY table that could represent a function.",mono:true,
 opts:["x: 1, 2, 3 → y: 4, 4, 4","x: 1, 1, 2 → y: 3, 5, 7","x: 0, 5, 10 → y: 1, 2, 3","x: 2, 2, 2 → y: 1, 2, 3"],aMulti:[0,2],
 expl:"The first and third tables never give one input two different outputs. The second and fourth send the same input to different outputs."},
{lvl:3,sec:"L",type:"in",q:"f(x) = 2x + 3 and f(a) = 19. What is a?",ans:8,hint:"Solve the equation 2a + 3 = 19.",
 expl:"2a + 3 = 19 gives 2a = 16, so a = 8."},
{lvl:3,sec:"L",type:"in",q:"g(x) = x² − 2x. What is g(7) − g(3)?",ans:32,hint:"Work out each value separately first.",
 expl:"g(7) = 49 − 14 = 35 and g(3) = 9 − 6 = 3, so g(7) − g(3) = 32."},
{lvl:3,sec:"L",type:"mc",q:"A function gives outputs 3, 7, 11, 15 for inputs 1, 2, 3, 4. Which rule fits?",mono:true,
 opts:["y = 4x − 1","y = 3x","y = 2x + 1","y = 4x + 1"],a:0,
 expl:"The outputs go up by 4 each time, so the rule is 4x plus a constant. 4 × 1 − 1 = 3, so y = 4x − 1."}
],

"g8-funccomp": [
{sec:"L",type:"mc",q:"Function A is y = 3x + 2. Function B is given by a table: x = 0, 1, 2 gives y = 1, 5, 9. Which has the greater rate of change?",
 opts:["Function B","Function A","They are equal","It cannot be told"],a:0,
 expl:"Function B rises 4 for each step of 1 in x, so its rate is 4. Function A's rate is 3, so B is greater."},
{sec:"L",type:"in",q:"A table shows y = 1, 5, 9 when x = 0, 1, 2. What is the rate of change?",ans:4,
 expl:"y goes up by 4 each time x goes up by 1, so the rate of change is 4."},
{sec:"L",type:"in",q:"A function is described in words: 'start at 7 and add 5 for each step'. What is its initial value?",ans:7,
 expl:"The starting value, when no steps have been taken, is 7. The 5 is the rate of change."},
{sec:"L",type:"mc",q:"Which function has the larger y-intercept: y = 2x + 8, or the line through (0, 4) and (2, 10)?",
 opts:["y = 2x + 8","The line through (0, 4) and (2, 10)","They start at the same value","Neither has a y-intercept"],a:0,
 expl:"The line through (0, 4) has y-intercept 4, while y = 2x + 8 has y-intercept 8. So 8 is larger."},
{lvl:2,sec:"L",type:"in",q:"Function P is y = 5x − 1. Function Q passes through (1, 3) and (3, 11). How much greater is P's rate of change than Q's?",ans:1,
 hint:"Find Q's slope from the two points.",expl:"Q's rate is (11 − 3) ÷ (3 − 1) = 4. P's rate is 5, so P is greater by 1."},
{lvl:2,sec:"L",type:"mc",q:"Function M's graph rises 6 units for every 2 units across. Function N is described as 'y increases by 2 whenever x increases by 1'. Which is steeper?",
 opts:["Function M","Function N","They are equally steep","Not enough information"],a:0,
 expl:"M's slope is 6 ÷ 2 = 3 and N's slope is 2, so M is steeper."},
{lvl:2,sec:"L",type:"order",q:"Order these functions from smallest rate of change to largest.",
 items:["y = 2x + 9","A line through (0, 0) and (2, 7)","y = 4x − 1","A table: x 0, 1, 2 → y 0, 1, 2"],
 ansOrder:["A table: x 0, 1, 2 → y 0, 1, 2","y = 2x + 9","A line through (0, 0) and (2, 7)","y = 4x − 1"],
 expl:"The rates are 2, 3.5, 4 and 1 respectively, so the order is the table (1), y = 2x + 9 (2), the line (3.5), y = 4x − 1 (4)."},
{lvl:3,sec:"L",type:"in",q:"Gym plan A costs $30 to join plus $10 per month. Plan B costs nothing to join and $16 per month. After how many months do the plans cost the same?",ans:5,
 hint:"Set 30 + 10m equal to 16m.",expl:"30 + 10m = 16m gives 30 = 6m, so m = 5 months (both cost $80)."},
{lvl:3,sec:"L",type:"mc",q:"Function F is y = 3x + 7. Function G passes through (2, 12) and (4, 20). Which statement is true?",
 opts:["G has a greater rate of change but a smaller initial value","F has a greater rate of change and a greater initial value","G has a greater rate of change and a greater initial value","F and G have the same rate of change"],a:0,
 expl:"G's rate is (20 − 12) ÷ 2 = 4, greater than 3. Going back 2 steps from (2, 12) gives G's initial value 12 − 8 = 4, less than 7."},
{lvl:3,sec:"L",type:"in",q:"Function H has initial value 5 and rate of change 2. Function K passes through (0, 1) and (2, 9). For what value of x are the two outputs equal?",ans:2,
 hint:"Write both as y = (rate)x + (initial value), then set them equal.",
 expl:"K's rate is (9 − 1) ÷ 2 = 4, so K is y = 4x + 1 and H is y = 2x + 5. Then 2x + 5 = 4x + 1 gives x = 2."}
],

"g8-funcmodel": [
{sec:"L",type:"mc",q:"A taxi charges $3 plus $2 per km. Which function gives the cost C for d km?",mono:true,
 opts:["C = 2d + 3","C = 3d + 2","C = 5d","C = 2d − 3"],a:0,
 expl:"The fixed $3 is the initial value and $2 per km is the rate, so C = 2d + 3."},
{sec:"L",type:"in",q:"Using C = 2d + 3, what is the cost in dollars of a 10 km taxi ride?",ans:23,expl:"C = 2 × 10 + 3 = 23 dollars."},
{sec:"L",type:"mc",q:"A plumber's charge is modelled by y = 15x + 40, where x is hours. What does the 40 represent?",
 opts:["The fixed call-out charge","The charge per hour","The number of hours","The total cost"],a:0,
 expl:"The constant 40 is the charge when x = 0, so it is the fixed fee paid before any hours are worked. The 15 is the hourly rate."},
{sec:"L",type:"in",q:"A candle is 20 cm tall and burns down 2 cm every hour. How tall is it, in cm, after 6 hours?",ans:8,
 expl:"Height = 20 − 2 × 6 = 8 cm."},
{lvl:2,sec:"L",type:"in",q:"A tank holds 50 litres and fills at 4 litres per minute. After how many minutes does it hold 90 litres?",ans:10,
 hint:"How many extra litres are needed?",expl:"50 + 4t = 90 gives 4t = 40, so t = 10 minutes."},
{lvl:2,sec:"L",type:"mc",q:"A battery's charge is modelled by a line through (0, 500) and (10, 300), with time in hours. Which describes the rate?",
 opts:["It loses 20 units every hour","It gains 20 units every hour","It loses 50 units every hour","It loses 10 units every hour"],a:0,
 expl:"The change is 300 − 500 = −200 over 10 hours, which is −20 per hour: a loss of 20 units each hour."},
{lvl:2,sec:"L",type:"in",q:"Kenji rents a bike for $12 plus $3 per hour. He pays $27 in total. For how many hours did he rent it?",ans:5,
 expl:"12 + 3h = 27 gives 3h = 15, so h = 5 hours."},
{lvl:2,sec:"L",type:"in",q:"A pool drains so that V = 1200 − 60t litres remain after t minutes. After how many minutes is the pool empty?",ans:20,
 hint:"Set V to 0.",expl:"1200 − 60t = 0 gives t = 1200 ÷ 60 = 20 minutes."},
{lvl:3,sec:"L",type:"in",q:"The temperature rises at a steady rate: it is 12°C at 6 am and 20°C at 10 am. What will it be, in °C, at 1 pm?",ans:26,
 hint:"Find the rate per hour first.",expl:"The rate is 8 ÷ 4 = 2°C per hour. From 10 am to 1 pm is 3 hours, so 20 + 6 = 26°C."},
{lvl:3,sec:"L",type:"in",q:"Hana runs a lemonade stand. Her fixed costs are $15, each cup costs $0.50 to make, and she sells each cup for $2. How many cups must she sell to break even?",ans:10,
 hint:"Break even means income equals total cost.",
 expl:"2n = 15 + 0.5n gives 1.5n = 15, so n = 10 cups."},
{lvl:3,sec:"L",type:"mc",q:"A quantity starts at 80 and decreases by 5 each day. Which equation models it after x days?",mono:true,
 opts:["y = 80 − 5x","y = 5x − 80","y = −80 + 5x","y = 80x − 5"],a:0,
 expl:"Initial value 80 and rate −5 per day give y = 80 − 5x."}
],

"g8-funcgraph": [
{sec:"L",type:"mc",q:"On a distance–time graph, one section is a horizontal line. What is happening there?",
 opts:["The object is not moving","The object moves at a steady speed","The object is speeding up","The object moves backwards"],a:0,
 expl:"A horizontal section means the distance does not change as time passes, so the object is stationary."},
{sec:"L",type:"mc",q:"On a distance–time graph, a steeper line means what?",
 opts:["A faster speed","A slower speed","A longer distance","A stop"],a:0,
 expl:"The slope of a distance–time graph is the speed, so a steeper line means more distance covered per second: faster."},
{sec:"L",type:"in",q:"A distance–time graph goes from (0, 0) to (4, 8), then stays flat until (7, 8). Time is in seconds and distance in metres. What is the speed, in metres per second, during the first 4 seconds?",ans:2,
 expl:"8 metres in 4 seconds is 8 ÷ 4 = 2 metres per second."},
{sec:"L",type:"mc",q:"A graph of a ball's height goes up, reaches a peak, then comes down. Which describes the function?",
 opts:["Increasing then decreasing","Decreasing then increasing","Constant throughout","Increasing throughout"],a:0,
 expl:"The height rises (increasing) up to the peak and then falls (decreasing)."},
{lvl:2,sec:"L",type:"in",q:"A distance–time graph goes from (0, 0) to (4, 8), then is flat until (7, 8), then returns to distance 0 at (11, 0). For how many seconds is the object stationary?",ans:3,
 hint:"Look for the flat part.",expl:"The flat section runs from 4 s to 7 s, which is 7 − 4 = 3 seconds."},
{lvl:2,sec:"L",type:"mc",q:"A graph of distance against time increases slowly at first, then increases much faster. Which story matches it?",
 opts:["A cyclist warms up slowly, then sprints","A cyclist sprints, then stops to rest","A cyclist waits at a red light the whole time","A cyclist rides at one steady pace"],a:0,
 expl:"A gentle slope means slow movement and a steep slope means fast movement, so the cyclist goes slowly first and then fast."},
{lvl:2,sec:"L",type:"multi",q:"A graph passes through (0, 5), (2, 9), (5, 3), (8, 3) and (10, 7), joined by straight segments. Select EVERY interval where the graph is decreasing.",
 opts:["From x = 2 to x = 5","From x = 0 to x = 2","From x = 5 to x = 8","From x = 8 to x = 10"],aMulti:[0],
 expl:"Only from x = 2 to x = 5 does y go down (9 to 3). From 0 to 2 and 8 to 10 it rises, and from 5 to 8 it stays constant."},
{lvl:2,sec:"L",type:"mc",q:"Which best describes the graph of y = x²?",
 opts:["A curve, not a straight line","A straight line through the origin","A horizontal line","A straight line with slope 2"],a:0,
 expl:"y = x² is nonlinear: equal steps in x do not give equal steps in y, so its graph is a curve (a parabola)."},
{lvl:3,sec:"L",type:"in",q:"Ravi's distance from home is graphed: (0, 0) to (3, 12), flat to (5, 12), then back to (11, 0). Time is in hours and distance in km. What is his speed, in km per hour, on the return journey?",ans:2,
 hint:"On the return, how far and how long?",expl:"He covers 12 km in 11 − 5 = 6 hours, so his speed is 12 ÷ 6 = 2 km per hour."},
{lvl:3,sec:"L",type:"in",q:"Using the same journey, (0, 0) to (3, 12), flat to (5, 12), then back to (11, 0), what total distance in km did Ravi travel?",ans:24,
 hint:"He goes out and comes back.",expl:"He travels 12 km out and 12 km back, so 24 km in total."},
{lvl:3,sec:"L",type:"mc",q:"A bath is filled steadily, then someone steps in, sits still for a while, and finally the plug is pulled. Which describes the graph of water level against time?",
 opts:["Rises steadily, jumps up, stays flat, then falls","Falls, jumps down, stays flat, then rises","Rises steadily the whole time","Stays flat, then rises, then jumps down"],a:0,
 expl:"Filling makes the level rise, stepping in makes it jump up suddenly, sitting still keeps it flat, and draining makes it fall."},
{lvl:3,sec:"L",type:"in",q:"Sofia walks 2 km in 30 minutes, rests for 30 minutes, then walks 4 km in 60 minutes. What is her average speed for the whole trip, in km per hour?",ans:3,
 hint:"Total distance divided by total time, including the rest.",
 expl:"She covers 6 km in 2 hours altogether, so her average speed is 6 ÷ 2 = 3 km per hour."}
],

"g8-transform": [
{sec:"G",type:"pair",q:"The point (3, 4) is translated 2 units right and 5 units down. Give the image point.",ansP:[5,-1],
 expl:"Add 2 to x and subtract 5 from y: (3 + 2, 4 − 5) = (5, −1)."},
{sec:"G",type:"mc",q:"What is the image of (2, 5) after a reflection in the x-axis?",mono:true,
 opts:["(2, −5)","(−2, 5)","(−2, −5)","(5, 2)"],a:0,
 expl:"Reflecting in the x-axis keeps x and changes the sign of y: (2, 5) → (2, −5)."},
{sec:"G",type:"mc",q:"Which transformation changes the size of a figure?",
 opts:["Dilation","Translation","Rotation","Reflection"],a:0,
 expl:"Translations, rotations and reflections are rigid motions that keep lengths the same. A dilation enlarges or shrinks the figure."},
{sec:"G",type:"pair",q:"Rotate the point (4, 1) by 90° anticlockwise about the origin. Give the image point.",ansP:[-1,4],
 hint:"A 90° anticlockwise turn sends (x, y) to (−y, x).",expl:"(x, y) → (−y, x), so (4, 1) → (−1, 4)."},
{sec:"G",type:"pair",q:"Rotate the point (3, 2) by 180° about the origin. Give the image point.",ansP:[-3,-2],
 expl:"A half-turn about the origin changes the sign of both coordinates: (3, 2) → (−3, −2)."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY property that stays the same after a rotation.",
 opts:["Side lengths","Angle measures","Position of the figure","Area"],aMulti:[0,1,3],
 expl:"A rotation is a rigid motion: lengths, angles and therefore area are unchanged. Only the position (and orientation) changes."},
{lvl:2,sec:"G",type:"mc",q:"Triangle ABC has A(1, 1), B(4, 1), C(1, 3). After a reflection in the y-axis, where is the image of B?",mono:true,
 opts:["(−4, 1)","(4, −1)","(−4, −1)","(1, 4)"],a:0,
 expl:"Reflecting in the y-axis changes the sign of x only: B(4, 1) → (−4, 1)."},
{lvl:2,sec:"G",type:"pair",q:"Reflect the point (−2, 6) in the line y = x. Give the image point.",ansP:[6,-2],
 hint:"Reflecting in y = x swaps the coordinates.",expl:"(x, y) → (y, x), so (−2, 6) → (6, −2)."},
{lvl:2,sec:"G",type:"mc",q:"Two figures are congruent when…",
 opts:["one maps onto the other by rigid motions","they have the same area","they have the same perimeter","they are both triangles"],a:0,
 expl:"Congruent means a sequence of translations, rotations and reflections carries one figure exactly onto the other. Equal area or perimeter alone is not enough."},
{lvl:3,sec:"G",type:"pair",q:"The point (2, 3) is translated 4 units left, then rotated 90° clockwise about the origin. Give the final image point.",ansP:[3,2],
 hint:"Do the translation first; a 90° clockwise turn sends (x, y) to (y, −x).",
 expl:"After the translation the point is (−2, 3). Rotating 90° clockwise: (x, y) → (y, −x) gives (3, 2)."},
{lvl:3,sec:"G",type:"in",q:"The point P(5, −2) is reflected in the x-axis, then the image is reflected in the y-axis. What is the sum of the final image's coordinates?",ans:-3,
 hint:"Apply the reflections one at a time.",expl:"(5, −2) → (5, 2) → (−5, 2). The sum is −5 + 2 = −3."},
{lvl:3,sec:"G",type:"mc",q:"A translation moves A(1, 2) to A'(4, 7). Where does the same translation send B(−3, 0)?",mono:true,
 opts:["(0, 5)","(−6, −5)","(0, −5)","(3, 5)"],a:0,
 expl:"The translation is 3 right and 5 up, so B(−3, 0) → (−3 + 3, 0 + 5) = (0, 5)."}
],

"g8-dilations": [
{sec:"G",type:"pair",q:"Dilate the point (2, 3) by scale factor 3 with centre at the origin. Give the image point.",ansP:[6,9],
 expl:"Multiply both coordinates by 3: (2 × 3, 3 × 3) = (6, 9)."},
{sec:"G",type:"in",q:"A triangle with sides 3, 4 and 5 cm is dilated by scale factor 2. What is the perimeter of the image in cm?",ans:24,
 expl:"Every side doubles: 6 + 8 + 10 = 24 cm (the perimeter also doubles from 12)."},
{sec:"G",type:"mc",q:"A dilation with scale factor 0.5 makes the figure…",
 opts:["half as long in every direction","twice as long in every direction","exactly the same size","a different shape"],a:0,
 expl:"A scale factor between 0 and 1 shrinks the figure; every length is multiplied by 0.5. The shape stays the same."},
{sec:"G",type:"pair",q:"Dilate the point (−4, 6) by scale factor 0.5 with centre at the origin. Give the image point.",ansP:[-2,3],
 expl:"Multiply both coordinates by 0.5: (−4 × 0.5, 6 × 0.5) = (−2, 3)."},
{lvl:2,sec:"G",type:"in",q:"A 4 cm by 6 cm rectangle is dilated by scale factor 3. What is the area of the image in square cm?",ans:216,
 hint:"Find the new side lengths first.",expl:"The image is 12 cm by 18 cm, so its area is 12 × 18 = 216 square cm (9 times the original 24)."},
{lvl:2,sec:"G",type:"in",q:"Two triangles are similar. One has sides 6, 8 and 10. The other has sides 9, 12 and x. What is x?",ans:15,
 hint:"Find the scale factor from the matching sides.",expl:"9 ÷ 6 = 1.5, so every side is multiplied by 1.5: x = 10 × 1.5 = 15."},
{lvl:2,sec:"G",type:"mc",q:"Which pair of shapes is ALWAYS similar?",
 opts:["Any two squares","Any two rectangles","Any two triangles","Any two rhombuses"],a:0,
 expl:"All squares have four right angles and equal sides, so one is always a dilation of another. Rectangles, triangles and rhombuses can have different proportions or angles."},
{lvl:2,sec:"G",type:"mc",q:"A figure is dilated by scale factor k. Its area is multiplied by…",mono:true,opts:["k²","k","2k","k³"],a:0,
 expl:"Both the length and the width are multiplied by k, so the area is multiplied by k × k = k²."},
{lvl:3,sec:"G",type:"in",q:"A triangle has sides 5, 7 and 9. A similar triangle has perimeter 63. What is the longest side of the larger triangle?",ans:27,
 hint:"Compare the perimeters to find the scale factor.",
 expl:"The small perimeter is 21, so the scale factor is 63 ÷ 21 = 3. The longest side is 9 × 3 = 27."},
{lvl:3,sec:"G",type:"in",q:"A 4 cm by 6 cm photo is enlarged so that its shorter side becomes 14 cm. How long is the longer side in cm?",ans:21,
 expl:"The scale factor is 14 ÷ 4 = 3.5, so the longer side is 6 × 3.5 = 21 cm."},
{lvl:3,sec:"G",type:"pair",q:"A dilation has centre (1, 1) and scale factor 2. Give the image of the point (3, 4).",ansP:[5,7],
 hint:"Measure from the centre, not from the origin.",
 expl:"From the centre, (3, 4) is 2 right and 3 up. Doubling gives 4 right and 6 up from (1, 1), which is (5, 7)."},
{lvl:3,sec:"G",type:"in",q:"A dilation maps a triangle of area 8 square units to a triangle of area 72 square units. What is the scale factor?",ans:3,
 hint:"Area scales by the square of the factor.",expl:"72 ÷ 8 = 9 = k², so k = 3."}
],

"g8-angleAA": [
{sec:"G",type:"in",q:"Two angles of a triangle are 50° and 65°. What is the third angle in degrees?",ans:65,
 expl:"The angles of a triangle add to 180°: 180 − 50 − 65 = 65°."},
{sec:"G",type:"in",q:"A transversal crosses two parallel lines. One angle is 110°. What is the size, in degrees, of its corresponding angle?",ans:110,
 expl:"Corresponding angles on parallel lines are equal, so it is also 110°."},
{sec:"G",type:"in",q:"A transversal crosses two parallel lines. One co-interior (same-side interior) angle is 72°. What is the other, in degrees?",ans:108,
 hint:"Co-interior angles are supplementary.",expl:"Co-interior angles add to 180°, so 180 − 72 = 108°."},
{sec:"G",type:"mc",q:"One triangle has angles 40° and 60°. Another has angles 40° and 80°. Are the triangles similar?",
 opts:["Yes, by the AA criterion","No, the angles differ","Only if their sides match","Not enough information"],a:0,
 expl:"The first triangle's third angle is 80° and the second's is 60°, so both have angles 40°, 60°, 80°. Two equal angles are enough: they are similar."},
{lvl:2,sec:"G",type:"in",q:"An exterior angle of a triangle is 120°. One of the two remote interior angles is 45°. What is the other, in degrees?",ans:75,
 hint:"An exterior angle equals the sum of the two remote interior angles.",expl:"120 − 45 = 75°."},
{lvl:2,sec:"G",type:"mc",q:"Which fact is enough to prove two triangles are similar?",
 opts:["Two angles of one equal two angles of the other","One angle of one equals one angle of the other","The two triangles have the same perimeter","The two triangles have the same area"],a:0,
 expl:"This is the AA criterion. Two matching angles force the third to match too, so the triangles have the same shape."},
{lvl:2,sec:"G",type:"in",q:"An isosceles triangle has an apex angle of 40°. What is each base angle in degrees?",ans:70,
 hint:"The two base angles are equal.",expl:"The base angles share 180 − 40 = 140°, so each is 70°."},
{lvl:2,sec:"G",type:"multi",q:"A transversal crosses two parallel lines. Select EVERY statement that is true.",
 opts:["Alternate interior angles are equal","Corresponding angles are equal","Co-interior angles are equal","Vertically opposite angles are equal"],aMulti:[0,1,3],
 expl:"Alternate interior and corresponding angles are equal when the lines are parallel, and vertically opposite angles are always equal. Co-interior angles add to 180°, they are not equal in general."},
{lvl:3,sec:"G",type:"in",q:"The angles of a triangle are in the ratio 2 : 3 : 4. What is the largest angle in degrees?",ans:80,
 hint:"There are 9 parts in total.",expl:"Each part is 180 ÷ 9 = 20°, so the largest angle is 4 × 20 = 80°."},
{lvl:3,sec:"G",type:"in",q:"In triangle ABC, angle A = 50° and angle B = 60°. In triangle PQR, angle P = 50° and angle R = 70°. AB = 10, BC = 8 and PQ = 15. What is the length of QR?",ans:12,
 hint:"Match up equal angles to see which sides correspond.",
 expl:"Angle Q = 180 − 50 − 70 = 60°, so A↔P, B↔Q, C↔R and the triangles are similar by AA. The scale factor is 15 ÷ 10 = 1.5, so QR = 8 × 1.5 = 12."},
{lvl:3,sec:"G",type:"in",q:"The angles of a triangle are (x + 10)°, (2x)° and (3x − 10)°. What is x?",ans:30,
 hint:"Add the three expressions and set the sum equal to 180.",expl:"x + 10 + 2x + 3x − 10 = 6x = 180, so x = 30."},
{lvl:3,sec:"G",type:"mc",q:"To prove the angles of a triangle add to 180°, a line is drawn through one vertex parallel to the opposite side. Which fact does the proof then use?",
 opts:["Alternate interior angles are equal","Corresponding sides are proportional","Vertically opposite angles add to 180°","Base angles of a triangle are equal"],a:0,
 expl:"The parallel line makes the two base angles of the triangle appear as alternate interior angles at the vertex. The three angles at the vertex lie on a straight line, so they total 180°."}
],

"g8-pythag": [
{sec:"G",type:"in",q:"A right triangle has legs of 6 cm and 8 cm. How long is the hypotenuse in cm?",ans:10,
 expl:"6² + 8² = 36 + 64 = 100, and √100 = 10 cm."},
{sec:"G",type:"in",q:"A right triangle has legs of 5 and 12. How long is the hypotenuse?",ans:13,expl:"5² + 12² = 25 + 144 = 169 = 13²."},
{sec:"G",type:"mc",q:"For a right triangle with legs a and b and hypotenuse c, which equation is the Pythagorean theorem?",mono:true,
 opts:["a² + b² = c²","a + b = c","a² − b² = c²","a² + c² = b²"],a:0,
 expl:"The squares of the two legs add to the square of the hypotenuse: a² + b² = c²."},
{sec:"G",type:"in",q:"A right triangle has hypotenuse 25 and one leg 7. How long is the other leg?",ans:24,
 hint:"Subtract the squares this time.",expl:"25² − 7² = 625 − 49 = 576, and √576 = 24."},
{lvl:2,sec:"G",type:"mc",q:"Which set of side lengths forms a right triangle?",mono:true,
 opts:["9, 12, 15","5, 6, 7","8, 9, 10","10, 11, 12"],a:0,
 expl:"9² + 12² = 81 + 144 = 225 = 15², so the converse of the theorem says it is right-angled. The other sets do not satisfy a² + b² = c²."},
{lvl:2,sec:"G",type:"in",q:"What is the distance between the points (−3, 1) and (5, 16)?",ans:17,
 hint:"Draw a right triangle with the horizontal and vertical changes as legs.",
 expl:"The horizontal change is 8 and the vertical change is 15. 8² + 15² = 64 + 225 = 289 = 17², so the distance is 17."},
{lvl:2,sec:"G",type:"in",q:"A 10 m ladder leans against a wall with its foot 6 m from the wall. How high up the wall, in metres, does it reach?",ans:8,
 expl:"10² − 6² = 100 − 36 = 64, so the ladder reaches √64 = 8 m."},
{lvl:2,sec:"G",type:"in",q:"A rectangle is 9 cm by 40 cm. How long is its diagonal in cm?",ans:41,
 expl:"9² + 40² = 81 + 1600 = 1681 = 41², so the diagonal is 41 cm."},
{lvl:3,sec:"G",type:"in",q:"A box measures 3 cm by 4 cm by 12 cm. What is the length in cm of the longest straight rod that fits inside it, corner to opposite corner?",ans:13,
 hint:"First find the diagonal of the base, then use it as a leg.",
 expl:"The base diagonal is √(3² + 4²) = 5. Then √(5² + 12²) = √169 = 13 cm."},
{lvl:3,sec:"G",type:"in",q:"An isosceles triangle has a base of 16 cm and two equal sides of 17 cm. What is its area in square cm?",ans:120,
 hint:"The height splits the base into two equal halves.",
 expl:"Half the base is 8, so the height is √(17² − 8²) = √(289 − 64) = √225 = 15. Area = ½ × 16 × 15 = 120 square cm."},
{lvl:3,sec:"G",type:"mc",q:"A square has sides of length 1. Which statement about its diagonal is true?",
 opts:["Its length is irrational","Its length is exactly 1.4","Its length is exactly 2","Its length is exactly 1.5"],a:0,
 expl:"The diagonal is √(1² + 1²) = √2, which is about 1.414 and cannot be written as a fraction: it is irrational."},
{lvl:3,sec:"G",type:"in",q:"A 29 m wire runs from the top of a vertical mast to a point on level ground 21 m from its base. How tall is the mast in metres?",ans:20,
 expl:"29² − 21² = 841 − 441 = 400, so the mast is √400 = 20 m tall."}
],


"g8-solids": [
{sec:"G",type:"mc",q:"Which formula gives the volume of a cylinder with radius r and height h?",mono:true,opts:["πr²h","(1/3)πr²h","(4/3)πr³","2πrh"],a:0,
 expl:"A cylinder is a stack of circular slices: base area πr² times the height h gives V = πr²h. (1/3)πr²h is a cone and (4/3)πr³ is a sphere."},
{sec:"G",type:"in",q:"A cylinder has radius 3 cm and height 10 cm. Using π ≈ 3.14, what is its volume in cubic cm?",ans:282.6,
 hint:"Find the area of the circular base first.",expl:"Base area = 3.14 × 3² = 28.26 square cm. Volume = 28.26 × 10 = 282.6 cubic cm."},
{sec:"G",type:"mc",q:"A cone has radius 2 and height 9. What is its volume in terms of π?",mono:true,opts:["12π","36π","18π","6π"],a:0,
 expl:"V = (1/3)πr²h = (1/3) × π × 4 × 9 = 12π. Without the 1/3 you would get the cylinder's 36π."},
{sec:"G",type:"in",q:"A sphere has radius 3 cm. Its volume is kπ cubic cm. What is k?",ans:36,
 hint:"Use V = (4/3)πr³ and cube the radius first.",expl:"r³ = 27, so V = (4/3) × 27 × π = 36π. k = 36."},
{lvl:2,sec:"G",type:"in",q:"A cylinder has radius 5 cm and volume 150π cubic cm. What is its height in cm?",ans:6,
 hint:"Divide the volume by the base area.",expl:"Base area = π × 25 = 25π. Height = 150π ÷ 25π = 6 cm."},
{lvl:2,sec:"G",type:"in",q:"A cone and a cylinder have the same radius and the same height. The cylinder holds 24 litres. How many litres does the cone hold?",ans:8,
 expl:"A cone holds exactly one third of the matching cylinder: 24 ÷ 3 = 8 litres."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY statement that is true.",
 opts:["Doubling the radius of a cylinder multiplies its volume by 4","Doubling the height of a cylinder doubles its volume","Doubling the radius of a sphere doubles its volume","A cone has one third the volume of a cylinder with the same base and height"],aMulti:[0,1,3],
 expl:"Volume of a cylinder is πr²h, so radius counts twice (×4) and height once (×2). A sphere's volume uses r³, so doubling r multiplies it by 8, not 2. The cone fact is the standard one third rule."},
{lvl:2,sec:"G",type:"in",q:"A sphere has volume 288π cubic cm. What is its radius in cm?",ans:6,
 hint:"Solve (4/3)r³ = 288 and then take a cube root.",expl:"(4/3)r³ = 288 gives r³ = 288 × 3 ÷ 4 = 216, and 6³ = 216, so r = 6 cm."},
{lvl:3,sec:"G",type:"in",q:"Zainab makes a solid from a cone of radius 3 cm and height 4 cm with a hemisphere of radius 3 cm glued to its base. The total volume is kπ cubic cm. What is k?",ans:30,
 hint:"A hemisphere is half a sphere. Add the two volumes.",
 expl:"Cone: (1/3) × 9 × 4 = 12π. Hemisphere: half of (4/3) × 27 = 18π. Total = 30π, so k = 30."},
{lvl:3,sec:"G",type:"in",q:"A cylindrical tank with radius 10 cm and height 20 cm is full of water. Lior pours it into paper cones, each of radius 5 cm and height 8 cm. How many cones can he fill completely?",ans:30,
 hint:"Compare the two volumes; the π cancels out.",
 expl:"Tank: π × 100 × 20 = 2000π. Cone: (1/3) × π × 25 × 8 = (200/3)π. 2000 ÷ (200/3) = 30 cones."},
{lvl:3,sec:"G",type:"mc",q:"Which solid has the greatest volume?",
 opts:["A sphere of radius 3","A cylinder of radius 3 and height 3","A cone of radius 5 and height 4","A cylinder of radius 2 and height 8"],a:0,
 expl:"Sphere: (4/3) × 27 = 36π. Cylinder 3 by 3: 27π. Cone: (1/3) × 25 × 4 ≈ 33.3π. Cylinder 2 by 8: 32π. The sphere is largest at 36π."},
{lvl:3,sec:"G",type:"in",q:"A solid metal cylinder of radius 6 cm and height 8 cm is melted down and recast into solid spheres of radius 2 cm. How many spheres are made?",ans:27,
 hint:"The total volume stays the same when the metal is recast.",
 expl:"Cylinder: π × 36 × 8 = 288π. One sphere: (4/3) × 8 = (32/3)π. 288 ÷ (32/3) = 288 × 3 ÷ 32 = 27 spheres."}
],

"g8-scatter": [
{sec:"S",type:"mc",q:"A scatter plot shows hours studied against test score. As the hours increase, the scores tend to increase too. What kind of association is this?",
 opts:["Positive","Negative","No association","Constant"],a:0,
 expl:"When one variable tends to go up as the other goes up, the association is positive."},
{sec:"S",type:"mc",q:"Which pair of variables would you expect to show a negative association?",
 opts:["Outdoor temperature and sales of hot chocolate","Height of a child and shoe size","Hours of practice and goals scored","Number of pages in a book and its weight"],a:0,
 expl:"Hotter days usually mean fewer hot chocolate sales, so one goes up while the other goes down: a negative association. The other pairs rise together."},
{sec:"S",type:"mc",q:"On a scatter plot, one point lies far away from the pattern made by all the other points. What is that point called?",
 opts:["An outlier","A cluster","A trend","An axis"],a:0,
 expl:"A point that does not follow the general pattern is an outlier. A cluster is a group of points close together."},
{sec:"S",type:"in",q:"Priya plots the points (1, 3), (2, 5), (3, 7), (4, 9) and (5, 11). Every time x increases by 1, by how much does y increase?",ans:2,
 expl:"The y-values go 3, 5, 7, 9, 11, rising by 2 each step. The points lie on a perfectly straight line, so the association is linear and positive."},
{lvl:2,sec:"S",type:"mc",q:"A scatter plot of the age of a car against its price shows points falling from top-left to bottom-right, all close to a straight line. Which description fits best?",
 opts:["Strong negative linear","Weak negative linear","Strong positive linear","Nonlinear"],a:0,
 expl:"Falling from left to right means negative; points close to a line means strong and linear."},
{lvl:2,sec:"S",type:"multi",q:"Select EVERY feature you can read from a scatter plot.",
 opts:["Whether the association is positive or negative","Whether there are outliers","Whether the association is linear or nonlinear","The exact value of every future data point"],aMulti:[0,1,2],
 expl:"A scatter plot shows direction, outliers and the shape of the pattern. It only suggests a trend; it cannot give exact future values."},
{lvl:2,sec:"S",type:"in",q:"A scatter plot has the points (1, 2), (2, 4), (3, 6), (4, 8) and (10, 3). What is the x-value of the outlier?",ans:10,
 hint:"Four of the points follow one simple pattern.",expl:"The first four points follow y = 2x. The point (10, 3) is nowhere near that line, so the outlier has x = 10."},
{lvl:2,sec:"S",type:"mc",q:"A scatter plot of daily temperature against ice-cream sales shows two separate groups of points, one for summer days and one for winter days. What is this feature called?",
 opts:["Clustering","An outlier","A negative association","A linear trend"],a:0,
 expl:"Separate groups of points on a scatter plot are clusters. Here the clusters come from two different seasons."},
{lvl:3,sec:"S",type:"mc",q:"A scatter plot shows a strong positive association between the number of fire engines sent to a fire and the damage caused. Which conclusion is justified?",
 opts:["Bigger fires need more engines and do more damage","Fire engines cause the damage","Sending fewer engines would reduce the damage","There is no association"],a:0,
 expl:"Association is not causation. The size of the fire drives both variables, so more engines go with more damage without the engines causing it."},
{lvl:3,sec:"S",type:"in",q:"Five points on a scatter plot are (2, 5), (4, 9), (6, 13), (8, 17) and (10, 21). A sixth point (12, y) follows the same pattern exactly. What is y?",ans:25,
 hint:"Look at how y changes each time x rises by 2.",expl:"y rises by 4 each time x rises by 2, so y = 2x + 1. When x = 12, y = 25."},
{lvl:3,sec:"S",type:"order",q:"Three scatter plots are described below. Put them in order from weakest to strongest positive association.",
 items:["Plot A: points scattered with no pattern","Plot B: points tightly along a rising line","Plot C: points loosely along a rising line"],
 ansOrder:["Plot A: points scattered with no pattern","Plot C: points loosely along a rising line","Plot B: points tightly along a rising line"],
 expl:"No pattern means no association (weakest). Points loosely following a rising line show a weak positive association, and points tightly along a rising line show a strong one."},
{lvl:3,sec:"S",type:"in",q:"Tomas plots hours of sleep (x) against reaction time in milliseconds (y): (5, 320), (6, 300), (7, 280), (8, 260), (9, 240). By how many milliseconds does the reaction time fall for each extra hour of sleep?",ans:20,
 expl:"Each extra hour of sleep takes the reaction time from 320 to 300 to 280 and so on, a fall of 20 ms per hour. This is a negative linear association."}
],

"g8-fitline": [
{sec:"S",type:"mc",q:"What is the purpose of a line of best fit on a scatter plot?",
 opts:["To show the overall trend of the data","To join every point in order","To show the axis of symmetry","To mark the largest value"],a:0,
 expl:"A line of best fit runs through the middle of the cloud of points to summarise the trend, so it can be used to make predictions."},
{sec:"S",type:"in",q:"A line of best fit is y = 3x + 5, where x is hours of practice and y is the score. What score does it predict for 4 hours of practice?",ans:17,
 expl:"Substitute x = 4: y = 3 × 4 + 5 = 17."},
{sec:"S",type:"mc",q:"A line of best fit has the equation y = −2x + 40. What does the slope tell you?",
 opts:["y falls by 2 for each increase of 1 in x","y rises by 2 for each increase of 1 in x","y starts at 40","x falls by 2 for each increase of 1 in y"],a:0,
 expl:"The slope −2 means that each time x goes up by 1, the predicted y goes down by 2. The 40 is the intercept, not the slope."},
{sec:"S",type:"mc",q:"Which line fits a set of scattered points best?",
 opts:["A line close to all the points, with points on both sides","A line through the two most distant points","A line through the highest point only","A line that must pass through the origin"],a:0,
 expl:"A good fit stays close to every point and has roughly as many points above it as below it. It need not pass through any particular point."},
{lvl:2,sec:"S",type:"in",q:"A line of best fit for a plant's height y (in cm) after x weeks is y = 4x + 6. After how many weeks does the line predict a height of 30 cm?",ans:6,
 hint:"Set y equal to 30 and solve for x.",expl:"4x + 6 = 30, so 4x = 24 and x = 6 weeks."},
{lvl:2,sec:"S",type:"in",q:"Wei draws a trend line through the points (2, 11) and (6, 23). What is the slope of her line?",ans:3,
 expl:"Slope = (23 − 11) ÷ (6 − 2) = 12 ÷ 4 = 3."},
{lvl:2,sec:"S",type:"mc",q:"A line of best fit passes through (1, 8) and (5, 20). What is its equation?",mono:true,
 opts:["y = 3x + 5","y = 3x + 8","y = 4x + 4","y = 2x + 6"],a:0,
 expl:"Slope = (20 − 8) ÷ (5 − 1) = 3. Then 8 = 3 × 1 + b gives b = 5, so y = 3x + 5."},
{lvl:2,sec:"S",type:"mc",q:"The line of best fit for study time in hours (x) and quiz score (y) is y = 5x + 20. What does the 20 represent?",
 opts:["The predicted score with no study time","The largest possible score","The number of students","The change in score per hour"],a:0,
 expl:"The intercept is the predicted y when x = 0, so 20 is the score the line predicts for zero hours of study."},
{lvl:3,sec:"S",type:"in",q:"A line of best fit predicts a puppy's mass y (in kg) at x weeks by y = 1.5x + 2. Diego's puppy actually has a mass of 14 kg at 6 weeks. What is the residual (actual minus predicted), in kg?",ans:3,
 hint:"Find the predicted mass at 6 weeks first.",expl:"Predicted: 1.5 × 6 + 2 = 11 kg. Residual = 14 − 11 = 3 kg."},
{lvl:3,sec:"S",type:"in",q:"A line of best fit for a car's value y (in thousands of dollars) after x years is y = −2.5x + 30. After how many years does the line predict a value of 5 thousand dollars?",ans:10,
 expl:"−2.5x + 30 = 5, so 2.5x = 25 and x = 10 years."},
{lvl:3,sec:"S",type:"mc",q:"Using data for children aged 5 to 12, a line of best fit gives height y = 6x + 80 (cm) at age x. Why is it unwise to use this line to predict the height of a 40-year-old?",
 opts:["The data only covers ages 5 to 12","The slope is too small","Heights cannot be measured in cm","The intercept is negative"],a:0,
 expl:"A trend line is only reliable within the range of the data. People stop growing, so the pattern for ages 5 to 12 does not continue to age 40 (the line would predict 320 cm)."},
{lvl:3,sec:"S",type:"multi",q:"The line y = 2x + 3 is a line of best fit for the points (1, 5), (2, 8), (3, 8) and (4, 11). Select EVERY point that lies exactly on the line.",mono:true,
 opts:["(1, 5)","(2, 8)","(3, 8)","(4, 11)"],aMulti:[0,3],
 expl:"2 × 1 + 3 = 5 and 2 × 4 + 3 = 11, so (1, 5) and (4, 11) are on the line. The line gives 7 at x = 2 and 9 at x = 3, so the other two points are not."},
{lvl:3,sec:"S",type:"in",q:"Amara draws a line of best fit through (0, 4) and (8, 20). What does her line predict for y when x = 20?",ans:44,
 hint:"Find the slope and intercept, then substitute.",expl:"Slope = (20 − 4) ÷ 8 = 2 and the intercept is 4, so y = 2x + 4. At x = 20, y = 44."}
],

"g8-twoway": [
{sec:"S",type:"in",q:"In a survey of 100 students, 30 play a sport and an instrument, 35 play a sport only, 15 play an instrument only and 20 do neither. How many students play a sport?",ans:65,
 hint:"Add the two groups that include a sport.",expl:"Sport total = 30 (both) + 35 (sport only) = 65 students."},
{sec:"S",type:"in",q:"In a survey of 100 students, 30 play a sport and an instrument, 35 play a sport only, 15 play an instrument only and 20 do neither. How many play an instrument?",ans:45,
 expl:"Instrument total = 30 (both) + 15 (instrument only) = 45 students."},
{sec:"S",type:"mc",q:"What does a two-way table show?",
 opts:["Counts for two categorical variables at once","The mean of two data sets","Two numerical variables on a graph","The order of a set of events"],a:0,
 expl:"A two-way table sorts each person or item by two categories, such as pet owner or not against walker or not, and records the count in each cell."},
{sec:"S",type:"in",q:"In a two-way table the row for Year 8 shows 12 students who like swimming and 8 who do not. What is the row total?",ans:20,
 expl:"The row total adds every cell in that row: 12 + 8 = 20 students."},
{lvl:2,sec:"S",type:"in",q:"A two-way table records 60 students. 25 are in Year 8 and like maths, 15 are in Year 8 and do not like maths, and 12 are in Year 7 and like maths. How many Year 7 students do not like maths?",ans:8,
 hint:"The four cells must add to 60.",expl:"60 − 25 − 15 − 12 = 8 Year 7 students do not like maths."},
{lvl:2,sec:"S",type:"in",q:"Of 80 people surveyed, 50 own a bike. 30 of the bike owners also own a car, and 18 people own neither. How many people own a car but not a bike?",ans:12,
 hint:"Start with the 30 people who do not own a bike.",expl:"80 − 50 = 30 people have no bike. 18 of them own neither, so 30 − 18 = 12 own a car but not a bike."},
{lvl:2,sec:"S",type:"in",q:"In a two-way table, 40 students walk to school and 30 of those walkers own a pet. What is the relative frequency of pet owners among the walkers, as a decimal?",ans:0.75,
 expl:"Row relative frequency = 30 ÷ 40 = 0.75."},
{lvl:2,sec:"S",type:"mc",q:"A two-way table shows that 45 of 60 dog owners enjoy hiking and 20 of 40 cat owners enjoy hiking. Which group is more likely to enjoy hiking?",
 opts:["Dog owners","Cat owners","Both groups equally","It cannot be told"],a:0,
 expl:"Compare the row relative frequencies: dog owners 45 ÷ 60 = 0.75, cat owners 20 ÷ 40 = 0.5. Dog owners are more likely to enjoy hiking."},
{lvl:3,sec:"S",type:"in",q:"Femi surveys 200 students. 80 play chess, and 60 of those also play football. Of the 120 who do not play chess, 90 play football. What percentage of the football players also play chess?",ans:40,
 hint:"First find the total number of football players.",
 expl:"Football players = 60 + 90 = 150. Of these, 60 play chess: 60 ÷ 150 = 0.4 = 40%."},
{lvl:3,sec:"S",type:"multi",q:"A two-way table shows that 20 of 50 left-handed students prefer art and 60 of 150 right-handed students prefer art. Select EVERY true statement.",
 opts:["The relative frequency of preferring art is 0.4 for both groups","Handedness and art preference show no association here","More right-handed than left-handed students prefer art","Left-handed students are more likely to prefer art"],aMulti:[0,1,2],
 expl:"20 ÷ 50 = 0.4 and 60 ÷ 150 = 0.4, so the rates match and there is no association. 60 is more than 20, so more right-handed students prefer art, but neither group is more likely to."},
{lvl:3,sec:"S",type:"in",q:"In a class of 30, 18 students have a brother, 14 have a sister and 7 have both. How many have neither a brother nor a sister?",ans:5,
 hint:"Fill in the both cell first, then the brother-only and sister-only cells.",
 expl:"Brother only: 18 − 7 = 11. Sister only: 14 − 7 = 7. Both: 7. That is 25 students, so 30 − 25 = 5 have neither."},
{lvl:3,sec:"S",type:"mc",q:"30 of 50 Year 7 students and 48 of 100 Year 8 students chose swimming as their favourite sport. Which statement is correct?",
 opts:["Year 7 students were more likely to choose swimming","Year 8 students were more likely to choose swimming","More Year 8 students chose it, so their rate is higher","The two rates are equal"],a:0,
 expl:"Year 7: 30 ÷ 50 = 0.6. Year 8: 48 ÷ 100 = 0.48. Although 48 is a bigger count than 30, the Year 7 rate is higher, so relative frequency is the fair comparison."},
{lvl:3,sec:"S",type:"in",q:"Chioma asks 120 people how they travel. 45% take the bus, and one third of the bus users are students. Of the people who do not take the bus, 40 are students. How many students did she ask altogether?",ans:58,
 hint:"Find the number of bus users first, then fill in each cell.",
 expl:"Bus users: 0.45 × 120 = 54, of whom 54 ÷ 3 = 18 are students. Non-bus: 66 people, 40 students. Total students = 18 + 40 = 58."}
]
};
