/* Grade 8. */
export const G8_BANKS = {
"g8-irrational": [
{sec:"N",type:"mc",q:"Which of these is IRRATIONAL?",mono:true,
 opts:["√2","4","1/2","0.75"],a:0,
 expl:"√2 cannot be written as a fraction of whole numbers — its decimal never ends or repeats."},
{sec:"N",type:"mc",q:"Which of these is RATIONAL?",mono:true,
 opts:["√9","√2","√3","π"],a:0,expl:"√9 = 3, a whole number, which is rational. The others are irrational."},
{sec:"N",type:"mc",q:"Is 0.333... (repeating forever) rational or irrational?",
 opts:["Rational","Irrational","Neither","Both"],a:0,
 expl:"A repeating decimal can always be written as a fraction (0.333... = 1/3), so it is rational."},
{sec:"N",type:"in",q:"What is √16?",ans:4,expl:"4 × 4 = 16, so √16 = 4."},
{sec:"N",type:"mc",q:"Which best describes π?",
 opts:["An irrational number","A whole number","A fraction","A repeating decimal"],a:0,
 expl:"π's decimal digits never end or repeat, which is the definition of irrational."},
{lvl:2,sec:"N",type:"mc",q:"√2 is approximately 1.41421356... Between which two whole numbers does √2 lie?",mono:true,
 opts:["1 and 2","0 and 1","2 and 3","1.4 and 1.5"],a:0,
 expl:"1² = 1 and 2² = 4, and 2 is between them, so √2 is between 1 and 2."},
{lvl:2,sec:"N",type:"in",q:"What is √49?",ans:7,expl:"7 × 7 = 49, so √49 = 7."},
{lvl:3,sec:"N",type:"mc",q:"Which sum is RATIONAL?",mono:true,
 opts:["√4 + √9","√2 + √3","π + 1","√2 + π"],a:0,
 expl:"√4 + √9 = 2 + 3 = 5, a whole number. The others combine irrational values that do not cancel out."}
],

"g8-radicals": [
{sec:"N",type:"in",q:"What is √25?",ans:5,expl:"5 × 5 = 25, so √25 = 5."},
{sec:"N",type:"in",q:"What is √64?",ans:8,expl:"8 × 8 = 64, so √64 = 8."},
{sec:"N",type:"mc",q:"Simplify: 2³ × 2²",mono:true,opts:["2⁵","2⁶","4⁵","2¹"],a:0,
 expl:"Multiplying powers with the same base adds the exponents: 3 + 2 = 5, so 2⁵."},
{sec:"N",type:"mc",q:"Simplify: (3²)³",mono:true,opts:["3⁶","3⁵","3⁹","6⁶"],a:0,
 expl:"Raising a power to a power multiplies the exponents: 2 × 3 = 6, so 3⁶."},
{sec:"N",type:"in",q:"What is 5⁻¹ written as a fraction, 1/__? Type just the denominator.",ans:5,
 expl:"A negative exponent flips it to a fraction: 5⁻¹ = 1/5."},
{lvl:2,sec:"N",type:"mc",q:"Simplify: 2⁴ ÷ 2²",mono:true,opts:["2²","2⁶","2⁸","1"],a:0,
 expl:"Dividing powers with the same base subtracts the exponents: 4 − 2 = 2, so 2²."},
{lvl:2,sec:"N",type:"in",q:"What is 4^(1/2), the square root of 4?",ans:2,
 expl:"A power of 1/2 means square root: 4^(1/2) = √4 = 2."},
{lvl:3,sec:"N",type:"mc",q:"Simplify: (2³)² ÷ 2²",mono:true,opts:["2⁴","2³","2⁸","2¹"],a:0,
 expl:"(2³)² = 2⁶, then 2⁶ ÷ 2² = 2⁴."}
],

"g8-linear": [
{sec:"P",type:"in",q:"Solve for x: 3x + 5 = 20",ans:5,expl:"20 − 5 = 15, and 15 ÷ 3 = 5."},
{sec:"P",type:"in",q:"Solve for x: 2(x − 4) = 10",ans:9,expl:"2x − 8 = 10, so 2x = 18 and x = 9."},
{sec:"P",type:"mc",q:"Which value of x solves 4x − 7 = 9?",mono:true,opts:["4","3","5","2"],a:0,
 expl:"4 × 4 − 7 = 16 − 7 = 9."},
{sec:"P",type:"in",q:"Solve for x: 5x − 3 = 3x + 9",ans:6,
 hint:"Get the x terms on one side first.",expl:"2x = 12, so x = 6."},
{sec:"P",type:"mc",q:"Which describes the solution to 2x + 6 = 2x + 6?",
 opts:["All real numbers (infinite solutions)","Only x equals zero exactly","There is no solution at all","Only x equals six exactly"],a:0,
 expl:"Both sides are identical for every x, so every real number is a solution."},
{lvl:2,sec:"P",type:"in",q:"Solve for x: 3(x + 2) = 2(x + 7)",ans:8,
 expl:"3x + 6 = 2x + 14, so x = 8."},
{lvl:2,sec:"P",type:"mc",q:"Which equation has NO solution?",mono:true,
 opts:["2x + 3 = 2x + 5","2x + 3 = 2x + 3","x + 3 = 5","2x = 6"],a:0,
 expl:"Subtracting 2x from both sides leaves 3 = 5, which is never true."},
{lvl:3,sec:"P",type:"in",q:"Solve for x: 4(x − 1) − 2x = 3x − 10",ans:6,
 hint:"Simplify the left side first.",
 expl:"4x − 4 − 2x = 2x − 4, so 2x − 4 = 3x − 10, giving x = 6."}
],

"g8-scinot": [
{sec:"N",type:"mc",q:"Which is 4,500 in scientific notation?",mono:true,
 opts:["4.5 × 10³","4.5 × 10²","45 × 10²","0.45 × 10⁴"],a:0,
 expl:"4,500 = 4.5 × 1000 = 4.5 × 10³."},
{sec:"N",type:"mc",q:"Which is 0.0032 in scientific notation?",mono:true,
 opts:["3.2 × 10⁻³","3.2 × 10³","32 × 10⁻⁴","0.32 × 10⁻²"],a:0,
 expl:"0.0032 = 3.2 × 10⁻³, moving the decimal 3 places right."},
{sec:"N",type:"in",q:"Write 6.2 × 10³ as a standard number.",ans:6200,expl:"Move the decimal 3 places right: 6200."},
{sec:"N",type:"in",q:"Write 5 × 10⁻² as a decimal.",ans:0.05,expl:"Move the decimal 2 places left: 0.05."},
{sec:"N",type:"mc",q:"Which number is LARGER: 3 × 10⁵ or 3 × 10⁴?",mono:true,
 opts:["3 × 10⁵","3 × 10⁴","They are equal","Cannot tell"],a:0,expl:"A bigger exponent means a bigger power of 10, so 3 × 10⁵ is larger."},
{lvl:2,sec:"N",type:"in",q:"Multiply: (2 × 10³) × (3 × 10²). Type the coefficient (the number part) of the result.",
 ans:6,expl:"2 × 3 = 6."},
{lvl:2,sec:"N",type:"in",q:"(2 × 10³) × (3 × 10²) = 6 × 10^?. What is the exponent?",ans:5,
 expl:"Multiplying powers of 10 adds the exponents: 3 + 2 = 5."},
{lvl:3,sec:"N",type:"in",q:"4 × 10⁶ plus 8 × 10⁵, written as (coefficient) × 10⁶. What is the coefficient?",
 ans:4.8,hint:"Convert both to the same power of 10 first.",
 expl:"4,000,000 + 800,000 = 4,800,000 = 4.8 × 10⁶."}
],

"g8-propgraph": [
{sec:"P",type:"in",q:"A line passes through (0,0) and (2,6). What is its slope?",ans:3,expl:"Slope = 6 ÷ 2 = 3."},
{sec:"P",type:"in",q:"A proportional graph has slope 4. What is y when x = 5?",ans:20,expl:"y = 4 × 5 = 20."},
{sec:"P",type:"mc",q:"The slope of a proportional relationship's graph equals ___.",
 opts:["the constant of proportionality","only the y-intercept value","always exactly zero","only the x-intercept value"],a:0,
 expl:"In y = kx, the slope k is exactly the constant of proportionality."},
{sec:"P",type:"in",q:"A line passes through (0,0) and (3,9). What is its slope?",ans:3,expl:"Slope = 9 ÷ 3 = 3."},
{sec:"P",type:"mc",q:"Which graph represents a proportional relationship?",
 opts:["A straight line through the origin","A curve","A line NOT through the origin","A circle"],a:0,
 expl:"Proportional relationships always graph as a straight line passing through (0, 0)."},
{lvl:2,sec:"P",type:"in",q:"A proportional graph passes through (4,12). What is the slope?",ans:3,
 expl:"Slope = 12 ÷ 4 = 3."},
{lvl:2,sec:"P",type:"in",q:"Using a proportional graph with slope 3, what is y when x = 7?",ans:21,
 expl:"y = 3 × 7 = 21."},
{lvl:3,sec:"P",type:"in",q:"Two points on a proportional line are (2,10) and (5,25). What is the slope, (25−10)/(5−2)?",
 ans:5,expl:"(25 − 10) ÷ (5 − 2) = 15 ÷ 3 = 5."}
],

"g8-systems": [
{sec:"P",type:"in",q:"Solve the system: x + y = 10, x = 4. What is y?",ans:6,expl:"10 − 4 = 6."},
{sec:"P",type:"in",q:"Solve: y = 2x, x + y = 12. What is x?",ans:4,
 expl:"x + 2x = 12, so 3x = 12 and x = 4."},
{sec:"P",type:"mc",q:"Two lines with DIFFERENT slopes will ___.",
 opts:["intersect at exactly one point","never intersect","overlap completely","have no solution"],a:0,
 expl:"Lines with different slopes are not parallel, so they cross at exactly one point."},
{sec:"P",type:"in",q:"Solve: x + y = 15, x − y = 3. What is x?",ans:9,
 hint:"Add the two equations together.",expl:"Adding both equations: 2x = 18, so x = 9."},
{sec:"P",type:"mc",q:"Two lines with the SAME slope but different y-intercepts are ___.",
 opts:["parallel, no solution","the same line, infinite solutions","intersecting once","perpendicular"],a:0,
 expl:"Same slope, different intercept means the lines never meet — they run parallel forever."},
{lvl:2,sec:"P",type:"in",q:"Solve: 2x + y = 9, y = x. What is x?",ans:3,
 expl:"2x + x = 9, so 3x = 9 and x = 3."},
{lvl:2,sec:"P",type:"in",q:"Solve: x − y = 2, x + y = 8. What is x?",ans:5,
 hint:"Add the two equations together.",expl:"Adding both equations: 2x = 10, so x = 5."},
{lvl:3,sec:"P",type:"in",q:"Solve: 2x + 3y = 16, x = y + 3. What is y?",ans:2,
 hint:"Substitute x = y + 3 into the first equation.",
 expl:"2(y + 3) + 3y = 16, so 2y + 6 + 3y = 16, giving 5y = 10 and y = 2."}
],

"g8-funcdef": [
{sec:"P",type:"mc",q:"A function assigns to each input ___.",
 opts:["exactly one output","any number of outputs","no outputs","always the same output"],a:0,
 expl:"That is the defining rule of a function: one input never maps to two different outputs."},
{sec:"P",type:"mc",q:"Which set of pairs (x, y) represents a function?",mono:true,
 opts:["(1,2), (2,3), (3,4)","(1,2), (1,3), (2,4)","(1,2), (1,5)","(2,3), (2,7)"],a:0,
 expl:"Only the first set has each x-value appearing exactly once."},
{sec:"P",type:"mc",q:"The VERTICAL LINE TEST checks whether a graph is a function by seeing if ___.",
 opts:["any vertical line crosses the graph more than once","any horizontal line crosses once","the graph is straight","the graph passes through the origin"],a:0,
 expl:"If a vertical line ever crosses the graph twice, that x-value has two outputs, so it is not a function."},
{sec:"P",type:"in",q:"A function is f(x) = 2x + 1. What is f(3)?",ans:7,expl:"2 × 3 + 1 = 7."},
{sec:"P",type:"in",q:"A function is f(x) = x². What is f(4)?",ans:16,expl:"4² = 16."},
{lvl:2,sec:"P",type:"in",q:"A function is f(x) = 3x − 2. What is f(5)?",ans:13,expl:"3 × 5 − 2 = 13."},
{lvl:2,sec:"P",type:"mc",q:"Which table does NOT represent a function?",mono:true,
 opts:["x=1→y=5, x=1→y=8","x=1→y=5, x=2→y=8","x=1→y=5, x=2→y=5","x=1→y=5, x=3→y=9"],a:0,
 expl:"x = 1 maps to two different outputs (5 and 8), which breaks the function rule."},
{lvl:3,sec:"P",type:"in",q:"A function is f(x) = 2x² − 3. What is f(−2)?",ans:5,
 expl:"2 × (−2)² − 3 = 2 × 4 − 3 = 5."}
],

"g8-funccomp": [
{sec:"P",type:"mc",q:"Function A: y = 2x. Function B: y = 5x. Which has the STEEPER graph?",
 opts:["Function B","Function A","They are equally steep","Cannot tell"],a:0,
 expl:"A larger slope (5 vs 2) means a steeper line."},
{sec:"P",type:"in",q:"Function A is given by a table: x=1,y=3; x=2,y=6. What is its rate of change (slope)?",
 ans:3,expl:"From x=1 to x=2, y goes from 3 to 6 — a change of 3 for each 1 in x."},
{sec:"P",type:"mc",q:"Comparing two functions given in different forms (table vs equation) requires ___.",
 opts:["finding a common measure like rate of change","simply guessing at random","ignoring one function entirely","assuming both are equal already"],a:0,
 expl:"Computing the same measure (rate of change, or a specific output) for both lets you compare fairly."},
{sec:"P",type:"in",q:"Function A: y = 4x + 1. What is y when x = 0 (the y-intercept)?",ans:1,
 expl:"4 × 0 + 1 = 1."},
{sec:"P",type:"mc",q:"Function A has a rate of change of 3. Function B (table) has points (0,2) and (2,10), a rate of change of 4. Which grows FASTER?",
 opts:["Function B","Function A","Equal","Cannot tell"],a:0,expl:"4 is a bigger rate of change than 3."},
{lvl:2,sec:"P",type:"in",q:"Function A: y = 2x + 5. Function B: y = 2x + 1. Both have the SAME rate of change. What is it?",
 ans:2,expl:"Both equations have a coefficient of 2 on x."},
{lvl:2,sec:"P",type:"mc",q:"Two functions have the same rate of change but different y-intercepts. Their graphs are ___.",
 opts:["parallel lines","the same line","intersecting lines","not lines at all"],a:0,
 expl:"Equal slope with different intercepts always produces parallel, non-intersecting lines."},
{lvl:3,sec:"P",type:"mc",q:"Function A (table): x=0,y=4; x=3,y=13. Function B: y = 4x − 2. At x = 3, which gives the LARGER value?",
 opts:["Function A","Function B","They are equal","Cannot tell"],a:0,
 expl:"Function A gives 13 at x=3. Function B gives 4×3−2 = 10. 13 is larger."}
],

"g8-funcmodel": [
{sec:"P",type:"in",q:"A taxi charges $3 plus $2 per mile: y = 2x + 3. What is the cost for 5 miles?",ans:13,
 expl:"2 × 5 + 3 = 13."},
{sec:"P",type:"mc",q:"Which situation is modeled by a LINEAR function?",
 opts:["A flat fee plus a constant rate per unit","Compound interest","Area of a growing circle","Population doubling each year"],a:0,
 expl:"A constant starting amount plus a constant rate per unit is exactly the form y = mx + b."},
{sec:"P",type:"in",q:"A savings model is y = 50 + 10x (x = months). How much after 6 months?",ans:110,
 expl:"50 + 10 × 6 = 110."},
{sec:"P",type:"mc",q:"In the model y = 50 + 10x, what does the 50 represent?",
 opts:["The starting amount","The monthly rate","The number of months","The final amount"],a:0,
 expl:"50 is the value when x = 0 — the starting point before any months pass."},
{sec:"P",type:"mc",q:"In the model y = 50 + 10x, what does the 10 represent?",
 opts:["The rate of change per month","The starting amount","The total after 1 year","Nothing important"],a:0,
 expl:"10 is added for every one unit increase in x — the rate of change."},
{lvl:2,sec:"P",type:"in",q:"A model is y = 100 − 5x (x = weeks, y = money left). How much is left after 8 weeks?",
 ans:60,expl:"100 − 5 × 8 = 60."},
{lvl:2,sec:"P",type:"in",q:"Using y = 100 − 5x, after how many weeks does y = 0?",ans:20,
 expl:"0 = 100 − 5x, so 5x = 100 and x = 20."},
{lvl:3,sec:"P",type:"in",q:"A gym charges a $40 sign-up fee plus $15/month: y = 15x + 40. After how many months has a member paid $130 total?",
 ans:6,expl:"130 = 15x + 40, so 90 = 15x and x = 6."}
],

"g8-funcgraph": [
{sec:"P",type:"mc",q:"On a graph, where does a function cross the y-axis?",
 opts:["At its y-intercept","At its slope","At the origin always","Nowhere"],a:0,
 expl:"The y-intercept is defined as where a graph crosses the y-axis."},
{sec:"P",type:"mc",q:"A graph is a straight line rising left to right. Its slope is ___.",
 opts:["positive","negative","zero","undefined"],a:0,expl:"A rising line (left to right) always has a positive slope."},
{sec:"P",type:"mc",q:"A graph is a straight line falling left to right. Its slope is ___.",
 opts:["negative","positive","zero","undefined"],a:0,expl:"A falling line (left to right) always has a negative slope."},
{sec:"P",type:"mc",q:"A horizontal line has a slope of ___.",
 opts:["zero","positive","negative","undefined"],a:0,expl:"A horizontal line never rises or falls, so its slope is 0."},
{sec:"P",type:"mc",q:"Reading a graph, if y = 8 when x = 2, what point is plotted?",mono:true,
 opts:["(2, 8)","(8, 2)","(2, 2)","(8, 8)"],a:0,expl:"An ordered pair is always written (x, y): (2, 8)."},
{lvl:2,sec:"P",type:"mc",q:"A graph shows a function increasing quickly then leveling off. Which best describes its rate of change?",
 opts:["It decreases over time","It stays exactly constant","It increases at first, then slows","It is always zero"],a:0,
 expl:"Leveling off after a fast start means the rate of increase itself is shrinking over time."},
{lvl:2,sec:"P",type:"mc",q:"Two functions are graphed. Function A is always above Function B for all x shown. What does that mean?",
 opts:["Function A has greater output values than B, everywhere shown","They are equal","Function B is always increasing","Nothing can be concluded"],a:0,
 expl:"Being higher on the graph at every x means larger y-values at every x."},
{lvl:3,sec:"P",type:"mc",q:"A graph shows a function passing through (0,5) and decreasing at a constant rate to (5,0). What is its slope?",
 opts:["−1","1","−5","5"],a:0,expl:"(0 − 5) ÷ (5 − 0) = −1."}
],

"g8-transform": [
{sec:"G",type:"mc",q:"A reflection, rotation, or translation of a shape produces a shape that is ___ to the original.",
 opts:["congruent","similar but not congruent","always bigger","always smaller"],a:0,
 expl:"These transformations preserve size and shape exactly — the image is congruent to the original."},
{sec:"G",type:"mc",q:"Which transformation flips a shape over a line?",
 opts:["Reflection","Rotation","Translation","Dilation"],a:0,expl:"A reflection is a mirror-flip across a line."},
{sec:"G",type:"mc",q:"Which transformation slides a shape without turning or flipping it?",
 opts:["Translation","Reflection","Rotation","Dilation"],a:0,expl:"A translation moves every point the same distance in the same direction."},
{sec:"G",type:"mc",q:"Which transformation turns a shape around a fixed point?",
 opts:["Rotation","Translation","Reflection","Dilation"],a:0,expl:"A rotation spins a shape around a center point by some angle."},
{sec:"G",type:"mc",q:"Two shapes are congruent if one can be mapped onto the other using ___.",
 opts:["rotations, reflections and translations","only enlarging the shape","only shrinking the shape","only changing its color"],a:0,
 expl:"Congruence transformations (rotate, reflect, translate) preserve size — exactly what congruence requires."},
{lvl:2,sec:"G",type:"mc",q:"A triangle is translated 3 units right and 2 units up. What happens to its side lengths?",
 opts:["They stay exactly the same","They all increase","They all decrease","They double"],a:0,
 expl:"A translation only moves a shape — it never changes any lengths."},
{lvl:2,sec:"G",type:"mc",q:"A shape is reflected twice over the same line. What is the result?",
 opts:["The same shape as the original","A shape twice as big","A rotated shape","A shrunk shape"],a:0,
 expl:"Reflecting back over the same line undoes the first reflection, returning the original."},
{lvl:3,sec:"G",type:"mc",q:"A figure undergoes a rotation, then a reflection, then a translation. Is the final figure congruent to the original?",
 opts:["Yes, all three are congruence transformations","No, reflections break congruence","No, only translations preserve congruence","Only if it's a circle"],a:0,
 expl:"Rotations, reflections and translations all preserve size and shape, so any sequence of them keeps the figure congruent."}
],

"g8-dilations": [
{sec:"G",type:"in",q:"A shape is dilated by a scale factor of 3. A side that was 4 units becomes how many units?",
 ans:12,expl:"4 × 3 = 12."},
{sec:"G",type:"in",q:"A shape is dilated by a scale factor of 1/2. A side that was 10 units becomes how many units?",
 ans:5,expl:"10 × 0.5 = 5."},
{sec:"G",type:"mc",q:"A dilation with scale factor greater than 1 makes a shape ___.",
 opts:["larger","smaller","the same size","rotated"],a:0,expl:"A scale factor above 1 enlarges every length."},
{sec:"G",type:"mc",q:"A dilation with scale factor between 0 and 1 makes a shape ___.",
 opts:["smaller","larger","the same size","reflected"],a:0,expl:"A scale factor below 1 shrinks every length."},
{sec:"G",type:"mc",q:"Two similar figures have ___.",
 opts:["the same shape but maybe not the same size","only the same size, nothing else","completely different shapes","no relationship at all"],a:0,
 expl:"Similar figures keep matching angles and proportional sides, but can differ in overall size."},
{lvl:2,sec:"G",type:"in",q:"A triangle with sides 3, 4, 5 is dilated by scale factor 2. What is the length of the side that was originally 5?",
 ans:10,expl:"5 × 2 = 10."},
{lvl:2,sec:"G",type:"in",q:"Two similar rectangles have a scale factor of 4. If the smaller rectangle's width is 3, what is the larger rectangle's width?",
 ans:12,expl:"3 × 4 = 12."},
{lvl:3,sec:"G",type:"in",q:"A figure is dilated by scale factor 2, then that image is dilated by scale factor 3. What is the OVERALL scale factor from the original?",
 ans:6,expl:"Scale factors multiply together: 2 × 3 = 6."}
],

"g8-angleAA": [
{sec:"G",type:"in",q:"Two angles of a triangle are 50° and 60°. What is the third angle?",ans:70,
 expl:"180 − 50 − 60 = 70."},
{sec:"G",type:"mc",q:"The AA (Angle-Angle) criterion says two triangles are similar if ___.",
 opts:["two pairs of corresponding angles are equal","one pair of sides is equal","all sides are equal","they have the same perimeter"],a:0,
 expl:"Matching just two angles is enough to guarantee similarity."},
{sec:"G",type:"mc",q:"If two angles of Triangle A match two angles of Triangle B, what can you conclude?",
 opts:["The triangles are similar","The triangles are congruent","The triangles are identical in size","Nothing"],a:0,
 expl:"AA guarantees similarity (same shape), not congruence (same size)."},
{sec:"G",type:"in",q:"A triangle has angles 90° and 40°. What is the third angle?",ans:50,
 expl:"180 − 90 − 40 = 50."},
{sec:"G",type:"mc",q:"Why does matching just 2 angles guarantee similarity, without needing the 3rd?",
 opts:["Triangle angles always sum to 180°, fixing the 3rd","Triangles never actually need 3 angles","This rule doesn't really work at all","Only right triangles work this way"],a:0,
 expl:"Once two angles are fixed, the third is forced to make the total 180°, so all three automatically match."},
{lvl:2,sec:"G",type:"in",q:"Triangle A has angles 30° and 70°. Triangle B has angles 30° and 70°. What is the third angle in EACH triangle?",
 ans:80,expl:"180 − 30 − 70 = 80."},
{lvl:2,sec:"G",type:"mc",q:"Two right triangles both have a 35° angle. Are they similar by AA?",
 opts:["Yes — both share a right angle and a 35° angle, so 2 angles match","No, right triangles are never similar","Only if their sides are equal too","Cannot tell without more angles"],a:0,
 expl:"Both share the right angle (90°) plus the 35° angle — that is 2 matching angles, which is enough for AA."},
{lvl:3,sec:"G",type:"mc",q:"Triangle A has angles 45°-45°-90°. Triangle B has angles 45°-45°-90°. Are they necessarily CONGRUENT (not just similar)?",
 opts:["Not necessarily — they could be different sizes","Yes, always congruent","No, they can never be similar","Only if drawn identically"],a:0,
 expl:"Matching angles alone guarantees similarity, not size — the triangles could still be different sizes."}
],

"g8-pythag": [
{sec:"G",type:"in",q:"A right triangle has legs 3 and 4. What is the hypotenuse?",ans:5,
 expl:"3² + 4² = 9 + 16 = 25, and √25 = 5."},
{sec:"G",type:"in",q:"A right triangle has legs 6 and 8. What is the hypotenuse?",ans:10,
 expl:"6² + 8² = 36 + 64 = 100, and √100 = 10."},
{sec:"G",type:"in",q:"A right triangle has a hypotenuse of 13 and one leg of 5. What is the other leg?",ans:12,
 expl:"13² − 5² = 169 − 25 = 144, and √144 = 12."},
{sec:"G",type:"mc",q:"The Pythagorean theorem states a² + b² = c², where c is ___.",
 opts:["the hypotenuse","the shortest leg","either leg","the perimeter"],a:0,
 expl:"c always represents the hypotenuse, the longest side, opposite the right angle."},
{sec:"G",type:"in",q:"A right triangle has legs 5 and 12. What is the hypotenuse?",ans:13,
 expl:"5² + 12² = 25 + 144 = 169, and √169 = 13."},
{lvl:2,sec:"G",type:"in",q:"A ladder leans against a wall, reaching 12 feet up. The base is 5 feet from the wall. How long is the ladder?",
 ans:13,expl:"12² + 5² = 144 + 25 = 169, and √169 = 13."},
{lvl:2,sec:"G",type:"in",q:"A right triangle has hypotenuse 25 and one leg 7. What is the other leg?",ans:24,
 expl:"25² − 7² = 625 − 49 = 576, and √576 = 24."},
{lvl:3,sec:"G",type:"in",q:"A rectangular TV screen is 24 by 18 inches. What is the diagonal length (its size in inches)?",
 ans:30,expl:"24² + 18² = 576 + 324 = 900, and √900 = 30."}
],

"g8-solids": [
{sec:"G",type:"in",q:"A sphere has radius 3. Using volume = (4/3)πr³ and π ≈ 3.14, what is its volume? Type as a decimal rounded to 2 places.",
 ans:113.04,expl:"(4/3) × 3.14 × 27 = 113.04."},
{sec:"G",type:"in",q:"A cone has radius 3, height 4. Using volume = (1/3)πr²h and π ≈ 3.14, what is its volume?",
 ans:37.68,expl:"(1/3) × 3.14 × 9 × 4 = 37.68."},
{sec:"G",type:"mc",q:"Which formula gives the volume of a sphere?",mono:true,
 opts:["(4/3)πr³","πr²h","(1/3)πr²h","2πr"],a:0,expl:"A sphere's volume formula is (4/3) times π times its radius cubed."},
{sec:"G",type:"mc",q:"Which formula gives the volume of a cone?",mono:true,
 opts:["(1/3)πr²h","πr²h","(4/3)πr³","2πrh"],a:0,
 expl:"A cone's volume is exactly 1/3 of a cylinder with the same base and height."},
{sec:"G",type:"in",q:"A cylinder and a cone share the same radius and height. If the cylinder's volume is 300, what is the cone's volume?",
 ans:100,expl:"A cone's volume is always 1/3 of the matching cylinder's: 300 ÷ 3 = 100."},
{lvl:2,sec:"G",type:"in",q:"A sphere has radius 6. Using π ≈ 3.14, what is its volume? Type as a decimal.",
 ans:904.32,expl:"(4/3) × 3.14 × 216 = 904.32."},
{lvl:2,sec:"G",type:"in",q:"A cone has volume 50.24, π ≈ 3.14, and radius 4. What is its height?",
 ans:3,hint:"Rearrange V = (1/3)πr²h to solve for h.",
 expl:"50.24 = (1/3) × 3.14 × 16 × h, so h = 50.24 ÷ 16.75 ≈ 3."},
{lvl:3,sec:"G",type:"in",q:"Two spheres have radii 2 and 4. The second sphere's volume is how many times the first's? (Volume scales with r³.)",
 ans:8,expl:"(4 ÷ 2)³ = 2³ = 8."}
],

"g8-scatter": [
{sec:"S",type:"mc",q:"A scatter plot with points trending upward (as x increases, y increases) shows a ___ association.",
 opts:["positive","negative","no","perfect only"],a:0,expl:"An upward trend means both variables increase together — a positive association."},
{sec:"S",type:"mc",q:"A scatter plot with points trending downward shows a ___ association.",
 opts:["negative","positive","no","perfect only"],a:0,expl:"A downward trend means one variable increases as the other decreases — negative."},
{sec:"S",type:"mc",q:"A scatter plot with points scattered randomly, no trend, shows ___.",
 opts:["no association","strong positive association","strong negative association","a perfect line"],a:0,
 expl:"No consistent pattern between the variables means no association."},
{sec:"S",type:"mc",q:"Which pair of variables would likely show a POSITIVE association on a scatter plot?",
 opts:["Hours studied and test score","Hours of TV watched and test score","Temperature and hot cocoa sales","None of these"],a:0,
 expl:"More hours studied tends to go with higher test scores — both tend to rise together."},
{sec:"S",type:"mc",q:"An outlier on a scatter plot is a point that ___.",
 opts:["doesn't fit the overall pattern","is exactly on the trend line","is at the origin","doesn't exist"],a:0,
 expl:"An outlier stands apart from where most of the data falls, breaking the general trend."},
{lvl:2,sec:"S",type:"mc",q:"A scatter plot shows height vs. shoe size with points closely following a line. This suggests a ___ association.",
 opts:["strong","weak","no","random"],a:0,expl:"Points that hug a line closely indicate a strong relationship between the variables."},
{lvl:2,sec:"S",type:"mc",q:"Which scatter plot pattern shows the STRONGEST association?",
 opts:["Points tightly clustered along a line","Points spread randomly everywhere","Points forming a circle","Points all at one spot"],a:0,
 expl:"A tight clustering along a line is the clearest sign of a strong relationship."},
{lvl:3,sec:"S",type:"mc",q:"A scatter plot of ice cream sales vs. temperature shows a positive trend, but one hot day had very LOW sales due to a storm. That point is a(n) ___.",
 opts:["outlier","the trend line","the mean","impossible data"],a:0,
 expl:"That point breaks the overall pattern for an explainable reason — a classic outlier."}
],

"g8-fitline": [
{sec:"S",type:"in",q:"A line of best fit is y = 2x + 1. What is the predicted y when x = 5?",ans:11,
 expl:"2 × 5 + 1 = 11."},
{sec:"S",type:"in",q:"A line of best fit is y = 3x − 2. What is the predicted y when x = 4?",ans:10,
 expl:"3 × 4 − 2 = 10."},
{sec:"S",type:"mc",q:"A line of best fit is used to ___.",
 opts:["make predictions from the data's overall trend","connect every single point exactly","show data with no pattern","replace the actual data"],a:0,
 expl:"It summarizes the trend so you can estimate values the data didn't directly measure."},
{sec:"S",type:"mc",q:"In y = mx + b for a line of best fit, m represents ___.",
 opts:["the rate of change (slope)","the starting value","the number of data points","the outliers"],a:0,
 expl:"m is the slope, showing how y changes per unit of x."},
{sec:"S",type:"mc",q:"In y = mx + b for a line of best fit, b represents ___.",
 opts:["the y-intercept","the slope","the mean","the range"],a:0,expl:"b is the value of y when x = 0 — the y-intercept."},
{lvl:2,sec:"S",type:"in",q:"A line of best fit is y = 1.5x + 3. What is the predicted y when x = 10?",ans:18,
 expl:"1.5 × 10 + 3 = 18."},
{lvl:2,sec:"S",type:"mc",q:"A line of best fit does NOT need to ___.",
 opts:["pass through every data point","show the general trend","have a slope","be useful for predictions"],a:0,
 expl:"A best-fit line summarizes the trend — it rarely hits every single point exactly."},
{lvl:3,sec:"S",type:"in",q:"A line of best fit is y = 0.5x + 20, modeling test scores (y) vs. hours studied (x). Predict the score for 10 hours studied.",
 ans:25,expl:"0.5 × 10 + 20 = 25."}
],

"g8-twoway": [
{sec:"S",type:"in",q:"A two-way table shows: 20 students like pizza and are in 6th grade; 15 like pizza and are in 7th grade. How many total students like pizza?",
 ans:35,expl:"20 + 15 = 35."},
{sec:"S",type:"mc",q:"A two-way table organizes data by ___.",
 opts:["two categorical variables at once","only one variable","numbers only","nothing meaningful"],a:0,
 expl:"A two-way table cross-tabulates two categories, like grade and favorite food."},
{sec:"S",type:"in",q:"A table shows: boys who play sports = 12, boys who don't = 8, girls who play = 15, girls who don't = 5. How many total boys?",
 ans:20,expl:"12 + 8 = 20."},
{sec:"S",type:"in",q:"Using that same table, how many total students play sports?",ans:27,
 expl:"12 + 15 = 27."},
{sec:"S",type:"mc",q:"A relative frequency in a two-way table is usually expressed as a ___.",
 opts:["percentage or proportion","whole number only","negative number","letter"],a:0,
 expl:"Relative frequencies compare a count to a total, typically shown as a percent or fraction."},
{lvl:2,sec:"S",type:"in",q:"Using the table (boys who play sports = 12, boys who don't = 8, girls who play = 15, girls who don't = 5), how many total students are there?",
 ans:40,expl:"12 + 8 + 15 + 5 = 40."},
{lvl:2,sec:"S",type:"in",q:"Using that table, how many more girls play sports than boys who don't play?",
 ans:7,expl:"15 − 8 = 7."},
{lvl:3,sec:"S",type:"in",q:"A two-way table has 60 students total: 25 boys play sports, 15 boys don't play, and 5 girls don't play. How many girls DO play?",
 ans:15,hint:"Find the total number of girls first.",
 expl:"Total boys: 25 + 15 = 40. Total girls: 60 − 40 = 20. Girls who play: 20 − 5 = 15."}
]
};
