/* Kindergarten, second set: ordinals, solid shapes, combining shapes, comparing,
   sorting, picture graphs, and the advanced strand (skip counting, halves,
   symmetry, pattern blocks, turns and flips, picture trees, winning moves).
   Sentences stay very short and concrete; numbers stay small. Pictures are
   described in words so the questions read aloud well. */
export const K_MORE_BANKS = {
"k-ordinal": [
{sec:"N",type:"mc",q:"In a line: Amara, Kenji, Priya. Who is second?",opts:["Kenji","Amara","Priya"],a:0,
 expl:"Amara is first, Kenji is second, Priya is third."},
{sec:"N",type:"mc",q:"Mateo is 3rd in line. What does 3rd mean?",opts:["third","three","thirty"],a:0,
 expl:"3rd is short for third. It tells the place in a line."},
{sec:"N",type:"in",q:"Zainab is first in line. Lior is right behind her. What place is Lior? Type the number.",ans:2,
 hint:"First, then what?",expl:"First, then second. Lior is 2nd, so the number is 2."},
{sec:"N",type:"mc",q:"Which word tells a place in a line?",opts:["fourth","four","forty"],a:0,
 expl:"Fourth tells the place. Four tells how many."},
{lvl:2,sec:"N",type:"mc",q:"A race: Tomas, then Aisha, then Wei, then Nadia. Who came third?",opts:["Wei","Aisha","Nadia"],a:0,
 expl:"Tomas is first, Aisha is second, Wei is third, Nadia is fourth."},
{lvl:2,sec:"N",type:"order",q:"Put these in order, first to last.",items:["third","first","second","fourth"],
 ansOrder:["first","second","third","fourth"],expl:"First comes before second, then third, then fourth."},
{lvl:2,sec:"N",type:"in",q:"Ten cars are in a row. The blue car is 5th from the front. How many cars are in front of it?",ans:4,
 hint:"Count the places before 5th.",expl:"Cars 1, 2, 3 and 4 are in front of the 5th car. That is 4 cars."},
{lvl:3,sec:"N",type:"in",q:"Oluwaseun is 3rd in line. There are 2 children behind him. How many children are in line?",ans:5,
 hint:"Count the children in front, then him, then the ones behind.",
 expl:"Two children are in front, then Oluwaseun, then 2 more. 2 + 1 + 2 = 5."},
{lvl:3,sec:"N",type:"mc",q:"Ingrid is 2nd in line. Ravi is right behind her. Sofia is right behind Ravi. What place is Sofia?",
 opts:["4th","3rd","5th"],a:0,expl:"Ingrid is 2nd, Ravi is 3rd, so Sofia is 4th."}
],

"k-3d": [
{sec:"G",type:"mc",q:"A ball is shaped like which solid?",opts:["sphere","cube","cone"],a:0,
 expl:"A ball is round all over. That is a sphere."},
{sec:"G",type:"mc",q:"A dice has 6 flat square faces. What solid is it?",opts:["cube","sphere","cylinder"],a:0,
 expl:"A cube has 6 square faces, all the same size."},
{sec:"G",type:"mc",q:"A tin of soup is shaped like which solid?",opts:["cylinder","cube","pyramid"],a:0,
 expl:"A tin has two round flat ends and a curved side. That is a cylinder."},
{sec:"G",type:"in",q:"How many flat faces does a cube have?",ans:6,hint:"Think of a dice.",
 expl:"A cube has 6 square faces: top, bottom and 4 sides."},
{lvl:2,sec:"G",type:"mc",q:"Which solid has a point at the top and one round face?",opts:["cone","cylinder","cube"],a:0,
 expl:"A cone has one round flat face and comes to a point, like an ice cream cone."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY solid that can roll.",opts:["sphere","cylinder","cube","cone"],aMulti:[0,1,3],
 expl:"A sphere, a cylinder and a cone have curved parts, so they roll. A cube only slides."},
{lvl:2,sec:"G",type:"in",q:"How many flat faces does a cylinder have?",ans:2,
 expl:"A cylinder has a flat circle on top and one on the bottom. That is 2."},
{lvl:3,sec:"G",type:"mc",q:"I have no flat faces. I roll every way. What am I?",opts:["sphere","cylinder","cone"],a:0,
 hint:"A cylinder and a cone each have a flat face.",expl:"A cylinder and a cone each have a flat face. Only a sphere has none."},
{lvl:3,sec:"G",type:"in",q:"Diego has 1 cube and 1 cylinder. How many flat faces do they have in all?",ans:8,
 hint:"Count the faces of each solid, then add.",expl:"A cube has 6 flat faces. A cylinder has 2. 6 + 2 = 8."}
],

"k-combine": [
{sec:"G",type:"mc",q:"Two same triangles are put side by side. What shape can they make?",opts:["a square","a circle","an oval"],a:0,
 expl:"Two triangles that match can make a square. Curved shapes need curves."},
{sec:"G",type:"mc",q:"Two squares are put side by side. What shape do they make?",opts:["a rectangle","a circle","a triangle"],a:0,
 expl:"Two squares in a row make a long shape with 4 corners: a rectangle."},
{sec:"G",type:"mc",q:"A house picture is a square with a shape on top for the roof. Which shape is the roof?",opts:["triangle","circle","oval"],a:0,
 expl:"A roof comes to a point. A triangle sits on the square."},
{sec:"G",type:"in",q:"Leila uses 2 triangles to make a square. How many triangles for 2 squares?",ans:4,
 hint:"Each square needs the same number.",expl:"Each square needs 2 triangles. 2 + 2 = 4 triangles."},
{lvl:2,sec:"G",type:"mc",q:"A square is cut from corner to corner. What are the two parts?",opts:["two triangles","two squares","two circles"],a:0,
 expl:"A cut from corner to corner makes two triangles that match."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY shape that can be made from squares only.",opts:["rectangle","bigger square","circle","triangle"],aMulti:[0,1],
 expl:"Squares in a row make a rectangle, and 4 squares make a bigger square. Squares have no curves, so no circle, and no slanted side, so no triangle."},
{lvl:2,sec:"G",type:"in",q:"Arjun uses 4 small squares to make one big square. How many small squares are along one side?",ans:2,
 hint:"Two rows, two in each row.",expl:"The big square is 2 small squares wide and 2 tall. One side has 2."},
{lvl:3,sec:"G",type:"in",q:"Noor makes a house: a square with a triangle roof. She uses 2 triangles for the square. How many triangles in all?",ans:3,
 hint:"Count the triangles in the square, then the roof.",expl:"2 triangles make the square, plus 1 for the roof. 2 + 1 = 3."},
{lvl:3,sec:"G",type:"mc",q:"Elias joins a square and a triangle along one side. How many sides does the new shape have?",mono:true,opts:["5","7","4"],a:0,
 hint:"The joined side is hidden inside.",expl:"The square has 4 sides and the triangle has 3. The joined side is hidden, so 4 + 3 − 2 = 5 sides."}
],

"k-compare": [
{sec:"M",type:"mc",q:"Which is heavier, a feather or a brick?",opts:["a brick","a feather","they are the same"],a:0,
 expl:"A brick is heavy. A feather is very light."},
{sec:"M",type:"mc",q:"A giraffe and a mouse. Which is taller?",opts:["the giraffe","the mouse","they are the same"],a:0,
 expl:"A giraffe is very tall. A mouse is small and low."},
{sec:"M",type:"mc",q:"Chioma's rope is 5 blocks long. Femi's rope is 3 blocks long. Whose rope is longer?",opts:["Chioma's","Femi's","the same"],a:0,
 expl:"5 is more than 3, so Chioma's rope is longer."},
{sec:"M",type:"mc",q:"A cup and a bucket. Which holds more water?",opts:["the bucket","the cup","the same"],a:0,
 expl:"A bucket is much bigger inside. It holds more."},
{lvl:2,sec:"M",type:"in",q:"Yusuf's pencil is 6 cubes long. Sofia's pencil is 4 cubes long. How much longer is Yusuf's pencil, in cubes?",ans:2,
 hint:"Take the short one away from the long one.",expl:"6 − 4 = 2. Yusuf's pencil is 2 cubes longer."},
{lvl:2,sec:"M",type:"mc",q:"A balance scale tips down on the side with the apple. The other side has a grape. Which is heavier?",opts:["the apple","the grape","the same"],a:0,
 expl:"The heavy side goes down. The apple side went down, so the apple is heavier."},
{lvl:2,sec:"M",type:"order",q:"Put these from shortest to tallest.",items:["a chair","a cup","a door"],ansOrder:["a cup","a chair","a door"],
 expl:"A cup is small. A chair is taller than a cup. A door is taller than a chair."},
{lvl:3,sec:"M",type:"mc",q:"Wei's stick is longer than Ravi's stick. Ravi's stick is longer than Hana's stick. Whose stick is shortest?",opts:["Hana's","Wei's","Ravi's"],a:0,
 hint:"Line the three sticks up in your head.",expl:"Wei's is the longest. Ravi's is in the middle. Hana's is the shortest."},
{lvl:3,sec:"M",type:"in",q:"A pumpkin weighs the same as 4 apples. An apple weighs the same as 2 plums. How many plums weigh the same as the pumpkin?",ans:8,
 hint:"Swap each apple for plums.",expl:"Each apple is 2 plums. 4 apples is 2 + 2 + 2 + 2 = 8 plums."}
],

"k-sort": [
{sec:"M",type:"mc",q:"Which one does not belong? sock, shoe, boot, apple",opts:["apple","sock","boot"],a:0,
 expl:"Sock, shoe and boot go on your feet. An apple is food."},
{sec:"M",type:"mc",q:"Pip sorts buttons by colour. Which button goes with the red ones?",opts:["a big red button","a small blue button","a green button"],a:0,
 expl:"Sorting by colour looks only at colour. The red button joins the red group, big or small."},
{sec:"M",type:"in",q:"Kenji has 3 red blocks, 2 blue blocks and 1 green block. How many colour groups can he make?",ans:3,
 hint:"Count the colours, not the blocks.",expl:"Red, blue and green. That is 3 groups."},
{sec:"M",type:"mc",q:"These toys are sorted: car, truck, bus in one box. What is the rule?",opts:["things with wheels","things that fly","things to eat"],a:0,
 expl:"A car, a truck and a bus all have wheels. That is the rule."},
{lvl:2,sec:"M",type:"in",q:"Amara sorts 7 shapes. 4 are circles. The rest are squares. How many squares?",ans:3,
 hint:"Take the circles away from 7.",expl:"7 − 4 = 3 squares."},
{lvl:2,sec:"M",type:"multi",q:"Select EVERY thing that belongs in the 'animals' group.",opts:["dog","cow","chair","fish"],aMulti:[0,1,3],
 expl:"A dog, a cow and a fish are animals. A chair is not."},
{lvl:2,sec:"M",type:"mc",q:"Priya sorts by size. Big things in one pile, small things in the other. Where does a bus go?",opts:["big pile","small pile","no pile"],a:0,
 expl:"A bus is big. It goes in the big pile."},
{lvl:3,sec:"M",type:"in",q:"Mateo has 6 buttons. 4 are round. 2 of the round ones are red. How many round buttons are not red?",ans:2,
 hint:"Only look at the round ones.",expl:"4 round buttons, and 2 of them are red. 4 − 2 = 2 are not red."},
{lvl:3,sec:"M",type:"mc",q:"Zainab sorts: 'apple, ball, orange' in one group and 'book, box, dice' in the other. What is her rule?",
 opts:["round or not round","red or not red","big or small"],a:0,
 expl:"Apple, ball and orange are round. Book, box and dice have flat sides and corners. The rule is round or not round."}
],

"k-picgraph": [
{sec:"M",type:"in",q:"A picture graph shows pets. Dogs: 4 pictures. Cats: 2 pictures. Each picture is 1 pet. How many dogs?",ans:4,
 expl:"Each picture is 1 dog. The dog row has 4 pictures, so 4 dogs."},
{sec:"M",type:"mc",q:"A graph shows fruit. Apples: 3 pictures. Pears: 5 pictures. Which fruit has more?",opts:["pears","apples","the same"],a:0,
 expl:"5 is more than 3. The pear row is longer."},
{sec:"M",type:"mc",q:"A graph shows the weather. Sunny: 6 pictures. Rainy: 2 pictures. Which had fewer days?",opts:["rainy","sunny","the same"],a:0,
 expl:"2 is fewer than 6. Rainy had fewer days."},
{sec:"M",type:"in",q:"A graph shows toys. Cars: 2, balls: 3, dolls: 1. Each picture is 1 toy. How many balls?",ans:3,
 expl:"The ball row shows 3 pictures, so there are 3 balls."},
{lvl:2,sec:"M",type:"in",q:"Lior's graph: red 3 pictures, blue 4 pictures. Each picture is 1 vote. How many votes in all?",ans:7,
 hint:"Add the two rows.",expl:"3 + 4 = 7 votes."},
{lvl:2,sec:"M",type:"in",q:"A graph shows drinks. Milk: 5 pictures. Juice: 2 pictures. How many more chose milk than juice?",ans:3,
 hint:"Find the gap between the rows.",expl:"5 − 2 = 3 more chose milk."},
{lvl:2,sec:"M",type:"order",q:"A graph shows pets: fish 1, dogs 4, cats 2. Put the pets in order from fewest to most.",items:["dogs","fish","cats"],ansOrder:["fish","cats","dogs"],
 expl:"Fish has 1, cats 2, dogs 4. From fewest to most: fish, cats, dogs."},
{lvl:3,sec:"M",type:"in",q:"Tomas makes a graph of 8 shapes. Circles: 3 pictures. Squares: 3 pictures. The rest are stars. How many stars?",ans:2,
 hint:"Add the circles and squares first.",expl:"3 + 3 = 6. 8 − 6 = 2 stars."},
{lvl:3,sec:"M",type:"mc",q:"In Aisha's graph, each picture is 2 cats. The cat row has 3 pictures. How many cats?",mono:true,opts:["6","3","5"],a:0,
 hint:"Each picture stands for more than one cat.",expl:"Each picture is 2 cats. 2 + 2 + 2 = 6 cats."}
],

"k-skip": [
{sec:"T",type:"in",q:"Count in twos: 2, 4, 6, 8, __",ans:10,hint:"Add 2 each time.",
 expl:"Add 2 each time. 8 + 2 = 10."},
{sec:"T",type:"in",q:"Count in tens: 10, 20, 30, __",ans:40,hint:"Add 10 each time.",
 expl:"Add 10 each time. 30 + 10 = 40."},
{sec:"T",type:"mc",q:"Which list counts in fives?",mono:true,opts:["5, 10, 15, 20","5, 6, 7, 8","2, 4, 6, 8"],a:0,
 expl:"5, 10, 15, 20 goes up by 5 each time."},
{sec:"T",type:"in",q:"Hana has 3 pairs of socks. Count in twos. How many socks?",ans:6,
 expl:"2, 4, 6. Three pairs make 6 socks."},
{lvl:2,sec:"T",type:"in",q:"Count in fives: 5, 10, 15, 20, __",ans:25,hint:"Add 5 each time.",
 expl:"Add 5 each time. 20 + 5 = 25."},
{lvl:2,sec:"T",type:"mc",q:"Which number is missing?  10, 20, __, 40",mono:true,opts:["30","25","35"],a:0,
 expl:"Counting in tens: 10, 20, 30, 40. The missing number is 30."},
{lvl:2,sec:"T",type:"in",q:"Nadia counts 4 hands. Each hand has 5 fingers. Count in fives. How many fingers?",ans:20,
 hint:"5, 10, and keep going.",expl:"5, 10, 15, 20. Four hands have 20 fingers."},
{lvl:3,sec:"T",type:"in",q:"Ingrid counts back in twos from 10: 10, 8, 6, __",ans:4,
 hint:"Going back, take 2 away each time.",expl:"Take 2 away each time. 6 − 2 = 4."},
{lvl:3,sec:"T",type:"in",q:"There are 5 bikes. Each bike has 2 wheels. Omar counts the wheels in twos. What is the last number he says?",ans:10,
 hint:"Say one number for each bike.",expl:"2, 4, 6, 8, 10. The last number is 10."},
{lvl:3,sec:"T",type:"mc",q:"Oluwaseun counts in fives from 5. Which number will she NOT say?",mono:true,opts:["12","15","20"],a:0,
 hint:"Say the list out loud.",expl:"Counting in fives: 5, 10, 15, 20. 12 is not in the list."}
],

"k-half": [
{sec:"F",type:"mc",q:"Yusuf cuts an apple into 2 pieces the same size. What is each piece called?",opts:["a half","a whole","a quarter"],a:0,
 expl:"Two equal pieces are halves. Each piece is a half."},
{sec:"F",type:"in",q:"How many halves make one whole?",ans:2,expl:"Two halves put together make one whole."},
{sec:"F",type:"in",q:"Half of 4 is __.",ans:2,hint:"Share 4 into 2 equal groups.",
 expl:"Share 4 into 2 equal groups. Each group has 2."},
{sec:"F",type:"mc",q:"A cookie is cut into 2 pieces. One piece is big, one is small. Is each piece a half?",opts:["no","yes","only the big one"],a:0,
 expl:"Halves must be the same size. These pieces are not equal, so they are not halves."},
{lvl:2,sec:"F",type:"in",q:"Half of 8 is __.",ans:4,hint:"What number and itself make 8?",
 expl:"4 + 4 = 8, so half of 8 is 4."},
{lvl:2,sec:"F",type:"in",q:"Kofi and Diego share 6 grapes. Each gets half. How many does Kofi get?",ans:3,
 hint:"Give one to each, over and over.",expl:"3 + 3 = 6. Each gets half, which is 3."},
{lvl:2,sec:"F",type:"multi",q:"Select EVERY number that can be shared into 2 equal groups with none left.",mono:true,opts:["4","6","5","3"],aMulti:[0,1],
 expl:"4 is 2 and 2. 6 is 3 and 3. 5 and 3 both leave one out."},
{lvl:3,sec:"F",type:"in",q:"Femi has 8 stickers. He gives half to Mei. Then he gives half of what is left to Leila. How many does Femi keep?",ans:2,
 hint:"Find half, then half again.",expl:"Half of 8 is 4, so 4 are left. Half of 4 is 2, so Femi keeps 2."},
{lvl:3,sec:"F",type:"mc",q:"A pizza is cut into 4 equal slices. Elias eats 2 slices. How much did he eat?",opts:["half","a quarter","all of it"],a:0,
 hint:"2 slices out of 4.",expl:"2 slices is half of the 4 slices. Elias ate half the pizza."}
],

"k-symmetry": [
{sec:"G",type:"mc",q:"A shape has a line of symmetry. What does that mean?",opts:["both sides match","it is very big","it has 3 sides"],a:0,
 expl:"Fold on the line and the two sides fit on top of each other. Both sides match."},
{sec:"G",type:"mc",q:"Which letter looks the same on both sides of a line down the middle?",opts:["A","F","J"],a:0,
 expl:"Fold A down the middle and the two halves match. F and J do not."},
{sec:"G",type:"mc",q:"Which shape has a line of symmetry?",opts:["a heart","a scribble","a letter P"],a:0,
 expl:"Fold a heart down the middle and the halves match. A scribble and a P do not."},
{sec:"G",type:"in",q:"Layla folds a paper heart in half. The two sides match. How many lines of symmetry did she find?",ans:1,
 expl:"The fold line is a line of symmetry. She found 1."},
{lvl:2,sec:"G",type:"in",q:"How many lines of symmetry does a square have?",ans:4,
 hint:"Try folding side to side, then corner to corner.",
 expl:"Two lines go through the middle of the sides, two go corner to corner. That is 4."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY letter with a line of symmetry.",opts:["H","O","T","L"],aMulti:[0,1,2],
 expl:"H, O and T can be folded so the sides match. L cannot."},
{lvl:2,sec:"G",type:"mc",q:"A butterfly has one wing with 3 spots. Its other wing matches. How many spots in all?",mono:true,opts:["6","3","4"],a:0,
 expl:"The other wing also has 3 spots. 3 + 3 = 6."},
{lvl:3,sec:"G",type:"in",q:"How many lines of symmetry does a rectangle that is not a square have?",ans:2,
 hint:"Corner to corner does not work here.",
 expl:"One line across the middle and one down the middle. Corner to corner does not match. That is 2."},
{lvl:3,sec:"G",type:"in",q:"Mei's paper has a line of symmetry down the middle. The left side has 4 dots and 1 star. How many dots and stars in all?",ans:10,
 hint:"The right side is a match of the left side.",
 expl:"The right side matches: 4 dots and 1 star. Left has 5 things, right has 5. 5 + 5 = 10."}
],

"k-blocks": [
{sec:"G",type:"in",q:"A yellow hexagon has 6 sides. How many green triangles fit inside it?",ans:6,
 expl:"Six triangles fit together to fill one hexagon."},
{sec:"G",type:"in",q:"How many red trapezoids make one yellow hexagon?",ans:2,
 expl:"A trapezoid is half a hexagon. Two of them fill it."},
{sec:"G",type:"mc",q:"Which block has 3 sides?",opts:["triangle","hexagon","square"],a:0,
 expl:"A triangle has 3 sides. A square has 4 and a hexagon has 6."},
{lvl:2,sec:"G",type:"in",q:"How many blue rhombus blocks fill one hexagon?",ans:3,
 hint:"A blue rhombus is 2 green triangles.",expl:"A blue rhombus is 2 triangles. Three of them make 6 triangles, which is one hexagon."},
{lvl:2,sec:"G",type:"in",q:"Farah fills a hexagon with 1 trapezoid and some green triangles. How many green ones does she need?",ans:3,
 hint:"The trapezoid fills half.",expl:"A trapezoid is half a hexagon. The other half is 3 triangles."},
{lvl:2,sec:"G",type:"mc",q:"Which set of blocks covers one red trapezoid exactly?",opts:["3 triangles","2 squares","2 hexagons"],a:0,
 expl:"A trapezoid is half a hexagon, and a hexagon is 6 triangles. So a trapezoid is 3 triangles."},
{lvl:2,sec:"G",type:"order",q:"Put the blocks in order from fewest sides to most sides.",items:["hexagon","square","triangle"],ansOrder:["triangle","square","hexagon"],
 expl:"A triangle has 3 sides, a square 4, a hexagon 6."},
{lvl:3,sec:"G",type:"in",q:"Tariq covers 2 hexagons. He uses 1 red trapezoid and green triangles only. How many green ones does he use?",ans:9,
 hint:"How many triangles fill 2 hexagons? The trapezoid takes the place of 3.",
 expl:"Two hexagons need 12 triangles. A trapezoid is 3 triangles, so 12 − 3 = 9 green triangles."},
{lvl:3,sec:"G",type:"in",q:"Rosa joins 2 hexagons along one side. How many sides does the new shape have?",ans:10,
 hint:"The joined sides are hidden inside.",expl:"Each hexagon has 6 sides. The 2 joined sides are hidden. 6 + 6 − 2 = 10 sides."}
],

"k-turns": [
{sec:"G",type:"mc",q:"Nim faces the door. Nim turns all the way around. Which way does Nim face now?",opts:["the door","the window","the wall"],a:0,
 expl:"A full turn brings you back to where you started. Nim faces the door again."},
{sec:"G",type:"mc",q:"A letter b is flipped over a line to its right. What does it look like?",opts:["d","p","q"],a:0,
 expl:"Flipping b side to side makes it face the other way: d."},
{sec:"G",type:"mc",q:"Hugo faces the tree. He makes a half turn. What is he facing now?",opts:["away from the tree","the tree","a little to the left"],a:0,
 expl:"A half turn makes you face the other way, so his back is to the tree."},
{lvl:2,sec:"G",type:"mc",q:"An arrow points up. It is turned a half turn. Which way does it point now?",opts:["down","left","up"],a:0,
 expl:"A half turn spins the arrow to face the other way: down."},
{lvl:2,sec:"G",type:"mc",q:"An arrow points up. Anya gives it a quarter turn to the right. Which way does it point?",opts:["right","left","down"],a:0,
 expl:"A quarter turn to the right moves the tip from up to right."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY move that is a flip.",opts:["turning a page over","looking in a mirror","spinning a top","rolling a ball"],aMulti:[0,1],
 expl:"A flip turns a shape over, like a page or a mirror picture. Spinning and rolling are turns."},
{lvl:2,sec:"G",type:"in",q:"How many quarter turns make one full turn?",ans:4,hint:"Four quarters make a whole.",
 expl:"Four quarter turns bring you back to the start."},
{lvl:3,sec:"G",type:"mc",q:"A letter p is flipped top to bottom. What letter does it look like?",opts:["b","q","d"],a:0,
 hint:"The tail moves up.",expl:"Flipping p top to bottom moves the tail up. It looks like b."},
{lvl:3,sec:"G",type:"mc",q:"Malik faces the tree. He makes a quarter turn right, then another quarter turn right. What does he face?",opts:["away from the tree","the tree","the sky"],a:0,
 hint:"Two quarter turns make what?",expl:"Two quarter turns make a half turn. Malik now faces away from the tree."},
{lvl:3,sec:"G",type:"in",q:"Nim makes 3 quarter turns to the right. How many more quarter turns to get back to the start?",ans:1,
 hint:"A full turn is 4 quarter turns.",expl:"Four quarter turns make a full turn. 3 + 1 = 4, so 1 more."}
],

"k-trees": [
{sec:"K",type:"in",q:"A tree diagram starts with 2 hats. Each hat branches to 2 scarves. How many ends does the tree have?",ans:4,
 hint:"Count the ends under each hat.",expl:"Each of the 2 hats has 2 scarf branches. 2 + 2 = 4 ends."},
{sec:"K",type:"mc",q:"Chioma draws a tree. First she picks milk or juice. How many branches come from the start?",mono:true,opts:["2","1","3"],a:0,
 expl:"There are 2 drinks to pick, so 2 branches."},
{sec:"K",type:"in",q:"Emeka picks a ball: red, blue or green. He draws a tree. How many branches from the start?",ans:3,
 expl:"One branch for each colour: red, blue, green. That is 3."},
{sec:"K",type:"mc",q:"A tree shows: hat then scarf. Which is picked first?",opts:["the hat","the scarf","both at once"],a:0,
 expl:"The tree reads from the start. The hat comes first, then the scarf."},
{lvl:2,sec:"K",type:"in",q:"Isla picks 1 of 3 tops and 1 of 2 skirts. Her tree has 3 branches, each with 2 more. How many ends?",ans:6,
 hint:"Count 2 for each top.",expl:"3 branches, each with 2 ends: 2 + 2 + 2 = 6 outfits."},
{lvl:2,sec:"K",type:"mc",q:"A tree: first ice cream or cake, then a spoon or a fork. Which is one end of the tree?",opts:["cake with a fork","cake with ice cream","a spoon with a fork"],a:0,
 expl:"One end pairs a food with a tool. Cake with a fork is one end. The others pair two foods or two tools."},
{lvl:2,sec:"K",type:"order",q:"Put the steps of drawing a tree in order, first to last.",
 items:["draw the second choice branches","draw the first choice branches","count the ends","draw the start dot"],
 ansOrder:["draw the start dot","draw the first choice branches","draw the second choice branches","count the ends"],
 expl:"Start with a dot, add the first branches, then the second, then count the ends."},
{lvl:3,sec:"K",type:"in",q:"Arjun's tree has 2 branches for bread. Each bread has 3 fillings. How many sandwiches can he make?",ans:6,
 hint:"Each bread branch has 3 ends.",expl:"Each bread has 3 ends. 3 + 3 = 6 sandwiches."},
{lvl:3,sec:"K",type:"in",q:"Zara's tree has 4 ends. Each first branch splits into 2. How many first branches are there?",ans:2,
 hint:"Each first branch makes 2 ends. How many twos make 4?",expl:"Each first branch gives 2 ends. 2 + 2 = 4, so there are 2 first branches."},
{lvl:3,sec:"K",type:"mc",q:"Jin flips a coin twice. His tree shows heads or tails each time. How many ends show heads twice?",mono:true,opts:["1","2","4"],a:0,
 hint:"List all four ends.",expl:"The ends are HH, HT, TH, TT. Only HH has heads twice: 1."}
],

"k-games": [
{sec:"P",type:"mc",q:"Tic-tac-toe: Ines has 2 Xs in a row. One spot in that row is empty. What should she do?",opts:["put an X there","put an X far away","skip her turn"],a:0,
 expl:"Three in a row wins. Filling the empty spot wins the game."},
{sec:"P",type:"in",q:"There are 2 counters. You may take 1 or 2. Taking the last counter wins. How many should you take?",ans:2,
 hint:"Can you take the last one right now?",expl:"Take both. None are left, so you took the last one and win."},
{sec:"P",type:"mc",q:"Kwame and Sana take turns saying 1 or 2 more. The one who says 5 wins. Kwame says 4. What should Sana say?",mono:true,opts:["5","6","4"],a:0,
 expl:"After 4 comes 5. Sana says 5 and wins."},
{sec:"P",type:"mc",q:"In a game, you win by getting to 10 first. You are on 8. You can add 1 or 2. What do you add?",mono:true,opts:["2","1","0"],a:0,
 expl:"8 + 2 = 10. Adding 2 gets you to 10 right now."},
{lvl:2,sec:"P",type:"in",q:"Counters game: 4 counters. Take 1 or 2 each turn. Last counter wins. Take how many now so you win next turn?",ans:1,
 hint:"Leave 3. Then whatever they take, you can take the rest.",
 expl:"Take 1 and leave 3. If they take 1, you take 2. If they take 2, you take 1. You take the last one."},
{lvl:2,sec:"P",type:"mc",q:"Race to 10: add 1 or 2 each turn. Saying 10 wins. Nikolai says 6. What should Noor say?",mono:true,opts:["7","8","10"],a:0,
 hint:"From 8 or 9, the other player can reach 10.",expl:"Say 7. Then Nikolai says 8 or 9, and either way Noor can say 10."},
{lvl:2,sec:"P",type:"mc",q:"Tic-tac-toe: Ana has 2 Os in the top row. It is Ben's turn. What should Ben do?",opts:["block the top row","take the middle","take a corner"],a:0,
 expl:"If Ana gets 3 in a row she wins. Ben must fill the last top spot to block."},
{lvl:2,sec:"P",type:"multi",q:"Race to 10: add 1 or 2 each turn. Omar says 5. Select EVERY number Lee can say next.",mono:true,opts:["6","7","8","5"],aMulti:[0,1],
 expl:"Adding 1 gives 6, adding 2 gives 7. Lee cannot add 3 or 0."},
{lvl:3,sec:"P",type:"in",q:"Counters game: 5 counters. Take 1 or 2 each turn. The last counter wins. It is your turn. How many should you take?",ans:2,
 hint:"Leave a pile that the other player cannot win from.",
 expl:"Take 2 to leave 3. Whatever they take, you can take the rest and get the last counter."},
{lvl:3,sec:"P",type:"in",q:"Race to 10: add 1 or 2 each turn. Saying 10 wins. Sana goes first. Which number should she say?",ans:1,
 hint:"Work back from 10: which numbers must she land on?",
 expl:"Say 1, then 4, then 7, then 10. From each one, she can reach the next no matter what."},
{lvl:3,sec:"P",type:"mc",q:"Tic-tac-toe: X is in the middle. It is O's first turn. Which spot is safest for O?",opts:["a corner","a side","there is no safe spot"],a:0,
 hint:"Think about where X could make two lines at once.",
 expl:"Taking a corner stops X from setting up two lines at once. A side lets X win."}
]
};
