/* Kindergarten banks. Language kept short and concrete; numbers stay small
   enough to work out with fingers or counters. */
export const K_BANKS = {
"k-count": [
{sec:"N",type:"in",q:"What number comes right after 7?",ans:8,hint:"Count on from 7.",
 expl:"Counting up: 6, 7, then 8. So 8 comes right after 7."},
{sec:"N",type:"in",q:"What number comes right after 15?",ans:16,hint:"Count on from 15.",
 expl:"After 15 comes 16."},
{sec:"N",type:"mc",q:"Which number is missing?  4, 5, __, 7",mono:true,opts:["6","8","3","9"],a:0,
 expl:"Counting 4, 5, 6, 7 — the missing number is 6."},
{sec:"N",type:"in",q:"How many is 10 and 1 more?",ans:11,hint:"Count on one from 10.",
 expl:"One more than 10 is 11."},
{sec:"N",type:"mc",q:"Which number is missing?  17, 18, __, 20",mono:true,opts:["19","16","21","15"],a:0,
 expl:"Counting 17, 18, 19, 20 — the missing number is 19."},
{lvl:2,sec:"N",type:"in",q:"What number comes right after 29?",ans:30,hint:"A new ten begins.",
 expl:"After 29 the next ten starts, so it is 30."},
{lvl:2,sec:"N",type:"order",q:"Put these numbers in order, smallest first.",
 items:["12","8","20","15"],ansOrder:["8","12","15","20"],
 expl:"Counting up: 8, then 12, then 15, then 20."},
{lvl:3,sec:"N",type:"in",q:"Start at 10 and count on 5 more. Where do you land?",ans:15,
 hint:"11, 12, 13...",expl:"10, then 11, 12, 13, 14, 15. You land on 15."}
],

"k-countback": [
{sec:"N",type:"in",q:"What number comes right before 9?",ans:8,hint:"Count back one.",
 expl:"Counting back from 9 gives 8."},
{sec:"N",type:"in",q:"Count back: 20, 19, 18, __",ans:17,expl:"Counting back one from 18 gives 17."},
{sec:"N",type:"mc",q:"Which number is missing?  12, 11, __, 9",mono:true,opts:["10","13","8","7"],a:0,
 expl:"Counting back 12, 11, 10, 9 — the missing number is 10."},
{lvl:2,sec:"N",type:"in",q:"Start at 15 and count back 3. Where do you land?",ans:12,
 hint:"14, 13...",expl:"15, then 14, 13, 12. You land on 12."},
{lvl:3,sec:"N",type:"order",q:"Put these in order, largest first.",
 items:["7","13","2","19"],ansOrder:["19","13","7","2"],
 expl:"Counting down: 19, then 13, then 7, then 2."}
],

"k-add10": [
{sec:"N",type:"in",q:"3 + 2 = ?",ans:5,hint:"Hold up 3 fingers, then 2 more.",
 expl:"3 and 2 more makes 5."},
{sec:"N",type:"in",q:"4 + 4 = ?",ans:8,expl:"4 and 4 more makes 8. This one is a double."},
{sec:"N",type:"in",q:"6 + 1 = ?",ans:7,hint:"One more than 6.",expl:"Adding 1 just counts on once: 7."},
{sec:"N",type:"in",q:"5 + 3 = ?",ans:8,expl:"Start at 5 and count on 3: 6, 7, 8."},
{sec:"N",type:"mc",q:"Which makes 10?",mono:true,opts:["7 + 3","7 + 2","6 + 3","8 + 4"],a:0,
 expl:"7 + 3 = 10. The others give 9, 9 and 12."},
{lvl:2,sec:"N",type:"in",q:"2 + 3 + 4 = ?",ans:9,hint:"Add two of them first.",
 expl:"2 + 3 = 5, then 5 + 4 = 9."},
{lvl:2,sec:"N",type:"multi",q:"Select EVERY pair that makes 8.",
 opts:["5 + 3","4 + 4","6 + 1","2 + 6"],aMulti:[0,1,3],
 expl:"5 + 3, 4 + 4 and 2 + 6 all make 8. 6 + 1 makes 7."},
{lvl:3,sec:"N",type:"in",q:"I have 4 apples. My friend gives me some more and now I have 9. How many did my friend give me?",
 ans:5,hint:"What do you add to 4 to reach 9?",expl:"4 + 5 = 9, so the friend gave 5 apples."}
],

"k-sub10": [
{sec:"N",type:"in",q:"7 − 2 = ?",ans:5,hint:"Start at 7 and count back 2.",
 expl:"7, then 6, 5. So 7 − 2 = 5."},
{sec:"N",type:"in",q:"9 − 4 = ?",ans:5,expl:"Counting back 4 from 9: 8, 7, 6, 5."},
{sec:"N",type:"in",q:"6 − 6 = ?",ans:0,hint:"Take away all of them.",
 expl:"Taking all 6 away leaves nothing, which is 0."},
{sec:"N",type:"in",q:"You have 8 grapes and eat 3. How many are left?",ans:5,
 expl:"8 − 3 = 5 grapes left."},
{lvl:2,sec:"N",type:"in",q:"10 − 4 = ?",ans:6,expl:"Counting back 4 from 10 gives 6."},
{lvl:2,sec:"N",type:"mc",q:"Which one leaves 3?",mono:true,opts:["8 − 5","9 − 5","7 − 5","6 − 2"],a:0,
 expl:"8 − 5 = 3. The others give 4, 2 and 4."},
{lvl:3,sec:"N",type:"in",q:"There were some birds on a branch. 3 flew away and 4 are left. How many were there at first?",
 ans:7,hint:"Put the ones that left back.",expl:"4 left plus the 3 that flew away makes 7 at the start."}
],

"k-evenodd": [
{sec:"N",type:"mc",q:"Is 6 even or odd?",opts:["Even","Odd"],a:0,
 expl:"6 counters pair up exactly with none left over, so 6 is even."},
{sec:"N",type:"mc",q:"Is 9 even or odd?",opts:["Odd","Even"],a:0,
 expl:"9 counters make 4 pairs with 1 left over, so 9 is odd."},
{sec:"N",type:"multi",q:"Select EVERY even number.",opts:["2","5","8","11","10"],aMulti:[0,2,4],
 expl:"2, 8 and 10 pair up exactly. 5 and 11 each leave one over."},
{lvl:2,sec:"N",type:"mc",q:"You have 7 socks. Can every sock find a partner?",
 opts:["No, one is left over","Yes, all of them"],a:0,
 expl:"7 is odd, so after 3 pairs there is 1 sock with no partner."},
{lvl:3,sec:"N",type:"mc",q:"Is the number of legs on 3 cats even or odd?",opts:["Even","Odd"],a:0,
 expl:"Each cat has 4 legs, so 3 cats have 12 legs. 12 pairs up exactly, so it is even."}
],

"k-2d": [
{sec:"G",type:"mc",q:"How many sides does a triangle have?",mono:true,opts:["3","4","5","2"],a:0,
 expl:"A triangle has 3 straight sides and 3 corners."},
{sec:"G",type:"mc",q:"How many corners does a square have?",mono:true,opts:["4","3","5","0"],a:0,
 expl:"A square has 4 corners and 4 sides, all the same length."},
{sec:"G",type:"mc",q:"Which shape has no straight sides at all?",opts:["Circle","Square","Triangle","Hexagon"],a:0,
 expl:"A circle is one curved line all the way round — no straight sides and no corners."},
{sec:"G",type:"mc",q:"How many sides does a hexagon have?",mono:true,opts:["6","5","7","4"],a:0,
 expl:"A hexagon has 6 sides. 'Hex' means six."},
{lvl:2,sec:"G",type:"multi",q:"Select EVERY shape that has 4 sides.",
 opts:["Square","Rectangle","Triangle","Rhombus"],aMulti:[0,1,3],
 expl:"Squares, rectangles and rhombuses all have 4 sides. A triangle has 3."},
{lvl:3,sec:"G",type:"in",q:"A triangle and a square are put side by side. How many corners are there altogether?",
 ans:7,hint:"Count each shape's corners, then add.",
 expl:"A triangle has 3 corners and a square has 4. Together that is 3 + 4 = 7."}
],

"k-compose": [
{sec:"N",type:"in",q:"5 is made of 2 and ___. What number completes it?",ans:3,
 expl:"2 and 3 together make 5."},
{sec:"N",type:"in",q:"How many more do you need to make 10, if you have 6?",ans:4,
 expl:"6 and 4 more make 10."},
{sec:"N",type:"mc",q:"Which pair makes 7?",opts:["3 and 4","2 and 4","5 and 3","6 and 2"],a:0,
 expl:"3 and 4 together make 7."},
{sec:"N",type:"in",q:"8 is made of 5 and ___.",ans:3,expl:"5 and 3 together make 8."},
{sec:"N",type:"mc",q:"Which pair makes 10?",opts:["6 and 4","5 and 4","7 and 2","8 and 3"],a:0,
 expl:"6 and 4 together make 10."},
{lvl:2,sec:"N",type:"in",q:"One way to make 6 is 1 and 5. Another way is 2 and ___.",ans:4,
 expl:"2 and 4 together also make 6."},
{lvl:2,sec:"N",type:"in",q:"9 is made of 4 and ___.",ans:5,expl:"4 and 5 together make 9."},
{lvl:3,sec:"N",type:"in",q:"You have 10 counters split into two groups. One group has 2 more than the other. How many are in the SMALLER group?",
 ans:4,hint:"Try two numbers that differ by 2 and add to 10.",
 expl:"4 and 6 add to 10, and 6 is 2 more than 4. The smaller group has 4."}
],

"k-3d": [
{sec:"G",type:"mc",q:"Which shape is a SOLID shape you could hold?",opts:["A cube","A circle","A triangle","A square"],a:0,
 expl:"A cube is a solid you can pick up. Circles, triangles and squares are flat."},
{sec:"G",type:"mc",q:"A ball is shaped like a ___.",opts:["sphere","cube","cylinder","cone"],a:0,
 expl:"A sphere is perfectly round all the way around, like a ball."},
{sec:"G",type:"mc",q:"A can of soup is shaped like a ___.",opts:["cylinder","sphere","cube","cone"],a:0,
 expl:"A cylinder has two flat circle ends and a curved side, like a can."},
{sec:"G",type:"mc",q:"Which of these is FLAT, not solid?",opts:["A circle","A cube","A sphere","A cylinder"],a:0,
 expl:"A circle is flat. The others are all solid shapes you could hold."},
{sec:"G",type:"mc",q:"An ice cream cone shape is called a ___.",opts:["cone","cube","sphere","cylinder"],a:0,
 expl:"A cone has one point and a flat circle base, like an ice cream cone."},
{lvl:2,sec:"G",type:"mc",q:"A box shaped like a square on every side is a ___.",opts:["cube","sphere","cone","cylinder"],a:0,
 expl:"A cube has 6 square faces, all the same size."},
{lvl:2,sec:"G",type:"mc",q:"Which solid shape can roll AND stack, like a can?",opts:["Cylinder","Sphere","Cube","Cone"],a:0,
 expl:"A cylinder's flat ends let it stack, and its curved side lets it roll."},
{lvl:3,sec:"G",type:"mc",q:"Which shape has NO flat faces at all?",opts:["Sphere","Cube","Cylinder","Cone"],a:0,
 expl:"A sphere is curved all over — it has no flat parts anywhere."}
],

"k-combine": [
{sec:"G",type:"mc",q:"Two matching triangles put together can make a ___.",
 opts:["square","circle","one triangle","nothing"],a:0,expl:"Two matching triangles joined along one side can make a square or rectangle."},
{sec:"G",type:"mc",q:"Putting two shapes together to make a new shape is called ___.",
 opts:["putting them together","taking them apart","coloring them","erasing them"],a:0,
 expl:"Building a new shape from smaller ones is putting shapes together."},
{sec:"G",type:"mc",q:"Which two shapes can join to make a rectangle?",
 opts:["Two matching triangles","Two circles","Two ovals","Two dots"],a:0,
 expl:"Two matching triangles joined along their longest side fit together into a rectangle."},
{sec:"G",type:"mc",q:"You join a small triangle to the top of a square. What could you build?",
 opts:["A house shape","A circle","A dot","A line"],a:0,expl:"A triangle roof on a square makes a house shape."},
{sec:"G",type:"mc",q:"Which is an example of combining shapes?",
 opts:["Joining two shapes to build a new one","Coloring in a shape","Naming a shape","Erasing a shape"],a:0,
 expl:"Combining means joining pieces together to build something new."},
{lvl:2,sec:"G",type:"mc",q:"A big triangle is split evenly into 4 small ones. How many small triangles are there?",
 opts:["4","2","3","1"],a:0,expl:"Splitting one triangle evenly into 4 parts makes 4 small triangles."},
{lvl:2,sec:"G",type:"mc",q:"Which combination makes a bigger square from 4 smaller squares?",
 opts:["2 rows of 2 squares","1 row of 4 squares","3 triangles","2 circles"],a:0,
 expl:"Arranging 4 small squares as 2 rows of 2 builds one bigger square."},
{lvl:3,sec:"G",type:"mc",q:"You build one shape from 2 triangles and 1 square. How many shapes did you combine in total?",
 opts:["3","2","1","4"],a:0,expl:"2 triangles plus 1 square is 3 shapes combined."}
],

"k-compare": [
{sec:"M",type:"mc",q:"Which is BIGGER?",opts:["An elephant","A mouse","A pencil","A coin"],a:0,
 expl:"An elephant is much bigger than the other three."},
{sec:"M",type:"mc",q:"Which is HEAVIER?",opts:["A rock","A feather","A leaf","A piece of paper"],a:0,
 expl:"A rock weighs far more than a feather, leaf or paper."},
{sec:"M",type:"mc",q:"Which is LONGER?",opts:["A snake","A coin","A button","A paperclip"],a:0,
 expl:"A snake is much longer than the other three small objects."},
{sec:"M",type:"mc",q:"Which is SMALLER?",opts:["An ant","A dog","A car","A house"],a:0,
 expl:"An ant is far smaller than the other three."},
{sec:"M",type:"mc",q:"Which is LIGHTER?",opts:["A feather","A brick","A rock","A book"],a:0,
 expl:"A feather weighs far less than the other three."},
{lvl:2,sec:"M",type:"mc",q:"You lift two boxes. The one that is harder to lift is ___.",
 opts:["heavier","lighter","smaller","the same"],a:0,expl:"A box that is harder to lift weighs more — it is heavier."},
{lvl:2,sec:"M",type:"mc",q:"Which word means 'has more length'?",
 opts:["longer","heavier","bigger in weight","louder"],a:0,expl:"'Longer' compares length, not weight or sound."},
{lvl:3,sec:"M",type:"mc",q:"A feather, a rock and a leaf are compared. Order them from LIGHTEST to heaviest.",mono:true,
 opts:["Feather, leaf, rock","Rock, leaf, feather","Leaf, rock, feather","Rock, feather, leaf"],a:0,
 expl:"A feather is lightest, a leaf is a bit heavier, and a rock is heaviest."}
],

"k-sort": [
{sec:"M",type:"mc",q:"You sort a pile of buttons by color. Which is a good rule?",
 opts:["Red buttons together, blue buttons together","Buttons named Sam","Buttons that fly","Buttons made of cheese"],a:0,
 expl:"Sorting by color groups buttons that share a real feature."},
{sec:"M",type:"in",q:"You sort 10 shapes into circles and squares. There are 6 circles. How many squares?",
 ans:4,expl:"10 − 6 = 4 squares."},
{sec:"M",type:"mc",q:"Which is a good sorting rule for animals?",
 opts:["Animals with 4 legs vs animals without","Animals that like pizza","Animals that are Tuesdays","Animals that are numbers"],a:0,
 expl:"Number of legs is a real, observable feature you can sort by."},
{sec:"M",type:"in",q:"You sort toys into 2 groups: cars (7) and blocks (5). How many toys in total?",
 ans:12,expl:"7 + 5 = 12 toys."},
{sec:"M",type:"mc",q:"After sorting objects into groups, what do you usually do next?",
 opts:["Count each group's objects","Throw the objects away","Paint the objects","Hide the objects"],a:0,
 expl:"Sorting is usually followed by counting each group to compare them."},
{lvl:2,sec:"M",type:"in",q:"You sort 15 buttons into 3 equal color groups. How many buttons in each group?",
 ans:5,expl:"15 ÷ 3 = 5 buttons per group."},
{lvl:2,sec:"M",type:"mc",q:"Which category has the MOST, if red = 4, blue = 7, green = 3?",mono:true,
 opts:["Blue","Red","Green","They're equal"],a:0,expl:"7 is more than 4 or 3, so blue has the most."},
{lvl:3,sec:"M",type:"in",q:"You sort 20 objects into two groups. One group has 8 more than the other. How many are in the SMALLER group?",
 ans:6,hint:"Try two numbers that differ by 8 and add to 20.",
 expl:"6 and 14 add to 20, and 14 is 8 more than 6. The smaller group has 6."}
],

"k-picgraph": [
{sec:"M",type:"in",q:"A picture graph shows 3 pictures of suns. Each picture equals 1 day. How many days?",
 ans:3,expl:"3 pictures, 1 day each, means 3 days."},
{sec:"M",type:"in",q:"A picture graph shows: apples = 4 pictures, bananas = 2 pictures. How many MORE apple pictures?",
 ans:2,expl:"4 − 2 = 2 more apple pictures."},
{sec:"M",type:"mc",q:"In a picture graph, more pictures in a row means ___.",
 opts:["a bigger count","a smaller count","nothing","it never changes"],a:0,
 expl:"Each picture stands for one, so more pictures means a bigger amount."},
{sec:"M",type:"in",q:"A picture graph shows cats = 5, dogs = 3. How many pets in total?",
 ans:8,expl:"5 + 3 = 8 pets."},
{sec:"M",type:"mc",q:"Which question can a picture graph answer?",
 opts:["Which group has more?","What color is it?","How old are you?","What day is it?"],a:0,
 expl:"A picture graph compares groups by count, so it can show which has more."},
{lvl:2,sec:"M",type:"in",q:"A picture graph shows 3 categories: 2, 5, and 3 pictures. What is the total?",
 ans:10,expl:"2 + 5 + 3 = 10."},
{lvl:2,sec:"M",type:"in",q:"A picture graph shows fish = 6, birds = 2. How many MORE fish than birds?",
 ans:4,expl:"6 − 2 = 4 more fish."},
{lvl:3,sec:"M",type:"mc",q:"A picture graph shows 4 fruits: apples = 3, pears = 5, grapes = 2, plums = 6. Which two fruits add up to exactly 7?",
 opts:["Grapes and pears","Apples and plums","Apples and pears","Plums and pears"],a:0,
 expl:"Grapes (2) + pears (5) = 7. The other pairs add to 9, 8 and 11."}
]
};
