/* Prerequisite knowledge graph (spec 6.2).

   Each entry lists the topics a learner should hold before a topic is
   worth attempting. Edges are authored rather than inferred from grade
   order, because the real dependencies cut across grades and strands —
   modular arithmetic needs division with remainders, combinatorics needs
   the multiplication principle, and neither follows from being "the next
   grade up".

   The graph must stay acyclic; requirements/checks.mjs enforces that. */

export const PREREQS = {
  /* ---- counting and early number ---- */
  "k-countback":  ["k-count"],
  "k-ordinal":    ["k-count"],
  "k-add10":      ["k-count"],
  "k-sub10":      ["k-add10"],
  "k-compose":    ["k-add10"],
  "k-evenodd":    ["k-count"],
  "k-skip":       ["k-count"],
  "k-half":       ["k-compose"],
  "k-combos":     ["k-count"],
  "k-trees":      ["k-combos"],
  "k-3d":         ["k-2d"],
  "k-compare":    ["k-sort"],
  "k-symmetry":   ["k-2d"],
  "k-combine":    ["k-2d"],
  "k-turns":      ["k-symmetry"],
  "k-blocks":     ["k-2d", "k-patterns"],
  "k-games":      ["k-count", "k-logic"],
  "k-picgraph":   ["k-sort"],

  /* ---- grade 1 ---- */
  "g1-attrib":    ["k-2d", "k-3d"],
  "g1-add20":     ["k-add10"],
  "g1-sub20":     ["k-sub10", "g1-add20"],
  "g1-equals":    ["g1-add20"],
  "g1-wordprob":  ["g1-add20", "g1-sub20"],
  "g1-props":     ["g1-add20"],
  "g1-tensones":  ["k-count"],
  "g1-compare2":  ["g1-tensones"],
  "g1-add100":    ["g1-tensones", "g1-add20"],
  "g1-tenmore":   ["g1-tensones"],
  "g1-shares":    ["k-half"],
  "g1-compose":   ["k-combine"],
  "g1-evenodd":   ["k-evenodd", "g1-tensones"],
  "g1-factors":   ["g1-evenodd"],
  "g1-div25":     ["k-skip", "g1-evenodd"],
  "g1-machines":  ["g1-add20"],
  "g1-growing":   ["k-patterns", "g1-add20"],
  "g1-grid":      ["k-logic"],
  "g1-deduce":    ["k-logic"],
  "g1-twostep":   ["g1-wordprob"],
  "g1-arrange":   ["k-combos"],
  "g1-choose":    ["g1-arrange"],

  /* ---- grade 2 ---- */
  "g2-fluency":   ["g1-add20", "g1-sub20"],
  "g2-add100":    ["g1-add100"],
  "g2-equalgrp":  ["k-skip", "g2-fluency"],
  "g2-arrays":    ["g2-equalgrp"],
  "g2-place1000": ["g1-tensones"],
  "g2-compare3":  ["g2-place1000", "g1-compare2"],
  "g2-add1000":   ["g2-place1000", "g2-add100"],
  "g2-mental":    ["g2-place1000", "g1-tenmore"],
  "g2-rulers":    ["g1-length"],
  "g2-estimate":  ["g2-rulers"],
  "g2-time5":     ["g1-time"],
  "g2-money":     ["g1-coins", "g2-add100"],
  "g2-lineplot":  ["g2-rulers", "g1-graphs"],
  "g2-thirds":    ["g1-shares"],
  "g2-rowcol":    ["g2-arrays"],
  "g2-prime20":   ["g1-factors"],
  "g2-divrules":  ["g1-div25"],
  "g2-gcf":       ["g1-factors"],
  "g2-repeated":  ["g2-equalgrp"],
  "g2-sharing":   ["g2-repeated"],
  "g2-multprob":  ["g2-repeated"],
  "g2-missing":   ["g1-equals"],
  "g2-symbols":   ["g2-missing"],
  "g2-rule":      ["g1-machines"],
  "g2-trees":     ["k-trees", "g2-repeated"],
  "g2-perm4":     ["g1-arrange"],
  "g2-permcomb":  ["g2-perm4", "g1-choose"],
  "g2-perimeter": ["g2-rulers", "g2-add100"],
  "g2-symmetry":  ["k-symmetry"],
  "g2-tangram":   ["g1-compose"],

  /* ---- grade 3 ---- */
  "g3-mult":      ["g2-repeated", "g2-arrays"],
  "g3-div":       ["g3-mult", "g2-sharing"],
  "g3-multprops": ["g3-mult"],
  "g3-twostep":   ["g3-mult", "g3-div", "g1-twostep"],
  "g3-patterns":  ["g3-mult", "g2-rule"],
  "g3-round":     ["g2-place1000"],
  "g3-add1000":   ["g2-add1000"],
  "g3-mult10":    ["g3-mult", "g2-place1000"],
  "g3-fracnum":   ["g2-thirds"],
  "g3-fraccomp":  ["g3-fracnum"],
  "g3-fraceq":    ["g3-fracnum", "g3-mult"],
  "g3-wholefrac": ["g3-fracnum"],
  "g3-timemin":   ["g2-time5"],
  "g3-volmass":   ["g2-estimate"],
  "g3-scaled":    ["g2-lineplot", "g3-mult"],
  "g3-area":      ["g2-rowcol", "g3-mult"],
  "g3-perimeter": ["g2-perimeter"],
  "g3-areaperim": ["g3-area", "g3-perimeter"],
  "g3-quads":     ["g2-polygons"],
  "g3-equalarea": ["g3-area", "g3-fracnum"],
  "g3-primefact": ["g2-prime20", "g3-mult"],
  "g3-divrules":  ["g2-divrules", "g3-div"],
  "g3-lcm":       ["g3-mult", "k-skip"],
  "g3-gcdlcm":    ["g3-primefact", "g3-lcm", "g2-gcf"],
  "g3-fracadd":   ["g3-fracnum"],
  "g3-fracmultw": ["g3-fracnum", "g3-mult"],
  "g3-benchmark": ["g3-fraccomp"],
  "g3-simpleeq":  ["g2-symbols", "g3-mult"],
  "g3-varpat":    ["g3-patterns", "g2-symbols"],
  "g3-evaluate":  ["g3-simpleeq"],
  "g3-syslist":   ["g2-trees"],
  "g3-multprin":  ["g3-syslist", "g3-mult"],
  "g3-composite": ["g3-area"],
  "g3-volpack":   ["g3-area"],
  "g3-angles":    ["g2-polygons"],
  "g3-lines":     ["g3-angles"],

  /* ---- grade 4 ---- */
  "g4-multcomp":  ["g3-mult"],
  "g4-multistep": ["g3-twostep"],
  "g4-factorpair":["g3-primefact"],
  "g4-seq":       ["g3-patterns"],
  "g4-placemil":  ["g3-round"],
  "g4-multidig":  ["g3-mult10", "g4-placemil"],
  "g4-divide":    ["g3-div", "g4-multidig"],
  "g4-fracadd":   ["g3-fracadd"],
  "g4-mixed":     ["g4-fracadd", "g3-wholefrac"],
  "g4-fracmultw": ["g3-fracmultw"],
  "g4-decnot":    ["g3-fracnum", "g4-placemil"],
  "g4-deccomp":   ["g4-decnot"],
  "g4-units":     ["g3-volmass"],
  "g4-areaform":  ["g3-areaperim"],
  "g4-lineplot":  ["g3-scaled", "g3-fracnum"],
  "g4-protract":  ["g3-angles"],
  "g4-linesrays": ["g3-lines"],
  "g4-classify":  ["g3-quads", "g4-linesrays"],
  "g4-symmetry":  ["g2-symmetry", "g4-classify"],
  "g4-primefact": ["g3-primefact"],
  "g4-divrules":  ["g3-divrules"],
  "g4-clockmod":  ["g4-divide"],                    // spec: modular needs division with remainders
  "g4-euclid":    ["g3-gcdlcm", "g4-divide"],
  "g4-evalexpr":  ["g3-evaluate"],
  "g4-liketerms": ["g4-evalexpr"],
  "g4-onestep":   ["g3-simpleeq", "g4-evalexpr"],
  "g4-inequal":   ["g4-onestep"],
  "g4-writeeq":   ["g4-onestep", "g4-multistep"],
  "g4-factorial": ["g3-multprin", "g2-perm4"],
  "g4-combin":    ["g4-factorial", "g2-permcomb"],
  "g4-paths":     ["g4-combin"],
  "g4-starsbars": ["g4-combin"],
  "g4-tri-area":  ["g4-areaform"],
  "g4-para-area": ["g4-tri-area"],
  "g4-circle":    ["g4-areaform"],
  "g4-nets":      ["g4-areaform", "g3-composite"],
  "g4-volprism":  ["g3-volpack", "g4-areaform"],
  "g4-exptheo":   ["g3-fracnum"],
  "g4-simple":    ["g4-exptheo"],
  "g4-compl":     ["g4-simple"],

  /* ---- grade 5 ---- */
  "g5-express":   ["g4-evalexpr"],
  "g5-patterns":  ["g4-seq"],
  "g5-thousandth":["g4-deccomp"],
  "g5-decops":    ["g5-thousandth", "g4-multidig"],
  "g5-twodigit":  ["g4-divide"],
  "g5-unlike":    ["g4-fracadd", "g3-lcm"],
  "g5-fracmult":  ["g4-fracmultw"],
  "g5-fracdiv":   ["g5-fracmult", "g3-div"],
  "g5-fracword":  ["g5-unlike", "g5-fracmult"],
  "g5-convert":   ["g4-units", "g5-decops"],
  "g5-lineplot":  ["g4-lineplot"],
  "g5-volume":    ["g4-volprism"],
  "g5-coord":     ["g5-patterns"],
  "g5-hierarchy": ["g4-classify"],
  "g5-modarith":  ["g4-clockmod"],
  "g5-congru":    ["g5-modarith"],
  "g5-fermat":    ["g5-congru", "g4-primefact"],
  "g5-diophant":  ["g5-congru", "g4-euclid"],
  "g5-bases":     ["g4-placemil", "g5-modarith"],
  "g5-multistep": ["g4-onestep", "g4-liketerms"],
  "g5-inequal":   ["g4-inequal", "g5-multistep"],
  "g5-rateeq":    ["g5-multistep"],
  "g5-formulas":  ["g5-multistep"],
  "g5-functions": ["g5-patterns", "g5-coord"],
  "g5-pythag":    ["g4-tri-area", "g5-coord"],
  "g5-distance":  ["g5-coord", "g5-pythag"],
  "g5-angletri":  ["g4-protract", "g4-classify"],
  "g5-circarea":  ["g4-circle"],
  "g5-cylinder":  ["g4-circle", "g4-volprism"],
  "g5-permrep":   ["g4-factorial"],
  "g5-combrep":   ["g4-combin"],
  "g5-subsets":   ["g4-combin"],
  "g5-inclexcl":  ["g4-combin"],
  "g5-pascal":    ["g4-paths", "g4-combin"],
  "g5-compound":  ["g4-simple", "g3-multprin"],
  "g5-expected":  ["g5-compound", "g5-fracmult"],
  "g5-geoprob":   ["g5-compound", "g4-areaform"],
  "g5-condition": ["g5-compound"],

  /* ---- grade 6 ---- */
  "g6-ratios":    ["g5-fracmult", "g5-decops"],
  "g6-percent":   ["g6-ratios", "g4-decnot"],
  "g6-unitconv":  ["g6-ratios", "g5-convert"],
  "g6-nscoord":   ["g5-coord"],
  "g6-fracdiv":   ["g5-fracdiv"],
  "g6-decimals":  ["g5-decops"],
  "g6-exprexp":   ["g5-express"],
  "g6-equivexpr": ["g6-exprexp", "g4-liketerms"],
  "g6-onevar":    ["g5-multistep"],
  "g6-relation":  ["g5-functions", "g6-onevar"],
  "g6-polyarea":  ["g4-para-area"],
  "g6-volfrac":   ["g5-volume", "g5-fracmult"],
  "g6-coordpoly": ["g6-nscoord", "g6-polyarea"],
  "g6-netsurf":   ["g4-nets"],
  "g6-statq":     ["g5-lineplot"],
  "g6-centervar": ["g6-statq", "g5-decops"],
  "g6-displays":  ["g6-centervar"],
  "g6-modexp":    ["g5-modarith"],
  "g6-crt":       ["g6-modexp", "g5-congru"],
  "g6-diophant":  ["g5-diophant"],
  "g6-basearith": ["g5-bases"],
  "g6-contfrac":  ["g5-fracdiv", "g4-euclid"],
  "g6-perfect":   ["g4-factorpair"],
  "g6-bothsides": ["g6-onevar"],
  "g6-compound":  ["g5-inequal"],
  "g6-literal":   ["g5-formulas", "g6-bothsides"],
  "g6-slope":     ["g6-nscoord", "g6-relation"],
  "g6-systems":   ["g6-bothsides", "g6-slope"],
  "g6-pythag":    ["g5-pythag"],
  "g6-specialtri":["g6-pythag"],
  "g6-apothem":   ["g6-polyarea", "g6-specialtri"],
  "g6-solids":    ["g5-cylinder", "g6-netsurf"],
  "g6-transvers": ["g5-angletri"],
  "g6-transform": ["g6-nscoord", "g6-transvers"],
  "g6-permcomb":  ["g5-permrep", "g5-combrep"],
  "g6-binomial":  ["g5-pascal", "g6-permcomb"],
  "g6-symmetry":  ["g6-permcomb", "g6-transform"],
  "g6-recursion": ["g5-patterns", "g6-permcomb"],
  "g6-catalan":   ["g6-recursion", "g5-pascal"],
  "g6-replace":   ["g5-condition"],
  "g6-bayes":     ["g6-replace", "g5-condition"],
  "g6-randvar":   ["g5-expected"],
  "g6-distrib":   ["g6-randvar", "g6-binomial"],

  /* ---- grade 7 ---- */
  "g7-unitfrac":  ["g6-ratios", "g6-fracdiv"],
  "g7-propor":    ["g7-unitfrac", "g6-relation"],
  "g7-percentapp":["g6-percent"],
  "g7-ratops":    ["g6-nscoord", "g6-decimals"],
  "g7-todecimal": ["g7-ratops", "g6-fracdiv"],
  "g7-expand":    ["g6-equivexpr"],
  "g7-multistep": ["g6-onevar", "g7-ratops"],
  "g7-eqineq":    ["g7-multistep", "g6-compound"],
  "g7-scaledraw": ["g7-propor"],
  "g7-construct": ["g6-transvers"],
  "g7-circles":   ["g5-circarea"],
  "g7-anglerel":  ["g6-transvers"],
  "g7-solids":    ["g6-solids"],
  "g7-sampling":  ["g6-displays"],
  "g7-probmodel": ["g6-replace"],
  "g7-compound":  ["g7-probmodel", "g6-bayes"],
  "g7-modpow":    ["g6-modexp"],
  "g7-euler":     ["g7-modpow", "g5-fermat"],
  "g7-triples":   ["g6-pythag", "g6-diophant"],
  "g7-contfrac":  ["g6-contfrac"],
  "g7-rsa":       ["g7-euler", "g6-crt"],
  "g7-absval":    ["g7-eqineq"],
  "g7-systems":   ["g6-systems"],
  "g7-factorquad":["g7-expand"],
  "g7-solvequad": ["g7-factorquad"],
  "g7-graphquad": ["g7-solvequad", "g6-slope"],
  "g7-exponen":   ["g7-graphquad"],
  "g7-proofs":    ["g7-construct", "g6-transform"],
  "g7-centers":   ["g7-proofs"],
  "g7-circthm":   ["g7-circles", "g7-proofs"],
  "g7-heron":     ["g6-pythag", "g7-circles"],
  "g7-frustum":   ["g7-solids"],
  "g7-coordgeo":  ["g6-slope", "g5-distance"],
  "g7-inclexcl3": ["g5-inclexcl"],
  "g7-genfunc":   ["g6-binomial", "g6-recursion"],
  "g7-partitions":["g6-recursion"],
  "g7-graphtheo": ["g6-permcomb"],
  "g7-ramsey":    ["g7-graphtheo", "g7-inclexcl3"],
  "g7-bayes":     ["g6-bayes"],
  "g7-joint":     ["g7-bayes"],
  "g7-variance":  ["g6-randvar"],
  "g7-distrib":   ["g6-distrib", "g7-variance"],
  "g7-markov":    ["g7-joint", "g7-distrib"],

  /* ---- grade 8 ---- */
  "g8-irrational":["g7-todecimal", "g6-pythag"],
  "g8-radicals":  ["g8-irrational", "g6-exprexp"],
  "g8-scinot":    ["g8-radicals"],
  "g8-propgraph": ["g7-propor", "g6-slope"],
  "g8-linear":    ["g7-eqineq"],
  "g8-systems":   ["g7-systems", "g8-linear"],
  "g8-funcdef":   ["g6-relation"],
  "g8-funccomp":  ["g8-funcdef", "g8-propgraph"],
  "g8-funcmodel": ["g8-funccomp"],
  "g8-funcgraph": ["g8-funcdef"],
  "g8-transform": ["g6-transform"],
  "g8-dilations": ["g8-transform", "g7-scaledraw"],
  "g8-angleAA":   ["g7-anglerel", "g8-dilations"],
  "g8-pythag":    ["g7-triples"],
  "g8-solids":    ["g7-frustum"],
  "g8-scatter":   ["g7-sampling"],
  "g8-fitline":   ["g8-scatter", "g8-propgraph"],
  "g8-twoway":    ["g8-scatter", "g7-compound"],
  "g8-modfull":   ["g7-modpow", "g6-crt"],
  "g8-quadres":   ["g8-modfull", "g7-solvequad"],
  "g8-pell":      ["g8-modfull", "g7-contfrac"],
  "g8-flt":       ["g7-triples", "g8-modfull"],
  "g8-primality": ["g8-modfull", "g7-euler"],
  "g8-rsa":       ["g7-rsa", "g8-primality"],
  "g8-polynom":   ["g7-factorquad"],
  "g8-rational":  ["g8-polynom", "g6-fracdiv"],
  "g8-radicaleq": ["g8-radicals", "g7-solvequad"],
  "g8-vieta":     ["g7-solvequad", "g8-polynom"],
  "g8-nonlinear": ["g8-systems", "g7-graphquad"],
  "g8-inequal":   ["g7-absval", "g8-vieta"],
  "g8-series":    ["g7-partitions", "g8-funcdef"],
  "g8-complex":   ["g8-vieta", "g8-radicals"],
  "g8-ceva":      ["g7-centers"],
  "g8-power":     ["g7-circthm"],
  "g8-trig":      ["g8-pythag", "g7-heron"],
  "g8-euler":     ["g8-solids", "g7-graphtheo"],
  "g8-vectors":   ["g7-coordgeo", "g8-trig"],
  "g8-noneuclid": ["g8-euler", "g8-trig"],
  "g8-genfunc":   ["g7-genfunc"],
  "g8-polya":     ["g6-symmetry", "g7-graphtheo"],
  "g8-planar":    ["g7-graphtheo", "g8-euler"],
  "g8-ramsey":    ["g7-ramsey"],
  "g8-designs":   ["g8-polya"],
  "g8-pgf":       ["g8-genfunc", "g7-distrib"],
  "g8-randwalk":  ["g7-markov"],
  "g8-continuous":["g7-variance", "g5-geoprob"],
  "g8-clt":       ["g8-continuous", "g7-distrib"],
  "g8-entropy":   ["g8-continuous"]
};

/* Direct prerequisites of a topic. */
export const prereqsOf = id => PREREQS[id] || [];

/* Everything a topic depends on, transitively. */
export function allPrereqs(id, seen = new Set()) {
  for (const p of prereqsOf(id)) {
    if (seen.has(p)) continue;
    seen.add(p);
    allPrereqs(p, seen);
  }
  return seen;
}

/* Topics that list `id` as a prerequisite — what studying it opens up. */
export function unlockedBy(id) {
  return Object.keys(PREREQS).filter(t => PREREQS[t].includes(id));
}

/* Cycle detection, so a bad edit cannot make a topic depend on itself. */
export function findCycle() {
  const state = new Map();   // 0 = visiting, 1 = done
  const stack = [];
  let cycle = null;
  const visit = id => {
    if (cycle) return;
    if (state.get(id) === 1) return;
    if (state.get(id) === 0) { cycle = [...stack.slice(stack.indexOf(id)), id]; return; }
    state.set(id, 0); stack.push(id);
    for (const p of prereqsOf(id)) visit(p);
    stack.pop(); state.set(id, 1);
  };
  for (const id of Object.keys(PREREQS)) visit(id);
  return cycle;
}
