/* Question bank. Keyed by topic id; each question carries lvl 1|2|3
   which maps to the practice / challenge / boss tiers.
   The Grade 6 coordinate-plane bank is the one built from Josiah's
   actual worksheets. */

const SECS = {
  N:"Number",
  F:"Fractions",
  G:"Geometry & Measure",
  R:"Ratios & Rates",
  M:"Measurement",
  W:"Word Problems",
  P:"Patterns & Algebra",
  D:"Decimals",
  MNY:"Money",
  AXES:"Know the Plane", PTS:"Points & Quadrants", DIST:"Distance on the Grid",
  REFL:"Reflections", RECT:"Rectangles & Word Problems", CMP:"Compare & Order", FRDEC:"Fractions & Decimals"
};

const ABCD = [["A",2,3],["B",-3,1],["C",-2,-4],["D",3,-2]];

import { K_BANKS } from "./banks/k.mjs";
import { G12_BANKS } from "./banks/g1g2.mjs";
import { G3_BANKS } from "./banks/g3.mjs";
import { G4_BANKS } from "./banks/g4.mjs";
import { G5_BANKS } from "./banks/g5.mjs";
import { G6_BANKS } from "./banks/g6.mjs";
import { G7_BANKS } from "./banks/g7.mjs";
import { G8_BANKS } from "./banks/g8.mjs";

const QUESTIONS = { ...K_BANKS, ...G12_BANKS, ...G3_BANKS, ...G4_BANKS, ...G5_BANKS, ...G6_BANKS, ...G7_BANKS, ...G8_BANKS };

QUESTIONS["g6-nscoord"] = [
/* A — Know the Plane */
{sec:"AXES",type:"mc",q:"The horizontal number line on the coordinate plane is called the ___.",
 opts:["x-axis","y-axis","origin","quadrant"],a:0,
 expl:"The x-axis runs left–right (horizontal). The y-axis is the one that runs up–down."},
{sec:"AXES",type:"mc",q:"The x-axis and y-axis cross at the point (0, 0). That point is called the ___.",
 mono:false,opts:["origin","quadrant","midpoint","corner"],a:0,
 expl:"The origin is where the two axes intersect — the ordered pair (0, 0). Every point is plotted starting from there."},
{sec:"AXES",type:"mc",q:"In the ordered pair (3, 7), what does the 3 tell you to do?",
 opts:["Move 3 units right from the origin","Move 3 units up from the origin","Move 3 units left from the origin","It names Quadrant 3"],a:0,
 expl:"The first number is the x-coordinate: it moves you left or right along the x-axis. Positive 3 means 3 to the right. Then the 7 moves you up."},
{sec:"AXES",type:"mc",q:"Which describes every point in Quadrant II?",
 opts:["x is negative, y is positive","x is positive, y is positive","x is negative, y is negative","x is positive, y is negative"],a:0,
 expl:"Quadrants count counter-clockwise from the top-right: I is (+, +), II is (−, +), III is (−, −), IV is (+, −). Quadrant II is the top-left."},
{sec:"AXES",type:"mc",q:"The point (−8, −3) is in which quadrant?",
 opts:["Quadrant III","Quadrant I","Quadrant II","Quadrant IV"],a:0,
 expl:"Both coordinates are negative: move left, then down. That lands in the bottom-left region — Quadrant III."},

/* B — Points & Quadrants */
{sec:"PTS",type:"mc",q:"The point (5, −3) is in which quadrant?",
 opts:["Quadrant IV","Quadrant I","Quadrant II","Quadrant III"],a:0,
 expl:"x is positive (right) and y is negative (down) — bottom-right, which is Quadrant IV."},
{sec:"PTS",type:"mc",q:"The point (0, 7) lies ___.",
 opts:["on the y-axis","on the x-axis","in Quadrant I","at the origin"],a:0,
 expl:"x = 0 means no left–right movement at all — the point sits straight up the y-axis. Points on an axis are not inside any quadrant."},
{sec:"PTS",type:"mc",q:"The point (−4, 0) lies ___.",
 opts:["on the x-axis","on the y-axis","in Quadrant II","in Quadrant III"],a:0,
 expl:"y = 0 means no up–down movement, so the point sits on the x-axis, 4 units to the left of the origin."},
{sec:"PTS",type:"mc",q:"Look at the grid. Which point is located at (−3, 1)?",
 fig:{pts:ABCD.map(p=>[p[1],p[2],p[0]])},
 opts:["Point B","Point A","Point C","Point D"],a:0,
 expl:"From the origin: 3 left (x = −3), then 1 up (y = 1). That is point B."},
{sec:"PTS",type:"pair",q:"Write the coordinates of point D as an ordered pair.",
 fig:{pts:ABCD.map(p=>[p[1],p[2],p[0]])},ansP:[3,-2],
 expl:"D is 3 units right and 2 units down: x = 3, y = −2, so D is (3, −2). Always write (x, y) — right/left first, up/down second."},
{sec:"PTS",type:"pair",q:"Start at (−3, 2). Move 4 units right and 2 units up. Write where you land as an ordered pair.",ansP:[1,4],
 figA:{pts:[[-3,2,"start"],[1,4,"end","pt2"]],path:[[-3,2],[1,2],[1,4]]},
 expl:"Right means add to x: −3 + 4 = 1. Up means add to y: 2 + 2 = 4. You land on (1, 4)."},

/* C — Distance */
{sec:"DIST",type:"in",q:"Points (2, 3) and (2, 8) are plotted on a grid. What is the vertical distance between them, in units?",ans:5,hint:"Type just the number.",
 figA:{pts:[[2,3,"(2, 3)"],[2,8,"(2, 8)"]],path:[[2,3],[2,8]]},
 expl:"The x-values match, so count the space between the y-values: 8 − 3 = 5 units."},
{sec:"DIST",type:"in",q:"What is the distance between (6, 7) and (6, −4), in units?",ans:11,hint:"Type just the number.",
 figA:{pts:[[6,7,"(6, 7)"],[6,-4,"(6, −4)"]],path:[[6,7],[6,-4]]},
 expl:"The y-values are on opposite sides of the x-axis, so add their absolute values: |7| + |−4| = 7 + 4 = 11 units."},
{sec:"DIST",type:"in",q:"What is the horizontal distance between (−9, −10) and (10, −10), in units?",ans:19,hint:"Type just the number.",
 figA:{pts:[[-9,-10,"(−9, −10)"],[10,-10,"(10, −10)"]],path:[[-9,-10],[10,-10]]},
 expl:"Same y-value, and the x-values sit on opposite sides of the y-axis: |−9| + |10| = 9 + 10 = 19 units."},
{sec:"DIST",type:"in",q:"Point J is at (9, −8) and point K is at (0, −8). What is the distance between J and K, in units?",ans:9,hint:"Type just the number.",
 figA:{pts:[[9,-8,"J"],[0,-8,"K"]],path:[[9,-8],[0,-8]]},
 expl:"Same y-value, so it is a horizontal trip from x = 0 to x = 9: that is 9 units."},
{sec:"DIST",type:"mc",q:"Which expression gives the distance between (−2, 4) and (7, 4)?",mono:true,
 opts:["|−2| + |7|","|4| + |4|","|7| − |−2|","|−2| + |4|"],a:0,
 expl:"The y-values match (both 4), so distance runs along x. The x-values are on opposite sides of the y-axis, so ADD the absolute values: 2 + 7 = 9 units."},
{sec:"DIST",type:"in",q:"Find the distance between (4, 5) and (4, −7), in units.",ans:12,hint:"Type just the number.",
 figA:{pts:[[4,5,"(4, 5)"],[4,-7,"(4, −7)"]],path:[[4,5],[4,-7]]},
 expl:"Opposite sides of the x-axis, so add absolute values: |5| + |−7| = 5 + 7 = 12 units."},
{sec:"DIST",type:"in",q:"Find the distance between (0, 8) and (0, −12), in units.",ans:20,hint:"Type just the number.",
 expl:"Both points sit on the y-axis. Add the absolute values: |8| + |−12| = 8 + 12 = 20 units."},

/* D — Reflections */
{sec:"REFL",type:"pair",q:"Reflect (3, 6) over the y-axis. Write where it lands.",ansP:[-3,6],
 figA:{pts:[[3,6,"(3, 6)"],[-3,6,"(−3, 6)","pt2"]],path:[[3,6],[-3,6]]},
 expl:"Reflecting over the y-axis flips left–right: the x-coordinate changes sign and y stays the same. (3, 6) → (−3, 6)."},
{sec:"REFL",type:"pair",q:"Reflect (5, 8) over the x-axis. Write where it lands.",ansP:[5,-8],
 figA:{pts:[[5,8,"(5, 8)"],[5,-8,"(5, −8)","pt2"]],path:[[5,8],[5,-8]]},
 expl:"Reflecting over the x-axis flips up–down: the y-coordinate changes sign and x stays the same. (5, 8) → (5, −8)."},
{sec:"REFL",type:"pair",q:"Reflect (−12, 10) over the x-axis. Write where it lands.",ansP:[-12,-10],
 expl:"Over the x-axis, keep x and flip y: x stays −12, and 10 becomes −10. It lands at (−12, −10)."},
{sec:"REFL",type:"mc",q:"When you reflect a point over the x-axis, which is true?",
 opts:["The y-coordinate changes sign; x stays the same","The x-coordinate changes sign; y stays the same","Both coordinates change sign","Both coordinates stay the same"],a:0,
 expl:"x-axis reflection flips a point up–down, so only y changes sign. Over the y-axis, only x flips. To the opposite quadrant, both flip."},
{sec:"REFL",type:"pair",q:"Reflect (−6, 5) over the y-axis. Write where it lands.",ansP:[6,5],
 figA:{pts:[[-6,5,"(−6, 5)"],[6,5,"(6, 5)","pt2"]],path:[[-6,5],[6,5]]},
 expl:"Over the y-axis, flip only the x: −6 becomes 6. The point lands at (6, 5) — no plotting needed once you know the pattern!"},
{sec:"REFL",type:"pair",q:"Reflect (4, −2) into the opposite quadrant (over BOTH axes). Write where it lands.",ansP:[-4,2],
 figA:{pts:[[4,-2,"(4, −2)"],[-4,2,"(−4, 2)","pt2"]],path:[[4,-2],[-4,2]]},
 expl:"Opposite quadrant means both coordinates change sign: (4, −2) → (−4, 2)."},

/* E — Rectangles & Word Problems */
{sec:"RECT",type:"mc",q:"Points (−4, 2) and (1, 2) are the TOP two corners of a rectangle that is 3 units tall (it drops down from these corners). What are the other two vertices?",mono:true,
 opts:["(−4, −1) and (1, −1)","(−4, 5) and (1, 5)","(−4, 1) and (1, 1)","(−7, 2) and (4, 2)"],a:0,
 figA:{poly:[[-4,2],[1,2],[1,-1],[-4,-1]],pts:[[-4,2,""],[1,2,""],[1,-1,"","pt2"],[-4,-1,"","pt2"]]},
 expl:"The bottom corners sit straight below, so the x-values stay −4 and 1. Drop the y down 3: 2 − 3 = −1."},
{sec:"RECT",type:"mc",q:"Points (−4, −4) and (0, −4) are the BOTTOM two corners of a rectangle that is 8 units tall (it rises up from these corners). What are the other two vertices?",mono:true,
 opts:["(−4, 4) and (0, 4)","(−4, −12) and (0, −12)","(−4, 8) and (0, 8)","(4, −4) and (8, −4)"],a:0,
 figA:{poly:[[-4,-4],[0,-4],[0,4],[-4,4]],pts:[[-4,-4,""],[0,-4,""],[0,4,"","pt2"],[-4,4,"","pt2"]]},
 expl:"Keep the x-values and go UP 8 from y = −4: that is 4 up to the x-axis, then 4 more, so y = −4 + 8 = 4."},
{sec:"RECT",type:"pair",q:"A cell phone tower is 6 blocks west and 2 blocks north of Darnell's house, which sits at the origin. Write the tower's location as an ordered pair.",ansP:[-6,2],
 figA:{pts:[[0,0,"house"],[-6,2,"tower","pt2"]],path:[[0,0],[-6,0],[-6,2]]},
 expl:"On a map grid: west is the negative x direction and north is the positive y direction. 6 west, 2 north → (−6, 2)."},
{sec:"RECT",type:"pair",q:"A boat leaves port at (−7, −3). It sails 5 miles east, then 8 miles south. Write the boat's new location as an ordered pair.",ansP:[-2,-11],
 figA:{pts:[[-7,-3,"port"],[-2,-11,"boat","pt2"]],path:[[-7,-3],[-2,-3],[-2,-11]]},
 expl:"East adds to x: −7 + 5 = −2. South subtracts from y: −3 − 8 = −11. The boat is at (−2, −11)."},
{sec:"RECT",type:"in",q:"You scored 96 on your first quiz and 89 on your second. Write the integer that shows the change in your score.",ans:-7,hint:"Include the sign if it dropped, like −4.",
 expl:"Change = new − old = 89 − 96 = −7. The score dropped 7 points, so the change is negative."},

/* F — Compare & Order */
{sec:"CMP",type:"mc",q:"Choose the symbol that makes this true:  −5.05 ◯ −5",mono:true,
 opts:["<",">","="],a:0,
 expl:"With negatives, the number farther below zero is SMALLER. −5.05 is a little more negative than −5, so −5.05 < −5."},
{sec:"CMP",type:"mc",q:"Choose the symbol that makes this true:  −1.75 ◯ −0.75",mono:true,
 opts:["<",">","="],a:0,
 expl:"−1.75 is farther from zero on the negative side, so it is the smaller number: −1.75 < −0.75."},
{sec:"CMP",type:"mc",q:"Choose the symbol that makes this true:  −24 ◯ −24.0",mono:true,
 opts:["=","<",">"],a:0,
 expl:"Writing .0 on the end does not change a number's value. −24 and −24.0 are exactly equal."},
{sec:"CMP",type:"mc",q:"Order from LEAST to greatest:  4,  −6,  4.6,  16,  −3.9",mono:true,
 opts:["−6, −3.9, 4, 4.6, 16","−3.9, −6, 4, 4.6, 16","16, 4.6, 4, −3.9, −6","−6, −3.9, 4.6, 4, 16"],a:0,
 expl:"Negatives come first, and −6 is less than −3.9 (it is farther below zero). Then 4 < 4.6 < 16."},
{sec:"CMP",type:"in",q:"What is the value of |−7| ?",ans:7,hint:"Absolute value asks: how far from zero?",
 expl:"Absolute value is a number's distance from zero, and distance is always positive: |−7| = 7."},
{sec:"CMP",type:"mc",q:"Order from LEAST to greatest:  3,  −½,  |−4|,  1½",mono:true,
 opts:["−½, 1½, 3, |−4|","−½, 1½, |−4|, 3","|−4|, 3, 1½, −½","1½, −½, 3, |−4|"],a:0,
 expl:"First simplify: |−4| = 4. Now order −0.5, 1.5, 3, 4 → −½, 1½, 3, |−4|."},
{sec:"CMP",type:"mc",q:"Order from LEAST to greatest:  1.77,  17,  1.07,  −4.5,  −7",mono:true,
 opts:["−7, −4.5, 1.07, 1.77, 17","−4.5, −7, 1.07, 1.77, 17","17, 1.77, 1.07, −4.5, −7","−7, −4.5, 1.77, 1.07, 17"],a:0,
 expl:"−7 is below −4.5. For 1.07 vs 1.77, compare tenths: 0 < 7, so 1.07 comes first. Then 17 is the biggest."},

/* G — Fractions & Decimals */
{sec:"FRDEC",type:"in",q:"Write 9/10 as a decimal.",ans:0.9,hint:"A fraction bar means divide: 9 ÷ 10.",
 expl:"The fraction bar means division: 9 ÷ 10 = 0.9."},
{sec:"FRDEC",type:"in",q:"Write 7/4 as a decimal.",ans:1.75,hint:"Divide the top by the bottom.",
 expl:"7 ÷ 4 = 1.75. (7/4 is the same as 1¾, and ¾ = 0.75.)"},
{sec:"FRDEC",type:"mc",q:"Order from GREATEST to least:  11/12,  2/3,  5/6,  1/4",mono:true,
 opts:["11/12, 5/6, 2/3, 1/4","11/12, 2/3, 5/6, 1/4","1/4, 2/3, 5/6, 11/12","5/6, 11/12, 2/3, 1/4"],a:0,
 expl:"Rename with the LCD of 12: 11/12, 8/12, 10/12, 3/12. Now compare tops: 11 > 10 > 8 > 3 → 11/12, 5/6, 2/3, 1/4."},
{sec:"FRDEC",type:"mc",q:"On a reading app, Margo finished 21/25 of a book, Mason finished 17/20, and Marco finished 5/6. Order them from MOST completed to least.",
 opts:["Mason, Margo, Marco","Margo, Mason, Marco","Marco, Mason, Margo","Mason, Marco, Margo"],a:0,
 expl:"Convert each to a decimal: 21/25 = 0.84, 17/20 = 0.85, 5/6 ≈ 0.83. So Mason (0.85) > Margo (0.84) > Marco (0.83)."},

/* ===== LEVEL 2 — CHALLENGE ===== */
{lvl:2,sec:"RECT",type:"in",q:"A rectangle has vertices (−3, 4), (5, 4), (5, −1) and (−3, −1). What is its perimeter, in units?",hint:"Find the width and height first.",ans:26,
 figA:{poly:[[-3,4],[5,4],[5,-1],[-3,-1]],pts:[[-3,4,""],[5,4,""],[5,-1,""],[-3,-1,""]]},
 expl:"Width = |−3| + |5| = 8. Height = |4| + |−1| = 5. Perimeter = 2 × (8 + 5) = 26 units."},
{lvl:2,sec:"RECT",type:"in",q:"What is the AREA of that same rectangle — vertices (−3, 4), (5, 4), (5, −1), (−3, −1) — in square units?",hint:"Area = width × height.",ans:40,
 expl:"Width 8 and height 5, so area = 8 × 5 = 40 square units. (Perimeter adds the sides; area multiplies them.)"},
{lvl:2,sec:"RECT",type:"pair",q:"Three vertices of a rectangle are (−6, 2), (1, 2) and (1, −4). Write the fourth vertex.",ansP:[-6,-4],
 figA:{poly:[[-6,2],[1,2],[1,-4],[-6,-4]],pts:[[-6,2,""],[1,2,""],[1,-4,""],[-6,-4,"?","pt2"]]},
 expl:"The missing corner shares its x with (−6, 2) and its y with (1, −4), so it is (−6, −4)."},
{lvl:2,sec:"REFL",type:"pair",q:"Start at (5, −3). Reflect it over the x-axis, THEN move 4 units left. Where does it end up?",ansP:[1,3],
 expl:"Reflect over the x-axis: (5, −3) → (5, 3). Then 4 left subtracts from x: 5 − 4 = 1. Final answer (1, 3)."},
{lvl:2,sec:"REFL",type:"pair",q:"Reflect (−4, 7) over the x-axis, then reflect that result over the y-axis. Where does it land?",ansP:[4,-7],
 expl:"Over the x-axis: (−4, 7) → (−4, −7). Then over the y-axis: (−4, −7) → (4, −7). Doing both is the same as one jump to the opposite quadrant."},
{lvl:2,sec:"REFL",type:"pair",q:"A point was reflected over the y-axis and landed at (−9, 4). What were its ORIGINAL coordinates?",ansP:[9,4],
 expl:"Work backwards: a y-axis reflection only flips x, and flipping is its own undo. So the start was (9, 4)."},
{lvl:2,sec:"DIST",type:"mc",q:"Which point is FARTHER from the origin: A at (0, −8) or B at (6, 0)?",
 opts:["A, because it is 8 units away","B, because it is 6 units away","They are the same distance","You cannot tell without a grid"],a:0,
 expl:"A sits on the y-axis, |−8| = 8 units from the origin. B sits on the x-axis, 6 units away. 8 > 6, so A is farther."},
{lvl:2,sec:"CMP",type:"mc",q:"Order from LEAST to greatest:  −3.5,  |−4|,  −2¾,  2.5,  |−1.5|",mono:true,
 opts:["−3.5, −2¾, |−1.5|, 2.5, |−4|","−3.5, −2¾, 2.5, |−1.5|, |−4|","|−4|, −3.5, −2¾, |−1.5|, 2.5","−2¾, −3.5, |−1.5|, 2.5, |−4|"],a:0,
 expl:"Simplify the absolute values first: |−4| = 4 and |−1.5| = 1.5. Now order −3.5, −2.75, 1.5, 2.5, 4."},
{lvl:2,sec:"PTS",type:"pair",q:"Point P lies on the x-axis, 7 units to the LEFT of the origin. Write its coordinates.",ansP:[-7,0],
 expl:"On the x-axis the y-coordinate is 0, and 7 to the left makes x = −7. So P is (−7, 0)."},
{lvl:2,sec:"DIST",type:"pair",q:"Two points share the x-value 3. One is at (3, 6). The other is 10 units BELOW it. Write the other point.",ansP:[3,-4],
 figA:{pts:[[3,6,"(3, 6)"],[3,-4,"?","pt2"]],path:[[3,6],[3,-4]]},
 expl:"Going down subtracts from y: 6 − 10 = −4. The other point is (3, −4)."},
{lvl:2,sec:"RECT",type:"pair",q:"A boat is at (−4, 6). It sails 9 units south, then 5 units east. Write its new position.",ansP:[1,-3],
 figA:{pts:[[-4,6,"start"],[1,-3,"end","pt2"]],path:[[-4,6],[-4,-3],[1,-3]]},
 expl:"South subtracts from y: 6 − 9 = −3. East adds to x: −4 + 5 = 1. The boat ends at (1, −3)."},
{lvl:2,sec:"PTS",type:"mc",q:"Which point lies in the SAME quadrant as (−7, −2)?",mono:true,
 opts:["(−1, −9)","(−1, 9)","(1, −9)","(1, 9)"],a:0,
 expl:"(−7, −2) has both coordinates negative, so it is in Quadrant III. Only (−1, −9) is also (−, −)."},
{lvl:2,sec:"DIST",type:"in",q:"Find the distance between (−12, 5) and (8, 5), in units.",hint:"Type just the number.",ans:20,
 expl:"Same y-value, and the x-values straddle the y-axis: |−12| + |8| = 12 + 8 = 20 units."},
{lvl:2,sec:"CMP",type:"mc",q:"Which statement is TRUE?",mono:true,
 opts:["|−8| > |5|","|−8| < |5|","|−8| = −8","−8 > 5"],a:0,
 expl:"Absolute value strips the sign: |−8| = 8 and |5| = 5, and 8 > 5. Note −8 itself is LESS than 5 — the absolute values compare differently than the numbers do."},
{lvl:2,sec:"AXES",type:"mc",q:"A point moves from Quadrant I to Quadrant III. What happens to its coordinates?",
 opts:["Both x and y change sign","Only x changes sign","Only y changes sign","Neither changes sign"],a:0,
 expl:"Quadrant I is (+, +) and Quadrant III is (−, −), so both coordinates flip sign. Quadrant I → II flips only x; I → IV flips only y."},
{lvl:2,sec:"FRDEC",type:"in",q:"Write 7/8 as a decimal.",hint:"Divide the top by the bottom.",ans:0.875,
 expl:"7 ÷ 8 = 0.875. Since 1/8 = 0.125, seven of them make 0.875."},
{lvl:2,sec:"FRDEC",type:"mc",q:"Order from LEAST to greatest:  5/8,  0.6,  2/3",mono:true,
 opts:["0.6, 5/8, 2/3","5/8, 0.6, 2/3","2/3, 5/8, 0.6","0.6, 2/3, 5/8"],a:0,
 expl:"Turn them all into decimals: 5/8 = 0.625 and 2/3 ≈ 0.667. Now compare 0.6 < 0.625 < 0.667."},
{lvl:2,sec:"AXES",type:"mc",q:"How are the four quadrants numbered?",
 opts:["Starting in the top-right, going counter-clockwise","Starting in the top-left, going clockwise","Starting in the bottom-left, going up","Left to right, then top to bottom"],a:0,
 expl:"Quadrant I is the top-right (+, +), then you count counter-clockwise: II top-left, III bottom-left, IV bottom-right."},
{lvl:2,sec:"AXES",type:"mc",q:"Which statement about the origin is TRUE?",mono:true,
 opts:["It is (0, 0), where the two axes cross","It is the centre of Quadrant I","It is any point on the x-axis","It is where x = 1 and y = 1"],a:0,
 expl:"The origin is the single point (0, 0) where the x-axis and y-axis intersect. Every plot starts there — and it belongs to no quadrant."},
{lvl:2,sec:"PTS",type:"mc",q:"In which quadrant does (−2.5, 6) lie?",mono:true,
 opts:["Quadrant II","Quadrant I","Quadrant III","Quadrant IV"],a:0,
 expl:"Decimals follow the same rule as whole numbers: x is negative and y is positive, which is (−, +) — Quadrant II."},
{lvl:2,sec:"CMP",type:"mc",q:"Choose the symbol that makes this true:  |−3.2| ◯ 3.2",mono:true,
 opts:["=","<",">"],a:0,
 expl:"Absolute value removes the sign, so |−3.2| = 3.2. The two sides are exactly equal."},
{lvl:2,sec:"FRDEC",type:"in",q:"Write 1⅗ as a decimal.",hint:"Keep the whole number, convert the fraction.",ans:1.6,
 expl:"The whole number 1 stays, and ⅗ = 3 ÷ 5 = 0.6. Together that makes 1.6."},

/* ===== LEVEL 3 — BOSS LEVEL ===== */
{lvl:3,sec:"RECT",type:"in",q:"A rectangle's top side runs from (−5, 3) to (4, 3), and its area is 45 square units. What is the y-coordinate of its bottom side? (The rectangle sits below the top side.)",hint:"Find the width, then the height.",ans:-2,
 expl:"Width = |−5| + |4| = 9. Area = width × height, so 45 ÷ 9 = 5 for the height. Going down 5 from y = 3 gives y = 3 − 5 = −2."},
{lvl:3,sec:"DIST",type:"mc",q:"Point Q is exactly 6 units from (2, −1), measured HORIZONTALLY. What are the two possible x-coordinates for Q?",mono:true,
 opts:["−4 and 8","−4 and 6","8 and 12","−6 and 6"],a:0,
 expl:"Horizontal means y stays −1 and x moves 6 either way: 2 − 6 = −4, or 2 + 6 = 8. Distance problems often have two answers!"},
{lvl:3,sec:"REFL",type:"mc",q:"A point is reflected over the x-axis and its image lands in Quadrant II. Which quadrant was the ORIGINAL point in?",
 opts:["Quadrant III","Quadrant I","Quadrant II","Quadrant IV"],a:0,
 expl:"An x-axis reflection keeps x and flips y. The image is in QII, so x < 0 and its y > 0 — meaning the original y was negative. Negative x with negative y is Quadrant III."},
{lvl:3,sec:"REFL",type:"pair",q:"A point was reflected over the y-axis, then over the x-axis, and ended at (−6, 9). Where did it START?",ansP:[6,-9],
 expl:"Both reflections flip a sign, so together they flip both. Undo them by flipping both again: (−6, 9) → (6, −9)."},
{lvl:3,sec:"CMP",type:"mc",q:"Order from GREATEST to least:  |−2.5|,  −¼,  2⅕,  −|3|,  0.75",mono:true,
 opts:["|−2.5|, 2⅕, 0.75, −¼, −|3|","2⅕, |−2.5|, 0.75, −¼, −|3|","|−2.5|, 2⅕, 0.75, −|3|, −¼","−|3|, −¼, 0.75, 2⅕, |−2.5|"],a:0,
 expl:"Simplify first: |−2.5| = 2.5, 2⅕ = 2.2, −|3| = −3. Watch that last one — the minus sits OUTSIDE, so it stays negative. Greatest to least: 2.5, 2.2, 0.75, −0.25, −3."},
{lvl:3,sec:"RECT",type:"in",q:"A hiker starts at (−8, −5), walks 12 units east, then 9 units north. How many units is she from the y-axis now?",hint:"Find where she ends up first.",ans:4,
 expl:"East: −8 + 12 = 4. North: −5 + 9 = 4, so she is at (4, 4). Distance from the y-axis is the absolute value of x: |4| = 4 units."},
{lvl:3,sec:"RECT",type:"in",q:"Find the perimeter of the rectangle with vertices (−6, −2), (3, −2), (3, 6) and (−6, 6), in units.",hint:"Width and height first.",ans:34,
 figA:{poly:[[-6,-2],[3,-2],[3,6],[-6,6]],pts:[[-6,-2,""],[3,-2,""],[3,6,""],[-6,6,""]]},
 expl:"Width = |−6| + |3| = 9. Height = |−2| + |6| = 8. Perimeter = 2 × (9 + 8) = 34 units."},
{lvl:3,sec:"CMP",type:"mc",q:"Three students' score changes were −12, +5 and −3. Order the changes from LEAST to greatest.",mono:true,
 opts:["−12, −3, +5","−3, −12, +5","+5, −3, −12","−12, +5, −3"],a:0,
 expl:"On a number line −12 sits farthest left, then −3, then +5. A bigger drop is a SMALLER number, even though it feels 'larger'."},
{lvl:3,sec:"CMP",type:"mc",q:"Which is greater:  |−9|  or  −(−8) ?",mono:true,
 opts:["|−9|, because it equals 9","−(−8), because it equals −8","They are equal","−(−8), because it equals 8"],a:0,
 expl:"|−9| = 9. And −(−8) means the opposite of −8, which is +8. Since 9 > 8, |−9| is greater."},
{lvl:3,sec:"DIST",type:"in",q:"What is the distance between (a, 4) and (a, −7), in units — for ANY value of a?",hint:"The x-values are identical, whatever a is.",ans:11,
 expl:"Both points share the same x, so the trip is purely vertical and a never matters: |4| + |−7| = 4 + 7 = 11 units."},
{lvl:3,sec:"AXES",type:"mc",q:"Which of these points does NOT lie in any quadrant?",mono:true,
 opts:["(0, −4)","(−1, −4)","(3, −4)","(−3, 4)"],a:0,
 expl:"A point with a 0 in either coordinate sits ON an axis, and the axes are not part of any quadrant. (0, −4) is on the y-axis."},
{lvl:3,sec:"PTS",type:"mc",q:"Point (a, b) has a < 0 and b > 0. In which quadrant is the point (b, a)?",
 opts:["Quadrant IV","Quadrant I","Quadrant II","Quadrant III"],a:0,
 expl:"(a, b) is (−, +), so it sits in Quadrant II. Swapping them gives (b, a) = (+, −) — positive x, negative y — which is Quadrant IV."},
{lvl:3,sec:"FRDEC",type:"mc",q:"Order from GREATEST to least:  11/8,  1.3,  1¼",mono:true,
 opts:["11/8, 1.3, 1¼","1.3, 11/8, 1¼","1¼, 1.3, 11/8","11/8, 1¼, 1.3"],a:0,
 expl:"Convert to decimals: 11/8 = 1.375 and 1¼ = 1.25. Now compare 1.375 > 1.3 > 1.25."},
{lvl:3,sec:"AXES",type:"mc",q:"A point sits on the y-axis, BELOW the origin. What must be true of its coordinates?",mono:true,
 opts:["x = 0 and y is negative","y = 0 and x is negative","Both x and y are negative","x = 0 and y is positive"],a:0,
 expl:"Being on the y-axis forces x = 0 (no left-right movement), and below the origin means y is negative — like (0, −6)."},
{lvl:3,sec:"PTS",type:"mc",q:"Point (m, n) lies in Quadrant IV. In which quadrant is the point (−m, n)?",
 opts:["Quadrant III","Quadrant I","Quadrant II","Quadrant IV"],a:0,
 expl:"Quadrant IV means m is positive and n is negative. Flipping m gives −m negative, and n stays negative — so (−m, n) is (−, −), which is Quadrant III."},
{lvl:3,sec:"FRDEC",type:"mc",q:"Which is greater:  7/9  or  0.8 ?",mono:true,
 opts:["0.8","7/9","They are equal","You cannot compare a fraction to a decimal"],a:0,
 expl:"Divide to compare: 7 ÷ 9 = 0.777… which is less than 0.8. A fraction and a decimal are always comparable — just convert one of them."},

/* Plot questions (spec 3.2.2). The child places points on the grid instead of
   typing coordinates, which tests the skill the topic is actually about: a
   learner can read "(3, −2)" off a diagram and still put the point in the
   wrong quadrant when asked to place it. `ansPlot` marks a specific set of
   points regardless of the order they were placed in; `plotRule` marks any
   points satisfying a relation, which is how a question with infinitely many
   right answers gets asked at all. */
{lvl:1,sec:"PTS",type:"plot",q:"Plot the point (3, −2).",
 plot:{xMin:-5,xMax:5,yMin:-5,yMax:5},ansPlot:[[3,-2]],
 hint:"The first number is how far across, the second is how far up or down.",
 expl:"Start at the origin, go 3 to the right, then 2 down. That lands in Quadrant IV, below the x-axis."},
{lvl:2,sec:"PTS",type:"plot",q:"Plot the point in Quadrant II that is 4 units from the y-axis and 1 unit from the x-axis.",
 plot:{xMin:-6,xMax:6,yMin:-6,yMax:6},ansPlot:[[-4,1]],
 hint:"Quadrant II is up and to the left: x negative, y positive.",
 expl:"Distance from the y-axis is how far across you are, so x = −4 to be 4 units left. Distance from the x-axis is how far up, so y = 1. In Quadrant II that fixes the point at (−4, 1)."},
{lvl:2,sec:"REFL",type:"plot",q:"Plot the reflection of (−3, 4) across the x-axis.",
 plot:{xMin:-6,xMax:6,yMin:-6,yMax:6},ansPlot:[[-3,-4]],
 hint:"Reflecting across the x-axis keeps you the same distance across, but flips above to below.",
 expl:"Across the x-axis, x stays −3 and y flips from 4 to −4. The point lands at (−3, −4) in Quadrant III."},
{lvl:3,sec:"RECT",type:"plot",q:"Three corners of a rectangle are (−2, 3), (4, 3) and (4, −1). Plot the fourth corner.",
 plot:{xMin:-6,xMax:6,yMin:-6,yMax:6},
 fig:{pts:[[-2,3,""],[4,3,""],[4,-1,""]]},ansPlot:[[-2,-1]],
 hint:"Opposite sides of a rectangle line up. Which x and which y are still missing a partner?",
 expl:"The corners pair up: x is either −2 or 4, and y is either 3 or −1. The pair not yet used is (−2, −1)."},
{lvl:3,sec:"PTS",type:"plot",q:"Plot any two different points that lie on the line y = 2x + 1.",
 plot:{xMin:-6,xMax:6,yMin:-6,yMax:6},plotRule:{m:2,c:1,need:2},
 hint:"Pick any x you like, double it, then add 1 to get y.",
 expl:"Every point on the line satisfies y = 2x + 1. Choosing x = 0 gives (0, 1); x = 1 gives (1, 3). Any two different points that fit the rule are correct — there is no single right answer here."}
];

/* ---- Grade 6 · Ratios & Unit Rates ---- */
QUESTIONS["g6-ratios"] = [
/* practice */
{sec:"R",type:"mc",q:"A bag has 4 red marbles and 6 blue marbles. What is the ratio of red to blue?",mono:true,
 opts:["4 : 6","6 : 4","4 : 10","10 : 4"],a:0,
 expl:"Ratios list the quantities in the order the question names them: red first, then blue, so 4 : 6. (It also simplifies to 2 : 3.)"},
{sec:"R",type:"mc",q:"Write the ratio 12 : 18 in simplest form.",mono:true,
 opts:["2 : 3","3 : 2","6 : 9","12 : 18"],a:0,
 expl:"Divide both sides by the greatest common factor, 6: 12 ÷ 6 = 2 and 18 ÷ 6 = 3. So 12 : 18 = 2 : 3."},
{sec:"R",type:"in",q:"6 apples cost $3. What is the cost of ONE apple, in dollars?",hint:"Type just the number, like 0.75",ans:0.5,
 expl:"A unit rate is the cost for one: $3 ÷ 6 apples = $0.50 per apple."},
{sec:"R",type:"in",q:"A car travels 150 miles in 3 hours. What is its speed in miles per hour?",hint:"Type just the number.",ans:50,
 expl:"Divide to get the rate for one hour: 150 ÷ 3 = 50 miles per hour."},
{sec:"R",type:"mc",q:"A recipe uses 2 cups of flour for every 3 cups of milk. If you use 4 cups of flour, how much milk do you need?",mono:true,
 opts:["6 cups","5 cups","8 cups","3 cups"],a:0,
 expl:"The flour doubled (2 → 4), so the milk must double too: 3 × 2 = 6 cups. Ratios scale up together."},
{sec:"R",type:"in",q:"A store sells 5 notebooks for $10. At that rate, what would 8 notebooks cost, in dollars?",hint:"Find the price of one first.",ans:16,
 expl:"One notebook costs $10 ÷ 5 = $2. So 8 notebooks cost 8 × $2 = $16."},
{sec:"R",type:"mc",q:"Which ratio is EQUIVALENT to 3 : 5?",mono:true,
 opts:["9 : 15","5 : 3","3 : 10","6 : 5"],a:0,
 expl:"Multiply both parts by the same number: 3 × 3 = 9 and 5 × 3 = 15, so 9 : 15 is equivalent."},
{sec:"R",type:"in",q:"In a class of 24 students the ratio of boys to girls is 1 : 2. How many girls are there?",hint:"Think about how many equal parts there are in total.",ans:16,
 expl:"1 + 2 = 3 equal parts, and 24 ÷ 3 = 8 students per part. Girls are 2 parts: 2 × 8 = 16."},

/* challenge */
{lvl:2,sec:"R",type:"in",q:"A printer prints 24 pages in 3 minutes. How many pages does it print in 7 minutes?",hint:"Find the per-minute rate first.",ans:56,
 expl:"Unit rate: 24 ÷ 3 = 8 pages per minute. In 7 minutes: 8 × 7 = 56 pages."},
{lvl:2,sec:"R",type:"in",q:"Which is the better buy, and by how much per ounce? A: 12 oz for $3.00.  B: 20 oz for $4.00.  Type the price per ounce of the BETTER buy, in dollars.",hint:"Compare cost per ounce.",ans:0.2,
 expl:"A is $3.00 ÷ 12 = $0.25 per ounce. B is $4.00 ÷ 20 = $0.20 per ounce. B is cheaper per ounce, at $0.20."},
{lvl:2,sec:"R",type:"in",q:"The ratio of cats to dogs at a shelter is 4 : 7. There are 28 cats. How many dogs are there?",hint:"What did 4 get multiplied by?",ans:49,
 expl:"4 × 7 = 28, so every part was multiplied by 7. Dogs: 7 × 7 = 49."},
{lvl:2,sec:"R",type:"mc",q:"A map uses a scale of 1 inch = 25 miles. Two towns are 3.5 inches apart on the map. How far apart are they in reality?",mono:true,
 opts:["87.5 miles","28.5 miles","75 miles","7.1 miles"],a:0,
 expl:"Multiply by the scale: 3.5 × 25 = 87.5 miles."},
{lvl:2,sec:"R",type:"in",q:"A runner covers 3/4 of a mile in 6 minutes. At that pace, how many minutes does ONE mile take?",hint:"How many minutes for each quarter-mile?",ans:8,
 expl:"3/4 mile took 6 minutes, so each quarter-mile takes 6 ÷ 3 = 2 minutes. A full mile is 4 quarters: 4 × 2 = 8 minutes."},
{lvl:2,sec:"R",type:"mc",q:"Paint is mixed 2 parts blue to 5 parts white. Which mixture is the SAME shade?",mono:true,
 opts:["8 parts blue to 20 parts white","4 parts blue to 8 parts white","5 parts blue to 2 parts white","3 parts blue to 6 parts white"],a:0,
 expl:"2 : 5 scaled by 4 gives 8 : 20 — the only option where both parts were multiplied by the same number."},

/* boss */
{lvl:3,sec:"R",type:"in",q:"Two numbers are in the ratio 3 : 8, and their difference is 35. What is the SMALLER number?",hint:"How many parts is the difference?",ans:21,
 expl:"The difference is 8 − 3 = 5 parts, and 5 parts = 35, so one part = 7. The smaller number is 3 parts: 3 × 7 = 21."},
{lvl:3,sec:"R",type:"in",q:"A recipe for 4 people uses 6 eggs. You are cooking for 10 people. How many eggs do you need?",hint:"Eggs per person first — the answer may not be whole.",ans:15,
 expl:"6 ÷ 4 = 1.5 eggs per person. For 10 people: 1.5 × 10 = 15 eggs."},
{lvl:3,sec:"R",type:"in",q:"Machine A makes 45 parts in 5 minutes. Machine B makes 96 parts in 12 minutes. Working together, how many parts do they make in 10 minutes?",hint:"Find each machine's rate per minute.",ans:170,
 expl:"A: 45 ÷ 5 = 9 per minute. B: 96 ÷ 12 = 8 per minute. Together 17 per minute, so in 10 minutes 17 × 10 = 170 parts."},
{lvl:3,sec:"R",type:"mc",q:"The ratio of red to blue counters is 5 : 3. If 8 more red counters are added, the ratio becomes 3 : 1. How many blue counters are there?",mono:true,
 opts:["6","3","9","12"],a:0,
 expl:"Let each original part be n: red = 5n, blue = 3n. After adding 8 red: (5n + 8) = 3 × 3n = 9n, so 8 = 4n and n = 2. Blue = 3 × 2 = 6."},
{lvl:3,sec:"R",type:"in",q:"A tank fills at 12 litres per minute and drains at 5 litres per minute. If both happen at once, how many minutes does it take to fill a 63-litre tank?",hint:"What is the NET rate per minute?",ans:9,
 expl:"Net rate = 12 − 5 = 7 litres per minute. 63 ÷ 7 = 9 minutes."}
];


export { SECS, QUESTIONS };

/* ---- Grade 6 · Percents (g6-percent) ----
   Exercises the ordering and select-all question types alongside the
   existing ones, so every type is represented in a real bank. */
QUESTIONS["g6-percent"] = [
/* practice */
{sec:"R",type:"in",q:"What is 25% of 80?",hint:"25% is one quarter.",ans:20,
 expl:"25% means 25 out of 100, or one quarter. A quarter of 80 is 80 ÷ 4 = 20."},
{sec:"R",type:"in",q:"What is 10% of 350?",hint:"To find 10%, divide by 10.",ans:35,
 expl:"10% is one tenth, so 350 ÷ 10 = 35."},
{sec:"R",type:"mc",q:"Which is the same as 40%?",mono:true,
 opts:["0.4","4.0","0.04","40.0"],a:0,
 expl:"Percent means 'per hundred', so 40% = 40/100 = 0.4."},
{sec:"R",type:"order",q:"Put these in order from SMALLEST to largest.",
 items:["25%","0.4","1/2","70%"],ansOrder:["25%","0.4","1/2","70%"],
 hint:"Turn them all into decimals first.",
 expl:"As decimals: 25% = 0.25, then 0.4, then 1/2 = 0.5, then 70% = 0.7."},
{sec:"R",type:"multi",q:"Select EVERY value that equals one half.",
 opts:["50%","0.5","5/10","0.05","5%"],aMulti:[0,1,2],
 hint:"There is more than one.",
 expl:"50% = 0.5 and 5/10 = 0.5, so those three match. 0.05 is a twentieth and 5% is even smaller."},
{sec:"R",type:"in",q:"A jacket costs $60. It is reduced by 20%. What is the new price, in dollars?",
 hint:"Find 20% first, then subtract.",ans:48,
 expl:"20% of 60 = 12, and 60 − 12 = $48."},

/* challenge */
{lvl:2,sec:"R",type:"in",q:"15% of a number is 45. What is the number?",
 hint:"If 15% is 45, what is 1%?",ans:300,
 expl:"1% is 45 ÷ 15 = 3, so 100% is 3 × 100 = 300."},
{lvl:2,sec:"R",type:"order",q:"Order these from LARGEST to smallest.",
 items:["3/5","55%","0.58","2/3"],ansOrder:["2/3","3/5","0.58","55%"],
 hint:"Convert everything to decimals.",
 expl:"2/3 ≈ 0.667, 3/5 = 0.6, then 0.58, then 55% = 0.55."},
{lvl:2,sec:"R",type:"in",q:"A price rises from $40 to $50. What is the percentage increase?",
 hint:"Compare the change to the ORIGINAL price.",ans:25,
 expl:"The change is $10 on an original $40. 10/40 = 0.25 = 25%."},
{lvl:2,sec:"R",type:"multi",q:"A shirt is $20 after a 50% discount. Select EVERY true statement.",
 opts:["The original price was $40","The discount was $20","The original price was $30","The discount was $10"],
 aMulti:[0,1],
 expl:"If $20 is half the original, the original was $40 and the discount was the other $20."},

/* boss */
{lvl:3,sec:"R",type:"in",q:"A jacket is reduced by 20%, then by a further 10% off the new price. What is the total percentage off the ORIGINAL price?",
 hint:"Try it with $100. The two discounts do not simply add.",ans:28,
 expl:"Take $100: after 20% off it is $80. Then 10% off $80 is $8, leaving $72. That is $28 off the original, so 28% — not 30%."},
{lvl:3,sec:"R",type:"in",q:"After a 25% increase, a price is $75. What was the original price, in dollars?",
 hint:"The new price is 125% of the original.",ans:60,
 expl:"$75 is 125% of the original, so 1% is 75 ÷ 125 = 0.6, and 100% is $60."},
{lvl:3,sec:"R",type:"order",q:"Order these price changes from BIGGEST drop to smallest.",
 items:["$80 → $60","$50 → $40","$30 → $27","$20 → $19"],
 ansOrder:["$80 → $60","$50 → $40","$30 → $27","$20 → $19"],
 hint:"Work out each change as a percentage of its starting price.",
 expl:"As percentages: 20/80 = 25%, 10/50 = 20%, 3/30 = 10%, 1/20 = 5%."}
];
