/* Standards alignment (spec 8.3, 13.1).

   Every core topic maps to the Common Core State Standards for Mathematics
   cluster or standard it addresses. Advanced topics sit beyond grade-level
   standards by design; each is tagged with the CCSS domain it extends and
   the competition strand it serves, so a teacher can still see where it
   belongs. Codes follow the official notation (e.g. 3.NF.A.1). */

export const STANDARDS = {
  catalogue: {
    CCSS: "Common Core State Standards for Mathematics",
    ENRICH: "Enrichment beyond grade-level standards (competition preparation)"
  },
  strands: {
    NT: "Number theory", CB: "Combinatorics", AL: "Algebra extension",
    GE: "Geometry extension", PS: "Probability & statistics extension",
    LG: "Logic & strategy", PR: "Proof & reasoning"
  }
};

/* topic id -> { ccss: [...codes], strand?: "NT"|... } */
export const TOPIC_STANDARDS = {
  /* ---- Kindergarten ---- */
  "k-count":     { ccss: ["K.CC.A.1", "K.CC.A.2"] },
  "k-countback": { ccss: ["K.CC.A.2"] },
  "k-ordinal":   { ccss: ["K.CC.B.4"] },
  "k-add10":     { ccss: ["K.OA.A.1", "K.OA.A.2"] },
  "k-sub10":     { ccss: ["K.OA.A.1", "K.OA.A.2"] },
  "k-compose":   { ccss: ["K.OA.A.3", "K.OA.A.4"] },
  "k-2d":        { ccss: ["K.G.A.2", "K.G.B.4"] },
  "k-3d":        { ccss: ["K.G.A.3", "K.G.B.4"] },
  "k-combine":   { ccss: ["K.G.B.6"] },
  "k-compare":   { ccss: ["K.MD.A.1", "K.MD.A.2"] },
  "k-sort":      { ccss: ["K.MD.B.3"] },
  "k-picgraph":  { ccss: ["K.MD.B.3"] },
  "k-patterns":  { ccss: ["K.OA.A.3"], note: "pattern work supports K.OA" },
  "k-logic":     { ccss: ["MP.1", "MP.3"] },
  "k-evenodd":   { ccss: ["2.OA.C.3"], strand: "NT" },
  "k-skip":      { ccss: ["2.NBT.A.2"], strand: "NT" },
  "k-half":      { ccss: ["1.G.A.3"], strand: "NT" },
  "k-symmetry":  { ccss: ["4.G.A.3"], strand: "GE" },
  "k-blocks":    { ccss: ["K.G.B.6"], strand: "GE" },
  "k-turns":     { ccss: ["8.G.A.1"], strand: "GE" },
  "k-combos":    { ccss: ["K.CC.B.5"], strand: "CB" },
  "k-trees":     { ccss: ["7.SP.C.8"], strand: "CB" },
  "k-games":     { ccss: ["MP.1", "MP.7"], strand: "LG" },

  /* ---- Grade 1 ---- */
  "g1-add20":    { ccss: ["1.OA.C.6"] },
  "g1-sub20":    { ccss: ["1.OA.C.6", "1.OA.B.4"] },
  "g1-equals":   { ccss: ["1.OA.D.7"] },
  "g1-wordprob": { ccss: ["1.OA.A.1", "1.OA.D.8"] },
  "g1-props":    { ccss: ["1.OA.B.3"] },
  "g1-tensones": { ccss: ["1.NBT.B.2"] },
  "g1-compare2": { ccss: ["1.NBT.B.3"] },
  "g1-add100":   { ccss: ["1.NBT.C.4", "1.NBT.C.6"] },
  "g1-tenmore":  { ccss: ["1.NBT.C.5"] },
  "g1-length":   { ccss: ["1.MD.A.1", "1.MD.A.2"] },
  "g1-time":     { ccss: ["1.MD.B.3"] },
  "g1-graphs":   { ccss: ["1.MD.C.4"] },
  "g1-coins":    { ccss: ["2.MD.C.8"], note: "coins are introduced early here" },
  "g1-attrib":   { ccss: ["1.G.A.1"] },
  "g1-compose":  { ccss: ["1.G.A.2"] },
  "g1-shares":   { ccss: ["1.G.A.3"] },
  "g1-evenodd":  { ccss: ["2.OA.C.3"], strand: "NT" },
  "g1-factors":  { ccss: ["4.OA.B.4"], strand: "NT" },
  "g1-div25":    { ccss: ["4.OA.B.4"], strand: "NT" },
  "g1-machines": { ccss: ["4.OA.C.5"], strand: "AL" },
  "g1-growing":  { ccss: ["4.OA.C.5"], strand: "AL" },
  "g1-grid":     { ccss: ["MP.1", "MP.3"], strand: "LG" },
  "g1-deduce":   { ccss: ["MP.3"], strand: "PR" },
  "g1-twostep":  { ccss: ["2.OA.A.1"], strand: "LG" },
  "g1-arrange":  { ccss: ["7.SP.C.8"], strand: "CB" },
  "g1-choose":   { ccss: ["7.SP.C.8"], strand: "CB" },

  /* ---- Grade 2 ---- */
  "g2-fluency":  { ccss: ["2.OA.B.2"] },
  "g2-add100":   { ccss: ["2.NBT.B.5", "2.OA.A.1"] },
  "g2-equalgrp": { ccss: ["2.OA.C.4"] },
  "g2-arrays":   { ccss: ["2.OA.C.4"] },
  "g2-place1000":{ ccss: ["2.NBT.A.1", "2.NBT.A.3"] },
  "g2-compare3": { ccss: ["2.NBT.A.4"] },
  "g2-add1000":  { ccss: ["2.NBT.B.7"] },
  "g2-mental":   { ccss: ["2.NBT.B.8"] },
  "g2-rulers":   { ccss: ["2.MD.A.1"] },
  "g2-estimate": { ccss: ["2.MD.A.3"] },
  "g2-time5":    { ccss: ["2.MD.C.7"] },
  "g2-money":    { ccss: ["2.MD.C.8"] },
  "g2-lineplot": { ccss: ["2.MD.D.9"] },
  "g2-polygons": { ccss: ["2.G.A.1"] },
  "g2-rowcol":   { ccss: ["2.G.A.2"] },
  "g2-thirds":   { ccss: ["2.G.A.3"] },
  "g2-prime20":  { ccss: ["4.OA.B.4"], strand: "NT" },
  "g2-divrules": { ccss: ["4.OA.B.4"], strand: "NT" },
  "g2-gcf":      { ccss: ["6.NS.B.4"], strand: "NT" },
  "g2-repeated": { ccss: ["3.OA.A.1"], strand: "AL" },
  "g2-sharing":  { ccss: ["3.OA.A.2"], strand: "AL" },
  "g2-multprob": { ccss: ["3.OA.A.3"], strand: "AL" },
  "g2-missing":  { ccss: ["3.OA.A.4"], strand: "AL" },
  "g2-symbols":  { ccss: ["3.OA.D.8"], strand: "AL" },
  "g2-rule":     { ccss: ["4.OA.C.5"], strand: "AL" },
  "g2-trees":    { ccss: ["7.SP.C.8"], strand: "CB" },
  "g2-perm4":    { ccss: ["7.SP.C.8"], strand: "CB" },
  "g2-permcomb": { ccss: ["7.SP.C.8"], strand: "CB" },
  "g2-perimeter":{ ccss: ["3.MD.D.8"], strand: "GE" },
  "g2-symmetry": { ccss: ["4.G.A.3"], strand: "GE" },
  "g2-tangram":  { ccss: ["2.G.A.1"], strand: "GE" },

  /* ---- Grade 3 ---- */
  "g3-mult":     { ccss: ["3.OA.A.1", "3.OA.C.7"] },
  "g3-div":      { ccss: ["3.OA.A.2", "3.OA.B.6"] },
  "g3-multprops":{ ccss: ["3.OA.B.5"] },
  "g3-twostep":  { ccss: ["3.OA.D.8"] },
  "g3-patterns": { ccss: ["3.OA.D.9"] },
  "g3-round":    { ccss: ["3.NBT.A.1"] },
  "g3-add1000":  { ccss: ["3.NBT.A.2"] },
  "g3-mult10":   { ccss: ["3.NBT.A.3"] },
  "g3-fracnum":  { ccss: ["3.NF.A.1", "3.NF.A.2"] },
  "g3-fraccomp": { ccss: ["3.NF.A.3.D"] },
  "g3-fraceq":   { ccss: ["3.NF.A.3.A", "3.NF.A.3.B"] },
  "g3-wholefrac":{ ccss: ["3.NF.A.3.C"] },
  "g3-timemin":  { ccss: ["3.MD.A.1"] },
  "g3-volmass":  { ccss: ["3.MD.A.2"] },
  "g3-scaled":   { ccss: ["3.MD.B.3"] },
  "g3-area":     { ccss: ["3.MD.C.5", "3.MD.C.7"] },
  "g3-perimeter":{ ccss: ["3.MD.D.8"] },
  "g3-quads":    { ccss: ["3.G.A.1"] },
  "g3-equalarea":{ ccss: ["3.G.A.2"] },
  "g3-areaperim":{ ccss: ["3.MD.D.8"] },
  "g3-primefact":{ ccss: ["4.OA.B.4"], strand: "NT" },
  "g3-divrules": { ccss: ["4.OA.B.4"], strand: "NT" },
  "g3-lcm":      { ccss: ["6.NS.B.4"], strand: "NT" },
  "g3-gcdlcm":   { ccss: ["6.NS.B.4"], strand: "NT" },
  "g3-fracadd":  { ccss: ["4.NF.B.3"], strand: "AL" },
  "g3-fracmultw":{ ccss: ["4.NF.B.4"], strand: "AL" },
  "g3-benchmark":{ ccss: ["4.NF.A.2"], strand: "AL" },
  "g3-simpleeq": { ccss: ["6.EE.B.5"], strand: "AL" },
  "g3-varpat":   { ccss: ["5.OA.B.3"], strand: "AL" },
  "g3-evaluate": { ccss: ["6.EE.A.2"], strand: "AL" },
  "g3-syslist":  { ccss: ["7.SP.C.8"], strand: "CB" },
  "g3-multprin": { ccss: ["7.SP.C.8"], strand: "CB" },
  "g3-composite":{ ccss: ["3.MD.C.7.D"], strand: "GE" },
  "g3-volpack":  { ccss: ["5.MD.C.4"], strand: "GE" },
  "g3-angles":   { ccss: ["4.G.A.1"], strand: "GE" },
  "g3-lines":    { ccss: ["4.G.A.1"], strand: "GE" },

  /* ---- Grade 4 ---- */
  "g4-multcomp": { ccss: ["4.OA.A.1", "4.OA.A.2"] },
  "g4-multistep":{ ccss: ["4.OA.A.3"] },
  "g4-factorpair":{ ccss: ["4.OA.B.4"] },
  "g4-seq":      { ccss: ["4.OA.C.5"] },
  "g4-placemil": { ccss: ["4.NBT.A.1", "4.NBT.A.2"] },
  "g4-multidig": { ccss: ["4.NBT.B.5"] },
  "g4-divide":   { ccss: ["4.NBT.B.6"] },
  "g4-fracadd":  { ccss: ["4.NF.B.3"] },
  "g4-mixed":    { ccss: ["4.NF.B.3.C"] },
  "g4-fracmultw":{ ccss: ["4.NF.B.4"] },
  "g4-decnot":   { ccss: ["4.NF.C.6"] },
  "g4-deccomp":  { ccss: ["4.NF.C.7"] },
  "g4-units":    { ccss: ["4.MD.A.1", "4.MD.A.2"] },
  "g4-areaform": { ccss: ["4.MD.A.3"] },
  "g4-lineplot": { ccss: ["4.MD.B.4"] },
  "g4-protract": { ccss: ["4.MD.C.5", "4.MD.C.6"] },
  "g4-linesrays":{ ccss: ["4.G.A.1"] },
  "g4-classify": { ccss: ["4.G.A.2"] },
  "g4-symmetry": { ccss: ["4.G.A.3"] },
  "g4-primefact":{ ccss: ["6.EE.A.1"], strand: "NT" },
  "g4-divrules": { ccss: ["4.OA.B.4"], strand: "NT" },
  "g4-clockmod": { ccss: ["6.NS.B.4"], strand: "NT" },
  "g4-euclid":   { ccss: ["6.NS.B.4"], strand: "NT" },
  "g4-evalexpr": { ccss: ["5.OA.A.1"], strand: "AL" },
  "g4-liketerms":{ ccss: ["6.EE.A.3"], strand: "AL" },
  "g4-onestep":  { ccss: ["6.EE.B.7"], strand: "AL" },
  "g4-inequal":  { ccss: ["6.EE.B.8"], strand: "AL" },
  "g4-writeeq":  { ccss: ["6.EE.B.6"], strand: "AL" },
  "g4-factorial":{ ccss: ["7.SP.C.8"], strand: "CB" },
  "g4-combin":   { ccss: ["7.SP.C.8"], strand: "CB" },
  "g4-paths":    { ccss: ["7.SP.C.8"], strand: "CB" },
  "g4-starsbars":{ ccss: ["7.SP.C.8"], strand: "CB" },
  "g4-tri-area": { ccss: ["6.G.A.1"], strand: "GE" },
  "g4-para-area":{ ccss: ["6.G.A.1"], strand: "GE" },
  "g4-circle":   { ccss: ["7.G.B.4"], strand: "GE" },
  "g4-nets":     { ccss: ["6.G.A.4"], strand: "GE" },
  "g4-volprism": { ccss: ["5.MD.C.5"], strand: "GE" },
  "g4-exptheo":  { ccss: ["7.SP.C.6"], strand: "PS" },
  "g4-simple":   { ccss: ["7.SP.C.5"], strand: "PS" },
  "g4-compl":    { ccss: ["7.SP.C.7"], strand: "PS" },

  /* ---- Grade 5 ---- */
  "g5-express":  { ccss: ["5.OA.A.1", "5.OA.A.2"] },
  "g5-patterns": { ccss: ["5.OA.B.3"] },
  "g5-thousandth":{ ccss: ["5.NBT.A.3"] },
  "g5-decops":   { ccss: ["5.NBT.B.7"] },
  "g5-twodigit": { ccss: ["5.NBT.B.6"] },
  "g5-unlike":   { ccss: ["5.NF.A.1"] },
  "g5-fracmult": { ccss: ["5.NF.B.4"] },
  "g5-fracdiv":  { ccss: ["5.NF.B.7"] },
  "g5-fracword": { ccss: ["5.NF.A.2", "5.NF.B.6"] },
  "g5-convert":  { ccss: ["5.MD.A.1"] },
  "g5-lineplot": { ccss: ["5.MD.B.2"] },
  "g5-volume":   { ccss: ["5.MD.C.3", "5.MD.C.5"] },
  "g5-coord":    { ccss: ["5.G.A.1", "5.G.A.2"] },
  "g5-hierarchy":{ ccss: ["5.G.B.3", "5.G.B.4"] },
  "g5-modarith": { ccss: ["6.NS.B.4"], strand: "NT" },
  "g5-congru":   { ccss: ["6.NS.B.4"], strand: "NT" },
  "g5-fermat":   { ccss: ["8.EE.A.1"], strand: "NT" },
  "g5-diophant": { ccss: ["8.EE.C.8"], strand: "NT" },
  "g5-bases":    { ccss: ["5.NBT.A.1"], strand: "NT" },
  "g5-multistep":{ ccss: ["8.EE.C.7"], strand: "AL" },
  "g5-inequal":  { ccss: ["6.EE.B.8"], strand: "AL" },
  "g5-rateeq":   { ccss: ["7.RP.A.3"], strand: "AL" },
  "g5-formulas": { ccss: ["A-CED.A.4"], strand: "AL" },
  "g5-functions":{ ccss: ["8.F.A.1"], strand: "AL" },
  "g5-pythag":   { ccss: ["8.G.B.7"], strand: "GE" },
  "g5-distance": { ccss: ["8.G.B.8"], strand: "GE" },
  "g5-angletri": { ccss: ["8.G.A.5"], strand: "GE" },
  "g5-circarea": { ccss: ["7.G.B.4"], strand: "GE" },
  "g5-cylinder": { ccss: ["8.G.C.9"], strand: "GE" },
  "g5-permrep":  { ccss: ["7.SP.C.8"], strand: "CB" },
  "g5-combrep":  { ccss: ["7.SP.C.8"], strand: "CB" },
  "g5-subsets":  { ccss: ["7.SP.C.8"], strand: "CB" },
  "g5-inclexcl": { ccss: ["7.SP.C.8"], strand: "CB" },
  "g5-pascal":   { ccss: ["7.SP.C.8"], strand: "CB" },
  "g5-compound": { ccss: ["7.SP.C.8"], strand: "PS" },
  "g5-expected": { ccss: ["S-MD.A.2"], strand: "PS" },
  "g5-geoprob":  { ccss: ["7.SP.C.7"], strand: "PS" },
  "g5-condition":{ ccss: ["S-CP.A.3"], strand: "PS" },

  /* ---- Grade 6 ---- */
  "g6-ratios":   { ccss: ["6.RP.A.1", "6.RP.A.2"] },
  "g6-percent":  { ccss: ["6.RP.A.3.C"] },
  "g6-unitconv": { ccss: ["6.RP.A.3.D"] },
  "g6-nscoord":  { ccss: ["6.NS.C.6", "6.NS.C.8"] },
  "g6-fracdiv":  { ccss: ["6.NS.A.1"] },
  "g6-decimals": { ccss: ["6.NS.B.3"] },
  "g6-exprexp":  { ccss: ["6.EE.A.1"] },
  "g6-equivexpr":{ ccss: ["6.EE.A.3", "6.EE.A.4"] },
  "g6-onevar":   { ccss: ["6.EE.B.7", "6.EE.B.8"] },
  "g6-relation": { ccss: ["6.EE.C.9"] },
  "g6-polyarea": { ccss: ["6.G.A.1"] },
  "g6-volfrac":  { ccss: ["6.G.A.2"] },
  "g6-coordpoly":{ ccss: ["6.G.A.3"] },
  "g6-netsurf":  { ccss: ["6.G.A.4"] },
  "g6-statq":    { ccss: ["6.SP.A.1"] },
  "g6-centervar":{ ccss: ["6.SP.A.2", "6.SP.B.5"] },
  "g6-displays": { ccss: ["6.SP.B.4"] },
  "g6-modexp":   { ccss: ["8.EE.A.1"], strand: "NT" },
  "g6-crt":      { ccss: ["6.NS.B.4"], strand: "NT" },
  "g6-diophant": { ccss: ["8.EE.C.8"], strand: "NT" },
  "g6-basearith":{ ccss: ["5.NBT.A.1"], strand: "NT" },
  "g6-contfrac": { ccss: ["7.NS.A.2"], strand: "NT" },
  "g6-perfect":  { ccss: ["4.OA.B.4"], strand: "NT" },
  "g6-bothsides":{ ccss: ["8.EE.C.7"], strand: "AL" },
  "g6-compound": { ccss: ["A-REI.B.3"], strand: "AL" },
  "g6-literal":  { ccss: ["A-CED.A.4"], strand: "AL" },
  "g6-slope":    { ccss: ["8.EE.B.6"], strand: "AL" },
  "g6-systems":  { ccss: ["8.EE.C.8"], strand: "AL" },
  "g6-pythag":   { ccss: ["8.G.B.6", "8.G.B.7"], strand: "GE" },
  "g6-specialtri":{ ccss: ["G-SRT.C.8"], strand: "GE" },
  "g6-apothem":  { ccss: ["G-MG.A.1"], strand: "GE" },
  "g6-solids":   { ccss: ["8.G.C.9"], strand: "GE" },
  "g6-transvers":{ ccss: ["8.G.A.5"], strand: "GE" },
  "g6-transform":{ ccss: ["8.G.A.3"], strand: "GE" },
  "g6-permcomb": { ccss: ["S-CP.B.9"], strand: "CB" },
  "g6-binomial": { ccss: ["A-APR.C.5"], strand: "CB" },
  "g6-symmetry": { ccss: ["S-CP.B.9"], strand: "CB" },
  "g6-recursion":{ ccss: ["F-IF.A.3"], strand: "CB" },
  "g6-catalan":  { ccss: ["F-IF.A.3"], strand: "CB" },
  "g6-replace":  { ccss: ["7.SP.C.8"], strand: "PS" },
  "g6-bayes":    { ccss: ["S-CP.B.6"], strand: "PS" },
  "g6-randvar":  { ccss: ["S-MD.A.1", "S-MD.A.2"], strand: "PS" },
  "g6-distrib":  { ccss: ["S-MD.A.3"], strand: "PS" },

  /* ---- Grade 7 ---- */
  "g7-unitfrac": { ccss: ["7.RP.A.1"] },
  "g7-propor":   { ccss: ["7.RP.A.2"] },
  "g7-percentapp":{ ccss: ["7.RP.A.3"] },
  "g7-ratops":   { ccss: ["7.NS.A.1", "7.NS.A.2"] },
  "g7-todecimal":{ ccss: ["7.NS.A.2.D"] },
  "g7-expand":   { ccss: ["7.EE.A.1"] },
  "g7-multistep":{ ccss: ["7.EE.B.3"] },
  "g7-eqineq":   { ccss: ["7.EE.B.4"] },
  "g7-scaledraw":{ ccss: ["7.G.A.1"] },
  "g7-construct":{ ccss: ["7.G.A.2"] },
  "g7-circles":  { ccss: ["7.G.B.4"] },
  "g7-anglerel": { ccss: ["7.G.B.5"] },
  "g7-solids":   { ccss: ["7.G.B.6"] },
  "g7-sampling": { ccss: ["7.SP.A.1", "7.SP.A.2"] },
  "g7-probmodel":{ ccss: ["7.SP.C.7"] },
  "g7-compound": { ccss: ["7.SP.C.8"] },
  "g7-modpow":   { ccss: ["8.EE.A.1"], strand: "NT" },
  "g7-euler":    { ccss: ["8.EE.A.1"], strand: "NT" },
  "g7-triples":  { ccss: ["8.G.B.6"], strand: "NT" },
  "g7-contfrac": { ccss: ["8.NS.A.2"], strand: "NT" },
  "g7-rsa":      { ccss: ["8.EE.A.1"], strand: "NT" },
  "g7-absval":   { ccss: ["A-REI.B.3"], strand: "AL" },
  "g7-systems":  { ccss: ["A-REI.C.6"], strand: "AL" },
  "g7-factorquad":{ ccss: ["A-SSE.B.3"], strand: "AL" },
  "g7-solvequad":{ ccss: ["A-REI.B.4"], strand: "AL" },
  "g7-graphquad":{ ccss: ["F-IF.C.7"], strand: "AL" },
  "g7-exponen":  { ccss: ["F-LE.A.1"], strand: "AL" },
  "g7-proofs":   { ccss: ["G-CO.B.8", "G-SRT.A.3"], strand: "PR" },
  "g7-centers":  { ccss: ["G-C.A.3"], strand: "GE" },
  "g7-circthm":  { ccss: ["G-C.A.2"], strand: "GE" },
  "g7-heron":    { ccss: ["G-SRT.D.9"], strand: "GE" },
  "g7-frustum":  { ccss: ["G-GMD.A.3"], strand: "GE" },
  "g7-coordgeo": { ccss: ["G-GPE.B.4"], strand: "GE" },
  "g7-inclexcl3":{ ccss: ["S-CP.B.7"], strand: "CB" },
  "g7-genfunc":  { ccss: ["A-APR.C.5"], strand: "CB" },
  "g7-partitions":{ ccss: ["S-CP.B.9"], strand: "CB" },
  "g7-graphtheo":{ ccss: ["MP.4"], strand: "CB" },
  "g7-ramsey":   { ccss: ["MP.3"], strand: "CB" },
  "g7-bayes":    { ccss: ["S-CP.B.6"], strand: "PS" },
  "g7-joint":    { ccss: ["S-CP.A.4"], strand: "PS" },
  "g7-variance": { ccss: ["S-MD.A.2"], strand: "PS" },
  "g7-distrib":  { ccss: ["S-MD.A.3"], strand: "PS" },
  "g7-markov":   { ccss: ["S-MD.B.5"], strand: "PS" },

  /* ---- Grade 8 ---- */
  "g8-irrational":{ ccss: ["8.NS.A.1", "8.NS.A.2"] },
  "g8-radicals": { ccss: ["8.EE.A.1", "8.EE.A.2"] },
  "g8-scinot":   { ccss: ["8.EE.A.3", "8.EE.A.4"] },
  "g8-propgraph":{ ccss: ["8.EE.B.5"] },
  "g8-linear":   { ccss: ["8.EE.C.7"] },
  "g8-systems":  { ccss: ["8.EE.C.8"] },
  "g8-funcdef":  { ccss: ["8.F.A.1"] },
  "g8-funccomp": { ccss: ["8.F.A.2"] },
  "g8-funcmodel":{ ccss: ["8.F.B.4"] },
  "g8-funcgraph":{ ccss: ["8.F.B.5"] },
  "g8-transform":{ ccss: ["8.G.A.1", "8.G.A.2"] },
  "g8-dilations":{ ccss: ["8.G.A.3", "8.G.A.4"] },
  "g8-angleAA":  { ccss: ["8.G.A.5"] },
  "g8-pythag":   { ccss: ["8.G.B.6", "8.G.B.7", "8.G.B.8"] },
  "g8-solids":   { ccss: ["8.G.C.9"] },
  "g8-scatter":  { ccss: ["8.SP.A.1"] },
  "g8-fitline":  { ccss: ["8.SP.A.2", "8.SP.A.3"] },
  "g8-twoway":   { ccss: ["8.SP.A.4"] },
  "g8-modfull":  { ccss: ["6.NS.B.4"], strand: "NT" },
  "g8-quadres":  { ccss: ["8.EE.A.2"], strand: "NT" },
  "g8-pell":     { ccss: ["A-REI.C.7"], strand: "NT" },
  "g8-flt":      { ccss: ["MP.3"], strand: "NT" },
  "g8-primality":{ ccss: ["8.EE.A.1"], strand: "NT" },
  "g8-rsa":      { ccss: ["8.EE.A.1"], strand: "NT" },
  "g8-polynom":  { ccss: ["A-APR.B.2", "A-APR.B.3"], strand: "AL" },
  "g8-rational": { ccss: ["A-APR.D.6"], strand: "AL" },
  "g8-radicaleq":{ ccss: ["A-REI.A.2"], strand: "AL" },
  "g8-vieta":    { ccss: ["A-REI.B.4"], strand: "AL" },
  "g8-nonlinear":{ ccss: ["A-REI.C.7"], strand: "AL" },
  "g8-inequal":  { ccss: ["A-REI.D.11"], strand: "AL" },
  "g8-series":   { ccss: ["F-BF.A.2"], strand: "AL" },
  "g8-complex":  { ccss: ["N-CN.A.1", "N-CN.A.2"], strand: "AL" },
  "g8-ceva":     { ccss: ["G-SRT.B.5"], strand: "GE" },
  "g8-power":    { ccss: ["G-C.A.2", "G-C.A.3"], strand: "GE" },
  "g8-trig":     { ccss: ["G-SRT.C.8", "G-SRT.D.10"], strand: "GE" },
  "g8-euler":    { ccss: ["G-GMD.B.4"], strand: "GE" },
  "g8-vectors":  { ccss: ["N-VM.A.1", "N-VM.B.4"], strand: "GE" },
  "g8-noneuclid":{ ccss: ["G-CO.A.1"], strand: "GE" },
  "g8-genfunc":  { ccss: ["F-BF.A.2"], strand: "CB" },
  "g8-polya":    { ccss: ["S-CP.B.9"], strand: "CB" },
  "g8-planar":   { ccss: ["MP.4"], strand: "CB" },
  "g8-ramsey":   { ccss: ["MP.3"], strand: "CB" },
  "g8-designs":  { ccss: ["MP.7"], strand: "CB" },
  "g8-pgf":      { ccss: ["S-MD.A.3"], strand: "PS" },
  "g8-randwalk": { ccss: ["S-MD.B.5"], strand: "PS" },
  "g8-continuous":{ ccss: ["S-ID.A.4"], strand: "PS" },
  "g8-clt":      { ccss: ["S-IC.B.4"], strand: "PS" },
  "g8-entropy":  { ccss: ["S-MD.A.2"], strand: "PS" }
};

/* Public form for one topic. */
export function standardsFor(topicId) {
  const s = TOPIC_STANDARDS[topicId];
  if (!s) return null;
  return {
    framework: s.strand ? "ENRICH" : "CCSS",
    codes: s.ccss,
    strand: s.strand ? { code: s.strand, name: STANDARDS.strands[s.strand] } : null,
    note: s.note || null
  };
}

/* Reverse index: CCSS code -> topic ids, for a teacher planning by standard. */
export function topicsForStandard(code) {
  return Object.entries(TOPIC_STANDARDS).filter(([, s]) => s.ccss.includes(code)).map(([id]) => id);
}
